Repository macports/macports-ports, pull requests merged in 2018-07, with the labels that each got.

#2119 py-pyscard: update to 1.9.7
  python/py-pyscard/Portfile
Labels: maintainer, maintainer: open, type: update

#2117 tomcat-native: update to 1.2.17
  java/tomcat-native/Portfile
Labels: maintainer, maintainer: open, type: bugfix, type: update

#2121 py-pbr: update to 4.0.4
  python/py-pbr/Portfile
Labels: maintainer: none, type: update

#2122 swi-prolog-devel: update to 7.7.17
  lang/swi-prolog-devel/Portfile
Labels: maintainer, type: update

#2124 OpenBLAS: update to 0.3.1.
  math/OpenBLAS/Portfile
  math/OpenBLAS/files/patch-libnoarch.release.diff
Labels: by: member, maintainer, maintainer: open, type: enhancement, type: update

#2130 py-functools32: fix livecheck, add size to checksums
  python/py-functools32/Portfile
Labels: maintainer: none, type: enhancement

#2132 Update to fricas 1.3.4
  math/fricas/Portfile
  math/fricas/files/use-macports-gmp.patch
Labels: maintainer

#2135 httpie, http-prompt: use Python 3.6
  net/http-prompt/Portfile
  net/httpie/Portfile
Labels: by: member, maintainer: requires approval, type: enhancement

#2129 py-backports-functools_lru_cache: update to 1.5
  python/py-backports-functools_lru_cache/Portfile
Labels: maintainer: none, type: update

#2128 py-yapf: update to 0.22.0
  python/py-yapf/Portfile
Labels: maintainer: open, type: update

#2137 crystal: update to 0.25.1
  lang/crystal/Portfile
Labels: maintainer, maintainer: open, type: update

#2139 py-dill: update to 0.2.8.2, add py37
  python/py-dill/Portfile
Labels: maintainer: open, type: update

#2134 php: Add php73 version 7.3.0alpha2
  lang/php/Portfile
  lang/php/files/patch-php73-ext-gd-config.m4.diff
  lang/php/files/patch-php73-iODBC.diff
  lang/php/files/patch-php73-sapi-fpm-php-fpm.conf.in.diff
  lang/php/files/patch-php73-scripts-php-config.in.diff
  lang/php/files/patch-php73-unixODBC.diff
  lang/php/files/php73
Labels: by: member, maintainer

#2127 plumed: update to 2.4.2
  science/plumed/Portfile
Labels: maintainer, maintainer: open, type: update

#2141 py-aiorpcX: new port, version 0.5.6
  python/py-aiorpcX/Portfile
Labels: type: enhancement, type: submission

#2142 py-six: added py37 subport
  python/py-six/Portfile
Labels: maintainer: open, type: enhancement

#2147 shards: change category to devel
  devel/shards/Portfile
Labels: maintainer, maintainer: open, type: enhancement

#2143 py-poppler-qt5: fix use of qt5 PortGroup
  python/py-poppler-qt5/Portfile
Labels: maintainer, maintainer: open, type: bugfix

#2145 p5-app-cli: update to 0.50, add depends_test
  perl/p5-app-cli/Portfile
Labels: maintainer: none, type: enhancement, type: update

#2146 p5-www-form-urlencoded-xs: update to 0.25
  perl/p5-www-form-urlencoded-xs/Portfile
Labels: maintainer: open, type: update

#2149 p5-file-find-object-rule: update to 0.0309, minor improvements
  perl/p5-file-find-object-rule/Portfile
Labels: maintainer: none, type: enhancement, type: update

#2150 flyway: update to 5.1.4
  java/flyway/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#2151 p5-event-rpc: update to 1.10, move `supported_archs noarch` to outside `if`
  perl/p5-event-rpc/Portfile
Labels: maintainer: none, type: enhancement, type: update

#2153 p5-mac-errors: update to 1.192, minor improvements
  perl/p5-mac-errors/Portfile
Labels: maintainer: none, type: enhancement, type: update

#2152 py-subprocess32: update to 3.5.2
  python/py-subprocess32/Portfile
Labels: maintainer: open, type: update

#2155 py-tox: update to 3.0.0
  python/py-tox/Portfile
Labels: maintainer: open, type: update

#2095 graphene: fix detection of SSE
  graphics/graphene/Portfile
  graphics/graphene/files/patch-meson.build.diff
Labels: by: member, maintainer: open

#2159 tor-devel: update to 0.3.4.3-alpha
  security/tor-devel/Portfile
Labels: maintainer: none, type: update

#2138 meson: update to 0.47.0, use python 3.7
  devel/meson/Portfile
Labels: by: member, maintainer: none, type: update

#2144 Add optimizations variant to python{27,35,36,37}
  lang/python27/Portfile
  lang/python35/Portfile
  lang/python36/Portfile
  lang/python37/Portfile
Labels: maintainer: open, type: enhancement

#2099 update perl5 PortGroup livecheck.regex
  _resources/port1.0/group/perl5-1.0.tcl
Labels: type: bugfix, type: enhancement

#2157 qgis3: update to 3.2
  gis/qgis3/Portfile
Labels: maintainer: requires approval, type: enhancement, type: update

#2140 todotxt: Portfile fixes to bash_completion variant and config file regex
  office/todotxt/Portfile
Labels: maintainer: open, type: bugfix

#2156 Update git-latexdiff
  devel/git-latexdiff/Portfile
Labels: maintainer: open, type: enhancement

#2162 py-plyvel: fix multiple issues
  python/py-plyvel/Portfile
Labels: maintainer: open, type: bugfix

#2166 hugo: update to 0.43
  www/hugo/Portfile
Labels: maintainer, maintainer: open, type: update

#2167 py-cairo: update to 1.17.1, add py37
  python/py-cairo/Portfile
Labels: maintainer: none, type: update

#2163 amber: new port, version 0.8.0
  www/amber/Portfile
Labels: type: submission

#2169 py-alabaster: update to 0.7.11, add py37
  python/py-alabaster/Portfile
Labels: maintainer: none, type: update

#2164 py-kivy: update to version 1.10.1
  python/py-kivy/Portfile
Labels: maintainer: open, type: enhancement, type: update

#2174 swi-prolog-devel: update to 7.7.18
  lang/swi-prolog-devel/Portfile
Labels: maintainer, type: update

#2173 libsbmlsim: new port, version 1.4.0
  science/libsbmlsim/Portfile
Labels: type: enhancement, type: submission

#2175 py-kivy: Fix checksums and size
  python/py-kivy/Portfile
Labels: maintainer: open, type: bugfix

#2183 Use consistent maintainer designation for yan12125
  aqua/android-file-transfer-linux/Portfile
  devel/libfilezilla/Portfile
  editors/texstudio/Portfile
  net/dhcptest/Portfile
  python/logcat-color_select/Portfile
  python/py-asynctest/Portfile
  python/py-brotlipy/Portfile
  python/py-curl/Portfile
  python/py-editorconfig/Portfile
  python/py-flaky/Portfile
  python/py-h11/Portfile
  python/py-hpack/Portfile
  python/py-jsbeautifier/Portfile
  python/py-kaitaistruct/Portfile
  python/py-ldap3/Portfile
  python/py-logcat-color/Portfile
  python/py-mitmproxy/Portfile
  python/py-pytest-asyncio/Portfile
  python/py-urwid/Portfile
  python/py-wsproto/Portfile
  security/KeePassXC/Portfile
  www/FileZilla/Portfile
Labels: by: member, maintainer: requires approval

#2203 Add GitHub handle neurodroid to maintainers
  python/py-stfio/Portfile
  science/libbiosig/Portfile
  science/stimfit/Portfile
Labels: by: member, maintainer: requires approval

#2181 maxima: Revbump for sbcl 1.4.9
  lang/sbcl/Portfile
  math/maxima/Portfile
Labels: by: member, maintainer: open

#2186 Use consistent maintainer designation for breun
  devel/gdub/Portfile
  java/openjdk10/Portfile
  java/spring-boot-cli/Portfile
  lang/groovy/Portfile
  lang/kotlin/Portfile
Labels: by: member, maintainer: open

#2182 Use consistent maintainer designation for KubaO
  math/maxima/Portfile
  python/py-filterpy/Portfile
Labels: by: member, maintainer: open

#2177 py-filelock: new port, version 3.0.4
  python/py-filelock/Portfile
Labels: type: enhancement, type: submission

#2184 Add GitHub handle quentinmit to maintainers
  net/mosh/Portfile
  net/remctl/Portfile
Labels: by: member, maintainer: requires approval

#2178 py-backports-functools_lru_cache: fix activation issue
  python/py-backports-functools_lru_cache/Portfile
Labels: maintainer: none, type: bugfix

#2168 py-pylint: update to 1.9.2
  python/py-pylint/Portfile
Labels: maintainer: open, type: update

#2208 hugo: update to 0.44
  www/hugo/Portfile
Labels: maintainer, maintainer: open, type: update

#2209 p5-tcl-ptk: update to 0.93, remove upstreamed patches, remove tix dependency
  perl/p5-tcl-ptk/Portfile
  perl/p5-tcl-ptk/files/patch-Makefile.PL.diff
  perl/p5-tcl-ptk/files/patch-Text.pm.diff
  perl/p5-tcl-ptk/files/patch-Widget.pm.diff
Labels: maintainer, maintainer: open, type: enhancement, type: update

#2210 gprolog: update to 1.4.5
  lang/gprolog/Portfile
  lang/gprolog/files/cflags.patch
  lang/gprolog/files/clang.patch
Labels: maintainer, type: update

#2213 p5-tcl: update to 1.12
  perl/p5-tcl/Portfile
Labels: maintainer: open, type: update

#2216 p5-devel-refcount: new port, version 0.10
  perl/p5-devel-refcount/Portfile
Labels: type: submission

#2217 tklib: tcllib dep, tests, SHA256/size
  devel/tklib/Portfile
Labels: maintainer: none, type: bugfix, type: enhancement

#2187 Use consistent maintainer designation for nano103
  net/3proxy/Portfile
  sysutils/gptfdisk/Portfile
Labels: by: member, maintainer: requires approval, maintainer: timeout

#2188 Add GitHub handle nottwo to maintainers
  perl/p5-json-xs/Portfile
Labels: by: member, maintainer: open

#2189 Add GitHub handle matteocorti to maintainers
  games/roll/Portfile
  perl/p5-file-slurp/Portfile
Labels: by: member, maintainer: requires approval, maintainer: timeout

#2191 Add GitHub handle Liontooth to maintainers
  multimedia/transcode/Portfile
Labels: by: member, maintainer: requires approval, maintainer: timeout

#2193 Update maintainer information for lloyd
  graphics/qiv/Portfile
  lang/librep/Portfile
  x11/rep-gtk/Portfile
  x11/sawfish/Portfile
Labels: by: member, maintainer: requires approval, maintainer: timeout

#2194 Add GitHub handle jpouellet to maintainers
  devel/git-cvs/Portfile
  python/py-rcsparse/Portfile
  security/signify/Portfile
Labels: by: member, maintainer: requires approval, maintainer: timeout

#2195 Add GitHub handle jpoliv to maintainers
  perl/p5-dancer-plugin-database/Portfile
  perl/p5-dancer/Portfile
  perl/p5-http-server-simple-psgi/Portfile
  perl/p5-io-interface/Portfile
  perl/p5-log-dispatch/Portfile
  perl/p5-log-log4perl/Portfile
  perl/p5-net-stomp/Portfile
  perl/p5-netpacket/Portfile
  perl/p5-pmtools/Portfile
  perl/p5-set-scalar/Portfile
Labels: by: member, maintainer: open, maintainer: timeout

#2196 Add GitHub handle aphor to maintainers
  net/haproxy/Portfile
  sysutils/salt/Portfile
Labels: by: member, maintainer: open, maintainer: timeout

#2197 Add GitHub handle freespace to maintainers
  graphics/libpano13/Portfile
  python/py-cherrypy/Portfile
Labels: by: member, maintainer: requires approval, maintainer: timeout

#2198 Use consistent maintainer designation for esafak
  python/py-agate-dbf/Portfile
  python/py-agate-excel/Portfile
  python/py-agate-sql/Portfile
  python/py-agate/Portfile
  python/py-awesome_slugify/Portfile
  python/py-csvkit/Portfile
  python/py-dbfread/Portfile
  python/py-isodate/Portfile
  python/py-leather/Portfile
  python/py-pytimeparse/Portfile
  python/py-slugify/Portfile
  python/py-unidecode/Portfile
  sysutils/sift/Portfile
Labels: maintainer: timeout

#2199 Add GitHub handle exg to maintainers
  x11/rxvt-unicode/Portfile
  x11/terminus-font/Portfile
Labels: by: member, maintainer: open

#2200 Add GitHub handle jokuha to maintainers
  science/eo/Portfile
  tex/bibutils/Portfile
  textproc/aspell/Portfile
Labels: maintainer: timeout

#2201 Add GitHub handle egull to maintainers
  science/ALPSMaxent/Portfile
Labels: by: member, maintainer: requires approval, maintainer: timeout

#2179 transcode: Don't override portfetch::assemble_url
  multimedia/transcode/Portfile
Labels: by: member, maintainer: requires approval, maintainer: timeout

#2218 groovy: update to 2.5.1
  lang/groovy/Portfile
Labels: maintainer, maintainer: open, type: update

#2219 gnuradio: update homepage following redirects
  science/gnuradio/Portfile
Labels: by: member, maintainer: requires approval, type: bugfix

#2180 auto-multiple-choice: Separate revision for each subport
  x11/auto-multiple-choice/Portfile
Labels: by: member, maintainer: open

#2133 revamp grep port due to 35915ffebe and adjust its dependents
  audio/tagtool/Portfile
  editors/MacVim/Portfile
  editors/poedit1/Portfile
  editors/vim/Portfile
  games/xmoto/Portfile
  math/gfm/Portfile
  math/libticables2/Portfile
  math/libticalcs2/Portfile
  math/libticonv/Portfile
  math/libtifiles2/Portfile
  math/tiemu3/Portfile
  math/tilp2/Portfile
  net/mcabber/Portfile
  science/liquid-dsp/Portfile
  security/openvas-client/Portfile
  security/openvas-libraries/Portfile
  security/openvas-plugins/Portfile
  shells/bash/Portfile
  sysutils/grep/Portfile
  sysutils/pwgen/Portfile
  textproc/dict/Portfile
  textproc/less/Portfile
Labels: maintainer: requires approval, type: bugfix, type: enhancement

#2221 py-asteval: add py37, enable test
  python/py-asteval/Portfile
Labels: maintainer, maintainer: open, type: enhancement

#2222 py-isort: add py37 subport
  python/py-isort/Portfile
Labels: maintainer, maintainer: open, type: enhancement

#2223 py-pypdf2: add py37 subport
  python/py-pypdf2/Portfile
Labels: maintainer, maintainer: open, type: enhancement

#2224 p5-tcl: update to 1.16, add p5-devel-refcount to depends_test
  perl/p5-tcl/Portfile
Labels: maintainer: open, type: enhancement, type: update

#2227 py-plyvel: add Python 3.7 support
  python/py-plyvel/Portfile
Labels: maintainer: open, type: enhancement

#2225 p5-tcl-tk: new port, version 1.12
  perl/p5-tcl-tk/Portfile
Labels: type: submission

#2212 py-virtualenv: update to 16.0.0
  python/py-graveyard/Portfile
  python/py-virtualenv/Portfile
  python/py-virtualenv/files/virtualenv26
  python/py-virtualenv/files/virtualenv33
Labels: maintainer: requires approval, maintainer: timeout, type: update

#2228 py-pycares: new port, version 2.3.0
  python/py-pycares/Portfile
Labels: type: enhancement, type: submission

#2230 minivmac-devel: Update to 36.00alpha-20180715
  emulators/minivmac-devel/Portfile
  emulators/minivmac-devel/files/README-binary-patchfiles.md
  emulators/minivmac-devel/files/configuration.patch
  emulators/minivmac-devel/files/configure
  emulators/minivmac-devel/files/echo-n.patch
  emulators/minivmac-devel/files/exit.patch
  emulators/minivmac-devel/files/newline.patch
  emulators/minivmac-devel/files/patch-Disk Tools.image.bsdiff
  emulators/minivmac-devel/files/patch-autquit7-1.3.1.dsk.bsdiff
  emulators/minivmac-devel/files/readalias.applescript
Labels: by: member, maintainer, type: update

#2232 kubectl: add co-maintainer
  sysutils/kubectl/Portfile
Labels: by: member, maintainer: open

#2231 p5-tcl-tk: remove test-for-tk in Makefile.PL
  perl/p5-tcl-tk/Portfile
  perl/p5-tcl-tk/files/patch-Makefile.PL.diff
Labels: maintainer, maintainer: open, type: bugfix

#2233 openjdk10: update to 10.0.2
  java/openjdk10/Portfile
Labels: maintainer, maintainer: open, type: update

#2234 kotlin: update to 1.2.51
  lang/kotlin/Portfile
Labels: maintainer, maintainer: open, type: update

#2241 py-tqdm: added py37 subport
  python/py-tqdm/Portfile
Labels: maintainer: open, type: enhancement

#2236 qpid-proton: update to version 0.24.0
  net/qpid-proton/Portfile
Labels: maintainer: open, type: update

#2240 py-scipy: added py37 subport
  python/py-scipy/Portfile
Labels: maintainer: open, type: enhancement

#2242 Add port olm
  devel/olm/Portfile
Labels: type: enhancement, type: submission

#2246 matrix-structs: Add port matrix-structs
  net/matrix-structs/Portfile
Labels: type: enhancement, type: submission

#2244 tweeny: Add port tweeny
  devel/tweeny/Portfile
Labels: type: enhancement, type: submission

#2251 py-greenlet: update to 0.4.14 for py37 compatibility
  python/py-greenlet/Portfile
Labels: by: member, maintainer: open, type: enhancement, type: update

#2254 olm: add cxx11 and cleanup portfile
  devel/olm/Portfile
Labels: maintainer, maintainer: open, type: enhancement

#2257 libsndfile +octave: drop the gsed dependency
  audio/libsndfile/Portfile
Labels: maintainer

#2255 py-neovim: update to 0.2.6 for py37 compatibility
  python/py-neovim/Portfile
Labels: by: member, maintainer: open, type: enhancement, type: update

#2258 php-zip: Get from PECL instead of bundled with PHP
  lang/php/Portfile
  php/php-zip/Portfile
Labels: by: member, maintainer, type: submission

#2259 php update 5.6.36 7.0.31 7.1.20 7.2.8 7.3.0alpha4
  lang/php/Portfile
  lang/php/files/patch-php73-ext-mbstring-config.m4.diff
Labels: by: member, maintainer

#2252 dict: drop needless dependencies
  textproc/dict/Portfile
Labels: maintainer: open, type: enhancement

#2256 py-Pillow: update to 5.2.0
  python/py-Pillow/Portfile
  python/py-Pillow/files/patch-setup-3.4.2.py.diff
Labels: maintainer: open, type: update

#2264 py-nmrglue: add py37 subport, enable tests
  python/py-nmrglue/Portfile
Labels: maintainer: open, type: enhancement

#2250 mtxclient: new portfile
  net/mtxclient/Portfile
Labels: type: enhancement, type: submission

#2260 iTerm2: update to 3.1.7
  aqua/iTerm2/Portfile
Labels: maintainer, type: update

#2266 hugo: update to 0.45
  www/hugo/Portfile
Labels: maintainer, maintainer: open, type: update

#1879 gimp2 fixes for quartz variant
  graphics/gimp2/Portfile
  graphics/gimp2/files/patch-quartz-32bit.diff
Labels: by: member, maintainer: requires approval

#2269 fftw-3: update 3.3.7->3.3.8
  math/fftw-3/Portfile
Labels: by: member, maintainer: requires approval

#2239 py-astropy: bumped to 3.0.3 for py>=35
  python/py-astropy/Portfile
Labels: maintainer: requires approval, type: enhancement

#2253 cctools: Add xcode variant that installs wrapper scripts around Xcode commands
  devel/cctools/Portfile
Labels: by: member, maintainer: open, type: enhancement

#2274 py-netaddr: add missing dependency
  python/py-netaddr/Portfile
  python/py-netaddr/files/patch-test_ieee_parsers.py.diff
Labels: maintainer: open, type: bugfix

#2271 autogen: Update to 5.18.14
  devel/autogen/Portfile
  devel/autogen/files/Werror.patch
  devel/autogen/files/patch-autogen-guile-2.2.diff
  devel/autogen/files/yosemite-libtool.patch
Labels: by: member, maintainer: none, type: update

#2278 astyle: change to nomaintainer
  devel/astyle/Portfile
Labels: by: member, maintainer, maintainer: open, type: enhancement

#2273 py-pip: update from 10.0.1 to 18.0
  python/py-pip/Portfile
Labels: maintainer: open

#2247 ld64: default to +ld64_xcode on Xcode9+
  devel/ld64/Portfile
Labels: by: member, maintainer: requires approval, maintainer: timeout

#2286 hugo: update to 0.45.1
  www/hugo/Portfile
Labels: maintainer, maintainer: open, type: update

#2277 clang-6.0: Restore missing O_CLOEXEC patchfile
  lang/llvm-6.0/files/2001-xray-Define-O_CLOEXEC-for-older-SDKs-that-don-t-have.patch
Labels: by: member, maintainer: requires approval, type: bugfix

#2165 boost: find library when using -flat_namespace
  devel/boost/Portfile
Labels: by: member, maintainer: open

#2284 stellarium: update to 0.18.1
  science/stellarium/Portfile
  science/stellarium/files/patch-CMakeLists.txt.diff
Labels: maintainer: open, type: update

#2263 cquery: update to v20180718
  devel/cquery/Portfile
Labels: by: member, maintainer, type: enhancement, type: update

#2272 py-dijitso: add missing dependencies
  python/py-dijitso/Portfile
Labels: by: member, maintainer: open

#2285 qbs: remove unnecessary patch file
  devel/qbs/Portfile
  devel/qbs/files/patch-headers.diff
Labels: by: member, maintainer: open

#2237 TOra: Fix build with clang-902.0.39.2 (Xcode 9.4.1)
  aqua/TOra/Portfile
  aqua/TOra/files/patch-src-toextract.cpp
  aqua/TOra/files/patch-src-toextract.h
  aqua/TOra/files/patch-src-toreport.cpp
Labels: maintainer: none, type: bugfix

#2289 clojure: Update to version 1.9.0
  lang/clojure/Portfile
  lang/clojure/files/.clj_completions
  lang/clojure/files/clj-rlwrap.sh
  lang/clojure/files/clj.sh
  lang/clojure/files/completions-contrib.clj
  lang/clojure/files/completions.clj
Labels: maintainer: none, type: enhancement, type: update

#2294 f3: update to 7.1
  sysutils/f3/Portfile
Labels: maintainer: none, type: enhancement, type: update

#2290 lmdbxx: Update to 0.9.14.1
  databases/lmdbxx/Portfile
Labels: type: enhancement, type: submission

#2291 borgbackup: update to 1.1.6, fix build issues
  sysutils/borgbackup/Portfile
  sysutils/borgbackup/files/patch-msgpack.diff
Labels: maintainer, type: bugfix, type: enhancement, type: update

#2283 eiffelstudio: update to version 18.07
  lang/eiffelstudio/Portfile
Labels: maintainer: requires approval, type: update

#2279 New port: packer
  sysutils/packer/Portfile
Labels: type: enhancement, type: submission

#2302 f3: fix maintainers line
  sysutils/f3/Portfile
Labels: maintainer, maintainer: open, type: bugfix

#2306 carthage: update to 0.30.1
  devel/carthage/Portfile
Labels: by: member, maintainer: open, type: update

#2307 py-poppler-qt4: require C++11
  python/py-poppler-qt4/Portfile
Labels: maintainer, maintainer: open, type: bugfix

#2267 qgis3: update to 3.2.1
  gis/qgis3/Portfile
Labels: maintainer: requires approval, maintainer: timeout, type: bugfix, type: update

#2304 tesseract: require C++11, fix mtree violation, fix library name
  textproc/tesseract/Portfile
  textproc/tesseract/files/patch-fix-library-name.diff
  textproc/tesseract/files/patch-fix-mtree-violation-by-cmake-files.diff
Labels: maintainer: requires approval, type: bugfix

#2204 Add new port : Nheko
  net/nheko/Portfile
Labels: type: enhancement, type: submission

#2305 New port: lynis
  security/lynis/Portfile
Labels: type: enhancement, type: submission

#2297 scotch: update version 6.0.0->6.0.6
  science/scotch/Portfile
  science/scotch/files/patch-Makefile-shared.diff
  science/scotch/files/patch-esmumps-shared.diff
  science/scotch/files/patch-libscotch-shared.diff
  science/scotch/files/patch-libscotchmetis-shared.diff
Labels: by: member, maintainer: open, maintainer: timeout

#2295 wireguard-tools: update to 0.0.20180718, use SYSCONFDIR
  net/wireguard-tools/Portfile
Labels: maintainer, maintainer: open, type: bugfix, type: update

#2301 oce: update version 0.17.2->0.18.3
  graphics/oce/Portfile
  graphics/oce/files/patch-src-OSD-OSD_Chronometer.cxx.diff
Labels: by: member, maintainer: open
