Repository macports/macports-ports, pull requests merged in 2018-04, with the labels that each got.

#1512 libusb* : fix build on 10.7.5
  devel/libusb/Portfile
  devel/libusb/files/patch-10.7-nospeedsuper.diff
Labels: by: member, maintainer: requires approval

#1497 libwebsockets: Update to 2.4.2
  devel/libwebsockets/Portfile
Labels: by: member, maintainer: open, maintainer: timeout, type: update

#1496 aff4: Update to 1.0-20180212
  security/aff4/Portfile
  security/aff4/files/nobundle.patch
Labels: by: member, maintainer: open, maintainer: timeout, type: update

#1515 py-m2crypto: update to 0.29.0
  python/py-m2crypto/Portfile
Labels: maintainer, maintainer: open, type: update

#1516 py-typing: update to 3.6.4
  python/py-typing/Portfile
Labels: maintainer, maintainer: open, type: update

#1503 Add GitHub handle davidnich
  lang/qore-asn1-module/Portfile
  lang/qore-devel/Portfile
  lang/qore-freetds-module/Portfile
  lang/qore-glut-module/Portfile
  lang/qore-json-module/Portfile
  lang/qore-mysql-module/Portfile
  lang/qore-ncurses-module/Portfile
  lang/qore-opengl-module/Portfile
  lang/qore-openldap-module/Portfile
  lang/qore-oracle-module/Portfile
  lang/qore-pgsql-module/Portfile
  lang/qore-sqlite3-module/Portfile
  lang/qore-ssh2-module/Portfile
  lang/qore-uuid-module/Portfile
  lang/qore-xml-module/Portfile
  lang/qore-xmlsec-module/Portfile
  lang/qore-yaml-module/Portfile
  lang/qore/Portfile
Labels: by: member, maintainer: requires approval, maintainer: timeout

#1505 Add GitHub handle scantor
  lang/opensaml/Portfile
  security/shibboleth/Portfile
  security/xml-security-c/Portfile
  security/xmltooling/Portfile
  sysutils/log4shib/Portfile
  textproc/xercesc3/Portfile
Labels: by: member, maintainer: requires approval, maintainer: timeout

#1507 Add GitHub handle jwhowarth
  math/meschach/Portfile
  python/py-minfx/Portfile
  science/apbs/Portfile
  science/ccpnmr/Portfile
  science/molmol/Portfile
  science/pdb2pqr/Portfile
  science/pymol/Portfile
  science/pynmr/Portfile
  science/rNMR/Portfile
  science/relax/Portfile
  science/sparky/Portfile
  science/whatcheck/Portfile
Labels: by: member, maintainer: requires approval, maintainer: timeout

#1522 py-mdtraj: update to 1.9.1
  python/py-mdtraj/Portfile
Labels: maintainer, maintainer: open, type: update

#1517 openscad: fix Resource directory discovery
  science/openscad/Portfile
Labels: by: member, maintainer: open

#1518 mosquitto: Update to revision 1.4.15.
  net/mosquitto/Portfile
Labels: maintainer, maintainer: open, type: update

#1521 Add GitHub handle ci42 to maintainers
  aqua/FScript/Portfile
  databases/couchdb-devel/Portfile
  devel/fossil/Portfile
  devel/go-tools/Portfile
  devel/nodejs5/Portfile
  devel/npm2/Portfile
  devel/npm3/Portfile
  devel/npm4/Portfile
  devel/play/Portfile
  erlang/rebar/Portfile
  lang/factor/Portfile
  lang/go-1.4/Portfile
  lang/jruby-devel/Portfile
  lang/jruby/Portfile
  net/ejabberd/Portfile
  sysutils/parallel/Portfile
  www/yaws/Portfile
Labels: by: member, maintainer: requires approval

#1529 FileZilla: update to 3.32.0
  www/FileZilla/Portfile
Labels: maintainer, maintainer: open, type: update

#1526 kitlist: fix compilation failure and update maintainer details
  office/kitlist/Portfile
Labels: maintainer: requires approval

#1532 net/teleport: update to v2.5.6
  net/teleport/Portfile
Labels: maintainer, maintainer: open, type: update

#1535 py-gast: submission 0.2.0
  python/py-gast/Portfile
Labels: by: member, type: submission

#1533 py-backports.weakref: add size to checksums and reformat
  python/py-backports.weakref/Portfile
Labels: by: member, maintainer, maintainer: open

#1534 py-astor: submission 0.6.2
  python/py-astor/Portfile
Labels: by: member, type: submission

#1524 harfbuzz: build with coretext
  graphics/harfbuzz/Portfile
  graphics/harfbuzz/files/coretext.patch
Labels: by: member, maintainer: open, type: enhancement

#1539 Add github handle for all ports I maintain.
  databases/mycli/Portfile
  databases/pgcli/Portfile
  irc/ngircd/Portfile
  net/ipcalc/Portfile
  python/py-backports.csv/Portfile
  python/py-cli-helpers/Portfile
  python/py-humanize/Portfile
  python/py-pgspecial/Portfile
  python/py-prompt_toolkit/Portfile
  python/py-pycryptodome/Portfile
  python/py-pymysql/Portfile
  python/py-setproctitle/Portfile
  python/py-sqlparse/Portfile
  python/py-terminaltables/Portfile
  python/py-wcwidth/Portfile
  sysutils/dpkg/Portfile
Labels: maintainer, maintainer: open

#1538 terraform: update to 0.11.6
  sysutils/terraform/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#1537 py-tensorboard: submission 1.6.0
  python/py-tensorboard/Portfile
Labels: by: member, type: submission

#1542 emacs: fix trac ticket 56236
  editors/emacs/Portfile
  editors/emacs/files/patch-configure.diff
Labels: by: member, maintainer: open, type: bugfix

#1546 spring-boot-cli: update to 2.0.1.RELEASE
  java/spring-boot-cli/Portfile
Labels: maintainer, maintainer: open, type: update

#1547 emacs-mac-app: Enable dynamic module support
  aqua/emacs-mac-app/Portfile
Labels: maintainer: none, type: enhancement

#1548 py-absl: update to 0.1.13
  python/py-absl/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#1550 neofetch: update to 3.4.0
  sysutils/neofetch/Portfile
Labels: maintainer, maintainer: open, type: update

#1555 sqlite3: enable JSON extension module
  databases/sqlite3/Portfile
Labels: maintainer: open, type: enhancement

#1551 py-mitmproxy: update to 3.0.4
  python/py-mitmproxy/Portfile
Labels: maintainer, maintainer: open, type: update

#1541 Add GitHub handle paumard to maintainers
  python/py-pyorick/Portfile
  python/py-svipc/Portfile
  science/Gyoto/Portfile
  science/LORENE/Portfile
  science/yorick-av/Portfile
  science/yorick-cubeview/Portfile
  science/yorick-gl/Portfile
  science/yorick-gy/Portfile
  science/yorick-hdf5/Portfile
  science/yorick-imutil/Portfile
  science/yorick-ml4/Portfile
  science/yorick-mpeg/Portfile
  science/yorick-optimpack/Portfile
  science/yorick-soy/Portfile
  science/yorick-spydr/Portfile
  science/yorick-yao/Portfile
  science/yorick-yeti/Portfile
  science/yorick-yutils/Portfile
  science/yorick-z/Portfile
  science/yorick/Portfile
Labels: by: member, maintainer: open, maintainer: timeout

#1530 Add GitHub handle lockhart to maintainers
  devel/ace/Portfile
  devel/tao/Portfile
  gis/geographiclib/Portfile
  gis/terra/Portfile
  math/levmar/Portfile
  perl/p5-sgmlspm/Portfile
  python/py-spectral/Portfile
  science/sumo/Portfile
  textproc/docbook-utils/Portfile
  textproc/docbook-xml/Portfile
  textproc/docbook2X/Portfile
  textproc/openjade/Portfile
  textproc/sgml-common/Portfile
Labels: by: member, maintainer: open, maintainer: timeout

#1552 audio/chuck: Update to version 1.4.0.
  audio/chuck/Portfile
  audio/chuck/files/patch-makefile.osx.diff
Labels: maintainer: none, type: update

#1455 Missing depends py-game and py-Pillow
  python/py-kivy/Portfile
Labels: maintainer: open, type: bugfix

#1556 openjk: update to 20180401
  games/openjk/Portfile
  games/openjk/files/patch-CMakeLists-Clang-ID.diff
Labels: by: member, maintainer, maintainer: open, type: update

#1544 kubectl: submission 1.10.0
  sysutils/kubectl/Portfile
Labels: type: submission

#1396 Qt57 fixes
  aqua/qt57/Portfile
Labels: maintainer: open

#1558 py-nltk: add py35 and py36
  python/py-nltk/Portfile
Labels: maintainer: open

#1560 get_iplayer: update to 3.13
  net/get_iplayer/Portfile
Labels: maintainer, maintainer: open, type: update

#1540 Use new use_tar command when available
  devel/jam/Portfile
  lang/eiffelstudio/Portfile
  net/tcpdstat/Portfile
  science/setiathome/Portfile
  tex/detex/Portfile
Labels: by: member, maintainer: requires approval, maintainer: timeout

#1563 terraform: update to 0.11.7
  sysutils/terraform/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#1562 gds: update to version 2.18.7
  science/gds/Portfile
Labels: maintainer: requires approval, type: update

#1564 et: update to 4.2.1
  net/et/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#1559 plumed: added optimization flags
  science/plumed/Portfile
Labels: maintainer, maintainer: open

#1554 bali-phy: Update to 3.0.3
  science/bali-phy/Portfile
Labels: by: member, maintainer: open, maintainer: timeout, type: update

#1519 pdf2json: update to 0.96
  graphics/poppler/Portfile
  graphics/xpdf-tools/Portfile
  graphics/xpdf/Portfile
  textproc/pdf2json/Portfile
  textproc/pdf2json/files/patch-Makefiles.diff
Labels: by: member, maintainer: requires approval, maintainer: timeout, type: enhancement, type: update

#1565 bitcoin: update to 0.16.0, fix issue
  finance/bitcoin/Portfile
Labels: maintainer: open, type: bugfix, type: enhancement, type: update

#1569 apachetop: update to 0.18.4
  sysutils/apachetop/Portfile
Labels: maintainer, type: enhancement, type: update

#1568 pipsi: new port submission
  python/pipsi/Portfile
Labels: by: member, type: submission

#1567 mercurial: point master_sites to official download location
  devel/mercurial/Portfile
Labels: by: member, maintainer: open

#1574 gtk3: tweak gcc blacklisting to fix build on PPC
  gnome/gtk3/Portfile
Labels: by: member, maintainer: open

#1578 tmux: update to 2.7 (tmux-devel to git master)
  sysutils/tmux/Portfile
Labels: maintainer, type: enhancement, type: update

#1580 ccpnmr: repair openmp to fix compilation
  science/ccpnmr/Portfile
  science/ccpnmr/files/ccpnmr.patch
Labels: by: member, maintainer: requires approval

#1582 libqalculate: update to version 2.4.0
  math/libqalculate/Portfile
  math/libqalculate/files/clang_char16_t.patch
  math/qalculate-gtk/Portfile
Labels: maintainer

#1579 yash: update to 2.47
  shells/yash/Portfile
Labels: by: member, maintainer: requires approval, maintainer: timeout, type: update

#1583 Add GitHub handle MarcusCalhoun-Lopez to maintainers
  aqua/doxygen-launcher/Portfile
  aqua/luminance-hdr/Portfile
  databases/db47/Portfile
  devel/gperf/Portfile
  devel/isl/Portfile
  devel/libedit/Portfile
  devel/openscop/Portfile
  graphics/aces_container/Portfile
  graphics/ctlang/Portfile
  graphics/openexr/Portfile
  graphics/openjpeg/Portfile
  graphics/pgplot/Portfile
  lang/dmd-bootstrap/Portfile
  lang/sml-mode.el/Portfile
  multimedia/libdumb/Portfile
  python/py-gdbm/Portfile
  python/py-libxml2/Portfile
  python/py-nose/Portfile
  python/py-openssl/Portfile
  python/py-quadtree/Portfile
  python/py-simpy/Portfile
  python/py-tkinter/Portfile
  python/py-zopeinterface/Portfile
  sysutils/octave_select/Portfile
  x11/glui/Portfile
  x11/imake/Portfile
  x11/xorg-cf-files/Portfile
Labels: by: member, maintainer: requires approval

#1588 babl: tweak gcc blacklisting
  graphics/babl/Portfile
Labels: by: member, maintainer: open

#1591 php-mcrypt: New port, version 1.0.1
  lang/php/Portfile
  php/php-mcrypt/Portfile
Labels: by: member, maintainer, type: submission

#1590 libxkbcommon: New port, version 0.8.0
  devel/libxkbcommon/Portfile
Labels: by: member, type: submission

#1592 serf1: Update to 1.3.9
  www/serf1/Portfile
  www/serf1/files/patch-SConstruct.diff
Labels: by: member, maintainer: requires approval, type: update

#1596 zsh: update to 5.5.1
  shells/zsh/Portfile
Labels: by: member, maintainer: requires approval, type: security fix, type: update

#1589 gds: Modified for C++ 2017 standard
  science/gds/Portfile
  science/gds/files/patch-Monitors-PulsarMon-PulsarMon.cc.diff
  science/gds/files/patch-std_cplusplus_2017.diff
Labels: maintainer, maintainer: open, type: bugfix

#1602 delete old ports requiring OpenSSL 0.9
  devel/libpdel/Portfile
  devel/libpdel/files/Darwin/hacks.h
  devel/libpdel/files/patch-GNUmakefile
  devel/libpdel/files/patch-http_servlet_http_servlet_file.c
  mail/qpopper/Portfile
  mail/qpopper/files/org.macports.mail.qpopper.plist-dist
  mail/qpopper/files/patch-Makefile.in
  mail/qpopper/files/patch-pop_pass.c
  mail/qpopper/files/patch-popper-Makefile.in
  mail/qpopper/files/qpopper-dist
  mail/sylpheed-devel/Portfile
  net/jabber/Portfile
  www/links1/Portfile
  www/lws/Portfile
  www/lws/files/patch-GNUmakefile
Labels: maintainer: none

#1603 remove the obsoleted mdocml
  textproc/mdocml/Portfile
Labels: maintainer: none

#1609 gradle: update to 4.7
  devel/gradle/Portfile
Labels: maintainer, maintainer: open, type: update

#1586 Add GitHub handle Ionic to maintainers
  aqua/pinentry-mac/Portfile
  aqua/x2goclient/Portfile
  audio/pulseaudio/Portfile
  devel/libssh/Portfile
  mail/gnupg/Portfile
  mail/gnupg1/Portfile
  mail/gnupg2/Portfile
  mail/gnupg21/Portfile
  multimedia/audacious-core/Portfile
  multimedia/audacious-plugins/Portfile
  multimedia/audacious/Portfile
  multimedia/mpv/Portfile
  net/nxcomp/Portfile
  perl/p5-cryptx/Portfile
  python/py-distutils-extra/Portfile
  security/dirmngr/Portfile
  security/gpg-agent/Portfile
  security/pinentry/Portfile
  sysutils/amttools/Portfile
  sysutils/fatsort/Portfile
Labels: by: member, maintainer: requires approval, maintainer: timeout

#1612 py-gnupg: Update to 0.4.2
  python/py-gnupg/Portfile
  python/py-gnupg/files/patch-gnupg.py.diff
Labels: maintainer, maintainer: open, type: update

#1617 mod_qos: use standard depends_lib style
  www/mod_qos/Portfile
Labels: maintainer: none

#1618 kotlin: update to 1.2.40
  lang/kotlin/Portfile
Labels: maintainer, maintainer: open, type: update

#1619 py-nclib: Submission
  python/py-nclib/Portfile
Labels: type: submission

#1621 Add GitHub handles bgilbert, jcupitt to maintainers
  graphics/nip2/Portfile
  graphics/openslide/Portfile
  graphics/vips/Portfile
  python/py-openslide/Portfile
  sysutils/tarsnap/Portfile
Labels: by: member, maintainer: requires approval

#1611 crystal: new port
  lang/crystal/Portfile
  lang/crystal/files/patch-compiler.diff
  lang/crystal/files/patch-crypto.diff
  lang/crystal/files/patch-link.diff
  lang/crystal/files/patch-readline.diff
  lang/crystal/files/patch-ssl.diff
  lang/crystal/files/patch-xml.diff
Labels: type: submission

#1624 ecs-cli: update to 1.5.0
  devel/ecs-cli/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#1620 root6: remove variants for python 2.6, 3.3, 3.4
  science/root6/Portfile
Labels: by: member, maintainer

#1594 Add GitHub handle Veence to maintainers
  databases/postgis2/Portfile
  gis/cgal/Portfile
  gis/gdal-grass/Portfile
  gis/gdal/Portfile
  gis/kealib/Portfile
  gis/libpcl/Portfile
  gis/pdal/Portfile
  gis/pgrouting/Portfile
  gis/saga/Portfile
  gis/sfcgal/Portfile
  math/atlas/Portfile
  math/gaul-devel/Portfile
Labels: by: member, maintainer: requires approval, maintainer: timeout

#1616 remove bincimap
  mail/bincimap/Portfile
  mail/bincimap/files/README.MACOSX.in
  mail/bincimap/files/pam-bincimap
  mail/bincimap/files/patch-Makefile.in.diff
  mail/bincimap/files/patch-conf.diff
  mail/bincimap/files/patch-service.diff
Labels: maintainer: none

#1614 delete sign
  security/sign/Portfile
Labels: maintainer: none

#1613 remove createtorrent
  sysutils/createtorrent/Portfile
  sysutils/createtorrent/files/patch-configure
Labels: maintainer: none

#1615 ldas-tools-al: fix depends_lib
  science/ldas-tools-al/Portfile
Labels: maintainer: requires approval

#1605 Add GitHub handle Gminfly to maintainers
  devel/libssh2/Portfile
  net/arpwatch/Portfile
  net/bittwist/Portfile
  net/corkscrew/Portfile
  net/dnstop/Portfile
  net/hping3/Portfile
  net/tcpreplay/Portfile
  net/xprobe2/Portfile
  security/medusa/Portfile
  security/zzuf/Portfile
  www/varnish/Portfile
Labels: by: member, maintainer: open, maintainer: timeout

#1606 Add GitHub handle jfcaron3 to maintainers
  games/angband/Portfile
  python/py-PyRSS2Gen/Portfile
  python/py-natsort/Portfile
  python/py-unidecode/Portfile
  python/py-yapsy/Portfile
Labels: by: member, maintainer: requires approval, maintainer: timeout

#1607 Add GitHub handle harciga to maintainers
  devel/girara/Portfile
  graphics/mupdf/Portfile
  irc/weechat/Portfile
  office/zathura-plugin-cb/Portfile
  office/zathura-plugin-djvu/Portfile
  office/zathura-plugin-pdf-mupdf/Portfile
  office/zathura-plugin-pdf-poppler/Portfile
  office/zathura-plugin-ps/Portfile
  office/zathura/Portfile
Labels: by: member, maintainer: open, maintainer: timeout

#1608 Add GitHub handle jswhit to maintainers
  python/py-netcdf4/Portfile
  python/py-pygrib/Portfile
Labels: by: member, maintainer: open, maintainer: timeout

#1581 libcxx: add libcxxabi headers
  lang/libcxx/Portfile
Labels: by: member, maintainer: requires approval, maintainer: timeout

#1630 perl5.2[46]: update to 5.24.4 and 5.26.2, add size
  lang/perl5/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#1622 Add GitHub handle eighthave to maintainers
  devel/fdroidserver/Portfile
  python/py-asn1-modules/Portfile
Labels: by: member, maintainer: requires approval, maintainer: timeout

#1623 Add GitHub handle agraef to maintainers
  audio/faustlive-devel/Portfile
  audio/lilv/Portfile
  audio/lv2/Portfile
  audio/serd/Portfile
  audio/sord/Portfile
  audio/sratom/Portfile
Labels: by: member, maintainer, maintainer: timeout

#1632 iTerm2: Update to version 3.1.6
  aqua/iTerm2/Portfile
Labels: by: member, maintainer: requires approval, type: update

#1633 py-uncertainties: update to 3.0.2
  python/py-uncertainties/Portfile
Labels: maintainer: open, type: update

#1643 meson: update to 0.46.0
  devel/meson/Portfile
Labels: by: member, maintainer: none, type: update

#1636 Add GitHub handle cdeil to maintainers
  python/py-astropy/Portfile
  python/py-gammapy/Portfile
  python/py-iminuit/Portfile
  python/py-photutils/Portfile
  python/py-pyregion/Portfile
  python/py-regions/Portfile
  python/py-reproject/Portfile
  science/cfitsio/Portfile
  science/missfits/Portfile
  science/psfex/Portfile
  science/scamp/Portfile
  science/sextractor/Portfile
  science/skymaker/Portfile
  science/stiff/Portfile
  science/stuff/Portfile
  science/swarp/Portfile
  science/weightwatcher/Portfile
Labels: by: member, maintainer: requires approval

#1637 Add GitHub handle pmetzger to maintainers
  lang/camlp5/Portfile
  lang/ocaml-camlp4/Portfile
  lang/ocaml/Portfile
  ocaml/ocaml-findlib/Portfile
Labels: by: member, maintainer: open

#1604 doxygen-launcher: install doxygen dependent with correct variant
  aqua/doxygen-launcher/Portfile
Labels: by: member, maintainer, maintainer: open

#1648 Remove myself (cdeil) as maintainer of Astromatic ports
  science/missfits/Portfile
  science/psfex/Portfile
  science/scamp/Portfile
  science/sextractor/Portfile
  science/skymaker/Portfile
  science/stiff/Portfile
  science/stuff/Portfile
  science/swarp/Portfile
  science/weightwatcher/Portfile
Labels: maintainer, maintainer: open

#1595 mandoc: rename files to not conflict with groff
  sysutils/groff/Portfile
  textproc/mandoc/Portfile
Labels: maintainer, maintainer: open

#1647 lowdown: upgrade to 0.3.2
  textproc/lowdown/Portfile
  textproc/lowdown/files/Makefile.patch
  textproc/lowdown/files/configure.patch
Labels: maintainer

#1652 Use MacPorts handle lbschenkel in maintainers
  databases/pspg/Portfile
  textproc/xdxf_makedict/Portfile
Labels: by: member, maintainer: open

#1627 py-astropy: update to 3.0.1
  python/py-astropy/Portfile
Labels: by: member, maintainer: requires approval, type: update

#1650 py-dill: update to 0.2.7.1
  python/py-dill/Portfile
Labels: maintainer: open, type: update

#1651 py-asteval: new port submission
  python/py-asteval/Portfile
Labels: type: submission

#1638 Add GitHub handle lperry to maintainers
  archivers/xdelta/Portfile
  graphics/comix/Portfile
  python/py-markupsafe/Portfile
  sysutils/port_cutleaves/Portfile
Labels: by: member, maintainer: open

#1655 Add GitHub handle smaret to maintainers
  science/gildas/Portfile
Labels: by: member, maintainer: requires approval

#1639 Add GitHub handle grimreaper to maintainers
  games/sl/Portfile
  java/hamcrest-core/Portfile
Labels: by: member, maintainer: requires approval

#1635 Add GitHub handle markemer to maintainers
  aqua/iTerm2/Portfile
  science/geda-gaf/Portfile
  textproc/tesseract/Portfile
Labels: by: member, maintainer: requires approval

#1659 py-isort: update to 4.3.4
  python/py-isort/Portfile
Labels: maintainer: none, type: update

#690 mosh: Switch to protobuf3-cpp
  net/mosh/Portfile
Labels: by: member, maintainer: requires approval, maintainer: timeout, type: enhancement

#1654 protobuf-c: update to 1.3.0
  devel/protobuf-c/Portfile
Labels: by: member, maintainer: none, type: update

#1662 py-pypdf2: update to 1.26.0
  python/py-pypdf2/Portfile
Labels: maintainer: none, type: update

#1631 acl2: Update to 8.0
  math/acl2/Portfile
Labels: by: member, maintainer: none, type: enhancement, type: update

#1666 py-lmfit: update to 0.9.9
  python/py-lmfit/Portfile
Labels: maintainer: open, type: update

#1661 osc2midi: new port @ 0.2.3
  audio/osc2midi/Portfile
Labels: by: member, type: submission

#1665 ostinato: switch from protobuf-cpp to protobuf3-cpp
  net/ostinato/Portfile
Labels: by: member, maintainer: open

#1664 libphonenumber-cpp: switch from protobuf-cpp to protobuf3-cpp
  devel/libphonenumber-cpp/Portfile
Labels: by: member, maintainer: open

#1634 Add GitHub handle emaros to maintainers
  science/gds/Portfile
  science/ldas-tools-al/Portfile
  science/ldas-tools-diskcacheAPI/Portfile
  science/ldas-tools-filters/Portfile
  science/ldas-tools-frameAPI/Portfile
  science/ldas-tools-framecpp/Portfile
  science/ldas-tools-ldasgen/Portfile
  science/ldas-tools-utilities/Portfile
  science/ldas-tools/Portfile
  science/ligotools/Portfile
  science/lscsoft-deps/Portfile
  science/nds2-client/Portfile
Labels: by: member, maintainer: requires approval, maintainer: timeout

#1640 Add MacPorts handle emcrisostomo to maintainers
  devel/ecs-cli/Portfile
  java/flyway/Portfile
  python/py-absl/Portfile
  python/py-astor/Portfile
  python/py-backports.weakref/Portfile
  python/py-boto3/Portfile
  python/py-cheetah/Portfile
  python/py-gast/Portfile
  python/py-grpcio/Portfile
  python/py-tensorboard/Portfile
  python/py-tensorflow-tensorboard/Portfile
  python/py-tensorflow/Portfile
  sysutils/fswatch/Portfile
  sysutils/terraform/Portfile
Labels: by: member, maintainer: open, maintainer: timeout

#1644 Add GitHub handle xuchunyang to maintainers
  devel/magit/Portfile
  devel/pick/Portfile
  devel/proxychains-ng/Portfile
  sysutils/fuzzy-find/Portfile
  sysutils/trash/Portfile
  sysutils/z/Portfile
  textproc/translate-shell/Portfile
Labels: by: member, maintainer: open, maintainer: timeout

#1645 Add GitHub handle RJVB to maintainers
  audio/phonon-backend-gstreamer/Portfile
  audio/phonon-backend-vlc/Portfile
  devel/dbusmenu-qt/Portfile
  devel/kchmviewer/Portfile
  devel/libical/Portfile
  devel/qca/Portfile
  devel/shared-mime-info/Portfile
  gnome/oxygen-gtk2/Portfile
  kde/Ciment-icons/Portfile
  kde/OSXdg-icons/Portfile
  kde/kde-extra-cmake-modules/Portfile
  kde/kde4-workspace/Portfile
  kde/mate-icons/Portfile
  kde/polkit-qt/Portfile
  kde/py-pykde4/Portfile
  kde/qtcurve/Portfile
  math/Vc/Portfile
  multimedia/VLC/Portfile
  multimedia/libmovit/Portfile
  multimedia/mlt/Portfile
  office/charm/Portfile
  sysutils/cpuid/Portfile
  sysutils/smartmontools/Portfile
  textproc/libetonyek/Portfile
  textproc/libodfgen/Portfile
Labels: by: member, maintainer: requires approval, maintainer: timeout

#1646 Add GitHub handle wyuenho to maintainers
  devel/astyle/Portfile
  devel/pmk/Portfile
  devel/premake/Portfile
  devel/premake4/Portfile
Labels: by: member, maintainer: requires approval, maintainer: timeout

#1656 Add GitHub handle ghosthound to maintainers
  security/aff4/Portfile
  sysutils/tienex-apfs/Portfile
Labels: by: member, maintainer: open, maintainer: timeout

#1657 Add GitHub handle jdberry to maintainers
  mail/dovecot/Portfile
  net/mrtg-ping-probe/Portfile
  net/mrtg/Portfile
  sysutils/cronolog-devel/Portfile
  sysutils/tag/Portfile
Labels: by: member, maintainer: requires approval, maintainer: timeout

#1663 caffe: switch from protobuf-cpp to protobuf3-cpp
  math/caffe/Portfile
Labels: by: member, maintainer: none

#1642 Add GitHub handle cssdev to maintainers
  audio/streamripper/Portfile
  devel/inventor/Portfile
  editors/hnb/Portfile
  multimedia/tivodecode/Portfile
  net/rsync-lart/Portfile
  palm/hrsh2csv/Portfile
  security/apg/Portfile
  textproc/doxygen/Portfile
  x11/glw/Portfile
Labels: by: member, maintainer: requires approval, maintainer: timeout

#1660 py-tqdm: add py34 subport
  python/py-tqdm/Portfile
Labels: maintainer: open

#1672 mpich: Remove unused files
  science/mpich/Portfile
  science/mpich/files/mpich-clang32
  science/mpich/files/mpich-clang32-fortran
  science/mpich/files/mpich-clang33
  science/mpich/files/mpich-clang33-fortran
  science/mpich/files/mpich-clang34
  science/mpich/files/mpich-clang34-fortran
  science/mpich/files/mpich-clang35
  science/mpich/files/mpich-clang35-fortran
  science/mpich/files/mpich-clang36
  science/mpich/files/mpich-clang36-fortran
  science/mpich/files/mpich-devel-clang32
  science/mpich/files/mpich-devel-clang32-fortran
  science/mpich/files/mpich-devel-clang33
  science/mpich/files/mpich-devel-clang33-fortran
  science/mpich/files/mpich-devel-clang34
  science/mpich/files/mpich-devel-clang34-fortran
  science/mpich/files/mpich-devel-clang35
  science/mpich/files/mpich-devel-clang35-fortran
  science/mpich/files/mpich-devel-clang36
  science/mpich/files/mpich-devel-clang36-fortran
  science/mpich/files/mpich-devel-gcc43-fortran
  science/mpich/files/mpich-devel-gcc45-fortran
  science/mpich/files/mpich-devel-gcc46-fortran
  science/mpich/files/mpich-devel-gcc47-fortran
  science/mpich/files/mpich-gcc43-fortran
  science/mpich/files/mpich-gcc45-fortran
  science/mpich/files/mpich-gcc46-fortran
  science/mpich/files/mpich-gcc47-fortran
Labels: by: member, maintainer: open

#1658 ninja: fix build on Tiger
  devel/ninja/Portfile
  devel/ninja/files/patch-tiger-no-posix-spawn.diff
  devel/ninja/files/patch-tiger-sysconf.diff
Labels: by: member, maintainer: open

#1641 npm5: depend on nodejs8 by default
  devel/npm5/Portfile
Labels: by: member, maintainer: open, maintainer: timeout, type: enhancement

#1675 rethinkdb: remove port
  databases/rethinkdb/Portfile
  databases/rethinkdb/files/3cf9e7bf13e5f0f364aecf0913e09d704e9688d2.patch
Labels: by: member, maintainer: none

#1679 py-typing: reverse py35/py36 subports added by 6c05e98
  python/py-typing/Portfile
Labels: maintainer, maintainer: open

#1683 octave: remove references to nonexistent compilers
  math/octave/Portfile
Labels: by: member, maintainer, maintainer: open

#1680 Improvements to cargo port group
  _resources/port1.0/group/cargo-1.0.tcl
Labels: by: member, type: enhancement

#1684 py-backports[-ssl_match_hostname]: revert subports
  python/py-backports-ssl_match_hostname/Portfile
  python/py-backports/Portfile
Labels: by: member, maintainer: open

#1670 asciinema: update to 2.0.1
  sysutils/asciinema/Portfile
Labels: by: member, maintainer: requires approval, type: update

#1685 rust: allow build if llvm is universal
  lang/rust/Portfile
Labels: by: member, maintainer: open

#1682 pymol: fix -O3 usage on Darwin and clean up broken reinplaces
  science/pymol/Portfile
  science/pymol/files/setup.py.diff
Labels: maintainer, maintainer: open

#1673 py-nmrglue: update to 0.6
  python/py-nmrglue/Portfile
Labels: maintainer: open, maintainer: timeout, type: bugfix, type: enhancement

#1690 ocaml3, ocaml3-camlp5, ocaml3-findlib: remove obsolete ports
  lang/ocaml3-camlp5/Portfile
  lang/ocaml3/Portfile
  lang/ocaml3/files/patch-configure.diff
  lang/ocaml3/files/patch-otherlibs-bigarray.diff
  ocaml/ocaml3-findlib/Portfile
  ocaml/ocaml3-findlib/files/camlp4find
  ocaml/ocaml3-findlib/files/patch-site-lib-src-camlp4.310-META.in.diff
Labels: by: member, maintainer: none

#1688 py-logcat-color: new port, version 0.6.0
  python/logcat-color_select/Portfile
  python/logcat-color_select/files/base
  python/logcat-color_select/files/none
  python/py-logcat-color/Portfile
  python/py-logcat-color/files/logcat-color-27
Labels: type: submission
