Repository macports/macports-ports, pull requests merged in 2018-06, with the labels that each got.

#1896 dmd-bootstrap: set configure.cxx_stdlib
  lang/dmd-bootstrap/Portfile
Labels: by: member, maintainer, maintainer: open

#1922 Gildas: update to 201806a
  science/gildas/Portfile
Labels: maintainer, type: update

#1919 dash: Add maintainer/openmaintainer
  shells/dash/Portfile
Labels: maintainer

#1920 auto-multiple-choice-devel: update to 1.4.0.b201805310528
  x11/auto-multiple-choice/Portfile
Labels: maintainer, maintainer: open, type: enhancement, type: update

#1924 New port: libjwt
  devel/libjwt/Portfile
Labels: type: enhancement, type: submission

#1911 Add GitHub handle Rudloff to maintainers
  aqua/jumpcut/Portfile
  aqua/tagainijisho/Portfile
  devel/angelscript/Portfile
  devel/dylibbundler/Portfile
  graphics/gpick/Portfile
  lang/jslint/Portfile
  lang/phpstylist/Portfile
  www/arora/Portfile
  www/nikto/Portfile
Labels: by: member, maintainer: requires approval

#1926 jmock[12]: set license
  java/jmock1/Portfile
  java/jmock2/Portfile
Labels: by: member, maintainer: requires approval

#1928 jslint: use github PortGroup
  lang/jslint/Portfile
Labels: by: member, maintainer: none, type: enhancement

#1931 libblocksruntime: add openmaintainer and remove clang_select depends
  devel/libblocksruntime/Portfile
Labels: maintainer: requires approval

#1900 various py-* ports: remove obsolete py26/py33 subports
  python/py-acor/Portfile
  python/py-acora/Portfile
  python/py-appdirs/Portfile
  python/py-astrolibcoords/Portfile
  python/py-astropy-helpers/Portfile
  python/py-async-task/Portfile
  python/py-atpy/Portfile
  python/py-backcall/Portfile
  python/py-beautifulsoup/Portfile
  python/py-boto/Portfile
  python/py-bottle-sqlalchemy/Portfile
  python/py-bottle/Portfile
  python/py-bottleneck/Portfile
  python/py-graveyard/Portfile
Labels: maintainer: requires approval, maintainer: timeout, type: enhancement

#1932 rabbitmq-server: update to 3.6.15
  net/rabbitmq-server/Portfile
Labels: by: member, maintainer: none, type: update

#1927 zeroc-ice33: Fix extract failure
  devel/zeroc-ice33/Portfile
Labels: by: member, maintainer: requires approval

#1935 iperf3: Enable livecheck for iperf3-devel
  net/iperf3/Portfile
Labels: by: member, maintainer: open

#1934 py*-ansible: updated ansible from 2.4.2.0 to 2.5.4 (current stable on PyPI)
  python/py-ansible/Portfile
Labels: maintainer: requires approval, type: enhancement

#1925 Added new jwt variant to nginx
  www/nginx/Portfile
Labels: maintainer: open, type: enhancement

#1885 rubberband: fix system test for < 10.7
  audio/rubberband/Portfile
  audio/rubberband/files/patch-vectorops-snowleopard.diff
Labels: by: member, maintainer: open

#1941 nsd: update to 4.1.21
  net/nsd/Portfile
Labels: by: member, maintainer: none, type: update

#1912 dylibbundler: Use the right CXXFLAGS
  devel/dylibbundler/Portfile
Labels: by: member, maintainer: open

#1913 SuiteSparse: Use MacPorts CXXFLAGS
  math/SuiteSparse/Portfile
Labels: by: member, maintainer: open

#1942 poedit: update to 2.0.8
  editors/poedit/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#1916 Add GitHub handle elelay to maintainers
  devel/gtk-osx-application/Portfile
  gnome/gpodder/Portfile
  python/py-eyed3/Portfile
  python/py-faulthandler/Portfile
  python/py-mutagen/Portfile
  python/py-mygpoclient/Portfile
  python/py-notify-python/Portfile
  python/py-podcastparser/Portfile
  python/py27-webkitgtk/Portfile
  python/quodlibet/Portfile
  textproc/meld/Portfile
  x11/tango-icon-theme-extras/Portfile
  x11/tango-icon-theme/Portfile
Labels: by: member, maintainer: requires approval, maintainer: timeout

#1917 Add GitHub handle mperrin to maintainers
  python/py-aplpy/Portfile
  python/py-astrolibcoords/Portfile
  python/py-pyds9/Portfile
Labels: by: member, maintainer: open, maintainer: timeout

#1918 Add GitHub handle tazzben to maintainers
  office/DepreciateForLedger/Portfile
  office/GTDtoCSV/Portfile
  office/LedgerScheduler/Portfile
  office/csvToLedger/Portfile
  office/expense.txt/Portfile
  office/heapCL/Portfile
  office/time.txt/Portfile
  office/torchCL/Portfile
Labels: by: member, maintainer: requires approval, maintainer: timeout

#1944 logtalk: update to 3.17.0
  lang/logtalk/Portfile
Labels: maintainer, type: update

#1945 swi-prolog-devel: update to 7.7.15
  lang/swi-prolog-devel/Portfile
Labels: maintainer, type: update

#1936 emacs: update patches and fix autoconf missing build failure
  editors/emacs/Portfile
  editors/emacs/files/patch-devel-src_emacs.c.diff
  editors/emacs/files/patch-inline-25.2-20170426.diff
  editors/emacs/files/patch-src-macim.m.diff
  editors/emacs/files/patch-src_emacs.c.diff
  editors/emacs/files/site-start.el
Labels: maintainer: open, type: enhancement

#1948 Fix emacs app inline patch
  editors/emacs/Portfile
  editors/emacs/files/patch-inline-25.2-20170426.diff
Labels: maintainer: open, type: bugfix

#1930 bind9: use https, fix livecheck
  net/bind9/Portfile
Labels: by: member, maintainer: requires approval, type: bugfix

#1952 Update to binwalk - 56341
  cross/binwalk/Portfile
Labels: maintainer: open, type: bugfix

#1947 gradle: update to 4.8
  devel/gradle/Portfile
Labels: maintainer, maintainer: open, type: update

#1958 hub: update to 2.3.0
  devel/hub/Portfile
Labels: by: member, maintainer: requires approval, type: update

#1959 ecs-cli: update to 1.6.0
  devel/ecs-cli/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#1955 OpenBLAS: update to 0.3.0.
  math/OpenBLAS/Portfile
  math/OpenBLAS/files/patch-libnoarch.release.diff
  math/OpenBLAS/files/patch-linkLib.release.diff
Labels: by: member, maintainer, maintainer: open, type: update

#1957 pybombs: add setuptools dep
  science/pybombs/Portfile
Labels: by: member, maintainer: requires approval, type: bugfix

#1933 folly: build with cmake
  devel/folly/Portfile
  devel/folly/files/patch-cmake-config.diff
  devel/folly/files/patch-cmakelists.diff
Labels: maintainer: none, type: enhancement

#1962 wangle: fix linking to folly
  devel/wangle/Portfile
Labels: maintainer: none, type: bugfix

#1939 gri: allow recent Perl version to be used
  science/gri/Portfile
  science/gri/files/patch-illegal-regex.diff
Labels: by: member, maintainer: none

#1954 Update emacs-*-devel versions, fix variants and misc clean ups
  editors/emacs/Portfile
  editors/emacs/files/patch-devel-src_dbusbind.c.diff
Labels: maintainer: open, type: bugfix, type: enhancement

#1963 groovy: update to 2.5.0
  lang/groovy/Portfile
Labels: maintainer, maintainer: open, type: update

#1946 Add GitHub handles pmoura and JanWielemaker to maintainers
  lang/gprolog/Portfile
  lang/logtalk/Portfile
  lang/swi-prolog-devel/Portfile
  lang/swi-prolog-lite/Portfile
  lang/swi-prolog/Portfile
  lang/yap-devel/Portfile
  lang/yap/Portfile
Labels: by: member, maintainer: requires approval, maintainer: timeout

#1940 p5-error: update to version 0.17026
  perl/p5-error/Portfile
Labels: by: member, maintainer: open, type: enhancement, type: update

#1961 fbthrift: update to 2018.05.28.00
  devel/fbthrift/Portfile
Labels: maintainer: none, type: update

#1949 Add GitHub handle maherg to maintainers
  python/py-pyke/Portfile
  python/py-twill/Portfile
Labels: by: member, maintainer: requires approval, maintainer: timeout

#1950 Add GitHub handle jeromecaffaro to maintainers
  python/py-pyrxp/Portfile
  python/py-stemmer/Portfile
Labels: by: member, maintainer: open, maintainer: timeout

#1923 multiple ports: url fixes for Thomas E. Dickey's sites
  devel/bcpp/Portfile
  devel/byacc/Portfile
  devel/c_count/Portfile
  devel/dialog/Portfile
  devel/diffstat/Portfile
  devel/reflex/Portfile
  devel/vttest/Portfile
  editors/vile/Portfile
  lang/mawk/Portfile
  www/lynx/Portfile
  x11/mrxvt/Portfile
  x11/xterm/Portfile
Labels: maintainer: requires approval, type: enhancement

#1956 xterm: update to 333
  x11/xterm/Portfile
Labels: maintainer: open, type: update

#1965 unison: update version 2.48.4->2.51.2
  net/unison/Portfile
  net/unison/files/patch-Makefile.OCaml-MINOSXVERSION.diff
  net/unison/files/patch-Makefile.OCaml.diff
  net/unison/files/patch-Makefile.diff
  net/unison/files/patch-check-cltool.diff
  net/unison/files/patch-target.diff
  net/unison/files/patch-uimacnew-uimacnew.xcodeproj-project.pbxproj.diff
Labels: by: member, maintainer: none

#1966 bro: update to 2.5.4
  net/bro/Portfile
Labels: by: member, maintainer: none, type: update

#1968 libjwt: Add comment to Portfile to not update to v1.9
  devel/libjwt/Portfile
Labels: maintainer, maintainer: open, type: enhancement

#1977 p5-datetime-locale: update to 1.22
  perl/p5-datetime-locale/Portfile
Labels: maintainer: none, type: update

#1974 p5-devel-nytprof: update to 6.06
  perl/p5-devel-nytprof/Portfile
Labels: maintainer: open, type: update

#1983 Thunar: update to 1.6.15
  xfce/Thunar/Portfile
Labels: maintainer: none, type: update

#1982 abcde: depend on p5.xx subports
  audio/abcde/Portfile
Labels: maintainer: open, type: enhancement

#1990 octave: have OCTAVE_VERSION return correct value
  math/octave/Portfile
Labels: by: member, maintainer, maintainer: open

#1992 dbus: update version 1.12.2->1.12.8
  devel/dbus/Portfile
Labels: by: member, maintainer, maintainer: open

#1994 qt59-qtlocation: avoid C++17
  aqua/qt59/Portfile
  aqua/qt59/files/patch-qtlocation-no-cxx17.diff
Labels: by: member, maintainer, maintainer: open

#1986 p5-math-anynum: update to 0.26
  perl/p5-math-anynum/Portfile
Labels: maintainer: open, type: update

#1987 p5-image-exiftool: update to 11.00
  perl/p5-image-exiftool/Portfile
Labels: maintainer: none, type: update

#1988 p5-twitter-api: update to 1.0002
  perl/p5-twitter-api/Portfile
Labels: maintainer: none, type: update

#1984 p5-mac-osversion: update to 1.003
  perl/p5-mac-osversion/Portfile
Labels: maintainer: open, type: update

#1995 p5-devel-nytprof: add depends_test-append modules
  perl/p5-devel-nytprof/Portfile
Labels: maintainer: open, type: enhancement

#1996 p5-net-netmask: update to 1.9101, add depends_test-append modules
  perl/p5-net-netmask/Portfile
Labels: maintainer: none, type: enhancement, type: update

#1970 Add Xcode 10 for macOS 10.14
  _resources/macports1.0/xcode_versions.ini
Labels: by: member

#1998 p5-tk: remove unused dependency tk
  perl/p5-tk/Portfile
Labels: maintainer: none, type: enhancement

#1979 py-pylru: new port, version 1.1.0
  python/py-pylru/Portfile
Labels: type: enhancement, type: submission

#1981 offlineimap: update to 7.2.0
  mail/offlineimap/Portfile
Labels: by: member, maintainer: open, type: update

#1971 jbig2enc: Remove github.version override
  graphics/jbig2enc/Portfile
Labels: by: member, maintainer: open, maintainer: timeout

#1989 cquery: new port
  devel/cquery/Portfile
Labels: by: member, type: enhancement, type: submission, wip

#1997 zstd: Use CXXFLAGS and LDFLAGS and don't build contrib, examples, or manual
  archivers/zstd/Portfile
Labels: by: member, maintainer: open

#2000 cquery: remove readonly var assignment
  devel/cquery/Portfile
Labels: maintainer, maintainer: open, type: bugfix

#2003 emacs-app: remove inline patch
  editors/emacs/Portfile
  editors/emacs/files/patch-inline-25.2-20170426.diff
Labels: maintainer: open, type: bugfix, type: enhancement

#2004 dbus: fix test for startupitem.install
  devel/dbus/Portfile
Labels: by: member, maintainer, maintainer: open

#2001 py-idna-ssl: new port, version 1.0.1
  python/py-idna-ssl/Portfile
Labels: type: enhancement, type: submission

#1991 py-lxml: Update to 4.2.1
  python/py-lxml/Portfile
Labels: by: member, maintainer: open, type: enhancement, type: update

#2002 libjwt: Update to version 1.9.0
  devel/libjwt/Portfile
Labels: maintainer, maintainer: open, type: enhancement, type: update

#2008 cppcheck: update to 1.84
  devel/cppcheck/Portfile
Labels: by: member, maintainer: none, type: update

#2009 dbus: use base support for multiple startupitems
  devel/dbus/Portfile
Labels: by: member, maintainer: open, type: enhancement

#2010 mpd: update to 0.20.20
  audio/mpd/Portfile
Labels: by: member, maintainer: none, type: update

#2006 p5-type-tiny-xs: update to 0.014
  perl/p5-type-tiny-xs/Portfile
Labels: maintainer: none, type: enhancement, type: update

#2011 lmdb: update to 0.9.22
  databases/lmdb/Portfile
  databases/lmdb/files/patch-Makefile.diff
Labels: by: member, maintainer: none, type: update

#2012 octave: add missing dependency on Qt sqlite3-plugin
  math/octave/Portfile
Labels: by: member, maintainer, maintainer: open

#2013 spice-protocol: update to 0.12.14
  devel/spice-protocol/Portfile
Labels: by: member, maintainer: open, type: update

#1969 llvm-*: Add 6.0 to clang versions to blacklist
  lang/llvm-3.3/Portfile
  lang/llvm-3.4/Portfile
  lang/llvm-3.5/Portfile
  lang/llvm-3.7/Portfile
  lang/llvm-3.8/Portfile
  lang/llvm-3.9/Portfile
  lang/llvm-4.0/Portfile
  lang/llvm-5.0/Portfile
  lang/llvm-6.0/Portfile
Labels: by: member, maintainer: requires approval, maintainer: timeout

#2015 ocatve: stop modifying OCTAVE_VERSION variable
  math/octave/Portfile
  math/octave/files/patch-versions-devel.diff
  math/octave/files/patch-versions.diff
Labels: by: member, maintainer, maintainer: open

#2014 avahi: use base support for multiple startupitems
  net/avahi/Portfile
Labels: by: member, maintainer: none

#2022 kotlin: update to 1.2.50
  lang/kotlin/Portfile
Labels: maintainer, maintainer: open, type: update

#2017 swi-prolog-devel: update to 7.7.16
  lang/swi-prolog-devel/Portfile
Labels: maintainer, type: update

#2019 ostinato: Update to v0.9
  net/ostinato/Portfile
Labels: maintainer: open, type: update

#2021 update www.mirrorservice.org urls
  _resources/port1.0/fetch/mirror_sites.tcl
  archivers/zip/Portfile
  cross/arm-elf-gcc/Portfile
  cross/arm-elf-gcc3/Portfile
  databases/mysql4/Portfile
  devel/libffi/Portfile
  games/larn/Portfile
  lang/antlr/Portfile
  lang/antlr3/Portfile
  lang/gcc45/Portfile
  lang/gcc46/Portfile
  lang/gcc47/Portfile
  lang/gcc5/Portfile
  mail/libmilter/Portfile
  net/ncftp/Portfile
  net/ripe-whois/Portfile
  net/squid/Portfile
  net/squid3/Portfile
  x11/dlume/Portfile
Labels: maintainer: requires approval, type: enhancement

#2018 octave-devel: use correct version for HG tag
  math/octave/Portfile
Labels: by: member, maintainer, maintainer: open

#2023 update mirror.aarnet.edu.au urls
  _resources/port1.0/fetch/mirror_sites.tcl
  databases/mariadb-10.0/Portfile
  databases/mariadb-10.1/Portfile
  databases/mariadb-10.2/Portfile
  databases/mariadb/Portfile
  devel/libffi/Portfile
  net/squid/Portfile
  net/squid3/Portfile
Labels: maintainer: open, type: enhancement

#2029 ffmpeg: update to 4.0.1, update URLs
  multimedia/ffmpeg/Portfile
Labels: by: member, maintainer: open, type: security fix, type: update

#2040 Vc: Update to 1.3.3 and migrate to GitHub.
  math/Vc/Portfile
Labels: by: member, maintainer: open, type: enhancement, type: update

#2038 hugo: update to 0.42.1
  www/hugo/Portfile
Labels: maintainer: none, type: update

#2043 py*-requests: update to 2.19.1.
  python/py-requests/Portfile
Labels: by: member, maintainer: open, type: bugfix, type: enhancement, type: update

#1770 texlive: update to 2018 release
  tex/biblatex-biber/Portfile
  tex/latexmk/Portfile
  tex/texlive-basic/Portfile
  tex/texlive-bibtex-extra/Portfile
  tex/texlive-bin-extra/Portfile
  tex/texlive-bin/Portfile
  tex/texlive-bin/files/patch-pdftosrc-const.diff
  tex/texlive-bin/files/patch-r47470.diff
  tex/texlive-common/Portfile
  tex/texlive-context/Portfile
  tex/texlive-fonts-extra/Portfile
  tex/texlive-fonts-recommended/Portfile
  tex/texlive-fontutils/Portfile
  tex/texlive-formats-extra/Portfile
  tex/texlive-games/Portfile
  tex/texlive-humanities/Portfile
  tex/texlive-lang-arabic/Portfile
  tex/texlive-lang-chinese/Portfile
  tex/texlive-lang-cjk/Portfile
  tex/texlive-lang-cyrillic/Portfile
  tex/texlive-lang-czechslovak/Portfile
  tex/texlive-lang-english/Portfile
  tex/texlive-lang-european/Portfile
  tex/texlive-lang-french/Portfile
  tex/texlive-lang-german/Portfile
  tex/texlive-lang-greek/Portfile
  tex/texlive-lang-italian/Portfile
  tex/texlive-lang-japanese/Portfile
  tex/texlive-lang-korean/Portfile
  tex/texlive-lang-other/Portfile
  tex/texlive-lang-polish/Portfile
  tex/texlive-lang-portuguese/Portfile
  tex/texlive-lang-spanish/Portfile
  tex/texlive-latex-extra/Portfile
  tex/texlive-latex-recommended/Portfile
  tex/texlive-latex/Portfile
  tex/texlive-luatex/Portfile
  tex/texlive-math-science/Portfile
  tex/texlive-metapost/Portfile
  tex/texlive-music/Portfile
  tex/texlive-pictures/Portfile
  tex/texlive-plain-generic/Portfile
  tex/texlive-pstricks/Portfile
  tex/texlive-publishers/Portfile
  tex/texlive-xetex/Portfile
  tex/texlive/Portfile
Labels: by: member, maintainer: requires approval, type: update

#2037 p5-tkx: add dependency on tk
  perl/p5-tkx/Portfile
Labels: maintainer: open, type: bugfix, type: enhancement

#2044 wireguard-go: new port, version 0.0.20180613
  net/wireguard-go/Portfile
Labels: type: submission

#2046 py-bob*: Delete
  python/py-bob-ap/Portfile
  python/py-bob-blitz/Portfile
  python/py-bob-core/Portfile
  python/py-bob-db-atnt/Portfile
  python/py-bob-db-base/Portfile
  python/py-bob-db-iris/Portfile
  python/py-bob-db-mnist/Portfile
  python/py-bob-db-verification-utils/Portfile
  python/py-bob-db-wine/Portfile
  python/py-bob-extension/Portfile
  python/py-bob-io-audio/Portfile
  python/py-bob-io-base/Portfile
  python/py-bob-io-image/Portfile
  python/py-bob-io-matlab/Portfile
  python/py-bob-io-video/Portfile
  python/py-bob-io-video/files/patch-ffmpeg-3.0.diff
  python/py-bob-ip-base/Portfile
  python/py-bob-ip-color/Portfile
  python/py-bob-ip-draw/Portfile
  python/py-bob-ip-facedetect/Portfile
  python/py-bob-ip-gabor/Portfile
  python/py-bob-ip-optflow-hornschunck/Portfile
  python/py-bob-ip-optflow-liu/Portfile
  python/py-bob-learn-activation/Portfile
  python/py-bob-learn-boosting/Portfile
  python/py-bob-learn-em/Portfile
  python/py-bob-learn-libsvm/Portfile
  python/py-bob-learn-linear/Portfile
  python/py-bob-learn-mlp/Portfile
  python/py-bob-math/Portfile
  python/py-bob-measure/Portfile
  python/py-bob-sp/Portfile
  python/py-bob/Portfile
Labels: by: member, maintainer: requires approval

#2028 entr: update to 4.1
  sysutils/entr/Portfile
Labels: by: member, maintainer: open, type: update

#2031 fxscintilla: set license to LGPL-2.1+
  x11/fxscintilla/Portfile
Labels: maintainer: requires approval, type: enhancement

#2035 scheme48: avoid conflict with libevent
  lang/scheme48/Portfile
Labels: by: member, maintainer: none

#2032 OpenBLAS: allow universal build
  math/OpenBLAS/Portfile
Labels: by: member, maintainer: open

#2027 texinfo: ensure all libraries are universal
  textproc/texinfo/Portfile
Labels: by: member, maintainer: none

#2025 py-lxml: patch out -isysroot addition
  python/py-lxml/Portfile
  python/py-lxml/files/patch-setupinfo-remove-xcrun-call.diff
Labels: by: member, maintainer: open, maintainer: timeout

#2055 Remove maintainer fastmail.net:konrad.hinsen
  science/gpp4/Portfile
  science/mmdb/Portfile
  science/nMOLDYN/Portfile
Labels: by: member, maintainer: open

#2057 Remove maintainer futurelab.ch:astricker
  perl/p5-perlmagick/Portfile
  ruby/rb-sprockets/Portfile
Labels: by: member, maintainer

#2059 py-gwpy: update to 0.11.0
  python/py-gwpy/Portfile
Labels: maintainer, maintainer: open, type: enhancement, type: update

#2061 hub: update to 2.4.0
  devel/hub/Portfile
Labels: by: member, maintainer: requires approval, type: update

#2036 p5-tcl-ptk: new port, version 0.92
  perl/p5-tcl-ptk/Portfile
  perl/p5-tcl-ptk/files/patch-Makefile.PL.diff
  perl/p5-tcl-ptk/files/patch-Text.pm.diff
  perl/p5-tcl-ptk/files/patch-Widget.pm.diff
Labels: type: submission

#2045 poppler-data: Update to 0.4.9
  graphics/poppler-data/Portfile
Labels: by: member, maintainer: open, type: update

#2060 spring-boot-cli: update to 2.0.3
  java/spring-boot-cli/Portfile
Labels: by: member, maintainer: open, type: update

#2063 crystal: update to 0.25.0
  lang/crystal/Portfile
  lang/crystal/files/patch-compiler.diff
  lang/crystal/files/patch-crypto.diff
  lang/crystal/files/patch-link.diff
  lang/crystal/files/patch-ssl.diff
Labels: maintainer, maintainer: open, type: update

#2026 openfortivpn: new port, version 1.6.0
  net/openfortivpn/Portfile
Labels: type: submission

#2062 Adjust maintainers line of Carles Fernandez ports
  science/gnss-sdr/Portfile
  science/volk-gnss-sdr/Portfile
Labels: by: member, maintainer: open

#2058 Remove maintainer gmail.com:myschizobuddy
  graphics/liblqr/Portfile
  x11/xorg-xf86bigfontproto/Portfile
Labels: by: member, maintainer: requires approval

#2067 grep: add new variant to install as ggrep
  sysutils/grep/Portfile
Labels: maintainer: open, type: enhancement

#2041 gst: update version 3.1->3.2.5
  lang/gst/Portfile
  lang/gst/files/04ac00a8.patch
Labels: by: member, maintainer: none

#2048 Add GitHub handle larryv to maintainers
  devel/autoconf/Portfile
  devel/cloog/Portfile
  devel/creduce/Portfile
  devel/dejagnu/Portfile
  devel/gindent/Portfile
  devel/icmake/Portfile
  devel/isl-devel/Portfile
  devel/libassuan/Portfile
  devel/libksba/Portfile
  devel/libtool/Portfile
  devel/mpfr/Portfile
  devel/pcre/Portfile
  graphics/libjpeg-turbo/Portfile
  lang/llvm-3.3/Portfile
  lang/llvm-3.4/Portfile
  lang/llvm-3.5/Portfile
  lang/llvm-3.6/Portfile
  lang/llvm-3.7/Portfile
  lang/llvm-3.8/Portfile
  lang/llvm-3.9/Portfile
  lang/llvm-4.0/Portfile
  lang/llvm-5.0/Portfile
  lang/llvm-6.0/Portfile
  lang/llvm-devel/Portfile
  multimedia/HandBrake/Portfile
  perl/p5-graveyard/Portfile
  python/py-graveyard/Portfile
  python/py-virtualenv/Portfile
  security/paperkey/Portfile
  shells/yash/Portfile
  shells/zsh/Portfile
  sysutils/asciinema/Portfile
  sysutils/tmux-pasteboard/Portfile
  sysutils/tree/Portfile
  textproc/yodl/Portfile
  www/lynx/Portfile
Labels: by: member, maintainer: requires approval, maintainer: timeout

#2050 Add GitHub handle conallob to maintainers
  python/py-gflags/Portfile
Labels: by: member, maintainer: requires approval, maintainer: timeout

#2051 Add GitHub handle valyukov to maintainers
  python/py-snmp/Portfile
Labels: by: member, maintainer: open, maintainer: timeout

#2052 Remove maintainer gmail.com:michel.sylvan
  python/py-sphinx/Portfile
Labels: by: member, maintainer: open, maintainer: timeout

#2053 Add GitHub handle donkopotamus to maintainers
  python/py-dispatcher/Portfile
Labels: by: member, maintainer: open, maintainer: timeout

#2054 Add GitHub handles roederja and schiebel to maintainers
  devel/mico/Portfile
  devel/spin/Portfile
  lang/eiffelstudio/Portfile
  net/daq/Portfile
Labels: by: member, maintainer: requires approval, maintainer: timeout

#2066 wireguard-tools: new port, version 0.0.20180613
  net/wireguard-tools/Portfile
  net/wireguard-tools/files/patch-genkey.c.diff
Labels: type: submission

#2073 tortoisehg: update to 4.6.1
  lang/vala/Portfile
Labels: by: member, maintainer: open, type: bugfix, type: update

#2069 qalculate: update to version 2.6.0
  math/libqalculate/Portfile
  math/qalculate-gtk/Portfile
Labels: maintainer

#2070 poppler-qt4-mac: version 0.61.1
  graphics/poppler-qt4-mac/Portfile
  graphics/poppler-qt4-mac/files/patch-CVE-2017-18267.diff
  graphics/poppler-qt4-mac/files/patch-bug106417.diff
Labels: by: member, type: submission

#2071 py-poppler-qt4: force rebuild
  python/py-poppler-qt4/Portfile
Labels: by: member, maintainer: open

#2076 ntpsec: update to 1.1.1
  sysutils/ntpsec/Portfile
  sysutils/ntpsec/files/patch-OldPython.diff
  sysutils/ntpsec/files/patch-PreHighSierra.diff
Labels: maintainer, maintainer: open, type: update

#2074 poppler: fix GIR generation during the build
  graphics/poppler/Portfile
  graphics/poppler/files/patch-bug106417.diff
Labels: by: member, maintainer: open, type: bugfix

#2075 emacs: update dependencies for 26.1 and devel
  editors/emacs/Portfile
Labels: by: member, maintainer: open, type: enhancement

#2077 cquery: remove asan variant and update devel
  devel/cquery/Portfile
Labels: by: member, maintainer: open, type: enhancement

#2079 gradle: update to 4.8.1
  devel/gradle/Portfile
Labels: maintainer: open, type: update

#2080 maven3: update to 3.5.4
  java/maven3/Portfile
Labels: maintainer: open, type: update

#2081 neomutt: update to 20180622
  mail/neomutt/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#2084 epiphany: update to 3.28.3.1
  gnome/epiphany/Portfile
  gnome/epiphany/files/patch-post-install-python.diff
Labels: by: member, maintainer: open, type: update

#2085 py-multidict: new port, version 4.3.1
  python/py-multidict/Portfile
Labels: type: enhancement, type: submission

#2086 wireguard-tools: update to 0.0.20180620
  net/wireguard-tools/Portfile
  net/wireguard-tools/files/patch-genkey.c.diff
Labels: maintainer, maintainer: open, type: update

#2087 py-yarl: new port, version 1.2.6
  python/py-yarl/Portfile
Labels: type: enhancement, type: submission

#2091 mpc: whitespace changes only
  audio/mpc/Portfile
Labels: by: member, maintainer: open

#2092 flyway: update to 5.1.3
  java/flyway/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#2082 openjdk10: new submission
  java/openjdk10/Portfile
Labels: type: submission

#2088 igtf-ca-bundle: update to 1.92
  security/igtf-ca-bundle/Portfile
Labels: by: member, maintainer: open, type: enhancement, type: update

#2094 monit: update to v5.25.2
  sysutils/monit/Portfile
Labels: maintainer: none, type: enhancement, type: update

#2102 py-async-timeout: new port, version 3.0.0
  python/py-async-timeout/Portfile
Labels: type: enhancement, type: submission

#2103 screenresolution: New port, version 1.6
  sysutils/screenresolution/Portfile
Labels: by: member, type: submission

#2024 p5-image-exiftool: remove -p5* suffix from binary
  perl/p5-image-exiftool/Portfile
Labels: maintainer: none, type: enhancement

#2104 Update MacPorts homepage URL
  lang/gnat-gcc/Portfile
  python/ansible_select/Portfile
  python/py-cairosvg_select/Portfile
  python/py-html2text_select/Portfile
  python/py-pss_select/Portfile
  python/trepan2_select/Portfile
  security/certsync/Portfile
  sysutils/Pallet/Portfile
  sysutils/mpstats/Portfile
  sysutils/python2_select/Portfile
  sysutils/python3_select/Portfile
  sysutils/python_select/Portfile
Labels: by: member, maintainer: requires approval

#2106 py-aiohttp: new port, version 3.3.2
  python/py-aiohttp/Portfile
Labels: type: enhancement, type: submission
