Repository macports/macports-ports, pull requests merged in 2018-03, with the labels that each got.

#1355 flyway: update to 5.0.7
  java/flyway/Portfile
Labels: maintainer, maintainer: open, type: update

#1354 gradle: update to 4.6
  devel/gradle/Portfile
Labels: maintainer: open, type: update

#1353 terraform: update to 0.11.3
  sysutils/terraform/Portfile
Labels: maintainer, maintainer: open, type: update

#1356 dhcp: update to 4.1-ESV-R15-P1
  net/dhcp/Portfile
  net/dhcp/files/RFC3542.include.patch
Labels: by: member, maintainer: none, type: security fix, type: update

#1357 github-1.0.tcl: always verify TLS certificate
  _resources/port1.0/group/github-1.0.tcl
Labels: by: member

#1360 Sophus: new port
  math/Sophus/Portfile
Labels: type: enhancement, type: submission

#1359 Pangolin: new port
  graphics/Pangolin/Portfile
Labels: type: enhancement, type: submission

#1358 libcaer: new port
  devel/libcaer/Portfile
Labels: type: enhancement, type: submission

#1361 py-gammapy: update to version 0.7
  python/py-gammapy/Portfile
Labels: maintainer, maintainer: open, type: update

#1351 biblatex-biber: remove perl variants
  tex/biblatex-biber/Portfile
Labels: by: member, maintainer: open

#1334 wget: explicit --options and missed dependencies
  net/wget/Portfile
Labels: maintainer: open

#1366 ansifilter: update to 2.9
  textproc/ansifilter/Portfile
Labels: maintainer, maintainer: open, type: enhancement, type: update

#1370 plumed: update to 2.4.1
  science/plumed/Portfile
Labels: maintainer, maintainer: open, type: update

#1367 tmux: update tmux-devel to latest commit
  sysutils/tmux/Portfile
Labels: maintainer, type: enhancement

#1347 mandoc: set default MANPATH
  textproc/mandoc/Portfile
Labels: maintainer, maintainer: requires approval

#1369 gildas: update to 201803a
  science/gildas/Portfile
  science/gildas/files/patch-admin-define-system.sh.diff
  science/gildas/files/patch-admin-gildas-env.sh.diff
Labels: maintainer: requires approval, type: update

#1346 npm5: exclude pre-release version from livecheck
  devel/npm5/Portfile
Labels: by: member, maintainer: open

#1372 net/teleport: update to v2.4.2
  net/teleport/Portfile
Labels: maintainer, maintainer: open, type: update

#1368 keepassxc: update to 2.3.0
  security/KeePassXC/Portfile
  security/KeePassXC/files/patch-no-deployqt.diff
Labels: maintainer, maintainer: open, type: update

#1352 mythtv.28: use perl5 PortGroup, switch to perl5.26
  multimedia/mythtv.28/Portfile
Labels: by: member, maintainer: open

#1378 py-neovim: update to 0.2.3
  python/py-neovim/Portfile
Labels: maintainer: open, type: update

#1377 py-boto3: update to 1.6.3
  python/py-boto3/Portfile
Labels: maintainer, maintainer: open, type: update

#1376 py-s3transfer: update to 0.1.13
  python/py-s3transfer/Portfile
Labels: maintainer: open, type: update

#270 rpcgen: new port
  lang/rpcgen-mt/Portfile
  lang/rpcgen-mt/files/patch-Makefile.diff
  lang/rpcgen-mt/files/patch-nofreebsd.diff
  lang/rpcgen-mt/files/patch-rpc_main.c.diff
Labels: type: submission

#1374 wget: +ssl and +gnutls
  net/wget/Portfile
Labels: maintainer: open

#1380 kotlin: update to 1.2.30
  lang/kotlin/Portfile
Labels: maintainer, maintainer: open, type: update

#1388 spring-boot-cli: update to 2.0.0
  java/spring-boot-cli/Portfile
Labels: maintainer, maintainer: open, type: update

#1384 mandoc: configure takes no arguments
  textproc/mandoc/Portfile
Labels: maintainer, maintainer: open

#1363 Pangolin: fix dependencies list
  graphics/Pangolin/Portfile
Labels: maintainer: none, type: bugfix

#1371 R: Set version normally
  math/R/Portfile
Labels: maintainer: requires approval

#1381 lowdown: LDFLAGS for universal and snowleopardfixes
  textproc/lowdown/Portfile
  textproc/lowdown/files/Makefile.patch
  textproc/lowdown/files/configure.patch
Labels: maintainer

#1395 libfdk-aac: update to version 0.1.6
  audio/libfdk-aac/Portfile
Labels: maintainer, maintainer: open, type: update

#103 cmake: Use $cmake.install_prefix for CMAKE_INSTALL_NAME_DIR, CMAKE_INSTALL_RPATH, and CMAKE_SYSTEM_PREFIX_PATH
  _resources/port1.0/group/cmake-1.0.tcl
  _resources/port1.0/group/cmake-1.1.tcl
Labels: type: enhancement

#1391 demeter, ifeffit: Add GitHub handle to maintainers
  science/demeter/Portfile
  science/ifeffit/Portfile
Labels: maintainer: open

#1399 osmocore: Add talloc dependency
  science/osmocore/Portfile
Labels: maintainer: open

#1389 R, R-app: Add GitHub maintainer handle
  math/R-app/Portfile
  math/R/Portfile
Labels: maintainer: requires approval, maintainer: timeout

#1387 spandsp-devel: Update to 0.0.6pre21
  comms/spandsp-devel/Portfile
Labels: maintainer: requires approval, maintainer: timeout, type: update

#1397 qlandkartegt: rev-bump because of proj upgrade
  gis/qlandkartegt/Portfile
Labels: maintainer

#1400 KeePassXC: update to 2.3.1
  security/KeePassXC/Portfile
Labels: maintainer, maintainer: open, type: update

#1405 ecs-cli: update to 1.4.0
  devel/ecs-cli/Portfile
Labels: maintainer, maintainer: open, type: update

#1402 groovy: update to 2.4.14
  lang/groovy/Portfile
Labels: maintainer, maintainer: open, type: update

#1364 grpc: new port
  devel/grpc/Portfile
  devel/grpc/files/patch-Makefile.diff
Labels: type: submission

#1313 cad/gtkwave: v3.3.87, using gtk-osx-application-gtk2
  cad/gtkwave/Portfile
Labels: maintainer: none, type: bugfix

#1407 neovim: Restore mouse support to neovim 0.2.2
  editors/neovim/Portfile
  editors/neovim/files/patch-mouse-ncurses.diff
Labels: maintainer: open, type: bugfix

#1410 py-neovim: update to 0.2.4
  python/py-neovim/Portfile
Labels: maintainer: open, type: update

#1412 go-ethereum: new port @1.8.2
  finance/go-ethereum/Portfile
Labels: by: member, type: submission

#1404 maven3: update to 3.5.3
  java/maven3/Portfile
Labels: maintainer: requires approval, type: update

#1338 shfmt: new port
  devel/shfmt/Portfile
Labels: type: submission

#1418 enchant2: Use release download
  textproc/enchant2/Portfile
Labels: by: member

#1422 chromedriver: update to 2.36
  www/chromedriver/Portfile
Labels: by: member, maintainer: none, type: update

#1424 bazel: update to 0.11.1
  devel/bazel/Portfile
Labels: maintainer: open, type: update

#1403 py-kombine @0.8.3: new port
  python/py-kombine/Portfile
Labels: type: enhancement, type: submission

#1425 Update Tesseract to 03.05.01
  textproc/tesseract/Portfile
Labels: maintainer

#1423 py-barnaba: submission
  python/py-barnaba/Portfile
Labels: type: submission

#1406 git-sizer @1.0.0: new port
  devel/git-sizer/Portfile
Labels: type: submission

#1417 pcre2: Update to 10.31
  devel/pcre/Portfile
Labels: by: member, maintainer: requires approval, maintainer: timeout, type: update

#1419 salt: update to version 2017.7.4
  sysutils/salt/Portfile
Labels: maintainer, type: bugfix, type: update

#1427 qpid-proton: update to version 0.21.0
  net/qpid-proton/Portfile
Labels: maintainer: open, type: enhancement, type: update

#1421 devel/automake: update to 1.16.1
  devel/automake/Portfile
  devel/libtool/Portfile
Labels: by: member, maintainer: requires approval, maintainer: timeout, type: update

#1428 net/teleport: update to v2.5.1
  net/teleport/Portfile
Labels: maintainer, maintainer: open, type: update

#1411 KeePassXC: fix building on 10.7-10.9
  security/KeePassXC/Portfile
Labels: maintainer, maintainer: open, type: bugfix

#1430 muttprint: fix perl 5.26 compatibility
  mail/muttprint/Portfile
  mail/muttprint/files/muttprintperl5.26fix.patch
Labels: by: member, maintainer: none

#1434 net/teleport: update to v2.5.2
  net/teleport/Portfile
Labels: maintainer, maintainer: open, type: update

#1433 mingw-w64 binutils: apply upstream patch for broken static constructors in linked PE files
  cross/i686-w64-mingw32-binutils/Portfile
  cross/i686-w64-mingw32-binutils/files/patch-upstream-fix-pe-static-constructors.diff
  cross/x86_64-w64-mingw32-binutils/Portfile
  cross/x86_64-w64-mingw32-binutils/files/patch-upstream-fix-pe-static-constructors.diff
Labels: maintainer: open, type: bugfix

#1436 mpstats: include requested port information
  sysutils/mpstats/Portfile
  sysutils/mpstats/files/mpstats.tcl
Labels: by: member, maintainer: open, type: enhancement

#1441 py-notebook: update to 5.4.1
  python/py-notebook/Portfile
Labels: by: member, maintainer: open, type: security fix, type: update

#1440 wget: explicitly enable opie, digest, ntlm, debug
  net/wget/Portfile
Labels: maintainer: open

#1437 py-flask: update to 0.12.2
  python/py-flask/Portfile
Labels: by: member, maintainer: open, type: update

#1432 py-django: update to 1.11.11
  python/py-django/Portfile
Labels: by: member, maintainer: open, type: security fix, type: update

#1438 ola: update to 0.10.6 maintainer
  net/ola/Portfile
Labels: maintainer, type: update

#1439 app PortGroup : add support for x11 applications
  _resources/port1.0/group/app-1.0.tcl
Labels: by: member

#1435 libsdl_sound: Fix building with physfs 3.0+
  audio/libsdl_sound/Portfile
  audio/libsdl_sound/files/patch-playsound-physfsrwops.h.diff
Labels: maintainer: none, type: bugfix

#1444 ecs-cli: update to 1.4.1
  devel/ecs-cli/Portfile
Labels: maintainer, maintainer: open, type: update

#1446 terraform: update to 0.11.4
  sysutils/terraform/Portfile
Labels: maintainer, maintainer: open, type: update

#1365 libzzip: update to 0.13.69
  archivers/libzzip/Portfile
  archivers/libzzip/files/patch-zzip_Makefile.in.diff
  archivers/libzzip/files/yosemite-libtool.patch
Labels: by: member, maintainer: none, type: update

#1450 *-binutils: update to 2.30
  _resources/port1.0/group/crossbinutils-1.0.tcl
  cross/arm-aout-binutils/Portfile
  cross/arm-elf-binutils/Portfile
  cross/arm-none-eabi-binutils/Portfile
  cross/arm-none-linux-gnueabi-binutils/Portfile
  cross/avr-binutils/Portfile
  cross/i386-elf-binutils/Portfile
  cross/m68k-elf-binutils/Portfile
  cross/mips-elf-binutils/Portfile
  cross/ppc-linux-binutils/Portfile
  cross/spu-binutils/Portfile
  cross/x86_64-elf-binutils/Portfile
  devel/binutils/Portfile
Labels: by: member, maintainer: requires approval, type: update

#1401 devel/boost: make boost-numpy extension a subport…
  devel/boost/Portfile
  devel/boost/files/patch-disable-numpy-extension.diff
Labels: maintainer: open, type: bugfix, type: enhancement

#1447 mediainfo: revbump after wxWidgets-3.2 update
  multimedia/mediainfo/Portfile
Labels: by: member, maintainer: requires approval

#1459 terraform: update to 0.11.5
  sysutils/terraform/Portfile
Labels: maintainer, maintainer: open, type: update

#1458 ecs-cli: update to 1.4.2
  devel/ecs-cli/Portfile
Labels: maintainer, maintainer: open, type: update

#1461 gromacs: update to 2016.5
  science/gromacs/Portfile
Labels: maintainer: open, type: update

#1460 dupd: update to version 1.6
  sysutils/dupd/Portfile
Labels: maintainer, type: update

#1465 neofetch @3.3.0: new port
  sysutils/neofetch/Portfile
Labels: type: submission

#1451 mipsel-linux*: delete ports
  cross/mipsel-linux-binutils/Portfile
  cross/mipsel-linux-binutils/files/100-uclibc-conf.patch
  cross/mipsel-linux-binutils/files/110-uclibc-libtool-conf.patch
  cross/mipsel-linux-binutils/files/300-001_ld_makefile_patch.patch
  cross/mipsel-linux-binutils/files/300-006_better_file_error.patch
  cross/mipsel-linux-binutils/files/300-012_check_ldrunpath_length.patch
  cross/mipsel-linux-binutils/files/702-binutils-skip-comments.patch
  cross/mipsel-linux-binutils/files/spacepad.diff
  cross/mipsel-linux-gcc34/Portfile
  cross/mipsel-linux-gcc34/files/100-uclibc-conf.patch
  cross/mipsel-linux-gcc34/files/200-uclibc-locale.patch
  cross/mipsel-linux-gcc34/files/300-libstdc++-pic.patch
  cross/mipsel-linux-gcc34/files/601-gcc34-arm-ldm.patch
  cross/mipsel-linux-gcc34/files/602-sdk-libstdc++-includes.patch
  cross/mipsel-linux-gcc34/files/700-pr15068-fix.patch
  cross/mipsel-linux-gcc34/files/800-arm-bigendian.patch
  cross/mipsel-linux-gcc34/files/810-arm-bigendian-uclibc.patch
  cross/mipsel-linux-gcc34/files/arm-softfloat.patch.conditional
  cross/mipsel-linux-kernel-headers/Portfile
  cross/mipsel-linux-kernel-headers/files/config
  cross/mipsel-linux-uclib-headers/Portfile
  cross/mipsel-linux-uclib-headers/files/100-gcc4_fix.patch
  cross/mipsel-linux-uclib-headers/files/110-inet6_hosts_resolve.patch
  cross/mipsel-linux-uclib-headers/files/120-more_standard_math.patch
  cross/mipsel-linux-uclib-headers/files/config.mips
  cross/mipsel-linux-uclib/Portfile
  cross/mipsel-linux-uclib/files/100-gcc4_fix.patch
  cross/mipsel-linux-uclib/files/110-inet6_hosts_resolve.patch
  cross/mipsel-linux-uclib/files/120-more_standard_math.patch
  cross/mipsel-linux-uclib/files/config.mips
  cross/mipsel-linux-uclib/files/patch-Makefile
Labels: by: member, maintainer: none

#1454 *-rtems-{gcc|binutils}: remove ports
  cross/arm-rtems-binutils/Portfile
  cross/arm-rtems-gcc/Portfile
  cross/arm-rtems-gcc/files/patch-newlib-libc-configure.diff
  cross/i386-rtems-binutils/Portfile
  cross/i386-rtems-gcc/Portfile
  cross/i386-rtems-gcc/files/patch-newlib-libc-configure.diff
  cross/lm32-rtems-binutils/Portfile
  cross/m68k-rtems-binutils/Portfile
  cross/m68k-rtems-gcc/Portfile
  cross/m68k-rtems-gcc/files/patch-newlib-libc-configure.diff
  cross/mips-rtems-binutils/Portfile
  cross/mips-rtems-gcc/Portfile
  cross/mips-rtems-gcc/files/patch-newlib-libc-configure.diff
  cross/powerpc-rtems-binutils/Portfile
  cross/powerpc-rtems-gcc/Portfile
  cross/powerpc-rtems-gcc/files/patch-newlib-libc-configure.diff
  cross/sh-rtems-binutils/Portfile
  cross/sh-rtems-gcc/Portfile
  cross/sh-rtems-gcc/files/patch-newlib-libc-configure.diff
  cross/sparc-rtems-binutils/Portfile
  cross/sparc-rtems-gcc/Portfile
  cross/sparc-rtems-gcc/files/patch-newlib-libc-configure.diff
Labels: by: member, maintainer: requires approval

#1453 i386-mingw32: replace by i686-mingw32-w64
  cross/i386-mingw32-binutils/Portfile
  cross/i386-mingw32-gcc/Portfile
  cross/i386-mingw32-gcc/files/patch-fastjar-Makefile.in
  cross/i386-mingw32-gcc/files/patch-gcc-Makefile.in
  cross/i386-mingw32-libunicows/Portfile
  cross/i386-mingw32-runtime/Portfile
  cross/i386-mingw32-w32api/Portfile
  cross/i386-mingw32/Portfile
Labels: by: member, maintainer: none, type: submission

#1442 gdal-grass: add MIT license, postgresql10 variant
  gis/gdal-grass/Portfile
Labels: by: member, maintainer: requires approval, maintainer: timeout, type: enhancement

#1466 harfbuzz: Add comment, won't need compiler blacklist on next update
  graphics/harfbuzz/Portfile
Labels: maintainer: open

#1468 new ports: libsass, sassc
  www/libsass/Portfile
  www/sassc/Portfile
Labels: by: member, type: enhancement, type: submission

#1473 rtptools: update to 1.22
  audio/rtptools/Portfile
Labels: maintainer, type: update

#1463 virt-manager: Update to version 1.5.1
  gnome/virt-manager/Portfile
Labels: by: member, maintainer: open, type: update

#1478 kotlin: update to 1.2.31
  lang/kotlin/Portfile
Labels: maintainer, maintainer: open, type: update

#1127 Okapi: new port
  aqua/Okapi/Portfile
Labels: type: submission

#1481 editorconfig-core-c: Update to 0.12.2
  devel/editorconfig-core-c/Portfile
Labels: by: member, maintainer: open, type: update

#1484 gimp-jp2: fix build by updating automake dependency
  graphics/gimp-jp2/files/patch-autogen.sh.diff
Labels: type: bugfix

#1485 gimp-lqr-plugin: fix by updating automake dependency
  graphics/gimp-lqr-plugin/files/patch-autogen.sh.diff
Labels: type: bugfix

#1472 cargo, rust: Require cmake provided by MacPorts
  devel/cargo/Portfile
  lang/rust/Portfile
Labels: by: member, maintainer: requires approval

#1482 pbzx: New port, version 20180319
  archivers/pbzx/Portfile
Labels: by: member, type: submission

#1486 py-pygit2: Add py-six to depends_lib
  python/py-pygit2/Portfile
Labels: by: member, maintainer: open, type: bugfix

#1456 Update to the Pygments port to support the select feature
  python/py-pygments/Portfile
  python/py-pygments/files/py26-pygments
  python/py-pygments/files/py27-pygments
  python/py-pygments/files/py33-pygments
  python/py-pygments/files/py34-pygments
  python/py-pygments/files/py35-pygments
  python/py-pygments/files/py36-pygments
  python/pygments_select/Portfile
  python/pygments_select/files/base
  python/pygments_select/files/none
Labels: maintainer: open, type: enhancement, type: submission

#1490 py-absl: update to 0.1.12
  python/py-absl/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#1491 mediainfo, mediainfolib: Update to 18.03.1
  devel/mediainfolib/Portfile
  multimedia/mediainfo/Portfile
Labels: by: member, maintainer: requires approval, type: update

#1493 LanguageTool: update to 4.1
  aqua/LanguageTool/Portfile
Labels: maintainer, maintainer: open, type: update

#1492 woff2: update to 1.0.2
  print/woff2/Portfile
Labels: maintainer, maintainer: open, type: update

#1487 rust: Downgrade to llvm-4.0
  lang/rust/Portfile
Labels: by: member, maintainer: requires approval, type: bugfix

#1501 ruby-build: update to 20180329
  ruby/ruby-build/Portfile
Labels: maintainer: open, type: update

#1498 npm5: update to 5.8.0
  devel/npm5/Portfile
Labels: by: member, maintainer: open, type: update

#1494 gildas: add -openmp variant
  science/gildas/Portfile
  science/gildas/files/patch-admin-define-system.sh.diff
Labels: by: member, maintainer: requires approval, type: enhancement

#1504 Add GitHub handle dstrubbe
  devel/svn2cl/Portfile
  editors/xemacs/Portfile
  math/feast/Portfile
  math/pfft/Portfile
  science/OpenCSG/Portfile
  science/ape/Portfile
  science/berkeleygw/Portfile
  science/etsf_io/Portfile
  science/gromacs/Portfile
  science/hpl/Portfile
  science/libtcd/Portfile
  science/libxc/Portfile
  science/octopus/Portfile
  science/openscad/Portfile
  science/paraview/Portfile
  science/quantum-espresso/Portfile
  science/sparskit/Portfile
  science/wannier90/Portfile
  science/xcrysden/Portfile
  science/xtide/Portfile
Labels: by: member, maintainer: requires approval

#1506 Add GitHub handle ecronin
  net/blackbag/Portfile
  net/libpcapnav/Portfile
  net/nemesis/Portfile
  sysutils/boxbackup/Portfile
  sysutils/lsdvd/Portfile
  www/duckytool/Portfile
Labels: by: member, maintainer: open

#1470 ntpsec: Fixes build for macOS <10.13.
  sysutils/ntpsec/Portfile
  sysutils/ntpsec/files/patch-PreHighSierra.diff
Labels: maintainer: open, type: bugfix

#989 py-pew: new port
  python/py-pew/Portfile
Labels: type: submission

#1511 ntpsec: Fixes build when default Python is old.
  sysutils/ntpsec/Portfile
  sysutils/ntpsec/files/patch-OldPython.diff
Labels: maintainer, maintainer: open, type: bugfix

#1510 groovy: update to 2.4.15
  lang/groovy/Portfile
Labels: maintainer, maintainer: open, type: update
