Repository macports/macports-ports, pull requests merged in 2018-02, with the labels that each got.

#1293 py-m2crypto: update to 0.28.2
  python/py-m2crypto/Portfile
Labels: maintainer, maintainer: open, type: update

#1300 gradle: update to 4.5.1
  devel/gradle/Portfile
Labels: maintainer, maintainer: open, type: update

#1299 rsync: update to version 3.1.3
  net/rsync/Portfile
  net/rsync/files/patch-crtimes.diff
  net/rsync/files/patch-fileflags.diff
Labels: maintainer: none, type: bugfix, type: enhancement, type: security fix, type: update

#1298 salt: update to version 2017.7.3
  sysutils/salt/Portfile
  sysutils/salt/files/patch-macports_syspaths.diff
Labels: maintainer, type: enhancement, type: update

#1297 gwyddion: update to 2.50
  science/gwyddion/Portfile
  science/gwyddion/files/gwyddion.quartz
Labels: maintainer: requires approval, type: update

#1302 rsync: remove unused patch files
  net/rsync/Portfile
  net/rsync/files/patch-hfs-compression-options.diff
  net/rsync/files/patch-hfs-compression.diff
Labels: maintainer: none

#1303 faust-devel: update to latest upstream
  audio/faust-devel/Portfile
Labels: maintainer, type: update

#1304 faust: update to 2.5.21
  audio/faust/Portfile
Labels: maintainer: requires approval, type: update

#1305 mkvtoolnix: update to v20.0.0
  multimedia/mkvtoolnix/Portfile
Labels: maintainer: open, type: update

#1306 pspg: new port submission
  databases/pspg/Portfile
Labels: by: member, type: submission

#1308 pugixml: update to v1.8.1 and make c++11 explicit
  textproc/pugixml/Portfile
Labels: maintainer: open, type: update

#1310 sslh: update to 1.19c
  net/sslh/Portfile
Labels: maintainer, maintainer: open, type: update

#1307 multiple ports: change gnome.org to https
  gnome/adwaita-icon-theme/Portfile
  gnome/alacarte/Portfile
  gnome/gitg/Portfile
  gnome/gnome-control-center/Portfile
  gnome/gnome-desktop/Portfile
  gnome/gnome-devel-docs/Portfile
  gnome/gnome-menus/Portfile
  gnome/gnome-settings-daemon/Portfile
  gnome/gnome-themes-standard/Portfile
  gnome/gnome/Portfile
  gnome/gsettings-desktop-schemas/Portfile
  gnome/libgnomekbd/Portfile
  gnome/libgtop/Portfile
  gnome/mm-common/Portfile
  gnome/vte-gtk2-compat/Portfile
  graphics/bitstream-vera/Portfile
  xfce/vte-gtk2-xfce/Portfile
Labels: maintainer: requires approval

#1311 kotlin: fix 'kotlin -version'
  lang/kotlin/Portfile
Labels: maintainer, maintainer: open, type: bugfix

#1217 opusfile: patch libressl version confusion
  audio/opusfile/Portfile
  audio/opusfile/files/patch-libressl.diff
Labels: maintainer: open

#1319 Rebuild port with boost 1.66.0
  science/plumed/Portfile
Labels: maintainer, maintainer: open

#1321 qpid-proton: update to version 0.20.0
  net/qpid-proton/Portfile
Labels: maintainer: open, type: enhancement, type: update

#1322 rust: update to 1.24.0
  lang/rust/Portfile
Labels: maintainer: requires approval, type: update

#1324 py-gwpy: update to 0.8.0
  python/py-gwpy/Portfile
Labels: maintainer: none, type: enhancement, type: update

#1315 py-mdtraj: new port submission
  python/py-mdtraj/Portfile
Labels: type: submission

#1325 bali-phy: Blacklist compilers that don't know -std=c++14
  science/bali-phy/Portfile
Labels: maintainer: none

#1327 py-gwpy: update to 0.8.1
  python/py-gwpy/Portfile
Labels: maintainer: none, type: bugfix, type: update

#1329 libfilezilla: update to 0.12.0
  devel/libfilezilla/Portfile
Labels: maintainer, maintainer: open, type: update

#1318 libsbml: update to version 5.16.0
  science/libsbml/Portfile
  science/libsbml/files/patch-python-mp.diff
Labels: maintainer: none, type: enhancement, type: update

#1330 mandoc: don't repeat the ./configure's job
  textproc/mandoc/Portfile
Labels: maintainer, maintainer: open

#1317 FreeRDP: Update to 2.0.0-rc1
  net/FreeRDP/Portfile
  net/FreeRDP/files/patch-client_mac_mrdview.diff
  net/FreeRDP/files/patch-ffmpeg-3.0.diff
  net/FreeRDP/files/patch-freerdp.pc.in.diff
  net/FreeRDP/files/patch-winpr-include-winpr-platform.h.diff
Labels: maintainer: none, type: update

#1323 asciinema: update to 2.0.0
  sysutils/asciinema/Portfile
Labels: by: member, maintainer: requires approval, maintainer: timeout, type: update

#1331 qgis: fix typo; allow for QT5 error to be shown
  gis/qgis/Portfile
Labels: maintainer: requires approval

#1314 math/libfaiss: add port.
  math/libfaiss/Portfile
Labels: type: submission

#1337 unixODBC: update to 2.3.5
  databases/unixODBC/Portfile
Labels: by: member, maintainer: none, type: security fix, type: update

#1339 fonttools: update to 3.22.0
  print/fonttools/Portfile
Labels: maintainer: none, type: update

#1341 bazel: Update to version 0.11.0
  devel/bazel/Portfile
Labels: maintainer, maintainer: open, type: bugfix, type: enhancement, type: update

#1342 Remove myself as maintainer for soxr
  audio/soxr/Portfile
Labels: maintainer: open

#1345 texstudio: update to 2.12.8
  editors/texstudio/Portfile
Labels: maintainer, maintainer: open, type: update

#1343 cask: update to 0.8.3
  devel/cask/Portfile
Labels: maintainer, maintainer: open, type: update

#1349 vit: use perl5.26
  office/vit/Portfile
Labels: by: member, maintainer: open

#1348 cpan2port: fetch from github, use perl5.26
  sysutils/cpan2port/Portfile
Labels: by: member, maintainer: open, type: update
