Repository macports/macports-ports, pull requests merged in 2018-11, with the labels that each got.

#2909 curl-ca-bundle: update to dc2f7806fbc1 / NSS 3.40
  net/curl/Portfile
Labels: by: member, maintainer: requires approval, type: update

#2901 openexr: update version 2.2.1->2.3.0
  aqua/luminance-hdr/Portfile
  devel/libdevil/Portfile
  gnome/gstreamer1-gst-plugins-bad/Portfile
  graphics/ImageMagick/Portfile
  graphics/OpenSceneGraph-devel/Portfile
  graphics/OpenSceneGraph/Portfile
  graphics/Pangolin/Portfile
  graphics/ctlang/Portfile
  graphics/ctlang/files/patch-CtlSimdInst.cpp.diff
  graphics/darktable/Portfile
  graphics/enblend/Portfile
  graphics/exact-image/Portfile
  graphics/gegl-0.3/Portfile
  graphics/gegl-0.4/Portfile
  graphics/gegl-devel/Portfile
  graphics/gimp2-devel/Portfile
  graphics/gimp2/Portfile
  graphics/gimp3-devel/Portfile
  graphics/hugin-app/Portfile
  graphics/opencv/Portfile
  graphics/openexr/Portfile
  graphics/openexr/files/patch-64bit_types.diff
  graphics/openexr/files/patch-IlmImf-ImfSystemSpecific.h.diff
  graphics/openexr/files/patch-IlmImf-Makefile.diff
  graphics/openexr/files/patch-configure.diff
  graphics/openexr/files/patch-fltk.diff
  graphics/openexr/files/patch-search_order.diff
  graphics/openimageio/Portfile
  graphics/povray/Portfile
  graphics/synfig/Portfile
  graphics/vigra/Portfile
  graphics/vips/Portfile
  kde/kde4-runtime/Portfile
  kde/kdelibs4/Portfile
  science/gmic/Portfile
Labels: by: member, maintainer

#2918 librttopo: new port
  gis/librttopo/Portfile
Labels: type: enhancement, type: submission

#2929 calcurse: update homepage to use https
  sysutils/calcurse/Portfile
Labels: maintainer: open

#2923 yarn: Update to version 1.12.1.
  devel/yarn/Portfile
Labels: maintainer: open, type: update

#2933 py-spyder-devel: update to 779fd0d (20181103)
  python/py-spyder-devel/Portfile
Labels: maintainer, maintainer: open, type: update

#2934 py-uncertainties: update to 3.0.3
  python/py-uncertainties/Portfile
Labels: maintainer: open, type: update

#2937 py-pluggy: update to 0.8.0
  python/py-pluggy/Portfile
Labels: maintainer: open, type: update

#2916 gdal: add sqlite3 prefix to configuration arguments
  gis/gdal/Portfile
Labels: maintainer: open, type: bugfix

#2938 py-future: update to 0.17.1
  python/py-future/Portfile
Labels: maintainer: open, type: update

#2892 libopus: update to 1.3
  audio/libopus/Portfile
Labels: maintainer: open, type: update

#2926 dvisvgm: update to 2.6.1
  graphics/dvisvgm/Portfile
Labels: by: member, maintainer: none, type: update

#2935 Io: Update to version 2017.09.06
  lang/Io/Portfile
Labels: maintainer: none, type: update

#2943 ffmpeg: update to 4.0.3
  multimedia/ffmpeg/Portfile
Labels: by: member, maintainer: open, type: security fix, type: update

#2877 yarn: use NodeJS v10
  devel/yarn/Portfile
Labels: maintainer: open, type: enhancement

#2927 Use https for www.vanheusden.com
  net/gibberish/Portfile
  net/httping/Portfile
  net/tcping/Portfile
  security/nasty/Portfile
  sysutils/andatool/Portfile
  sysutils/multitail/Portfile
  sysutils/truncate/Portfile
  textproc/unsort/Portfile
  www/sgwi/Portfile
Labels: by: member, maintainer, type: enhancement

#2931 MoarVM, nqp, rakudo: update to 2018.10
  lang/MoarVM/Portfile
  lang/nqp/Portfile
  lang/rakudo/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#2941 p5-clone: update to version 0.41
  perl/p5-clone/Portfile
Labels: by: member, maintainer: open, type: update

#2940 p5-yaml: update to version 1.27
  perl/p5-yaml/Portfile
Labels: by: member, maintainer: open, type: update

#2944 tomcat-native: update to version 1.2.18
  java/tomcat-native/Portfile
Labels: maintainer, maintainer: open, type: update

#2948 gnupg2: update to 2.2.11
  mail/gnupg2/Portfile
Labels: by: member, maintainer: open, type: update

#2945 py-BitVector: update to 3.4.8, add py37 subport
  python/py-BitVector/Portfile
Labels: maintainer: open, type: update

#2921 py-canmatrix: new port
  python/py-canmatrix/Portfile
Labels: type: enhancement, type: submission

#2949 gildas: updated to 201811a
  science/gildas/Portfile
Labels: maintainer

#2928 py-django: update to 2.1.3
  python/py-django/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#2947 py-pysvn: Don't use rpath
  python/py-pysvn/Portfile
Labels: by: member, maintainer: open

#2896 gerris/gts/gfsview: switch to snapshot versions
  math/gts/Portfile
  math/gts/files/patch-examples-happrox.c.diff
  science/gerris/Portfile
  science/gerris/files/patch-Makefile.in
  science/gerris/files/patch-fortran_lib.diff
  science/gerris/files/patch-hypre_no_mpi.diff
  science/gerris/files/patch-lis_names.diff
  science/gfsview/Portfile
Labels: by: member, maintainer: open, type: enhancement

#2953 field3d: rebuild after upgrade to ilmbase 2.3.0
  graphics/field3d/Portfile
Labels: by: member, maintainer: requires approval, type: bugfix

#2936 py-pytest: update to 3.10.0, update patch
  python/py-pytest/Portfile
  python/py-pytest/files/patch-setup.cfg.diff
  python/py-pytest/files/patch-setup.py.diff
Labels: maintainer: open, type: update

#2942 p5-file-slurp: update to version 9999.24
  perl/p5-file-slurp/Portfile
Labels: by: member, maintainer: requires approval, type: update

#2950 tcl: don't build bundled sqlite3 package. Use sqlite3-tcl instead.
  lang/tcl/Portfile
Labels: by: member, maintainer: open, type: enhancement

#2956 hugo: update to 0.51
  www/hugo/Portfile
Labels: maintainer, maintainer: open, type: update

#2957 youtube-dl: Update to 2018.11.07
  net/youtube-dl/Portfile
Labels: maintainer: open, type: update

#2958 tor-devel: update to 0.3.5.4-alpha
  security/tor-devel/Portfile
Labels: maintainer: none, type: update

#2962 py-keyring: update to 16.0.1
  python/py-keyring/Portfile
Labels: maintainer, maintainer: open, type: update

#2963 py-pbr: update to 5.1.1
  python/py-pbr/Portfile
Labels: maintainer: none, type: update

#2968 py-httplib2: add py37 support
  python/py-httplib2/Portfile
Labels: by: member, maintainer: open

#2972 GPXSee: update to 6.3
  gis/GPXSee/Portfile
  gis/GPXSee/files/patch-src_GUI_app_cpp.diff
Labels: maintainer, maintainer: open, type: enhancement, type: update

#2973 tcptrace: Update upstream urls
  net/tcptrace/Portfile
Labels: maintainer: none, type: bugfix

#2976 jdupes: use right compiler and universal build flags
  sysutils/jdupes/Portfile
Labels: maintainer, maintainer: open, type: bugfix

#2975 newsboat: update to 2.13
  net/newsboat/Portfile
Labels: maintainer, maintainer: open, type: bugfix, type: update

#2960 npm6: use NodeJS v10
  devel/npm6/Portfile
Labels: maintainer: open, type: enhancement

#2982 maven3: update to 3.6.0
  java/maven3/Portfile
Labels: by: member, maintainer: open, type: update

#2978 py-matplotlib: update to 3.0.2
  python/py-matplotlib/Portfile
Labels: maintainer: open, type: update

#2983 py-awscli: update to 1.16.52
  python/py-awscli/Portfile
  python/py-botocore/Portfile
Labels: by: member, maintainer: open, type: update

#2964 py-plyvel: Fix build on 10.6 and earlier
  python/py-plyvel/Portfile
  python/py-plyvel/files/setup.py.patch
Labels: by: member, maintainer: open

#2981 libuv: enable tests
  devel/libuv/Portfile
Labels: by: member, maintainer: open, type: enhancement

#2984 py-boto3: update to 1.9.42
  python/py-boto3/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#2986 pdns-recursor: update to 4.0.9
  net/pdns-recursor/Portfile
Labels: by: member, maintainer, maintainer: open, type: security fix, type: update

#2965 wireshark2: fix build with +lua when lua5.3 is installed
  net/wireshark2/Portfile
  net/wireshark2/files/patch-wireshark2-luafix-001.diff
  net/wireshark2/files/patch-wireshark2-luafix-002.diff
Labels: by: member, maintainer: requires approval, type: bugfix

#2987 tectonic: update to 0.1.11
  tex/tectonic/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#2991 meson: update to 0.48.2
  devel/meson/Portfile
Labels: maintainer, maintainer: open, type: update

#2990 faust-devel, faustlive-devel: update to latest git
  audio/faust-devel/Portfile
  audio/faustlive-devel/Portfile
  audio/faustlive-devel/files/patch-Darwin-Makefile.diff
Labels: maintainer, type: update

#2992 wxmsw: remove a broken outdated port
  cross/wxmsw/Portfile
Labels: by: member, maintainer: none, type: bugfix

#2920 openjdk8, openjdk11: Add new port for OpenJDK 8 and migrate OpenJDK 11 to AdoptOpenJDK
  java/openjdk10/Portfile
  java/openjdk8/Portfile
Labels: maintainer, maintainer: open, type: enhancement, type: submission

#2998 p5-cryptx: update to version 0.062
  perl/p5-cryptx/Portfile
Labels: by: member, maintainer: open, type: update

#3003 libuv: peg at 1.23.2 for Tiger
  devel/libuv/Portfile
  devel/libuv/files/patch-libuv-1-23-2-tiger.diff
  devel/libuv/files/patch-makefile-am-no-libutil-on-Tiger.diff
Labels: by: member, maintainer: open, type: bugfix, type: enhancement

#3008 tkimg: fix spelling in comment
  graphics/tkimg/Portfile
Labels: maintainer: open, type: enhancement

#3011 mpich: Update -devel; remove suspect flag.
  science/mpich/Portfile
Labels: by: member, maintainer, maintainer: open

#3005 astyle: Build using cmake
  devel/astyle/Portfile
  devel/astyle/files/patch-CMakeLists.txt.diff
  devel/astyle/files/patch-Makefile.diff
Labels: by: member, maintainer: none

#3010 postgresql11: Add LLVM_CONFIG to env
  databases/postgresql11/Portfile
Labels: maintainer: requires approval

#3018 consul: update to 1.3.1
  net/consul/Portfile
Labels: maintainer, maintainer: open, type: update

#3017 vault: update to 0.11.5
  security/vault/Portfile
Labels: maintainer, maintainer: open, type: update

#3015 py-autopep8: update to 1.4.3
  python/py-autopep8/Portfile
Labels: maintainer, maintainer: open, type: update

#3013 percona-toolkit: update to 3.0.12
  databases/percona-toolkit/Portfile
Labels: maintainer: open, type: enhancement, type: update

#3014 jmol: update to 14.29.28
  science/jmol/Portfile
Labels: maintainer, maintainer: open, type: update

#2966 Io: fix of outdated python dependency
  lang/Io/Portfile
Labels: maintainer, maintainer: open

#3024 micronaut: update to 1.0.1
  java/micronaut/Portfile
Labels: maintainer, maintainer: open, type: bugfix, type: update

#3023 openjdk11-openj9: new submission for OpenJDK 11 with OpenJ9 VM
  java/openjdk8/Portfile
Labels: maintainer, maintainer: open

#3021 util-linux: peg at v2.32.1 for < darwin 14
  devel/util-linux/Portfile
Labels: by: member, maintainer: open

#3029 tix: patch tixPort.h for +quartz
  x11/tix/Portfile
  x11/tix/files/patch-tk_x11.diff
Labels: maintainer: none, type: bugfix

#3025 wireguard-tools: update to 0.0.20181115
  net/wireguard-tools/Portfile
Labels: maintainer, maintainer: open, type: update

#3012 cmake: fix build on Tiger
  devel/cmake/Portfile
  devel/cmake/files/patch-cmake-3-12-libuv-tiger.diff
Labels: by: member, maintainer: requires approval

#3030 consul: update to 1.4.0
  net/consul/Portfile
Labels: maintainer, maintainer: open, type: update

#3032 tor-devel: update to 0.3.5.5-alpha
  security/tor-devel/Portfile
Labels: maintainer: none, type: update

#3033 iTerm2: Split pre/post XC10 versions.
  aqua/iTerm2/Portfile
  aqua/iTerm2/files/patch-Makefile-XC10.diff
Labels: by: member, maintainer: open

#3031 scribus-devel: patch to properly detect Mojave
  print/scribus-devel/Portfile
  print/scribus-devel/files/CMakeLists.txt.patch
Labels: maintainer: none

#3035 minio[-mc]: Update to lastets.
  www/minio-mc/Portfile
  www/minio/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#3009 faust-devel: add missing cmake dependency (fixes trac #57593)
  audio/faust-devel/Portfile
Labels: maintainer

#3040 py-qtpy: update to 1.5.2
  python/py-qtpy/Portfile
Labels: maintainer: open, type: update

#3036 emacs-mac-app: update to 7.4
  aqua/emacs-mac-app/Portfile
Labels: by: member, maintainer: none, type: update

#3038 py-alabaster: update to 0.7.12
  python/py-alabaster/Portfile
Labels: maintainer: none, type: update

#3039 py-coverage: update to 4.5.2
  python/py-coverage/Portfile
  python/py-coverage/files/patch-setup.py.diff
Labels: maintainer: open, type: update

#3042 py-cairo: update to 1.18.0
  python/py-cairo/Portfile
Labels: maintainer: none, type: update

#3043 py-keyring: update to 16.1.0
  python/py-keyring/Portfile
Labels: maintainer, maintainer: open, type: update

#3028 zstd: Update to 1.3.7
  archivers/zstd/Portfile
  archivers/zstd/files/cpuid-i386.patch
  archivers/zstd/files/universal.patch
Labels: by: member, maintainer: open, type: update

#3019 py-virtualenv: update to 16.1.0
  python/py-virtualenv/Portfile
Labels: maintainer: requires approval, maintainer: timeout, type: update

#2993 p5-tcl: update options provided to Makefile.PL, add myself as co-maintainer
  perl/p5-tcl/Portfile
Labels: maintainer: open, type: enhancement

#3044 py-serial: Add Python 3.7 subport.
  python/py-serial/Portfile
Labels: maintainer: open, type: enhancement

#3046 py-qdarkstyle: update to 2.6.4
  python/py-qdarkstyle/Portfile
Labels: maintainer: open, type: update

#3037 libedit: fix tab completion and history in Python
  devel/libedit/Portfile
  devel/libedit/files/patch-history.diff
  devel/libedit/files/patch-no_escaping.diff
Labels: by: member, maintainer, maintainer: open, type: bugfix

#3020 hdf4, hdf5: Fix reinplace warning
  science/hdf4/Portfile
  science/hdf5/Portfile
Labels: by: member, maintainer: requires approval

#3048 ffmpeg / ffmpeg-devel: enable features on snowleopard and lion
  multimedia/ffmpeg-devel/Portfile
  multimedia/ffmpeg/Portfile
Labels: by: member, maintainer: open

#3047 py-awscli: update to 1.16.57
  python/py-awscli/Portfile
  python/py-boto3/Portfile
  python/py-botocore/Portfile
Labels: by: member, maintainer: open, type: update

#3053 wireguard-tools: update to 0.0.20181119
  net/wireguard-tools/Portfile
Labels: maintainer, maintainer: open, type: update

#3052 kotlin: update to 1.3.10
  lang/kotlin/Portfile
Labels: maintainer, maintainer: open, type: update

#3058 valgrind-devel: add test for incompatible systems
  devel/valgrind/Portfile
Labels: by: member, maintainer: open

#3061 ecs-cli: update to 1.12.0
  devel/ecs-cli/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#3049 tig: update and make it redistributable
  devel/tig/Portfile
Labels: by: member, maintainer: open, type: enhancement

#3055 Update to Vc 1.4.1
  math/Vc/Portfile
Labels: maintainer: open, type: enhancement

#3050 p5-file-slurp: update to version 9999.25
  perl/p5-file-slurp/Portfile
Labels: by: member, maintainer: requires approval, type: update

#3064 py-pytest: update to 4.0.0
  python/py-pytest/Portfile
Labels: maintainer: open, type: update

#3045 tk: update to 8.6.9.1
  x11/tk/Portfile
  x11/tk/files/patch-macosx-tkMacOSXEntry.c.diff
  x11/tk/files/patch-macosx-tkMacOSXXStubs.c.diff
Labels: maintainer: open, type: update

#3067 openssl: security update to 1.0.2q
  devel/openssl/Portfile
  net/openssh/Portfile
  sysutils/freeradius/Portfile
Labels: by: member, maintainer: open, type: security fix

#3062 blosc: disable tests and benchmarks
  archivers/blosc/Portfile
Labels: by: member, maintainer: open

#3072 py-jenkins-job-builder: update to 2.8.0
  python/py-jenkins-job-builder/Portfile
Labels: maintainer: none, type: bugfix, type: update

#3073 py-spyder-devel: update to 9d8cd53 (20181122)
  python/py-spyder-devel/Portfile
Labels: maintainer, maintainer: open, type: update

#3068 mlt/mlt-qt5: merge and update
  multimedia/mlt/Portfile
Labels: by: member, maintainer: open, type: enhancement

#3075 youtube-dl: Update to 2018.11.23
  net/youtube-dl/Portfile
Labels: maintainer: open, type: update

#3069 gnupg2: bison is not used at all
  mail/gnupg2/Portfile
Labels: by: member, maintainer: open, type: enhancement

#3056 libressl-devel: update to 2.8.2
  security/libressl-devel/Portfile
Labels: maintainer: requires approval, maintainer: timeout, type: update

#3083 claws-mail: disable unrecognized ld flag on older systems
  mail/claws-mail/Portfile
  mail/claws-mail/files/patch-claws-mail-no-export-dynamic-on-older-ld-versions.diff
Labels: by: member, maintainer: open, type: bugfix

#3070 py-scikit-learn: use https homepage
  python/py-scikit-learn/Portfile
Labels: maintainer: open, type: update, wip

#3085 radare2: update to version 3.1.0
  devel/radare2/Portfile
Labels: maintainer: open, type: enhancement, type: update

#3082 mame: Update version in order to build on Mojave
  emulators/mame/Portfile
  emulators/mame/files/patch-rendutil.cpp.diff
Labels: maintainer: none, type: bugfix

#3084 mariadb-10.2: update to 10.2.19
  databases/mariadb-10.2/Portfile
Labels: by: member, maintainer: open, type: security fix, type: update

#3078 py-spyder: update to 3.3.2, add py37 subport
  python/py-spyder/Portfile
  python/py-spyder/files/spyder-37
Labels: maintainer: open, type: update

#3086 py-ipdb: add py37 subport
  python/py-ipdb/Portfile
  python/py-ipdb/files/ipdb37
Labels: maintainer: none

#3077 R: fix dependencies
  math/R/Portfile
Labels: by: member, maintainer: requires approval, maintainer: timeout, type: bugfix

#3074 libosmo-dsp: remove old complex.h force
  science/libosmo-dsp/Portfile
  science/libosmo-dsp/files/patch-complex.h.diff
Labels: by: member, maintainer: open, type: bugfix

#3091 hugo: update to 0.52
  www/hugo/Portfile
Labels: maintainer, maintainer: open, type: update

#3089 py-spyder-kernels: update to 0.3.0
  python/py-spyder-kernels/Portfile
Labels: maintainer, maintainer: open, type: update

#3092 py-keyring: update to 16.1.1
  python/py-keyring/Portfile
Labels: maintainer, maintainer: open, type: update

#3095 nds2-client Update to 0.16.2 nds2-client-swig 0.16.3 new Portfile
  science/nds2-client-swig/Portfile
  science/nds2-client-swig/files/patch-java-rpath.diff
  science/nds2-client-swig/files/patch-python-module.diff
  science/nds2-client/Portfile
Labels: maintainer, maintainer: open, type: submission

#3094 Travis: Only use the MacPorts CDN, not the mirrors
  _ci/bootstrap.sh
Labels: by: member
