Repository macports/macports-ports, pull requests merged in 2019-04, with the labels that each got.

#3980 clang-8.0/devel : fix build on older systems
  lang/llvm-8.0/Portfile
  lang/llvm-8.0/files/0004-Fix-build-issues-pre-Lion-due-to-missing-a-strnlen-d.patch
  lang/llvm-8.0/files/patch-libcxx-cmakelists-reenable-10.6.8.diff
  lang/llvm-devel/files/0004-Fix-build-issues-pre-Lion-due-to-missing-a-strnlen-d.patch
  lang/llvm-devel/files/yosemite-no-clangd.patch
Labels: by: member, maintainer: requires approval

#3981 vlc: fix build against libssh2
  multimedia/VLC/Portfile
  multimedia/VLC/files/patch-vlc-fix-libssh2.diff
Labels: by: member, maintainer: open, type: bugfix

#3982 Gildas: update to 201904a
  science/gildas/Portfile
Labels: maintainer, type: update

#3987 bind9: fix build on older systems
  net/bind9/Portfile
  net/bind9/files/atomics.patch
Labels: by: member, maintainer: requires approval, type: bugfix

#3989 [volk-]gnss-sdr: Update to version 0.0.10
  science/gnss-sdr/Portfile
  science/gnss-sdr/files/patch-CMakeLists.txt.diff
  science/gnss-sdr/files/patch-for_boost_1.67.devel.diff
  science/volk-gnss-sdr/Portfile
Labels: maintainer, maintainer: open, type: update

#3986 update CastXML to snapshot that supports clang-8.0, add variant for clang-8.0, ...
  lang/castxml/Portfile
  lang/castxml/files/patch-src_CMakeLists.txt.diff
Labels: by: member, maintainer: open, type: enhancement

#3983 libomp: update to 8.0.0
  lang/libomp/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#3995 py-ansible: update to 2.7.9
  python/py-ansible/Portfile
Labels: maintainer: requires approval, type: update

#3996 py-awscli: update to 1.16.136
  python/py-awscli/Portfile
Labels: maintainer: none, type: update

#3999 logtalk: update to 3.25.0
  lang/logtalk/Portfile
Labels: maintainer, type: update

#3998 youtube-dl: update to 2019.04.01
  net/youtube-dl/Portfile
Labels: maintainer: open, type: update

#4000 uhd: update to 3.14.0.0
  science/gnuradio/Portfile
  science/gr-osmosdr/Portfile
  science/uhd/Portfile
  science/uhd/files/patch-fix-boost-python.release.diff
  science/uhd/files/patch-fix-clang-match.release.diff
  science/uhd/files/patch-host_CMakeLists.txt.release.diff
Labels: maintainer: requires approval, type: update

#3997 whois: update version to 5.4.2
  net/whois/Portfile
Labels: maintainer: requires approval

#3942 SoapySDR: add variants for python bindings
  science/SoapySDR/Portfile
Labels: maintainer: open

#4008 ffmpeg: Update to 4.1.3
  multimedia/ffmpeg/Portfile
Labels: maintainer: open, type: update

#4011 radare2: update to 3.4.1
  devel/radare2/Portfile
Labels: by: member, maintainer: open, type: update

#3988 Dynamips all architectures version bump to 0.2.20 STABLE
  net/dynamips/Portfile
  net/dynamips/files/Makefile.diff
  net/dynamips/files/idle_pcs.diff
Labels: maintainer: requires approval

#3992 libssh2: update to 1.8.2
  devel/libssh2/Portfile
Labels: maintainer: open, type: update

#4005 swi-prolog-devel: update to 8.1.4
  lang/swi-prolog-devel/Portfile
Labels: maintainer, type: update

#4007 p5-ppix-regexp: update to version 0.064
  perl/p5-ppix-regexp/Portfile
Labels: by: member, maintainer: open, type: update

#4006 p5-dancer: update to version 1.3512
  perl/p5-dancer/Portfile
Labels: by: member, maintainer: open, type: update

#4013 limesuite: update -devel
  science/limesuite/Portfile
  science/limesuite/files/patch-fix-images-download-regex.diff
Labels: maintainer, maintainer: open, type: bugfix

#4004 virt-manager: update to 2.1.0
  gnome/virt-manager/Portfile
Labels: maintainer: open, type: bugfix, type: enhancement, type: update

#3857 ccls: New port
  devel/ccls/Portfile
Labels: type: enhancement, type: submission

#4021 Added imager executable.
  science/gildas/Portfile
  science/gildas/files/imager.in
Labels: maintainer

#4018 teleport: update to v3.2.0
  net/teleport/Portfile
Labels: maintainer, maintainer: open, type: update

#4012 gitlab-runner: update to 11.9.1
  devel/gitlab-runner/Portfile
Labels: maintainer, maintainer: open, type: update

#3994 proxychains-ng: update to 4.14
  devel/proxychains-ng/Portfile
Labels: maintainer: none, type: update

#4023 gnome-internet-radio-locator: Update to version 2.0.2
  gnome/gnome-internet-radio-locator/Portfile
Labels: maintainer, maintainer: open, type: enhancement, type: update

#4014 py-pytest: update to 4.4.0
  python/py-pytest/Portfile
Labels: by: member, maintainer: open, type: update

#4031 google-cloud-sdk: update to 241.0.0
  devel/google-cloud-sdk/Portfile
Labels: maintainer, maintainer: open, type: update

#4030 vulkan-headers: new port (submission)
  graphics/vulkan-headers/Portfile
Labels: type: submission

#4028 glslang: new port (submission)
  graphics/glslang/Portfile
Labels: type: submission

#4034 vulkan-loader: new port
  graphics/vulkan-loader/Portfile
  graphics/vulkan-loader/files/MoltenVK_icd.json
Labels: type: submission

#4015 py-qtpy: update to 1.7.0
  python/py-qtpy/Portfile
Labels: by: member, maintainer: open, type: update

#4036 asciidoctor: update to 2.0.6
  textproc/asciidoctor/Portfile
Labels: maintainer: none, type: update

#4040 wireguard-tools: update to 0.0.20190406
  net/wireguard-tools/Portfile
Labels: maintainer, maintainer: open, type: update

#4038 mackup: update to 0.8.23
  sysutils/mackup/Portfile
Labels: maintainer, maintainer: open, type: enhancement, type: update

#4039 mlterm: update to version 3.8.8
  x11/mlterm/Portfile
Labels: maintainer: none, type: bugfix, type: enhancement, type: security fix

#4048 limesuite-devel: update to new commit
  science/limesuite/Portfile
Labels: maintainer, maintainer: open, type: update

#4016 isl-devel: update to 0.21
  devel/isl-devel/Portfile
  devel/isl-devel/files/fix-deprecated-headers.patch
Labels: by: member, maintainer: requires approval, maintainer: timeout, type: enhancement, type: update

#4041 hugo: update to 0.55.0
  www/hugo/Portfile
Labels: maintainer, maintainer: open, type: update

#4042 SourceKitten: Update to 0.23.0
  devel/SourceKitten/Portfile
Labels: maintainer: none, type: update

#4049 ntp: update to 4.2.8p13
  sysutils/ntp/Portfile
  sysutils/ntp/files/patch-libntp-work_fork.c.diff
Labels: by: member, maintainer: requires approval, type: update

#4050 wireguard-go: update to 0.0.20190409
  net/wireguard-go/Portfile
Labels: maintainer, maintainer: open, type: bugfix, type: update

#4052 openhantek: new port
  science/openhantek/Portfile
Labels: type: submission

#4053 py-pycares: add missing py-cffi dependency
  python/py-pycares/Portfile
Labels: by: member, maintainer: open, type: bugfix

#4058 py-Pillow: roll back py34 subport to previous working version 5.4.1
  python/py-Pillow/Portfile
  python/py-Pillow/files/patch-setup-5.4.1.py.diff
Labels: by: member, maintainer: open, type: bugfix

#4054 heirloom-doctools: new port
  textproc/heirloom-doctools/Portfile
  textproc/heirloom-doctools/files/patch-grap-print.diff
Labels: type: submission

#4056 new port: nomad
  net/nomad/Portfile
Labels: type: submission

#4061 libgsm: new port
  audio/libgsm/Portfile
  audio/libgsm/files/patch-makefile-more.diff
  audio/libgsm/files/patch-makefile.diff
Labels: by: member, type: submission

#4046 mu: update to 1.2
  mail/mu/Portfile
Labels: maintainer: none, type: update

#4064 jmol: update to 14.29.35
  science/jmol/Portfile
Labels: maintainer, maintainer: open, type: bugfix, type: enhancement, type: update

#4055 Wireshark*: updates
  net/wireshark2/Portfile
  net/wireshark2/files/patch-epan-dissectors-CMakeLists.diff
  net/wireshark2/files/patch-ui-CMakeLists.txt.diff
  net/wireshark24/Portfile
  net/wireshark3/files/patch-epan-dissectors-CMakeLists.diff
  net/wireshark3/files/patch-ui-CMakeLists.txt.diff
Labels: maintainer: requires approval

#4069 john: update to 1.9.0
  sysutils/john/Portfile
Labels: maintainer: none, type: update

#4066 vault: update to 1.1.1
  security/vault/Portfile
Labels: maintainer, maintainer: open, type: update

#4067 packer: update to 1.4.0
  sysutils/packer/Portfile
Labels: maintainer, maintainer: open, type: update

#4068 hugo: update to 0.55.1
  www/hugo/Portfile
Labels: maintainer, maintainer: open, type: update

#4062 tor-devel: update to 0.4.0.4-rc
  security/tor-devel/Portfile
Labels: maintainer: none, type: bugfix, type: enhancement, type: update

#4070 micronaut: update to 1.1.0
  java/micronaut/Portfile
Labels: maintainer, maintainer: open, type: update

#4071 emacs: update to 26.2 and update -devel
  editors/emacs/Portfile
Labels: maintainer: open, type: update

#4073 kotlin: update to 1.3.30
  lang/kotlin/Portfile
Labels: maintainer, maintainer: open, type: update

#4019 carthage: Update to 0.33.0
  devel/carthage/Portfile
Labels: maintainer, maintainer: open, type: update

#4072 gitlab-runner: update to 11.9.2
  devel/gitlab-runner/Portfile
Labels: maintainer, maintainer: open, type: update

#4074 OpenBLAS: enable build on Apple i386
  math/OpenBLAS/Portfile
  math/OpenBLAS/files/patch-OpenBLAS-i386-Apple.diff
Labels: by: member, maintainer: open, type: bugfix

#4059 pcre: update to 8.43
  devel/pcre/Portfile
Labels: by: member, maintainer: requires approval, maintainer: timeout, type: update

#3946 freetype: update to 2.10.0
  print/freetype/Portfile
  print/freetype/files/patch-modules.cfg.diff
Labels: maintainer: requires approval, maintainer: timeout, type: enhancement, type: update

#4027 ipe: Bump version and fix qhull linking
  graphics/ipe/Portfile
Labels: maintainer: open, type: enhancement

#4060 ttfautohint: update to version 1.8.3
  graphics/ttfautohint/Portfile
Labels: maintainer: open, type: enhancement, type: update

#4001 H3D Ports: Update versions to 2.4 release
  graphics/h3dapi/Portfile
  graphics/h3dapi/files/patch-CMakeLists.txt.diff
  graphics/h3dapi/files/patch-CMakeListsPython.diff
  graphics/h3dapi/files/patch-FindAudiofile-PreventFramework.diff
  graphics/h3dapi/files/patch-glutwindow.diff
  graphics/h3dapi/files/patch-h3dapicmake.diff
  graphics/h3dapi/files/patch-include-H3D-X3DParticleEmitterNode.h.diff
  graphics/h3dapi/files/patch-pythonmethods.diff
  graphics/h3dapi/files/patch-pythonscript.diff
  graphics/h3dapi/files/patch-pythontypes.diff
  graphics/h3dapi/files/patch-pythontypesheader.diff
  graphics/h3dapi/files/patch-pytypewrapper.diff
  graphics/h3dmedx3d/Portfile
  graphics/h3dmedx3d/files/patch-build-CMakeLists.txt.diff
  graphics/h3dphysics/Portfile
  graphics/h3dphysics/files/patch-build-CMakeLists.txt.diff
  graphics/h3dphysics/files/patch-bulletcallbacks.diff
  graphics/h3dphysics/files/patch-bulletjoints.diff
  graphics/h3dphysics/files/patch-odecallbacks.diff
  graphics/h3dui/Portfile
  graphics/h3dui/files/patch-build-CMakeLists.txt.diff
  graphics/h3dutil/Portfile
  graphics/h3dutil/files/patch-CMakeLists.txt.diff
  graphics/hapi/Portfile
  graphics/hapi/files/patch-build-CMakeLists.txt.diff
Labels: maintainer: requires approval

#4075 gdub: update to ebe14f110153f05 to support Kotlin-based gradle.build.kts files
  devel/gdub/Portfile
Labels: maintainer: open, type: bugfix, type: update

#4017 tkdnd: update to 2.9
  x11/tkdnd/Portfile
Labels: maintainer: open, type: update

#4020 splash: update to v2.9.0
  science/splash/Portfile
Labels: maintainer, type: enhancement, type: update

#4079 bfs: update to 1.4
  sysutils/bfs/Portfile
Labels: maintainer, maintainer: open, type: enhancement, type: update

#4076 qsynth: new port, version 0.5.6
  audio/qsynth/Portfile
  audio/qsynth/files/patch-src-CMakeLists.txt.diff
Labels: by: member, type: submission

#4082 py-gsd: update to 1.6.2
  python/py-gsd/Portfile
Labels: maintainer, maintainer: open, type: update

#4083 hugo: update to 0.55.2
  www/hugo/Portfile
Labels: maintainer, maintainer: open, type: update

#4081 lz4: update to 1.9.0
  archivers/lz4/Portfile
Labels: maintainer: open, type: enhancement, type: update

#4077 py-clang: remove obsolete variant +clang38
  python/py-clang/Portfile
Labels: by: member, maintainer: open

#4080 py-django: update to 2.2
  python/py-django/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#4085 dnscrypt-proxy: update to version 2.0.22
  net/dnscrypt-proxy/Portfile
Labels: maintainer: open, type: enhancement, type: update

#4088 maven3: update to 3.6.1
  java/maven3/Portfile
Labels: maintainer: open, type: update

#4089 openjdk8: update to 8u212
  java/openjdk8/Portfile
Labels: maintainer, maintainer: open, type: update

#4090 openjdk11: update to 11.0.3
  java/openjdk8/Portfile
Labels: maintainer, maintainer: open, type: update

#4091 meson: update to 0.50.1
  devel/meson/Portfile
Labels: maintainer, maintainer: open, type: update

#4092 fldigi: fix build error on macOS < 10.9
  science/fldigi/Portfile
  science/fldigi/files/patch-FreqControl.cxx.diff
Labels: maintainer, maintainer: open, type: bugfix

#4096 gitlab-runner: update to 11.10.0
  devel/gitlab-runner/Portfile
Labels: maintainer, maintainer: open, type: update

#4097 vault: update to 1.1.2
  security/vault/Portfile
Labels: maintainer, maintainer: open, type: update

#4098 openjdk12-openj9: update to 12.0.1
  java/openjdk8/Portfile
Labels: maintainer, maintainer: open, type: update

#4100 py-clang: add 8.0.0
  python/py-clang/Portfile
Labels: maintainer: open, type: enhancement

#4101 abcde: update to 2.9.3
  audio/abcde/Portfile
Labels: maintainer: open, type: enhancement, type: update

#4102 tcl: add dtrace variant
  lang/tcl/Portfile
Labels: maintainer: open, type: enhancement

#4104 lmdb: update to 0.9.23
  databases/lmdb/Portfile
Labels: maintainer: none, type: update

#4107 hugo: update to 0.55.3
  www/hugo/Portfile
Labels: maintainer, maintainer: open, type: update

#4106 rrdtool: switch to using Perl 5.28
  net/rrdtool/Portfile
Labels: maintainer: open, type: enhancement

#4118 libgpg-error: prevent use of MacPorts gawk
  devel/libgpg-error/Portfile
Labels: by: member, maintainer: open, type: enhancement

#4099 supertuxkart: update to 1.0
  games/supertuxkart/Portfile
Labels: maintainer: open, type: update

#4111 mysql-zrm: add maintainer's github handle, update to perl5.28
  databases/mysql-zrm/Portfile
Labels: by: member, maintainer: requires approval

#4121 perl5: use HTTPS master_sites and livecheck
  lang/perl5/Portfile
Labels: maintainer: open, type: enhancement

#4115 asciidoctor: update to 2.0.7
  textproc/asciidoctor/Portfile
Labels: by: member, maintainer: none, type: update

#4116 swi-prolog-devel: update to 8.1.5
  lang/swi-prolog-devel/Portfile
Labels: maintainer, type: update

#4120 psbind: update to 20090315
  textproc/psbind/Portfile
  textproc/psbind/files/=back.patch
Labels: maintainer: none, type: update

#4122 openjdk12: update to 12.0.1
  java/openjdk8/Portfile
Labels: maintainer, maintainer: open, type: update

#4123 bwping: new port, version 1.12
  net/bwping/Portfile
Labels: type: submission

#4124 openhantek: update to 2.01
  science/openhantek/Portfile
Labels: maintainer, maintainer: open, type: update

#4126 bwping: fix build on mac os x 10.6
  net/bwping/Portfile
  net/bwping/files/patch-gcc-pedantic.diff
Labels: maintainer, maintainer: open, type: bugfix

#4108 qt53: new port
  _resources/port1.0/group/qmake5-1.0.tcl
  _resources/port1.0/group/qt5-1.0.tcl
  aqua/qt53/Portfile
  aqua/qt53/files/patch-add_sdk.diff
  aqua/qt53/files/patch-allow-c++11-with-106OSDK.diff
  aqua/qt53/files/patch-cups.diff
  aqua/qt53/files/patch-deployment_target.diff
  aqua/qt53/files/patch-find_rez.diff
  aqua/qt53/files/patch-fix-nullable-clang.diff
  aqua/qt53/files/patch-fix_sdk.diff
  aqua/qt53/files/patch-icu.diff
  aqua/qt53/files/patch-install_examples.diff
  aqua/qt53/files/patch-machtest.diff
  aqua/qt53/files/patch-midifix.diff
  aqua/qt53/files/patch-mkspecs.diff
  aqua/qt53/files/patch-no_qtwebkit.diff
  aqua/qt53/files/patch-opengl.diff
  aqua/qt53/files/patch-pcfiles.diff
  aqua/qt53/files/patch-qt53-SL-nispro.diff
  aqua/qt53/files/patch-qt53-disable-macsdkify.diff
  aqua/qt53/files/patch-qt53-qtwebkit-unistd-include.diff
  aqua/qt53/files/patch-qtconn-for-10.12.diff
  aqua/qt53/files/patch-qtconnectivity-sdk10_13.diff
  aqua/qt53/files/patch-qtconnectivity-uuid.diff
  aqua/qt53/files/patch-qtscript_ceil.diff
  aqua/qt53/files/patch-qtwebengine32.diff
  aqua/qt53/files/patch-qtwebengine_xcode10.diff
  aqua/qt53/files/patch-qualified_reference.diff
  aqua/qt53/files/patch-rpath.diff
  aqua/qt53/files/patch-sdk10_13.diff
  aqua/qt53/files/patch-shared.diff
  aqua/qt53/files/patch-ssl.diff
  aqua/qt53/files/patch-stdloc.diff
  aqua/qt53/files/patch-tst_benchlibcallgrind.diff
  aqua/qt53/files/patch-tst_qpluginloader.diff
  aqua/qt53/files/patch-xcrun.diff
Labels: by: member, type: enhancement, type: submission

#4132 i386-mingw32: remove obsolete port
  cross/i386-mingw32/Portfile
Labels: maintainer: none

#4129 qpdf: update to 8.4.0
  textproc/qpdf/Portfile
  textproc/qpdf/files/LDFLAGS.patch
Labels: maintainer: none, type: update

#4133 avahi: fix typo in comment
  net/avahi/Portfile
Labels: maintainer: none

#4131 libhidapi: remove obsolete port
  cross/openocd/Portfile
  devel/libhidapi/Portfile
Labels: maintainer: none

#4143 gramps3: remove obsolete port
  genealogy/gramps3/Portfile
Labels: maintainer: none

#4145 gnome-themes-standard: remove obsolete port
  gnome/gnome-themes-standard/Portfile
Labels: maintainer: none

#4146 xchat2: remove obsolete port
  irc/xchat2/Portfile
  irc/xchat2/files/patch-glib-2.32.diff
  irc/xchat2/files/patch-gmodule.diff
  irc/xchat2/files/patch-gtk2.19.7.diff
Labels: maintainer: none

#4144 hdf5-18: remove obsolete port
  science/h4h5tools/Portfile
  science/hdf5-18/Portfile
  science/hdf5/Portfile
Labels: maintainer: open

#4138 gnutls: remove conflicts_build on autoconf-archive
  devel/gnutls/Portfile
Labels: by: member, maintainer: open

#4139 sqlite3-tools: remove pre-activate block
  databases/sqlite3/Portfile
Labels: maintainer: open

#4148 ansifilter: update to 2.14
  textproc/ansifilter/Portfile
Labels: maintainer, maintainer: open

#4150 mpich: Add clang 8.0 versions.
  science/mpich/Portfile
  science/mpich/files/mpich-clang80
  science/mpich/files/mpich-clang80-fortran
  science/mpich/files/mpich-devel-clang80
  science/mpich/files/mpich-devel-clang80-fortran
Labels: by: member, maintainer, maintainer: open

#4149 zabbix4: Update to latest.
  net/zabbix4/Portfile
  net/zabbix4/files/ZBX-15935.patch
Labels: by: member, maintainer, maintainer: open, type: update

#4137 burp: remove pre-activate block
  sysutils/burp/Portfile
Labels: maintainer: open

#4140 logwatch: remove pre-activate block
  security/logwatch/Portfile
Labels: maintainer: open

#4110 rex: add maintainer's github handle, use perl5.28
  sysutils/rex/Portfile
Labels: by: member, maintainer: requires approval, maintainer: timeout

#4152 ditaa: Update to version 0.11.0
  java/ditaa/Portfile
  java/ditaa/files/ditaa.sh
Labels: maintainer: none, type: update

#4156 gitlab-runner: update to 11.10.1
  devel/gitlab-runner/Portfile
Labels: maintainer, maintainer: open, type: update

#4114 pcre2: update to 10.33
  devel/pcre/Portfile
Labels: by: member, maintainer: requires approval, maintainer: timeout, type: update

#4109 homebank: update to 5.2.4
  x11/homebank/Portfile
Labels: maintainer: open, type: update

#4094 ripgrep: update to 11.0.1
  textproc/ripgrep/Portfile
Labels: maintainer: open, type: enhancement, type: update

#4119 nodejs6: fix build on older systems
  devel/nodejs6/Portfile
  devel/nodejs6/files/patch-nodejs6-old-tr1-calls.diff
Labels: by: member, maintainer: requires approval, type: enhancement

#4161 tmux: update to 2.9, tmux-devel to latest commit
  sysutils/tmux/Portfile
Labels: maintainer, maintainer: open, type: update

#4159 weechat: update to 2.4
  irc/weechat/Portfile
  irc/weechat/files/patch-fix-compilation.diff
Labels: maintainer: open, type: update

#4113 nodejs*: drop nodejs{5,7,9}
  devel/nodejs10/Portfile
  devel/nodejs11/Portfile
  devel/nodejs4/Portfile
  devel/nodejs5/Portfile
  devel/nodejs5/files/patch-common.gypi.diff
  devel/nodejs5/files/patch-tools-gyp-pylib-gyp-generator-make.py.diff
  devel/nodejs6/Portfile
  devel/nodejs7/Portfile
  devel/nodejs7/files/patch-common.gypi.diff
  devel/nodejs7/files/patch-tools-gyp-pylib-gyp-generator-make.py.diff
  devel/nodejs8/Portfile
  devel/nodejs9/Portfile
  devel/nodejs9/files/patch-common.gypi.diff
  devel/nodejs9/files/patch-tools-gyp-pylib-gyp-generator-make.py.diff
Labels: by: member, maintainer: requires approval, maintainer: timeout

#4163 LyX: fix build on older systems
  aqua/LyX/Portfile
  aqua/LyX/files/patch-lyx-applescriptproxy-add-stringh.diff
Labels: by: member, maintainer: open

#4157 Subport for osslsigncode to support hardware tokens
  devel/osslsigncode/Portfile
  devel/osslsigncode/files/configure.ac.diff
Labels: maintainer: none, type: enhancement

#4160 plantuml: Update to version 1.2019.5
  java/plantuml/Portfile
  java/plantuml/files/patch-build.xml.diff
Labels: maintainer: none, type: update

#4170 hugo: update to 0.55.4
  www/hugo/Portfile
Labels: maintainer, maintainer: open, type: update

#4172 py-urllib3: update to 1.25.1
  python/py-urllib3/Portfile
Labels: by: member, maintainer: open

#4173 cvs: avoid opportunistic linking to kerberos
  devel/cvs/Portfile
Labels: maintainer: none

#4174 fldigi: update to 4.1.03
  science/fldigi/Portfile
  science/fldigi/files/patch-FreqControl.cxx.diff
Labels: maintainer, maintainer: open, type: update

#4151 py-sphinx-[gallery|-bootstrap-theme]: New ports.
  python/py-sphinx-bootstrap-theme/Portfile
  python/py-sphinx-gallery/Portfile
Labels: by: member, type: submission

#4171 libp11: new port
  security/libp11/Portfile
Labels: type: submission

#4179 kotlin: update to 1.3.31
  lang/kotlin/Portfile
Labels: maintainer, maintainer: open, type: update

#4178 rx_tools: new port
  science/rx_tools/Portfile
Labels: type: submission

#4182 wkhtmltopdf: use qt5.depends_component
  textproc/wkhtmltopdf/Portfile
Labels: by: member, maintainer: open

#4185 wordpress: update to 4.9.10
  www/wordpress/Portfile
Labels: maintainer: none, type: security fix, type: update

#4169 perl5: set default to +perl5_28, version 5.28.2
  lang/perl5/Portfile
Labels: by: member, maintainer: open, type: enhancement

#4188 fntsample: switch to perl5.28
  graphics/fntsample/Portfile
Labels: by: member, maintainer, maintainer: open

#4184 mod_jk2: delete port
  www/mod_jk2/Portfile
  www/mod_jk2/files/patch-workers2.properties.minimal.diff
Labels: maintainer: none

#4177 multimon-ng: new port
  science/multimon-ng/Portfile
Labels: type: submission

#4189 recoll: use modern qt5 syntax
  textproc/recoll/Portfile
Labels: by: member, maintainer: open
