Repository macports/macports-ports, pull requests merged in 2019-07, with the labels that each got.

#4709 bochs: fix build: strrchr() const overload produces an error.
  emulators/bochs/Portfile
  emulators/bochs/files/patch-cdrom_osx.cc.diff
Labels: maintainer: requires approval, type: bugfix

#4721 bochs: add Upstream-Status comment to patch
  emulators/bochs/files/patch-cdrom_osx.cc.diff
Labels: maintainer: requires approval

#4719 py-agate-excel: update to 0.2.3
  python/py-agate-excel/Portfile
Labels: maintainer: open, type: update

#4713 Submission dns-server: named DNS server working configuration
  net/dns-server/Portfile
  net/dns-server/files/db.@LAN_REVERSE_IP_SUBNET@.in-addr.arpa
  net/dns-server/files/db.@domain@.@tld@
  net/dns-server/files/db.@domain@.private
  net/dns-server/files/localhost.zone
  net/dns-server/files/named.ca
  net/dns-server/files/named.conf
  net/dns-server/files/named.local
Labels: type: submission

#4722 Gildas: update to 201907a
  science/gildas/Portfile
Labels: maintainer, type: update

#4708 charls: build shared library
  graphics/charls/Portfile
Labels: by: member, maintainer: requires approval, maintainer: timeout, type: enhancement

#4717 dart-sdk: Update to version 2.4.0
  lang/dart-sdk/Portfile
Labels: maintainer: none, type: enhancement, type: update

#4725 yubico-pam: Update to 2.26
  security/yubico-pam/Portfile
Labels: by: member, maintainer, type: update

#4732 xercesc3, xml-security-c: use HTTPS sites
  security/xml-security-c/Portfile
  textproc/xercesc3/Portfile
Labels: maintainer: requires approval

#4729 tomcat-native: use HTTPS homepage and livecheck
  java/tomcat-native/Portfile
Labels: maintainer: open

#4726 multiple ports (nomaintainer): use HTTPS for Apache sites
  databases/cassandra/Portfile
  devel/apache-ivy/Portfile
  devel/libzookeeper/Portfile
  devel/log4cxx/Portfile
  devel/maven-ant-tasks/Portfile
  java/apache-solr4/Portfile
  java/apache-solr8/Portfile
  java/batik/Portfile
  java/commons-beanutils/Portfile
  java/commons-cli/Portfile
  java/commons-codec/Portfile
  java/commons-daemon/Portfile
  java/commons-dbcp/Portfile
  java/commons-digester/Portfile
  java/commons-el/Portfile
  java/commons-fileupload/Portfile
  java/commons-httpclient/Portfile
  java/commons-io/Portfile
  java/commons-lang/Portfile
  java/commons-launcher/Portfile
  java/commons-modeler/Portfile
  java/commons-pool/Portfile
  java/commons-validator/Portfile
  java/derby-server/Portfile
  java/hadoop/Portfile
  java/jakarta-bcel/Portfile
  java/jakarta-log4j/Portfile
  java/jakarta-oro/Portfile
  java/jakarta-regexp/Portfile
  java/jakarta-taglibs-standard-11/Portfile
  java/mahout/Portfile
  java/poi/Portfile
  java/servlet23-api/Portfile
  java/servlet24-api/Portfile
  java/struts/Portfile
  java/xalanj/Portfile
  java/xercesj/Portfile
  java/xmlgraphics-commons/Portfile
  perl/p5-mail-spamassassin/Portfile
  python/py-jcc/Portfile
  textproc/fop/Portfile
  textproc/xalanc/Portfile
  www/flood/Portfile
  www/mod_fcgid/Portfile
  www/mod_perl2/Portfile
  www/mod_python/Portfile
Labels: maintainer: none

#4718 lighttpd: add legacysupport PG
  www/lighttpd/Portfile
Labels: by: member, maintainer: requires approval

#4734 wireguard-tools: update to 0.0.20190702
  net/wireguard-tools/Portfile
Labels: maintainer, maintainer: open, type: update

#4723 submission (new Portfile): ondir @0.2.3_0 (sysutils)
  sysutils/ondir/Portfile
  sysutils/ondir/files/patch-Makefile.diff
Labels: type: submission

#4731 apr-util: use HTTPS homepage and livecheck
  devel/apr-util/Portfile
Labels: maintainer: requires approval

#4730 subversion ports: use HTTPS for Apache sites
  devel/subversion-javahlbindings/Portfile
  devel/subversion-perlbindings/Portfile
  devel/subversion-python27bindings/Portfile
  devel/subversion-rubybindings/Portfile
  devel/subversion/Portfile
Labels: maintainer: requires approval

#4733 py-libcloud: use HTTPS homepage and master_sites
  python/py-libcloud/Portfile
Labels: maintainer: open

#4745 hub: update version to 2.12.1 - build/install manpages
  devel/hub/Portfile
Labels: maintainer: requires approval, type: enhancement, type: submission

#4754 swi-prolog-devel: update to 8.1.9
  lang/swi-prolog-devel/Portfile
Labels: maintainer, type: update

#4750 webkit2-gtk: fix bad_optional_access build error
  www/webkit2-gtk/Portfile
  www/webkit2-gtk/files/patch_bad_optional_access.diff
Labels: maintainer: requires approval, type: bugfix

#4728 couchdb: use HTTPS homepage and livecheck
  databases/couchdb/Portfile
Labels: maintainer: requires approval

#4755 nonpareil: fix whitespace, license and scons build
  emulators/nonpareil/Portfile
  emulators/nonpareil/files/patch-sconstruct.diff
Labels: maintainer: none

#4762 fldigi: update to 4.1.05
  science/fldigi/Portfile
Labels: maintainer, maintainer: open, type: update

#4763 multimon-ng: update to 1.1.8
  science/multimon-ng/Portfile
Labels: maintainer, maintainer: open, type: update

#4765 Google cloud SDK bug fix / update
  devel/google-cloud-sdk/Portfile
Labels: by: member, maintainer: open, type: bugfix, type: enhancement

#4766 Update version to 3.8.0-b2, hashes and filesize.
  lang/python38-devel/Portfile
Labels: maintainer: open, type: enhancement, type: update

#4768 kotlin: update to 1.3.41
  lang/kotlin/Portfile
Labels: maintainer, maintainer: open, type: update

#4759 micronaut: update to 1.1.4
  java/micronaut/Portfile
Labels: maintainer, maintainer: open, type: update

#4758 graalvm: update to 19.1.0
  java/graalvm/Portfile
Labels: maintainer, maintainer: open, type: update

#4769 nonpareil: resolve conflict with nss
  emulators/nonpareil/Portfile
Labels: maintainer: none, type: bugfix

#4767 z: update - add subport z-devel pointing to git master, add homepage
  sysutils/z/Portfile
Labels: maintainer: none, type: enhancement, type: update

#4746 submission (new Portfile): flash @2.3.0 (sysutils)
  sysutils/flash/Portfile
Labels: type: submission

#4760 lighttpd: fix build on Tiger
  www/lighttpd/Portfile
  www/lighttpd/files/patch-tigerfixes.diff
Labels: by: member, maintainer: requires approval, type: enhancement

#4771 web-ext: update to 3.1.0
  devel/web-ext/Portfile
Labels: maintainer: none, type: update

#4720 apache-ant: update to 1.10.6
  devel/apache-ant/Portfile
Labels: by: member, maintainer: open, type: bugfix, type: update

#4761 xcrysden: change getline test to os version
  science/xcrysden/Portfile
Labels: by: member, maintainer: requires approval, type: bugfix

#4772 mirror_sites.tcl: Fetch distfiles via HTTP on 10.8 or older
  _resources/port1.0/fetch/mirror_sites.tcl
Labels: by: member, type: bugfix

#4770 clang-devel: refactor patch file
  lang/llvm-devel/Portfile
  lang/llvm-devel/files/9001-macports-libstdcxx.diff
Labels: by: member, maintainer: requires approval, type: bugfix

#4756 py-dill: update to 0.3.0
  python/py-dill/Portfile
Labels: by: member, maintainer: open, type: update

#4757 py-requests-mock: update to 1.6.0, add noarch
  python/py-requests-mock/Portfile
Labels: by: member, maintainer: open, type: update

#4774 py-buildbot-macports-custom-views: update to 0.0.3
  python/py-buildbot-macports-custom-views/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#4780 Gildas: update to 201907b
  science/gildas/Portfile
Labels: maintainer, type: update

#4779 neovim: update to v0.3.8
  editors/neovim/Portfile
Labels: maintainer: open, type: security fix, type: update

#4773 qemu: update to 4.0.0 and add riscv32/64 support
  emulators/qemu/Portfile
Labels: maintainer: open, type: enhancement, type: update

#4783 rust: update to 1.36.0
  lang/rust/Portfile
Labels: by: member, maintainer: open, type: update

#4777 gitlab-runner: update to 12.0.2
  devel/gitlab-runner/Portfile
Labels: maintainer, maintainer: open, type: update

#4785 plumed: update
  science/plumed/Portfile
Labels: maintainer, maintainer: open, type: update

#4784 lang/elixir: update to 1.9.0
  lang/elixir/Portfile
Labels: maintainer, type: enhancement, type: update

#4741 dns-server: Add hard-coded network settings to address portindex issue
  net/dns-server/Portfile
Labels: maintainer, type: bugfix

#4788 mesos: update to 1.8.0
  devel/mesos/Portfile
  devel/mesos/files/patch-configureac.patch
Labels: maintainer, maintainer: open, type: bugfix, type: update

#4790 cargo: update to 0.37.0
  devel/cargo/Portfile
Labels: by: member, maintainer: none, type: update

#4792 bfs: update to 1.5
  sysutils/bfs/Portfile
Labels: maintainer, maintainer: open, type: enhancement, type: update

#4781 submission (new Portfile): mailutils @3.6 (mail)
  mail/mailutils/Portfile
Labels: type: submission

#4791 prometheus: update to 2.11.0
  net/prometheus/Portfile
Labels: maintainer, maintainer: open, type: update

#4789 qemu fixes
  emulators/qemu/Portfile
Labels: by: member, maintainer: open

#4747 openjfx11: Initial commit of portfile
  java/openjfx11/Portfile
Labels: type: enhancement, type: submission

#4793 shadowfox-updater: update to 2.2.0
  www/shadowfox-updater/Portfile
Labels: maintainer, maintainer: open, type: enhancement, type: update

#4727 multiple ports (maintained by @blair): use HTTPS for Apache sites
  devel/apache-ant-1.9/Portfile
  devel/apache-ant/Portfile
  devel/apr-util0/Portfile
  devel/apr0/Portfile
  devel/thrift/Portfile
  java/commons-collections/Portfile
  java/commons-logging/Portfile
  java/derby/Portfile
  perl/p5-thrift/Portfile
  python/py-thrift/Portfile
Labels: maintainer: requires approval, maintainer: timeout

#4800 prometheus: update to 2.11.1
  net/prometheus/Portfile
Labels: maintainer, maintainer: open, type: update

#4799 mosh: Support building with C++20 (clang 7+ and GCC 9.1+)
  net/mosh/Portfile
  net/mosh/files/patch-version-subdir.diff
Labels: maintainer, maintainer: open, type: bugfix

#4803 scdoc: Update to 1.9.6
  textproc/scdoc/Portfile
Labels: maintainer, maintainer: open, type: update

#4621 capnproto: update to version 1.7.0
  devel/capnproto/Portfile
Labels: maintainer: open, type: update

#4778 Fixed vtk +qt5 variant
  graphics/vtk/Portfile
Labels: maintainer: open, type: bugfix

#4787 mpv: fix build with swift 5
  multimedia/mpv/Portfile
Labels: maintainer: requires approval, type: bugfix

#4805 gpsd: update to 3.19
  net/gpsd/Portfile
  net/gpsd/files/patch-SConstruct.diff
  net/gpsd/files/patch-noC99.diff
  net/gpsd/files/patch-pyserial.diff
Labels: maintainer, maintainer: open, type: update

#4806 pgbadger: update to 11.0
  databases/pgbadger/Portfile
Labels: maintainer: none, type: enhancement, type: update

#4804 ntpsec: update to 1.1.6
  sysutils/ntpsec/Portfile
  sysutils/ntpsec/files/patch-PreHighSierra.diff
Labels: maintainer, maintainer: open, type: update

#4808 terraform: update to 0.12.4
  sysutils/terraform/Portfile
Labels: maintainer, maintainer: open, type: update

#4809 alertmanager: upgrade to 0.18.0
  net/alertmanager/Portfile
Labels: maintainer, maintainer: open

#4812 py-htmldocs: 3.6.9 and 3.7.4
  lang/py-htmldocs/Portfile
Labels: by: member, maintainer, maintainer: open

#4811 minio[-mc]: Update to 2019-07-10/11
  www/minio-mc/Portfile
  www/minio/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#4796 cfiles: new port
  sysutils/cfiles/Portfile
  sysutils/cfiles/files/patch-Makefile.diff
  sysutils/cfiles/files/patch-config.h.diff
Labels: type: enhancement, type: submission

#4795 clang-devel: fix broken patch file
  lang/llvm-devel/files/9001-macports-libstdcxx.diff
Labels: by: member, maintainer: requires approval, type: bugfix

#4810 llvm-devel; clang-devel: fix build on older systems
  lang/llvm-devel/Portfile
  lang/llvm-devel/files/5000-patch-lib-support-unix-path-copyfileclone-on-older-systems.diff
  lang/llvm-devel/files/5001-patch-machoreader-strnlen.diff
  lang/llvm-devel/files/5002-patch-objdumper-strnlen.diff
  lang/llvm-devel/files/yosemite-no-clangd.patch
Labels: by: member, maintainer: requires approval

#4753 struts: remove port
  java/struts/Portfile
Labels: maintainer: none

#4743 macos-vpn-server: Add hard-coded network settings to address portindex issue
  net/macos-vpn-server/Portfile
Labels: maintainer, maintainer: open, type: bugfix

#4776 jemalloc: update to version 5.2.0
  devel/jemalloc/Portfile
Labels: maintainer: open, type: update

#4817 gmtsar: update to version 5.7
  science/gmtsar/Portfile
Labels: maintainer, maintainer: open, type: update

#4816 kubectx: new submission
  sysutils/kubectx/Portfile
Labels: type: submission

#4820 aerc: update to 0.1.4
  mail/aerc/Portfile
Labels: maintainer, maintainer: open, type: update

#4815 py-nclib: Update to 0.8.3 and enable support for Python 3.7
  python/py-nclib/Portfile
Labels: maintainer, maintainer: open, type: update

#4826 tomcat-native: update to version 1.2.23
  java/tomcat-native/Portfile
Labels: maintainer, maintainer: open, type: update

#4818 bind9: fix livecheck
  net/bind9/Portfile
Labels: by: member, maintainer: requires approval, type: bugfix

#4821 helm*: Allow for multiple versions of Helm/Tiller
  sysutils/helm/Portfile
  sysutils/helm/files/base
  sysutils/helm/files/helm2.12
  sysutils/helm/files/helm2.13
  sysutils/helm/files/helm2.14
  sysutils/helm/files/none
Labels: maintainer: open, type: submission

#4828 websocat: update to 1.5.0
  net/websocat/Portfile
Labels: maintainer, maintainer: open, type: update

#4830 auto-multiple-choice: Update get language codes from CPAN
  x11/auto-multiple-choice/Portfile
Labels: maintainer, maintainer: open, type: enhancement, type: update

#4724 addresses libkml support #58410
  gis/gdal/Portfile
Labels: maintainer: open, type: enhancement

#4834 terraform: update to 0.12.5
  sysutils/terraform/Portfile
Labels: maintainer, maintainer: open, type: update

#4837 openjdk11-openj9: update to 11.0.4
  java/openjdk8/Portfile
Labels: maintainer, maintainer: open, type: update

#4836 openjdk11: update to 11.0.4
  java/openjdk8/Portfile
Labels: maintainer, maintainer: open, type: update

#4835 openjdk8: update to 8u222
  java/openjdk8/Portfile
Labels: maintainer, maintainer: open, type: update

#4838 openjdk12: update to 12.0.2
  java/openjdk8/Portfile
Labels: maintainer, maintainer: open, type: update

#4839 graalvm: update to 19.1.1
  java/graalvm/Portfile
Labels: maintainer, maintainer: open, type: update

#4841 py-ansible: update to 2.8.2
  python/py-ansible/Portfile
Labels: by: member, maintainer, maintainer: open, type: security fix, type: update

#4840 update castxml to version 0.2
  lang/castxml/Portfile
Labels: by: member, maintainer: open, type: enhancement, type: update

#4842 *: simplify skipping build phase
  cross/android-ndk/Portfile
  devel/apache-ant-1.9/Portfile
  devel/apache-ant/Portfile
  devel/grails/Portfile
  devel/griffon/Portfile
  devel/groovyserv/Portfile
  java/android/Portfile
  java/antenna/Portfile
  java/derby/Portfile
  java/dualist/Portfile
  java/gant/Portfile
  java/glassfishv3/Portfile
  java/jgoodies-common/Portfile
  java/jgoodies-forms/Portfile
  java/jgoodies-looks/Portfile
  java/jmock1/Portfile
  java/jmock2/Portfile
  java/log4jdbc/Portfile
  java/maven1/Portfile
  java/maven2/Portfile
  java/microemu/Portfile
  java/msv/Portfile
  java/objenesis/Portfile
  java/proguard/Portfile
  java/slf4j/Portfile
  java/spring-framework25/Portfile
  java/spring-framework30/Portfile
  java/spring-framework31/Portfile
  java/spring-javaconfig/Portfile
  lang/antlr3/Portfile
Labels: by: member, maintainer: open, type: enhancement

#4843 kubectx: updated runtime dependency due to obsoletion of kubectl port
  sysutils/kubectx/Portfile
Labels: maintainer, maintainer: open, type: bugfix, type: update

#4831 kube-ps1: new submission
  sysutils/kube-ps1/Portfile
Labels: type: submission

#4802 Submission: bitwise @0.30
  devel/bitwise/Portfile
Labels: type: submission

#4844 kube-ps1: fix for obsoleted kubectl
  sysutils/kube-ps1/Portfile
Labels: maintainer, maintainer: open, type: bugfix

#4846 p5-devel-mat-dumper: remove conflict handler
  perl/p5-devel-mat-dumper/Portfile
Labels: maintainer: open

#4853 john-jumbo: update to 1.9.0
  sysutils/john/Portfile
Labels: by: member, maintainer: none, type: update

#4858 mico: Fix compilation on modern OS X
  devel/mico/Portfile
  devel/mico/files/patch-os-math.h.diff
Labels: by: member, maintainer, maintainer: open

#4847 npm6: update to 6.10.1
  devel/npm6/Portfile
Labels: maintainer: none, type: enhancement, type: update

#4845 tmux: update tmux-devel to latest commit
  sysutils/tmux/Portfile
Labels: maintainer, maintainer: open, type: update

#4857 google-cloud-sdk: update to 254.0.0
  devel/google-cloud-sdk/Portfile
Labels: maintainer, maintainer: open, type: update

#4860 gitlab-runner: update to 12.1.0
  devel/gitlab-runner/Portfile
Labels: maintainer, maintainer: open, type: update

#4862 qt5-qtbase: add dependency on double-conversion and rebuild
  aqua/qt5/Portfile
Labels: by: member, maintainer: open, type: bugfix

#4850 xcodeversion-1.0: set use_xcode yes
  _resources/port1.0/group/xcodeversion-1.0.tcl
Labels: by: member, type: enhancement

#4864 swi-prolog-devel: update to 8.1.10
  lang/swi-prolog-devel/Portfile
Labels: maintainer, type: update

#4782 submission (new Portfile): isce2
  python/py-isce2/Portfile
  python/py-isce2/files/gcc_SconfigISCE
Labels: type: submission

#4852 openjdk12-openj9: update to 12.0.2
  java/openjdk8/Portfile
Labels: maintainer, maintainer: open, type: update

#4859 pstoedit: use abs from cmath
  graphics/pstoedit/Portfile
  graphics/pstoedit/files/patch-src-dxfacad.h.diff
Labels: maintainer: none, type: bugfix

#4868 mysql8: update to 8.0.17
  databases/mysql8/Portfile
  databases/mysql8/files/patch-router-cmake-set_rpath.diff
Labels: maintainer, maintainer: open, type: update

#4849 gnucash-docs: provide workaround for +quartz
  gnome/gnucash-docs/Portfile
Labels: maintainer: open, type: bugfix

#4870 py-pynetdicom: Update to 1.4.1.
  python/py-pynetdicom/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#4863 xinput: update to 1.6.3
  x11/xinput/Portfile
Labels: maintainer: open, type: update

#4872 mallet: Update to v2.0.8
  math/mallet/Portfile
  math/mallet/files/patch-mallet.diff
Labels: maintainer: none, type: update

#4869 pdns-recursor: update to 4.2.0
  net/pdns-recursor/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#4856 stern: new submission
  sysutils/stern/Portfile
Labels: type: submission

#4873 mallet: fix classpath definitions
  math/mallet/Portfile
  math/mallet/files/patch-mallet.diff
Labels: maintainer: none, type: bugfix, type: update

#4861 vtk: use MacPorts libs instead of local versions
  graphics/vtk/Portfile
Labels: by: member, maintainer: open, type: enhancement

#4874 qalculate-gtk: bump to 3.3.0
  math/libqalculate/Portfile
  math/qalculate-gtk/Portfile
Labels: by: member, maintainer: requires approval, type: enhancement

#4877 web-ext: update to 3.1.1
  devel/web-ext/Portfile
Labels: maintainer: none, type: update

#4855 mpstats: add support for cxx_stdlib submission
  sysutils/mpstats/Portfile
  sysutils/mpstats/files/mpstats.tcl
Labels: by: member, maintainer: open, type: enhancement

#4886 vault: update to 1.1.4
  security/vault/Portfile
Labels: maintainer, maintainer: open, type: update

#4884 hugo: update to 0.56.0
  www/hugo/Portfile
Labels: maintainer, maintainer: open, type: update

#4887 consul: update to 1.5.3
  net/consul/Portfile
Labels: maintainer, maintainer: open, type: update

#4880 openhantek: update version to 2.12
  science/openhantek/Portfile
Labels: maintainer, maintainer: open, type: update

#4876 notmuch: Fix output file being closed twice
  mail/notmuch/Portfile
  mail/notmuch/files/notmuch-0.29.1-fix-sigabrt.patch
Labels: maintainer, maintainer: open, type: bugfix

#4879 py-exifread: update to 2.2.0, adopt port
  python/py-exif/Portfile
  python/py-exifread/Portfile
Labels: maintainer: none, type: submission, type: update

#4881 cppreference: new port.
  lang/cppreference/Portfile
Labels: by: member, type: submission

#4875 libevent: update to 2.1.10
  devel/libevent/Portfile
  devel/libevent/files/patch-apple-clang.diff
  devel/libevent/files/patch-libressl-2-7.diff
Labels: maintainer, maintainer: open, type: update

#4889 tor-devel: update to 0.4.1.4-rc
  security/tor-devel/Portfile
Labels: maintainer: none, type: update

#4882 GraphicsMagick: update to 1.3.33
  graphics/GraphicsMagick/Portfile
  graphics/GraphicsMagick/files/fix-strlcat-crash.patch
Labels: maintainer: open, type: update

#4891 fldigi: update version to 4.1.06
  science/fldigi/Portfile
Labels: maintainer, maintainer: open, type: update

#4892 flrig: update to 1.3.46
  science/flrig/Portfile
  science/flrig/files/patch-info.plist.diff
  science/flrig/files/patch-timeops.cxx.diff
Labels: maintainer, maintainer: open, type: update

#4883 getmail: update to version 5.13
  mail/getmail/Portfile
Labels: maintainer: none, type: update

#4878 xca: Initial commit of xca 2.1.2, a cross-platform GUI certificate an…
  security/xca/PortFile
  security/xca/files/patch-disable-codesigning.diff
Labels: type: enhancement

#4900 kermit-devel: new port
  comms/kermit-devel/Portfile
  comms/kermit-devel/files/patch-ckuus5.c.diff
  comms/kermit-devel/files/patch-makefile.diff
Labels: by: member, type: submission

#4906 hugo: update to 0.56.1
  www/hugo/Portfile
Labels: maintainer, maintainer: open, type: update

#4897 vpnc-scripts: update version to 20190606
  net/vpnc-scripts/Portfile
Labels: maintainer: none, type: bugfix, type: enhancement, type: update

#4893 exim: update to 4.92.1
  mail/exim/Portfile
Labels: maintainer: none, type: security fix, type: update

#4890 CubicSDR: update version to 20190724-21fc2d60
  science/CubicSDR/Portfile
Labels: maintainer, maintainer: open, type: update

#4902 new port: sequoia-pgp
  security/sequoia-pgp/Portfile
Labels: by: member, type: submission

#4865 php-mailparse: update to 3.0.3
  php/php-mailparse/Portfile
  php/php-mailparse/files/php73-mailparse.patch
Labels: maintainer: open, type: update

#4871 xorg-libice: update to 1.0.10
  x11/xorg-libice/Portfile
Labels: maintainer: open, type: enhancement, type: update

#4903 xca: Fix compile error on 10.14.6
  security/xca/PortFile
  security/xca/files/patch-disable-codesigning.diff
Labels: type: bugfix

#4895 gr-limesdr-devel: update version to 14b29b3b
  science/gr-limesdr/Portfile
Labels: maintainer, maintainer: open, type: update

#4904 libfmt: update version to 5.3.0
  devel/libfmt/Portfile
Labels: maintainer: none, type: update
