Repository macports/macports-ports, pull requests merged in 2019-06, with the labels that each got.

#4507 girara, zathura: demote intltool to a build dependency
  devel/girara/Portfile
  office/zathura/Portfile
Labels: by: member, maintainer: open

#4509 wireshark-chmodbpf: fix group creation if installed from binary
  net/wireshark-chmodbpf/Portfile
Labels: maintainer, maintainer: open, type: bugfix

#4506 wireguard-tools: update to 0.0.20190531
  net/wireguard-tools/Portfile
Labels: maintainer, maintainer: open, type: update

#4450 libcomerr: remove old conflict handlers
  sysutils/e2fsprogs/Portfile
Labels: maintainer: open

#4512 wireguard-tools: update to 0.0.20190601
  net/wireguard-tools/Portfile
Labels: maintainer, maintainer: open, type: update

#4505 demeter: switch to Perl 5.28, add size
  science/demeter/Portfile
Labels: maintainer: open

#4503 kuser, kcron: remove old conflict handlers
  kde/kcron/Portfile
  kde/kuser/Portfile
Labels: maintainer: open

#4504 kdepimlibs4: remove old conflict handler
  kde/kdepimlibs4/Portfile
Labels: maintainer: requires approval

#4514 kdelibs4: remove old conflict handler
  kde/kdelibs4/Portfile
Labels: maintainer: requires approval

#4515 openjpeg15: remove old conflict handler
  graphics/openjpeg15/Portfile
Labels: maintainer: none

#4513 py-google-api: update to 1.7.9
  python/py-google-api/Portfile
Labels: maintainer: none, type: update

#4488 osxfuse: Update to 3.9.0
  fuse/osxfuse/Portfile
Labels: maintainer: open, maintainer: timeout, type: update

#4523 php-sqlsrv: New port, versions 5.6.1 and 5.3.0
  php/php-sqlsrv/Portfile
Labels: by: member, type: submission

#4524 minio[-mc]: Update to latest
  www/minio-mc/Portfile
  www/minio/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#4525 py-htmldocs: Updates to latest versions.
  lang/py-htmldocs/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#4522 Gildas: update to 201906b
  science/gildas/Portfile
Labels: maintainer, type: update

#4528 Security update to pam-u2f
  security/pam-u2f/Portfile
Labels: maintainer: open, type: security fix

#4532 jdupes: update to 1.13
  sysutils/jdupes/Portfile
Labels: maintainer, maintainer: open, type: update

#4529 terraform: update to 0.12.1
  sysutils/terraform/Portfile
Labels: maintainer, maintainer: open, type: update

#4530 node_exporter: update to 0.18.1
  net/node_exporter/Portfile
Labels: maintainer, maintainer: open, type: update

#4533 PothosWidgets: fix qt5 components
  science/PothosWidgets/Portfile
Labels: maintainer, maintainer: open, type: bugfix

#4537 minio: update to latest.
  www/minio/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#4536 neovim: Update to v0.3.7
  editors/neovim/Portfile
Labels: maintainer: open, type: update

#4535 swi-prolog-devel: update to 8.1.7
  lang/swi-prolog-devel/Portfile
Labels: maintainer, type: update

#4540 nomad: update to 0.9.2
  net/nomad/Portfile
Labels: maintainer, maintainer: open, type: update

#4538 vault: update to 1.1.3
  security/vault/Portfile
Labels: maintainer, maintainer: open, type: update

#4534 node_exporter: correct log file location in notes
  net/node_exporter/Portfile
Labels: maintainer, maintainer: open

#4543 py-pyqt5: update to 5.12.2
  python/py-pyqt5/Portfile
Labels: maintainer: open, type: update

#4539 Tcl/Tk ports: use tcl-lang.org instead of tcl.tk
  devel/tklib/Portfile
  lang/tcl/Portfile
  x11/tk/Portfile
Labels: maintainer: open

#4542 p5-devel-nytprof: use MacPorts-installed scripts
  perl/p5-devel-nytprof/Portfile
  perl/p5-devel-nytprof/files/patch-bin-nytprofhtml.diff
Labels: maintainer: none, type: bugfix

#4547 irctree, xserve-raid-tools: delete ports
  irc/irctree/Portfile
  irc/irctree/files/patch-irctree-parse.pl
  sysutils/xserve-raid-tools/Portfile
Labels: maintainer: none

#4546 py-pyqt5-webengine: fix livecheck
  python/py-pyqt5/Portfile
Labels: maintainer: open

#4553 gitlab-runner: update to 11.11.2
  devel/gitlab-runner/Portfile
Labels: maintainer, maintainer: open, type: update

#4552 tor-devel: update to 0.4.1.2-alpha
  security/tor-devel/Portfile
Labels: maintainer: none, type: update

#4551 micronaut: update to 1.1.3
  java/micronaut/Portfile
Labels: maintainer, maintainer: open, type: update

#4471 doctl: new port
  www/doctl/Portfile
Labels: type: submission

#4531 dovecot2: Add missing build dependency port:automake
  mail/dovecot2/Portfile
Labels: maintainer: none, type: bugfix

#4550 mysql8: compile against cyrus-sasl2 for SASL dependency
  databases/mysql8/Portfile
Labels: maintainer, maintainer: open

#4545 Update to sysutils/glances
  sysutils/glances/Portfile
Labels: maintainer: open, type: update

#4555 py-gpilab*: Update to 1.0.6
  python/py-gpilab-core/Portfile
  python/py-gpilab-core/files/math_fft_PyMOD_cpp.patch
  python/py-gpilab-core/files/spiral.diff
  python/py-gpilab-framework/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#4557 mpich: update to 3.3.1
  science/mpich/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#4521 mpstats: add subport mpstats-gsoc and stop submission of inactive ports
  sysutils/mpstats/Portfile
  sysutils/mpstats/files/mpstats.plist.default
  sysutils/mpstats/files/mpstats.tcl
  sysutils/mpstats/files/stats-gsoc.conf
Labels: by: member, maintainer: open

#4560 py-django: update to 1.11.21 / 2.2.2
  python/py-django/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#4558 oksh: submission
  shells/oksh/Portfile
Labels: type: submission

#4526 Submission: scdoc @1.9.4
  textproc/scdoc/Portfile
  textproc/scdoc/files/patch-makefile.diff
Labels: type: submission

#4548 n2n: port abandoned
  net/n2n/Portfile
Labels: maintainer: open

#4549 yara: port abandoned
  security/yara/Portfile
Labels: maintainer: open

#4517 py-py: remove old conflict handler
  python/py-py/Portfile
Labels: maintainer: open

#4498 perl5.30: new port
  lang/perl5/Portfile
  lang/perl5/files/5.30/avoid-no-cpp-precomp-PR38913.patch
  lang/perl5/files/5.30/clean-up-paths.patch
  lang/perl5/files/5.30/config.h.ed
  lang/perl5/files/5.30/enable-syscall-on-sierra.patch
  lang/perl5/files/5.30/fix-db_file-paths.patch
  lang/perl5/files/5.30/fix-miniperl-linking-PR36438.patch
  lang/perl5/files/5.30/install-under-short-version-PR43480.patch
  lang/perl5/files/5.30/patch-Configure-remove-libs.diff
Labels: by: member, maintainer, maintainer: open

#4167 tomcat6, servlet25-api: delete EOL ports
  java/servlet25-api/Portfile
  java/tomcat6/Portfile
  java/tomcat6/files/conf_setup.sh
  java/tomcat6/files/patch-bin-catalina.sh
  java/tomcat6/files/patch-build.properties.default
  java/tomcat6/files/patch-build.xml.diff
  java/tomcat6/files/patch-catalina.sh
  java/tomcat6/files/setenv.local
  java/tomcat6/files/setenv.sh
  java/tomcat6/files/tomcat6.sh
  java/tomcat6/files/tomcatctl
Labels: maintainer: open

#4567 pgbadger: update to 10.3
  databases/pgbadger/Portfile
Labels: maintainer: none, type: enhancement, type: update

#4562 mysql8: prevent using external boost libs
  databases/mysql8/Portfile
  databases/mysql8/files/patch-sql-local-boost.diff
Labels: maintainer, maintainer: open, type: bugfix

#4565 QCA upgrade for future botan2 compat (see trac #58567)
  devel/qca/Portfile
  devel/qca/files/patch-cmakeminver.diff
  devel/qca/files/patch-configure.diff
  devel/qca/files/patch-installname.diff
  devel/qca/files/patch-macports-clang.diff
  devel/qca/files/patch-qca-ossl.diff
  devel/qca/files/patch-qca210-qt550.diff
  devel/qca/files/patch-qca210-qt56x.diff
  devel/qca/files/patch-src_botantools_botan_botan_secmem.h.diff
  devel/qca/files/patch-src_qac_systemstore_mac.cpp.diff
Labels: maintainer, maintainer: open

#4564 hexchat: update to 2.14.2
  irc/hexchat/Portfile
  irc/hexchat/files/0003-Python-plugin-Call-EndInterpreter-when-deinit-ing-th.patch
  irc/hexchat/files/patch-Fix-plugins-on-macOS.diff
  irc/hexchat/files/patch-build-Add-option-to-specify-path-to-perl-binary.diff
  irc/hexchat/files/patch-build-perl-as-a-dependency.diff
Labels: maintainer: open, type: update

#4556 mail/notmuch: Update to 0.29
  mail/notmuch/Portfile
  mail/notmuch/files/notmuch-0.29-doc-makefile.patch
Labels: maintainer, maintainer: open, type: update

#4570 drop maintainership
  audio/libsamplerate/Portfile
  audio/libsndfile/Portfile
  audio/rtptools/Portfile
  audio/sox/Portfile
  textproc/lowdown/Portfile
  textproc/mandoc/Portfile
Labels: maintainer

#4573 mail/notmuch: configure script bugfix, dependency update
  mail/notmuch/Portfile
  mail/notmuch/files/notmuch-0.29-configure.patch
Labels: maintainer, maintainer: open

#4574 jdupes: update to 1.13.1
  sysutils/jdupes/Portfile
Labels: maintainer, maintainer: open, type: update

#4575 poppler: really fix self-build conflict
  graphics/poppler/Portfile
Labels: by: member, maintainer: open, type: bugfix

#4563 py27-scipy, py34-scipy: update to 1.2.2
  python/py-scipy/Portfile
Labels: maintainer: open, type: update

#4580 php-xdebug: update to 2.7.2
  php/php-xdebug/Portfile
Labels: maintainer: open, type: bugfix, type: enhancement, type: update

#4572 rspamd: Update to v1.9.4
  mail/rspamd/Portfile
Labels: maintainer: none, type: bugfix, type: enhancement, type: update

#4576 mail/notmuch: configure phase bugfix V2
  mail/notmuch/files/notmuch-0.29-configure.patch
Labels: maintainer, maintainer: open

#4584 exim: update to 4.92
  mail/exim/Portfile
Labels: maintainer: none, type: security fix, type: update

#4582 new port: sshuttle
  net/sshuttle/Portfile
Labels: type: submission

#4583 ipfs: submission
  net/ipfs/Portfile
Labels: type: submission

#4589 sshuttle: fix Python versions
  net/sshuttle/Portfile
Labels: maintainer, maintainer: open

#4588 net/bwping: update to 1.15
  net/bwping/Portfile
Labels: maintainer, maintainer: open, type: update

#4591 p5-datemanip: remove obsolete port
  perl/p5-datemanip/Portfile
  perl/p5-graveyard/Portfile
Labels: maintainer: none

#4590 sshuttle: requires setuptools to run
  net/sshuttle/Portfile
Labels: maintainer, maintainer: open

#4586 botan: minor changes for botan2 and simplification/cleanup
  devel/qca/Portfile
Labels: maintainer, maintainer: open

#4566 mosh: include a patch for bind function
  net/mosh/Portfile
  net/mosh/files/network-bind.patch
Labels: maintainer: open, type: bugfix

#4544 hugo: add extended variant for Sass/SCSS support.
  www/hugo/Portfile
Labels: maintainer: open, type: enhancement

#4581 py-uncertainties: update to 3.1.1, add noarch
  python/py-uncertainties/Portfile
Labels: by: member, maintainer: open, type: update

#4598 py-httpbin: new port
  python/py-httpbin/Portfile
  python/py-httpbin/files/patch-test_httpbin.py.diff
Labels: by: member, type: submission

#4569 py-treq: new port
  python/py-treq/Portfile
Labels: by: member, type: submission

#4601 osxfuse: Revert to 3.8.3
  fuse/osxfuse/Portfile
Labels: maintainer: open

#4604 nomad: update to 0.9.3
  net/nomad/Portfile
Labels: maintainer, maintainer: open, type: update

#4603 terraform: update to 0.12.2
  sysutils/terraform/Portfile
Labels: maintainer, maintainer: open, type: update

#4596 ports abandoned by gmail.com:blair.christensen
  perl/p5-net-twitter-lite/Portfile
  perl/p5-object-tiny/Portfile
  perl/p5-shell-parser/Portfile
  ruby/rb-bones/Portfile
  ruby/rb-configuration/Portfile
  ruby/rb-cucumber/Portfile
  ruby/rb-diff-lcs/Portfile
  ruby/rb-heroku/Portfile
  ruby/rb-innate/Portfile
  ruby/rb-launchy/Portfile
  ruby/rb-nitpick/Portfile
  ruby/rb-polyglot/Portfile
  ruby/rb-rack/Portfile
  ruby/rb-ramaze/Portfile
  ruby/rb-rest-client/Portfile
  ruby/rb-term-ansicolor/Portfile
  ruby/rb-treetop/Portfile
  ruby/rb19-configuration/Portfile
  ruby/rb19-heroku/Portfile
  ruby/rb19-launchy/Portfile
  ruby/rb19-rest-client/Portfile
Labels: maintainer: open

#4594 mhddfs, mdf2iso: ports abandoned
  fuse/mhddfs/Portfile
  sysutils/mdf2iso/Portfile
Labels: maintainer: requires approval

#4592 ports abandoned by googlemail.com:usx303
  net/argus-clients/Portfile
  security/libprelude/Portfile
  security/libpreludedb/Portfile
  security/nbtscan/Portfile
  security/prelude-lml/Portfile
  security/prelude-manager/Portfile
Labels: maintainer: requires approval

#4602 SleepTight: Remove obsolete port
  aqua/SleepTight/Portfile
Labels: by: member, maintainer: none

#4599 p5-graveyard: remove obsolete perl5.24 subports outdated as of 20190308
  perl/p5-graveyard/Portfile
Labels: by: member, maintainer: none

#4130 fpc: Update to 3.0.4 and improvements
  lang/fpc/Portfile
  lang/fpc/files/patch-iso-tmp.diff
  lang/fpc/files/patch-transparent-filename.diff
Labels: maintainer: none, type: enhancement, type: update

#4597 mysql8: Remove unneeded patch
  databases/mysql8/Portfile
  databases/mysql8/files/patch-disable-xcode-check.diff
Labels: by: member, maintainer: open

#4600 go: update to version 1.12.6
  lang/go/Portfile
Labels: maintainer: open, type: enhancement, type: update

#4614 py-rencode: new port
  python/py-rencode/Portfile
Labels: by: member, type: submission, wip

#4579 new port: websocat
  net/websocat/Portfile
Labels: type: submission

#4612 openjdk8: update to 8u212-b04
  java/openjdk8/Portfile
Labels: maintainer, maintainer: open, type: update

#4613 openjdk11-openj9*: Update to AdoptOpenJDK 11.0.3+7-openj9-0.14.3
  java/openjdk8/Portfile
Labels: maintainer, maintainer: open, type: update

#4615 py-m2crypto: update to 0.35.2
  python/py-m2crypto/Portfile
Labels: maintainer, maintainer: open, type: update

#4605 sf-pwgen: Submission of macOS command line password generator
  security/sf-pwgen/Portfile
Labels: type: submission

#4608 helm: submission
  sysutils/helm/Portfile
Labels: type: submission

#4585 Argus ports: use HTTPS URLs
  net/argus-clients/Portfile
  net/argus/Portfile
Labels: maintainer: open

#4519 tor: Add startupitem and basic working configuration
  security/tor/Portfile
Labels: maintainer: none, type: enhancement

#4481 dovecot2-sieve: Upgrade to v0.5.6, dovecot v2.3.6, Portfile overhaul
  mail/dovecot2-sieve/Portfile
Labels: maintainer: none, type: bugfix, type: enhancement

#4084 nccmp: new port
  science/nccmp/Portfile
Labels: by: member, type: submission

#4610 python34: support OpenSSL 1.1
  lang/python34/Portfile
  lang/python34/files/patch-openssl11.diff
Labels: by: member, maintainer: open, type: enhancement

#4618 GPXSee: update to 7.9
  gis/GPXSee/Portfile
Labels: maintainer, maintainer: open, type: enhancement, type: update

#4619 rclone: update to 1.48.0
  net/rclone/Portfile
Labels: maintainer: open, type: update

#4617 graalvm: new port submission
  java/graalvm/Portfile
Labels: type: submission

#4626 flrig: update version to 1.3.45
  science/flrig/Portfile
Labels: maintainer, maintainer: open, type: update

#4622 py-filterpy: update to 1.4.5
  python/py-filterpy/Portfile
Labels: maintainer, maintainer: open, type: update

#4607 Update to lang/python38-devel
  lang/python38-devel/Portfile
  lang/python38-devel/files/patch-libedit.diff
  lang/python38-devel/files/patch-setup.py.diff
Labels: maintainer: open, type: update

#4630 crfpp-devel: remove obsolete port
  math/crfpp-devel/Portfile
Labels: maintainer: none

#4629 google-collections: remove obsolete port
  java/google-collections/Portfile
Labels: maintainer: none

#4628 gsutil: remove obsolete port
  net/gsutil/Portfile
Labels: maintainer: none

#4627 logtalk: update to 3.27.0
  lang/logtalk/Portfile
Labels: maintainer, type: update

#4620 swi-prolog-devel: update to 8.1.8
  lang/swi-prolog-devel/Portfile
Labels: maintainer, type: update

#4559 new port: alertmanager
  net/alertmanager/Portfile
  net/alertmanager/files/org.macports.alertmanager.plist
Labels: type: submission

#4631 p5-tcl-ptk: update to 1.00
  perl/p5-tcl-ptk/Portfile
Labels: maintainer, maintainer: open, type: update

#4634 spring-boot-cli: update to 2.1.6
  java/spring-boot-cli/Portfile
Labels: maintainer, maintainer: open, type: update

#4593 vlc: update to 3.0.7.1
  multimedia/VLC/Portfile
  multimedia/VLC/files/patch-build-on-pre-1014.diff
  multimedia/VLC/files/patch-for-libvpx-1.8.0.diff
  multimedia/VLC/files/patch-vlc-fix-libssh2.diff
Labels: maintainer: open, type: security fix, type: update

#4638 grisbi: port abandoned
  gnome/grisbi/Portfile
Labels: maintainer: requires approval

#4639 tpkg: delete port
  sysutils/tpkg/Portfile
Labels: maintainer: open

#4642 fldigi: update to 4.1.04
  science/fldigi/Portfile
  science/fldigi/files/patch-info.plist.diff
Labels: maintainer, maintainer: open, type: update

#4637 openfortivpn: update to 1.10.0
  net/openfortivpn/Portfile
Labels: maintainer, maintainer: open, type: bugfix, type: enhancement, type: security fix, type: update

#4640 xsane: update homepage, master_sites, livecheck
  graphics/xsane/Portfile
Labels: by: member, maintainer: open, type: bugfix

#4643 minio[-mc]: Update to 2016-06-19
  www/minio-mc/Portfile
  www/minio/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#4636 gpsd-devel: Update to 20190619-48d3833c
  net/gpsd/Portfile
Labels: by: member, maintainer: open, type: update

#4645 Update to py-pyodbc
  python/py-pyodbc/Portfile
Labels: maintainer: none, type: enhancement, type: update

#4635 net/teleport: update to v4.0.0
  net/teleport/Portfile
Labels: maintainer, maintainer: open, type: update

#4644 doctl: update to 1.20.1
  www/doctl/Portfile
Labels: maintainer: open, type: enhancement, type: update

#4587 clamav-server: Update Portfile with major upgrade, enhancements, and bugfixes
  sysutils/clamav-server/Portfile
  sysutils/clamav-server/files/ClamavScanIt.sh
  sysutils/clamav-server/files/ClamavScanIt.workflow/Contents/Info.plist
  sysutils/clamav-server/files/ClamavScanIt.workflow/Contents/QuickLook/Preview.png
  sysutils/clamav-server/files/ClamavScanIt.workflow/Contents/QuickLook/Thumbnail.png
  sysutils/clamav-server/files/ClamavScanIt.workflow/Contents/Resources/background.color
  sysutils/clamav-server/files/ClamavScanIt.workflow/Contents/document.wflow
  sysutils/clamav-server/files/NOTICE
  sysutils/clamav-server/files/org.macports.clamd.plist
  sysutils/clamav-server/files/org.macports.freshclam.plist
  sysutils/clamav-server/files/patch-etc-clamd-conf-macports.diff
  sysutils/clamav-server/files/patch-etc-freshclam-conf-macports.diff
Labels: maintainer: none, type: bugfix, type: enhancement, type: security fix, type: update

#4646 notmuch: Update to 0.29.1
  mail/notmuch/Portfile
  mail/notmuch/files/notmuch-0.29-doc-makefile.patch
  mail/notmuch/files/notmuch-0.29.1-configure.patch
Labels: maintainer, maintainer: open, type: update

#4527 Submission: aerc @0.1.2
  mail/aerc/Portfile
Labels: type: submission

#4650 GnuPG ports: use HTTPS URLs
  devel/gpgme/Portfile
  devel/libgcrypt/Portfile
  devel/libgpg-error/Portfile
Labels: maintainer: open

#4652 Node.js ports: use HTTPS homepage
  devel/nodejs10/Portfile
  devel/nodejs11/Portfile
  devel/nodejs12/Portfile
Labels: maintainer: open

#4651 git: use HTTPS homepage
  devel/git/Portfile
Labels: maintainer: open

#4653 mysql-proxy: delete port
  databases/mysql-proxy/Portfile
Labels: maintainer: none

#4606 macos-vpn-server: Submission of macOS-native VPN (L2TP-IPSec-PSK) Server
  net/macos-vpn-server/Portfile
  net/macos-vpn-server/files/com.apple.RemoteAccessServers.plist.macports
  net/macos-vpn-server/files/org.macports.ppp.l2tp.plist
Labels: type: submission

#4658 yggdrasil-go: new port
  net/yggdrasil-go/Portfile
Labels: by: member, type: submission

#4655 iperf3: update to 3.7
  net/iperf3/Portfile
Labels: maintainer, maintainer: open, type: update

#4664 libomp: use HTTPS homepage
  lang/libomp/Portfile
Labels: maintainer: open

#4659 py-virtualenv: update to 16.6.1
  python/py-virtualenv/Portfile
Labels: by: member, maintainer: open, type: update

#4665 libunwind: use HTTPS master_sites
  devel/libunwind/Portfile
Labels: maintainer: open

#4654 py-sure: new port, version 1.4.11
  python/py-sure/Portfile
Labels: by: member, type: submission

#4656 py-parameterized: new port, version 0.7.0
  python/py-parameterized/Portfile
Labels: by: member, type: submission

#4662 py-kiwisolver: update to 1.1.0
  python/py-kiwisolver/Portfile
Labels: by: member, maintainer: open, type: update

#4623 libiconv: remove cp932fix variant
  textproc/libiconv/Portfile
Labels: by: member, maintainer: requires approval, type: bugfix

#4671 nmap: use HTTPS homepage
  net/nmap/Portfile
Labels: maintainer: requires approval

#4489 buildbot: new ports
  devel/buildbot-2/Portfile
  devel/buildbot-2/files/org.macports.buildmaster.template.plist
  devel/buildbot-worker/Portfile
  devel/buildbot-worker/files/org.macports.buildbot-worker.template.plist
  python/py-buildbot-console-view/Portfile
  python/py-buildbot-grid-view/Portfile
  python/py-buildbot-pkg/Portfile
  python/py-buildbot-waterfall-view/Portfile
  python/py-buildbot-www/Portfile
  python/py-buildbot/Portfile
Labels: by: member, type: submission

#4660 py-qtpy: update to 1.8.0
  python/py-qtpy/Portfile
Labels: by: member, maintainer: open, type: update

#4672 p5-tcl-ptk: update to 1.01
  perl/p5-tcl-ptk/Portfile
Labels: maintainer, maintainer: open, type: update

#4648 xsane: update to version 0.999
  graphics/xsane/Portfile
Labels: by: member, maintainer: open, type: update

#4678 meson: update to 0.51.0
  devel/meson/Portfile
Labels: maintainer, maintainer: open, type: update

#4680 jack: remove old conflict handler
  audio/jack/Portfile
Labels: maintainer: none

#4677 google-cloud-sdk: update to 251.0.0
  devel/google-cloud-sdk/Portfile
Labels: maintainer, maintainer: open, type: update

#4670 abiword-x11: deactivate champlain due to crashes
  editors/abiword-x11/Portfile
Labels: by: member, maintainer: none, type: bugfix
