Repository macports/macports-ports, pull requests merged in 2019-02, with the labels that each got.

#3546 freedink ports: set nomaintainer
  games/freedink-data/Portfile
  games/freedink/Portfile
Labels: maintainer: requires approval

#3547 Multiple ruby ports: set to nomaintainer
  ruby/rb-activeldap/Portfile
  ruby/rb-mechanize/Portfile
  ruby/rb-piston/Portfile
  ruby/rb-snmp/Portfile
Labels: maintainer: requires approval

#3551 CocoaDialog: Update to 2.3.7
  aqua/CocoaDialog/Portfile
  aqua/CocoaDialog/files/cocoadialog.in
  aqua/CocoaDialog/files/fix-Changelog-case.patch
  aqua/CocoaDialog/files/no-Werror.patch
  aqua/CocoaDialog/files/no-sparkle.patch
  aqua/CocoaDialog/files/patch-AppController.h
  aqua/CocoaDialog/files/patch-AppController.m
  aqua/CocoaDialog/files/patch-CDControl.h
  aqua/CocoaDialog/files/patch-CDControl.m
  aqua/CocoaDialog/files/patch-KABubbleWindow.m
  aqua/CocoaDialog/files/patch-KABubbleWindowView.h
  aqua/CocoaDialog/files/patch-KABubbleWindowView.m
  aqua/CocoaDialog/files/update-Changelog.patch
  aqua/CocoaDialog/files/update-URLs.patch
Labels: by: member, maintainer: none, type: update

#3553 terminus-font: update to version 4.47
  x11/terminus-font/Portfile
Labels: maintainer, maintainer: open, type: update

#3554 micronaut: update to 1.0.4
  java/micronaut/Portfile
Labels: maintainer, maintainer: open, type: update

#3555 openjdk8-openj9: add correct descriptions
  java/openjdk8/Portfile
Labels: maintainer, maintainer: open, type: bugfix

#3545 Nagios ports: use https urls
  net/nagios-plugins/Portfile
  net/nagios/Portfile
Labels: maintainer: none

#3558 abook: set to nomaintainer
  mail/abook/Portfile
Labels: maintainer: requires approval

#3550 py-spyder-devel: update to b4a6804 (20190131)
  python/py-spyder-devel/Portfile
  python/py-spyder-devel/files/patch-spyder_app_mainwindow.py.diff
  python/py-spyder-devel/files/patch-spyder_config_main.py.diff
  python/py-spyder-devel/files/patch-spyder_plugins_editor_plugin.py.diff
Labels: maintainer, maintainer: open, type: update

#3567 mspdebug: add missing dependency on readline
  devel/mspdebug/Portfile
Labels: by: member, maintainer: open, type: bugfix

#3569 tcl: remove outdated comment
  lang/tcl/Portfile
Labels: maintainer: open

#3543 xorg-server-devel: avoid redefinition error on older compilers
  x11/xorg-server-devel/Portfile
  x11/xorg-server-devel/files/5006-patch-xorg-server-dont-redefine-GLXscreen.diff
  x11/xorg-server-devel/files/5007-patch-randr-randrstr-h-dont-redefine-CARD32.diff
Labels: by: member, maintainer: open

#3568 gcin: set to nomaintainer
  x11/gcin/Portfile
Labels: maintainer: requires approval

#3564 py-qtpy: update to 1.6.0
  python/py-qtpy/Portfile
Labels: maintainer: open, type: update

#3575 mkcert: update to 1.3.0
  security/mkcert/Portfile
Labels: maintainer, maintainer: open, type: update

#3576 zabbix4: update to 4.0.4
  net/zabbix4/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#3566 py-pytest: update to 4.2.0
  python/py-pytest/Portfile
Labels: maintainer: open, type: update

#3577 groovy: update to 2.5.6
  lang/groovy/Portfile
Labels: maintainer, maintainer: open, type: update

#3579 hugo: update to 0.54.0
  www/hugo/Portfile
Labels: maintainer, maintainer: open, type: update

#3580 ninja: Update to 1.9.0
  devel/ninja/Portfile
  devel/ninja/files/patch-configure.py-CXXFLAGS.diff
Labels: maintainer: open, type: update

#3581 Improve grammar in portfile comments
  databases/sqlite3/Portfile
  devel/developer_cmds/Portfile
Labels: maintainer: open

#3571 Binutils 2.32
  _resources/port1.0/group/crossbinutils-1.0.tcl
  cross/arm-elf-binutils/Portfile
  cross/arm-none-linux-gnueabi-binutils/Portfile
  cross/avr-binutils/Portfile
  cross/i386-elf-binutils/Portfile
  cross/i686-w64-mingw32-binutils/Portfile
  cross/m68k-elf-binutils/Portfile
  cross/mips-elf-binutils/Portfile
  cross/ppc-linux-binutils/Portfile
  cross/spu-binutils/Portfile
  cross/x86_64-elf-binutils/Portfile
  cross/x86_64-w64-mingw32-binutils/Portfile
  devel/binutils/Portfile
Labels: by: member, maintainer

#3548 mpfr: update version 4.0.1->4.0.2
  devel/mpfr/Portfile
Labels: by: member, maintainer: open, type: enhancement

#3535 fribidi: update version 0.19.7->1.0.5
  textproc/fribidi/Portfile
Labels: by: member, maintainer: open, type: enhancement

#3584 meson: update to 0.49.2
  devel/meson/Portfile
Labels: maintainer, maintainer: open, type: update

#3585 Fixes #55850: Resolve correct CXX11 dependency
  science/seqan-apps/Portfile
Labels: maintainer, type: bugfix

#3472 free42: update to 2.0.22
  emulators/free42/Portfile
  emulators/free42/files/patch-Free42.xcodeproj.diff
Labels: by: member, maintainer, maintainer: open, type: update

#3586 openjdk11-openj9: update to 11.0.2+9_openj9-0.12.1
  java/openjdk8/Portfile
Labels: maintainer, maintainer: open, type: update

#3565 py-language-server: update to 0.22.1
  python/py-language-server/Portfile
Labels: maintainer: open, type: update

#3528 QLColorCode: Update to 2.1.0
  sysutils/QLColorCode/Portfile
  sysutils/QLColorCode/files/patch-xcode.diff
Labels: type: update

#3588 radare2: update to 3.2.1
  devel/radare2/Portfile
Labels: by: member, maintainer: open, type: update

#3589 mod_perl2: update to use perl5.28
  www/mod_perl2/Portfile
Labels: maintainer: none, type: enhancement, type: update

#3592 openjdk8: add OpenJ9 subports with large heap support
  java/openjdk8/Portfile
Labels: maintainer, maintainer: open

#3593 openjdk8-openj9: update to 8u202-b08_openj9-0.12.1
  java/openjdk8/Portfile
Labels: maintainer, maintainer: open, type: update

#3595 kotlin: update to 1.3.21
  lang/kotlin/Portfile
Labels: maintainer, maintainer: open, type: update

#3596 docker-machine: Update to 0.16.1
  devel/docker-machine/Portfile
Labels: by: member, maintainer: none, type: update

#3591 py-typed-ast: update to 1.3.1
  python/py-typed-ast/Portfile
Labels: maintainer, maintainer: open, type: update

#3597 mpi-doc: Update to 3.3
  science/mpi-doc/Portfile
Labels: maintainer: open, type: update

#3600 Security update to libu2f-host
  security/libu2f-host/Portfile
Labels: maintainer: open, type: security fix

#3562 py-virtualenv: update to 16.3.0, disable tests
  python/py-virtualenv/Portfile
Labels: maintainer: requires approval, maintainer: timeout, type: update

#3603 libomp: Add clang-7.0 to the blacklist when not available.
  lang/libomp/Portfile
Labels: by: member, maintainer, maintainer: open

#3604 mosquitto: Update to version 1.5.6.
  net/mosquitto/Portfile
Labels: maintainer, maintainer: open, type: security fix, type: update

#3606 bison: update to 3.3.2
  devel/bison/Portfile
Labels: by: member, maintainer: none, type: update

#3610 gradle: update to 5.2.1
  devel/gradle/Portfile
Labels: maintainer: open, type: update

#3607 renameutils: update to 0.12.0
  sysutils/renameutils/Portfile
  sysutils/renameutils/files/patch-fix_install.diff
  sysutils/renameutils/files/patch-use_coreutils.diff
Labels: maintainer: none, type: update

#3605 gnome-internet-radio-locator version 1.7.0
  gnome/gnome-internet-radio-locator/Portfile
Labels: maintainer, maintainer: open, type: enhancement

#3614 smtube: added myself as co-maintainery
  www/smtube/Portfile
Labels: maintainer: open

#3582 mod_maxminddb: new port
  www/mod_maxminddb/Portfile
  www/mod_maxminddb/files/patch-Wl.diff
Labels: type: enhancement, type: submission

#3619 fuse/s3fs: update to latest 1.84 from github
  fuse/s3fs/Portfile
Labels: by: member, maintainer: none, type: update

#3608 dnsviz: update to version 0.8.1
  net/dnsviz/Portfile
Labels: maintainer, maintainer: open, type: update

#3609 google-cloud-sdk: update to 233.0.0
  devel/google-cloud-sdk/Portfile
Labels: maintainer, maintainer: open, type: update

#3628 cppcheck: update to 1.87
  devel/cppcheck/Portfile
Labels: maintainer: none, type: update

#3627 py-dateutil: update to 2.8.0
  python/py-dateutil/Portfile
Labels: maintainer: none, type: update

#3620 fricas: Updated to version 1.3.5
  math/fricas/Portfile
Labels: maintainer, type: enhancement

#3612 py-backports.weakref: declare py34/py35/py36 obsolete
  python/py-graveyard/Portfile
Labels: maintainer: open, type: bugfix

#3578 ncdu: Update to 1.14
  python/py-graveyard/Portfile
Labels: maintainer: open, type: update

#3611 taucs: new port
  math/taucs/Portfile
  math/taucs/files/patch-dylib.diff
  math/taucs/files/patch-ldflags.diff
  math/taucs/files/patch-taucs-build.diff
Labels: by: member, type: enhancement, type: submission

#3561 osxfuse: update to version 3.8.3
  fuse/osxfuse/Portfile
Labels: maintainer: open, type: update

#3623 math/nfft-3: update to 3.5.0 (the latest)
  math/nfft-3/Portfile
Labels: by: member, maintainer: open, type: update

#3629 curl: security update to version 7.64.0
  net/curl/Portfile
Labels: by: member, maintainer: requires approval, type: security fix

#3630 php: update to php72 to 7.2.15 and php73 to 7.3.2
  lang/php/Portfile
Labels: by: member, maintainer: requires approval, type: update

#3631 py-rope: update to 0.12.0
  python/py-rope/Portfile
Labels: maintainer, maintainer: open, type: update

#3626 xorg-libXau: update to 1.0.9
  x11/xorg-libXau/Portfile
Labels: maintainer: open, type: bugfix, type: update

#3602 dcmtk: Add jpeg dependency and small patch
  graphics/dcmtk/Portfile
Labels: by: member, maintainer, maintainer: open

#3635 py-yapf: update to 0.26.0
  python/py-yapf/Portfile
Labels: maintainer: open, type: update

#3640 py-libxml2: update to version 2.9.9
  python/py-libxml2/Portfile
  python/py-libxml2/files/libxml2-2.9.4-remove-pyverify_fd.patch
Labels: by: member, maintainer: open, type: update

#3616 iTerm2: update to 3.2.7 and fix version strings
  aqua/iTerm2/Portfile
  azure-pipelines.yml
Labels: by: member, maintainer: open, type: bugfix, type: update

#3643 vault: update to 1.0.3
  security/vault/Portfile
Labels: maintainer, maintainer: open, type: update

#3637 py-bokeh: Add py-Pillow as a dependency
  python/py-bokeh/Portfile
Labels: maintainer: open, type: bugfix

#3644 mplayer: patch internal ffmpeg for libx264
  multimedia/MPlayer/Portfile
  multimedia/MPlayer/files/patch-mplayer-libx264-updated.diff
Labels: by: member, maintainer: open, type: bugfix

#3645 minio[-mc]: Update to latest.
  www/minio-mc/Portfile
  www/minio/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#3641 mplayer-devel: update to latest upstream commit
  multimedia/mplayer-devel/Portfile
  multimedia/mplayer-devel/files/configure.vorbis.patch
  multimedia/mplayer-devel/files/configure.x11.patch
Labels: by: member, maintainer: open, type: bugfix, type: enhancement, type: update

#3642 mongodb: license changed to SSPL since 4.0.4
  databases/mongodb/Portfile
Labels: by: member, maintainer: requires approval, type: bugfix

#3646 bfs: update to 1.3.3
  sysutils/bfs/Portfile
Labels: maintainer, maintainer: open, type: enhancement, type: update

#3647 shadowfox-updater: update to 1.7.20
  www/shadowfox-updater/Portfile
Labels: maintainer, maintainer: open, type: enhancement, type: update

#3648 dcmtk: revert change to PACKAGE_VERSION name
  graphics/dcmtk/Portfile
Labels: by: member, maintainer: open, type: bugfix

#3650 org-mode: update to 9.2.1, use https homepage
  editors/org-mode/Portfile
Labels: by: member, maintainer: requires approval, type: update

#3654 rclone: update to 1.46.0
  net/rclone/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#3625 diff-pdf: new Portfile
  graphics/diff-pdf/Portfile
Labels: type: submission

#3657 qemu: disable capstone to avoid stealth linking
  emulators/qemu/Portfile
Labels: by: member, maintainer: open, type: bugfix

#3658 teleport: update to v3.1.6
  net/teleport/Portfile
Labels: maintainer, maintainer: open, type: update

#3659 ipcalc: require perl5.28.
  net/ipcalc/Portfile
Labels: maintainer, maintainer: open, type: enhancement

#3661 Gildas: update to 201902b
  science/gildas/Portfile
Labels: maintainer, type: update

#3660 dpkg: update to 1.19.4 and use perl5.28. Disable dselect.
  sysutils/dpkg/Portfile
Labels: maintainer, maintainer: open, type: enhancement, type: update

#3652 py-keyring: update to 18.0.0
  python/py-keyring/Portfile
Labels: maintainer, maintainer: open, type: update

#3663 x2goclient: Update linking for libssh 0.8.0.
  aqua/x2goclient/Portfile
Labels: by: member, maintainer: open

#3665 mplayer-devel: remove dirac variant
  multimedia/mplayer-devel/Portfile
Labels: by: member, maintainer: open

#3662 npm6: update to 6.8.0
  devel/npm6/Portfile
Labels: maintainer: open, type: enhancement, type: update

#3670 VLC, libVLC: fix build against new libx264
  multimedia/VLC/Portfile
  multimedia/VLC/files/patch-modules-codec-x264-new-api.diff
Labels: by: member, maintainer: open, type: bugfix

#3672 ruby26: fix build on lion
  lang/ruby26/Portfile
Labels: by: member, maintainer: open, type: bugfix

#3674 valgrind: fix build on lion
  devel/valgrind/Portfile
Labels: by: member, maintainer: open, type: bugfix

#3633 submission limesuite: support for the LMS7002M RFIC
  science/limesuite/Portfile
Labels: type: submission

#3679 py-language-server: update to 0.23.2
  python/py-language-server/Portfile
Labels: by: member, maintainer: open, type: update

#3681 jdupes: update to 1.12
  sysutils/jdupes/Portfile
Labels: maintainer, maintainer: open, type: update

#3682 mysql57: fixes to allow build
  databases/mysql57/Portfile
  databases/mysql57/files/patch-cmake-fix-test-env.diff
Labels: by: member, maintainer: none, type: bugfix

#3684 GPXSee: update to 7.3
  gis/GPXSee/Portfile
Labels: maintainer, maintainer: open, type: enhancement, type: update

#3690 py-checker: correct case for file in post-destroot
  python/py-checker/Portfile
Labels: maintainer: none, type: bugfix

#3686 gnome-internet-radio-locator: Update to version 1.9.0
  gnome/gnome-internet-radio-locator/Portfile
Labels: maintainer, maintainer: open, type: enhancement, type: update

#3673 birdfont: update to version 2.25.0
  graphics/birdfont/Portfile
  graphics/birdfont/files/fix-install-name.patch
  graphics/birdfont/files/patch_use_cc_and_ldflags_install_icons_and_translations.diff
Labels: by: member, maintainer: open, type: update

#3691 py-biggles: update to 1.72
  python/py-biggles/Portfile
Labels: maintainer: none, type: update

#3693 libvpx: restore build on Leopard Intel
  multimedia/libvpx/Portfile
Labels: by: member, maintainer: open

#3636 py-astroquery: update to version 0.3.9
  python/py-astroquery/Portfile
Labels: maintainer: open, type: enhancement, type: update

#3698 py-ansible: update to 2.7.7
  python/py-ansible/Portfile
Labels: maintainer: requires approval, type: update

#3700 zsh-completions: update to 0.30.0
  sysutils/zsh-completions/Portfile
Labels: maintainer: open, type: update

#3702 gnome-internet-radio-locator: Update to version 2.0.0
  gnome/gnome-internet-radio-locator/Portfile
Labels: maintainer, maintainer: open, type: enhancement, type: update

#3570 webkit-sharp: remove outdated port
  devel/webkit-sharp/Portfile
Labels: by: member, maintainer: open

#3692 p5-tex-encode: update to version 2.005
  perl/p5-tex-encode/Portfile
Labels: by: member, maintainer: open, type: bugfix, type: update

#3667 Arduino: add Portfile for Arduino 1.8.8
  devel/Arduino/Portfile
Labels: type: submission

#3708 Veclibfort : fix build on Tiger, enable tests
  devel/vecLibFort/Portfile
Labels: by: member, maintainer: requires approval, type: bugfix, type: enhancement

#3707 arpack: restore build on Tiger
  math/arpack/Portfile
Labels: by: member, maintainer: open, type: enhancement

#3705 libassuan: fix build on Tiger
  devel/libassuan/Portfile
  devel/libassuan/files/INADDR_LOOPBACK.patch
  devel/libassuan/files/patch-src-assuan-socket-tiger-needs-sys-select.diff
Labels: by: member, maintainer: open, type: bugfix

#3678 weechat: use upstream tarball
  irc/weechat/Portfile
Labels: by: member, maintainer: open, maintainer: timeout, type: enhancement

#3697 borgbackup: update to 1.1.9
  sysutils/borgbackup/Portfile
Labels: maintainer: open, type: update

#3710 radare2: update to 3.3.0
  devel/radare2/Portfile
Labels: by: member, maintainer: open, type: update

#3714 py-ansible: update to 2.7.8
  python/py-ansible/Portfile
Labels: by: member, maintainer: requires approval, type: security fix, type: update

#3711 tor-devel: update to 0.4.0.2-alpha
  security/tor-devel/Portfile
Labels: maintainer: none, type: update

#3676 Update audio/cmus 2.8.0 + arch=ppc support
  audio/cmus/Portfile
  audio/cmus/files/patch-ffmpeg-3.0.diff
  audio/cmus/files/patch-ffmpeg-4.0.diff
Labels: maintainer: open, type: bugfix, type: enhancement

#3689 libpixman: update to 0.38.0
  graphics/libpixman/Portfile
Labels: maintainer: requires approval, maintainer: timeout, type: enhancement, type: update

#3719 py-language-server: update to 0.24.0
  python/py-language-server/Portfile
Labels: maintainer: none, type: update

#3725 gitlab-runner: update to 11.8.0
  devel/gitlab-runner/Portfile
Labels: maintainer, maintainer: open, type: update

#3720 posix-manpages: new port
  devel/posix-manpages/Portfile
Labels: type: submission

#3696 Fix tuntaposx build for Mojave
  net/tuntaposx/Portfile
  net/tuntaposx/files/patch-mojave.diff
Labels: maintainer: none

#3583 fluidsynth: use configure.cc for all components
  multimedia/fluidsynth/Portfile
  multimedia/fluidsynth/files/patch-external_project_cc.diff
Labels: by: member, maintainer: open, type: bugfix

#3727 scite: fix build on Mojave
  editors/scite/Portfile
  editors/scite/files/patch-compile-error.diff
Labels: maintainer: none, type: bugfix

#3730 meson: enable test suite
  devel/meson/Portfile
Labels: by: member, maintainer: open, type: enhancement

#3737 gstreamer1-gst-plugins-base: enable tests
  gnome/gstreamer1-gst-plugins-base/Portfile
Labels: by: member, maintainer: none, type: enhancement

#3736 gstreamer1: fix build on Tiger
  gnome/gstreamer1/Portfile
  gnome/gstreamer1/files/patch-gst-gst-c-tiger-no-procpidpath.diff
Labels: by: member, maintainer: none, type: bugfix, type: enhancement

#3739 py-gnupg: update to 0.4.4
  python/py-gnupg/Portfile
Labels: by: member, maintainer: open, type: security fix, type: update

#3740 the_silver_searcher: fix build on older systems
  textproc/the_silver_searcher/Portfile
Labels: by: member, maintainer: open, type: bugfix

#3701 gnupg2: update to 2.2.13
  mail/gnupg2/Portfile
Labels: maintainer: open, maintainer: timeout, type: update

#3741 annie: update to 0.9.2
  net/annie/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#3745 py-isort: update to 4.3.8
  python/py-isort/Portfile
Labels: maintainer, maintainer: open, type: update

#3734 packer: update to 1.3.4
  sysutils/packer/Portfile
Labels: maintainer: open, type: update

#3746 tmux: update tmux-devel to latest commit
  sysutils/tmux/Portfile
Labels: maintainer

#3735 py-spyder-devel: update to 1e33e88 (20190224)
  python/py-spyder-devel/Portfile
  python/py-spyder-devel/files/patch-spyder_config_base.py.diff
  python/py-spyder-devel/files/patch-spyder_plugins_editor_lsp_client.py.diff
  python/py-spyder-devel/files/patch-spyder_utils_programs.py.diff
Labels: type: update

#3750 zabbix4: Update to 4.0.5; win32 agent no longer included.
  net/zabbix4/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#3747 p5-tcl-ptk: update to 0.95
  perl/p5-tcl-ptk/Portfile
  perl/p5-tcl-ptk/files/patch-Makefile.PL.diff
Labels: maintainer, maintainer: open, type: update

#3694 Add ProjectLibre 1.8.0
  office/ProjectLibre/Portfile
Labels: type: submission

#3754 ansifilter: update to 2.13
  textproc/ansifilter/Portfile
Labels: maintainer, maintainer: open, type: update

#3717 py-nmrglue: update to 0.7
  python/py-nmrglue/Portfile
Labels: maintainer: open, type: update

#3760 wireguard-tools: update to 0.0.20190227
  net/wireguard-tools/Portfile
Labels: maintainer, maintainer: open, type: update

#3759 caddy: new port
  www/caddy/Portfile
Labels: type: submission

#3743 mg: update to 20180927
  editors/mg/Portfile
  editors/mg/files/patch-configure.diff
Labels: maintainer: none, type: update

#3699 whois: update to 5.4.1
  net/whois/Portfile
  net/whois/files/patch-lcrypt.diff
Labels: maintainer: requires approval, maintainer: timeout, type: update

#3757 libdmtx: update to version 0.7.5
  graphics/libdmtx/Portfile
Labels: maintainer: none, type: enhancement, type: update

#3761 logtalk: update to 3.24.0
  lang/logtalk/Portfile
Labels: maintainer, type: update

#3718 py-flake8: update to 3.7.7
  python/py-flake8/Portfile
Labels: maintainer: open, type: update

#3713 yarn: update to 1.13.0
  devel/yarn/Portfile
Labels: by: member, maintainer: open, type: update

#3677 SourceKitten: Update to 0.22.0
  devel/SourceKitten/Portfile
Labels: maintainer: none, type: update

#3668 libaes_siv: new port
  security/libaes_siv/Portfile
  security/libaes_siv/files/patch-cmake.diff
Labels: type: submission
