Repository macports/macports-ports, pull requests merged in 2019-11, with the labels that each got.

#5665 git-lfs: switch to Ronn-NG for building docs
  devel/git-lfs/Portfile
Labels: by: member, maintainer: open, type: enhancement

#5620 py-arpeggio: update to 1.9.2 to fix checksum and permit use of tests
  python/py-arpeggio/Portfile
Labels: maintainer: none, type: bugfix, type: update

#5667 SDRangel: fix build on macos <= 10.11
  science/SDRangel/files/leandsdr_dvbs2.h.patch
Labels: maintainer, maintainer: open

#5669 welle.io: add welle.io-devel subport
  multimedia/welle.io/Portfile
Labels: maintainer: none, type: enhancement

#5652 bali-phy: update to 3.4.1
  science/bali-phy/Portfile
  science/bali-phy/files/patch-bali_phy_pkg.diff
  science/bali-phy/files/patch-bp_analyze.diff
  science/bali-phy/files/patch-keep.pl.diff
  science/bali-phy/files/patch-run_tests.py.diff
  science/bali-phy/files/scripts.patch
Labels: by: member, maintainer: open, type: update

#5674 icu: allow build on PowerPC systems
  devel/icu/Portfile
Labels: by: member, maintainer: none, type: bugfix

#5682 doxygen: requires c++11
  textproc/doxygen/Portfile
Labels: by: member, maintainer: open, type: bugfix

#5683 Revert "clang_select: Add some more entries"
  lang/llvm-8.0/files/mp-clang-8.0
  lang/llvm-9.0/files/mp-clang-9.0
  sysutils/clang_select/Portfile
  sysutils/clang_select/files/base
Labels: by: member, maintainer: requires approval

#5681 CubicSDR: fix version number and fix HighDpi wrong behaviour
  science/CubicSDR/Portfile
  science/CubicSDR/files/disable-highdpi.patch
Labels: maintainer, maintainer: open, type: bugfix

#5677 freedv-gui: update to 20191031-17671ccd
  science/freedv-gui/Portfile
Labels: maintainer, maintainer: open, type: update

#5679 gr-satellites: update version to 1.8.2
  science/gr-satellites/Portfile
  science/gr-satellites/files/patch-volk.diff
Labels: maintainer, maintainer: open, type: update

#5685 dpkg: update to 1.19.7.
  sysutils/dpkg/Portfile
Labels: maintainer, maintainer: open, type: update

#5684 dovecot2: Portfile bugfix for apns variant
  mail/dovecot2/Portfile
Labels: maintainer: none, type: bugfix

#5636 bmon-4.0: fix for undeclared identifier
  net/bmon/Portfile
  net/bmon/files/patch-fix__unused.diff
Labels: maintainer: open, type: bugfix

#5662 py-selenium: Update Portfile to use Python 3
  python/py-selenium/Portfile
Labels: maintainer: open, type: enhancement, type: update

#5417 kubectl: update to 1.16.2 and 1.15.4
  sysutils/kubectl/Portfile
Labels: maintainer: open, type: update

#5699 minikube: update to 1.5.2
  sysutils/minikube/Portfile
Labels: maintainer: open, type: update

#5660 libcxx: Avoid hardcoded list of clang compiler versions
  lang/libcxx/Portfile
Labels: by: member, maintainer: requires approval, maintainer: timeout

#5701 eksctl: update to 0.8.0
  sysutils/eksctl/Portfile
Labels: maintainer, maintainer: open, type: update

#5697 FAudio: Update to 19.11
  audio/FAudio/Portfile
Labels: maintainer: none, type: enhancement, type: update

#5672 terraform: update to 0.12.13
  sysutils/terraform/Portfile
Labels: maintainer, maintainer: open, type: update

#5707 packer: update to 1.4.5
  sysutils/packer/Portfile
Labels: maintainer, maintainer: open, type: update

#5713 nomad: update to 0.10.1
  net/nomad/Portfile
Labels: maintainer, maintainer: open, type: update

#5676 weechat: update to 2.6
  irc/weechat/Portfile
Labels: by: member, maintainer: open, type: update

#5715 lazygit: update to 0.9
  devel/lazygit/Portfile
Labels: maintainer, maintainer: open, type: update

#5712 dcc: Update to version 2.3.167
  mail/dcc/Portfile
Labels: maintainer: none, type: update

#5714 logtalk: Update to 3.32.0
  lang/logtalk/Portfile
Labels: maintainer, type: update

#5710 rspamd: Update to version 2.1
  mail/rspamd/Portfile
Labels: maintainer: none, type: update

#5709 hyperscan: Update to version 5.2.1
  textproc/hyperscan/Portfile
Labels: maintainer: none, type: update

#5698 Gildas: update to 201911a
  science/gildas/Portfile
Labels: maintainer, type: update

#5673 multiple ports: create PG to handle Xcode 11 bug
  _resources/port1.0/group/cltversion-1.0.tcl
  _resources/port1.0/group/xcode_workaround-1.0.tcl
  databases/redis/Portfile
  devel/gmp/Portfile
  lang/guile/Portfile
  lang/luajit/Portfile
  math/OpenBLAS/Portfile
  math/pari/Portfile
  multimedia/ffmpeg-devel/Portfile
  multimedia/ffmpeg/Portfile
  multimedia/x265/Portfile
  net/wrk/Portfile
  python/py-tensorflow/Portfile
  python/py-tensorflow1/Portfile
Labels: by: member, maintainer: open, type: bugfix, type: enhancement

#5718 dbeaver-community: update to 6.2.4
  databases/dbeaver-community/Portfile
Labels: maintainer, maintainer: open, type: update

#5706 apache-solr8: Update to version 8.3
  java/apache-solr8/Portfile
Labels: maintainer, maintainer: open, type: update

#5716 zabbix4*: updates 4.0.14 4.2.8 4.4.1
  net/zabbix4/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#5688 dns-server: Portfile improvements
  net/dns-server/Portfile
Labels: maintainer, maintainer: open, type: enhancement

#5671 rhyme: Fix build failure without /usr/include
  editors/vis/Portfile
  security/lastpass-cli/Portfile
  textproc/rhyme/Portfile
Labels: by: member, maintainer: requires approval, maintainer: timeout

#5726 mkvtoolnix: Update to 39.0.0
  multimedia/mkvtoolnix/Portfile
Labels: maintainer: open, type: update

#5708 dovecot2 and dovecot2-sieve: Update to version 2.3.8
  mail/dovecot2-sieve/Portfile
  mail/dovecot2/Portfile
Labels: maintainer: none, type: update

#5723 codec2: update version to d6f93b52
  audio/codec2/Portfile
Labels: maintainer, maintainer: open, type: update

#5724 cm256cc: update version to 8917b222
  science/cm256cc/Portfile
Labels: maintainer, maintainer: open, type: update

#5720 kubectx: update default kubectl dependency from 1.15 to 1.16
  sysutils/kubectx/Portfile
Labels: maintainer, maintainer: open, type: enhancement, type: update

#5719 kube-ps1: update default kubectl dependency from 1.15 to 1.16
  sysutils/kube-ps1/Portfile
Labels: maintainer, maintainer: open, type: enhancement, type: update

#5717 dbvis: update to 10.0.24
  databases/dbvis/Portfile
Labels: maintainer, maintainer: open, type: update

#5696 adblock2privoxy: Portfile enhancements
  www/adblock2privoxy/Portfile
Labels: maintainer, type: enhancement

#5692 xpkg: Delete port
  sysutils/xpkg/Portfile
  sysutils/xpkg/files/bison3.patch
Labels: by: member, maintainer: none

#5721 freedv-gui: update version to 7aa0b4d6
  science/freedv-gui/Portfile
Labels: maintainer, maintainer: open, type: update

#5728 google-cloud-sdk: update to 270.0.0
  devel/google-cloud-sdk/Portfile
Labels: maintainer, maintainer: open, type: update

#5695 gr-sdrplay: new port
  science/gr-sdrplay/Portfile
  science/gr-sdrplay/files/cmakelists.txt.patch
Labels: type: submission

#4992 cocoa-rest-client: new port
  www/CocoaRestClient/Portfile
Labels: type: submission

#5732 dcmtk: 3.6.5; use cxx11 PG.
  graphics/dcmtk/Portfile
Labels: by: member, maintainer, maintainer: open

#5733 vault: update to 1.2.4
  security/vault/Portfile
Labels: maintainer, maintainer: open, type: update

#5731 php-xdebug: update to 2.8.0
  php/php-xdebug/Portfile
Labels: maintainer: open, type: update

#5735 Update PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: type: enhancement, type: update

#5741 py-demjson: add py36 and py37
  python/py-demjson/Portfile
Labels: maintainer: none, type: enhancement

#5743 fribidi: fix CVE-2019-18397 - Stack buffer overflow
  textproc/fribidi/Portfile
  textproc/fribidi/files/CVE-2019-18397.patch
Labels: maintainer: none, type: security fix

#5736 splash: update to 2.9.1
  science/splash/Portfile
Labels: maintainer, type: update

#5675 gmt5: update gmt6 sub-port to version 6.0.0
  science/gmt5/Portfile
Labels: maintainer: requires approval, maintainer: timeout, type: update

#5631 SourceKitten: Update to 0.26.0
  devel/SourceKitten/Portfile
Labels: maintainer: none, type: update

#5694 gnuplot: allow build with MacPorts compilers
  math/gnuplot/Portfile
  math/gnuplot/files/patch-cxx20.diff
Labels: by: member, maintainer: open, type: bugfix

#5744 openjdk8: update OpenJ9 subports to OpenSSL 1.1.1d
  java/openjdk8/Portfile
Labels: maintainer, maintainer: open, type: security fix, type: update

#5745 tmux: update tmux-devel to latest commit
  sysutils/tmux/Portfile
Labels: maintainer, maintainer: open, type: update

#5750 gmp: allow build on older systems
  devel/gmp/Portfile
Labels: by: member, maintainer, maintainer: open, type: bugfix

#5746 qsynth: use original icns file
  audio/qsynth/Portfile
Labels: maintainer: open, type: bugfix

#5753 rxvt-unicode: fix build failure
  x11/rxvt-unicode/Portfile
  x11/rxvt-unicode/files/patch-perl-embed-args.diff
Labels: maintainer, maintainer: open

#5747 qt4-mac: allow newer compilers on older systems
  aqua/qt4-mac/Portfile
  aqua/qt4-mac/files/patch-compiler_standard.diff
  aqua/qt4-mac/files/patch-nis.diff
  aqua/qt4-mac/files/patch-test_compiler_version.diff
Labels: by: member, maintainer: open, type: bugfix

#5752 cross/dtc: update to version 1.5.1
  cross/dtc/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#5766 kubectl: Updating 1.15.5 and 1.14.8
  sysutils/kubectl/Portfile
Labels: maintainer, maintainer: open

#5762 javacc: update homepage
  java/javacc/Portfile
Labels: maintainer: none, type: update

#5764 qbs: Update to 1.14.1
  devel/qbs/Portfile
Labels: maintainer, maintainer: open, type: update

#5765 GPXSee: update to 7.17
  gis/GPXSee/Portfile
Labels: maintainer, maintainer: open, type: enhancement, type: update

#5757 lazygit: update to 0.10.4
  devel/lazygit/Portfile
Labels: maintainer, maintainer: open, type: update

#5768 wtfutil: update to 0.24.0
  sysutils/wtfutil/Portfile
Labels: maintainer, maintainer: open, type: update

#5738 nco: update to 4.8.1
  science/nco/Portfile
Labels: maintainer: requires approval, maintainer: timeout, type: enhancement, type: update

#5782 py-healpy: use OpenMP option from MacPorts 2.6.0
  python/py-healpy/Portfile
Labels: maintainer: requires approval, type: enhancement

#5791 gravity: update to 0.7.8
  lang/gravity/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#5756 mkcert: update to 1.4.1
  security/mkcert/Portfile
Labels: maintainer, maintainer: open, type: update

#5769 prometheus: update to 2.14.0; Prometheus now requires Yarn at build-t…
  net/prometheus/Portfile
Labels: maintainer, maintainer: open, type: update

#5772 ansifilter: update to 2.15
  textproc/ansifilter/Portfile
Labels: maintainer, maintainer: open, type: update

#5779 freedv-gui: update version to 1.4
  science/freedv-gui/Portfile
  science/freedv-gui/files/patch-info.plist.diff
  science/freedv-gui/files/patch-src_cmakelists.txt.diff
Labels: maintainer, maintainer: open, type: update

#5784 google-cloud-sdk: update to 271.0.0
  devel/google-cloud-sdk/Portfile
Labels: maintainer, maintainer: open, type: update

#5785 spring-boot-cli: update to 2.2.1
  java/spring-boot-cli/Portfile
Labels: maintainer, maintainer: open, type: update

#5786 micronaut: update to 1.2.6
  java/micronaut/Portfile
Labels: maintainer, maintainer: open, type: update

#5754 helm: add subports (2.16.0, 2.15.2), co-maintainer
  sysutils/helm/Portfile
  sysutils/helm/files/helm2.15
  sysutils/helm/files/helm2.16
Labels: maintainer: open, type: enhancement

#5689 macos-vpn-server: Portfile enhancements
  net/dns-server/Portfile
  net/macos-vpn-server/Portfile
Labels: maintainer, maintainer: open, type: enhancement

#5687 mail-server: Portfile and launch daemon improvements and bugfixes
  mail/dovecot2/Portfile
  mail/mail-server/Portfile
  mail/mail-server/files/prefix/etc/dovecot/conf.d/10-auth.conf
  mail/mail-server/files/prefix/etc/dovecot/conf.d/10-mail.conf
  mail/mail-server/files/prefix/etc/dovecot/conf.d/10-master.conf
  mail/mail-server/files/prefix/etc/dovecot/conf.d/10-ssl.conf
  mail/mail-server/files/prefix/etc/dovecot/conf.d/15-mailboxes.conf
  mail/mail-server/files/prefix/etc/dovecot/conf.d/auth-od.conf.ext
  mail/mail-server/files/prefix/etc/postfix/main.cf
  mail/mail-server/files/prefix/etc/postfix/smtp.keytab.README.sh
Labels: maintainer, maintainer: open, type: bugfix, type: enhancement

#5795 swi-prolog-devel: update to 8.1.16
  lang/swi-prolog-devel/Portfile
Labels: maintainer, type: update

#5778 codec2: update version to 0.9.2
  audio/codec2/Portfile
Labels: maintainer, maintainer: open, type: update

#5781 lazygit: update to 0.10.5
  devel/lazygit/Portfile
Labels: maintainer, maintainer: open, type: update

#5760 nlohmann-json: Update to 3.7.2
  devel/nlohmann-json/Portfile
Labels: maintainer, maintainer: open, type: enhancement, type: update

#5777 lpcnetfreedv: update version to 0.1
  audio/lpcnetfreedv/Portfile
Labels: maintainer, maintainer: open, type: update

#5787 starship: update to 0.26.4
  sysutils/starship/Portfile
Labels: maintainer: open, type: update

#5799 lazygit: update to 0.10.6
  devel/lazygit/Portfile
Labels: maintainer, maintainer: open, type: update

#5798 terraform: update to 0.12.14
  sysutils/terraform/Portfile
Labels: maintainer, maintainer: open, type: update

#5802 gmic: require Xcode if SDKs not provided by CLT
  science/gmic/Portfile
Labels: by: member, maintainer: open, type: bugfix

#5805 qt5*-qtbase: fix ICU test
  aqua/qt53/Portfile
  aqua/qt53/files/patch-qtbase-icu_test.diff
  aqua/qt55/Portfile
  aqua/qt55/files/patch-qtbase-icu_test.diff
  aqua/qt56/Portfile
  aqua/qt56/files/patch-qtbase-icu_test.diff
  aqua/qt57/Portfile
  aqua/qt57/files/patch-qtbase-icu_test.diff
Labels: by: member, maintainer, maintainer: open, type: bugfix

#5761 nice: delete port
  lang/nice/Portfile
Labels: maintainer: none

#5809 terraform: update to 0.12.15
  sysutils/terraform/Portfile
Labels: maintainer, maintainer: open, type: update

#5810 welle.io: update to 20191113 (welle.io-devel subport)
  multimedia/welle.io/Portfile
Labels: maintainer: none, type: enhancement, type: update

#5804 mpich: update to 3.3.2; add clang90 flavors
  science/mpich/Portfile
  science/mpich/files/mpich-clang90
  science/mpich/files/mpich-clang90-fortran
  science/mpich/files/mpich-devel-clang90
  science/mpich/files/mpich-devel-clang90-fortran
Labels: by: member, maintainer, maintainer: open, type: update

#5770 py-pyaudio: fix example folder; add python 3.8; remove python 3.4
  python/py-pyaudio/Portfile
Labels: maintainer: open, type: bugfix

#5800 json-modern-cpp: replaced by nlohmann-json
  devel/json-modern-cpp/Portfile
  science/PothosAudio/Portfile
  science/PothosBlocks/Portfile
  science/PothosComms/Portfile
  science/PothosCore/Portfile
  science/PothosSoapy/Portfile
Labels: maintainer, maintainer: open

#5817 fzf: update to 0.19.0
  sysutils/fzf/Portfile
Labels: maintainer, maintainer: open, type: update

#5813 consul: update to 1.6.2
  net/consul/Portfile
Labels: maintainer, maintainer: open, type: update

#5812 vault: update to 1.3.0
  security/vault/Portfile
  security/vault/files/remove-replace-thrift-gomod.patch
Labels: maintainer, maintainer: open, type: update

#5734 VIBES: new port
  graphics/VIBES/Portfile
  graphics/VIBES/files/patch-vibes-packaging.diff
Labels: type: enhancement, type: submission

#5794 py-scikit-learn: force OpenMP-capable compiler
  python/py-scikit-learn/Portfile
Labels: maintainer: open, type: bugfix

#5796 kubectx: update to 0.7.1
  sysutils/kubectx/Portfile
Labels: maintainer, maintainer: open, type: update

#5792 commons-validator: delete port
  java/commons-validator/Portfile
Labels: maintainer: none

#5793 commons-dbcp: delete port
  java/commons-dbcp/Portfile
Labels: maintainer: none

#5704 ecCodes-2.14.1: Update to latest upstream version
  science/ecCodes/Portfile
  science/ecCodes/files/patch-no-jasper-deps.diff
Labels: maintainer: requires approval, maintainer: timeout, type: bugfix, type: enhancement, type: update

#5727 kerberos5: add support for libressl 2.9
  net/kerberos5/files/libressl.patch
Labels: maintainer: open, type: enhancement

#5737 cdo: update to 1.9.8
  science/cdo/Portfile
  science/cdo/files/patch-skip-nc4-test.diff
Labels: maintainer: open, type: enhancement, type: update

#5819 tor-devel: update to 0.4.2.4-rc
  security/tor-devel/Portfile
Labels: maintainer: none, type: update

#5811 openhantek: update version to 3.0.0
  science/openhantek/Portfile
Labels: maintainer, maintainer: open, type: update

#5816 Dovecot2 pandocfix
  mail/dovecot2/Portfile
Labels: maintainer: none, type: bugfix

#5820 net/bwping: update to 1.16
  net/bwping/Portfile
Labels: maintainer, maintainer: open, type: update

#5821 jakarta-oro: delete port
  java/jakarta-oro/Portfile
Labels: maintainer: none

#5824 proguard: update to 6.2.0
  java/proguard/Portfile
Labels: maintainer: none, type: update

#5643 macos-fortress: Submission of adaptive firewall and proxy chain
  net/macos-fortress/Portfile
  net/macos-fortress/files/blacklist.txt
  net/macos-fortress/files/blockips.conf
  net/macos-fortress/files/dshield_pubkey_file.txt
  net/macos-fortress/files/hosts.orig
  net/macos-fortress/files/hphosts_pubkey_file.txt
  net/macos-fortress/files/logrotate.d.macos-fortress
  net/macos-fortress/files/macosfortress_setup_check.sh
  net/macos-fortress/files/pf.conf
  net/macos-fortress/files/pf_attacks.sh
  net/macos-fortress/files/privoxy-config.patch
  net/macos-fortress/files/privoxy-match-all.action.patch
  net/macos-fortress/files/squid-squid.conf.patch
  net/macos-fortress/files/whitelist.txt
  perl/p5-data-validate-domain/Portfile
Labels: type: submission

#5801 py-pyopencl: Update to 2019.1.2 and add py37
  python/py-pyopencl/Portfile
Labels: maintainer: open, type: update

#5828 macos-fortress: Bugfix, rename hosts-orig file, add to notes
  net/macos-fortress/Portfile
  net/macos-fortress/files/hosts-orig
Labels: maintainer, maintainer: open, type: bugfix, type: enhancement

#5836 greycstoration: remove obsolete port
  graphics/greycstoration/Portfile
Labels: maintainer: requires approval

#5835 magic-exttools: remove obsolete port
  science/magic-exttools/Portfile
Labels: maintainer: none

#5833 commons-el: delete port
  java/commons-el/Portfile
Labels: maintainer: none

#5354 phantomjs: update version 2.0.0->2.1.1
  _resources/port1.0/group/qt5-1.0.tcl
  aqua/phantomjs-qt/Portfile
  aqua/phantomjs-qt/files/patch-add_sdk.diff
  aqua/phantomjs-qt/files/patch-cups.diff
  aqua/phantomjs-qt/files/patch-deployment_target.diff
  aqua/phantomjs-qt/files/patch-export_global.diff
  aqua/phantomjs-qt/files/patch-find_rez.diff
  aqua/phantomjs-qt/files/patch-fix_sdk.diff
  aqua/phantomjs-qt/files/patch-icu.diff
  aqua/phantomjs-qt/files/patch-machtest.diff
  aqua/phantomjs-qt/files/patch-midifix.diff
  aqua/phantomjs-qt/files/patch-mkspecs.diff
  aqua/phantomjs-qt/files/patch-no_qtwebkit.diff
  aqua/phantomjs-qt/files/patch-opengl.diff
  aqua/phantomjs-qt/files/patch-pcfiles.diff
  aqua/phantomjs-qt/files/patch-qtbase-icu_test.diff
  aqua/phantomjs-qt/files/patch-qtbase-intel_intrinsics.diff
  aqua/phantomjs-qt/files/patch-qtconn-for-10.12.diff
  aqua/phantomjs-qt/files/patch-qtconnectivity-sdk10_13.diff
  aqua/phantomjs-qt/files/patch-qtconnectivity-uuid.diff
  aqua/phantomjs-qt/files/patch-qtscript_ceil.diff
  aqua/phantomjs-qt/files/patch-qtwebengine32.diff
  aqua/phantomjs-qt/files/patch-qtwebengine_xcode10.diff
  aqua/phantomjs-qt/files/patch-qtwebkit_fix_icu.diff
  aqua/phantomjs-qt/files/patch-qualified_reference.diff
  aqua/phantomjs-qt/files/patch-rpath.diff
  aqua/phantomjs-qt/files/patch-sdk10_13.diff
  aqua/phantomjs-qt/files/patch-shared.diff
  aqua/phantomjs-qt/files/patch-ssl.diff
  aqua/phantomjs-qt/files/patch-stdloc.diff
  aqua/phantomjs-qt/files/patch-tst_benchlibcallgrind.diff
  aqua/phantomjs-qt/files/patch-tst_qpluginloader.diff
  aqua/phantomjs-qt/files/patch-upstream.diff
  aqua/phantomjs-qt/files/patch-xcrun.diff
  www/phantomjs/Portfile
  www/phantomjs/files/patch-printer_support.diff
  www/phantomjs/files/patch-qcocoaapplicationdelegate.mm.diff
  www/phantomjs/files/patch-src__tools__qlalr__lalr.cpp.diff
  www/phantomjs/files/patch-tools_preconfig.sh.diff
  www/phantomjs/files/xcrun.patch
Labels: by: member, maintainer: open, type: submission, type: update

#5837 apache-solr[34]: remove EOL ports
  java/apache-solr3/Portfile
  java/apache-solr3/files/patch-head.vm.diff
  java/apache-solr3/files/patch-solr-ja.diff
  java/apache-solr3/files/solr-ja.xml
  java/apache-solr3/files/solr.in
  java/apache-solr3/files/velocity.properties
  java/apache-solr4/Portfile
  java/apache-solr4/files/patch-solr-ja.diff
  java/apache-solr4/files/solr-ja.xml
  java/apache-solr4/files/solr.in
  java/apache-solr4/files/velocity.properties
Labels: maintainer: none

#5838 dbeaver-community: update to 6.2.5
  databases/dbeaver-community/Portfile
Labels: maintainer, maintainer: open, type: update

#5823 SourceKitten: Update to 0.27.0
  devel/SourceKitten/Portfile
Labels: maintainer: none, type: update

#5839 kotlin: update to 1.3.60
  lang/kotlin/Portfile
Labels: maintainer, maintainer: open, type: update

#5803 cool-retro-term: new port
  aqua/cool-retro-term/Portfile
Labels: by: member, type: submission

#5842 macos-fortress: Bugfix bump revision
  net/macos-fortress/Portfile
Labels: maintainer, maintainer: open, type: bugfix

#5841 maven2, maven32: ports abandoned
  java/maven2/Portfile
  java/maven32/Portfile
Labels: maintainer: open

#5844 terraform: update to 0.12.16
  sysutils/terraform/Portfile
Labels: maintainer, maintainer: open, type: update

#5843 eksctl: update to 0.10.1
  sysutils/eksctl/Portfile
Labels: maintainer, maintainer: open, type: update

#5832 psgml, xml-commons-resolver: ports abandoned
  editors/psgml/Portfile
  java/xml-commons-resolver/Portfile
Labels: maintainer: requires approval

#5826 commons-daemon: delete port
  java/commons-daemon/Portfile
  java/commons-daemon/files/patch-configure.diff
  java/commons-daemon/files/patch-native-dso-dyld.c
Labels: maintainer: none

#5846 google-cloud-sdk: update to 272.0.0
  devel/google-cloud-sdk/Portfile
Labels: maintainer, maintainer: open, type: update

#5853 unbound: update version to 1.9.5 and fix CVE-2019-18934
  net/unbound/Portfile
Labels: maintainer: open, type: security fix, type: update

#5850 py-sacremoses: Submission
  python/py-sacremoses/Portfile
Labels: type: submission

#5851 webkit2-gtk: fix quartz build
  www/webkit2-gtk/Portfile
  www/webkit2-gtk/files/patch-layertreehost-remove-invalidate.diff
Labels: by: member, maintainer

#5848 sentencepiece: Submission
  textproc/sentencepiece/Portfile
Labels: type: submission

#5858 lazygit: update to 0.11.2
  devel/lazygit/Portfile
Labels: maintainer, maintainer: open, type: update

#5857 LALSuite: use compiler.openmp_version for compiler
  science/lal/Portfile
  science/lalburst/Portfile
  science/lalframe/Portfile
  science/lalinference/Portfile
  science/lalinspiral/Portfile
  science/lalmetaio/Portfile
  science/lalpulsar/Portfile
  science/lalsimulation/Portfile
Labels: by: member, maintainer: requires approval, type: enhancement

#5849 py-sentencepiece: Submission
  python/py-sentencepiece/Portfile
Labels: type: submission

#5860 gnome-internet-radio-locator: Update to 2.1.3
  gnome/gnome-internet-radio-locator/Portfile
Labels: maintainer, maintainer: open, type: enhancement, type: update

#5861 lnav: update to 0.8.5
  sysutils/lnav/Portfile
Labels: maintainer: open, type: update

#5829 gimp2: fix stuttering when linking SDK > 10.13
  graphics/gimp2/Portfile
Labels: maintainer: requires approval, maintainer: timeout, type: bugfix

#5840 py-transformers: Submission of 🤗 Transformers
  python/py-transformers/Portfile
Labels: type: submission

#5863 py-clang: Bump supported versions and flavors
  python/py-clang/Portfile
Labels: by: member, maintainer, maintainer: open

#5806 Add py38 flavors to maintained ports.
  python/py-ctypeslib2/Portfile
  python/py-h5py/Portfile
  python/py-pptx/Portfile
  python/py-pydicom/Portfile
  python/py-pynetdicom/Portfile
  python/py-qimage2ndarray/Portfile
Labels: by: member, maintainer, maintainer: open
