Repository macports/macports-ports, pull requests merged in 2019-10, with the labels that each got.

#5397 GPXSee: update to 7.14
  gis/GPXSee/Portfile
Labels: maintainer, maintainer: open, type: enhancement, type: update

#5379 Update to py-fortranformat: Bump available python version number to 37
  python/py-fortranformat/Portfile
Labels: maintainer, maintainer: open, type: update

#5403 packer: update to 1.4.4
  sysutils/packer/Portfile
Labels: maintainer, maintainer: open, type: update

#5407 py-buildbot-macports-custom-views: update to 0.1.1
  python/py-buildbot-macports-custom-views/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#5399 qsynth: update do 0.5.7
  audio/qsynth/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#5409 gr-limesdr-devel: update commit to 20190917-ccceb5c4
  science/gr-limesdr/Portfile
Labels: maintainer, maintainer: open, type: update

#5377 Submission (new Portfile): eksctl @0.6.0 (sysutils)
  sysutils/eksctl/Portfile
Labels: type: submission

#5382 spatialite: add rttopo support
  databases/spatialite/Portfile
Labels: maintainer: none, type: enhancement

#5413 Minikube: update to 1.4.0
  sysutils/minikube/Portfile
Labels: maintainer: open, type: update

#5416 cmake: update to 3.15.4
  devel/cmake/Portfile
Labels: by: member, maintainer: requires approval, type: update

#5415 web-ext: update to 3.2.0
  devel/web-ext/Portfile
Labels: maintainer: none, type: update

#5411 Python38 devel
  lang/python38-devel/Portfile
Labels: maintainer: none, type: update

#5408 codec2: update commit to 20190928-f86e7e06
  audio/codec2/Portfile
Labels: maintainer, maintainer: open, type: update

#5410 msmtp: update version to 1.8.6
  mail/msmtp/Portfile
Labels: maintainer, maintainer: open, type: update

#5405 google-cloud-sdk: fix support for 32-bit OS
  devel/google-cloud-sdk/Portfile
Labels: maintainer, maintainer: open, type: bugfix

#5402 gmp: workaround bug in Xcode11
  devel/gmp/Portfile
Labels: by: member, maintainer: open, type: bugfix

#5414 Gildas: update to 201910b
  science/gildas/Portfile
  science/gildas/files/patch-admin-gildas-env.sh.diff
  science/gildas/files/patch-lapack.diff
Labels: maintainer, type: update

#5400 lang/fpc-cross: new port
  lang/fpc/Portfile
Labels: maintainer: none, type: enhancement

#5406 openconnect: update to version 8.05
  net/openconnect/Portfile
Labels: maintainer: none, type: bugfix, type: enhancement, type: update

#5423 gmp: allow binary distribution
  devel/gmp/Portfile
Labels: by: member, maintainer: open

#5420 apache-solr8: Update java dependecies and fallbacks
  java/apache-solr8/Portfile
Labels: maintainer, maintainer: open, type: update

#5421 mallet: Update java fallback
  math/mallet/Portfile
Labels: maintainer: none, type: update

#5165 doctl: update to 1.29.2
  www/doctl/Portfile
Labels: maintainer: open, type: bugfix, type: enhancement, type: update

#5007 apparix: update to 11-062
  sysutils/apparix/Portfile
Labels: by: member, maintainer: requires approval, type: update

#5425 golangci-lint: update to 1.18.0
  devel/golangci-lint/Portfile
Labels: maintainer, maintainer: open

#5427 prometheus: update to 2.13.0
  net/prometheus/Portfile
Labels: maintainer, maintainer: open, type: update

#5428 google-cloud-sdk: update to 265.0.0
  devel/google-cloud-sdk/Portfile
Labels: maintainer, maintainer: open, type: update

#5429 screen: update to 4.7.0
  sysutils/screen/Portfile
  sysutils/screen/files/patch-blanker-fix.diff
  sysutils/screen/files/patch-panic-fix.diff
Labels: maintainer, maintainer: open, type: enhancement, type: update

#5263 redland-bindings: update to 1.0.17.1, add python3 variants
  www/redland-bindings/Portfile
Labels: maintainer: none, type: update

#5433 FAudio: update to 19.10
  audio/FAudio/Portfile
  audio/FAudio/files/patch-faudio-remove-deployment-target.diff
Labels: by: member, maintainer: none, type: bugfix, type: enhancement, type: update

#5422 elasticsearch: Update to 7.4.0 and java version dependencies
  databases/elasticsearch/Portfile
  databases/elasticsearch/files/patch-elasticsearch-env.diff
Labels: maintainer: open, type: update

#5432 py-tz: update to 2019.2
  python/py-tz/Portfile
Labels: by: member, maintainer: open, type: update

#5362 llvm/clang/lldb-9.0: new port
  lang/llvm-9.0/Portfile
  lang/llvm-9.0/files/0001-Set-the-Mach-O-CPU-Subtype-to-ppc7400-when-targeting.patch
  lang/llvm-9.0/files/0002-Define-EXC_MASK_CRASH-and-MACH_EXCEPTION_CODES-if-th.patch
  lang/llvm-9.0/files/0003-MacPorts-Only-Don-t-embed-the-deployment-target-in-t.patch
  lang/llvm-9.0/files/0004-Fix-build-issues-pre-Lion-due-to-missing-a-strnlen-d.patch
  lang/llvm-9.0/files/0005-Threading-Only-call-pthread_setname_np-on-SnowLeopar.patch
  lang/llvm-9.0/files/0006-Only-call-setpriority-PRIO_DARWIN_THREAD-0-PRIO_DARW.patch
  lang/llvm-9.0/files/1001-MacPorts-Only-Prepare-clang-format-for-replacement-w.patch
  lang/llvm-9.0/files/1002-MacPorts-Only-Fix-name-of-scan-view-executable-insid.patch
  lang/llvm-9.0/files/1003-Default-to-ppc7400-for-OSX-10.5.patch
  lang/llvm-9.0/files/1004-Default-to-fragile-ObjC-runtime-when-targeting-darwi.patch
  lang/llvm-9.0/files/1005-Fixup-libstdc-header-search-paths-for-older-versions.patch
  lang/llvm-9.0/files/1006-Fix-build-issues-pre-Lion-due-to-missing-a-strnlen-d.patch
  lang/llvm-9.0/files/1007-Fix-float.h-to-work-on-Snow-Leopard-and-earlier.patch
  lang/llvm-9.0/files/2001-xray-Define-O_CLOEXEC-for-older-SDKs-that-don-t-have.patch
  lang/llvm-9.0/files/2002-Work-around-no-libdispatch-on-10.6.patch
  lang/llvm-9.0/files/3001-Fix-missing-long-long-math-prototypes-when-using-the.patch
  lang/llvm-9.0/files/3002-implement-atomic-using-mutex-lock_guard-for-64b-ops-.patch
  lang/llvm-9.0/files/5000-patch-lib-support-unix-path-copyfileclone-on-older-systems.diff
  lang/llvm-9.0/files/5001-patch-machoreader-strnlen.diff
  lang/llvm-9.0/files/5002-patch-objdumper-strnlen.diff
  lang/llvm-9.0/files/5003-patch-no-directory-watcher-on-snowleopard.diff
  lang/llvm-9.0/files/9000-patch-clang-7.0-support-emulated-tls.diff
  lang/llvm-9.0/files/9000-patch-llvm-7.0-support-emulated-tls.diff
  lang/llvm-9.0/files/9001-macports-libstdcxx.diff
  lang/llvm-9.0/files/9003-patch-clang-7.0-default-to-libcxx-on-all-systems.diff
  lang/llvm-9.0/files/leopard-no-asan.patch
  lang/llvm-9.0/files/leopard-no-blocks.patch
  lang/llvm-9.0/files/llvm-bin
  lang/llvm-9.0/files/llvm-bin-compat
  lang/llvm-9.0/files/mp-clang-9.0
  lang/llvm-9.0/files/mp-llvm-9.0
  lang/llvm-9.0/files/openmp-locations.patch
Labels: by: member, type: submission

#5445 redis: update to 5.0.6
  databases/redis/Portfile
Labels: maintainer: none, type: enhancement, type: update

#5431 inspectrum: add application bundle and cleanup
  science/inspectrum/Portfile
  science/inspectrum/files/inspectrum.icns
Labels: maintainer: open, type: enhancement

#5452 gnome-internet-radio-locator: Update to 2.0.8
  gnome/gnome-internet-radio-locator/Portfile
Labels: maintainer, maintainer: open, type: enhancement, type: update

#5454 clamav: support systems < 10.7
  sysutils/clamav/Portfile
Labels: by: member, maintainer: requires approval, type: enhancement

#5434 blosc: use MacPorts snappy
  archivers/blosc/Portfile
Labels: by: member, maintainer: open, type: enhancement

#5441 py-yappi: update to version 0.98, add py37 / remove py3[45] subports
  python/py-yappi/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#5456 irrlicht: use upstream patches
  devel/irrlicht/Portfile
  devel/irrlicht/files/patch-irrlicht-cirrdevice.diff
Labels: by: member, maintainer: none, type: enhancement

#5455 iTerm2: update to 3.3.5
  aqua/iTerm2/Portfile
Labels: by: member, maintainer: open, type: update

#5447 tor-devel: update to 0.4.2.2-alpha
  security/tor-devel/Portfile
Labels: maintainer: none, type: update

#5440 py-pyinstaller: update to version 3.5, add py37 / remove py3[45] subports
  python/py-pyinstaller/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#5389 qt5*: update version 5.12.4->5.12.5
  aqua/qt5/Portfile
Labels: maintainer: open, type: update

#5450 mole: new port
  net/mole/Portfile
Labels: type: submission

#5430 gnudatalanguage: Fix build on 10.8 and earlier
  math/gnudatalanguage/Portfile
  math/gnudatalanguage/files/sincos.patch
Labels: by: member, maintainer: requires approval, maintainer: timeout

#5464 nomad: update to 0.9.6
  net/nomad/Portfile
Labels: maintainer, maintainer: open, type: update

#5470 vislcg3: update to version 1.3.0
  textproc/vislcg3/Portfile
Labels: maintainer, type: update

#5468 wiggle: update to 1.1
  devel/wiggle/Portfile
Labels: maintainer: none, type: update

#5469 carthage: Mark as requiring Xcode
  devel/carthage/Portfile
Labels: maintainer, maintainer: open

#5444 torsocks: update to 2.3.0
  net/torsocks/Portfile
  net/torsocks/files/0001-Fix-macros-for-accept4-2.patch
Labels: maintainer: requires approval, maintainer: timeout, type: enhancement, type: update

#5451 swi-prolog-devel: update to 8.1.15
  lang/swi-prolog-devel/Portfile
Labels: maintainer, type: update

#5449 terraform: update to 0.12.10
  sysutils/terraform/Portfile
Labels: maintainer, maintainer: open, type: update

#5438 GPXSee: update to 7.15
  gis/GPXSee/Portfile
Labels: maintainer, maintainer: open, type: enhancement, type: update

#5443 openhantek: update version to 2.15
  science/openhantek/Portfile
Labels: maintainer, maintainer: open, type: update

#5437 QtPBFImagePlugin: update to 2.0
  graphics/QtPBFImagePlugin/Portfile
Labels: maintainer, maintainer: open, type: enhancement, type: update

#5418 clang_select: Add some more entries
  lang/llvm-8.0/files/mp-clang-8.0
  lang/llvm-9.0/files/mp-clang-9.0
  sysutils/clang_select/Portfile
  sysutils/clang_select/files/base
Labels: maintainer: requires approval, maintainer: timeout, type: enhancement

#5137 jikespg: delete port
  lang/jikespg/Portfile
Labels: maintainer: none

#5471 emulators/qemu: trivial update to 4.1.0
  emulators/qemu/Portfile
Labels: by: member, maintainer: open

#5478 spring-boot-cli: update to 2.1.9
  java/spring-boot-cli/Portfile
Labels: maintainer, maintainer: open, type: update

#5459 rebar3: update to 3.12
  erlang/rebar3/Portfile
Labels: maintainer: requires approval, maintainer: timeout, type: update

#5435 unbound: update to 1.9.4
  net/unbound/Portfile
Labels: maintainer: open, type: security fix, type: update

#5458 update erlang to 22.1
  lang/erlang/Portfile
Labels: maintainer: requires approval, maintainer: timeout, type: update

#5479 wtfutil: update to 0.23.0
  sysutils/wtfutil/Portfile
Labels: maintainer, maintainer: open, type: update

#5462 jtc: new port
  textproc/jtc/Portfile
  textproc/jtc/files/patch-json-hpp.diff
  textproc/jtc/files/patch-jtc-cpp.diff
  textproc/jtc/files/patch-streamstr-hpp.diff
Labels: type: submission

#5466 rust: switch to llvm-9.0 from llvm-7.0.
  lang/rust/Portfile
Labels: by: member, maintainer: open, type: enhancement

#5483 VLC2: mark use xcode
  multimedia/VLC2/Portfile
Labels: by: member, maintainer: open

#5484 jtc: update patch to fix indentation
  textproc/jtc/files/patch-jtc-cpp.diff
Labels: maintainer, maintainer: open, type: update

#5486 libfdk-aac: update to 2.0.1
  audio/libfdk-aac/Portfile
Labels: maintainer, maintainer: open, type: update

#5493 Remove existence checks for use_xcode
  _resources/port1.0/group/qmake5-1.0.tcl
  aqua/iTerm2/Portfile
  devel/SourceKitten/Portfile
  devel/bazel/Portfile
  devel/carthage/Portfile
  editors/textmate2/Portfile
  multimedia/VLC/Portfile
  multimedia/VLC2/Portfile
  net/gpsd/Portfile
Labels: by: member, maintainer: open, type: enhancement

#5485 p5-musicbrainz-discid: update to version 0.06
  perl/p5-musicbrainz-discid/Portfile
Labels: by: member, maintainer: open, type: update

#5491 gr-iridium: new port
  science/gr-iridium/Portfile
Labels: type: submission

#5494 go-ethereum: update to 1.9.6
  finance/go-ethereum/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#5496 cmake: remove cyclic dependency on clang-9.0
  devel/cmake/Portfile
Labels: maintainer: requires approval, type: bugfix

#5473 octave-1.0 PG: fix cannot rename folder issue.
  _resources/port1.0/group/octave-1.0.tcl
Labels: by: member, type: bugfix

#5474 qt5-{qtbase,qtscript}: remove unneeded dependencies
  aqua/qt5/Portfile
  aqua/qt511/Portfile
  aqua/qt53/Portfile
  aqua/qt55/Portfile
  aqua/qt56/Portfile
  aqua/qt57/Portfile
  aqua/qt58/Portfile
  aqua/qt59/Portfile
Labels: by: member, maintainer: open, type: enhancement

#5495 google-cloud-sdk: update to 266.0.0, added long description
  devel/google-cloud-sdk/Portfile
Labels: maintainer, maintainer: open, type: update

#5424 ghc: Remove unecessary compiler options
  lang/ghc/Portfile
Labels: maintainer, maintainer: open, type: bugfix

#5487 lilypond-devel: add gcc9 as fallback
  textproc/lilypond-devel/Portfile
Labels: maintainer: open

#5480 py-tensor*: minimize diffs between py-tensor* and py-tensor*1.
  python/py-tensorboard/Portfile
  python/py-tensorflow/Portfile
  python/py-tensorflow_estimator/Portfile
Labels: by: member, maintainer: open

#5502 gnome-internet-radio-locator: Update to 2.0.9
  gnome/gnome-internet-radio-locator/Portfile
Labels: maintainer, maintainer: open, type: enhancement, type: update

#5472 luajit: fix segfault when building with Xcode 11
  lang/luajit/Portfile
Labels: by: member, maintainer: open, type: bugfix

#5499 cmake: Use clang_dependency PG
  devel/cmake/Portfile
Labels: by: member, maintainer: requires approval

#5511 _ci: improve portindex script
  _ci/bootstrap.sh
Labels: by: member

#5508 wireguard-tools: update to 0.0.20191012
  net/wireguard-tools/Portfile
Labels: maintainer, maintainer: open, type: update

#5507 wireguard-go: update to 0.0.20191012
  net/wireguard-go/Portfile
Labels: maintainer, maintainer: open, type: update

#5448 zabbix4[2]*: Update to 4.0.13 and 4.2.7
  net/zabbix4/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#5514 sudo: update version to 1.8.28 - fix CVE-2019-14287
  sysutils/sudo/Portfile
Labels: maintainer: requires approval, type: security fix, type: update

#4848 gtk3: update to version 3.24.10
  gnome/gtk3/Portfile
  gnome/gtk3/files/patch-quartz-hardcode-screen-resolution.patch
Labels: maintainer: open, type: bugfix, type: enhancement, type: update

#5506 iTerm2: Fix the version checking logic
  aqua/iTerm2/Portfile
Labels: by: member, maintainer, maintainer: open

#5481 nginx: add fancyindex module & variant, enabled by default
  www/nginx/Portfile
Labels: by: member, maintainer: open, type: enhancement

#5516 jtc: ensure compiler meets C++ 2014 standard
  textproc/jtc/Portfile
Labels: maintainer, maintainer: open

#5519 gr-iridium: add cppunit as build depends
  science/gr-iridium/Portfile
Labels: maintainer, maintainer: open

#5521 limesuite-devel: update version to e1c54ee2
  science/limesuite/Portfile
Labels: maintainer, maintainer: open, type: update

#5522 codec2: update version to 34292702
  audio/codec2/Portfile
Labels: maintainer, maintainer: open, type: update

#5523 cm256cc: update commit to f21e8bc1
  science/cm256cc/Portfile
Labels: maintainer, maintainer: open, type: enhancement, type: update

#5524 dsdcc: update version to 1.8.6
  audio/dsdcc/Portfile
Labels: maintainer, maintainer: open, type: update

#5525 lpcnetfreedv: update version to 1443da92
  audio/lpcnetfreedv/Portfile
Labels: maintainer, maintainer: open, type: update

#5526 freedv-gui: update version to 05c03348
  science/freedv-gui/Portfile
Labels: maintainer, maintainer: open, type: update

#5500 gr-limesdr: move to the new examples folder
  science/gr-limesdr/Portfile
Labels: maintainer, maintainer: open, type: enhancement

#5517 pgbadger: update to 11.1
  databases/pgbadger/Portfile
Labels: maintainer: none, type: enhancement, type: update

#5489 py-construct: update version to 2.9.45
  python/py-construct/Portfile
Labels: maintainer: open, type: update

#5513 qbs: Update to 1.14.0
  devel/qbs/Portfile
Labels: maintainer, maintainer: open, type: update

#5528 logtalk: update to 3.31.0
  lang/logtalk/Portfile
Labels: maintainer, type: update

#5527 python38: update python38-devel to python38
  lang/python38/Portfile
  lang/python38/files/patch-Lib-cgi.py.diff
  lang/python38/files/patch-Lib-ctypes-macholib-dyld.py.diff
  lang/python38/files/patch-configure-xcode4bug.diff
  lang/python38/files/patch-configure.diff
  lang/python38/files/patch-libedit.diff
  lang/python38/files/patch-setup.py.diff
  lang/python38/files/pyconfig.ed
  lang/python38/files/pyconfig.h-universal.ed
  lang/python38/files/python-python38
  lang/python38/files/python3-python38
Labels: maintainer: none, type: update

#5512 starship: update to 0.24.0
  sysutils/starship/Portfile
Labels: maintainer: open, type: update

#5533 gpredict: add application bundle
  science/gpredict/Portfile
Labels: maintainer: open, type: enhancement

#5534 libfec: update version to 9de5ef59
  science/libfec/Portfile
  science/libfec/files/patch-makefile.in.diff
Labels: maintainer, maintainer: open, type: enhancement, type: update

#5538 libvpx: obey MacPorts configure.sdkroot
  multimedia/libvpx/files/patch-build-make-configure.sh.diff
Labels: maintainer: open, type: enhancement

#5540 gtk3: disable cups on <= 10.7
  gnome/gtk3/Portfile
Labels: by: member, maintainer: open, type: bugfix

#5531 micronaut: update to 1.2.4
  java/micronaut/Portfile
Labels: maintainer, maintainer: open, type: update

#5541 openhantek: update version to 2.16
  science/openhantek/Portfile
Labels: maintainer, maintainer: open, type: update

#5542 graalvm: update to 19.2.1
  java/graalvm/Portfile
Labels: maintainer, maintainer: open, type: update

#5505 Welle.io port (new addition)
  multimedia/welle.io/Portfile
  multimedia/welle.io/files/CMakeLists.txt.patch
Labels: type: submission

#5535 google-cloud-sdk: update to 267.0.0
  devel/google-cloud-sdk/Portfile
Labels: maintainer, maintainer: open, type: update

#5530 zim: update version to 0.72.0
  editors/zim/Portfile
  editors/zim/files/zim
  editors/zim/files/zim-app
Labels: maintainer: none, type: update

#5536 py-cvxopt: update to version 1.2.3
  python/py-cvxopt/Portfile
  python/py-cvxopt/files/patch-setup.py.diff
Labels: maintainer, maintainer: open, type: bugfix, type: enhancement, type: update

#5504 upt: enable system wide man page
  sysutils/upt/Portfile
Labels: maintainer: open, type: enhancement

#5543 starship: update to 0.25.0
  sysutils/starship/Portfile
Labels: maintainer: open, type: update

#5548 py-pyqt5: Add python2 qstring patch to address seg. faults
  python/py-pyqt5/Portfile
  python/py-pyqt5/files/python2_qstring.diff
Labels: by: member, maintainer: open

#5545 gpilab: Update to latest versions.
  python/gpilab_select/Portfile
  python/gpilab_select/files/base
  python/gpilab_select/files/none
  python/py-gpilab-core/Portfile
  python/py-gpilab-core/files/Matplotlib_GPI.py.patch
  python/py-gpilab-examples/Portfile
  python/py-gpilab-framework/Portfile
  python/py-gpilab-framework/files/canvasGraph.py.diff
  python/py-gpilab-framework/files/gpilab-35
  python/py-gpilab-framework/files/gpilab-36
  python/py-gpilab-framework/files/gpilab-37
  python/py-gpilab-framework/files/mainWindow.py.diff
Labels: by: member, maintainer, maintainer: open, type: update

#5537 python38: update rev 1: patches, add +devel
  lang/python38-devel/Portfile
Labels: maintainer: none, type: submission, type: update

#5552 py-poppler-qt5: restore workaround to find qmake
  python/py-poppler-qt5/Portfile
  python/py-poppler-qt5/files/patch-fix-qt-dirs.diff
Labels: maintainer, maintainer: open, type: bugfix

#5550 py-prompt_toolkit: update to 1.0.18
  python/py-prompt_toolkit/Portfile
Labels: by: member, maintainer: open, type: update

#5557 openjdk8: update OpenJ9 subports to 8u232
  java/openjdk8/Portfile
Labels: maintainer, maintainer: open, type: update

#5554 terraform: update to 0.12.12
  sysutils/terraform/Portfile
Labels: maintainer, maintainer: open, type: update

#5551 prometheus: update to 2.13.1
  net/prometheus/Portfile
Labels: maintainer, maintainer: open, type: update

#5558 libomp: Don't block Universal, let base handle it
  lang/libomp/Portfile
Labels: maintainer: open, type: enhancement

#5546 angle-grinder: update to 0.12.0
  sysutils/angle-grinder/Portfile
  sysutils/angle-grinder/files/patch-lock-logfmt.diff
  sysutils/angle-grinder/files/patch-toml-logfmt.diff
Labels: maintainer, maintainer: open, type: update

#5559 openjdk8: update openjdk11-openj9* subports to 11.0.5
  java/openjdk8/Portfile
Labels: maintainer, maintainer: open, type: update

#5562 buildbot: update to 2.5.0
  devel/buildbot-2/Portfile
  devel/buildbot-worker/Portfile
  python/py-buildbot-console-view/Portfile
  python/py-buildbot-grid-view/Portfile
  python/py-buildbot-pkg/Portfile
  python/py-buildbot-waterfall-view/Portfile
  python/py-buildbot-www/Portfile
  python/py-buildbot/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#5561 dbeaver-community: update to 6.2.2
  databases/dbeaver-community/Portfile
Labels: maintainer, maintainer: open, type: update

#5556 py-astor: Update to 0.8.0 and add patch for setuptools fix
  python/py-astor/Portfile
  python/py-astor/files/setuptools-fix.patch
Labels: by: member, maintainer: open, type: update

#5560 nodejs12: Use system ICU
  devel/nodejs12/Portfile
Labels: by: member, maintainer: open, type: enhancement

#5566 limesuite-devel: update version to 627c82c7
  science/limesuite/Portfile
Labels: maintainer, maintainer: open, type: update

#5579 unrar: update version to 5.8.3
  archivers/unrar/Portfile
Labels: maintainer: none, type: update

#5576 orc: update version to 0.4.30
  devel/orc/Portfile
Labels: maintainer: none, type: update

#5571 gdb: update version to 8.3.1
  devel/gdb/Portfile
Labels: maintainer: none, type: update

#5567 dos2unix: update version to 7.4.1
  textproc/dos2unix/Portfile
Labels: maintainer: none, type: update

#5583 git-lfs: update to 2.9.0
  devel/git-lfs/Portfile
Labels: by: member, maintainer: open, type: update

#5570 binwalk: update version to 2.2.0
  cross/binwalk/Portfile
Labels: maintainer: open, type: update

#5503 get_iplayer: update to version 3.22
  net/get_iplayer/Portfile
Labels: by: member, maintainer: open, type: update

#5575 lua: update version to 5.3.5
  lang/lua/Portfile
  lang/lua/files/patch-src-Makefile.diff
Labels: maintainer: none, type: update

#5587 spring-boot-cli: update to 2.2.0
  java/spring-boot-cli/Portfile
Labels: maintainer, maintainer: open, type: update

#5588 micronaut: update to 1.2.5
  java/micronaut/Portfile
Labels: maintainer, maintainer: open, type: update

#5572 freedv-gui: update version to 5272add1
  science/freedv-gui/Portfile
Labels: maintainer, maintainer: open, type: update

#5578 rclone: update version to 1.49.5
  net/rclone/Portfile
Labels: maintainer: open, type: update

#5518 webkit2-gtk: bump to 2.26.1
  www/webkit2-gtk/Portfile
  www/webkit2-gtk/files/WebKit-icu-65.1-fix.patch
  www/webkit2-gtk/files/patch-WTF-wtf-Randomdevice.diff
  www/webkit2-gtk/files/patch-WTF-wtf-spi-darwin-ProcessMemoryFootprint-h.diff
  www/webkit2-gtk/files/patch-Webcore-page-crypto.diff
  www/webkit2-gtk/files/patch-ramsize.diff
  www/webkit2-gtk/files/patch-snowleopard-cmakelists-stdcformatmacros.diff
  www/webkit2-gtk/files/patch-snowleopard-npruntime-redefine-cursor.diff
  www/webkit2-gtk/files/patch-source-wtf-wtf-osallocatorposix-cpp-map-jit.diff
  www/webkit2-gtk/files/patch-source-wtf-wtf-unix-cputimeunix-cpp-darwin-version-restore.diff
  www/webkit2-gtk/files/patch-webkit2gtk-macports.diff
  www/webkit2-gtk/files/unused/PR-152650-2.patch
  www/webkit2-gtk/files/unused/PR-153138.patch
  www/webkit2-gtk/files/unused/PR-157574.patch
  www/webkit2-gtk/files/unused/patch-name-conflicts.diff
  www/webkit2-gtk/files/unused/patch_bad_optional_access.diff
Labels: by: member, maintainer: requires approval, type: enhancement, wip

#5585 py-django: update to 2.2.6 and 1.11.25
  python/py-django/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#5581 zsh-completions: update version to 0.31.0
  sysutils/zsh-completions/Portfile
Labels: maintainer: open, type: update
