Repository macports/macports-ports, pull requests merged in 2019-03, with the labels that each got.

#3715 netpbm: disable parallel build on Tiger
  graphics/netpbm/Portfile
Labels: by: member, maintainer: open, type: bugfix

#3749 sahana2: remove outdated port
  www/sahana2/Portfile
Labels: by: member, maintainer: none

#3748 php5-shindig: remove unmaintained/attic port
  php/php5-shindig/Portfile
Labels: by: member, maintainer: open

#3764 py-pbr: update to 5.1.3
  python/py-pbr/Portfile
Labels: maintainer, maintainer: open, type: update

#3765 py-isort: update to 4.3.9
  python/py-isort/Portfile
Labels: maintainer, maintainer: open, type: update

#3763 Gildas: update to 201903a
  science/gildas/Portfile
Labels: maintainer, type: update

#3680 tomcat-native: update to version 1.2.21
  java/tomcat-native/Portfile
Labels: maintainer, maintainer: open, type: update

#3770 vpcs 0.8c new port
  emulators/vpcs/Portfile
  emulators/vpcs/files/patch-arch-ppc-fix.diff
  emulators/vpcs/files/patch-makefiles-osx.diff
  emulators/vpcs/files/patch-nonlinux-test-fix.diff
Labels: maintainer, maintainer: open, type: submission

#3771 openssl: update to 1.0.2r and bump dependent ports
  devel/openssl/Portfile
  net/openssh/Portfile
  sysutils/freeradius/Portfile
Labels: by: member, maintainer: open, type: security fix, type: update

#3773 gnuradio: add python37 variant
  science/gnuradio/Portfile
Labels: maintainer: requires approval, type: enhancement

#3772 py-numpy: fix build with +gfortran +openblas
  python/py-numpy/Portfile
  python/py-numpy/files/patch-numpy_linalg_setup.py.diff
Labels: by: member, maintainer: open

#3775 fish: move to cmake build
  shells/fish/Portfile
  shells/fish/files/patch-remove-unguarded-availability.diff
  shells/fish/files/patch-tests-bash-check.diff
Labels: by: member, maintainer: none, type: bugfix, type: enhancement

#3776 gegl-0.4: support legacy systems
  graphics/gegl-0.4/Portfile
  graphics/gegl-devel/Portfile
Labels: by: member, maintainer: open, type: bugfix

#3781 bfg: new port
  java/bfg/Portfile
  java/bfg/files/bfg
Labels: type: submission

#3786 py-hggit: update to 8d00fde for compatibility with mercurial 4.9
  python/py-hggit/Portfile
Labels: by: member, maintainer: open, type: bugfix, type: enhancement, type: update

#3778 py-isort: update to 4.3.10
  python/py-isort/Portfile
Labels: maintainer, maintainer: open, type: update

#3782 python38-devel: update to 3.8.0a2
  lang/python38-devel/Portfile
Labels: maintainer: open, type: update

#3788 p5-test-perltidy: update to version 20190305, dependencies
  perl/p5-test-perltidy/Portfile
Labels: by: member, maintainer: open, type: bugfix, type: update

#3790 ranger: update to 1.9.2
  sysutils/ranger/Portfile
Labels: maintainer: open, type: update

#3685 gr-limesdr: new port
  science/gr-limesdr/Portfile
Labels: type: submission

#3758 dmtx-utils: new port, version 0.7.6
  graphics/dmtx-utils/Portfile
Labels: type: enhancement, type: submission

#3784 py-pytest: update to 4.3.0
  python/py-pytest/Portfile
Labels: maintainer: open, type: update

#3787 py-astroid: update to 2.2.3
  python/py-astroid/Portfile
Labels: maintainer: open, type: update

#3793 mosquitto: Update to version 1.5.8.
  net/mosquitto/Portfile
Labels: maintainer, maintainer: open, type: update

#3794 vifm: update to 0.10
  sysutils/vifm/Portfile
Labels: maintainer: none, type: update

#3756 openconnect: update to version 8.02
  net/openconnect/Portfile
Labels: maintainer: none, type: bugfix, type: enhancement, type: update

#3795 py-isort: update to 4.3.12
  python/py-isort/Portfile
Labels: maintainer, maintainer: open, type: update

#3777 xfractint: new port (version 20.04p14)
  graphics/xfractint/Portfile
  graphics/xfractint/files/patch-prefix-x11-dirs.diff
Labels: type: enhancement, type: submission

#3802 py-notebook: update to 5.7.5
  python/py-notebook/Portfile
Labels: maintainer: open, type: update

#3783 openssl11: new port, version 1.1.1b
  devel/openssl11/Portfile
Labels: by: member, type: submission

#3796 py-markupsafe: update to 1.1.1
  python/py-markupsafe/Portfile
Labels: maintainer: none, type: update

#3803 dart-sdk: update to 2.2.0
  lang/dart-sdk/Portfile
Labels: maintainer: none, type: enhancement, type: update

#3805 xar: patch deprecated openssl function
  archivers/xar/Portfile
  archivers/xar/files/patch-configure.ac
Labels: by: member, maintainer: open, type: enhancement

#3808 p5-tk: adopt
  perl/p5-tk/Portfile
Labels: maintainer: none

#3811 py-nmrglue: set to nomaintainer (port abandoned)
  python/py-nmrglue/Portfile
Labels: maintainer: open, type: enhancement

#3812 XviD: new livecheck URL
  multimedia/XviD/Portfile
Labels: maintainer: none, type: bugfix

#3814 paraview: requires qt5-qtxmlpatterns
  science/paraview/Portfile
Labels: by: member, maintainer: open, type: bugfix

#3817 fzf: new port
  sysutils/fzf/Portfile
Labels: type: submission

#3815 OpenBLAS: add PowerPC support
  math/OpenBLAS/Portfile
  math/OpenBLAS/files/patch-darwin-powerpc.diff
  math/OpenBLAS/files/patch-openblas-powermac970-fix.diff
Labels: by: member, maintainer: open

#3804 xchm: switch to github, update
  textproc/xchm/Portfile
Labels: by: member, maintainer, maintainer: open

#3797 py-olefile: update to 0.46
  python/py-olefile/Portfile
Labels: maintainer: none, type: update

#3785 py-pluggy: update to 0.9.0
  python/py-pluggy/Portfile
Labels: maintainer: open, type: update

#3806 xfractint: fix to build against MacPorts Xorg, not XQuartz
  graphics/xfractint/Portfile
  graphics/xfractint/files/patch-prefix-x11-dirs.diff
Labels: maintainer, maintainer: open, type: bugfix

#3807 py-qtawesome: update to 0.5.7
  python/py-qtawesome/Portfile
Labels: maintainer, maintainer: open, type: update

#3824 py-language-server: update to 0.25.0
  python/py-language-server/Portfile
Labels: maintainer, maintainer: open, type: update

#3823 py-isort: update to 4.3.13
  python/py-isort/Portfile
Labels: maintainer, maintainer: open, type: update

#3813 mariadb-10.1: Update to v10.1.38
  databases/mariadb-10.1/Portfile
Labels: maintainer: none, type: security fix, type: update

#3768 tcpreplay: update to 4.3.1, update URLs
  net/tcpreplay/Portfile
Labels: by: member, maintainer: open, type: enhancement, type: update

#3789 swi-prolog-devel: update to version 8.1.2
  lang/swi-prolog-devel/Portfile
Labels: maintainer, type: update

#3792 swi-prolog: update to version 8.0.2
  lang/swi-prolog/Portfile
Labels: maintainer, type: update

#3830 google-cloud-sdk: Update to 237.0.0
  devel/google-cloud-sdk/Portfile
Labels: maintainer, maintainer: open, type: update

#3829 spring-boot-cli: Update to 2.1.3.RELEASE
  java/spring-boot-cli/Portfile
Labels: maintainer, maintainer: open, type: update

#3801 fd: Update to 7.3.0
  sysutils/fd/Portfile
Labels: maintainer: open, type: update

#3832 py-aiorpcX: update to 0.10.5
  python/py-aiorpcX/Portfile
Labels: maintainer: open, type: enhancement, type: update

#3837 consul: update to 1.4.3
  net/consul/Portfile
Labels: maintainer, maintainer: open, type: update

#3838 GPXSee: update to 7.4
  gis/GPXSee/Portfile
Labels: maintainer, maintainer: open, type: enhancement, type: update

#3800 simple-web-server: new port 3.0.0-rc3
  devel/simple-web-server/Portfile
Labels: type: enhancement, type: submission

#3799 simple-websocket-server: new port version 2.0.0-rc4
  devel/simple-websocket-server/Portfile
Labels: type: enhancement, type: submission

#3744 diskus: new port
  sysutils/diskus/Portfile
Labels: type: enhancement, type: submission

#3840 packer: update to 1.3.5
  sysutils/packer/Portfile
Labels: maintainer, maintainer: open, type: update

#3816 fzy: Update to 1.0
  devel/fzy/Portfile
Labels: maintainer: open, type: update

#3819 adtpro: fix license
  emulators/adtpro/Portfile
Labels: maintainer: requires approval, maintainer: timeout

#3833 py-spyder-devel: update to 0615f01 (20190309)
  python/py-spyder-devel/Portfile
  python/py-spyder-devel/files/patch-spyder_app_mainwindow.py.diff
  python/py-spyder-devel/files/patch-spyder_config_main.py.diff
  python/py-spyder-devel/files/patch-spyder_plugins_editor_lsp_client.py.diff
  python/py-spyder-devel/files/patch-spyder_plugins_editor_lsp_transport_main.py.diff
  python/py-spyder-devel/files/patch-spyder_plugins_editor_lsp_transport_producer.py.diff
Labels: maintainer, maintainer: open, type: update

#3826 wxWidgets-3.0: add upstream patch for strings
  graphics/wxWidgets-3.0/Portfile
  graphics/wxWidgets-3.0/files/patch-upstream-strvararg.diff
Labels: by: member, maintainer, type: bugfix

#3843 coreutils: fix build on older OSX (e.g., 10.5 PPC)
  sysutils/coreutils/Portfile
  sysutils/coreutils/files/patch-fix-strtod.c.diff
Labels: by: member, maintainer: open, type: bugfix

#3809 py-virtualenv: update to 16.4.3
  python/py-virtualenv/Portfile
Labels: maintainer: open, type: update

#3810 py-py: update to 1.8.0
  python/py-py/Portfile
Labels: maintainer: open, type: update

#3849 minio[-mc]: Update to latest.
  www/minio-mc/Portfile
  www/minio/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#3842 Gildas: update to 201903b
  science/gildas/Portfile
Labels: maintainer, type: update

#3835 net/openssh: Update to version 7.9p1.
  net/openssh/Portfile
  net/openssh/files/gssapi.patch
  net/openssh/files/openssh-7.6p1-hpnssh14v13.diff
  net/openssh/files/openssh-7.9p1-hpnssh14v15.diff
Labels: maintainer: none, type: update

#3828 tkimg: update to 1.4.9
  graphics/tkimg/Portfile
  graphics/tkimg/files/patch-quartz.diff
Labels: maintainer: open, type: update

#2989 gtk3 3.22.30: Fix large fonts on Retina displays (HiDPI) for quartz
  gnome/gtk3/Portfile
  gnome/gtk3/files/patch-quartz-hardcode-screen-resolution.patch
Labels: maintainer: open, type: bugfix

#3853 fd: Change maintainer to me
  sysutils/fd/Portfile
Labels: maintainer: open

#3844 OpenBlas*: blacklist non-thread_local compilers
  math/OpenBLAS/Portfile
Labels: by: member, maintainer: open

#3841 Update Bison license
  devel/bison/Portfile
Labels: maintainer: none, type: bugfix

#3852 dnsviz: update to version 0.8.2
  net/dnsviz/Portfile
Labels: maintainer, maintainer: open, type: update

#3856 py-isort: update to 4.3.15
  python/py-isort/Portfile
Labels: maintainer, maintainer: open, type: update

#3854 py-sip: various fixes and tweaks for correctness and brevity
  python/py-sip/Portfile
Labels: by: member, maintainer, maintainer: open, type: bugfix

#3860 QtPBFImagePlugin: update to 1.3
  graphics/QtPBFImagePlugin/Portfile
Labels: maintainer, maintainer: open, type: enhancement, type: update

#3774 nethack: update to 3.6.1, keep 3.4.3 as coexisting subport
  games/nethack/Portfile
  games/nethack/files/patch-doc__nethack.6.diff
  games/nethack/files/patch-gamestate-dir.diff
  games/nethack/files/patch-manpage-dir.diff
  games/nethack/files/patch-sys__unix__Makefile.doc.diff
  games/nethack/files/patch-sys__unix__Makefile.top.diff
  games/nethack/files/x11/patch-x11-interface.diff
Labels: maintainer: requires approval, maintainer: timeout, type: enhancement, type: update

#3864 nethack: open maintainer; reduce main/subport redundancy
  games/nethack/Portfile
Labels: maintainer: requires approval, type: enhancement

#3867 crystal: update to 0.27.2
  lang/crystal/Portfile
  lang/crystal/files/patch-xml-reader.diff
Labels: maintainer, maintainer: open, type: update

#3865 websocketpp: new port
  net/websocketpp/Portfile
Labels: type: submission

#3866 cpprestsdk: update to 2.10.10
  www/cpprestsdk/Portfile
Labels: maintainer, maintainer: open, type: update

#3862 emacs{-app}-devel: Update to 01/03/2019 commit
  editors/emacs/Portfile
Labels: maintainer: open, type: enhancement, type: update

#3859 gambit version bump
  lang/gambit-c/Portfile
Labels: maintainer: none, type: enhancement

#3820 websvn: fix license
  www/websvn/Portfile
Labels: maintainer: open

#3875 ack: add a perl5.28 variant
  devel/ack/Portfile
Labels: by: member, maintainer: none

#3878 py-argh: add python 3.7
  python/py-argh/Portfile
Labels: maintainer: open, type: enhancement

#3877 newsboat: update to version 2.14.1
  net/newsboat/Portfile
  net/newsboat/files/patch-config.sh.diff
Labels: maintainer, maintainer: open, type: bugfix, type: enhancement, type: update

#3834 libwebsockets and mosquitto: Prepare for PR #3822
  net/mosquitto/Portfile
Labels: maintainer, maintainer: open

#3885 GPXSee: update to 7.5
  gis/GPXSee/Portfile
Labels: maintainer, maintainer: open, type: enhancement, type: update

#3884 py-argcomplete: new port
  python/py-argcomplete/Portfile
Labels: type: submission

#3882 lenstool: submission (new Portfile)
  science/lenstool/Portfile
Labels: type: submission

#3846 terraform: update to 0.11.13
  sysutils/terraform/Portfile
Labels: maintainer: open, type: update

#3858 swi-prolog-devel: update to 8.1.3
  lang/swi-prolog-devel/Portfile
Labels: maintainer, type: update

#3889 SoapySDRPlay: new port
  science/SoapySDRPlay/Portfile
Labels: type: submission

#3892 redis: update to 5.0.4
  databases/redis/Portfile
Labels: maintainer: none, type: enhancement, type: update

#3893 rtl_433: update to 18.12
  science/rtl_433/Portfile
Labels: maintainer: open, type: update

#3891 CubicSDR: new port
  science/CubicSDR/Portfile
Labels: type: submission

#3888 hamlib: update to 3.3
  science/hamlib/Portfile
Labels: maintainer: none, type: update

#3894 p5-dancer: update to version 1.3510
  perl/p5-dancer/Portfile
Labels: by: member, maintainer: open, type: update

#3897 p5-tcl-ptk: update to version 0.96, minor description typo
  perl/p5-tcl-ptk/Portfile
Labels: by: member, maintainer: open, type: update

#3895 p5-text-csv_xs: update to version 1.39
  perl/p5-text-csv_xs/Portfile
Labels: by: member, maintainer: open, type: update

#3898 p5-webservice-musicbrainz: update to version 1.0.5
  perl/p5-webservice-musicbrainz/Portfile
Labels: by: member, maintainer: open, type: update

#3896 VLC : make build on 10.11
  multimedia/VLC/Portfile
  multimedia/VLC/files/patch-build-on-darwin13.diff
  multimedia/VLC/files/patch-build-on-pre-1014.diff
Labels: maintainer, maintainer: open

#3900 openjdk8: add subport openjdk12-openj9
  java/openjdk8/Portfile
Labels: maintainer, maintainer: open

#3872 py-roman: update to 3.1
  python/py-roman/Portfile
Labels: maintainer: open, type: update

#3871 py-pytest-runner: update to 4.4
  python/py-pytest-runner/Portfile
Labels: maintainer: open, type: update

#3905 youtube-dl: Update to 2019.03.18
  net/youtube-dl/Portfile
Labels: maintainer: open, type: update

#3906 php4: remove duplicate revision line
  lang/php4/Portfile
Labels: by: member, maintainer: requires approval

#3907 ntfs-3g: Fix CVE-2019-9755
  fuse/ntfs-3g/Portfile
  fuse/ntfs-3g/files/patch-CVE-2019-9755.diff
Labels: by: member, maintainer: none, type: security fix

#3876 Update PHP to 7.3.3
  lang/php/Portfile
Labels: maintainer: requires approval, maintainer: timeout, type: enhancement

#3909 py-simplekml: new port, version 1.3.1
  python/py-simplekml/Portfile
Labels: type: submission

#3912 glm: bump to 0.9.9.4 and fix build on older systems
  devel/glm/Portfile
Labels: by: member, maintainer: open

#3914 py-keyring: update to 19.0.0
  python/py-keyring/Portfile
Labels: maintainer, maintainer: open, type: update

#3915 py-rope: update to 0.14.0, update license
  python/py-rope/Portfile
Labels: maintainer, maintainer: open, type: update

#3920 borgbackup: set to nomaintainer
  sysutils/borgbackup/Portfile
Labels: maintainer, maintainer: open

#3911 gitlab-runner: update to 11.9.0
  devel/gitlab-runner/Portfile
Labels: maintainer, maintainer: open, type: update

#3913 tor-devel: update to 0.4.0.3-alpha
  security/tor-devel/Portfile
Labels: maintainer: none, type: bugfix, type: enhancement, type: update

#3919 openjdk8: add openjdk12 subport
  java/openjdk8/Portfile
Labels: maintainer, maintainer: open

#3863 Arduino upstream 1.8.9 released
  devel/Arduino/Portfile
Labels: maintainer, maintainer: open, type: enhancement

#3925 doclifter: use python27
  textproc/doclifter/Portfile
Labels: by: member, maintainer: none, wip

#3908 mythtv.28: build fix for x264 build 153+
  multimedia/mythtv.28/Portfile
  multimedia/mythtv.28/files/patch-x264-build-153.diff
Labels: by: member, maintainer: open, type: bugfix

#3916 py-spyder-devel: update to a8b9d43 (20190321)
  python/py-spyder-devel/Portfile
  python/py-spyder-devel/files/patch-spyder_config_main.py.diff
Labels: maintainer, maintainer: open, type: update

#3930 google-cloud-sdk: update to 239.0.0
  devel/google-cloud-sdk/Portfile
Labels: maintainer, maintainer: open, type: update

#3935 libssh2: update to 1.8.1
  devel/libssh2/Portfile
Labels: by: member, maintainer: open, type: security fix, type: update

#3932 XFree86: delete port
  x11/XFree86/Portfile
  x11/XFree86/files/patch-XTerm.ad
  x11/XFree86/files/patch-Xtranssock.c.diff
  x11/XFree86/files/patch-decompress.c.diff
  x11/XFree86/files/patch-freetype.h
  x11/XFree86/files/patch-glxcmds.c
Labels: maintainer: none

#3937 SoapyRTLSDR: new port
  science/SoapyRTLSDR/Portfile
Labels: type: submission

#3939 ngspice: update to version 30, add openmp variant
  science/ngspice/Portfile
Labels: maintainer, maintainer: open, type: update

#3927 iTerm2: update to 3.2.8
  aqua/iTerm2/Portfile
Labels: by: member, maintainer: open, type: update

#3924 py-pyqt4, py-pyqt5: update homepage and livecheck URLs
  python/py-pyqt4/Portfile
  python/py-pyqt5/Portfile
Labels: maintainer: open, type: enhancement

#3945 consul: update to 1.4.4
  net/consul/Portfile
Labels: maintainer, maintainer: open, type: update

#3886 barman: new port
  databases/barman/Portfile
Labels: type: submission

#3922 myrepos: update to version 1.20180726
  devel/myrepos/Portfile
Labels: maintainer: open, type: bugfix, type: enhancement, type: update

#3936 yarn: update to 1.15.2
  devel/yarn/Portfile
Labels: by: member, maintainer: open, type: update

#3941 gdb: Change uint64_t to ULONGEST to fix +multiarch
  devel/gdb/Portfile
  devel/gdb/files/patch-gdb-aarch64-linux-tdep.c.diff
Labels: maintainer: none, type: bugfix

#3917 cpprestsdk: update to 2.10.11
  www/cpprestsdk/Portfile
Labels: maintainer, maintainer: open, type: update

#3940 bash: update to patch 3
  shells/bash/Portfile
Labels: maintainer: requires approval, type: enhancement, type: update

#3943 bedtools: update to 2.28.0 (and remove patch)
  science/bedtools/Portfile
  science/bedtools/files/patch-docs-conf.py.diff
  science/bedtools/files/patch-src-utils-BamTools-include-BamAlignment.hpp.diff
  science/bedtools/files/patch-src-utils-BamTools-include-SamHeader.hpp.diff
Labels: type: update

#3955 phonon, phonon-backend-gstreamer: use HTTPS homepage
  audio/phonon-backend-gstreamer/Portfile
  audio/phonon/Portfile
Labels: maintainer: open, type: enhancement

#3952 py-isort: update to 4.3.16
  python/py-isort/Portfile
Labels: maintainer, maintainer: open, type: update

#3953 blueutil: add maintainer's GitHub handle
  sysutils/blueutil/Portfile
Labels: maintainer: requires approval

#3958 py-language-server: update to 0.26.0
  python/py-language-server/Portfile
Labels: maintainer, maintainer: open, type: update

#3959 nginx: add stream_ssl_preread module
  www/nginx/Portfile
Labels: maintainer: open, type: enhancement

#3961 nano: bugfix building for nano v4
  editors/nano/Portfile
Labels: maintainer: open, type: bugfix

#3957 py-keyring: update to 18.0.1 and 19.0.1
  python/py-keyring/Portfile
Labels: maintainer, maintainer: open, type: update

#3948 py-pgspecial: update to 1.11.5
  python/py-pgspecial/Portfile
Labels: maintainer: open, type: update

#3947 vault: update to 1.1.0
  security/vault/Portfile
Labels: maintainer, maintainer: open, type: update

#3934 Black: new port
  python/black/Portfile
Labels: by: member, maintainer: open, type: submission
