Repository macports/macports-ports, pull requests merged in 2020-02, with the labels that each got.

#6288 textproc/qpdf: trivial version update to 9.1.1
  textproc/qpdf/Portfile
Labels: by: member, maintainer: none

#6285 nvm: Add notes for usage
  devel/nvm/Portfile
Labels: maintainer, maintainer: open, type: enhancement

#6291 lazygit: update to 0.14
  devel/lazygit/Portfile
Labels: maintainer, maintainer: open, type: update

#6263 py-twine: update to 3.1.1
  python/py-twine/Portfile
Labels: by: member, maintainer: open, type: update

#6292 Gildas: update to 202002a
  science/gildas/Portfile
  science/gildas/files/patch-admin-Makefile.build.diff
  science/gildas/files/patch-admin-define-system.sh.diff
Labels: maintainer, type: update

#6295 k9s: update to 0.13.7
  sysutils/k9s/Portfile
Labels: maintainer, maintainer: open, type: update

#6164 mysql_select: add MySQL8's ibd2sdi
  databases/mariadb-10.0/files/mariadb-10.0
  databases/mariadb-10.1/files/mariadb-10.1
  databases/mariadb-10.2/files/mariadb-10.2
  databases/mariadb/files/mariadb
  databases/mysql51/files/mysql51
  databases/mysql55/files/mysql55
  databases/mysql56/files/mysql56
  databases/mysql57/files/mysql57
  databases/mysql8/files/mysql8
  databases/mysql_select/Portfile
  databases/mysql_select/files/base
  databases/mysql_select/files/none
  databases/percona/files/percona
Labels: maintainer, maintainer: open

#6296 buku: update to 4.3
  www/buku/Portfile
  www/buku/files/patch-prompt-colors-fix.diff
Labels: maintainer, maintainer: open, type: update

#6298 qlandkartegt: upgrade to latest revision
  gis/qlandkartegt/Portfile
Labels: maintainer

#6303 mercurial: update to 5.3
  devel/mercurial/Portfile
Labels: maintainer: none, type: update

#6302 starship: update to 0.34.1
  sysutils/starship/Portfile
Labels: maintainer, maintainer: open, type: update

#6301 google-cloud-sdk: update to 279.0.0
  devel/google-cloud-sdk/Portfile
Labels: maintainer, maintainer: open, type: update

#6300 dvdbackup: revbump after libdvdread upgrade
  multimedia/dvdbackup/Portfile
Labels: maintainer: none

#6299 welle.io: update welle.io-devel to 20200204
  multimedia/welle.io/Portfile
Labels: maintainer: none, type: update

#6307 TexShop4: fix build for macOS 10.14 with Xcode 11
  aqua/TeXShop4/Portfile
Labels: maintainer: open

#6262 ld64-latest: build 450.3
  devel/ld64/Portfile
  devel/ld64/files/Makefile-450
  devel/ld64/files/dyld-655-availability.diff
  devel/ld64/files/ld64-409-Options-strndup.diff
  devel/ld64/files/ld64-409-add-missing-machine-defs.diff
  devel/ld64/files/ld64-409-lto-file-llvm-3.4-fix.diff
  devel/ld64/files/ld64-409-options-disable-i386-warning.diff
  devel/ld64/files/ld64-409-snapshot-no-mkpath-np.diff
  devel/ld64/files/ld64-450-move-baseplatform-def-to-header.diff
Labels: by: member, maintainer, type: enhancement

#6316 rspamd: Update to Version 2.3
  mail/rspamd/Portfile
Labels: maintainer: none, type: update

#6319 tor: update to 0.4.2.6
  security/tor/Portfile
Labels: maintainer: none, type: update

#6318 tor-devel: update to 0.4.3.1-alpha
  security/tor-devel/Portfile
Labels: maintainer: none, type: update

#6324 wireguard-tools: update to 1.0.20200206
  net/wireguard-tools/Portfile
Labels: maintainer, maintainer: open, type: update

#6321 broot: update to 0.13.0
  sysutils/broot/Portfile
Labels: maintainer, maintainer: open, type: update

#6322 starship: update to 0.35.1
  sysutils/starship/Portfile
Labels: maintainer, maintainer: open, type: update

#6320 lazygit: update to 0.14.2
  devel/lazygit/Portfile
Labels: maintainer, maintainer: open, type: update

#6312 wtfutil: update to 0.26.0
  sysutils/wtfutil/Portfile
Labels: maintainer, maintainer: open, type: update

#6311 micronaut: update to 1.3.0
  java/micronaut/Portfile
Labels: maintainer, maintainer: open, type: update

#6310 dbvis: update to 10.0.26
  databases/dbvis/Portfile
Labels: maintainer, maintainer: open, type: update

#6323 mercurial: add py27-gnureadline as a runtime dependency.
  devel/mercurial/Portfile
Labels: maintainer: none, type: bugfix, type: enhancement

#6304 hugo: update to 0.64.0
  www/hugo/Portfile
Labels: type: update

#6330 FAudio: Update to 20.02
  audio/FAudio/Portfile
Labels: maintainer: none, type: enhancement, type: update

#6325 sigil: update to 1.1.0
  editors/sigil/Portfile
Labels: maintainer: none, type: update

#6293 mpv: update to 0.31.0
  multimedia/mpv/Portfile
  multimedia/mpv/files/patch-fix-swift-detection.diff
  multimedia/mpv/files/patch-osdep-macosx_compat-h-typo.diff
Labels: by: member, maintainer: requires approval, maintainer: timeout, type: update

#6337 screen: update to 4.8.0
  sysutils/screen/Portfile
  sysutils/screen/files/patch-apple.diff
  sysutils/screen/files/patch-config.h.in.diff
  sysutils/screen/files/patch-limit-termcap-size.diff
Labels: maintainer, maintainer: open, type: enhancement, type: update

#6338 openjdk8: AdoptOpenJDK requires OS 10.10 or later
  java/openjdk8/Portfile
Labels: maintainer, maintainer: open, type: bugfix

#6313 topydo: Use Python 37
  office/topydo/Portfile
Labels: maintainer: none

#6336 py-lockfile: update to 0.12.2
  python/py-lockfile/Portfile
Labels: maintainer: none, type: enhancement, type: update

#6334 py-pylev: new port
  python/py-pylev/Portfile
Labels: type: enhancement, type: submission

#6332 py-tomlkit: new port
  python/py-tomlkit/Portfile
Labels: type: enhancement, type: submission

#6331 py-shellingham: new port
  python/py-shellingham/Portfile
Labels: type: enhancement, type: submission

#6335 py-pastel: new port
  python/py-pastel/Portfile
Labels: type: enhancement, type: submission

#6345 nano: Update to 4.8
  editors/nano/Portfile
Labels: maintainer: open, type: update

#6343 flac: fix for building with PowerPC
  audio/flac/Portfile
  audio/flac/files/patch-ppc-cpu.c.diff
Labels: maintainer: none, type: bugfix

#6346 py-clikit: new port
  python/py-clikit/Portfile
Labels: type: enhancement, type: submission

#6347 hugo: update to 0.64.1
  www/hugo/Portfile
Labels: maintainer, maintainer: open, type: update

#6349 py-nclib: Enable support for Python 3.8
  python/py-nclib/Portfile
Labels: maintainer, maintainer: open, type: enhancement

#6348 routino: update to 3.3.2
  gis/routino/Portfile
  gis/routino/files/patch-Makefile_conf.diff
  gis/routino/files/patch-src_Makefile_dylib_extension.diff
Labels: maintainer: open, type: enhancement, type: update

#6327 sane-frontends: fetch from gitlab.com, adapt livecheck, add license
  graphics/sane-frontends/Portfile
Labels: maintainer: none

#6352 k9s: update to 0.13.8
  sysutils/k9s/Portfile
Labels: maintainer, maintainer: open, type: update

#6333 py-gpilab: update to latest; add 38 flavors.
  python/py-gpilab-core/Portfile
  python/py-gpilab-core/files/Matplotlib_GPI.py.patch
  python/py-gpilab-examples/Portfile
  python/py-gpilab-framework/Portfile
  python/py-gpilab-framework/files/canvasGraph.py.diff
  python/py-gpilab-framework/files/mainWindow.py.diff
Labels: by: member, maintainer, maintainer: open, type: update

#6342 py-cachy: new port
  python/py-cachy/Portfile
Labels: type: enhancement, type: submission

#6344 py-CacheControl: new port
  python/py-cachecontrol/Portfile
Labels: type: enhancement, type: submission

#6341 py-pyqt5-*: update to 5.14.1; switch to PyPI
  python/py-pyqt5/Portfile
Labels: maintainer: none, type: update

#6364 groovy: update to 3.0.0
  lang/groovy/Portfile
Labels: maintainer, maintainer: open, type: update

#6363 k9s: update to 0.14.0
  sysutils/k9s/Portfile
Labels: maintainer, maintainer: open, type: update

#6362 consul: update to 1.7.0
  net/consul/Portfile
Labels: maintainer, maintainer: open, type: update

#6361 delve: update to 1.4.0
  devel/delve/Portfile
Labels: maintainer, maintainer: open, type: update

#6359 tor-devel: update to 0.4.3.2-alpha
  security/tor-devel/Portfile
Labels: maintainer: none, type: update

#6354 py-cleo: new port
  python/py-cleo/Portfile
Labels: type: enhancement, type: submission

#6360 OpenBLAS: update to 0.3.8
  math/OpenBLAS/Portfile
Labels: by: member, maintainer, maintainer: open, type: enhancement, type: update

#6358 meson: Update to 0.53.1
  devel/meson/Portfile
Labels: maintainer: open, type: update

#6350 New Portfile for maxminddb 1.5.2
  python/py-maxminddb/Portfile
Labels: type: submission

#6370 mbedtls: build shared library
  devel/mbedtls/Portfile
Labels: by: member, maintainer: open, type: enhancement

#6371 kompose: new port submission
  devel/kompose/Portfile
Labels: by: member, type: submission

#6356 gdb: Update to 9.1
  devel/gdb/Portfile
Labels: maintainer: none, type: update

#6317 zsh-autosuggestions: new Portfile
  sysutils/zsh-autosuggestions/Portfile
Labels: type: submission

#6367 p5-mail-spamassassin: Update to v3.4.4
  perl/p5-mail-spamassassin/Portfile
Labels: maintainer: none, type: bugfix, type: enhancement, type: security fix, type: update

#6351 p5-compress-raw-lzma: new port
  perl/p5-compress-raw-lzma/Portfile
Labels: type: submission

#6372 p5-io-compress-lzma: new port
  perl/p5-io-compress-lzma/Portfile
Labels: type: submission

#6374 google-cloud-sdk: update to 280.0.0
  devel/google-cloud-sdk/Portfile
Labels: maintainer, maintainer: open, type: update

#6377 range-v3: new port
  devel/range-v3/Portfile
Labels: type: submission

#6378 cctools: remove resource fork from more files
  devel/cctools/Portfile
Labels: by: member, maintainer: open, type: bugfix

#6381 asciidoc: Update to asciidoc-py3 9.0.0rc1
  textproc/asciidoc/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#6380 lazygit: update to 0.14.3
  devel/lazygit/Portfile
Labels: maintainer, maintainer: open, type: update

#6384 GPXSee: update to 7.22
  gis/GPXSee/Portfile
Labels: type: enhancement, type: update

#6286 grafx2: update to 2.7
  graphics/grafx2/Portfile
  graphics/grafx2/files/patch-osx-tiger_Makefile-b.diff
  graphics/grafx2/files/patch-osx-tiger_Makefile.diff
  graphics/grafx2/files/patch-osx-tiger_realpath.c.diff
Labels: maintainer, maintainer: open, type: enhancement, type: update

#6369 Update QEMU to version 4.2.0 to fix Cocoa crash.
  emulators/qemu/Portfile
Labels: maintainer: open, type: bugfix, type: update

#6373 radare2: update to 4.2.1
  devel/radare2/Portfile
Labels: maintainer: open, type: update

#6393 packer: update to 1.5.4
  sysutils/packer/Portfile
Labels: maintainer, maintainer: open, type: update

#6392 angle-grinder: update to 0.13.0
  sysutils/angle-grinder/Portfile
Labels: maintainer, maintainer: open, type: update

#6387 micronaut: update to 1.3.1
  java/micronaut/Portfile
Labels: maintainer, maintainer: open, type: update

#6385 prometheus: update to 2.16.0
  net/prometheus/Portfile
Labels: maintainer, maintainer: open, type: update

#6386 k9s: update to 0.15.2
  sysutils/k9s/Portfile
Labels: maintainer, maintainer: open, type: update

#6403 youtube-dl: Update to 2020.02.16
  net/youtube-dl/Portfile
Labels: maintainer: open, type: update

#6404 socat: Update to 1.7.3.4
  sysutils/socat/Portfile
  sysutils/socat/files/patch-xio-termios.h.diff
Labels: maintainer: open, type: update

#6402 broot: update to 0.13.2
  sysutils/broot/Portfile
Labels: maintainer, maintainer: open, type: update

#6400 f3: update to 7.2
  sysutils/f3/Portfile
Labels: maintainer, maintainer: open, type: enhancement, type: update

#6405 QLStephen: Update to 1.5.1
  sysutils/QLStephen/Portfile
Labels: maintainer: none, type: update

#6399 bashdb: update to 5.0-1.1.2
  devel/bashdb/Portfile
Labels: maintainer: none, type: enhancement, type: update

#6398 argp-standalone: fix livecheck regex
  devel/argp-standalone/Portfile
Labels: maintainer: none, type: bugfix

#6391 swi-prolog-devel: updatew to 8.1.22
  lang/swi-prolog-devel/Portfile
Labels: maintainer, type: update

#6379 lilypond-devel: update to 2.19.84
  textproc/lilypond-devel/Portfile
  textproc/lilypond-devel/files/patch-avoid-empty-locale.diff
  textproc/lilypond-devel/files/patch-no-Wstrict-prototypes-warning.diff
Labels: maintainer: open, type: enhancement, type: update

#6183 SourceKitten: Update to 0.29.0
  devel/SourceKitten/Portfile
Labels: maintainer: none, type: update

#6375 fsdb, fsdb_select: new ports
  perl/fsdb/Portfile
  perl/fsdb/files/fsdb-5.26
  perl/fsdb/files/fsdb-5.28
  perl/fsdb/files/fsdb-5.30
  perl/fsdb_select/Portfile
  perl/fsdb_select/files/base
  perl/fsdb_select/files/none
Labels: type: submission

#6412 gtk3: update to 3.24.14
  gnome/gtk3/Portfile
Labels: maintainer: open, type: enhancement, type: update

#6413 ld64: adjust no-blocks patch for < 10.6
  devel/ld64/Portfile
  devel/ld64/files/dyld-421-no-blocks.patch
  devel/ld64/files/dyld-655-no-blocks.patch
Labels: by: member, maintainer

#6397 py-trio: update to 0.13.0, add python38 variant
  python/py-outcome/Portfile
  python/py-sniffio/Portfile
  python/py-trio/Portfile
  python/py-trio/files/patch-trio-_socket.py-select-fix.diff
  python/py-trustme/Portfile
Labels: maintainer, maintainer: open, type: update

#6416 groovy: update to 3.0.1
  lang/groovy/Portfile
Labels: maintainer, maintainer: open, type: update

#6417 google-cloud-sdk: update to 281.0.0
  devel/google-cloud-sdk/Portfile
Labels: maintainer, maintainer: open, type: update

#6418 kubectl: update kubectl-1.16 to 1.16.7
  sysutils/kubectl/Portfile
Labels: maintainer: open, type: update

#6419 kubectl: update kubectl-1.15 to 1.15.10
  sysutils/kubectl/Portfile
Labels: maintainer: open, type: update

#6420 kubectl: add kubectl-1.17 subport
  sysutils/kubectl/Portfile
Labels: maintainer: open

#6415 git: Update to 2.25.1
  devel/git/Portfile
  devel/git/files/patch-git-subtree.1.diff
  devel/git/files/patch-git-subtree.html.diff
Labels: maintainer: open, type: update

#6410 dovecot: Update to version 2.3.9.3
  mail/dovecot/Portfile
Labels: maintainer: open, type: enhancement, type: update

#6421 terraform-0.12: update to 0.12.21
  sysutils/terraform/Portfile
Labels: maintainer, maintainer: open, type: update

#6424 lazygit: update to 0.14.4
  devel/lazygit/Portfile
Labels: maintainer, maintainer: open, type: update

#6422 nomad: update to 0.10.4
  net/nomad/Portfile
Labels: maintainer, maintainer: open, type: update

#6388 appengine-java-sdk: update to 1.9.78
  java/appengine-java-sdk/Portfile
Labels: maintainer: open, type: enhancement, type: update

#5465 Php tideways xhprof submission
  php/php-tideways_xhprof/Portfile
Labels: type: enhancement, type: submission

#6423 rust: update to 1.41.0
  lang/rust/Portfile
Labels: maintainer: open, type: update

#6411 nco: update to 4.9.2
  science/nco/Portfile
Labels: maintainer: requires approval, maintainer: timeout, type: enhancement, type: update

#6426 k9s: update to 0.16.1
  sysutils/k9s/Portfile
Labels: maintainer, maintainer: open, type: update

#6427 consul: update to 1.7.1
  net/consul/Portfile
Labels: maintainer, maintainer: open, type: update

#6407 git-lfs: update to 2.10.0
  devel/git-lfs/Portfile
Labels: maintainer: open, type: enhancement, type: update

#6433 hugo: update to 0.65.2
  www/hugo/Portfile
Labels: maintainer, maintainer: open, type: update

#6432 micronaut: update to 1.3.2
  java/micronaut/Portfile
Labels: maintainer, maintainer: open, type: update

#6431 kubectx: update to 0.8.0
  sysutils/kubectx/Portfile
Labels: maintainer, maintainer: open, type: update

#6430 cargo: update to 0.41.0
  devel/cargo/Portfile
Labels: maintainer: none, type: update

#6383 python PG: update default version to 3.8
  _resources/port1.0/group/python-1.0.tcl
Labels: by: member, type: enhancement, type: update

#6434 starship: update to 0.36.1
  sysutils/starship/Portfile
Labels: maintainer, maintainer: open, type: update

#6401 bochs: update to version 2.6.11
  emulators/bochs/Portfile
  emulators/bochs/files/patch-.bochsrc.diff
  emulators/bochs/files/patch-bxhub.cc.diff
  emulators/bochs/files/patch-cdrom_osx.cc.diff
  emulators/bochs/files/patch-dbg_main.cc.diff
  emulators/bochs/files/patch-eth_socket.cc.diff
Labels: maintainer: requires approval, maintainer: timeout, type: enhancement, type: update

#6406 percona-toolkit: update to version 3.1.0
  databases/percona-toolkit/Portfile
Labels: maintainer: none, type: update

#6355 crossbinutils: Update to 2.34
  _resources/port1.0/group/crossbinutils-1.0.tcl
  cross/arm-elf-binutils/Portfile
  cross/arm-none-eabi-binutils/Portfile
  cross/arm-none-linux-gnueabi-binutils/Portfile
  cross/avr-binutils/Portfile
  cross/i386-elf-binutils/Portfile
  cross/i686-w64-mingw32-binutils/Portfile
  cross/m68k-elf-binutils/Portfile
  cross/mips-elf-binutils/Portfile
  cross/ppc-linux-binutils/Portfile
  cross/spu-binutils/Portfile
  cross/x86_64-elf-binutils/Portfile
  cross/x86_64-w64-mingw32-binutils/Portfile
Labels: maintainer: none, type: update

#6425 cctools: Update as patch to allow search for MacPorts clang to be disabled
  devel/cctools/Portfile
  devel/cctools/files/as-try-clang.patch
Labels: by: member, maintainer: open, type: update

#6438 bind9: use legacysupport PortGroup
  net/bind9/Portfile
Labels: by: member, maintainer: requires approval, type: bugfix

#6444 docker-machine: update to 0.16.2
  devel/docker-machine/Portfile
Labels: by: member, maintainer: none, type: update

#6437 meson: switch to python 3.8
  devel/meson/Portfile
Labels: by: member, maintainer: open

#6429 pcre: update to 8.44
  devel/pcre/Portfile
Labels: maintainer: requires approval, maintainer: timeout, type: enhancement, type: update

#6447 pydicom: update to 1.4.2
  python/py-pydicom/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#6448 xephem: use bundled motif
  science/xephem/Portfile
  science/xephem/files/patch-Makefile.diff
Labels: by: member, maintainer: none, type: bugfix

#6450 py-subprocess32: update to 3.5.4
  python/py-subprocess32/Portfile
Labels: by: member, maintainer: open, type: update

#6454 lazygit: update to 0.15.3
  devel/lazygit/Portfile
Labels: maintainer, maintainer: open, type: update

#6455 go: update to 1.14
  lang/go/Portfile
Labels: maintainer: open, type: update

#6453 hugo: update to 0.65.3
  www/hugo/Portfile
Labels: maintainer, maintainer: open, type: update

#6456 py-docker: add missing dependency
  python/py-docker/Portfile
Labels: by: member, maintainer: none, type: enhancement

#6436 upt: switch to python3.8
  python/py-upt-cpan/Portfile
  python/py-upt-macports/Portfile
  python/py-upt-pypi/Portfile
  python/py-upt-rubygems/Portfile
  sysutils/upt/Portfile
Labels: by: member, maintainer: open

#6458 py-cached-property: add support for python 3.8
  python/py-cached-property/Portfile
Labels: by: member, maintainer: none, type: enhancement

#6457 py-dockerpty: fix dependencies
  python/py-dockerpty/Portfile
Labels: by: member, maintainer: none

#6442 docker: update to 19.03.6
  devel/docker/Portfile
Labels: by: member, maintainer: none, type: update

#6461 py-socks: update to 1.7.0
  python/py-socks/Portfile
Labels: by: member, maintainer: open, type: update

#6463 google-cloud-sdk: update to 282.0.0
  devel/google-cloud-sdk/Portfile
Labels: maintainer, maintainer: open, type: update

#6464 k9s: update to 0.17.0
  sysutils/k9s/Portfile
Labels: maintainer, maintainer: open, type: update

#6462 docker-compose: update to 1.25.4
  python/docker-compose/Portfile
  python/docker-compose/files/patch-setup.py.diff
Labels: by: member, maintainer: none, type: update

#6440 wtfutil: update to 0.27.0
  sysutils/wtfutil/Portfile
Labels: maintainer, maintainer: open, type: update

#6465 SDRplay3: new port
  science/SDRplay3/Portfile
  science/SDRplay3/files/license.txt
Labels: by: member, type: submission

#6467 gitlab-runner: update to 12.8.0
  devel/gitlab-runner/Portfile
Labels: maintainer, maintainer: open, type: update

#6471 meson: Update to 0.53.2
  devel/meson/Portfile
Labels: maintainer: open, type: update

#6472 docker: acquire maintainership
  devel/docker/Portfile
Labels: by: member, maintainer: none

#6473 py-docker: acquire maintainership
  python/py-docker/Portfile
Labels: by: member, maintainer: none

#6474 py-dockerpty: acquire maintainership
  python/py-dockerpty/Portfile
Labels: by: member, maintainer: none

#6441 swi-prolog-devel: update to 8.1.23
  lang/swi-prolog-devel/Portfile
Labels: maintainer, type: update

#6468 cfm: new Portfile
  sysutils/cfm/Portfile
Labels: type: submission
