Repository macports/macports-ports, pull requests merged in 2020-10, with the labels that each got.

#8578 evans: don't fetch dependencies in build phase
  devel/evans/Portfile
Labels: by: member, maintainer: open, type: bugfix

#8579 mingw-binutils: upgrade to 2.35
  _resources/port1.0/group/crossbinutils-1.0.tcl
  cross/i686-w64-mingw32-binutils/Portfile
  cross/x86_64-w64-mingw32-binutils/Portfile
Labels: maintainer: open, type: enhancement

#8593 chezmoi: don't fetch dependencies in build phase
  sysutils/chezmoi/Portfile
Labels: by: member, maintainer: open, type: bugfix

#8594 cloudmonkey: don't fetch dependencies in build phase
  sysutils/cloudmonkey/Portfile
Labels: by: member, maintainer: open, type: bugfix

#8585 weechat: update to 2.9, cleanup Portfile
  irc/weechat-devel/Portfile
  irc/weechat/Portfile
Labels: maintainer: open, type: update

#8584 thrift +glib2: fix implicit function declaration
  devel/thrift/Portfile
  devel/thrift/files/patch-0d6a2d3.diff
  devel/thrift/files/patch-thrift_protocol_decorator.h.diff
  devel/thrift/files/patch-thrift_ssl_socket.h.diff
Labels: maintainer: none

#8595 thrift: actually use patchfiles
  devel/thrift/Portfile
Labels: maintainer: none

#8597 smpeg: fix patch offsets
  multimedia/smpeg/Portfile
  multimedia/smpeg/files/patch-configure-flags.diff
Labels: maintainer: none, type: enhancement

#8599 libmikmod: update to 3.3.11.1
  audio/libmikmod/Portfile
  audio/libmikmod/files/patch-ngvolume
Labels: maintainer: none, type: update

#8596 impressive: update to 0.12.1
  python/impressive/Portfile
Labels: maintainer: none, type: update

#8600 weechat: use legacysupport
  irc/weechat/Portfile
Labels: maintainer: open

#8583 skaffold: update to 1.15.0
  devel/skaffold/Portfile
Labels: maintainer, maintainer: open, type: update

#8602 py-slackclient: update to v2.9.1
  python/py-slackclient/Portfile
Labels: maintainer, maintainer: open, type: update

#8601 py-umap-learn: Submission
  python/py-umap-learn/Portfile
Labels: type: enhancement, type: submission

#8582 google-cloud-sdk: update to 312.0.0
  devel/google-cloud-sdk/Portfile
Labels: maintainer, maintainer: open, type: update

#8577 check: update to 0.15.2, cleanup Portfile
  devel/check/Portfile
Labels: maintainer: none, type: update

#8559 swi-prolog-devel: Updated to version 8.3.8
  lang/swi-prolog-devel/Portfile
Labels: maintainer, maintainer: open, type: update

#8469 dovecot: apns variant bugfix and compiler error fix
  mail/dovecot/Portfile
  mail/dovecot/files/dovecot-core-pushnotify.patch
  mail/dovecot/files/patch-src-lib-ioloop-notify-kqueue-c.diff
Labels: maintainer: open, type: bugfix

#8603 mupdf: update to version 1.17.0
  graphics/mupdf/Portfile
  graphics/mupdf/files/patch-Makerules.diff
Labels: by: member, maintainer: open, type: update

#8607 bwping: update to 2.1
  net/bwping/Portfile
Labels: maintainer, maintainer: open, type: update

#8604 ansifilter: update to 2.17
  textproc/ansifilter/Portfile
Labels: maintainer, maintainer: open, type: update

#8598 py-sentence-transformers: Update to version 0.3.7
  python/py-sentence-transformers/Portfile
Labels: maintainer: none, type: enhancement, type: update

#8611 thrift: update Upstream-Status in patches
  devel/thrift/Portfile
  devel/thrift/files/patch-thrift_protocol_decorator.h.diff
  devel/thrift/files/patch-thrift_ssl_socket.h.diff
Labels: maintainer: none, type: update

#8539 netgen: fix build on macOS 10.13 and earlier
  math/netgen/Portfile
Labels: maintainer: open

#8576 zola: new port
  www/zola/Portfile
Labels: by: member, type: submission

#8591 Gildas: update to 202010a
  science/gildas/Portfile
Labels: maintainer, type: update

#8442 py-scikit-image: build with OpenMP support
  python/py-scikit-image/Portfile
Labels: maintainer: open

#8613 seed: update Upstream-Status in patch
  gnome/seed/files/patch-modules-os-seed-os.c.diff
Labels: maintainer: none

#8617 autojump: Update to 22.5.3
  sysutils/autojump/Portfile
Labels: maintainer: none, type: update

#8605 FAudio: Update to 20.10
  audio/FAudio/Portfile
  audio/FAudio/files/faudio.pc
Labels: maintainer: none, type: enhancement, type: update

#8618 ansifilter: use the right compiler
  textproc/ansifilter/Portfile
Labels: maintainer: open

#8622 certigo: don't fetch dependencies in build phase
  sysutils/certigo/Portfile
Labels: by: member, maintainer: open, type: bugfix

#8623 gitqlite: don't fetch dependencies in build phase
  devel/gitqlite/Portfile
Labels: by: member, maintainer: open, type: bugfix

#8608 py-urwidtrees: new port
  python/py-urwidtrees/Portfile
Labels: type: enhancement, type: submission

#8217 cgal5: cleanup compilers
  gis/cgal5/Portfile
Labels: maintainer: requires approval, maintainer: timeout

#8614 R: Add openmp variant & change openblas variant to lowercase
  math/R/Portfile
Labels: by: member, maintainer, maintainer: open, type: enhancement

#8619 haproxy: update to 2.2.4
  net/haproxy/Portfile
Labels: by: member, maintainer: open, type: update

#8072 ispc{-clang}: extend legacy-support to 10.11
  lang/ispc/Portfile
Labels: maintainer: open, type: bugfix

#8335 bazel: minor adjustments
  devel/bazel/Portfile
Labels: maintainer: open

#8630 p5-graphviz2: update to version 2.50
  perl/p5-graphviz2/Portfile
Labels: by: member, maintainer: open, type: update

#8624 py-atomiclong: new port
  python/py-atomiclong/Portfile
Labels: type: submission

#8625 py-fusepy: new port
  python/py-fusepy/Portfile
Labels: type: submission

#8628 gitlab-runner: update to 13.4.1
  devel/gitlab-runner/Portfile
Labels: maintainer, maintainer: open, type: update

#8627 micronaut: update to 2.1.0
  java/micronaut/Portfile
Labels: maintainer, maintainer: open, type: update

#8571 libheif: Update to 1.9.1
  multimedia/libheif/Portfile
Labels: by: member, maintainer: open, type: update

#8621 igraph: update to 0.8.3
  math/igraph/Portfile
Labels: maintainer, maintainer: open, type: bugfix, type: enhancement, type: update

#8525 py-Pillow: move xcb to x11 variant
  python/py-Pillow/Portfile
Labels: by: member, maintainer: open, type: bugfix

#8631 fdupes: Add missing deps and clean up
  sysutils/fdupes/Portfile
Labels: by: member, maintainer: requires approval

#8203 py-tensorflow, py-tensorflow1: fix for NumPy 1.19.x, use LTS JDK, legacysupport pg
  python/py-tensorflow/Portfile
  python/py-tensorflow/files/patch-numpy-1.19-fix.diff
  python/py-tensorflow1/Portfile
  python/py-tensorflow1/files/CLOCK_REALTIME-Older-OSX.patch
  python/py-tensorflow1/files/patch-numpy-1.19-fix.diff
Labels: maintainer: open, type: enhancement

#8635 tomcat-native: update to version 1.2.25
  java/tomcat-native/Portfile
Labels: maintainer, maintainer: open, type: update

#8634 py-questionary: update to 1.6.0
  python/py-questionary/Portfile
Labels: maintainer, maintainer: open, type: enhancement, type: update

#8632 annie: don't fetch dependencies in build phase
  net/annie/Portfile
Labels: by: member, maintainer: open, type: bugfix

#8425 jython: minor improvements
  lang/jython/Portfile
Labels: maintainer: open

#8633 fzf: don't fetch dependencies in build phase
  sysutils/fzf/Portfile
Labels: by: member, maintainer: open, type: bugfix

#8644 jenkins-cli: don't fetch dependencies in build phase
  devel/jenkins-cli/Portfile
Labels: by: member, maintainer: open, type: bugfix

#8590 py-cachelib: new port
  python/py-cachelib/Portfile
Labels: type: enhancement, type: submission

#8592 mackup: update to 0.8.29
  sysutils/mackup/Portfile
Labels: maintainer: open, type: enhancement, type: update

#8612 py-corner: update to 2.1.0
  python/py-corner/Portfile
Labels: maintainer: open, type: enhancement, type: update

#8643 dbeaver-community: update to 7.2.2
  databases/dbeaver-community/Portfile
Labels: maintainer, maintainer: open, type: update

#8642 topgrade: update to 5.8.0
  sysutils/topgrade/Portfile
Labels: maintainer, maintainer: open, type: update

#8640 hey: new port
  www/hey/Portfile
Labels: by: member, type: submission

#8646 Homebank : Update to version 5.4.3
  x11/homebank/Portfile
Labels: maintainer, maintainer: open, type: update

#8637 py-brotli: use a newer clang
  python/py-brotli/Portfile
Labels: maintainer: open, type: bugfix

#8587 py-tox: update to 3.20.0
  python/py-tox/Portfile
Labels: maintainer: open, type: update

#8615 pugixml: update to 1.10
  textproc/pugixml/Portfile
Labels: maintainer: open, type: bugfix, type: enhancement, type: update

#8588 py-roman: update to 3.3
  python/py-roman/Portfile
Labels: maintainer: open, type: update

#8589 py-boto3: update to 1.15.9
  python/py-boto3/Portfile
Labels: maintainer: open, type: update

#8650 syncthing: update to 1.10.0
  net/syncthing/Portfile
Labels: maintainer: open, type: bugfix, type: enhancement, type: update

#8649 py-brotli: Use MacPorts CXXFLAGS
  python/py-brotli/Portfile
  python/py-brotli/files/CXXFLAGS.patch
Labels: by: member, maintainer: open

#8654 syncthing: don't fetch dependencies in build phase
  net/syncthing/Portfile
Labels: by: member, maintainer: open, type: bugfix

#8658 gh: update to 1.1.0
  devel/gh/Portfile
Labels: by: member, maintainer: open, type: enhancement, type: update

#8653 kubeseal: update to 0.12.6
  sysutils/kubeseal/Portfile
Labels: maintainer, maintainer: open, type: enhancement, type: update

#8660 topgrade: update to 5.8.1
  sysutils/topgrade/Portfile
Labels: maintainer, maintainer: open, type: update

#8661 hugo: update to 0.76.0
  www/hugo/Portfile
Labels: maintainer, maintainer: open, type: update

#8657 py-commonmark: new port
  python/py-commonmark/Portfile
Labels: type: enhancement, type: submission

#8659 py-yaspin: new port
  python/py-yaspin/Portfile
Labels: type: enhancement, type: submission

#8610 github-backup: update to 0.36.0
  python/github-backup/Portfile
Labels: maintainer: open, type: enhancement, type: update

#8645 py-decli: new port
  python/py-decli/Portfile
Labels: type: enhancement, type: submission

#8665 topgrade: remove broken dependency on mas
  sysutils/topgrade/Portfile
Labels: maintainer, maintainer: open, type: bugfix

#8669 postgresql13: fix reference to psql12
  databases/postgresql13/Portfile
Labels: maintainer: requires approval, type: bugfix

#8664 py-json-tricks,pynetdicom,xlsxwriter: Updates
  python/py-XlsxWriter/Portfile
  python/py-json-tricks/Portfile
  python/py-pynetdicom/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#8670 nginx: install the manpage
  www/nginx/Portfile
Labels: maintainer: open, type: enhancement

#8652 plplot: add optional +deprecated variant
  science/plplot/Portfile
Labels: by: member, maintainer: open, type: enhancement

#8128 py-pyqt5: update to 5.15.1, pin to 5.14.2 for Qt5 < 5.11
  python/py-pyqt5/Portfile
  python/py-pyqt5/files/patch-dbus_includes.diff
  python/py-pyqt5/files/patch-qtwebengine-with-qt-5.14.diff
  python/py-pyqt5/files/patch-use-default-sip.diff
Labels: maintainer: none

#8666 commitizen: new port
  devel/commitizen/Portfile
Labels: type: enhancement, type: submission

#8639 lwan: new port
  www/lwan/Portfile
  www/lwan/files/org.macports.lwan.plist
Labels: by: member, type: submission

#8606 libsignal-protocol-c: new port
  devel/libsignal-protocol-c/Portfile
Labels: type: submission

#8662 cloudflared: submission
  net/cloudflared/Portfile
  net/cloudflared/files/config.yml
Labels: by: member, type: submission

#8668 keystore-explorer: update to 5.4.4
  security/keystore-explorer/Portfile
Labels: maintainer, maintainer: open, type: update

#8667 swi-prolog-devel: Updated to version 8.3.9
  lang/swi-prolog-devel/Portfile
Labels: maintainer, maintainer: open, type: bugfix, type: update

#8674 GPXSee: update to 7.33
  gis/GPXSee/Portfile
Labels: maintainer, maintainer: open, type: enhancement, type: update

#8677 py-arrow: update to 0.17.0
  python/py-arrow/Portfile
Labels: maintainer: none, type: enhancement, type: update

#8675 py-rich: new port
  python/py-rich/Portfile
Labels: type: enhancement, type: submission

#8678 py-igraph: update to 0.8.3
  python/py-igraph/Portfile
Labels: maintainer, maintainer: open, type: bugfix, type: enhancement, type: update

#8680 fzf: update to 0.23.0
  sysutils/fzf/Portfile
Labels: maintainer, maintainer: open, type: update

#8673 clojure: update to 1.10.1.708
  lang/clojure/Portfile
Labels: maintainer, maintainer: open, type: bugfix, type: update

#8681 google-cloud-sdk: update to 313.0.1
  devel/google-cloud-sdk/Portfile
Labels: maintainer, maintainer: open, type: update

#8679 hugo: update to 0.76.3
  www/hugo/Portfile
Labels: maintainer, maintainer: open, type: update

#8671 mycli: update to 1.22.2.
  databases/mycli/Portfile
  databases/mycli/files/patch-mycli_main.py.diff
Labels: maintainer, maintainer: open, type: update

#8629 cc65: update to 2.18
  lang/cc65/Portfile
Labels: maintainer: none, type: enhancement, type: update

#8349 xorg-scripts: Add support for Apple silicon
  x11/xorg-scripts/Portfile
  x11/xorg-scripts/files/apple-silicon.diff
Labels: maintainer: open, type: enhancement

#8350 xsetmode: Add support for Apple silicon
  x11/xsetmode/Portfile
  x11/xsetmode/files/apple-silicon.diff
Labels: maintainer: open, type: enhancement

#8620 Submission: py-fann2
  python/py-fann2/Portfile
Labels: type: enhancement, type: submission

#8683 kcov: use legacysupport portgroup for MAP_ANONYMOUS
  devel/kcov/Portfile
Labels: maintainer: none

#8638 py-fontaine: new port
  python/py-fontaine/Portfile
Labels: type: submission

#8672 octosql: new port
  databases/octosql/Portfile
  databases/octosql/files/patch-main-version.diff
Labels: by: member, type: submission

#8684 vigra: Default to python38 to match boost
  graphics/vigra/Portfile
Labels: by: member, maintainer: requires approval

#8071 qpid-proton: update to version 0.31.0
  net/qpid-proton/Portfile
Labels: maintainer: open, type: update

#8347 py-repoze.lru: add py3{7..9} subports
  python/py-repoze.lru/Portfile
Labels: maintainer: open, type: update

#8685 p5-ppix-regexp: update to version 0.075
  perl/p5-ppix-regexp/Portfile
Labels: by: member, maintainer: open, type: update

#8690 poppler: add boost variant
  graphics/poppler/Portfile
  graphics/poppler/files/patch-check-boost.diff
Labels: maintainer: open, type: bugfix

#8691 armadillo: uses C++11 and thread_local
  science/armadillo/Portfile
Labels: maintainer: open

#8702 mame: cleanup compilers
  emulators/mame/Portfile
Labels: maintainer: none

#8697 dlib: cleanup compilers
  math/dlib/Portfile
Labels: maintainer: none

#8704 xchm: cleanup compilers
  textproc/xchm/Portfile
Labels: maintainer: open

#8701 quassel: cleanup compilers
  irc/quassel/Portfile
Labels: maintainer: none

#8699 fish: cleanup compilers
  shells/fish/Portfile
Labels: maintainer: none

#8698 gdb: cleanup compilers
  devel/gdb/Portfile
Labels: maintainer: none

#8709 extractpdfmark: use compiler.cxx_standard 2011
  textproc/extractpdfmark/Portfile
Labels: maintainer: open

#8708 drupal7: update to 7.73
  www/drupal7/Portfile
Labels: maintainer: none, type: security fix, type: update

#8712 ipe: cleanup compilers
  graphics/ipe/Portfile
Labels: maintainer: none

#8705 cquery: remove port
  devel/cquery/Portfile
Labels: maintainer: open

#8710 seed: update to 4.0.0-20201009
  gnome/seed/Portfile
  gnome/seed/files/patch-modules-os-seed-os.c.diff
Labels: maintainer: none, type: update

#8706 poppler: use compiler.thread_local_storage yes
  graphics/poppler/Portfile
Labels: maintainer: open

#8693 py-cchardet: drop noarch, workaround GCC error
  python/py-cchardet/Portfile
Labels: maintainer: open

#8692 p5-graphviz2: update to version 2.54, dependencies
  perl/p5-graphviz2/Portfile
Labels: by: member, maintainer: open, type: update

#8711 nghttp2: cleanup compilers
  www/nghttp2/Portfile
Labels: maintainer: open

#8686 p5-pdl: update to version 2.024
  perl/p5-pdl/Portfile
  perl/p5-pdl/files/patch-implicit-declaration-gsl_set_error_handler_off.diff
Labels: by: member, maintainer: open, type: update

#8689 py-{atomiclong,cached-property,pygit2,raven}: add py39
  python/py-atomiclong/Portfile
  python/py-cached-property/Portfile
  python/py-pygit2/Portfile
  python/py-raven/Portfile
Labels: maintainer: open, type: update

#8722 py-cchardet: do not blacklist compilers
  python/py-cchardet/Portfile
Labels: maintainer: open

#8727 p5-future-asyncawait: drop noarch
  perl/p5-future-asyncawait/Portfile
Labels: maintainer: open

#8724 ntpsec: update to 1.2.0
  sysutils/ntpsec/Portfile
  sysutils/ntpsec/files/ntp.conf
  sysutils/ntpsec/files/patch-PreHighSierra.diff
Labels: maintainer, maintainer: open, type: update

#8729 p5-class-load-xs: drop noarch
  perl/p5-class-load-xs/Portfile
Labels: maintainer: none

#8728 p5-io-kqueue: drop noarch
  perl/p5-io-kqueue/Portfile
Labels: maintainer: none

#8733 sentencepiece: use compiler.thread_local_storage yes
  textproc/sentencepiece/Portfile
Labels: maintainer: none

#8731 p5-unicode-utf8: drop noarch
  perl/p5-unicode-utf8/Portfile
Labels: maintainer: none

#8723 kustomize: update to 3.8.5
  devel/kustomize/Portfile
Labels: maintainer, maintainer: open, type: update

#8730 knot: requires macOS 10.11 or later
  net/knot/Portfile
Labels: maintainer: open

#8746 octave-symbolic: remove +python35 variant
  math/octave-symbolic/Portfile
Labels: maintainer: open

#8676 util-linux: add bash-completion
  devel/util-linux/Portfile
Labels: maintainer: open, type: enhancement

#8726 py-ligo-segments: fix stub port
  python/py-ligo-segments/Portfile
Labels: maintainer: none

#8716 py-pycryptodome: drop noarch
  python/py-pycryptodome/Portfile
Labels: maintainer: open

#8758 eigen3: Update to 3.3.8
  math/eigen3/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#8737 python39: fix build on older systems
  lang/python39/Portfile
  lang/python39/files/patch-no-copyfile-on-Tiger.diff
  lang/python39/files/patch-threadid-older-systems.diff
Labels: by: member, maintainer: requires approval, type: bugfix

#8715 py-fann2: drop noarch
  python/py-fann2/Portfile
Labels: maintainer: open

#8751 gnome-dictionary: remove pre-activate
  gnome/gnome-dictionary/Portfile
Labels: maintainer: open

#8759 golang-1.0: handle dependencies from salsa.debian.org
  _resources/port1.0/group/golang-1.0.tcl
Labels: type: enhancement

#8748 lilypond: update devel version to 2.21.7
  textproc/lilypond/Portfile
Labels: maintainer: open, type: enhancement, type: update

#8761 gnss-sdr[-devel]: requires thread_local
  science/gnss-sdr/Portfile
Labels: maintainer: open

#8743 fzf: update to 0.23.1
  sysutils/fzf/Portfile
Labels: maintainer, maintainer: open, type: update
