Repository macports/macports-ports, pull requests merged in 2020-03, with the labels that each got.

#6470 go: backport upstream fix for AVX
  lang/go/Portfile
  lang/go/files/go-141-avx-fix.patch
Labels: by: member, maintainer: open, type: bugfix

#6483 nlohmann-json: update version to 3.7.3
  devel/nlohmann-json/Portfile
Labels: by: member, maintainer: open, type: update

#6414 bash: update to 5.0-16
  shells/bash/Portfile
Labels: maintainer: requires approval, type: enhancement, type: update

#6486 flyway: update to 6.2.4
  java/flyway/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#6485 ecs-cli: update to 1.18.1
  devel/ecs-cli/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#6487 kompose: update to 1.21.0
  devel/kompose/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#6490 py-pdbpp: new port
  python/py-pdbpp/Portfile
Labels: type: enhancement, type: submission

#6489 py-docker: update to 4.2.0
  python/py-docker/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#6493 rke: new port, v. 1.0.4
  devel/rke/Portfile
Labels: by: member, type: submission

#6491 py-wmctrl: new port
  python/py-wmctrl/Portfile
Labels: type: enhancement, type: submission

#6492 python38: fix build on older systems
  lang/python38/Portfile
  lang/python38/files/patch-no-copyfile-on-Tiger.diff
  lang/python38/files/patch-threadid-older-systems.diff
Labels: by: member, maintainer: none, type: bugfix

#6482 Py quantities: update version to 0.12.4 and add python 3.7 and 3.8 support
  python/py-quantities/Portfile
Labels: by: member, maintainer: open, type: update

#6498 bandwhich: update to 0.12.0
  net/bandwhich/Portfile
Labels: maintainer, maintainer: open, type: update

#6494 py-ansible: update to 2.9.5, add py38 support
  python/py-ansible/Portfile
  python/py-ansible/files/py38-ansible
Labels: maintainer: open, type: update

#6499 gh: update to 0.5.7
  devel/gh/Portfile
Labels: by: member, maintainer: open, type: update

#6500 alpine: update to version 2.22
  mail/alpine/Portfile
Labels: maintainer, maintainer: open, type: update

#6496 httpie: add python variants
  net/httpie/Portfile
Labels: maintainer: open, type: enhancement

#6505 logtalk: update to 3.36.0
  lang/logtalk/Portfile
Labels: maintainer, type: update

#6497 gildas: update to 202003b
  science/gildas/Portfile
  science/gildas/files/astro.in
  science/gildas/files/class.in
  science/gildas/files/clic.in
  science/gildas/files/greg.in
  science/gildas/files/imager.in
  science/gildas/files/mapping.in
  science/gildas/files/mira.in
  science/gildas/files/mrtcal.in
  science/gildas/files/patch-admin-Makefile.build.diff
  science/gildas/files/sched-30m.in
  science/gildas/files/sic.in
Labels: maintainer, type: update

#6511 google-cloud-sdk: update to 283.0.0
  devel/google-cloud-sdk/Portfile
Labels: maintainer, maintainer: open, type: update

#6510 lazygit: update to 0.16
  devel/lazygit/Portfile
Labels: maintainer, maintainer: open, type: update

#6509 k9s: update to 0.17.3
  sysutils/k9s/Portfile
Labels: maintainer, maintainer: open, type: update

#6506 starship: update to 0.37.0
  sysutils/starship/Portfile
Labels: maintainer, maintainer: open, type: update

#6513 docker: update to 19.03.7
  devel/docker/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#6514 kotlin: update to 1.3.70
  lang/kotlin/Portfile
Labels: maintainer, maintainer: open, type: update

#6508 cfm: update to 0.6.0
  sysutils/cfm/Portfile
Labels: maintainer: requires approval, type: bugfix, type: enhancement, type: update

#6516 swi-prolog-devel: update to 8.1.24
  lang/swi-prolog-devel/Portfile
Labels: maintainer, type: update

#6502 chromedriver: Update to version 81, provide support for recent versions
  www/chromedriver/Portfile
Labels: maintainer: none, type: update

#6517 R: update to 3.6.3
  math/R/Portfile
Labels: maintainer: requires approval, type: update

#6518 gh: update to 0.6.1
  devel/gh/Portfile
Labels: maintainer: open, type: update

#6519 hugo: update to 0.66.0
  www/hugo/Portfile
Labels: maintainer, maintainer: open, type: update

#6512 lilypond: update to version 2.20.0
  textproc/lilypond/Portfile
  textproc/lilypond/files/patch-scripts-build-mf2pt1.pl.diff
Labels: maintainer: open, type: update

#6521 k9s: update to 0.17.4
  sysutils/k9s/Portfile
Labels: maintainer, maintainer: open, type: update

#6523 flyway: update to 6.3.0
  java/flyway/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#6504 Per issue 60156 - patch app.vala to build with newer vala in macports
  gnome/vte/Portfile
  gnome/vte/files/patch-app-vala.diff
Labels: maintainer: open

#6524 qri: update to 0.9.6
  devel/qri/Portfile
Labels: maintainer, maintainer: open, type: update

#6526 vault: update to 1.3.3
  security/vault/Portfile
Labels: maintainer, maintainer: open, type: update

#6525 terraform-0.12: update to 0.12.23
  sysutils/terraform/Portfile
Labels: maintainer, maintainer: open, type: update

#6522 rancher-cli: new port, v. 2.4.0-rc4
  devel/rancher-cli/Portfile
Labels: by: member, type: submission

#6530 buildbot: update to 2.7.0
  devel/buildbot-2/Portfile
  devel/buildbot-worker/Portfile
  python/py-buildbot-console-view/Portfile
  python/py-buildbot-grid-view/Portfile
  python/py-buildbot-pkg/Portfile
  python/py-buildbot-waterfall-view/Portfile
  python/py-buildbot-www/Portfile
  python/py-buildbot/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#6527 bali-phy: update to 3.5.0.1
  science/bali-phy/Portfile
  science/bali-phy/files/patch-bp_analyze.diff
Labels: by: member, maintainer: open, type: update

#6533 syncthing: update to 1.3.4
  net/syncthing/Portfile
Labels: maintainer: open, type: bugfix, type: update

#6531 antlr4-cpp-runtime: new port, v. 4.8
  lang/antlr4-cpp-runtime/Portfile
Labels: by: member, type: submission

#6536 zabbix4*: Update to 4.0.18, 4.4.6
  net/zabbix4/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#6459 ghc: Update to version 8.8.3
  lang/ghc/Portfile
Labels: maintainer, maintainer: open, type: enhancement, type: update

#6537 k9s: update to 0.17.5
  sysutils/k9s/Portfile
Labels: maintainer, maintainer: open, type: update

#6534 itstool: add python38 variant
  textproc/itstool/Portfile
Labels: maintainer: open, type: bugfix

#6529 munin: upgrade to 2.0.56, remove obsolete patches
  net/munin/Portfile
  net/munin/files/patch-Makefile-javaplugin
  net/munin/files/patch-Makefile.config
  net/munin/files/patch-encodings.diff
Labels: maintainer: none

#6541 groovy: update to 3.0.2
  lang/groovy/Portfile
Labels: maintainer, maintainer: open, type: update

#6545 fricas: update to 1.3.6
  math/fricas/Portfile
Labels: maintainer, type: update

#6546 BWidget: update to 1.9.14
  x11/BWidget/Portfile
Labels: maintainer: none, type: bugfix, type: enhancement, type: update

#6547 hugo: update to 0.67.0
  www/hugo/Portfile
Labels: maintainer, maintainer: open, type: update

#5834 multiple X.Org ports: remove obsolete ports
  x11/xorg-applewmproto/Portfile
  x11/xorg-bigreqsproto/Portfile
  x11/xorg-compositeproto/Portfile
  x11/xorg-damageproto/Portfile
  x11/xorg-dmxproto/Portfile
  x11/xorg-dri2proto/Portfile
  x11/xorg-dri3proto/Portfile
  x11/xorg-evieproto/Portfile
  x11/xorg-fixesproto/Portfile
  x11/xorg-fontcacheproto/Portfile
  x11/xorg-fontsproto/Portfile
  x11/xorg-glproto/Portfile
  x11/xorg-inputproto/Portfile
  x11/xorg-kbproto/Portfile
  x11/xorg-presentproto/Portfile
  x11/xorg-printproto/Portfile
  x11/xorg-randrproto/Portfile
  x11/xorg-recordproto/Portfile
  x11/xorg-renderproto/Portfile
  x11/xorg-resourceproto/Portfile
  x11/xorg-scrnsaverproto/Portfile
  x11/xorg-trapproto/Portfile
  x11/xorg-videoproto/Portfile
  x11/xorg-xcmiscproto/Portfile
  x11/xorg-xextproto/Portfile
  x11/xorg-xf86bigfontproto/Portfile
  x11/xorg-xf86dgaproto/Portfile
  x11/xorg-xf86driproto/Portfile
  x11/xorg-xf86miscproto/Portfile
  x11/xorg-xf86vidmodeproto/Portfile
  x11/xorg-xineramaproto/Portfile
  x11/xorg-xproto/Portfile
  x11/xorg-xproxymanagementprotocol/Portfile
Labels: maintainer: open

#6544 gobject-introspection: update to 1.60.2
  gnome/gobject-introspection/Portfile
  gnome/gobject-introspection/files/no-env-shebang.patch
  gnome/gobject-introspection/files/patch-fix-rpath-gir-typelib.diff
  gnome/gobject-introspection/files/patch-girscanner-tiger-no-rpath.diff
Labels: by: member, maintainer: open, type: bugfix, type: enhancement, type: update

#6548 gtk3 +quartz: Fix building on case-sensitive file systems
  gnome/gtk3/Portfile
  gnome/gtk3/files/patch-gdkquartz-gtk-only.diff
Labels: maintainer: open, type: bugfix

#6551 micronaut: update to 1.3.3
  java/micronaut/Portfile
Labels: maintainer, maintainer: open, type: update

#6550 google-cloud-sdk: update to 284.0.0
  devel/google-cloud-sdk/Portfile
Labels: maintainer, maintainer: open, type: update

#6520 radare2: update to 4.3.0
  devel/radare2/Portfile
Labels: by: member, maintainer: open, type: update

#6552 k9s: update to 0.17.6
  sysutils/k9s/Portfile
Labels: maintainer, maintainer: open, type: update

#6553 p5-tcl-ptk: update to version 1.06
  perl/p5-tcl-ptk/Portfile
Labels: by: member, maintainer: open, type: update

#6555 docker: update to 19.03.8
  devel/docker/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#6557 lazygit: update to 0.16.2
  devel/lazygit/Portfile
Labels: maintainer, maintainer: open, type: update

#6554 radare2: update to 4.3.1
  devel/radare2/Portfile
Labels: maintainer, maintainer: open, type: update

#6251 gift: Delete ancient unbuildable port
  net/gift/Portfile
Labels: by: member, maintainer: none

#6561 libuv: restore patch that works on v1.30
  devel/libuv/Portfile
  devel/libuv/files/patch-libuv-130-unix-core-close-nocancel.diff
Labels: by: member, maintainer: open

#6565 libuv: fix universal build
  devel/libuv/files/patch-libuv-unix-core-close-nocancel.diff
Labels: by: member, maintainer: open

#6566 p5-tcl-ptk: update to 1.07
  perl/p5-tcl-ptk/Portfile
Labels: maintainer, maintainer: open, type: bugfix, type: enhancement, type: update

#6569 k9s: update to 0.17.7
  sysutils/k9s/Portfile
Labels: maintainer, maintainer: open, type: update

#6568 igraph: update to 0.8.1
  math/igraph/Portfile
Labels: maintainer: open, type: bugfix, type: update

#6560 libomp: Use canonical llvm-project github account.
  lang/libomp/Portfile
Labels: by: member, maintainer, maintainer: open

#6567 [volk-]gnss-sdr: Update to v0.0.12
  science/gnss-sdr/Portfile
  science/gnss-sdr/files/patch-gtest-c++11.diff
  science/volk-gnss-sdr/Portfile
Labels: maintainer, maintainer: open, type: update

#6575 codesearch: move to releases.
  devel/codesearch/Portfile
Labels: by: member, maintainer: none

#6576 py-htmldocs: Update to latest versions.
  lang/py-htmldocs/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#6574 zabbix/zabbix2: remove old ports and point to 44
  net/zabbix/Portfile
  net/zabbix/files/patch-src-zabbix_server-poller-checks_snmp.c.diff
  net/zabbix/files/zabbix_agentd.init
  net/zabbix/files/zabbix_server.init
  net/zabbix2/Portfile
  net/zabbix2/files/zabbix_server.init
  net/zabbix2/files/zabbix_server.init.mysql
Labels: by: member, maintainer, maintainer: open

#6577 rclone: Update to 1.51.0
  net/rclone/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#6535 py-gpilab-*: Update to latest.
  python/py-gpilab-core/Portfile
  python/py-gpilab-core/files/math_fft_PyMOD_cpp.patch
  python/py-gpilab-framework/Portfile
  python/py-gpilab-framework/files/gpilab-38
  python/py-json-tricks/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#6578 minio[-mc]: Update to latest
  www/minio-mc/Portfile
  www/minio/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#6579 pam-google-authenticator: Update to 1.08
  security/pam-google-authenticator/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#6582 tk +quartz: add patch to fix unresponsive menus
  x11/tk/Portfile
  x11/tk/files/patch-macosx-tkMacOSXInit.c.diff
Labels: maintainer: open, type: bugfix

#6586 ntp: update to 4.2.8p14
  sysutils/ntp/Portfile
Labels: by: member, maintainer: requires approval, type: update

#6584 poppler: Fix upstream issue #893
  graphics/poppler/Portfile
  graphics/poppler/files/patch-upstream-issue-893.diff
Labels: maintainer: open, type: bugfix

#6571 rust: update to 1.42.0
  lang/rust/Portfile
Labels: maintainer: open, type: update

#6594 wtfutil: update to 0.28.0
  sysutils/wtfutil/Portfile
Labels: maintainer, maintainer: open, type: update

#6581 libsdl2: bugfix sdl2-config.cmake file
  devel/libsdl2/Portfile
  devel/libsdl2/files/sdl2-config.cmake.in-fix.patch
Labels: maintainer: open, type: bugfix

#6596 syncthing: update to 1.4.0
  net/syncthing/Portfile
Labels: maintainer: open, type: bugfix, type: enhancement, type: update

#6604 commons-launcher: delete port
  java/commons-launcher/Portfile
Labels: maintainer: none

#6549 jakarta-bcel, jakarta-regexp: delete ports
  java/jakarta-bcel/Portfile
  java/jakarta-regexp/Portfile
Labels: maintainer: none

#6564 py-jupytext: new port
  python/py-jupytext/Portfile
Labels: type: enhancement, type: submission

#6602 uni: update to 1.1.0
  textproc/uni/Portfile
Labels: maintainer, maintainer: open, type: update

#6599 consul: update to 1.7.2
  net/consul/Portfile
Labels: maintainer, maintainer: open, type: update

#6597 hugo: update to 0.67.1
  www/hugo/Portfile
Labels: maintainer, maintainer: open, type: update

#6598 fzf: update to 0.21.0-1
  sysutils/fzf/Portfile
Labels: maintainer, maintainer: open, type: update

#6570 broot: update to 0.13.4
  sysutils/broot/Portfile
Labels: maintainer, maintainer: open, type: update

#6583 terminus-font: use python 3.8
  x11/terminus-font/Portfile
Labels: maintainer, maintainer: open

#6603 miller: update to 5.7.0
  textproc/miller/Portfile
Labels: maintainer, maintainer: open, type: update

#6606 bedtools: update to v2.29.2
  science/bedtools/Portfile
  science/bedtools/files/patch-src-utils-BamTools-include-BamAlignment.hpp.diff
  science/bedtools/files/patch-src-utils-BamTools-include-SamHeader.hpp.diff
Labels: maintainer, maintainer: open, type: update

#6573 rtags: update to 2.38
  devel/rtags/Portfile
Labels: maintainer: none, type: update

#6618 flyway: update to 6.3.1
  java/flyway/Portfile
Labels: maintainer, maintainer: open, type: update

#6624 db44: remove obsolete port
  databases/db44/Portfile
  www/redland/Portfile
Labels: maintainer: none

#6631 OpenBLAS: update to version 0.3.9
  math/OpenBLAS/Portfile
Labels: by: member, maintainer, maintainer: open, type: enhancement, type: update

#6620 bedtools: rename "version" to avoid clash with STL
  science/bedtools/Portfile
  science/bedtools/files/patch-rename-version.diff
Labels: maintainer, maintainer: open

#6608 new port: gore
  devel/gore/Portfile
Labels: type: submission

#6622 Gitlab portgroup
  _resources/port1.0/group/gitlab-1.0.tcl
Labels: by: member, maintainer: requires approval

#6621 openssl: update to 1.1.1e, including bug and security fixes
  devel/openssl/Portfile
Labels: by: member, maintainer: open, type: security fix, type: update

#6635 lazygit: update to 0.17.1
  devel/lazygit/Portfile
Labels: maintainer, maintainer: open, type: update

#6634 terraform-0.12: update to 0.12.24
  sysutils/terraform/Portfile
Labels: maintainer, maintainer: open, type: update

#6637 flyway: use Java portgroup
  java/flyway/Portfile
Labels: maintainer: open, type: enhancement

#6623 openjdk8: add OpenJDK 14 subports
  java/openjdk8/Portfile
Labels: maintainer, maintainer: open

#6628 qtoctave-mac: remove obsolete port
  aqua/qtoctave-mac/Portfile
Labels: maintainer: none

#6630 syncthing-0.14: remove obsolete port
  net/syncthing-0.14/Portfile
Labels: maintainer: none

#6629 open-cobol: remove obsolete port
  lang/open-cobol/Portfile
Labels: maintainer: none

#6638 vault: update to 1.3.4
  security/vault/Portfile
Labels: maintainer, maintainer: open, type: update

#6585 FAudio: Update to 20.03
  audio/FAudio/Portfile
Labels: maintainer: none, type: enhancement, type: update

#6600 smartmontools: update to 7.1
  sysutils/smartmontools/Portfile
Labels: by: member, maintainer: open, type: update

#6639 wireguard-tools: update to 1.0.20200319
  net/wireguard-tools/Portfile
Labels: maintainer, maintainer: open, type: update

#6641 tor: update to 0.4.2.7
  security/tor/Portfile
Labels: maintainer: none, type: update

#6642 tor-devel: update to 0.4.3.3-alpha
  security/tor-devel/Portfile
Labels: maintainer: none, type: update

#6540 neofetch: update to 7.0
  sysutils/neofetch/Portfile
Labels: maintainer: open, type: update

#6625 gh: update to 0.6.2
  devel/gh/Portfile
Labels: maintainer: open, type: update

#6640 go: update to 1.14.1
  lang/go/Portfile
  lang/go/files/go-141-avx-fix.patch
Labels: maintainer: open, type: update

#6644 eigen3[-devel]: Use new gitlab pg.
  math/eigen3/Portfile
Labels: by: member, maintainer, maintainer: open

#6572 cargo: update to 0.43.0
  devel/cargo/Portfile
Labels: maintainer: none, type: update

#6647 fantom: drop maintainer
  java/fantom/Portfile
Labels: maintainer: requires approval

#6649 Updated Port lttoolbox to version 3.5.0
  textproc/lttoolbox/Portfile
Labels: maintainer: none

#6643 junit: update to 4.13
  java/junit/Portfile
Labels: maintainer: none, type: update

#6636 jmol: use Java portgroup
  science/jmol/Portfile
Labels: maintainer: open, type: enhancement

#6650 knock: new port
  net/knock/Portfile
Labels: by: member, type: submission

#6651 redis: update to 5.0.8
  databases/redis/Portfile
Labels: maintainer, maintainer: open, type: enhancement, type: update

#6627 py-pynetdicom3: remove obsolete port
  python/py-pynetdicom3/Portfile
Labels: maintainer: none

#6655 asciidoc: update version and Python
  textproc/asciidoc/Portfile
Labels: by: member, maintainer: open, type: enhancement, type: update

#6654 caf: allow build on older systems
  devel/caf/Portfile
Labels: by: member, maintainer: open, type: bugfix

#6645 gnu-classpathx-javamail: delete port
  java/gnu-classpathx-javamail/Portfile
  java/gnu-classpathx-javamail/files/patch-PrintStreamLogger.java
Labels: maintainer: none

#6659 swi-prolog-devel: update to 8.1.25
  lang/swi-prolog-devel/Portfile
Labels: maintainer, type: update

#6539 luaradio: new port, version 0.6.1
  science/luaradio/Portfile
  science/luaradio/files/wrapper.sh
Labels: type: enhancement, type: submission

#6660 gnu-classpathx-activation: delete port
  java/gnu-classpathx-activation/Portfile
Labels: maintainer: none

#6658 gnu-classpathx-comm: delete port
  java/gnu-classpathx-comm/Portfile
Labels: maintainer: none

#6633 castor: update homepage
  java/castor/Portfile
Labels: maintainer: none, type: update

#6661 lazygit: update to 0.17.2
  devel/lazygit/Portfile
Labels: maintainer, maintainer: open, type: update

#6657 gitlab-runner: update to 12.9.0
  devel/gitlab-runner/Portfile
Labels: maintainer, maintainer: open, type: update

#6619 auto-multiple-choice-devel: update to version 1.4.0-201912050859
  x11/auto-multiple-choice/Portfile
  x11/auto-multiple-choice/files/patch-cupslp-pm-684.diff
Labels: maintainer, maintainer: open, type: bugfix, type: enhancement, type: update

#6663 py-applaunchservices: add subport for Python 3.8
  python/py-applaunchservices/Portfile
Labels: by: member, maintainer: open, type: enhancement

#6667 directory-studio: update livecheck regex
  databases/directory-studio/Portfile
Labels: maintainer, maintainer: open, type: bugfix, type: update

#6666 py-numpy: update to 1.18.2 and 1.16.4 (PY27)
  python/py-numpy/Portfile
Labels: by: member, maintainer: open, type: update

#6669 wireguard-go: update to 0.0.20200320
  net/wireguard-go/Portfile
Labels: maintainer, maintainer: open, type: update

#6648 starship: update to 0.38.0
  sysutils/starship/Portfile
Labels: maintainer, maintainer: open, type: update

#6671 drupal8: update to 8.7.12
  www/drupal8/Portfile
Labels: maintainer: none, type: bugfix, type: security fix, type: update

#6670 drupal7: update to 7.69
  www/drupal7/Portfile
Labels: maintainer: none, type: bugfix, type: enhancement, type: security fix, type: update

#6668 dbeaver-community: update to 7.0.0
  databases/dbeaver-community/Portfile
  databases/dbeaver-community/files/openjdk8.patch
Labels: maintainer, maintainer: open, type: update

#6677 gsmartcontrol: update to 1.1.3
  sysutils/gsmartcontrol/Portfile
Labels: by: member, maintainer: open, type: enhancement, type: update

#6678 hugo: update to 0.68.1
  www/hugo/Portfile
Labels: maintainer, maintainer: open, type: update
