Repository macports/macports-ports, pull requests merged in 2020-11, with the labels that each got.

#9007 p5-graphviz2: update to version 2.59, dependencies
  perl/p5-graphviz2/Portfile
Labels: by: member, maintainer: open, type: update

#9009 Revbump leftovers from GCC symlink fix
  lang/apple-gcc42/Portfile
  lang/apple-gcc42/files/apple-gcc42
  lang/llvm-gcc42/Portfile
  lang/llvm-gcc42/files/mp-llvm-gcc42
Labels: maintainer: requires approval, type: bugfix

#9010 xorg-server-devel: bring up to 1.20.9
  x11/xorg-server-devel/Portfile
  x11/xorg-server-devel/files/0001-xquartz-Add-stub-ddxInputThread.patch
  x11/xorg-server-devel/files/5007-patch-randr-randrstr-h-dont-redefine-CARD32.diff
  x11/xorg-server-devel/files/Darwin19-Remove-AppFlags-Active-Hack.patch
Labels: by: member, maintainer: open, type: enhancement

#9013 lilypond: update devel version to 2.21.80
  textproc/lilypond/Portfile
Labels: maintainer: open, type: enhancement, type: update

#9016 Gildas: update to 202011a
  science/gildas/Portfile
Labels: maintainer, type: update

#9015 dbeaver-community: update to 7.2.4
  databases/dbeaver-community/Portfile
Labels: maintainer, maintainer: open, type: update

#9012 packr: new port
  devel/packr/Portfile
Labels: by: member, type: submission

#8985 gobject-introspection: tweak scanner patch
  gnome/gobject-introspection/Portfile
  gnome/gobject-introspection/files/patch-fix-scanner-in-build-execution.diff
Labels: by: member, maintainer: open

#9018 textproc/qpdf: trivial update to 10.0.3
  textproc/qpdf/Portfile
Labels: by: member, maintainer: none

#8983 wireshark3: update to 3.4.0
  net/wireshark3/Portfile
Labels: by: member, maintainer: requires approval, maintainer: timeout, type: update

#8991 vcs_blackbox: update to 1.20200429
  security/vcs_blackbox/Portfile
Labels: maintainer: open, maintainer: timeout, type: update

#9023 google-cloud-sdk: update to 317.0.0
  devel/google-cloud-sdk/Portfile
Labels: maintainer, maintainer: open, type: update

#9024 fzf: update to 0.24.2
  sysutils/fzf/Portfile
Labels: maintainer, maintainer: open, type: update

#9021 sops: new port
  security/sops/Portfile
Labels: by: member, type: submission

#8968 qgis: cleanup compilers
  gis/qgis/Portfile
Labels: maintainer: requires approval, maintainer: timeout

#9027 swi-prolog-devel: Updated to version 8.3.11
  lang/swi-prolog-devel/Portfile
Labels: maintainer, maintainer: open, type: update

#9003 lwp-useragent-cached: submission of new port (v0.08)
  perl/p5-lwp-useragent-cached/Portfile
Labels: type: submission

#9032 py-h5py: Update (py36+ only) to 3.0.0
  python/py-h5py/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#9033 pydicom: update to 2.1.0
  python/py-pydicom/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#9034 k9s: update to 0.23.4
  sysutils/k9s/Portfile
Labels: maintainer, maintainer: open, type: update

#8688 xournalpp: submission
  x11/xournalpp/Portfile
Labels: type: enhancement, type: submission

#8996 httpie: add python39 variant
  net/httpie/Portfile
Labels: maintainer: open, type: enhancement

#9035 SilentKnight: update to 1.12
  sysutils/SilentKnight/Portfile
Labels: maintainer, maintainer: open, type: update

#9040 py-numpy: update to 1.19.4
  python/py-numpy/Portfile
Labels: by: member, maintainer, maintainer: open, type: enhancement, type: update

#9045 py-wntr: update to version 0.3.0
  python/py-wntr/Portfile
Labels: maintainer, maintainer: open, type: enhancement

#9044 k9s: update to 0.23.7
  sysutils/k9s/Portfile
Labels: maintainer, maintainer: open, type: update

#9043 micronaut: update to 2.1.3
  java/micronaut/Portfile
Labels: maintainer, maintainer: open, type: update

#9036 topgrade: update to 5.9.0
  sysutils/topgrade/Portfile
Labels: maintainer, maintainer: open, type: update

#9041 p5-graphviz2: update to version 2.60
  perl/p5-graphviz2/Portfile
Labels: by: member, maintainer: open, type: update

#9046 ox: new port
  editors/ox/Portfile
Labels: by: member, type: submission

#9029 py-httpcore: new port
  python/py-httpcore/Portfile
Labels: by: member, type: submission

#9008 youtube-dl: update to 2020.11.01.1
  net/youtube-dl/Portfile
  net/youtube-dl/files/patch-youtube_dl-update.py.diff
Labels: maintainer: requires approval, type: update

#9050 k9s: update to 0.23.9
  sysutils/k9s/Portfile
Labels: maintainer, maintainer: open, type: update

#9056 syncthing: update to 1.11.1
  net/syncthing/Portfile
Labels: maintainer: open, type: bugfix, type: enhancement, type: update

#9060 py-rich: update to 9.2.0
  python/py-rich/Portfile
Labels: maintainer, maintainer: open, type: enhancement, type: update

#9058 py-questionary: update to 1.8.0
  python/py-questionary/Portfile
Labels: maintainer, maintainer: open, type: enhancement, type: update

#9063 argyll: fix for macOS 10.15 (backwards-compatible)
  graphics/argyll/Portfile
  graphics/argyll/files/patch-obj_msgSend.diff
Labels: by: member, maintainer, maintainer: open

#9038 SDRangel: update to 4.21.1
  science/SDRangel/Portfile
  science/SDRangel/files/revert_cm256cc.patch
Labels: by: member, maintainer, maintainer: open, type: enhancement, type: update

#9064 mtools: Update to 4.0.25
  sysutils/mtools/Portfile
  sysutils/mtools/files/implicit.patch
Labels: by: member, maintainer: requires approval, type: update

#9059 promu: update to 0.7.0
  devel/promu/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#9062 notmuch: update to 0.31.2
  mail/notmuch/Portfile
  mail/notmuch/files/realpath.patch
  mail/notmuch/files/version.patch
Labels: maintainer, maintainer: open, type: update

#9039 py-scipy: update to 1.5.4
  python/py-scipy/Portfile
  python/py-scipy/files/patch-fix_implicit_functions_for_Xcode_12.diff
Labels: by: member, maintainer, maintainer: open, type: enhancement, type: update

#9061 t-rec: new port
  sysutils/t-rec/Portfile
Labels: by: member, type: submission

#9042 iTerm2: disable automatic update functionality
  aqua/iTerm2/Portfile
  aqua/iTerm2/files/patch-nsur.diff
  aqua/iTerm2/files/patch-remove-sparkle.diff
Labels: maintainer: open, type: enhancement

#9068 nvm: update to 0.37.0
  devel/nvm/Portfile
Labels: maintainer: open, type: enhancement, type: update

#9069 k9s: update to 0.23.10
  sysutils/k9s/Portfile
Labels: maintainer, maintainer: open, type: update

#9070 google-cloud-sdk: update to 318.0.0
  devel/google-cloud-sdk/Portfile
Labels: maintainer, maintainer: open, type: update

#9019 nnn: update to 3.4
  sysutils/nnn/Portfile
Labels: by: member, maintainer: open, type: update

#9048 lrzsz: fix implicit declaration errors macOS 11
  comms/lrzsz/Portfile
  comms/lrzsz/files/implicit.patch
Labels: maintainer: none, type: bugfix

#8836 vtk: Fix FT_CALLBACK_DEF with updated freetype
  graphics/vtk/Portfile
  graphics/vtk/files/patch-FT_CALLBACK_DEF.diff
Labels: maintainer, maintainer: open, type: bugfix

#9076 py-django: update to 2.2.17, add dep py-sqlparse
  python/py-django/Portfile
Labels: maintainer: open, type: security fix, type: update

#9077 helm: update to 3.4.1
  sysutils/helm/Portfile
Labels: by: member, maintainer: open, type: update

#9079 kubectl: fix for older systems
  sysutils/kubectl/Portfile
Labels: by: member, maintainer: open, type: bugfix

#9081 folderify: update to 2.0.0
  sysutils/folderify/Portfile
Labels: maintainer, maintainer: open, type: enhancement, type: update

#9073 topgrade: update to 5.9.1
  sysutils/topgrade/Portfile
Labels: maintainer, maintainer: open, type: update

#9072 SilentKnight: update to 1.13
  sysutils/SilentKnight/Portfile
Labels: maintainer, maintainer: open, type: update

#9017 Arduino: update to 1.8.13
  devel/Arduino/Portfile
Labels: maintainer: open, type: enhancement, type: update

#9082 GPXSee: update to 7.36
  gis/GPXSee/Portfile
Labels: maintainer, maintainer: open, type: enhancement, type: update

#9080 py27-pandas: fix implicit function declaration
  python/py-pandas/Portfile
  python/py-pandas/files/patch-a3c158dad2.diff
Labels: maintainer: open

#9083 kustomize: update to 3.8.7
  devel/kustomize/Portfile
Labels: maintainer, maintainer: open, type: update

#9084 folderify: update to 2.0.2
  sysutils/folderify/Portfile
Labels: maintainer, maintainer: open, type: enhancement, type: update

#9086 mongo-cxx-driver: attempt to fix macOS 10.9 build
  devel/mongo-cxx-driver/Portfile
Labels: maintainer: open

#9089 py-pymc: remove obsolete port
  python/py-pymc/Portfile
Labels: maintainer: none

#9088 mfa: new port
  security/mfa/Portfile
Labels: by: member, type: submission

#9091 rzip64: New port, version 3.0
  archivers/rzip64/Portfile
  archivers/rzip64/files/Makefile.in.patch
  archivers/rzip64/files/runzip.c.patch
  archivers/rzip64/files/rzip64.h.patch
Labels: by: member, type: submission

#9094 fzf: update to 0.24.3
  sysutils/fzf/Portfile
Labels: maintainer, maintainer: open, type: update

#9093 hugo: update to 0.78.2
  www/hugo/Portfile
Labels: maintainer, maintainer: open, type: update

#9095 weechat: update to 3.0
  irc/weechat/Portfile
Labels: maintainer, maintainer: open, type: update

#9096 fsdb: update to 2.70
  perl/fsdb/Portfile
Labels: maintainer, maintainer: open, type: update

#9097 minikube: update to 1.15.0
  sysutils/minikube/Portfile
Labels: by: member, maintainer: open, type: update

#9101 commitizen: update to 2.7.0
  devel/commitizen/Portfile
Labels: maintainer, maintainer: open, type: enhancement, type: update

#9107 ccaudio: remove obsolete port
  audio/ccaudio/Portfile
Labels: maintainer: none

#9102 bro: remove obsolete port
  net/bro/Portfile
Labels: maintainer: none

#9109 rspamd: Update to version 2.6
  mail/rspamd/Portfile
Labels: maintainer: none, type: enhancement, type: update

#9103 KeePassXC-devel: remove obsolete port
  security/KeePassXC-devel/Portfile
Labels: maintainer: none

#9106 npm2: remove obsolete port
  devel/npm2/Portfile
  devel/npm2/files/patch-lib-update.js.diff
Labels: maintainer: none

#9110 pinentry: fix build on Big Sur
  security/pinentry/Portfile
Labels: maintainer: open, type: bugfix

#9108 apache-solr8: Update to version 8.7.0, use LTS JDK fallback
  java/apache-solr8/Portfile
Labels: maintainer, maintainer: open, type: enhancement, type: update

#9100 p5-extutils-makemaker: update to 7.54
  perl/p5-extutils-makemaker/Portfile
Labels: maintainer: none, type: update

#9085 pinentry-mac: fix implicit function declaration
  aqua/pinentry-mac/Portfile
  aqua/pinentry-mac/files/patch-includes-quotes-2.diff
Labels: maintainer: requires approval

#9074 virtualenv: update to 20.1.0 and py39
  python/py-virtualenv/Portfile
  python/py-virtualenv/files/virtualenv39
Labels: maintainer: open, type: enhancement, type: update

#9099 p5-tk-dynatabframe: new port
  perl/p5-tk-dynatabframe/Portfile
Labels: type: submission

#9111 py-zope-*: remove pre-activate
  python/py-zope-deferredimport/Portfile
  python/py-zope-deprecation/Portfile
  python/py-zope-hookable/Portfile
  python/py-zope-proxy/Portfile
Labels: maintainer: open

#9113 spring-boot-cli: update to 2.4.0
  java/spring-boot-cli/Portfile
Labels: maintainer, maintainer: open, type: update

#9124 ioping: new port
  devel/ioping/Portfile
Labels: type: enhancement, type: submission

#9122 folderify: update to 2.1.0
  sysutils/folderify/Portfile
Labels: maintainer, maintainer: open, type: enhancement, type: update

#9121 commitizen: update to 2.8.0
  devel/commitizen/Portfile
Labels: maintainer, maintainer: open, type: enhancement, type: update

#9123 java-1.0 portgroup: temporarily skip exact version check on Big Sur
  _resources/port1.0/group/java-1.0.tcl
Labels: by: member, type: bugfix

#9119 jbig2dec: update to 0.19
  graphics/jbig2dec/Portfile
Labels: maintainer: none, type: update

#9133 libhsplasma: cleanup pre-activate
  devel/libhsplasma/Portfile
Labels: maintainer: requires approval

#9129 xgalaga: cleanup pre-activate
  games/xgalaga/Portfile
Labels: maintainer: none

#9112 duti: update patch for Big Sur
  sysutils/duti/files/mojave.diff
Labels: maintainer: open, type: bugfix, type: update

#9127 libranlib: cleanup pre-activate
  math/libranlib/Portfile
Labels: maintainer: none

#9132 nedi: cleanup pre-activate
  net/nedi/Portfile
Labels: maintainer: none

#9126 rb-rubygems: cleanup pre-activate
  ruby/rb-rubygems/Portfile
Labels: maintainer: none

#9134 qtiplot: cleanup pre-activate
  aqua/qtiplot/Portfile
Labels: maintainer: open

#9118 ghostscript: update to v9.53.3
  print/ghostscript-fonts-hiragino/Portfile
  print/ghostscript/Portfile
  print/ghostscript/files/ghostpdl.git-06c920713e11.patch
  print/ghostscript/files/patch-6756b355c238.diff
Labels: maintainer: none, type: update

#9131 ioping: drop noarch, change category
  sysutils/ioping/Portfile
Labels: maintainer, maintainer: open, type: enhancement

#9137 e2fsprogs: Fix build with Big Sur
  sysutils/e2fsprogs/Portfile
  sysutils/e2fsprogs/files/patch-probe.c.diff
Labels: maintainer: open, type: bugfix

#9115 p5-tk-idelayout: new port
  perl/p5-tk-idelayout/Portfile
Labels: type: submission

#9136 stack: Update to version 2.5.1
  lang/stack/Portfile
  lang/stack/files/keyid-1c5c154d.txt
  lang/stack/files/keyid-575159689befb442.txt
Labels: maintainer, maintainer: open, type: enhancement, type: update

#9125 k6: update to 0.29.0
  net/k6/Portfile
Labels: by: member, maintainer: open, type: update

#9139 llvm/clang/lldb-devel: bump to 20201115
  lang/llvm-devel/Portfile
Labels: by: member, maintainer

#7918 macos-fortress: Fix startupitems for MacPorts 2.6.3
  net/macos-fortress/Portfile
Labels: maintainer, maintainer: open, type: bugfix

#9143 openjdk8: update to 8u275
  java/openjdk8/Portfile
Labels: maintainer, maintainer: open, type: update

#9141 swi-prolog-devel: Updated to version 8.3.13
  lang/swi-prolog-devel/Portfile
Labels: maintainer, maintainer: open, type: update

#9142 aerc: update to 0.5.2
  mail/aerc/Portfile
Labels: maintainer: none, type: enhancement, type: update

#9128 gnome-system-log: cleanup pre-activate
  gnome/gnome-system-log/Portfile
Labels: maintainer: open

#9145 openjdk8: update to AdoptOpenJDK 11.0.9+11.1
  java/openjdk8/Portfile
Labels: maintainer, maintainer: open, type: update

#9144 gpac: update to 1.0.1
  multimedia/gpac/Portfile
  multimedia/gpac/files/patch-configure.diff
  multimedia/gpac/files/patch-no-hevc-yosemite.diff
Labels: maintainer: none, type: update

#9147 minikube: update to 1.15.1
  sysutils/minikube/Portfile
Labels: by: member, maintainer: open, type: update

#9155 smplayer: remove obsolete port
  multimedia/smplayer/Portfile
Labels: maintainer: none

#9152 beancount: remove obsolete port
  finance/beancount/Portfile
Labels: maintainer: none

#9149 p5-graphviz2: update to version 2.62
  perl/p5-graphviz2/Portfile
Labels: by: member, maintainer: open, type: update

#9153 qore-devel: remove obsolete port
  lang/qore-devel/Portfile
Labels: maintainer: none

#9158 Pydicom: Update to 2.1.1.
  python/py-pydicom/Portfile
Labels: by: member, maintainer, maintainer: open

#9161 py-XlsxWriter: Update to 1.3.7
  python/py-XlsxWriter/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#9160 py-h5py: update to 3.1.0
  python/py-h5py/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#9146 dbus-python: add patch to fix libtool bug
  devel/dbus-python/Portfile
  devel/dbus-python/files/dynamic_lookup-11.patch
Labels: by: member, maintainer: open, type: bugfix

#9162 py-questionary: update to 1.8.1
  python/py-questionary/Portfile
Labels: maintainer, maintainer: open, type: enhancement, type: update

#9098 virtuoso-7: allow implicit function declarations
  devel/virtuoso-7/Portfile
  devel/virtuoso-7/files/patch-libsrc-Wi-numeric.c.diff
Labels: maintainer: open

#9166 fsdb: update to 2.71
  perl/fsdb/Portfile
Labels: maintainer, maintainer: open, type: update

#9159 google-cloud-sdk: update to 319.0.0
  devel/google-cloud-sdk/Portfile
Labels: maintainer, maintainer: open, type: update

#9178 texlive-bin: add patch to fix build on ARM64
  tex/texlive-bin/Portfile
  tex/texlive-bin/files/patch-texk_web2c_luatexdir_luafontloader_fontforge_fontforge-fix_finite.diff
Labels: by: member, maintainer: requires approval, type: bugfix

#9179 logisim-evolution: new port
  cad/logisim-evolution/Portfile
Labels: type: enhancement, type: submission

#9170 capstone: cleanup MacPorts < 2.6.0 handling
  devel/capstone/Portfile
Labels: maintainer: requires approval

#9168 subversion-python27bindings: cleanup handling for MacPorts < 2.6.0
  devel/subversion-python27bindings/Portfile
Labels: maintainer: none

#9163 openjdk8: update GraalVM subports to 20.3.0
  java/openjdk8/Portfile
Labels: maintainer, maintainer: open, type: update

#9140 rustscan: new port
  net/rustscan/Portfile
Labels: by: member, type: submission

#9180 pgbadger: update to 11.3
  databases/pgbadger/Portfile
Labels: maintainer: none, type: enhancement, type: update

#9174 py-httpx: new port
  python/py-httpx/Portfile
Labels: by: member

#9182 gdb: Update version to 10.1
  devel/gdb/Portfile
  devel/gdb/files/patch-elf-bfd.h.diff
Labels: maintainer: none, type: update

#9171 ruby: cleanup MacPorts < 2.6.0 handling
  lang/ruby/Portfile
Labels: maintainer: requires approval

#9148 nnn: update to 3.5
  sysutils/nnn/Portfile
Labels: maintainer: open, type: enhancement, type: update

#9183 py27-twython: fix build
  python/py-twython/Portfile
  python/py-twython/files/patch-ccf20e3261.diff
Labels: maintainer: open

#9190 lisaem, ncid: cleanup MacPorts < 2.6.0 handling
  emulators/lisaem/Portfile
  net/ncid/Portfile
Labels: maintainer: requires approval

#9191 micronaut: update to 2.2.0
  java/micronaut/Portfile
Labels: maintainer, maintainer: open, type: update

#9189 kotlin: update to 1.4.20
  lang/kotlin/Portfile
Labels: maintainer, maintainer: open, type: update

#9188 p5-anyevent-aio: new port
  perl/p5-anyevent-aio/Portfile
Labels: type: submission

#9156 erlang: Update to 23.1 and fix build on macOS 11 and arm64
  lang/erlang/Portfile
  lang/erlang/files/patch-erts_emulator_Makefile.in.diff
  lang/erlang/files/patch-erts_emulator_sys_unix_ddll.c.diff
  lang/erlang/files/patch-lib_wx_configure.in.diff
  lang/erlang/files/patch-make-configure.diff
Labels: by: member, maintainer: requires approval, maintainer: timeout, type: update

#9130 c2html: cleanup pre-activate
  textproc/c2html/Portfile
Labels: maintainer: requires approval, maintainer: timeout

#9192 wireguard-go: update to 0.0.20201118
  net/wireguard-go/Portfile
Labels: maintainer, maintainer: open, type: update

#9167 go-bindata: new port
  devel/go-bindata/Portfile
Labels: by: member, type: submission

#9185 p5-coro: new port
  perl/p5-coro/Portfile
Labels: type: submission

#9194 perl5.28: Fix build with inaccessible parent dir
  lang/perl5/Portfile
  lang/perl5/files/5.28/add-internals-getcwd.patch
  lang/perl5/files/5.28/dont-write-invalid-write_buildcustomize.pl.patch
  lang/perl5/files/5.28/fallback-to-built-in-getcwd.patch
Labels: by: member, maintainer: open

#9198 rancher-cli: update to 2.4.9
  devel/rancher-cli/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#9203 k9s: update to 0.24.0
  sysutils/k9s/Portfile
Labels: maintainer, maintainer: open, type: update

#9201 commitizen: update to 2.8.2
  devel/commitizen/Portfile
Labels: maintainer, maintainer: open, type: enhancement, type: update

#9199 rke: update to 1.2.3
  devel/rke/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#9200 flyway: update to 7.2.1
  java/flyway/Portfile
Labels: by: member, maintainer, maintainer: open, type: update
