Repository macports/macports-ports, pull requests merged in 2020-01, with the labels that each got.

#6081 libarchive: update to 3.4.1
  archivers/libarchive/Portfile
  archivers/libarchive/files/patch-libarchive__archive_read_support_format_lha.c.diff
  archivers/libarchive/files/patch-libarchive__archive_write_disk_posix.c.diff
Labels: by: member, maintainer: open, type: update

#6080 gnome-internet-radio-locator: Update to 2.4.0
  gnome/gnome-internet-radio-locator/Portfile
Labels: maintainer, maintainer: open, type: enhancement, type: update

#6079 assimp: update version 4.1.0->5.0.0
  aqua/qt5/Portfile
  aqua/qt511/Portfile
  aqua/qt55/Portfile
  aqua/qt56/Portfile
  aqua/qt57/Portfile
  aqua/qt58/Portfile
  aqua/qt59/Portfile
  graphics/assimp/Portfile
  math/deal.ii/Portfile
  science/ompl/Portfile
Labels: by: member, maintainer: requires approval, type: enhancement, type: update

#6031 ecCodes: tweak code
  science/ecCodes/Portfile
Labels: by: member, maintainer: requires approval, maintainer: timeout, type: bugfix, type: enhancement

#6089 jdupes: update to 1.14.0
  sysutils/jdupes/Portfile
Labels: maintainer, maintainer: open, type: update

#6088 hugo: update to 0.62.1
  www/hugo/Portfile
Labels: maintainer, maintainer: open, type: update

#6087 tmux: update tmux-devel to latest commit
  sysutils/tmux/Portfile
Labels: maintainer, maintainer: open, type: update

#6086 FAudio: Update to 20.01
  audio/FAudio/Portfile
Labels: maintainer: none, type: enhancement, type: update

#6092 wireguard-tools: update to 1.0.20200102
  net/wireguard-tools/Portfile
Labels: maintainer, maintainer: open, type: update

#6085 rtl_433: update to version 19.08
  science/rtl_433/Portfile
Labels: maintainer, maintainer: open, type: update

#6084 k9s: update to 0.10.4
  sysutils/k9s/Portfile
Labels: maintainer, maintainer: open, type: update

#6094 dcmtk: Simplify variants, add -static sub-port
  graphics/dcmtk/Portfile
Labels: by: member, maintainer, maintainer: open

#6100 k9s: update to 0.10.10
  sysutils/k9s/Portfile
Labels: maintainer, maintainer: open, type: update

#6090 FreeRDP : switch to cmake-1.1 PG plus fixes and cleanup
  net/FreeRDP/Portfile
  net/FreeRDP/files/MainMenu.xib
  net/FreeRDP/files/PasswordDialog.xib
  net/FreeRDP/files/en-MainMenu.xib
  net/FreeRDP/files/patch-64bitfs.diff
  net/FreeRDP/files/patch-config.h.in.diff
Labels: maintainer: none

#6105 lilypond-devel: do not add unsupported compilers to fallback list
  textproc/lilypond-devel/Portfile
Labels: maintainer: open, type: bugfix

#6069 meson: apply upstream patch to fix 32bit macs
  devel/meson/Portfile
  devel/meson/files/patch-meson-32bit-apple.diff
Labels: wip

#6102 jtc: update to 1.75c
  textproc/jtc/Portfile
Labels: maintainer, maintainer: open, type: update

#6107 FreeRDP : fix +codecs variant
  net/FreeRDP/Portfile
Labels: maintainer: none

#6108 k9s: update to 0.11.0
  sysutils/k9s/Portfile
Labels: maintainer, maintainer: open

#6097 web-ext: update to 4.0.0
  devel/web-ext/Portfile
Labels: maintainer: none, type: update

#6022 pandoc: update to 2.9
  textproc/pandoc/Portfile
Labels: maintainer: none, type: update

#6101 py-astor: Update to 0.8.1
  python/py-astor/Portfile
  python/py-astor/files/setuptools-fix.patch
Labels: maintainer: open, type: bugfix, type: enhancement, type: update

#6093 frescobaldi: fix empty conflicts variable
  editors/frescobaldi/Portfile
Labels: maintainer, maintainer: open, type: bugfix

#6082 gpsd: Fix build failures on 10.6, then update to v3.20.
  net/gpsd/Portfile
Labels: maintainer, maintainer: open, type: bugfix

#6023 nebula: new port
  net/nebula/Portfile
Labels: type: submission

#6099 hdf5: Take ownership; update to 1.10.6; bump deps.
  gis/gdal/Portfile
  gis/kealib/Portfile
  graphics/InsightToolkit-devel/Portfile
  graphics/field3d/Portfile
  graphics/vigra/Portfile
  graphics/vips/Portfile
  graphics/vtk/Portfile
  math/caffe/Portfile
  math/deal.ii/Portfile
  math/dolfin/Portfile
  math/gnudatalanguage/Portfile
  math/mathgl/Portfile
  math/octave/Portfile
  math/petsc/Portfile
  math/shogun-devel/Portfile
  math/shogun/Portfile
  perl/p5-pdl-io-hdf5/Portfile
  python/py-h5py/Portfile
  python/py-isce2/Portfile
  python/py-nio/Portfile
  python/py-pyne/Portfile
  python/py-stfio/Portfile
  python/py-tables/Portfile
  science/ALPSCore/Portfile
  science/ALPSMaxent/Portfile
  science/H5Part/Portfile
  science/HDF5-External-Filter-Plugins/Portfile
  science/alps/Portfile
  science/armadillo/Portfile
  science/berkeleygw/Portfile
  science/cdo/Portfile
  science/crystfel/Portfile
  science/digital_rf/Portfile
  science/flann/Portfile
  science/gds/Portfile
  science/gmsh/Portfile
  science/gmtk/Portfile
  science/gmtsar/Portfile
  science/grads/Portfile
  science/h4h5tools/Portfile
  science/h5utils/Portfile
  science/hdf5-lz4-plugin/Portfile
  science/hdf5/Portfile
  science/hdf5/files/patch-tools-src-misc-h5cc.in.diff
  science/hdfeos5/Portfile
  science/ismrmrd/Portfile
  science/lal/Portfile
  science/magicspp/Portfile
  science/ncarg/Portfile
  science/nco/Portfile
  science/netcdf/Portfile
  science/paraview/Portfile
  science/silo/Portfile
  science/splash/Portfile
  science/stimfit/Portfile
  science/swarm/Portfile
  science/vapor/Portfile
  science/wgrib2/Portfile
  science/xdmf/Portfile
Labels: by: member, maintainer: requires approval

#6110 swi-prolog-devel: update to 8.1.20
  lang/swi-prolog-devel/Portfile
Labels: maintainer, type: update

#6014 GPXLab: New port
  gis/GPXLab/Portfile
Labels: type: enhancement, type: submission

#5993 dovecot2: Update, Bugfix, add dovecot2-sieve as subport
  mail/dovecot2-sieve/Portfile
  mail/dovecot2/Portfile
  mail/dovecot2/files/org.macports.dovecot-apns.plist
Labels: maintainer: none, type: bugfix

#6095 py-sentence-transformers: Update and switch to pypi
  python/py-sentence-transformers/Portfile
Labels: maintainer: none, type: update

#6112 hugo: update to 0.62.2
  www/hugo/Portfile
Labels: maintainer, maintainer: open, type: update

#6114 k9s: update to 0.11.2
  sysutils/k9s/Portfile
Labels: maintainer, maintainer: open, type: update

#6111 prometheus: update to 2.15.2
  net/prometheus/Portfile
Labels: maintainer, maintainer: open, type: update

#6116 dbeaver-community: update to 6.3.2
  databases/dbeaver-community/Portfile
Labels: maintainer, maintainer: open, type: update

#6119 logtalk: update to 3.34.0
  lang/logtalk/Portfile
Labels: maintainer, type: update

#6025 git-secret: Adding new port
  devel/git-secret/Portfile
Labels: type: enhancement, type: submission

#6007 dfu-programmer: update version to 0.7.2
  cross/dfu-programmer/Portfile
  cross/dfu-programmer/files/configure.patch
Labels: maintainer: requires approval, maintainer: timeout, type: update

#6121 starship: update to 0.33.0
  sysutils/starship/Portfile
Labels: maintainer, maintainer: open, type: update

#6115 py-pyside2: update version 5.13.0->5.14.0
  python/py-pyside2/Portfile
  python/py-pyside2/files/patch-find-llvm-config.diff
Labels: by: member, maintainer, maintainer: open, type: enhancement, type: update

#6123 msmtp: update version to 1.8.7
  mail/msmtp/Portfile
Labels: maintainer, maintainer: open, type: update

#6125 lazygit: update to 0.12.3
  devel/lazygit/Portfile
Labels: maintainer, maintainer: open, type: update

#6124 google-cloud-sdk: update to 275.0.0
  devel/google-cloud-sdk/Portfile
Labels: maintainer, maintainer: open, type: update

#6126 Gildas update for Januray 2020 release.
  science/gildas/Portfile
  science/gildas/files/patch-admin-Makefile.build.diff
Labels: maintainer

#6122 qt4-mac-sqlite*-plugin: use correct C++ std library
  aqua/qt4-mac-sqlite2-plugin/Portfile
Labels: by: member, maintainer: open, type: bugfix

#6019 xhyve: Update to current master
  emulators/xhyve/Portfile
Labels: maintainer: requires approval, maintainer: timeout, type: bugfix, type: update

#6002 nsis: update to 3.05
  devel/nsis/Portfile
Labels: maintainer: none, type: enhancement, type: update

#6118 org-mode: update to 9.3.1
  editors/org-mode/Portfile
Labels: by: member, maintainer: requires approval, type: update

#6131 llvm/clang/lldb-9.0: bump to 9.0.1
  lang/llvm-9.0/Portfile
Labels: by: member, maintainer: requires approval

#6135 opensc: update to 0.20.0
  security/opensc/Portfile
  security/opensc/files/patch-xcode10.diff
Labels: by: member, maintainer, maintainer: open, type: update

#6133 py35-astropy: version 3.2.3 is the last that supports Python 3.5
  python/py-astropy/Portfile
Labels: by: member, maintainer: open

#6028 trash: Fix build on Lion and older
  sysutils/trash/Portfile
  sysutils/trash/files/patch-HGUtils.m-lion.diff
Labels: maintainer: none, type: bugfix

#6127 terraform: update to 0.12.19
  sysutils/terraform/Portfile
Labels: maintainer, maintainer: open, type: update

#6137 lazygit: update to 0.13
  devel/lazygit/Portfile
Labels: maintainer, maintainer: open, type: update

#6134 eksctl: update to 0.12.0
  sysutils/eksctl/Portfile
Labels: maintainer, maintainer: open, type: update

#6139 k9s: update to 0.12.0
  sysutils/k9s/Portfile
Labels: maintainer, maintainer: open, type: update

#6129 jtc: patch 1.75c for older compilers
  textproc/jtc/Portfile
  textproc/jtc/files/patch-signal-hpp.diff
Labels: maintainer, maintainer: open

#6128 broot: new port
  sysutils/broot/Portfile
Labels: type: submission

#6138 gate: update Geant4 version
  science/gate/Portfile
Labels: by: member, maintainer, maintainer: open, type: bugfix, type: update

#6117 py-neovim: update to 0.4.0
  python/py-neovim/Portfile
Labels: by: member, maintainer: open, type: update

#6144 textproc/qpdf: trivial update to 9.1.0
  textproc/qpdf/Portfile
Labels: by: member, maintainer: none

#6143 py-nbval: Add Python 38
  python/py-nbval/Portfile
Labels: maintainer: none

#6142 broot: update to 0.11.8
  sysutils/broot/Portfile
Labels: maintainer, maintainer: open, type: update

#6113 py-hdbscan: Submission
  python/py-hdbscan/Portfile
Labels: type: submission

#6145 httpie: update to 2.0.0
  net/httpie/Portfile
Labels: by: member, maintainer: open, type: update

#6146 py-gpilab-framework: remove 35
  python/py-gpilab-framework/Portfile
  python/py-gpilab-framework/files/gpilab-35
Labels: by: member, maintainer, maintainer: open

#6148 llvm/clang/lldb: bump to 7.1.0
  lang/llvm-7.0/Portfile
Labels: by: member, maintainer, type: enhancement

#6152 ntp: Add configure options
  sysutils/ntp/Portfile
Labels: maintainer: requires approval, type: update

#6165 broot: update to 0.11.9
  sysutils/broot/Portfile
Labels: maintainer, maintainer: open, type: update

#6168 fldigi: update version to 4.1.09
  science/fldigi/Portfile
Labels: maintainer, maintainer: open, type: update

#6170 flrig: update version to 1.3.49
  science/flrig/Portfile
Labels: maintainer, maintainer: open, type: update

#6132 qbittorrent: new port submission
  net/qBittorrent/Portfile
Labels: maintainer: open, type: submission

#6167 starship: update to 0.33.1
  sysutils/starship/Portfile
Labels: maintainer, maintainer: open, type: update

#6149 update spdlog to 1.5.0
  devel/spdlog/Portfile
Labels: maintainer, maintainer: open, type: enhancement, type: update

#6171 cmake-1.1: debug variant wait until pre-configure
  _resources/port1.0/group/cmake-1.1.tcl
Labels: by: member

#6158 julia: update to version 1.3.1
  lang/julia/Portfile
Labels: maintainer: open, type: enhancement, type: update

#6147 php: Add php74 subports
  lang/php/Portfile
  lang/php/files/patch-php74-bison-re2c-version.diff
  lang/php/files/patch-php74-iODBC.diff
  lang/php/files/patch-php74-sapi-fpm-php-fpm.conf.in.diff
  lang/php/files/patch-php74-scripts-php-config.in.diff
  lang/php/files/patch-php74-unixODBC.diff
  lang/php/files/php74
Labels: maintainer: requires approval

#6175 nebula: update to 1.1.0
  net/nebula/Portfile
Labels: maintainer, maintainer: open, type: update

#6173 qbittorrent: remove the use of macdeployqt
  net/qBittorrent/Portfile
Labels: maintainer, maintainer: open, type: enhancement

#6166 bandwhich: new port
  net/bandwhich/Portfile
Labels: type: submission

#6178 bandwhich: remove unneeded variables
  net/bandwhich/Portfile
Labels: maintainer, maintainer: open

#6140 luajit: Update to 2.1.0-beta3
  lang/luajit/Portfile
Labels: maintainer: none, type: update

#6159 geos: Fix build on 10.7 and 10.8.
  science/geos/Portfile
Labels: maintainer: open, type: bugfix

#6151 proj6: Fix build on 10.8 and 10.9.
  gis/proj6/Portfile
Labels: maintainer: open, type: bugfix

#6191 radare2: update to 4.1.1
  devel/radare2/Portfile
Labels: maintainer: open, type: update

#6193 diff-pdf: update to 0.4.1
  graphics/diff-pdf/Portfile
Labels: maintainer, maintainer: open, type: update

#6189 micronaut: update to 1.2.9
  java/micronaut/Portfile
Labels: maintainer, maintainer: open, type: update

#6188 groovy: update to 2.5.9
  lang/groovy/Portfile
Labels: maintainer, maintainer: open, type: update

#6186 bandwhich: update to 0.10.0
  net/bandwhich/Portfile
Labels: maintainer, maintainer: open, type: update

#6181 google-cloud-sdk: update to 276.0.0
  devel/google-cloud-sdk/Portfile
Labels: maintainer, maintainer: open, type: update

#6180 spring-boot-cli: update to 2.2.3.RELEASE
  java/spring-boot-cli/Portfile
Labels: maintainer, maintainer: open, type: update

#6179 openjdk8: update to GraalVM 19.3.1
  java/openjdk8/Portfile
Labels: maintainer, maintainer: open, type: update

#6177 openjdk8: update to AdoptOpenJDK 11.0.6+10
  java/openjdk8/Portfile
Labels: maintainer, maintainer: open, type: update

#6162 ecCodes: update to 2.16.0
  science/ecCodes/Portfile
  science/ecCodes/files/patch-no-jasper-deps.diff
Labels: maintainer: requires approval, maintainer: timeout, type: enhancement, type: update

#6196 broot: update to 0.12.0
  sysutils/broot/Portfile
Labels: maintainer, maintainer: open, type: update

#6184 tig: Update to 2.5.0
  devel/tig/Portfile
Labels: maintainer: open, type: update

#6190 sigil: update to 1.0.0
  editors/sigil/Portfile
Labels: maintainer: none, type: update

#6198 php-zip: Add php74
  php/php-zip/Portfile
Labels: maintainer: open

#6201 rclone: update to 1.50.2
  net/rclone/Portfile
Labels: maintainer: open, type: update

#6199 php-event: Add php74
  php/php-event/Portfile
Labels: maintainer: open

#6197 php74: Add PHP 7.4 to non-core PHP extensions
  php/php-APCu/Portfile
  php/php-excel/Portfile
  php/php-geoip/Portfile
  php/php-gmagick/Portfile
  php/php-imagick/Portfile
  php/php-jsmin/Portfile
  php/php-lzf/Portfile
  php/php-mailparse/Portfile
  php/php-mcrypt/Portfile
  php/php-mongodb/Portfile
  php/php-mysql-xdevapi/Portfile
  php/php-pdflib/Portfile
  php/php-propro/Portfile
  php/php-raphf/Portfile
  php/php-redis/Portfile
  php/php-scrypt/Portfile
  php/php-ssh2/Portfile
  php/php-stomp/Portfile
  php/php-svm/Portfile
  php/php-taint/Portfile
  php/php-timezonedb/Portfile
  php/php-uuid/Portfile
  php/php-vld/Portfile
  php/php-yaf/Portfile
  php/php-yaml/Portfile
  php/php-yaz/Portfile
Labels: maintainer: requires approval

#6209 jtc: update to 1.75d
  textproc/jtc/Portfile
  textproc/jtc/files/patch-signal-hpp.diff
Labels: maintainer, maintainer: open, type: update

#6204 apache-solr8: Update to version 8.4.1
  java/apache-solr8/Portfile
Labels: maintainer, maintainer: open, type: update

#6203 go-ethereum: update to 1.9.10
  finance/go-ethereum/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#6208 gitlab-runner: update to 12.7.0
  devel/gitlab-runner/Portfile
Labels: maintainer, maintainer: open, type: update

#6207 k9s: update to 0.13.1
  sysutils/k9s/Portfile
Labels: maintainer, maintainer: open, type: update

#6206 spring-boot-cli: update to 2.2.4.RELEASE
  java/spring-boot-cli/Portfile
Labels: maintainer, maintainer: open, type: update

#6211 wireguard-tools: update to 1.0.20200121
  net/wireguard-tools/Portfile
Labels: maintainer, maintainer: open, type: update

#6210 wireguard-go: update to 0.0.20200121
  net/wireguard-go/Portfile
Labels: maintainer, maintainer: open, type: update

#6213 micronaut: update to 1.2.10
  java/micronaut/Portfile
Labels: maintainer, maintainer: open, type: update

#6205 openjdk8: update to AdoptOpenJDK 13.0.2+8
  java/openjdk8/Portfile
Labels: maintainer, maintainer: open, type: update

#6212 openjdk8: update to AdoptOpenJDK 8u242 with HotSpot VM
  java/openjdk8/Portfile
Labels: maintainer, maintainer: open, type: update

#6217 radare2: update to 4.2.0
  devel/radare2/Portfile
Labels: maintainer: open, type: update

#6195 buildbot 2: switch to python 3.8
  devel/buildbot-2/Portfile
  devel/buildbot-worker/Portfile
  python/py-buildbot-console-view/Portfile
  python/py-buildbot-grid-view/Portfile
  python/py-buildbot-macports-custom-views/Portfile
  python/py-buildbot-pkg/Portfile
  python/py-buildbot-waterfall-view/Portfile
  python/py-buildbot-www/Portfile
  python/py-buildbot/Portfile
Labels: by: member, maintainer, maintainer: open

#5928 weechat: Change build option from aspell to spell
  irc/weechat/Portfile
Labels: maintainer: open, type: bugfix

#6219 eksctl: update to 0.13.0
  sysutils/eksctl/Portfile
Labels: maintainer, maintainer: open, type: update

#6221 buildbot: update to 2.6.0
  devel/buildbot-2/Portfile
  devel/buildbot-worker/Portfile
  python/py-buildbot-console-view/Portfile
  python/py-buildbot-grid-view/Portfile
  python/py-buildbot-pkg/Portfile
  python/py-buildbot-waterfall-view/Portfile
  python/py-buildbot-www/Portfile
  python/py-buildbot/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#6220 emacs-app: do not run code meant for other subports
  editors/emacs/Portfile
Labels: by: member, maintainer: open, type: bugfix

#6215 perl5: remove special-cased compiler selection for subports on 10.6 a…
  lang/perl5/Portfile
Labels: by: member, maintainer: open, type: bugfix

#6192 lablgtk2: Update to 2.18.9 and fix livecheck
  x11/lablgtk2/Portfile
Labels: by: member, maintainer: open, type: update

#6155 mysql8: update to 8.0.19
  databases/mysql8/Portfile
  databases/mysql8/files/patch-cmake-install_layout.cmake.diff
  databases/mysql8/files/patch-cmake-install_macros.cmake.diff
Labels: maintainer, maintainer: open, type: update

#6214 k9s: update to 0.13.2
  sysutils/k9s/Portfile
Labels: maintainer, maintainer: open, type: update

#6216 google-cloud-sdk: update to 277.0.0
  devel/google-cloud-sdk/Portfile
Labels: maintainer, maintainer: open, type: update

#6222 vault: update to 1.3.2
  security/vault/Portfile
Labels: maintainer, maintainer: open, type: update

#6157 dlib: Update to work with OpenCV 4.2.0 and 3.4.9
  math/dlib/Portfile
Labels: maintainer: none, type: update

#5966 hwloc: update to 2.1.0
  devel/hwloc/Portfile
  math/petsc/Portfile
  science/openmpi/Portfile
Labels: maintainer: none, type: update

#6218 QLMarkdown: Update to 1.3.6
  sysutils/QLMarkdown/Portfile
Labels: type: update

#6227 hugo: update to 0.63.0
  www/hugo/Portfile
Labels: maintainer, maintainer: open, type: update

#6224 terraform-0.12: update to 0.12.20
  sysutils/terraform/Portfile
Labels: maintainer, maintainer: open, type: update

#6226 Update Portfile whizard 2.6.4 -> 2.8.2
  science/whizard/Portfile
  science/whizard/files/WOXDR.cpp.patch
Labels: maintainer: requires approval, type: update

#6200 isl: update version 0.21->0.22.1
  cross/arm-none-eabi-gcc/Portfile
  cross/avr-gcc/Portfile
  cross/i386-elf-gcc/Portfile
  cross/i686-w64-mingw32-gcc/Portfile
  cross/msp430-elf-gcc/Portfile
  cross/msp430-gcc-devel/Portfile
  cross/msp430-gcc/Portfile
  cross/x86_64-elf-gcc/Portfile
  cross/x86_64-w64-mingw32-gcc/Portfile
  devel/cloog/Portfile
  devel/isl/Portfile
  devel/isl/files/patch-configure_c++11.diff
  lang/gcc10/Portfile
  lang/gcc6/Portfile
  lang/gcc7/Portfile
  lang/gcc8/Portfile
  lang/gcc9/Portfile
Labels: by: member, maintainer, type: enhancement, type: update

#6154 gmt5, gmt6: use github for tarball and livecheck
  science/gmt5/Portfile
Labels: maintainer: requires approval, maintainer: timeout, type: enhancement

#6229 k9s: update to 0.13.4
  sysutils/k9s/Portfile
Labels: maintainer, maintainer: open, type: update

#6230 openjdk8: update to OpenJ9 0.18.1
  java/openjdk8/Portfile
Labels: maintainer, maintainer: open, type: update

#6231 hugo: update to 0.63.1
  www/hugo/Portfile
Labels: maintainer, maintainer: open, type: update

#6232 swi-prolog-devel: update to 8.1.21
  lang/swi-prolog-devel/Portfile
Labels: maintainer, type: update

#6233 gitlab-runner: update to 12.7.1
  devel/gitlab-runner/Portfile
Labels: maintainer, maintainer: open, type: update

#6156 homebank: Update to version 5.3.1
  x11/homebank/Portfile
Labels: maintainer, maintainer: open, type: update

#6234 restic: restructure Build and add debug variant
  sysutils/restic/Portfile
Labels: maintainer: none

#6228 maxima: update to 5.43.1
  math/maxima/Portfile
Labels: maintainer: open, type: update

#6236 clang-3.4 and 3.7: remove libxml2 dependency
  lang/llvm-3.4/Portfile
  lang/llvm-3.7/Portfile
Labels: by: member, maintainer

#6242 limesuite-devel: update version to 538e186b
  science/limesuite/Portfile
Labels: maintainer, maintainer: open, type: update

#6241 gr-limesdr-devel: update version to cd653a40
  science/gr-limesdr/Portfile
Labels: maintainer, maintainer: open, type: update

#6239 libfec: update version to 07632475
  science/libfec/Portfile
Labels: maintainer, maintainer: open, type: update

#6245 SDRangel: temporary fix for building the software
  science/SDRangel/Portfile
  science/SDRangel/files/disable-remotetx.patch
Labels: maintainer, maintainer: open, type: bugfix

#6240 py-commpy: update version to 0.5.0
  python/py-commpy/Portfile
Labels: maintainer, maintainer: open, type: update

#6163 welle.io: Update welle.io-devel & rearranage variants for binary distribution
  multimedia/welle.io/Portfile
Labels: maintainer: none, type: bugfix, type: enhancement, type: update

#6246 libtapi: use a more complete patch for zippered support
  devel/libtapi/Portfile
  devel/libtapi/files/patch-0002-tapi-zippered-support-poechtrager.diff
Labels: by: member, maintainer, maintainer: open, type: enhancement

#6235 texlive-bin: remove deprecated PortGroup cxx11
  tex/texlive-bin/Portfile
Labels: by: member, maintainer: requires approval, type: enhancement

#6161 mas: update to version 1.6.3
  sysutils/mas/Portfile
Labels: maintainer: open, type: update

#6250 munge: update to version 0.5.14
  net/munge/Portfile
Labels: maintainer, maintainer: open, type: bugfix, type: enhancement, type: update
