Repository macports/macports-ports, pull requests merged in 2020-06, with the labels that each got.

#6390 libsndfile: patch to build under OS X 10.4
  audio/libsndfile/Portfile
  audio/libsndfile/files/patch-sndfile-play.diff
Labels: maintainer: none, type: bugfix

#7279 wireshark3: update to 3.2.4
  net/wireshark3/Portfile
Labels: by: member, maintainer: requires approval, type: update

#7261 sdcc: update version to 4.0.0
  lang/sdcc/Portfile
Labels: by: member, maintainer: open, type: update

#7284 alacritty: update to 0.4.3
  aqua/alacritty/Portfile
Labels: maintainer, maintainer: open, type: update

#7287 SilentKnight: update to 1.7
  sysutils/SilentKnight/Portfile
Labels: maintainer, maintainer: open, type: update

#7286 dbeaver-community: update to 7.1.0
  databases/dbeaver-community/Portfile
Labels: maintainer, maintainer: open, type: update

#7289 hugo: update to 0.72.0
  www/hugo/Portfile
Labels: maintainer, maintainer: open, type: update

#7291 broot: update to 0.14.2
  sysutils/broot/Portfile
Labels: maintainer, maintainer: open, type: update

#7290 go: update to 1.14.4
  lang/go/Portfile
Labels: maintainer: open, type: update

#7268 py-astroplan: update to astroplan 0.6
  python/py-astroplan/Portfile
Labels: maintainer: open, type: update

#7264 leiningen: update to 2.9.3
  devel/leiningen/Portfile
Labels: maintainer: open, type: enhancement, type: update

#7293 docker: update to 19.03.11
  devel/docker/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#7297 gitlab-runner: update to 13.0.1
  devel/gitlab-runner/Portfile
Labels: maintainer, maintainer: open, type: update

#7295 google-cloud-sdk: update to 295.0.0
  devel/google-cloud-sdk/Portfile
Labels: maintainer, maintainer: open, type: update

#7298 perl5: update subports to latest versions
  lang/perl5/Portfile
Labels: by: member, maintainer: open, type: update

#7303 semgrep: update to 0.9.0
  devel/semgrep/Portfile
Labels: maintainer, maintainer: open, type: update

#7300 redis: update to 6.0.4
  databases/redis/Portfile
Labels: maintainer, maintainer: open, type: enhancement, type: update

#7299 less: use pcre2
  textproc/less/Portfile
Labels: maintainer: open, type: enhancement

#7301 ripgrep: update to 12.1.1
  textproc/ripgrep/Portfile
Labels: maintainer: open, type: enhancement, type: update

#7313 v2ray: update to 4.23.4
  net/v2ray/Portfile
Labels: maintainer: open, type: bugfix, type: security fix, type: update

#7312 josm: update to 16538
  gis/JOSM/Portfile
Labels: maintainer, maintainer: open, type: enhancement, type: update

#7311 keystore-explorer: new port
  security/keystore-explorer/Portfile
Labels: type: submission

#7296 patchelf: New port
  devel/patchelf/Portfile
Labels: type: submission

#7305 grafana: update to 7.0.3
  net/grafana/Portfile
Labels: maintainer, maintainer: open, type: update

#7306 simple-web-server: update to 3.0.2
  devel/simple-web-server/Portfile
Labels: maintainer, maintainer: open, type: update

#7259 micro: new port
  editors/micro/Portfile
Labels: type: submission

#7262 chromedriver: Update to version 83.0.4103.39
  www/chromedriver/Portfile
Labels: maintainer: none, type: update

#7315 lang/abcl: update to abcl-1.7.0
  lang/abcl/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#7320 ecs-cli: update to 1.19.1
  devel/ecs-cli/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#7318 sshuttle: update to 1.0.1
  net/sshuttle/Portfile
Labels: maintainer, maintainer: open, type: update

#7283 pdb2pqr: fix pdb2pqr shell script to run - remove md5/sha1 and add size field to checksums
  science/pdb2pqr/Portfile
Labels: maintainer, type: bugfix

#7236 exa: remove dependency on libssh2, bump revision to 1
  sysutils/exa/Portfile
Labels: maintainer, maintainer: open

#7230 nanogui: new port
  graphics/nanogui/Portfile
Labels: type: submission

#7324 plantuml: Update to 1.2020.11
  java/plantuml/Portfile
  java/plantuml/files/patch-build.xml.diff
Labels: by: member, maintainer: none, type: update

#7316 syncthing: update to 1.6.1
  net/syncthing/Portfile
Labels: maintainer: open, type: bugfix, type: enhancement, type: update

#7288 openttd: use application bundle
  games/openttd/Portfile
  games/openttd/files/patch-lto.diff
  games/openttd/files/patch-sysroot.diff
Labels: by: member, maintainer: open, type: enhancement

#7323 procmail: avoid using strlcat/strlcpy
  mail/procmail/Portfile
  mail/procmail/files/patch-avoid-strlcat-strlcpy.diff
Labels: maintainer: none, type: bugfix

#7304 Gildas: update to 202006b
  science/gildas/Portfile
Labels: maintainer, type: update

#7155 py-pycryptodome: update to version 3.9.7
  python/py-pycryptodome/Portfile
Labels: maintainer: open, type: update

#7282 pick: update to version 4.0.0
  devel/pick/Portfile
Labels: maintainer, maintainer: open, type: enhancement, type: update

#6937 chruby: new port
  ruby/chruby/Portfile
Labels: type: submission

#6938 ruby-install: new port
  ruby/ruby-install/Portfile
Labels: type: submission

#7216 py-graph-tool: add GitHub handle for maintainer
  python/py-graph-tool/Portfile
Labels: maintainer: requires approval, maintainer: timeout

#7267 mpv: add variant for building libmpv
  multimedia/mpv/Portfile
Labels: maintainer: requires approval, maintainer: timeout, type: enhancement

#7330 nomad: update to 0.11.3
  net/nomad/Portfile
Labels: maintainer, maintainer: open, type: update

#7332 drupal7: update to 7.71
  www/drupal7/Portfile
Labels: maintainer: none, type: bugfix, type: security fix, type: update

#7331 drupal8: update to 8.7.14
  www/drupal8/Portfile
Labels: maintainer: none, type: security fix, type: update

#7337 ultralist: update to 0.9.6
  office/ultralist/Portfile
Labels: maintainer, maintainer: open, type: update

#7336 micronaut: update to 1.3.6
  java/micronaut/Portfile
Labels: maintainer, maintainer: open, type: update

#7335 k9s: update to 0.20.5
  sysutils/k9s/Portfile
Labels: maintainer, maintainer: open, type: update

#7339 vgrep: update to 2.3.1
  textproc/vgrep/Portfile
Labels: maintainer, maintainer: open, type: update

#7307 simple-websocket-server: update to 2.0.0
  devel/simple-websocket-server/Portfile
Labels: maintainer, maintainer: open, type: update

#7333 bitcoin: Update to 0.20.0
  finance/bitcoin/Portfile
Labels: maintainer: open, type: update

#7340 ghostscript: use macports versions of dependencies
  print/ghostscript/Portfile
Labels: maintainer: none, type: enhancement

#7342 aerc: update to 0.4.0
  mail/aerc/Portfile
Labels: maintainer: none, type: enhancement, type: update

#7338 crystal: update to 0.34.0
  lang/crystal/Portfile
  lang/crystal/files/patch-readline.diff
Labels: maintainer, maintainer: open, type: update

#7329 ntpsec: update to 1.1.9
  sysutils/ntpsec/Portfile
  sysutils/ntpsec/files/ntp.conf
  sysutils/ntpsec/files/patch-PreHighSierra.diff
Labels: maintainer, maintainer: open, type: update

#7321 py-docker: update to 4.2.1
  python/py-docker/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#7322 docker-compose: update to 1.26.0 (and update dependencies)
  python/docker-compose/Portfile
  python/py-python-dotenv/Portfile
Labels: by: member, maintainer, maintainer: open, type: submission, type: update

#7346 youtube-dl: Update to 2020.06.06
  net/youtube-dl/Portfile
Labels: maintainer: open, type: update

#7358 flyway: update to 6.4.3
  java/flyway/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#7351 topgrade: update to 4.6.0
  sysutils/topgrade/Portfile
Labels: maintainer, maintainer: open, type: update

#7363 eric4: remove obsolete port
  devel/eric4/Portfile
Labels: maintainer: none

#7354 clojure-devel: remove obsolete port
  lang/clojure-devel/Portfile
Labels: maintainer: none

#7355 rdesktop-devel: remove obsolete port
  devel/rdesktop-devel/Portfile
Labels: maintainer: none

#7356 dynamips-devel: remove obsolete port
  net/dynamips-devel/Portfile
Labels: maintainer: none

#7357 taglib-devel: remove obsolete port
  audio/taglib-devel/Portfile
Labels: maintainer: none

#7353 swfdec-devel: remove obsolete port
  multimedia/swfdec-devel/Portfile
Labels: maintainer: none

#7359 griffon-devel: remove obsolete port
  devel/griffon-devel/Portfile
Labels: maintainer: none

#7352 hidapi-devel: remove obsolete port
  comms/hidapi-devel/Portfile
Labels: maintainer: none

#7360 pgf-devel: remove obsolete port
  tex/pgf-devel/Portfile
Labels: maintainer: none

#7361 thrift-devel: remove obsolete port
  devel/thrift-devel/Portfile
Labels: maintainer: none

#7362 py-pyusb-devel: remove obsolete port
  python/py-pyusb-devel/Portfile
Labels: maintainer: none

#7364 progress: update to 0.15
  sysutils/progress/Portfile
Labels: maintainer, maintainer: open, type: update

#7349 mysql56: update to 5.6.48
  databases/mysql56/Portfile
  databases/mysql56/files/patch-storage-innobase-handler-i_s.cc.diff
Labels: maintainer: none, type: bugfix, type: update

#7367 swi-prolog-devel: Updated to version 8.3.1
  lang/swi-prolog-devel/Portfile
Labels: maintainer, maintainer: open, type: update

#7372 mod_gnutls +apache22: remove obsolete variant
  www/mod_gnutls/Portfile
Labels: maintainer: open

#7369 petsc-devel: remove obsolete port
  math/petsc/Portfile
Labels: maintainer: open

#7378 grails-devel: remove obsolete port
  devel/grails-devel/Portfile
Labels: maintainer: none

#7377 tin-devel: remove obsolete port
  news/tin-devel/Portfile
Labels: maintainer: none

#7376 couchdb-devel: remove obsolete port
  databases/couchdb-devel/Portfile
Labels: maintainer: none

#7375 py-wordnet: remove obsolete port
  python/py-wordnet/Portfile
Labels: maintainer: none

#7374 recode-devel: remove obsolete port
  textproc/recode-devel/Portfile
Labels: maintainer: none

#7373 rtf2latex: remove obsolete port
  tex/rtf2latex/Portfile
Labels: maintainer: none

#7371 mod_python26: remove obsolete port
  www/mod_python/Portfile
Labels: maintainer: none

#7382 grass7: re-enable python patch
  gis/grass7/Portfile
Labels: maintainer: none, type: bugfix

#7370 mod_wsgi +apache22: remove obsolete variant
  www/mod_wsgi/Portfile
Labels: maintainer: none

#7381 R: update to 4.0.1
  math/R/Portfile
Labels: maintainer, maintainer: open, type: update

#7272 sqlitebrowser: use qmake for darwin
  databases/sqlitebrowser/Portfile
Labels: maintainer: open, type: enhancement

#7384 chezmoi: update to 1.8.2
  sysutils/chezmoi/Portfile
Labels: maintainer, maintainer: open, type: update

#7344 librdkafka: fix opportunistic linkage
  net/librdkafka/Portfile
Labels: maintainer, maintainer: open, type: bugfix

#7386 jdupes: update to 1.16.0
  sysutils/jdupes/Portfile
Labels: maintainer, maintainer: open, type: update

#7383 prometheus: update to 2.19.0
  net/prometheus/Portfile
Labels: maintainer, maintainer: open, type: update

#7391 semgrep: update to 0.10.0
  devel/semgrep/Portfile
Labels: maintainer, maintainer: open, type: update

#7390 google-cloud-sdk: update to 296.0.0
  devel/google-cloud-sdk/Portfile
Labels: maintainer, maintainer: open, type: update

#7394 gloomhaven-helper: update to 8.3.6
  games/gloomhaven-helper/Portfile
Labels: by: member, maintainer, type: update

#7395 consul: update to 1.7.4
  net/consul/Portfile
Labels: maintainer, maintainer: open, type: update

#7345 zettlr: new port
  aqua/zettlr/Portfile
  aqua/zettlr/files/patch-make.sh.diff
  aqua/zettlr/files/patch-package.json.diff
Labels: type: submission

#7379 py-uncertainties: update to 3.1.4
  python/py-uncertainties/Portfile
Labels: by: member, maintainer: open, type: update

#7098 iqtree: new port
  science/iqtree/Portfile
  science/iqtree/files/patch-CMakeLists.txt.diff
Labels: type: enhancement, type: submission

#7407 patchelf: update to 0.11
  devel/patchelf/Portfile
Labels: maintainer, maintainer: open, type: update

#7411 apache-solr8: Update to version 8.5.2
  java/apache-solr8/Portfile
Labels: maintainer, maintainer: open, type: update

#7410 hyperscan: Update to version 5.3.0
  textproc/hyperscan/Portfile
Labels: maintainer: none, type: update

#7405 trojan: update to 1.16.0
  net/trojan/Portfile
Labels: maintainer, maintainer: open, type: update

#7403 skaffold: update to 1.11.0
  devel/skaffold/Portfile
Labels: maintainer, maintainer: open, type: update

#7380 fossil: update to 2.10.1
  devel/fossil/Portfile
Labels: maintainer: requires approval, maintainer: timeout, type: bugfix, type: security fix, type: update

#7385 py-gnupg: update to version 0.4.6
  python/py-gnupg/Portfile
Labels: maintainer: open, type: update

#7412 broot: update to 0.15.1
  sysutils/broot/Portfile
Labels: maintainer, maintainer: open, type: update

#7404 v2ray: update to 4.24.2
  net/v2ray/Portfile
Labels: maintainer: open, type: security fix, type: update

#7413 google-cloud-sdk: update to 296.0.1
  devel/google-cloud-sdk/Portfile
Labels: maintainer: open, type: enhancement, type: update

#7417 ncdu: Update to 1.15.1
  sysutils/ncdu/Portfile
Labels: by: member, maintainer: open, type: update

#7416 yaegi: update to 0.8.7
  devel/yaegi/Portfile
Labels: maintainer, maintainer: open, type: update

#7420 uchardet: uses c++11
  textproc/uchardet/Portfile
Labels: by: member, maintainer: open, type: bugfix

#7408 mas: update to 1.7.0
  sysutils/mas/Portfile
Labels: maintainer: open, type: update

#7161 salt: update to version 3000.3
  sysutils/salt/Portfile
Labels: maintainer, maintainer: open, type: update

#7398 Add py-pydantic and dependency py-dataclasses
  python/py-pydantic/Portfile
Labels: type: submission

#7171 ideviceinstaller-devel: change dependencies
  devel/ideviceinstaller/Portfile
Labels: maintainer: open, type: enhancement

#7422 topgrade: update to 4.7.1
  sysutils/topgrade/Portfile
Labels: maintainer, maintainer: open, type: update

#7423 beekeeper-studio: update to 1.5.1
  aqua/beekeeper-studio/Portfile
Labels: maintainer, maintainer: open, type: update

#7419 iperf3{,-devel}: update to 3.8.1 and 20200612
  net/iperf3/Portfile
Labels: maintainer, maintainer: open, type: update

#7418 whitebox-tools: update to version 1.3.0
  gis/whitebox-tools/Portfile
Labels: maintainer, maintainer: open, type: enhancement, type: update

#7327 openttd: update to 1.10.2
  games/openttd/Portfile
  games/openttd/files/patch-name_conflict.diff
Labels: by: member, maintainer: open, type: update

#7426 duckdb: update to 0.1.8
  databases/duckdb/Portfile
Labels: maintainer, maintainer: open, type: update

#7275 swi-prolog-lite: discontinued port
  lang/swi-prolog-lite/Portfile
  lang/swi-prolog/Portfile
Labels: maintainer

#7326 py-dulwich: update to 0.19.16; add python38 variant
  python/py-dulwich/Portfile
Labels: by: member, maintainer: open, type: update

#7343 virt-manager: add app bundle for the quartz variant
  _resources/port1.0/group/app-1.0.tcl
  gnome/virt-manager/Portfile
  gnome/virt-manager/files/virt-manager.sh
Labels: by: member, maintainer, maintainer: open, type: enhancement

#7280 stlink: update to 1.6.1
  cross/stlink/Portfile
  cross/stlink/files/patch-CMakeList.txt.diff
  cross/stlink/files/patch-cmake-modules-FindLibUSB.cmake.diff
Labels: maintainer, maintainer: open, type: bugfix, type: enhancement, type: security fix, type: update

#7281 spim: update to version 9.1.22
  emulators/spim/Portfile
Labels: maintainer, maintainer: open, type: enhancement, type: update

#7434 py-isodate: update to version 0.6.0
  python/py-isodate/Portfile
  python/py-isodate/files/patch-avoid-unclosed-file-warning.diff
  python/py-isodate/files/patch-fix-py38-deprecationwarning.diff
Labels: by: member, maintainer: requires approval, type: update

#7429 spring-boot-cli: update to 2.3.1.RELEASE
  java/spring-boot-cli/Portfile
Labels: maintainer, maintainer: open, type: update

#7435 beanstalkd: enable persistent storage
  sysutils/beanstalkd/Portfile
Labels: maintainer: none

#7441 ttyrec: Fix "Out of pty's" error
  sysutils/ttyrec/Portfile
  sysutils/ttyrec/files/patch-ttyrec.c-openpty-in-utilh.diff
Labels: by: member, maintainer, maintainer: open, type: bugfix

#7438 FAudio: Update to 20.06
  audio/FAudio/Portfile
Labels: maintainer: none, type: enhancement, type: update

#7024 jq: Replace oniguruma5 with oniguruma6
  sysutils/jq/Portfile
Labels: by: member, maintainer, maintainer: open, type: enhancement

#7317 jsoncpp: Update to 1.9.3
  devel/jsoncpp/Portfile
  devel/jsoncpp/files/patch-disable-ccache.diff
  devel/jsoncpp/files/patch-fix-build.release.diff
Labels: by: member, maintainer: open, type: update

#7447 alertmanager: update to 0.21.0
  net/alertmanager/Portfile
Labels: maintainer, maintainer: open, type: update

#7445 logtalk: update to 3.39.0
  lang/logtalk/Portfile
Labels: maintainer, type: update

#7448 semgrep: update to 0.11.0
  devel/semgrep/Portfile
Labels: maintainer, maintainer: open, type: update

#7437 utahfs: new port
  fuse/utahfs/Portfile
Labels: type: submission

#7436 node_exporter: update to 1.0.1
  net/node_exporter/Portfile
Labels: maintainer, maintainer: open, type: update

#7425 cargo: update to 0.44.0
  devel/cargo/Portfile
Labels: maintainer: none, type: update

#7409 dovecot: Update to version 2.3.10.1
  mail/dovecot/Portfile
Labels: maintainer: open, type: update

#6909 libpcl: fix build with Boost 1.70+, use compiler.openmp_version
  gis/libpcl/Portfile
  gis/libpcl/files/boost170.patch
Labels: maintainer: requires approval, maintainer: timeout, type: enhancement

#7449 raceintospace: define MAXPATHLEN if needed
  games/raceintospace/Portfile
  games/raceintospace/files/patch-racespace-maxpathlen.diff
Labels: by: member, maintainer: open

#7455 buildbot: update to 2.8.2
  devel/buildbot-2/Portfile
  devel/buildbot-worker/Portfile
  python/py-buildbot-console-view/Portfile
  python/py-buildbot-grid-view/Portfile
  python/py-buildbot-pkg/Portfile
  python/py-buildbot-waterfall-view/Portfile
  python/py-buildbot-www/Portfile
  python/py-buildbot/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#7458 yaegi: update to 0.8.8
  devel/yaegi/Portfile
Labels: maintainer, maintainer: open, type: update

#7456 beekeeper-studio: update to 1.5.2
  aqua/beekeeper-studio/Portfile
Labels: maintainer, maintainer: open, type: update

#7454 google-cloud-sdk: update to 297.0.1
  devel/google-cloud-sdk/Portfile
Labels: maintainer, maintainer: open, type: update

#7459 xdelta: Add file's size to checksums and set maintainer to nomaintainer
  archivers/xdelta/Portfile
Labels: by: member, maintainer: open, type: enhancement

#7462 xsv: Update maintainer and add additional checksums and sizes for crates
  textproc/xsv/Portfile
Labels: by: member, maintainer: open, type: enhancement, type: update
