Repository macports/macports-ports, pull requests merged in 2020-12, with the labels that each got.

#9295 emacs{,-app}-devel: fix fetch for +nativecomp
  editors/emacs/Portfile
Labels: by: member, maintainer: open, type: bugfix

#9281 cc65: update 2.19
  lang/cc65/Portfile
  lang/cc65/files/patch-doc-Makefile.diff
Labels: maintainer: none, type: enhancement, type: update

#9305 nccmp: update to 1.8.8.0
  science/nccmp/Portfile
Labels: maintainer, maintainer: open, type: enhancement, type: update

#9306 Gildas: update to 202012a
  science/gildas/Portfile
Labels: maintainer, type: update

#9297 dbeaver-community: update to 7.3.0
  databases/dbeaver-community/Portfile
Labels: maintainer, maintainer: open, type: update

#9278 ripgrep-all: new port
  textproc/ripgrep-all/Portfile
Labels: by: member, type: submission

#9279 ali: new port
  www/ali/Portfile
Labels: by: member, type: submission

#9280 please: new port
  devel/please/Portfile
Labels: by: member, type: submission

#9298 abduco: new port
  sysutils/abduco/Portfile
Labels: by: member, type: submission

#9300 libsbml: update to version 5.19.0
  science/libsbml/Portfile
  science/libsbml/files/patch-readSBML-py.diff
Labels: maintainer, maintainer: open, type: enhancement, type: update

#9296 podman: new port
  sysutils/podman/Portfile
Labels: type: enhancement, type: submission

#9290 smithy: new port
  devel/smithy/Portfile
Labels: by: member, type: submission

#9263 librsvg: revert to pre-cargo version on Apple Silicon
  graphics/librsvg/Portfile
Labels: maintainer: open, type: bugfix

#9308 py-rich: update to 9.3.0
  python/py-rich/Portfile
Labels: maintainer, maintainer: open, type: enhancement, type: update

#9312 commitizen: update to 2.9.0
  devel/commitizen/Portfile
Labels: maintainer, maintainer: open, type: enhancement, type: update

#9316 SilentKnight: update to 1.15
  sysutils/SilentKnight/Portfile
Labels: maintainer, maintainer: open, type: update

#9317 topgrade: update to 6.0.1
  sysutils/topgrade/Portfile
Labels: maintainer, maintainer: open, type: update

#9307 libarchive: upgrade to 3.5.0
  archivers/libarchive/Portfile
  archivers/libarchive/files/patch-libarchive__archive_read_support_format_lha.c.diff
Labels: by: member, maintainer: open, type: enhancement

#9320 drupal7: update to 7.76
  www/drupal7/Portfile
Labels: maintainer: none, type: bugfix, type: enhancement, type: security fix, type: update

#9313 skaffold: update to 1.17.1
  devel/skaffold/Portfile
Labels: maintainer, maintainer: open, type: update

#9265 testdisk: update to 7.1
  sysutils/testdisk/Portfile
  sysutils/testdisk/files/patch-testdisk-new-libewf.diff
Labels: maintainer: none, type: update

#9319 py-appnope: Add missing setuptools dependency
  python/py-appnope/Portfile
Labels: by: member, maintainer: open, type: bugfix

#9321 py-curl: update to 7.43.0.6
  python/py-curl/Portfile
Labels: maintainer: none, type: bugfix, type: update

#9175 gegl: remove disused dependency on w3m
  graphics/gegl/Portfile
Labels: by: member, maintainer: open

#9273 asciinema: update Python dependency to version 3.8
  sysutils/asciinema/Portfile
Labels: maintainer: requires approval, maintainer: timeout, type: bugfix, type: enhancement, type: update

#9328 groovy: update to 3.0.7
  lang/groovy/Portfile
Labels: maintainer, maintainer: open, type: update

#9322 py-m2crypto: update to 0.36.0
  python/py-m2crypto/Portfile
Labels: maintainer: open, type: enhancement, type: update

#9318 terraform: new sub-port for Terraform 0.14
  sysutils/terraform/Portfile
Labels: by: member, maintainer, maintainer: open

#9000 pgbouncer: update to 1.14.0
  databases/pgbouncer/Portfile
Labels: maintainer: none, type: enhancement, type: update

#8979 git: fix trace build, patch fuzz and offsets
  devel/git/Portfile
  devel/git/files/patch-Makefile.diff
  devel/git/files/patch-git-gui-Makefile.diff
  devel/git/files/patch-sha1dc-older-apple-gcc-versions.diff
Labels: maintainer: open, type: bugfix

#8720 usd: new port
  graphics/usd/Portfile
  graphics/usd/files/patch-add-blender-mods.diff
  graphics/usd/files/patch-plugins-output-paths.diff
  graphics/usd/files/patch-tests-output-paths.diff
Labels: type: submission

#9176 babl: make w3m an optional dependency via +doc variant
  graphics/babl/Portfile
Labels: by: member, maintainer: open

#9272 minicom: make kermit support a variant
  comms/minicom/Portfile
Labels: maintainer: none, type: enhancement

#9332 commitizen: update to 2.10.0 and add bash completion
  devel/commitizen/Portfile
Labels: maintainer, maintainer: open, type: enhancement, type: update

#9333 gping: update to 1.1.0
  net/gping/Portfile
Labels: maintainer, maintainer: open, type: enhancement, type: update

#9335 iperf3{,-devel}: update to {3.9, 20201204}
  net/iperf3/Portfile
Labels: maintainer, maintainer: open, type: update

#9334 py-typing: update to 3.7.4.3
  python/py-typing/Portfile
Labels: maintainer, maintainer: open, type: update

#9310 litecli: update to 1.4.1
  databases/litecli/Portfile
  databases/litecli/files/setup.py.diff
Labels: maintainer: open, type: update

#9314 Mame: Update to 0.226
  emulators/mame/Portfile
  emulators/mame/files/mame-patch-0226-language-portuguese_brazil.diff
  emulators/mame/files/mame-patch-0226-scripts-genie-compile-warnings.diff
  emulators/mame/files/mame-script-template-launcher.sh
Labels: maintainer: none, type: update

#9324 osc: update to 0.171.0
  devel/osc/Portfile
Labels: maintainer: open, type: enhancement, type: update

#9338 k9s: update to 0.24.2
  sysutils/k9s/Portfile
Labels: maintainer, maintainer: open, type: update

#9337 mpv: fix building on apple silicon
  multimedia/mpv/Portfile
Labels: maintainer: open, type: enhancement

#9341 emacs-deve: upgrade nativecomp branch
  editors/emacs/Portfile
Labels: maintainer: open, type: bugfix

#9340 py-geoip: add python3.{7,8,9}
  python/py-geoip/Portfile
Labels: maintainer: none

#9339 oksh: update to 6.8.1
  shells/oksh/Portfile
Labels: maintainer, maintainer: open, type: update

#9336 x264: fix building on apple silicon
  multimedia/x264/Portfile
  multimedia/x264/files/patch-x264-apple-silicon.diff
Labels: maintainer: open, type: enhancement

#9342 syncthing: update to 1.12.0
  net/syncthing/Portfile
Labels: maintainer: open, type: bugfix, type: enhancement, type: update

#9344 podman: update to 2.2.0
  sysutils/podman/Portfile
Labels: maintainer: none, type: enhancement, type: update

#9346 octave-ltfat: Update to 2.4.0
  math/octave-ltfat/Portfile
Labels: by: member, maintainer: open, type: update

#9349 Mame: Portfile license fix, allowing binaries to be published
  emulators/mame/Portfile
Labels: maintainer, maintainer: open, type: bugfix

#9356 asymptote: update to 2.68
  graphics/asymptote/Portfile
Labels: by: member, maintainer, maintainer: open, type: bugfix, type: update

#9351 py-rfc6555: new port
  python/py-rfc6555/Portfile
Labels: type: enhancement, type: submission

#9309 py-pyobjc: upgrade to 7.0.1
  python/py-pyobjc/Portfile
Labels: by: member, type: enhancement

#9362 gping: update to 1.2.0
  net/gping/Portfile
Labels: maintainer, maintainer: open, type: enhancement, type: update

#9357 kube-ps1: update default kubectl dependency to kubectl-1.19
  sysutils/kube-ps1/Portfile
Labels: maintainer, maintainer: open, type: enhancement, type: update

#9303 py-kaptan: add Python 3.9 support
  python/py-kaptan/Portfile
Labels: maintainer: open

#9353 materialx: update to version 1.37.3
  graphics/materialx/Portfile
  graphics/materialx/files/patch-use-macports-nanogui.diff
Labels: maintainer, maintainer: open, type: update

#9365 topgrade: update to 6.0.2
  sysutils/topgrade/Portfile
Labels: maintainer, maintainer: open, type: update

#8939 tktable: fix remaining compiler warnings
  x11/tktable/Portfile
  x11/tktable/files/patch-CONST86.diff
  x11/tktable/files/patch-INT2PTR.diff
  x11/tktable/files/patch-quartz.diff
Labels: maintainer: none

#9247 gnupg2: Remove +openldap from default variants
  mail/gnupg2/Portfile
Labels: by: member, maintainer: open, type: enhancement

#9350 DiffPDF: new port
  graphics/DiffPDF/Portfile
  graphics/DiffPDF/files/patch-include-poppler-qt4.diff
Labels: type: submission

#9364 scdoc: update to 1.11.1
  textproc/scdoc/Portfile
  textproc/scdoc/files/0001-Adjust-flags-for-MacPorts.patch
  textproc/scdoc/files/patch-0001-adjust-makefile-flags.diff
Labels: by: member, maintainer: none, type: update

#9368 gcc-devel for ARM64: update to 11-20201205
  lang/gcc-devel/Portfile
Labels: by: member, maintainer: none, type: enhancement, type: update

#9370 commitizen: add setuptools as a library dependency
  devel/commitizen/Portfile
Labels: maintainer, maintainer: open, type: bugfix

#9371 folderify: fix dependency categories
  sysutils/folderify/Portfile
Labels: maintainer, maintainer: open, type: bugfix

#9373 igraph: update to 0.8.5
  math/igraph/Portfile
Labels: maintainer, maintainer: open, type: bugfix, type: update

#9363 fd: update to 8.2.0
  sysutils/fd/Portfile
Labels: by: member, maintainer: open, type: update

#7387 nektarpp: new port
  science/nektarpp/Portfile
  science/nektarpp/files/avoid-python-install.patch
  science/nektarpp/files/no-homebrew.patch
  science/nektarpp/files/thirdparty-sources.patch
Labels: type: submission

#9352 offlineimap: update version to 7.3.3
  mail/offlineimap/Portfile
Labels: maintainer: none, type: update

#9348 FAudio: Update to 20.12
  audio/FAudio/Portfile
  audio/FAudio/files/faudio.pc
Labels: maintainer: none, type: update

#9330 babl-devel: make w3m an optional dependency via +docs variant
  graphics/babl-devel/Portfile
Labels: by: member, maintainer: requires approval, maintainer: timeout

#9380 gnutls: simplify compiler selection
  devel/gnutls/Portfile
Labels: by: member, maintainer: open, type: bugfix

#9367 ccls: include clang-11 support
  devel/ccls/Portfile
Labels: maintainer: open

#9294 dvtm: update to 0.15
  sysutils/dvtm/Portfile
  sysutils/dvtm/files/patch-src-Makefile.diff
  sysutils/dvtm/files/patch-src-config.mk.diff
Labels: by: member, maintainer: requires approval, maintainer: timeout, type: update

#9383 openssl: Update to 1.1.1i
  devel/openssl/Portfile
  devel/openssl/files/darwin64-arm64-cc.patch
Labels: by: member, maintainer, maintainer: open, type: bugfix, type: security fix, type: update

#9377 jenkins-cli: update to 0.0.32
  devel/jenkins-cli/Portfile
Labels: maintainer, maintainer: open, type: enhancement, type: update

#9376 py-segno: add setuptools as a library dependency
  python/py-segno/Portfile
Labels: maintainer, maintainer: open, type: bugfix

#9375 py-pyqrcodeng: fix dependency categories
  python/py-pyqrcodeng/Portfile
Labels: maintainer, maintainer: open, type: bugfix

#9374 py-commonmark: dependency fix and test added
  python/py-commonmark/Portfile
Labels: maintainer, maintainer: open, type: bugfix

#9372 gitlint: fix dependency categories
  devel/gitlint/Portfile
Labels: maintainer, maintainer: open, type: bugfix

#9378 cmake: fix Qt GUI to be great again!
  devel/cmake/Portfile
  devel/cmake/files/Info.plist.in
  devel/cmake/files/macports.cmake
  devel/cmake/files/patch-Modules-noArchCheck.diff
  devel/cmake/files/patch-cmake-leopard-tiger.diff
  devel/cmake/files/patch-qt4gui.diff
  devel/cmake/files/patch-qt5gui.diff
Labels: by: member, maintainer, type: bugfix

#9384 libid3tag: update to version 0.15.1c
  audio/libid3tag/Portfile
Labels: maintainer: none, type: bugfix, type: update

#9388 micronaut: update to 2.2.1
  java/micronaut/Portfile
Labels: maintainer, maintainer: open, type: update

#9386 kotlin: update to 1.4.21
  lang/kotlin/Portfile
Labels: maintainer, maintainer: open, type: update

#9315 poppler: upgrade to 20.12.0
  graphics/poppler/Portfile
  graphics/poppler/files/patch-check-boost.diff
  graphics/poppler/files/patch-cmake_modules_PopplerMacros.cmake.diff
Labels: by: member, maintainer: open, type: enhancement

#9389 google-cloud-sdk: update to 320.0.0
  devel/google-cloud-sdk/Portfile
Labels: maintainer, maintainer: open, type: update

#9391 Mame: Fix compilation error on older MacOS/Xcode releases, for file 'src/osd/modules/file/posixfile.cpp'
  emulators/mame/Portfile
  emulators/mame/files/mame-patch-0226-src-posixfile-build-error.diff
Labels: maintainer, maintainer: open, type: bugfix

#9385 lnav: update to 0.9.0
  sysutils/lnav/Portfile
Labels: by: member, maintainer: open, type: update

#9382 clojure: update to 1.10.1.754
  lang/clojure/Portfile
Labels: maintainer, maintainer: open, type: update

#9054 MenuMeters: update to 2.1.1
  aqua/MenuMeters/Portfile
  aqua/MenuMeters/files/patch-MenuMeters.xcodeproj-project.pbxproj.diff
Labels: maintainer: open, type: update

#9395 kubectl: update to 1.20.0, 1.19.4, 1.18.12, 1.17.14
  sysutils/kubectl/Portfile
Labels: maintainer: open, type: enhancement, type: update

#9397 skaffold: update to 1.17.2
  devel/skaffold/Portfile
Labels: maintainer, maintainer: open, type: update

#9403 py-pydicom: Update to 2.1.2
  python/py-pydicom/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#9401 commitizen: update to 2.11.0
  devel/commitizen/Portfile
Labels: maintainer, maintainer: open, type: enhancement, type: update

#9381 nodejs15: add arm64 support
  devel/nodejs15/Portfile
Labels: maintainer: open, type: enhancement

#7075 xz-bootstrap: Remove nonessential features
  archivers/xz/Portfile
Labels: by: member, maintainer, maintainer: open

#9055 libreoffice: new port
  office/libreoffice/Portfile
  office/libreoffice/files/configure.patch
  office/libreoffice/files/unpack-sources-fix-for-bsd-find.patch
Labels: type: enhancement, type: submission

#9409 py-cffi: fix build on older systems
  python/py-cffi/Portfile
  python/py-cffi/files/patch-setup.py.diff
Labels: by: member, maintainer: open, type: bugfix

#9359 libmad: configure stage on Big Sur
  audio/libmad/Portfile
  audio/libmad/files/remove-optimizations.patch
Labels: maintainer: none, type: bugfix

#9417 htop: needs legacysupport
  sysutils/htop/Portfile
Labels: by: member, maintainer: open

#9421 kustomize: update to 3.9.0
  devel/kustomize/Portfile
Labels: maintainer, maintainer: open, type: update

#9420 flyway: update to v. 7.3.1
  java/flyway/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#9422 mc: update to 4.8.25
  sysutils/mc/Portfile
Labels: maintainer: none, type: bugfix, type: update

#9419 docker: update to v. 20.10.0
  devel/docker/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#9416 vf1: submission
  net/vf-1/Portfile
Labels: type: enhancement, type: submission

#9427 libqalculate: use legacysupport
  math/libqalculate/Portfile
Labels: by: member, maintainer: open

#9425 fzf: update to 0.24.4
  sysutils/fzf/Portfile
Labels: maintainer, maintainer: open, type: update

#9434 py-rich: update to 9.4.0 and test added
  python/py-rich/Portfile
Labels: maintainer, maintainer: open, type: enhancement, type: update

#9436 kubectl: update to 1.19.5, 1.18.13, 1.17.15
  sysutils/kubectl/Portfile
Labels: maintainer: open, type: enhancement, type: update

#9404 minio[-mc]: Update to latest
  www/minio-mc/Portfile
  www/minio/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#9444 cmake: variant qt5: fix faulty symbolic link 'cmake-gui'
  devel/cmake/Portfile
  devel/cmake/files/patch-qt5gui.diff
Labels: maintainer: requires approval, type: bugfix

#9443 swi-prolog-devel: Updated to version 8.3.15
  lang/swi-prolog-devel/Portfile
Labels: maintainer, maintainer: open, type: update

#9379 lynx: fix build failure due to implicit declaration
  www/lynx/Portfile
  www/lynx/files/patch-LYCharSets.diff
  www/lynx/files/patch-no-implicit-tgoto.diff
Labels: maintainer: requires approval, maintainer: timeout, type: bugfix

#7983 WIP: hdf5: update to 1.12.0
  gis/kealib/Portfile
  graphics/InsightToolkit-devel/Portfile
  graphics/field3d/Portfile
  graphics/vigra/Portfile
  graphics/vips/Portfile
  graphics/vtk/Portfile
  math/caffe/Portfile
  math/deal.ii/Portfile
  math/gnudatalanguage/Portfile
  math/mathgl/Portfile
  math/octave/Portfile
  math/shogun-devel/Portfile
  math/shogun/Portfile
  perl/p5-pdl-io-hdf5/Portfile
  python/py-h5py/Portfile
  python/py-isce2/Portfile
  python/py-netcdf4/Portfile
  python/py-nio/Portfile
  python/py-pyne/Portfile
  python/py-stfio/Portfile
  python/py-tables/Portfile
  science/ALPSCore/Portfile
  science/ALPSMaxent/Portfile
  science/H5Part/Portfile
  science/HDF5-External-Filter-Plugins/Portfile
  science/abinit/Portfile
  science/alps/Portfile
  science/armadillo/Portfile
  science/cdo/Portfile
  science/cgnslib/Portfile
  science/crystfel/Portfile
  science/digital_rf/Portfile
  science/flann/Portfile
  science/gds/Portfile
  science/gmsh/Portfile
  science/gmtk/Portfile
  science/gmtsar/Portfile
  science/grads/Portfile
  science/h4h5tools/Portfile
  science/h5utils/Portfile
  science/hdf5-lz4-plugin/Portfile
  science/hdf5/Portfile
  science/hdf5/files/update_revs.sh
  science/hdfeos5/Portfile
  science/ismrmrd/Portfile
  science/lal/Portfile
  science/libmed/Portfile
  science/lscsoft-deps/Portfile
  science/magicspp/Portfile
  science/metview/Portfile
  science/ncarg/Portfile
  science/nco/Portfile
  science/netcdf/Portfile
  science/paraview/Portfile
  science/silo/Portfile
  science/stimfit/Portfile
  science/swarm/Portfile
  science/vapor/Portfile
  science/wgrib2/Portfile
  science/xdmf/Portfile
Labels: by: member, maintainer, maintainer: open, type: update, wip

#9406 libressl: update to 3.2.3
  security/libressl/Portfile
  security/libressl/files/patch-openssldir-cert.pem.diff
Labels: maintainer: requires approval, type: update

#9449 barrier: new port
  aqua/barrier/Portfile
  aqua/barrier/files/patch-do-not-run-tests.diff
Labels: type: enhancement, type: submission

#9448 web-ext: update to 5.4.1
  devel/web-ext/Portfile
Labels: maintainer: none, type: update

#9442 py-serial: Update to v3.5.
  python/py-serial/Portfile
Labels: maintainer, maintainer: open, type: update

#9447 task: update to 2.5.2
  office/task/Portfile
Labels: maintainer: none, type: bugfix, type: update

#9439 elixir: update to version 1.11.2
  lang/elixir/Portfile
Labels: maintainer: requires approval, maintainer: timeout, type: enhancement, type: update

#9435 macos-fortress: Update macos-fortress-easylistpac
  net/macos-fortress/Portfile
Labels: maintainer, maintainer: open, type: enhancement, type: update

#9433 libmpeg2: fix arm64 build by dropping old ARM asm code
  multimedia/libmpeg2/Portfile
  multimedia/libmpeg2/files/patch-arm64.diff
Labels: maintainer: none, type: bugfix

#9412 mysql56: update to 5.6.50
  databases/mysql56/Portfile
  databases/mysql56/files/patch-storage-innobase-handler-i_s.cc.diff
Labels: maintainer: none, type: bugfix, type: enhancement, type: update

#9411 tor: update to 0.4.4.6
  security/tor/Portfile
Labels: maintainer: none, type: update

#9405 cfssl: new port
  security/cfssl/Portfile
Labels: by: member, type: submission

#9424 pass: fix bash, fish and zsh completion installation
  security/pass/Portfile
Labels: maintainer: none, type: bugfix

#9345 texmaker: new port
  tex/texmaker/Portfile
Labels: type: enhancement, type: submission

#9445 gimp-resynthesizer: new port
  graphics/gimp-resynthesizer/Portfile
  graphics/gimp-resynthesizer/files/patch-configure.diff
  graphics/gimp-resynthesizer/files/patch-python.diff
Labels: type: enhancement, type: submission

#9454 commitizen: update to 2.11.1
  devel/commitizen/Portfile
Labels: maintainer, maintainer: open, type: enhancement, type: update

#9410 tor-devel: update to 0.4.5.2-alpha
  security/tor-devel/Portfile
Labels: maintainer: none, type: update

#9423 git-chglog: Submission of new port (v0.9.1)
  sysutils/git-chglog/Portfile
Labels: type: submission

#9457 zstd: update to 1.4.7
  archivers/zstd/Portfile
Labels: by: member, maintainer: none, type: update

#9453 libreoffice: update to 7.0.4.2
  office/libreoffice/Portfile
Labels: maintainer, maintainer: open, type: update

#9459 google-cloud-sdk: update to 321.0.0
  devel/google-cloud-sdk/Portfile
Labels: maintainer, maintainer: open, type: update

#9460 mbedtls: Use github portgroup
  devel/mbedtls/Portfile
Labels: by: member, maintainer: open

#9461 py-rich: update to 9.5.0
  python/py-rich/Portfile
Labels: maintainer, maintainer: open, type: enhancement, type: update

#9402 chafa: new port
  graphics/chafa/Portfile
Labels: by: member, type: submission

#9458 qgis3: update to 3.16.1 & fix cmakelists patch
  gis/qgis3/Portfile
  gis/qgis3/files/patch-CMakelists_txt.diff
Labels: by: member, maintainer: open, type: update

#9466 cloudflared: update to 2020.11.11
  net/cloudflared/Portfile
Labels: by: member, maintainer: open, type: update

#9451 openssh: update to 8.4p1, drop keychain patch and hpn variant
  net/openssh/Portfile
  net/openssh/files/0002-Apple-keychain-integration-other-changes.patch
  net/openssh/files/macports-config.patch
  net/openssh/files/openssh-8.1p1-gsskex-all-20141021-mp-20201216.patch
  net/openssh/files/patch-openbsd_compat-memmem-bug.diff
Labels: by: member, maintainer: none, type: security fix, type: update

#9471 py-rich: update to 9.5.1
  python/py-rich/Portfile
Labels: maintainer, maintainer: open, type: enhancement, type: update

#9470 libreoffice: accept macOS 11.1 SDK
  office/libreoffice/Portfile
  office/libreoffice/files/accept-macos-11.1.patch
Labels: maintainer, maintainer: open, type: bugfix

#9469 py-outcome: update to 1.1.0, remove py27, py35
  python/py-outcome/Portfile
Labels: maintainer, maintainer: open, type: bugfix, type: enhancement, type: update

#9472 kubectl: update to 1.20.1, 1.19.6, 1.18.14, 1.17.16
  sysutils/kubectl/Portfile
Labels: maintainer: open, type: enhancement, type: update

#9467 qgis3: drop python35 & build with proj7 & default to python38
  gis/qgis3/Portfile
Labels: by: member, maintainer: open, type: enhancement

#9446 mame: add variant 'debug'; soft link tools in ${prefix}/bin; add tools man pages; improve link time; reduce warnings; eliminate superfluous files; remove variant 'python36'
  emulators/mame/Portfile
  emulators/mame/files/mame-patch-0226-scripts-genie-compile-warnings.diff
Labels: maintainer, maintainer: open, type: bugfix, type: enhancement

#9477 python39: tweak copyfile patch
  lang/python39/files/patch-no-copyfile-on-Tiger.diff
Labels: by: member, maintainer: requires approval

#9481 ghc: Update to version 10.8.3
  lang/ghc/Portfile
Labels: maintainer, maintainer: open, type: enhancement, type: update

#9479 py-questionary: update to 1.9.0
  python/py-questionary/Portfile
Labels: maintainer, maintainer: open, type: enhancement, type: update

#9301 py-tmuxp: fix 1.6.3 checksums
  python/py-tmuxp/Portfile
Labels: maintainer: open, type: bugfix
