Repository macports/macports-ports, pull requests merged in 2020-09, with the labels that each got.

#8277 py-prompt_toolkit: update to 3.0.7
  python/py-prompt_toolkit/Portfile
Labels: by: member, maintainer: open, type: update

#8245 gh: add LegacySupport tweaks for OSX <= 10.9
  devel/gh/Portfile
Labels: by: member, maintainer: open, type: bugfix

#8251 boost: add basic support for ARM64
  devel/boost/Portfile
  devel/boost/files/patch-add-support-for-arm64.diff
Labels: by: member, maintainer, maintainer: open, type: enhancement

#8284 logtalk: update to 3.41.0
  lang/logtalk/Portfile
Labels: maintainer, type: update

#8286 stack: Update to version 2.3.3
  lang/stack/Portfile
Labels: maintainer, maintainer: open, type: enhancement, type: update

#8254 git-interactive-rebase-tool: New port
  devel/git-interactive-rebase-tool/Portfile
Labels: type: submission

#8271 py-asciimatics: new port
  python/py-asciimatics/Portfile
Labels: type: submission

#8213 xorg-server: update to 1.20.9
  x11/xorg-server/Portfile
  x11/xorg-server/files/1001-XQuartz-Hack-around-an-issue-that-can-occur-on-macOS.patch
  x11/xorg-server/files/CVE-2020-14347.diff
Labels: maintainer: open, type: security fix, type: update

#8263 htop: update to 3.0.0
  sysutils/htop/Portfile
Labels: maintainer: open, type: update

#8289 go: update to 1.15.1
  lang/go/Portfile
Labels: by: member, maintainer: open, type: update

#8236 blender: new port
  graphics/blender/Portfile
  graphics/blender/files/old_appkit_compat/AppKit/AppKit.h
  graphics/blender/files/patch-macports-libs-creator.diff
  graphics/blender/files/patch-macports-libs-platform_apple.diff
  graphics/blender/files/patch-manpage-for-apple.diff
  graphics/blender/files/patch-unix-or-apple.diff
Labels: type: submission

#8291 py-slackclient: update to v2.8.1
  python/py-slackclient/Portfile
Labels: maintainer, maintainer: open, type: update

#8288 gimp-save-for-web: new port
  graphics/gimp-save-for-web/Portfile
  graphics/gimp-save-for-web/files/patch-autogen.sh.diff
Labels: type: enhancement, type: submission

#8299 skaffold: update to 1.14.0
  devel/skaffold/Portfile
Labels: maintainer, maintainer: open, type: update

#8303 openldap: update to 2.4.52
  databases/openldap/Portfile
  databases/openldap/files/libressl.patch
Labels: maintainer: none, type: bugfix, type: enhancement, type: update

#8252 rust: update to 1.46.0
  lang/rust/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#8302 py-boltons: new port
  python/py-boltons/Portfile
Labels: type: enhancement, type: submission

#8305 LyX: remove reminder comment
  aqua/LyX/Portfile
Labels: maintainer: open

#8306 chromaprint: use compiler.cxx_standard 2011
  audio/chromaprint/Portfile
Labels: maintainer: open

#8293 Gildas: update to 202009a
  science/gildas/Portfile
Labels: maintainer, type: update

#8297 google-cloud-sdk: update to 308.0.0
  devel/google-cloud-sdk/Portfile
Labels: maintainer, maintainer: open, type: update

#8292 ViennaRNA: update to v2.4.15
  science/ViennaRNA/Portfile
Labels: maintainer, maintainer: open, type: update

#8301 web-ext: update to 5.0.0
  devel/web-ext/Portfile
Labels: maintainer: none, type: update

#8310 quartz-wm: Enable Xplugin dock support on 10.8+
  x11/quartz-wm/Portfile
Labels: by: member, maintainer: open

#8307 grepcidr: add the makefile PG
  sysutils/grepcidr/Portfile
Labels: maintainer: none, type: update

#8311 libsdl2: Fix build on arm64 Macs
  devel/libsdl2/Portfile
  devel/libsdl2/files/arm.patch
Labels: by: member, maintainer: open

#8313 minikube: update to 1.13.0
  sysutils/minikube/Portfile
Labels: maintainer: open, type: enhancement, type: update

#8320 oniguruma6: update to v6.9.5_rev1
  devel/oniguruma6/Portfile
Labels: maintainer: open, type: bugfix, type: update

#8319 gitlab-runner: update to 13.3.1
  devel/gitlab-runner/Portfile
Labels: maintainer, maintainer: open, type: update

#8317 recoll: use compiler.cxx_standard 2011
  textproc/recoll/Portfile
Labels: maintainer: open

#8316 guetzli, lirc: use compiler.cxx_standard 2011
  graphics/guetzli/Portfile
  sysutils/lirc/Portfile
Labels: maintainer: open

#8315 creduce: use compiler.cxx_standard 2011
  devel/creduce/Portfile
Labels: maintainer: requires approval

#8283 py-bpemb: Submission of py-bpemb
  python/py-bpemb/Portfile
  python/py-gensim/Portfile
Labels: type: enhancement, type: submission

#7878 libsodium: Update to 1.0.18-20200728
  devel/libsodium/Portfile
Labels: by: member, maintainer: open, type: update

#7581 espeak-ng: new port, version 1.50
  audio/espeak-ng/Portfile
  audio/espeak-ng/files/patch-espeak-ng-mac.diff
  audio/pcaudiolib/Portfile
  audio/sonic/Portfile
  audio/sonic/files/patch-sonic-mac.diff
Labels: type: submission

#8309 cmake: Fix build on 10.4.
  devel/cmake/files/patch-cmake-leopard-tiger.diff
Labels: maintainer: requires approval, type: bugfix

#8308 mesos: use compiler.cxx_standard 2011
  devel/mesos/Portfile
Labels: maintainer: open

#8322 htop: update to 3.0.1
  sysutils/htop/Portfile
Labels: maintainer: open, type: bugfix, type: update

#8323 gnupg2: Update to 2.2.23
  mail/gnupg2/Portfile
Labels: by: member, maintainer: open, type: security fix, type: update

#8321 p5-class-tiny: update to version 1.008
  perl/p5-class-tiny/Portfile
Labels: by: member, maintainer: open, type: update

#8327 dvisvgm: add dependency xxhashlib, rebuild
  graphics/dvisvgm/Portfile
Labels: by: member, maintainer: open, type: bugfix

#8333 grepcidr: use MP flags
  sysutils/grepcidr/Portfile
  sysutils/grepcidr/files/patch-ldflags.diff
Labels: maintainer: none, type: update

#8298 gmt6: update to 6.1.1
  science/gmt5/Portfile
Labels: maintainer: open, type: update

#8334 llvm*: Use known_fail yes correctly
  lang/llvm-10/Portfile
  lang/llvm-3.3/Portfile
  lang/llvm-3.4/Portfile
  lang/llvm-3.7/Portfile
  lang/llvm-5.0/Portfile
  lang/llvm-6.0/Portfile
  lang/llvm-7.0/Portfile
  lang/llvm-8.0/Portfile
  lang/llvm-9.0/Portfile
  lang/llvm-devel/Portfile
  lang/llvm-gcc42/Portfile
Labels: by: member, maintainer: requires approval

#8296 py-questionary: new port
  python/py-questionary/Portfile
Labels: type: enhancement, type: submission

#8332 p5-log-log4perl: update to version 1.51
  perl/p5-log-log4perl/Portfile
Labels: by: member, maintainer: open, type: update

#8282 narrow libodbc conflict
  databases/unixODBC/Portfile
  devel/libiodbc/Portfile
Labels: by: member, maintainer, maintainer: open, type: bugfix

#8336 FAudio: Update to 20.09
  audio/FAudio/Portfile
Labels: maintainer: none, type: enhancement, type: update

#8340 mednafen: update to 1.24.3
  emulators/mednafen/Portfile
Labels: maintainer: none, type: update

#8304 ctlang, gdcm2, luminance-hdr, olena: use compiler.cxx_standard 2011
  aqua/luminance-hdr/Portfile
  devel/olena/Portfile
  graphics/ctlang/Portfile
  science/gdcm2/Portfile
Labels: maintainer: open

#8294 elasticsearch: update to 7.9.0
  databases/elasticsearch/Portfile
  databases/elasticsearch/files/patch-elasticsearch-env.diff
  databases/elasticsearch/files/patch-jvm-options.diff
Labels: by: member, maintainer: open, type: update

#8285 eksctl: update to 0.26.0
  sysutils/eksctl/Portfile
Labels: by: member, maintainer: open, type: update

#8312 croc: new port
  net/croc/Portfile
Labels: by: member, type: submission

#8338 notmuch: Update to 0.31
  mail/notmuch/Portfile
Labels: maintainer, maintainer: open, type: update

#8339 tcsh: update to 6.22.02
  shells/tcsh/Portfile
Labels: by: member, maintainer: none, type: update

#8295 sccs: new port
  devel/sccs/Portfile
  devel/sccs/files/patch-bdiff.diff
  devel/sccs/files/patch-delta.diff
  devel/sccs/files/patch-diff.diff
  devel/sccs/files/patch-help.diff
  devel/sccs/files/patch-sccs.diff
Labels: type: submission

#8337 jenkins-cli: new port
  devel/jenkins-cli/Portfile
Labels: type: enhancement, type: submission

#8352 nanopass-scheme: update to 1.9.1
  scheme/nanopass-scheme/Portfile
Labels: maintainer, maintainer: open, type: update

#8353 scc: update to 2.13.0
  devel/scc/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#8354 croc: update to 8.3.1
  net/croc/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#8326 glslang: use compiler.cxx_standard 2011
  graphics/glslang/Portfile
  graphics/spirv-tools/Portfile
  graphics/vulkan-headers/Portfile
  graphics/vulkan-loader/Portfile
  graphics/vulkan-tools/Portfile
  graphics/vulkan-validationlayers/Portfile
Labels: maintainer: open

#8357 shellharden: new port
  devel/shellharden/Portfile
Labels: by: member, type: submission

#8355 deco-archive: update to 1.7
  archivers/deco-archive/Portfile
Labels: by: member, maintainer: none, type: update

#8358 syncthing: update to 1.9.0
  net/syncthing/Portfile
Labels: maintainer: open, type: bugfix, type: enhancement, type: update

#8344 pipx: update to 0.15.5.1
  python/pipx/Portfile
Labels: by: member, maintainer: open

#8343 py-argcomplete: update to 1.12.0
  python/py-argcomplete/Portfile
Labels: by: member, maintainer: open, type: update

#8359 fluent-bit: update to 1.5.5
  sysutils/fluent-bit/Portfile
Labels: by: member, maintainer: open, type: update

#8360 swi-prolog-devel: Updated to version 8.3.7
  lang/swi-prolog-devel/Portfile
Labels: maintainer, maintainer: open, type: update

#8351 py-crank: new port
  python/py-crank/Portfile
Labels: type: submission

#8356 deco: update to 1.6.4
  archivers/deco/Portfile
Labels: by: member, maintainer: none, type: update

#8361 llvm-3.7: fix fuzz and offset in patch
  lang/llvm-3.7/files/llvm-skip-unittests.patch
Labels: maintainer: requires approval

#8324 git: Use Python 3.8
  devel/git/Portfile
Labels: by: member, maintainer: open, type: enhancement

#8362 php: enable file based opcache, and update current versions
  lang/php/Portfile
Labels: maintainer: requires approval, type: enhancement

#8373 evans: fix checksums
  devel/evans/Portfile
Labels: maintainer: open

#8370 google-cloud-sdk: update to 309.0.0
  devel/google-cloud-sdk/Portfile
Labels: maintainer, maintainer: open, type: update

#8325 bzflag: use compiler.cxx_standard 2011
  games/bzflag/Portfile
Labels: maintainer: open

#8346 mesos: attempt to fix build on 10.11 and earlier
  devel/mesos/Portfile
Labels: maintainer: open

#8371 fluent-bit: attempt to fix build on 10.11 and earlier
  sysutils/fluent-bit/Portfile
Labels: maintainer: open

#8377 go: update to 1.15.2
  lang/go/Portfile
Labels: by: member, maintainer: open, type: update

#8380 qbs: Update to 1.17.0
  devel/qbs/Portfile
Labels: maintainer, maintainer: open, type: update

#8381 talloc: update to 2.3.1
  devel/talloc/Portfile
  devel/talloc/files/Makefile.patch
Labels: maintainer: none, type: update

#8382 bwping: update to 2.0
  net/bwping/Portfile
Labels: maintainer, maintainer: open, type: update

#8376 sleuthkit: requires C++14
  sysutils/sleuthkit/Portfile
Labels: maintainer: none

#8364 openssl11: remove obsolete port
  devel/openssl11/Portfile
Labels: maintainer: none

#8388 osmocore(-devel): add missing libusb dependency
  science/osmocore/Portfile
Labels: maintainer: open, type: bugfix

#8366 cherokee: update to 1.2.204
  www/cherokee/Portfile
Labels: by: member, maintainer: none, type: update

#8314 ade, chipmunk, geos, libdynd: use compiler.cxx_standard
  devel/ade/Portfile
  devel/chipmunk/Portfile
  devel/libdynd/Portfile
  science/geos/Portfile
Labels: maintainer: open

#8386 pulseaudio: Fix build error for Xcode 12 CLT
  audio/pulseaudio/Portfile
  audio/pulseaudio/files/patch-src_modules_macosx_module_coreaudio_device.c-import-util-h.diff
Labels: maintainer: open, type: bugfix

#8379 libffi: fix darwin powerpc build
  devel/libffi/Portfile
  devel/libffi/files/patch-libffi-darwin-powerpc-no-go-closures.diff
Labels: by: member, maintainer: none, type: bugfix, type: enhancement

#8395 zmq22, zmq3: fix build
  devel/zmq/Portfile
  devel/zmq/files/patch-zmq22-src_select.cpp.diff
  devel/zmq/files/patch-zmq3-src_select.cpp.diff
Labels: maintainer: open

#8405 blender: update to version 2.83.0
  graphics/blender/Portfile
  graphics/blender/files/patch-macports-libs-creator.diff
  graphics/blender/files/patch-macports-libs-platform_apple.diff
  graphics/blender/files/patch-manpage-for-apple.diff
  graphics/blender/files/patch-unix-or-apple.diff
Labels: maintainer, type: update

#7424 cdf: use makefile PG; allow build with GCC 10
  science/cdf/Portfile
Labels: by: member, maintainer: open, type: bugfix

#8402 syncthing-macos: update version to 1.9.0-1
  net/syncthing-macos/Portfile
  net/syncthing-macos/files/no-bundled-syncthing.patch
Labels: maintainer: open, type: update

#8411 k9s: update to 0.21.9
  sysutils/k9s/Portfile
Labels: maintainer, maintainer: open, type: update

#8412 micronaut: update to 2.0.2
  java/micronaut/Portfile
Labels: maintainer, maintainer: open, type: update

#8413 kotlin: update to 1.4.10
  lang/kotlin/Portfile
Labels: maintainer, maintainer: open, type: update

#8414 spring-boot-cli: update to 2.3.3.RELEASE
  java/spring-boot-cli/Portfile
Labels: maintainer, maintainer: open, type: update

#8397 chez-scheme: update to 9.5.4
  lang/chez-scheme/Portfile
  lang/chez-scheme/files/patch-c-Mf-base.diff
  lang/chez-scheme/files/patch-c-Mf-ta6osx.diff
  lang/chez-scheme/files/patch-c-Mf-ti3osx.diff
  lang/chez-scheme/files/patch-configure.diff
  lang/chez-scheme/files/patch-s-Mf-base.diff
Labels: maintainer, maintainer: open, type: update

#8418 webify: new port
  devel/webify/Portfile
Labels: type: enhancement, type: submission

#8421 mkvtoolnix: update to 50.0.0
  multimedia/mkvtoolnix/Portfile
Labels: by: member, maintainer: open, type: update

#8396 topgrade: update to 5.7.1
  sysutils/topgrade/Portfile
Labels: maintainer, maintainer: open, type: update

#8387 drill, ldns-tools: remove obsolete ports
  net/ldns/Portfile
Labels: maintainer: none

#8385 serf0: remove obsolete port
  www/serf0/Portfile
Labels: maintainer: none

#8383 trivy: new port
  security/trivy/Portfile
Labels: by: member, type: submission

#8389 elvish: new port
  shells/elvish/Portfile
Labels: by: member, type: submission

#8407 omniawrite: new port
  editors/omniawrite/Portfile
Labels: by: member, type: submission

#8367 mlt: use compiler.cxx_standard 2011
  multimedia/mlt/Portfile
Labels: maintainer: open

#8363 py-wntr: update to version 0.2.3
  python/py-wntr/Portfile
Labels: maintainer, maintainer: open, type: enhancement, type: update

#8368 kitlist: use compiler.cxx_standard 2011
  office/kitlist/Portfile
Labels: maintainer: open

#8345 spdlog: Update to 1.8.0
  devel/spdlog/Portfile
Labels: by: member, maintainer: open, type: update

#8394 esmf: use known_fail yes on 10.7 and earlier
  science/esmf/Portfile
Labels: maintainer: requires approval, maintainer: timeout

#8348 mas: update to 1.7.1
  sysutils/mas/Portfile
Labels: by: member, maintainer: open, type: update

#8342 py-userpath: update to 1.4.1
  python/py-userpath/Portfile
Labels: by: member, maintainer: open, type: update

#8399 Bear: upgrade to 2.4.4
  devel/Bear/Portfile
Labels: by: member, maintainer: open, type: enhancement

#8423 py-numpy: update to 1.19.2
  python/py-numpy/Portfile
Labels: maintainer: open, type: bugfix, type: enhancement, type: update

#8137 nanogui: update: new subport
  graphics/nanogui/Portfile
Labels: maintainer, maintainer: open, type: enhancement, type: update

#8417 gtk2: Add missing import statement
  gnome/gtk2/Portfile
  gnome/gtk2/files/patch-gtkclipboard-quartz.diff
Labels: maintainer: none, type: bugfix

#8398 emacs: Fix typo and clean up configure flags
  editors/emacs/Portfile
Labels: by: member, maintainer: open, type: bugfix, type: enhancement

#8427 hugo: update to 0.75.0
  www/hugo/Portfile
Labels: maintainer, maintainer: open, type: update

#8430 lang/sbcl: update to sbcl-2.0.8
  lang/sbcl/Portfile
  math/maxima/Portfile
Labels: by: member, maintainer: open, type: update

#8436 knot: revision 1 of version 3.0.0
  net/knot/Portfile
Labels: maintainer: open, type: enhancement

#8143 xorg-libxcb: mark Python as non-conflicting
  x11/xorg-libxcb/Portfile
Labels: by: member, maintainer: open

#8406 claws-mail: add optional dependencies dbus, dbus-glib, rebuild
  mail/claws-mail/Portfile
Labels: by: member, maintainer: open, type: bugfix

#8150 py-axolotl, py-axolotl-curve25519: add py38
  python/py-axolotl-curve25519/Portfile
  python/py-axolotl/Portfile
Labels: maintainer: none, type: enhancement

#8012 scid: update to 4.7.0
  games/scid/Portfile
  games/scid/files/patch-Makefile.conf.diff
Labels: maintainer: open, type: bugfix, type: enhancement

#8439 google-cloud-sdk: update to 310.0.0
  devel/google-cloud-sdk/Portfile
Labels: maintainer, maintainer: open, type: update

#8408 carthage: Update to 0.35.0
  devel/carthage/Portfile
Labels: maintainer: open, type: enhancement, type: update

#7641 nghttp2: separate library into a subport not depending on OpenSSL
  www/nghttp2/Portfile
Labels: by: member, maintainer: requires approval

#8453 pypy: fix build with latest Xcode
  lang/pypy/Portfile
  lang/pypy/files/fix-build.diff
Labels: by: member, maintainer, maintainer: open

#8429 htop: update to 3.0.2
  sysutils/htop/Portfile
Labels: maintainer: open, type: bugfix, type: update

#8391 libdynd: fix build
  devel/libdynd/Portfile
  devel/libdynd/files/patch-src_dynd_type.cpp.diff
Labels: maintainer: open

#8451 k9s: update to 0.22.0
  sysutils/k9s/Portfile
Labels: maintainer, maintainer: open, type: update

#8432 josm: update to 17013
  gis/JOSM/Portfile
Labels: maintainer, maintainer: open, type: enhancement, type: update

#8458 R: fix configure phase for Xcode 12
  math/R/Portfile
  math/R/files/patch-bzlib-clt12-headers.diff
Labels: maintainer: open

#8459 rancher-cli: update to 2.4.6
  devel/rancher-cli/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#8460 rke: update to 1.1.7
  devel/rke/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#8461 docker-compose: update 1.27.3
  python/docker-compose/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#8444 py-Pillow: add dummy x11 & quartz variants
  python/py-Pillow/Portfile
Labels: by: member, maintainer: open, type: bugfix

#8463 glow: don't fetch dependencies in build phase
  textproc/glow/Portfile
Labels: by: member, maintainer: open, type: bugfix

#8401 mpfr: bump to 4.1.0
  devel/mpfr/Portfile
Labels: by: member, maintainer: open, type: enhancement

#8420 blender: requires Xcode 8.2 or later
  graphics/blender/Portfile
Labels: maintainer: requires approval

#8470 avahi: reenable building manpage with xmltoman & grab maintainership
  net/avahi/Portfile
Labels: by: member, maintainer: none, type: enhancement

#8473 R: attempt to fix configure phase on 10.7
  math/R/Portfile
Labels: maintainer: open

#7257 Update: mirror_sites.tcl
  _resources/port1.0/fetch/mirror_sites.tcl
Labels: type: update

#8471 py-pytest: update to 6.0.2
  python/py-pytest/Portfile
Labels: maintainer: open, type: update

#8375 py35-jupyter_console: pin to 6.1.0
  python/py-jupyter_console/Portfile
Labels: maintainer: open

#8452 openjdk8: add subport openjdk15
  java/openjdk8/Portfile
Labels: maintainer, maintainer: open

#8472 py-colored: new port
  python/py-colored/Portfile
Labels: by: member, type: submission

#8448 qcachegrind: update to 20.08.1, Qt5
  devel/qcachegrind/Portfile
  devel/qcachegrind/files/0001-Fix-shell-invocations-for-MacPorts.patch
Labels: by: member, maintainer: requires approval, maintainer: timeout, type: update

#8390 fluent-bit: attempt to fix build on 10.7/10.8
  sysutils/fluent-bit/Portfile
Labels: maintainer: open
