Repository macports/macports-ports, pull requests merged in 2020-05, with the labels that each got.

#6984 kubectx: update to 0.9.0
  sysutils/kubectx/Portfile
Labels: maintainer, maintainer: open, type: update

#6865 rspamd: Update to 2.5
  mail/rspamd/Portfile
Labels: maintainer: none, type: update

#6955 innoextract: Update to 1.8
  archivers/innoextract/Portfile
Labels: maintainer: open, type: enhancement, type: update

#6934 npm6: default to nodejs14
  devel/npm6/Portfile
Labels: maintainer: open, type: enhancement

#6981 logcat-colorize: update to 0.9.0
  devel/logcat-colorize/Portfile
  devel/logcat-colorize/files/patch-makefile.diff
Labels: maintainer, maintainer: open, type: enhancement, type: update

#6985 qt4 PortGroup: wrap platform error in pre-fetch block
  _resources/port1.0/group/qt4-1.0.tcl
Labels: by: member, type: bugfix

#6973 R: update to 4.0.0
  math/R/Portfile
Labels: maintainer, maintainer: open, type: update

#6989 openvdb: switch python default to +python38
  graphics/openvdb/Portfile
Labels: by: member, maintainer: open, type: enhancement

#6988 k9s: update to 0.19.4
  sysutils/k9s/Portfile
Labels: maintainer, maintainer: open, type: update

#6822 mingw-gcc: update to 9.3.0
  cross/i686-w64-mingw32-gcc/Portfile
  cross/x86_64-w64-mingw32-gcc/Portfile
Labels: maintainer: open, type: enhancement, type: update

#6993 cfm: Don't set duplicate DESTDIR arg; indicate C language requirement
  sysutils/cfm/Portfile
Labels: by: member, maintainer: requires approval

#6995 bandwhich: update to 0.14.0
  net/bandwhich/Portfile
Labels: maintainer, maintainer: open, type: update

#6990 py-panedr: new port version 0.5.2
  python/py-panedr/Portfile
Labels: type: submission

#6998 py-mdtraj: added support for python 3.8
  python/py-mdtraj/Portfile
Labels: maintainer, maintainer: open

#6994 packer: update to 1.5.6
  sysutils/packer/Portfile
Labels: maintainer, maintainer: open, type: update

#6999 tmux: update to 3.1b
  sysutils/tmux/Portfile
Labels: maintainer, maintainer: open, type: update

#6992 FAudio: Update to 20.05
  audio/FAudio/Portfile
Labels: maintainer: none, type: enhancement, type: update

#6926 vtk: fix install location of python files
  graphics/vtk/Portfile
Labels: maintainer: open, type: bugfix

#7002 syncthing: update to 1.5.0
  net/syncthing/Portfile
Labels: maintainer: open, type: bugfix, type: enhancement, type: update

#7005 searchfs: fix fspatch workaround for older systems
  sysutils/searchfs/Portfile
  sysutils/searchfs/files/patch-searchfs-fsgetpath-availability.diff
Labels: by: member, maintainer: requires approval

#7013 prometheus: update to 2.18.0
  net/prometheus/Portfile
Labels: maintainer, maintainer: open, type: update

#7009 pari: update to 2.11.4
  math/pari/Portfile
Labels: maintainer, maintainer: open, type: update

#6920 wxMaxima: update to version 20.04.0 (April 2020)
  math/wxMaxima/Portfile
  math/wxMaxima/files/patch-devel-src_Dirstructure.cpp.diff
  math/wxMaxima/files/patch-src_Dirstructure.cpp.diff
  math/wxMaxima/files/patch-src_Dirstructure.h.diff
  math/wxMaxima/files/patch-src_main.cpp.diff
  math/wxMaxima/files/patch-src_wxMaxima.cpp.diff
Labels: maintainer: none, type: bugfix, type: enhancement, type: update

#7029 swi-prolog: update maintainers
  lang/swi-prolog/Portfile
Labels: maintainer, type: update

#7028 swi-prolog-devel: update maintainers
  lang/swi-prolog-devel/Portfile
Labels: maintainer, type: update

#7032 prometheus: update to 2.18.1
  net/prometheus/Portfile
Labels: maintainer, maintainer: open, type: update

#7023 google-cloud-sdk: update to 291.0.0
  devel/google-cloud-sdk/Portfile
Labels: maintainer, maintainer: open, type: update

#7021 hugo: update to 0.70.0
  www/hugo/Portfile
Labels: maintainer, maintainer: open, type: update

#7020 websocketpp: update to 0.8.2
  net/websocketpp/Portfile
Labels: maintainer, maintainer: open, type: update

#7018 apache-solr8: Update to version 8.5.1
  java/apache-solr8/Portfile
Labels: maintainer, maintainer: open, type: update

#7016 stack: Update to version 2.3.1
  lang/stack/Portfile
Labels: maintainer, maintainer: open, type: update

#7015 consul: update to 1.7.3
  net/consul/Portfile
Labels: maintainer, maintainer: open, type: update

#7000 qbs: Update to 1.16.0
  devel/qbs/Portfile
Labels: maintainer, maintainer: open, type: update

#6910 wgrib2: use compiler.openmp_version
  science/wgrib2/Portfile
Labels: maintainer: requires approval, maintainer: timeout, type: enhancement

#6991 gdal: Update to 3.0.4
  gis/gdal/Portfile
  gis/gdal/files/patch-poppler.diff
Labels: by: member, maintainer: open, type: update

#6918 borgbackup: move llfuse dependency into a variant.
  sysutils/borgbackup/Portfile
Labels: maintainer: none

#7034 gdb: Support +python38 variant
  devel/gdb/Portfile
Labels: maintainer: none, type: enhancement

#6876 skaffold: new submission
  devel/skaffold/Portfile
Labels: type: submission

#7031 JOSM: new port
  gis/JOSM/Portfile
Labels: type: enhancement, type: submission

#7037 jtc: update to 1.76
  textproc/jtc/Portfile
Labels: maintainer, maintainer: open, type: update

#6832 gptfdisk: update to 1.0.5
  sysutils/gptfdisk/Portfile
  sysutils/gptfdisk/files/patch-Makefile.mac.diff
Labels: maintainer: open, type: update

#7039 librdkafka: update to version 1.4.2
  net/librdkafka/Portfile
Labels: maintainer, maintainer: open, type: enhancement, type: update

#7042 mysql8: update to 8.0.20
  databases/mysql8/Portfile
  databases/mysql8/files/patch-cmake-sasl-disable-platform-check.diff
Labels: maintainer, maintainer: open, type: update

#7041 kafkacat: Update version to 1.5.0
  net/kafkacat/Portfile
Labels: maintainer, maintainer: open, type: update

#7045 gerbil: Update to latest master
  science/gerbil/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#7044 gitlab-runner: update to 12.10.2
  devel/gitlab-runner/Portfile
Labels: maintainer, maintainer: open, type: update

#7046 micronaut: update to 1.3.5
  java/micronaut/Portfile
Labels: maintainer, maintainer: open, type: update

#7047 cpprestsdk: update to 2.10.16
  www/cpprestsdk/Portfile
Labels: maintainer, maintainer: open, type: update

#7050 qrcp: Update to 0.6.2
  sysutils/qrcp/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#7048 pandoc: Update to 2.9.2.1
  textproc/pandoc/Portfile
Labels: by: member, maintainer: none, type: update

#7051 openttd: Update to 1.10.1
  games/openttd/Portfile
  games/openttd/files/patch-name_conflict.diff
Labels: by: member, maintainer, maintainer: open, type: update

#7049 dblatex: Update to 0.3.11
  textproc/dblatex/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#7057 php-solr: Add php74-solr subport
  php/php-solr/Portfile
  php/php-solr/files/php74.patch
Labels: maintainer: open, type: enhancement

#7056 wtfutil: update to 0.30.0
  sysutils/wtfutil/Portfile
Labels: maintainer, maintainer: open, type: update

#7067 py-ansible: trivial update to 2.9.7
  python/py-ansible/Portfile
Labels: by: member, maintainer, maintainer: open

#7070 cmake: Remove redundant or outdated comments
  devel/cmake/Portfile
Labels: by: member, maintainer: requires approval

#6996 cfm: respect MacPorts settings
  sysutils/cfm/Portfile
  sysutils/cfm/files/patch-Makefile.diff
Labels: by: member, maintainer: requires approval, type: bugfix

#7006 partio: new port
  graphics/partio/Portfile
Labels: type: submission

#7071 spring-boot-cli: update to 2.2.7
  java/spring-boot-cli/Portfile
Labels: maintainer, maintainer: open, type: update

#7068 logcat-colorize: update to 0.10.0
  devel/logcat-colorize/Portfile
Labels: maintainer, maintainer: open, type: enhancement, type: update

#7063 flatbuffers: new port
  devel/flatbuffers/Portfile
Labels: type: submission

#7064 wireguard-tools: update to 1.0.20200510
  net/wireguard-tools/Portfile
Labels: maintainer, maintainer: open, type: update

#7062 skim: new port
  sysutils/skim/Portfile
Labels: type: submission

#7058 skaffold: update to 1.9.1
  devel/skaffold/Portfile
Labels: maintainer, maintainer: open, type: update

#7069 kustomize: new submission
  devel/kustomize/Portfile
Labels: type: submission

#7061 eksctl: update to 0.18.0
  sysutils/eksctl/Portfile
Labels: maintainer: open, type: update

#7035 wgrib2: Use legacysupport for strnlen
  science/wgrib2/Portfile
Labels: by: member, maintainer: requires approval, maintainer: timeout

#7003 opencv +java: lower required Java version (again)
  graphics/opencv/Portfile
Labels: maintainer: none, type: bugfix, type: enhancement

#7027 xorg-server: add xcsecurity variant to enable the security extension
  x11/xorg-server/Portfile
Labels: by: member, maintainer: open, type: enhancement

#6911 xrmc +openmp: use compiler.openmp_version
  science/xrmc/Portfile
Labels: maintainer: none, type: enhancement

#7025 alacritty: new port
  aqua/alacritty/Portfile
Labels: type: submission

#7077 py-mdtraj: update to 1.9.4
  python/py-mdtraj/Portfile
Labels: maintainer, maintainer: open, type: update

#7078 bwping: update to 1.17
  net/bwping/Portfile
Labels: maintainer, maintainer: open, type: update

#6959 2048.cpp: fix user data overwritting and data store failure
  games/2048.cpp/Portfile
Labels: maintainer, maintainer: open, type: bugfix

#7079 google-cloud-sdk: update to 292.0.0
  devel/google-cloud-sdk/Portfile
Labels: maintainer, maintainer: open, type: update

#6881 chuck: fix build on newer versions of macOS
  audio/chuck/Portfile
  audio/chuck/files/patch-makefile.osx.diff
Labels: maintainer: open, type: bugfix

#7001 ldid: submission
  devel/ldid/Portfile
  devel/ldid/files/patch-make.sh.diff
Labels: type: submission

#6974 grafana: new port
  net/grafana/Portfile
  net/grafana/files/grafana.ini.diff
  net/grafana/files/org.macports.grafana.plist
Labels: type: submission

#6987 osquery: new port
  sysutils/osquery/Portfile
  sysutils/osquery/files/org.macports.osquery.plist
  sysutils/osquery/files/osquery.flags
  sysutils/osquery/files/patch-default_paths.h.diff
  sysutils/osquery/files/patch-lenses-path-augeas.cpp.diff
  sysutils/osquery/files/patch-macports-cmake-packaging.cmake.diff
Labels: type: submission

#7052 mpfr: use xcode_workaround PG
  devel/mpfr/Portfile
Labels: by: member, maintainer: open, type: bugfix

#7065 xcode_workaround PG: add problematic OS option
  _resources/port1.0/group/xcode_workaround-1.0.tcl
  python/py-tensorflow/Portfile
Labels: by: member, maintainer: open, type: enhancement

#6957 yabasic: update to 2.86.7 and enable libffi
  lang/yabasic/Portfile
Labels: maintainer: none, type: bugfix, type: update

#7054 scdoc: respect MacPorts settings
  textproc/scdoc/Portfile
  textproc/scdoc/files/patch-Makefile.diff
Labels: by: member, maintainer: open, type: bugfix

#7060 dosfstools: new port
  sysutils/dosfstools/Portfile
Labels: type: submission

#7082 Gildas: update to 202005b
  science/gildas/Portfile
Labels: maintainer, type: update

#7087 topgrade: update to 4.4.0
  sysutils/topgrade/Portfile
Labels: maintainer, maintainer: open, type: update

#7083 dbeaver-community: update to 7.0.4
  databases/dbeaver-community/Portfile
  databases/dbeaver-community/files/openjdk11.patch
Labels: maintainer, maintainer: open, type: update

#7055 macos-fortress: Update to version 2020.05.09, fix hosts file updating
  net/macos-fortress/Portfile
  net/macos-fortress/files/hphosts-ad_servers_20170602.txt.bz2
  net/macos-fortress/files/hphosts-hosts_20180316.txt.bz2
  net/macos-fortress/files/hphosts-partial_20190815.asp.bz2
  net/macos-fortress/files/hphosts_pubkey_file.txt
  net/macos-fortress/files/macosfortress_setup_check.sh
  net/macos-fortress/files/squid-squid.conf.patch
  net/macos-fortress/files/squid.conf.macports
Labels: maintainer, maintainer: open, type: update

#7089 ldid: change xcode portgroup to use_xcode
  devel/ldid/Portfile
Labels: maintainer, maintainer: open, type: enhancement

#7085 dbvis: update to 11.0.1
  databases/dbvis/Portfile
Labels: maintainer, maintainer: open, type: update

#6952 doctl: update to 1.42.0
  www/doctl/Portfile
Labels: maintainer: open, type: enhancement, type: update

#7022 clew: Update to version 20170324
  devel/clew/Portfile
Labels: maintainer: open, type: enhancement, type: update

#6997 nextcloud-client: update to 2.6.4
  www/nextcloud-client/Portfile
  www/nextcloud-client/files/patch-qt5.12.diff
Labels: maintainer: none, type: update

#7081 bash: update to 5.0.17
  shells/bash/Portfile
Labels: maintainer: requires approval, type: enhancement, type: update

#7092 terraform: update to 0.12.25
  sysutils/terraform/Portfile
Labels: maintainer, maintainer: open, type: update

#7095 wireguard-tools: update to 1.0.20200513
  net/wireguard-tools/Portfile
Labels: maintainer, maintainer: open, type: update

#7088 mkvtoolnix: update to 46.0.0 & remove temporary xsltproc fix
  multimedia/mkvtoolnix/Portfile
  multimedia/mkvtoolnix/files/patch-Rakefile.diff
Labels: maintainer: open, type: update

#7093 lazygit: update to 0.20.3
  devel/lazygit/Portfile
Labels: maintainer, maintainer: open, type: update

#7096 pgbadger: update to 11.2
  databases/pgbadger/Portfile
Labels: maintainer: none, type: enhancement, type: update

#7099 akumuli: new port
  databases/Akumuli/Portfile
Labels: type: enhancement, type: submission

#7103 nomad: update to 0.11.2
  net/nomad/Portfile
Labels: maintainer, maintainer: open, type: update

#7072 cfm: Use legacysupport portgroup for <=10.9
  sysutils/cfm/Portfile
Labels: by: member, maintainer: requires approval, maintainer: timeout, type: bugfix

#7104 ViennaRNA: new port version 2.4.14
  science/ViennaRNA/Portfile
Labels: type: submission

#7106 axel: update to 2.17.8
  net/axel/Portfile
  net/axel/files/patch-axel-tiger-no-posix-c-source.diff
Labels: maintainer: none, type: update

#7108 alacritty: minor changes and cleanups
  aqua/alacritty/Portfile
Labels: by: member, maintainer: open

#7097 vcftools: new port
  science/vcftools/Portfile
Labels: type: enhancement, type: submission

#7014 godot: new port
  games/godot/Portfile
Labels: type: submission

#7112 3mux: new port
  sysutils/3mux/Portfile
Labels: type: enhancement, type: submission

#7111 spring-boot-cli: update to 2.3.0
  java/spring-boot-cli/Portfile
Labels: maintainer, maintainer: open, type: update

#7113 grafana: update to 7.0.0
  net/grafana/Portfile
Labels: maintainer, maintainer: open, type: update

#7114 Tinc 1.0.36 upgrade
  net/tinc/Portfile
Labels: maintainer: none, type: enhancement

#7059 9e fix
  archivers/9e/Portfile
  archivers/9e/files/patch-Makefile
Labels: by: member, maintainer: requires approval, maintainer: timeout, type: enhancement

#7109 redis: update to 6.0.1
  databases/redis/Portfile
  databases/redis/files/patch-redis.conf.diff
Labels: maintainer, maintainer: open, type: enhancement, type: update

#7115 topgrade: update to 4.5.0
  sysutils/topgrade/Portfile
Labels: maintainer, maintainer: open, type: update

#7118 jdupes: update to 1.15.0
  sysutils/jdupes/Portfile
Labels: maintainer, maintainer: open, type: update

#6901 trojan: submission
  net/trojan/Portfile
Labels: type: submission

#7110 Update to current s3cmd 2.1.0, using Python 3.7 and github facilities
  net/s3cmd/Portfile
Labels: maintainer: none, type: update

#7119 starship: update to 0.41.3
  sysutils/starship/Portfile
Labels: maintainer, maintainer: open, type: update

#7127 py-numpy: update to 1.18.4
  python/py-numpy/Portfile
Labels: by: member, maintainer: open, type: update

#7120 tokei: new port
  devel/tokei/Portfile
Labels: type: submission

#7128 k9s: update to 0.19.5
  sysutils/k9s/Portfile
Labels: maintainer, maintainer: open, type: update

#7116 sigil: tweak procedure to use globals
  editors/sigil/Portfile
Labels: maintainer, maintainer: open, type: enhancement

#7121 openblas: go native on older systems
  math/OpenBLAS/Portfile
Labels: by: member, maintainer: open

#7076 dblatex: +mactex variant fix installed style detection
  textproc/dblatex/Portfile
Labels: maintainer: open, type: bugfix

#7129 py-powerline: update to 2.8
  python/py-powerline/Portfile
Labels: maintainer: none, type: update

#6944 Add ghostpdl variant to ghostscript port
  print/ghostscript/Portfile
  print/ghostscript/files/patch-base_unix-dll.mak.diff
  print/ghostscript/files/patch-base_unixinst.mak.diff
Labels: maintainer: none, type: enhancement

#7080 mpv: use python 3.8 & update to 0.32.0 & catalina build fix
  multimedia/mpv/Portfile
Labels: maintainer: requires approval, maintainer: timeout, type: bugfix, type: update

#6767 SilentKnight: new port
  sysutils/SilentKnight/Portfile
Labels: type: submission

#7130 lilypond-devel: Fix +docs.
  textproc/lilypond-devel/Portfile
Labels: maintainer: open, type: bugfix

#7133 vile: update 9.8 → 9.8u
  editors/vile/Portfile
Labels: maintainer: none, type: enhancement, type: update

#7134 rke: update to 1.1.1
  devel/rke/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#7135 rancher-cli: update to 2.4.3
  devel/rancher-cli/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#7007 osl: new port
  graphics/osl/Portfile
Labels: type: submission

#7124 hr: submission
  sysutils/hr/Portfile
Labels: type: submission

#7137 siege: update to version 4.0.5
  www/siege/Portfile
Labels: maintainer: none, type: update

#7138 ultralist: new port
  office/ultralist/Portfile
Labels: type: submission

#7139 certigo: new port
  sysutils/certigo/Portfile
Labels: type: submission

#7140 evans: new port
  devel/evans/Portfile
Labels: type: submission

#7141 dua-cli: new port
  sysutils/dua-cli/Portfile
Labels: type: submission

#7147 nuspell: new port
  textproc/nuspell/Portfile
  textproc/nuspell/files/patch-finder-cxx.diff
Labels: type: submission

#7136 libetonyek: blacklist incompatible compilers
  textproc/libetonyek/Portfile
Labels: by: member, maintainer: requires approval, type: bugfix

#7163 osx2x: fix build with current openssl
  aqua/osx2x/Portfile
  aqua/osx2x/files/patch-XXRemoteX11Daemon.m.diff
Labels: maintainer: none, type: bugfix

#7160 lazygit: update to 0.20.4
  devel/lazygit/Portfile
Labels: maintainer, maintainer: open, type: update

#7162 nauty: update to version 2.7r1
  math/nauty/Portfile
Labels: maintainer: none, type: bugfix, type: enhancement, type: update

#7156 tokei: update to 11.2.0
  devel/tokei/Portfile
Labels: maintainer, maintainer: open, type: update

#7152 hugo: update to 0.71.0
  www/hugo/Portfile
Labels: maintainer, maintainer: open, type: update

#7150 k9s: update to 0.19.6
  sysutils/k9s/Portfile
Labels: maintainer, maintainer: open, type: update

#7146 dbeaver-community: update to 7.0.5
  databases/dbeaver-community/Portfile
Labels: maintainer, maintainer: open, type: update

#7151 glow: new port
  textproc/glow/Portfile
Labels: type: submission

#7073 gh: update to 0.8.0
  devel/gh/Portfile
Labels: maintainer: open, type: update
