Repository macports/macports-ports, pull requests merged in 2020-04, with the labels that each got.

#6758 softhsm: add myself as primary maintainer
  security/softhsm/Portfile
Labels: maintainer: open, type: enhancement

#6757 new port: hyperfine
  sysutils/hyperfine/Portfile
Labels: type: submission

#6761 rke: update to 1.1.0
  devel/rke/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#6751 nano: Update to 4.9.1
  editors/nano/Portfile
Labels: maintainer: open, type: update

#6766 node_exporter, miller: fix maintainer email
  net/node_exporter/Portfile
  textproc/miller/Portfile
Labels: maintainer, maintainer: open

#6759 gh: update to 0.6.4
  devel/gh/Portfile
Labels: maintainer: open, type: update

#6747 dpkg: update to 1.20.0. Disable update-alternatives.
  sysutils/dpkg/Portfile
Labels: maintainer, maintainer: open, type: update

#6764 google-cloud-sdk: update to 287.0.0
  devel/google-cloud-sdk/Portfile
Labels: maintainer, maintainer: open, type: update

#6726 boost-numpy: fix build for Xcode >= 10.0
  devel/boost/Portfile
  devel/boost/files/patch-clang_version.diff
Labels: by: member, maintainer: open, type: bugfix

#6712 cmake: Use gitlab PortGroup
  devel/cmake/Portfile
Labels: by: member, maintainer: requires approval

#6772 signing-party: Use Python 3.8
  mail/signing-party/Portfile
Labels: by: member, maintainer, maintainer: open, type: bugfix

#6774 py-xdg: add py38 subport
  python/py-xdg/Portfile
Labels: by: member, maintainer: open, type: enhancement

#6770 logtalk: update to 3.37.0
  lang/logtalk/Portfile
Labels: maintainer, type: update

#6771 spring-boot-cli: update to 2.2.6
  java/spring-boot-cli/Portfile
Labels: maintainer, maintainer: open, type: update

#6775 qbittorrent: update to 4.2.3
  net/qBittorrent/Portfile
Labels: maintainer, maintainer: open, type: update

#6776 most: update to 5.1.0
  textproc/most/Portfile
Labels: maintainer: none, type: update

#6777 blueutil: Use known_fail yes; minor text changes
  sysutils/blueutil/Portfile
Labels: by: member, maintainer: requires approval

#6708 cloog-devel: Remove obsolete port
  devel/cloog/Portfile
Labels: by: member, maintainer: requires approval, maintainer: timeout

#6765 broot: update to 0.13.5b
  sysutils/broot/Portfile
Labels: maintainer, maintainer: open, type: update

#6778 cmatrix: update to 2.0
  games/cmatrix/Portfile
  games/cmatrix/files/Makefile.in.patch
Labels: maintainer: none, type: update

#6763 py-pyobjc: update to 6.2, moved to GitHub
  python/py-pyobjc/Portfile
  python/py-pyobjc/files/patch-docs-conf.py.diff
  python/py-pyobjc/files/patch-install.py.diff
  python/py-pyobjc/files/pyobjc_setup.py.patch
Labels: by: member, maintainer: open, type: update

#6780 softhsm: implement 'port test'
  security/softhsm/Portfile
Labels: maintainer, maintainer: open, type: enhancement

#6788 k9s: update to 0.19.0
  sysutils/k9s/Portfile
Labels: maintainer, maintainer: open, type: update

#6789 micronaut: update to 1.3.4
  java/micronaut/Portfile
Labels: maintainer, maintainer: open, type: update

#6785 php-mysql-xdevapi: fix parse error on Mac OS X Lion
  php/php-mysql-xdevapi/Portfile
Labels: by: member, maintainer: open, type: bugfix

#6734 py-tensorflow1: fix Python 3.8 build.
  python/py-tensorflow1/Portfile
  python/py-tensorflow1/files/Fix-build-failures-for-python-3.8.patch
Labels: by: member, maintainer: open, type: bugfix

#6787 meson: update to version 0.54.0
  devel/meson/Portfile
  devel/meson/files/patch-meson-32bit-apple.diff
Labels: by: member, maintainer: open, type: update

#6760 vigra: add variant for Python 3.8
  graphics/vigra/Portfile
Labels: by: member, maintainer: requires approval, maintainer: timeout, type: enhancement

#6791 k9s: update to 0.19.1
  sysutils/k9s/Portfile
Labels: maintainer, maintainer: open, type: update

#6792 bandwhich: update to 0.13.0
  net/bandwhich/Portfile
Labels: maintainer, maintainer: open, type: update

#6782 prometheus: set the USER env var in environments where it isn't set.
  net/prometheus/Portfile
Labels: maintainer, maintainer: open

#6795 iso-codes: build with Python version 3.8
  devel/iso-codes/Portfile
Labels: by: member, maintainer: open, type: enhancement

#6794 pango: fix broken x11 variant.
  x11/pango/Portfile
Labels: maintainer: open, type: bugfix

#6722 dar: don't opportunistically try to build Python bindings
  archivers/dar/Portfile
Labels: by: member, maintainer: open, type: bugfix

#6798 fzf: update to 0.21.1
  sysutils/fzf/Portfile
Labels: maintainer, maintainer: open, type: update

#6803 syncthing: update to 1.4.1
  net/syncthing/Portfile
Labels: maintainer: open, type: bugfix, type: enhancement, type: update

#6796 shellcheck: update to 0.7.1
  devel/shellcheck/Portfile
Labels: maintainer: open, type: update

#5653 wxWidgets-3.2: update version to 3.1.3
  gis/saga/Portfile
  graphics/wxWidgets-3.2/Portfile
  graphics/wxWidgets-3.2/files/fix-datatransfer_h.patch
  graphics/wxWidgets-3.2/files/patch-configure.diff
  graphics/wxWidgets-common/Portfile
  math/wxMaxima/Portfile
  multimedia/mediainfo/Portfile
  science/CubicSDR/Portfile
  science/freedv-gui/Portfile
  science/limesuite/Portfile
Labels: maintainer: requires approval, type: update

#6804 qpdf: trivial update to 10.0.0
  textproc/qpdf/Portfile
Labels: by: member, maintainer: none

#6806 starship: update to 0.39.0
  sysutils/starship/Portfile
Labels: maintainer, maintainer: open, type: update

#6801 node_exporter: fix promu
  net/node_exporter/Portfile
Labels: maintainer, maintainer: open

#6800 alertmanager: set USER envvar if missing for promu
  net/alertmanager/Portfile
Labels: maintainer, maintainer: open

#6790 whitebox-tools: new port
  gis/whitebox-tools/Portfile
Labels: type: enhancement, type: submission

#6786 yarn: fix missing yarnpkg symlink
  devel/yarn/Portfile
Labels: maintainer: open, type: bugfix

#6802 welle.io: update welle.io-devel to 20200405
  multimedia/welle.io/Portfile
Labels: maintainer: none, type: update

#6809 nano: Update to 4.9.2
  editors/nano/Portfile
Labels: maintainer: open, type: update

#6781 Adds initial version of the terragrunt port
  sysutils/terragrunt/Portfile
Labels: type: enhancement, type: submission

#6810 google-cloud-sdk: update to 288.0.0
  devel/google-cloud-sdk/Portfile
Labels: maintainer, maintainer: open, type: update

#6811 nvm: update to 0.35.3
  devel/nvm/Portfile
Labels: maintainer, maintainer: open, type: update

#6812 qri: update to 0.9.7
  devel/qri/Portfile
Labels: maintainer, maintainer: open, type: update

#6814 transmission: fix build on mojave and catalina
  net/transmission/Portfile
Labels: maintainer: open, type: bugfix

#6816 syncthing: update to 1.4.2
  net/syncthing/Portfile
Labels: maintainer: open, type: bugfix, type: update

#6797 ompl: add variant for Python 3.8
  science/ompl/Portfile
Labels: by: member, maintainer: requires approval, type: enhancement

#6819 nomad: update to 0.11.0
  net/nomad/Portfile
Labels: maintainer, maintainer: open, type: update

#6820 broot: update to 0.13.6
  sysutils/broot/Portfile
Labels: maintainer, maintainer: open, type: update

#6818 vault: update to 1.4.0
  security/vault/Portfile
  security/vault/files/remove-replace-thrift-gomod.patch
Labels: maintainer, maintainer: open, type: update

#6823 nebula: update to 1.2.0
  net/nebula/Portfile
Labels: maintainer, maintainer: open, type: update

#6824 glances: update to 3.1.4.1
  sysutils/glances/Portfile
Labels: maintainer: open, type: update

#6826 rancher-cli: update to 2.4.0
  devel/rancher-cli/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#6825 dbeaver-community: update to 7.0.2
  databases/dbeaver-community/Portfile
Labels: maintainer, maintainer: open, type: update

#6784 Update of Port ehcache to version 3.8.1
  java/ehcache/Portfile
Labels: maintainer: none, type: enhancement, type: update

#6831 textproc/qpdf: trivial version bump to 10.0.1
  textproc/qpdf/Portfile
Labels: by: member, maintainer: none

#6833 highlight: update to 3.56
  textproc/highlight/Portfile
Labels: maintainer: none, type: update

#6793 cppman: use Python 3.8
  lang/cppman/Portfile
Labels: by: member, maintainer: open, type: enhancement

#6746 Minor changes to gloomhaven-helper and ismrmrd
  games/gloomhaven-helper/Portfile
  science/ismrmrd/Portfile
Labels: by: member, maintainer: requires approval, maintainer: timeout

#6830 crossbinutils: bugfix - disable libbfd
  _resources/port1.0/group/crossbinutils-1.0.tcl
  cross/arm-elf-binutils/Portfile
  cross/arm-none-eabi-binutils/Portfile
  cross/arm-none-linux-gnueabi-binutils/Portfile
  cross/avr-binutils/Portfile
  cross/i386-elf-binutils/Portfile
  cross/i686-w64-mingw32-binutils/Portfile
  cross/m68k-elf-binutils/Portfile
  cross/mips-elf-binutils/Portfile
  cross/ppc-linux-binutils/Portfile
  cross/spu-binutils/Portfile
  cross/x86_64-elf-binutils/Portfile
  cross/x86_64-w64-mingw32-binutils/Portfile
  devel/binutils/Portfile
Labels: type: bugfix

#6837 ismrmrd: Upgrade to 1.4.2.1
  science/ismrmrd/Portfile
Labels: by: member, maintainer, maintainer: open

#6805 FAudio: Update to 20.04
  audio/FAudio/Portfile
Labels: maintainer: none, type: enhancement, type: update

#6834 auto-multiple-choice-devel: update to version 1.4.0-202004101300
  x11/auto-multiple-choice/Portfile
  x11/auto-multiple-choice/files/patch-cupslp-pm-684.diff
Labels: maintainer, maintainer: open, type: enhancement, type: update

#6848 dbvis: update to 11.0
  databases/dbvis/Portfile
Labels: maintainer, maintainer: open, type: update

#6827 Proguard
  java/proguard/Portfile
Labels: maintainer, maintainer: open

#6829 py-wxpython-4.0: fix build on macOS 10.15
  python/py-wxpython-4.0/Portfile
  python/py-wxpython-4.0/files/fix_webview_macos1015.patch
  python/py-wxpython-4.0/files/patch-ext_wxWidgets_configure_in.diff
  python/py-wxpython-4.0/files/patch-ext_wxWidgets_src_html_htmlctrl_webkit_webkit_mm.diff
Labels: by: member, maintainer: none, type: bugfix

#6850 BlackHole: new port
  audio/BlackHole/Portfile
Labels: type: submission

#6845 mc: update to 4.8.24
  sysutils/mc/Portfile
Labels: maintainer: none, type: update

#6847 lunzip: update to 1.11
  archivers/lunzip/Portfile
Labels: maintainer: none, type: update

#6815 r: add quartz variant
  math/R/Portfile
Labels: maintainer: requires approval, maintainer: timeout, type: enhancement

#6813 chezmoi: new port
  sysutils/chezmoi/Portfile
Labels: type: submission

#6846 GPXSee: update to 7.28
  gis/GPXSee/Portfile
Labels: maintainer, maintainer: open, type: enhancement, type: update

#6843 vgrep: new port
  textproc/vgrep/Portfile
Labels: type: submission

#6853 R: assign myself as comaintainer
  math/R/Portfile
Labels: maintainer: requires approval

#6841 OpenIPMI: Update to 2.0.28
  sysutils/OpenIPMI/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#6852 ruby-build: update to 20200401
  ruby/ruby-build/Portfile
Labels: maintainer: open, type: update

#6857 BlackHole: Adding maintainer
  audio/BlackHole/Portfile
Labels: maintainer: none

#6855 flyway: update to 6.3.3
  java/flyway/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#6854 docker-compose: update to 1.25.5
  python/docker-compose/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#6856 starship: update to 0.40.1
  sysutils/starship/Portfile
Labels: maintainer, maintainer: open, type: update

#6860 tig: update to 2.5.1
  devel/tig/Portfile
Labels: maintainer: open, type: update

#6861 hugo: update to 0.69.0
  www/hugo/Portfile
Labels: maintainer, maintainer: open, type: update

#6863 groovy: update to 3.0.3
  lang/groovy/Portfile
Labels: maintainer, maintainer: open, type: update

#6838 XlsxWriter,pdfminer,qimage2ndarry: Python updates
  python/py-XlsxWriter/Portfile
  python/py-pdfminer/Portfile
  python/py-qimage2ndarray/Portfile
Labels: by: member, maintainer, maintainer: open

#6839 mpich/mpi-doc updates
  science/mpi-doc/Portfile
  science/mpich/Portfile
Labels: by: member, maintainer, maintainer: open

#6862 nnn: update version 3.0->3.1
  sysutils/nnn/Portfile
Labels: maintainer: open, type: enhancement, type: update

#6783 macos-fortress: Update configuration files and launchd bugfix
  net/macos-fortress/Portfile
  net/macos-fortress/files/privoxy-config.macports
  net/macos-fortress/files/privoxy-config.patch
  net/macos-fortress/files/privoxy-match-all.action.macports
  net/macos-fortress/files/privoxy-match-all.action.patch
  net/macos-fortress/files/squid-squid.conf.patch
  net/macos-fortress/files/squid.conf.macports
Labels: maintainer, maintainer: open, type: update

#6840 minio[-mc]: update to 2020-04-10/04
  www/minio-mc/Portfile
  www/minio/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#6868 gimp-lqr-plugin: fixed invalid parameter name - plugin crashed gimp 2.10.18
  graphics/gimp-lqr-plugin/Portfile
  graphics/gimp-lqr-plugin/files/patch-invalid-parameter-name-fix.diff
Labels: maintainer: open, type: bugfix

#6828 terragrunt: fix terraform binary used
  sysutils/terragrunt/Portfile
  sysutils/terragrunt/files/patch-options.go.diff
Labels: by: member, maintainer: open, type: enhancement

#6870 swig-python3: make it obsolete
  devel/swig/Portfile
Labels: by: member, maintainer: open, type: enhancement

#6867 swi-prolog-devel: update to 8.1.28
  lang/swi-prolog-devel/Portfile
Labels: maintainer, type: update

#6842 logcat-colorize: new port
  devel/logcat-colorize/Portfile
Labels: type: submission

#6866 apache-solr8: Update to 8.5.0
  java/apache-solr8/Portfile
Labels: maintainer, maintainer: open, type: update

#6873 google-cloud-sdk: update to 289.0.0
  devel/google-cloud-sdk/Portfile
Labels: maintainer, maintainer: open, type: update

#6871 tmux: update tmux-devel to latest commit
  sysutils/tmux/Portfile
Labels: maintainer, maintainer: open, type: update

#6874 kotlin: update to 1.3.72
  lang/kotlin/Portfile
Labels: maintainer, maintainer: open, type: update

#6858 py-twine: update dependencies
  python/py-twine/Portfile
Labels: maintainer: open, type: bugfix

#6878 cctools: Remove rsrc forks from manpages.
  devel/cctools/Portfile
Labels: by: member, maintainer: open

#6821 vtk: Bump to 8.2.0
  graphics/vtk/Portfile
  graphics/vtk/files/patch-IOMovie-module.cmake.diff
  graphics/vtk/files/patch-pugixml.diff
  graphics/vtk/files/patch-python37.diff
Labels: maintainer: open

#6879 logcat-colorize: update to 0.8.2
  devel/logcat-colorize/Portfile
Labels: maintainer, maintainer: open, type: bugfix, type: update

#6851 xorg-server: update to 1.20.8
  x11/xorg-server/Portfile
  x11/xorg-server/files/0001-xquartz-Add-stub-ddxInputThread.patch
Labels: maintainer: open, type: update

#6884 Lazarus: Update to new upstream version (2.0.8)
  devel/lazarus/Portfile
Labels: maintainer, maintainer: open, type: update

#6877 openjdk8: update subport openjdk11 to 11.0.7
  java/openjdk8/Portfile
Labels: maintainer, maintainer: open, type: update

#6882 k9s: update to 0.19.2
  sysutils/k9s/Portfile
Labels: maintainer, maintainer: open, type: update

#6883 ripgrep: update to 12.0.1
  textproc/ripgrep/Portfile
Labels: maintainer: open, type: bugfix, type: enhancement, type: security fix, type: update

#5515 liblas: reference liblas by its actual ID
  gis/liblas/Portfile
Labels: maintainer: none, type: bugfix

#6886 rtags: use clang-9.0
  devel/rtags/Portfile
Labels: maintainer: none

#5460 php: php-zstd submission - add support for the zstd compression lib
  php/php-zstd/Portfile
Labels: type: enhancement, type: submission

#6888 openjdk8: update to 8u252
  java/openjdk8/Portfile
Labels: maintainer, maintainer: open, type: update

#6892 py-sip: update to 4.19.22
  python/py-sip/Portfile
Labels: maintainer: open, type: bugfix, type: update

#6890 openjdk8: OpenJ9 updates for openjdk11 and openjdk14 subports
  java/openjdk8/Portfile
Labels: maintainer, maintainer: open

#6895 py-pyside2: update to 5.14.2
  python/py-pyside2/Portfile
Labels: maintainer: open, type: update

#6885 radare2: update to 4.4.0
  devel/radare2/Portfile
Labels: maintainer, maintainer: open, type: update

#6891 drupal8: update to 8.7.13
  www/drupal8/Portfile
Labels: maintainer: none, type: bugfix, type: update

#6864 frescobaldi{,-devel}: update to 3.1.2
  editors/frescobaldi/Portfile
Labels: maintainer, maintainer: open, type: update

#6904 py-plumbum: update to version 1.6.9, license
  python/py-plumbum/Portfile
Labels: by: member, maintainer: open, type: enhancement, type: update

#6744 lilypond: Synchronize Portfile with 'lilypond-devel' Portfile.
  textproc/lilypond/Portfile
Labels: maintainer: open, type: enhancement

#6903 chezmoi: update to 1.8.0
  sysutils/chezmoi/Portfile
Labels: maintainer, maintainer: open, type: update

#6889 py-sentence-transformers: Update to v 0.2.6.1
  python/py-sentence-transformers/Portfile
Labels: maintainer: none, type: update

#6906 lazygit: update to 0.20
  devel/lazygit/Portfile
Labels: maintainer, maintainer: open, type: update

#6905 prometheus: update to 2.17.2
  net/prometheus/Portfile
Labels: maintainer, maintainer: open, type: update

#6913 Bear: update to 2.4.3, add notes
  devel/Bear/Portfile
Labels: by: member, maintainer: open, type: update

#6912 qri: update to 0.9.8
  devel/qri/Portfile
Labels: maintainer, maintainer: open, type: update

#6907 openjdk8: update openjdk14 subport to 14.0.1
  java/openjdk8/Portfile
Labels: maintainer, maintainer: open, type: update

#6900 directory-studio: update to 2.0.0.v20200411-M15
  databases/directory-studio/Portfile
Labels: maintainer, maintainer: open, type: update

#6849 ghc: Update to version 8.10.1
  lang/ghc/Portfile
Labels: maintainer, maintainer: open, type: update

#6919 libsoundio: update version to 2.0.0
  audio/libsoundio/Portfile
Labels: by: member, maintainer: open, type: update

#6799 icu: Fix possibly-conflicting macro invocation
  devel/icu/Portfile
  devel/icu/files/patch-declspec-conflict.patch
Labels: maintainer: none, type: bugfix

#6749 2048.cpp: new port
  games/2048.cpp/Portfile
  games/2048.cpp/files/data_path.diff
Labels: type: enhancement, type: submission

#6921 ncdu: update to 1.14.2
  sysutils/ncdu/Portfile
Labels: maintainer: open, type: bugfix, type: enhancement, type: update

#6194 bitcoin: Update to 0.19.1
  finance/bitcoin/Portfile
Labels: maintainer: open, type: update

#6928 openconnect: update to version 8.08
  net/openconnect/Portfile
Labels: maintainer: none, type: bugfix, type: enhancement, type: update

#6936 imapfilter: update to 2.6.16
  mail/imapfilter/Portfile
Labels: maintainer: none, type: update

#6927 lazygit: update to 0.20.2
  devel/lazygit/Portfile
Labels: maintainer, maintainer: open, type: update

#6925 nomad: update to 0.11.1
  net/nomad/Portfile
Labels: maintainer, maintainer: open, type: update

#6923 google-cloud-sdk: update to 290.0.0
  devel/google-cloud-sdk/Portfile
Labels: maintainer, maintainer: open, type: update

#6939 fd: Update to 8.0.0
  sysutils/fd/Portfile
  sysutils/fd/files/patch-disable-jemallocator.diff
Labels: maintainer, maintainer: open, type: update

#6940 tmux: update to 3.1
  sysutils/tmux/Portfile
Labels: maintainer, maintainer: open, type: update

#6931 qbittorrent: update to 4.2.4
  net/qBittorrent/Portfile
Labels: maintainer, maintainer: open, type: update

#6916 julia: update to version 1.4.1
  lang/julia/Portfile
Labels: maintainer: open, type: update

#6893 py-pyqt5: update to 5.14.2
  python/py-pyqt5/Portfile
Labels: maintainer: none, type: bugfix, type: update

#6941 flyway: update to 6.4.0
  java/flyway/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#6929 gh: update to 0.7.0
  devel/gh/Portfile
Labels: maintainer: open, type: update
