Repository macports/macports-ports, pull requests merged in 2021-01, with the labels that each got.

#9582 hugo: update to 0.80.0
  www/hugo/Portfile
Labels: maintainer, maintainer: open, type: update

#9583 bandwhich: update to 0.20.0
  net/bandwhich/Portfile
  net/bandwhich/files/patch-Cargo-toml-remove-git-package.diff
Labels: by: member, maintainer, maintainer: open, type: update

#9489 mc: add sftp variant
  sysutils/mc/Portfile
Labels: maintainer: none, type: enhancement

#9584 nccmp: update to 1.8.9.0
  science/nccmp/Portfile
Labels: maintainer, maintainer: open, type: update

#9588 commitizen: update to 2.13.0
  devel/commitizen/Portfile
Labels: maintainer, maintainer: open, type: enhancement, type: update

#9589 py-rich: update to 9.6.1
  python/py-rich/Portfile
Labels: maintainer, maintainer: open, type: enhancement, type: update

#9572 bind9: support python39
  net/bind9/Portfile
Labels: by: member, maintainer: requires approval, type: enhancement

#9585 ruby: fix implicit function declarations
  lang/ruby/Portfile
  lang/ruby/files/implicit.patch
Labels: by: member, maintainer: requires approval, type: bugfix

#9596 python34: fix building on big sur
  lang/python34/Portfile
  lang/python34/files/patch-Python-random.c.diff
  lang/python34/files/patch-configure.diff
  lang/python34/files/patch-pyconfig.h.in.diff
Labels: by: member, maintainer: open, type: bugfix

#9601 libarchive: update to 3.5.1
  archivers/libarchive/Portfile
Labels: by: member, maintainer: open, type: enhancement, type: update

#9506 net-snmp: update to 5.9
  net/net-snmp/Portfile
  net/net-snmp/files/fix-compiler-warnings.patch
  net/net-snmp/files/fix-order-of-L-flags.patch
  net/net-snmp/files/patch-Makefile.in.diff
  net/net-snmp/files/patch-agent-mibgroup-mibII-icmp.h.diff
  net/net-snmp/files/yosemite-libtool.patch
Labels: by: member, maintainer: open, type: bugfix, type: update

#8934 sane-backends: update to 1.0.31 and fix build error
  graphics/sane-backends/Portfile
  graphics/sane-backends/files/patch-backend-ricoh2_buffer.c.diff
  graphics/sane-backends/files/patch-configure.diff
  graphics/sane-backends/files/patch-frontend-scanimage.c.diff
Labels: maintainer: none, type: bugfix, type: enhancement, type: update

#9602 pallet: fix build on newer systems
  sysutils/Pallet/Portfile
  sysutils/Pallet/files/patch-pallet-open-save-panel.diff
  sysutils/Pallet/files/patch-pallet-system-target.diff
  sysutils/Pallet/files/patch-preferences-lib-location.diff
Labels: by: member, maintainer: none, type: bugfix

#9600 py-argcomplete: update to 1.12.2
  python/py-argcomplete/Portfile
Labels: maintainer: open, type: enhancement, type: update

#9613 fzf: update to 0.25.0
  sysutils/fzf/Portfile
Labels: maintainer, maintainer: open, type: update

#9478 qemu: update to 5.2.0
  emulators/qemu/Portfile
  emulators/qemu/files/patch-configure.diff
Labels: maintainer: open, type: enhancement, type: update

#9622 OpenIPMI: Update to 2.0.30
  sysutils/OpenIPMI/Portfile
  sysutils/OpenIPMI/files/include_OpenIPMI_selector.h.patch
Labels: by: member, maintainer, maintainer: open, type: update

#9624 py-h5py: remove py27/35 versions
  python/py-h5py/Portfile
Labels: by: member, maintainer, maintainer: open

#9599 bazel: update to 3.7.2
  devel/bazel/Portfile
Labels: by: member, maintainer: open, type: update

#9393 opensmtpd: submission
  mail/opensmtpd/Portfile
Labels: type: submission

#9593 openjdk15*: stealth updates
  java/openjdk/Portfile
Labels: maintainer, maintainer: open

#9619 BlackHole: Add compiler blacklist
  audio/BlackHole/Portfile
Labels: maintainer, maintainer: open, type: enhancement

#9615 topgrade: update to 6.2.0
  sysutils/topgrade/Portfile
Labels: maintainer, maintainer: open, type: update

#9625 emacs{,-app}-devel: update to 20210105
  editors/emacs/Portfile
Labels: by: member, maintainer: open, type: update

#9620 phpmyadmin: Add php80 variant and make default
  www/phpmyadmin/Portfile
Labels: maintainer: open

#9611 py-pyobjc: update to 7.1
  python/py-pyobjc/Portfile
  python/py-pyobjc/files/patch-install.py.diff
Labels: by: member, maintainer: open, type: enhancement, type: update

#9631 fpc: Update to fix build on 11.x
  lang/fpc/Portfile
Labels: maintainer: none, type: bugfix, type: enhancement, type: update

#9630 Gildas: update to 202101a
  science/gildas/Portfile
Labels: maintainer, type: update

#9635 textproc/qpdf: trivial update to 10.1.0
  textproc/qpdf/Portfile
Labels: by: member, maintainer: none

#9652 v2ray: remove execute bit from dat files
  net/v2ray/Portfile
Labels: by: member, maintainer: open, type: bugfix

#9649 syncthing: update to 1.12.1
  net/syncthing/Portfile
Labels: maintainer: open, type: bugfix, type: enhancement, type: update

#9623 task: update to 2.5.3
  office/task/Portfile
Labels: maintainer: none, type: update

#9643 py-click-spinner: new port
  python/py-click-spinner/Portfile
Labels: type: enhancement, type: submission

#9430 erlang: fix for faulty symbolic links; issue: 61665
  lang/erlang/Portfile
Labels: maintainer: requires approval, maintainer: timeout, type: bugfix

#9591 openmpi: add subport clang11
  science/openmpi/Portfile
  science/openmpi/files/openmpi-clang11
  science/openmpi/files/openmpi-clang11-fortran
Labels: maintainer: none, type: enhancement

#9637 dbeaver-community: update to 7.3.2
  databases/dbeaver-community/Portfile
Labels: maintainer, maintainer: open, type: update

#9628 json-modern-cpp: remove obsolete port
  devel/json-modern-cpp/Portfile
Labels: maintainer: none

#9606 py-trio: update to 0.17.0
  python/py-trio/Portfile
Labels: maintainer, maintainer: open, type: update

#9655 hamlib: use legacysupport
  science/hamlib/Portfile
Labels: by: member, maintainer: open

#9608 qwt-qt5: update to 6.1.6
  graphics/qwt-qt5/Portfile
Labels: by: member, maintainer: open, type: enhancement, type: update

#9660 gnss-sdr: update to 0.0.14
  science/gnss-sdr/Portfile
  science/volk-gnss-sdr/Portfile
Labels: maintainer, maintainer: open, type: update

#9659 py-rich: update to 9.6.2
  python/py-rich/Portfile
Labels: maintainer, maintainer: open, type: enhancement, type: update

#9657 swi-prolog-devel: Updated to version 8.3.17
  lang/swi-prolog-devel/Portfile
Labels: maintainer, maintainer: open, type: update

#9665 eigen3: Update to 3.3.9
  math/eigen3/Portfile
  math/eigen3/files/openmp_fix.diff
Labels: by: member, maintainer, maintainer: open, type: update

#9661 OpenBLAS: on ARM64 build as +native for now
  math/OpenBLAS/Portfile
Labels: by: member, maintainer, maintainer: open

#9663 asmotor: Update to 1.0.4
  devel/asmotor/Portfile
Labels: by: member, maintainer: requires approval, type: update

#9650 py-click-didyoumean: new port
  python/py-click-didyoumean/Portfile
Labels: by: member, type: submission

#9668 py-Pillow: update to 8.1.0
  python/py-Pillow/Portfile
Labels: maintainer: open, type: enhancement, type: update

#9670 py-janus: update to 0.6.1
  python/py-janus/Portfile
Labels: maintainer: none, type: enhancement, type: update

#9671 py-rich: update to 9.7.0
  python/py-rich/Portfile
Labels: maintainer, maintainer: open, type: enhancement, type: update

#9651 py-selenium: add Python 3.9 subport
  python/py-selenium/Portfile
Labels: maintainer: open, type: enhancement

#9638 py-pyaudio: add Python 3.9 subport
  python/py-pyaudio/Portfile
Labels: maintainer: open, type: enhancement

#9646 micronaut: update to 2.2.3
  java/micronaut/Portfile
Labels: maintainer, maintainer: open, type: update

#9658 luaradio: update to 0.9.1
  science/luaradio/Portfile
Labels: maintainer, maintainer: open, type: enhancement, type: update

#9540 py-qpageview: add Python 3.9
  python/py-qpageview/Portfile
Labels: maintainer, maintainer: open, type: enhancement

#9674 gnuplot: update to 5.4.1, retire cxx11 PG
  math/gnuplot/Portfile
Labels: by: member, maintainer: open, type: update

#9672 dnsviz: update to version 0.9.0
  net/dnsviz/Portfile
Labels: maintainer, maintainer: open, type: update

#9679 vobcopy: port abandoned
  multimedia/vobcopy/Portfile
Labels: maintainer: requires approval

#9677 supertuxkart: patch to fix SDL-related build failure in file src/input/gamepad_config.cpp
  games/supertuxkart/Portfile
  games/supertuxkart/files/patch-1.2-sdl-gamepad_config.diff
Labels: maintainer: none, type: bugfix

#9676 zile: update to 2.4.15
  editors/zile/Portfile
Labels: maintainer: none, type: update

#9667 materialx: update to version 1.37.4
  graphics/materialx/Portfile
Labels: maintainer, maintainer: open, type: update

#9656 plumed: fix for arm build
  science/plumed/Portfile
Labels: maintainer, maintainer: open, type: bugfix

#9603 restic: update to 0.11.0
  sysutils/restic/Portfile
Labels: by: member, maintainer: none, type: update

#9552 godot: fix building for apple silicon
  games/godot/Portfile
Labels: maintainer: open, type: enhancement

#9531 openmpi: update to 4.1.0
  science/openmpi/Portfile
Labels: maintainer: none, type: update

#8154 qt59-qtconnectivity: fix for recent Xcode on 10.15
  aqua/qt59/Portfile
  aqua/qt59/files/patch-qtconnectivity_qtbug_76847.diff
Labels: maintainer: open, type: bugfix

#9687 py-rich: update to 9.8.0
  python/py-rich/Portfile
Labels: maintainer, maintainer: open, type: enhancement, type: update

#9688 mos: update to 2.19.0
  devel/mos/Portfile
Labels: maintainer, maintainer: open, type: enhancement, type: update

#9690 mos-devel: update to 202101120021
  devel/mos-devel/Portfile
Labels: maintainer, maintainer: open, type: enhancement, type: update

#9354 blender: add support for Universal Scene Description (USD)
  graphics/blender/Portfile
Labels: maintainer, type: bugfix, type: enhancement

#9366 embree: add static variant
  graphics/embree/Portfile
  graphics/embree/files/patch-static-lib.diff
Labels: maintainer, maintainer: open, type: enhancement

#9685 openal-soft: patch to fix template-related build errors
  audio/openal-soft/Portfile
  audio/openal-soft/files/openal-soft-alnumeric-templates.patch
Labels: maintainer: open, type: bugfix

#9662 fpc: Update for arm (WIP)
  lang/fpc/Portfile
Labels: maintainer, maintainer: open, type: enhancement, type: update

#9689 bupstash: new port
  sysutils/bupstash/Portfile
Labels: by: member, type: submission

#9636 argocd: new port
  devel/argocd/Portfile
Labels: by: member, type: submission

#9639 dmux: new port
  sysutils/dmux/Portfile
Labels: by: member, type: submission

#9432 hyper: new port
  aqua/hyper/Portfile
  aqua/hyper/files/patch-package-json.diff
Labels: by: member, type: submission

#9496 edex-ui: new port
  sysutils/edex-ui/Portfile
Labels: by: member, type: submission

#9575 zenith: new port
  sysutils/zenith/Portfile
Labels: by: member, type: submission

#9525 kakoune: new port
  editors/kakoune/Portfile
Labels: by: member, type: submission

#9675 watson: new port
  office/watson/Portfile
Labels: by: member, type: submission

#8922 lens: new port
  sysutils/lens/Portfile
Labels: by: member, type: submission

#9560 bed: new port
  sysutils/bed/Portfile
Labels: by: member, type: submission

#9486 proxify: new port
  net/proxify/Portfile
Labels: by: member, type: submission

#9581 pastel: new port
  graphics/pastel/Portfile
Labels: by: member, type: submission

#9610 haproxy: update to 2.2.6
  net/haproxy/Portfile
Labels: by: member, maintainer: open, type: update

#9612 timewarrior: new port
  office/timewarrior/Portfile
Labels: by: member, type: submission

#9556 raylib: new port
  multimedia/raylib/Portfile
Labels: by: member, type: submission

#9653 go-mmv: new port
  sysutils/go-mmv/Portfile
Labels: by: member, type: submission

#9396 hexyl: new port
  sysutils/hexyl/Portfile
Labels: by: member, type: submission

#9645 openjdk11-openj9*: update to 11.0.9+11.2
  java/openjdk/Portfile
Labels: maintainer, maintainer: open, type: update

#9618 cdparanoia: Fix compilation problems on macOS 11
  audio/cdparanoia/Portfile
  audio/cdparanoia/files/fixing-fprintf.patch
  audio/cdparanoia/files/fixing-include.patch
  audio/cdparanoia/files/fixing-labs.patch
Labels: maintainer: open, type: bugfix

#9604 jpeginfo: use autoconf
  multimedia/jpeginfo/Portfile
Labels: maintainer, maintainer: open, type: bugfix

#9616 keybase: Update to 5.5.2
  security/keybase/Portfile
Labels: maintainer: none, type: update

#9595 qiv: update to version 2.3.2
  graphics/qiv/Portfile
  graphics/qiv/files/patch-Makefile.diff
Labels: maintainer: requires approval, maintainer: timeout, type: bugfix, type: enhancement, type: update

#9614 kaf: new port
  sysutils/kaf/Portfile
Labels: by: member, type: submission

#9586 amp: new port
  editors/amp/Portfile
Labels: by: member, type: submission

#9369 tealdeer: new port
  sysutils/tealdeer/Portfile
Labels: by: member, type: submission

#9482 pkger: new port
  devel/pkger/Portfile
Labels: by: member, type: submission

#9474 dstask: new port
  office/dstask/Portfile
Labels: by: member, type: submission

#7996 uboot-tools: Specify C standard for compiler and enable extensions
  devel/uboot-tools/Portfile
Labels: maintainer, maintainer: open, type: bugfix

#9698 npm6: fix broken replace for older versions of macOS
  devel/npm6/Portfile
Labels: by: member, maintainer: open

#9692 mackup: update to 0.8.32
  sysutils/mackup/Portfile
Labels: maintainer: open, type: enhancement, type: update

#9684 openmpi: force use of macports libevent, to eliminate implicit use when already installed
  science/openmpi/Portfile
Labels: maintainer, maintainer: open, type: bugfix

#9633 nodejs12: add arm64 support
  devel/nodejs12/Portfile
Labels: maintainer: open, type: enhancement

#9621 proxy-audio-device: new port
  audio/proxy-audio-device/Portfile
Labels: type: submission

#9564 pinentry-mac: fix building for apple silicon
  aqua/pinentry-mac/Portfile
  aqua/pinentry-mac/files/patch-apple-silicon.diff
Labels: maintainer: requires approval, maintainer: timeout, type: enhancement

#9499 vcs_blackbox: update to 2.0.0
  security/vcs_blackbox/Portfile
Labels: maintainer: open, type: update

#9271 dav1d: update to version 0.8.0
  multimedia/dav1d/Portfile
Labels: maintainer: open, type: enhancement, type: update

#9597 screen: fix garbled statusline in Big Sur
  sysutils/screen/files/patch-configure_no_implicit_defs.diff
Labels: maintainer: open

#8864 chronos-go: new port
  devel/chronos-go/Portfile
Labels: by: member, type: submission

#8957 Floppy&Flow: New ports
  devel/floppy/Portfile
  devel/flow/Portfile
Labels: type: submission

#5068 gauche-dbd-pg: delete port
  databases/gauche-dbd-pg/Portfile
Labels: maintainer: none

#9704 mame: fix for macOS 10.13 builds
  emulators/mame/Portfile
Labels: maintainer, maintainer: open, type: bugfix

#9707 p5-compress-raw-zlib: update to version 2.100
  perl/p5-compress-raw-zlib/Portfile
Labels: maintainer: none, type: update

#9706 p5-compress-raw-bzip2: update to version 2.100
  perl/p5-compress-raw-bzip2/Portfile
Labels: maintainer: none, type: update

#9705 p5-compress-raw-lzma: update to version 2.100
  perl/p5-compress-raw-lzma/Portfile
Labels: maintainer, maintainer: open, type: update

#9708 p5-io-compress: update to version 2.100
  perl/p5-io-compress/Portfile
Labels: maintainer: none, type: update

#8963 jq: better patch, that should hopefully work on 10.7
  sysutils/jq/Portfile
  sysutils/jq/files/patch-autoconf-builtins.diff
Labels: by: member, maintainer: open

#9711 p5-io-compress-lzf: update to version 2.100
  perl/p5-io-compress-lzf/Portfile
Labels: maintainer: open, type: update

#9710 p5-io-compress-lzma: update to version 2.100
  perl/p5-io-compress-lzma/Portfile
Labels: maintainer, maintainer: open, type: update

#9709 p5-io-compress-zstd: update to version 2.100
  perl/p5-io-compress-zstd/Portfile
Labels: maintainer: open, type: update

#8239 stgit: Update to 0.23
  devel/stgit/Portfile
  devel/stgit/files/gerrit-integration.diff
  devel/stgit/files/template.diff
Labels: maintainer: none, type: enhancement, type: update

#7733 dlib: Add Python bindings
  math/dlib/Portfile
Labels: maintainer: none, type: enhancement

#9570 multiple: add python39 support
  gnome/gexiv2/Portfile
  gnome/gtk-doc/Portfile
  graphics/gegl/Portfile
  graphics/libepoxy/Portfile
  python/py-anytree/Portfile
Labels: by: member, maintainer: open, type: enhancement

#9713 py-rich: update to 9.8.1
  python/py-rich/Portfile
Labels: maintainer, maintainer: open, type: enhancement, type: update

#9504 cleanup of obscure enthought ports
  python/py-blockcanvas/Portfile
  python/py-chaco/Portfile
  python/py-codetools/Portfile
  python/py-enable/Portfile
  python/py-enable/files/no-64-bit-quartz.diff
  python/py-enable/files/patch-swig_fix.diff
  python/py-etsdevtools/Portfile
  python/py-scimath/Portfile
Labels: maintainer, maintainer: open, type: bugfix

#9719 mame: enable arm64 build
  emulators/mame/Portfile
Labels: maintainer, maintainer: open, type: enhancement

#9720 served: new port
  devel/served/Portfile
Labels: type: enhancement, type: submission

#9648 boxes: update to 1.3
  textproc/boxes/Portfile
  textproc/boxes/files/boxes.c.diff
  textproc/boxes/files/regexp.h.diff
  textproc/boxes/files/testrunner.sh.diff
  textproc/boxes/files/tools.c.diff
Labels: maintainer: open, type: enhancement, type: update

#9669 Update to digikam port (remove myself as maintainer)
  kde/digikam/Portfile
Labels: maintainer, maintainer: open, type: update

#9563 pdfpc: update to version 4.4.1
  graphics/pdfpc/Portfile
Labels: maintainer, maintainer: open, type: enhancement, type: update

#9539 shellcheck: install binary for BigSur
  devel/shellcheck/Portfile
Labels: maintainer: open

#9696 xinetd: update to 2.3.15.4
  net/xinetd/Portfile
Labels: maintainer: none, type: bugfix, type: enhancement, type: security fix, type: update

#9723 icmake: cleanup MacPorts < 2.6.0 handling
  devel/icmake/Portfile
Labels: maintainer: requires approval

#9725 baresip, libre, librem, restund: cleanup handling for MacPorts < 2.6.0
  net/baresip/Portfile
  net/libre/Portfile
  net/librem/Portfile
  net/restund/Portfile
Labels: maintainer: requires approval

#9724 py-reportlab: add Python 3.9 support
  python/py-reportlab/Portfile
Labels: by: member, maintainer: open, type: enhancement

#9487 submission libcbor
  devel/libcbor/Portfile
Labels: type: submission

#9726 gpsd: Update to 3.22
  net/gpsd/Portfile
Labels: maintainer, maintainer: open, type: update

#8253 zabbix: Update 4/44; add 5.
  net/zabbix4/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#9727 py-rich: update to 9.8.2
  python/py-rich/Portfile
Labels: maintainer, maintainer: open, type: enhancement, type: update

#9733 py-slackclient: update to 2.9.3, added python39 support
  python/py-slackclient/Portfile
Labels: maintainer, maintainer: open, type: update

#9732 openmpi: rev bump for recent libevent changes
  science/openmpi/Portfile
Labels: maintainer, maintainer: open, type: bugfix

#9116 rb-ronn-ng, rb-kramdown, rb-nokogiri: Update
  ruby/rb-kramdown/Portfile
  ruby/rb-nokogiri/Portfile
  ruby/rb-ronn-ng/Portfile
  ruby/rb-ronn-ng/files/patch-relax-dependencies.diff
Labels: maintainer: none, type: bugfix

#9715 mesa: fix build on macOS 10.11 and earlier
  x11/mesa/Portfile
Labels: maintainer: open

#9734 whitebox-tools: update to version 1.4.0
  gis/whitebox-tools/Portfile
Labels: maintainer, maintainer: open, type: update

#9738 blender: update to version 2.83.2
  graphics/blender/Portfile
Labels: maintainer, type: update

#9026 openrct2: update to 0.3.2
  games/openrct2/Portfile
  games/openrct2/files/patch-jsonfwd-hpp.diff
Labels: maintainer: none, type: update

#9730 terragrunt: added multiple versions (contd.)
  sysutils/terragrunt/Portfile
  sysutils/terragrunt/files/base
  sysutils/terragrunt/files/none
  sysutils/terragrunt/files/terragruntX.YY.template
Labels: maintainer, maintainer: open, type: enhancement

#9480 submission libfido2
  security/libfido2/Portfile
Labels: type: submission
