Repository macports/macports-ports, pull requests merged in 2021-02, with the labels that each got.

#9858 py-sox: Update to version 1.4.1, add sox dependency, add Python 39
  python/py-sox/Portfile
Labels: maintainer: none, type: bugfix, type: enhancement, type: update

#9856 jenkins-cli: update to 0.0.33, add shell completion
  devel/jenkins-cli/Portfile
Labels: maintainer, maintainer: open, type: enhancement, type: update

#9775 rust-analyzer: new Portfile submission
  devel/rust-analyzer/Portfile
Labels: type: submission

#9881 samurai: update to 1.2
  devel/samurai/Portfile
Labels: by: member, maintainer: none, type: update

#9879 meson: update to 0.56.2
  devel/meson/Portfile
Labels: by: member, maintainer: open, type: update

#9880 pyqtgraph: add support for python39
  python/py-pyqtgraph/Portfile
Labels: maintainer: open, type: enhancement

#9886 ledit: update to 2.04
  editors/ledit/Portfile
Labels: maintainer: none, type: update

#9894 py-ipython: update to version 7.20.0
  python/py-ipython/Portfile
Labels: maintainer: open, type: bugfix, type: enhancement

#9899 lang/ecl: update to ecl-21.2.1
  lang/ecl/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#9896 oauth2-proxy: update to 7.0.0
  security/oauth2-proxy/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#9895 micronaut: update to 2.3.1
  java/micronaut/Portfile
Labels: maintainer, maintainer: open, type: update

#9889 dav1d: update to 0.8.1
  multimedia/dav1d/Portfile
Labels: by: member, maintainer: open, type: update

#9903 mpich: Update to 3.4.1, move (back) to ch3
  science/mpich/Portfile
  science/mpich/files/mpich-gccdevel-fortran
Labels: by: member, maintainer, maintainer: open, type: update

#9900 commitizen: update to 2.14.1
  devel/commitizen/Portfile
Labels: maintainer, maintainer: open, type: enhancement, type: update

#9890 tomcat-native: update to version 1.2.26
  java/tomcat-native/Portfile
Labels: maintainer, maintainer: open, type: bugfix, type: enhancement, type: update

#9884 Gildas: update to 202102a
  science/gildas/Portfile
Labels: maintainer, type: update

#9800 pv: Fix detection of stat64 in Apple Silicon.
  sysutils/pv/Portfile
Labels: maintainer: open, type: bugfix, wip

#9901 glab: new port
  devel/glab/Portfile
Labels: type: enhancement, type: submission

#9907 google-cloud-sdk: update to 326.0.0
  devel/google-cloud-sdk/Portfile
Labels: maintainer, maintainer: open, type: update

#9906 minipro: fix checksums
  devel/minipro/Portfile
Labels: maintainer: open, type: bugfix

#9885 KeePassXC: update to version 2.6.4
  security/KeePassXC/Portfile
Labels: maintainer: none, type: update

#9905 shtools 4.8 (revision 1): add support for compilers PortGroup
  science/shtools/Portfile
Labels: maintainer, type: enhancement

#9902 lagrange: new port
  net/lagrange/Portfile
Labels: type: enhancement, type: submission

#9898 mozjs60: arm64: Code sign virtualenv python on arm64.
  lang/mozjs60/Portfile
  lang/mozjs60/files/patch-virtualenv-arm64-codesign.diff
Labels: maintainer: open, type: bugfix

#9893 freac,boca: add minimum macOS version
  audio/boca/Portfile
Labels: maintainer: open, type: enhancement

#9721 bazel: fix build for +bash_completion variant
  devel/bazel/Portfile
Labels: maintainer: open

#8986 samba4: Fix linking issues
  net/samba4/Portfile
Labels: maintainer: none, type: bugfix

#9911 jenkins-cli: update to 0.0.34
  devel/jenkins-cli/Portfile
Labels: maintainer, maintainer: open, type: enhancement, type: update

#9909 logtalk: update to 3.44.0
  lang/logtalk/Portfile
Labels: maintainer, type: update

#9908 auto-multiple-choice-devel: update to version 1.5.0-rc1
  x11/auto-multiple-choice/Portfile
Labels: maintainer, maintainer: open, type: enhancement, type: update

#9917 py-pyside2: requires at least Qt 5.12
  python/py-pyside2/Portfile
Labels: maintainer: open

#9912 auctex: update to version 12.3
  editors/auctex/Portfile
Labels: maintainer: none, type: bugfix, type: enhancement, type: update

#9913 py-cipheycore: new port
  python/py-cipheycore/Portfile
Labels: type: enhancement, type: submission

#9926 nomad: set supported_archs
  net/nomad/Portfile
Labels: maintainer: open, type: enhancement

#9925 py-cleo: Add python 37 subport
  python/py-cleo/Portfile
Labels: maintainer: open, type: bugfix

#9252 libvpx: fix configuration for arm64
  multimedia/libvpx/Portfile
  multimedia/libvpx/files/patch-build-make-configure.sh.diff
Labels: maintainer: open, type: bugfix

#9927 weechat: update to 3.0.1
  irc/weechat/Portfile
Labels: maintainer, maintainer: open, type: update

#9919 nektarpp: update to 5.0.1, add new variant +python39
  science/nektarpp/Portfile
  science/nektarpp/files/avoid-python-install.patch
  science/nektarpp/files/thirdparty-sources.patch
Labels: maintainer, maintainer: open, type: update

#9916 ossp-uuid: configure +perl5_32 variant correctly
  devel/ossp-uuid/Portfile
Labels: maintainer: none, type: bugfix

#9924 py-loguru: new port
  python/py-loguru/Portfile
Labels: type: enhancement, type: submission

#9923 py-pybase62: new port
  python/py-pybase62/Portfile
Labels: type: enhancement, type: submission

#9922 py-base91: new port
  python/py-base91/Portfile
Labels: type: enhancement, type: submission

#9921 py-base58: new port
  python/py-base58/Portfile
Labels: type: enhancement, type: submission

#9920 py-cipheydists: new port
  python/py-cipheydists/Portfile
Labels: type: enhancement

#9915 redis: update to 6.0.10
  databases/redis/Portfile
Labels: maintainer, maintainer: open, type: enhancement, type: update

#9928 Gloomhaven-Helper: Update to 3.4.8
  games/gloomhaven-helper/Portfile
Labels: by: member, maintainer, type: update

#9605 portfolio-performance: new port
  finance/portfolio-performance/Portfile
  finance/portfolio-performance/files/patch-disable-autoupdate-pref.diff
  finance/portfolio-performance/files/patch-remove-autoupdate-dialog.diff
Labels: type: submission

#9933 zabbix(4/5): Update 4.0.27/5.0.8
  net/zabbix4/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#9590 MacPass: New port
  devel/hnhui/Portfile
  devel/kissxml/Portfile
  devel/transformerkit/Portfile
  security/keepasskit/Portfile
  security/macpass/Portfile
  security/macpass/files/patch-remove-sparkle-app.diff
  security/macpass/files/patch-remove-sparkle-pref.diff
  security/macpass/files/patch-xcodeproj.diff
Labels: type: submission

#9939 fzf: update to 0.25.1
  sysutils/fzf/Portfile
Labels: maintainer, maintainer: open, type: update

#9934 py-click-spinner: Add python38 subport
  python/py-click-spinner/Portfile
Labels: maintainer, maintainer: open, type: enhancement

#9940 kotlin: update to 1.4.30
  lang/kotlin/Portfile
Labels: maintainer, maintainer: open, type: update

#9931 dbeaver-community: update to 7.3.4
  databases/dbeaver-community/Portfile
Labels: maintainer, maintainer: open, type: update

#9930 dbvis: update to 12.0.1
  databases/dbvis/Portfile
Labels: maintainer, maintainer: open, type: update

#9929 topgrade: update to 6.3.2
  sysutils/topgrade/Portfile
Labels: maintainer, maintainer: open, type: update

#9945 commitizen: update to 2.14.2
  devel/commitizen/Portfile
Labels: maintainer, maintainer: open, type: enhancement, type: update

#9946 isync: update to 1.4.0
  mail/isync/Portfile
Labels: maintainer, maintainer: open, type: update

#9949 deno: add support for aarch64
  devel/deno/Portfile
Labels: maintainer: open, type: enhancement

#9464 tilt: new port
  devel/tilt/Portfile
Labels: type: enhancement, type: submission

#9936 VisualVM: new port
  java/VisualVM/Portfile
Labels: type: submission

#9948 dnsviz: update to 0.9.2
  net/dnsviz/Portfile
Labels: maintainer, maintainer: open, type: update

#9941 libpsl: move to python 3.9
  net/libpsl/Portfile
Labels: maintainer: none, type: enhancement

#9888 ocaml-doc: update to 4.08
  lang/ocaml-doc/Portfile
Labels: maintainer: none, type: update

#9950 auctex: add texlive-bin-extra as build-dep
  editors/auctex/Portfile
Labels: maintainer, maintainer: open, type: bugfix

#9953 ansifilter: update to 2.18
  textproc/ansifilter/Portfile
Labels: maintainer, maintainer: open, type: update

#9951 redis: fix compilation on arm64
  databases/redis/Portfile
  databases/redis/files/patch-arm64.diff
Labels: maintainer, maintainer: open, type: bugfix

#8718 VLC : fix and upgrade to 3.0.11.1
  audio/phonon-backend-vlc/Portfile
  audio/phonon/Portfile
  audio/phonon/files/phonon
  audio/phonon/files/qt4/patch-CMakeLists.txt.diff
  audio/phonon/files/qt4/patch-cmake_FindPhononInternal.cmake.diff
  audio/phonon/files/qt4/patch-cmake_PhononMacros.cmake.diff
  audio/phonon/files/qt5/patch-support-older-qt5.diff
  kde/kde-extra-cmake-modules/Portfile
  kde/kde-extra-cmake-modules/files/patch-BUNDLEDIR.diff
  kde/kde-extra-cmake-modules/files/patch-doc-building.diff
  kde/kde-extra-cmake-modules/files/patch-enable-named-operators.diff
  kde/kde-extra-cmake-modules/files/patch-kdecompilerflags.diff
  kde/kde-extra-cmake-modules/files/patch-mac-installdirs.diff
  kde/kde-extra-cmake-modules/files/patch-qt_no_exceptions.diff
  multimedia/VLC/Portfile
  multimedia/VLC/files/configure.ac-no-arch.patch
  multimedia/VLC/files/libvlc.pc
  multimedia/VLC/files/lock.h
  multimedia/VLC/files/no-sparkle.patch
  multimedia/VLC/files/patch-build-on-darwin13.diff
  multimedia/VLC/files/patch-build-on-pre-1012.diff
  multimedia/VLC/files/patch-ffmpegVLC.diff
  multimedia/VLC/files/patch-for-lua53.diff
  multimedia/VLC/files/patch-no-@rpath.diff
  multimedia/VLC/files/patch-no-hrtfs.diff
  multimedia/VLC/files/patch-soundfont-path.diff
  multimedia/VLC/files/patch-static_assert.diff
  multimedia/VLC/files/patch-use-NSGetEnviron.diff
  multimedia/VLC/files/patch-vda-ffmpeg34+.diff
  multimedia/VLC/files/patch-vlc-for-macports.diff
  multimedia/VLC/files/vlc-plugin.pc
  multimedia/VLC2/Portfile
  multimedia/VLC2/files/buildfix-package.mak.patch
  multimedia/VLC2/files/patch-build-on-post-1012.diff
  multimedia/VLC2/files/patch-buildsystem.diff
Labels: maintainer, maintainer: open

#9943 p5-tkx: update to 1.10
  perl/p5-tkx/Portfile
  perl/p5-tkx/files/0001-tkx-ed-remove-tclCarbonProcesses-usage.patch
Labels: maintainer, maintainer: open, type: update

#9952 gcal: update maintainer to mhberger
  science/gcal/Portfile
Labels: maintainer: open, type: update

#9954 turbogit: update to 2.0.0
  devel/turbogit/Portfile
Labels: maintainer, maintainer: open, type: update

#9869 qrupdate: Update Portfile for arm64
  math/qrupdate/Portfile
Labels: maintainer: none, type: bugfix, type: update

#9956 kustomize: update to 3.9.3
  devel/kustomize/Portfile
Labels: maintainer, maintainer: open, type: update

#9938 openconnect: make libproxy an optional dependency
  net/openconnect/Portfile
Labels: maintainer: none, type: enhancement

#8130 cgit: update dependencies
  www/cgit/Portfile
  www/cgit/files/patch-config-mak-uname.diff
Labels: maintainer: none, type: enhancement, type: update

#9932 py-cipheycore: Add compiler blacklist
  python/py-cipheycore/Portfile
Labels: maintainer, maintainer: open, type: bugfix

#9960 logisim-evolution: update fallback dependency
  cad/logisim-evolution/Portfile
Labels: maintainer, maintainer: open, type: bugfix, type: update

#9962 mos: update to 2.19.1
  devel/mos/Portfile
Labels: maintainer, maintainer: open, type: enhancement, type: update

#9963 mos-devel: update to 202102072216
  devel/mos-devel/Portfile
Labels: maintainer, maintainer: open, type: enhancement, type: update

#9935 dspdfviewer: new port
  office/dspdfviewer/Portfile
Labels: type: enhancement, type: submission

#9914 syncthing: update to 1.13.1
  net/syncthing/Portfile
Labels: maintainer: open, type: bugfix, type: enhancement, type: update

#9918 Minidlna: update to 1.3.0
  net/minidlna/Portfile
Labels: maintainer: requires approval, maintainer: timeout, type: update

#9964 py-cipheycore: Fix python3 configuration
  python/py-cipheycore/Portfile
Labels: maintainer, maintainer: open, type: bugfix

#9961 eksctl: update to 0.37.0
  sysutils/eksctl/Portfile
Labels: by: member, maintainer: open, type: update

#9965 py-mpi4py: add Python 3.9 subport
  python/py-mpi4py/Portfile
Labels: maintainer: none, type: bugfix, type: enhancement

#9966 ciphey: new port
  security/ciphey/Portfile
Labels: type: enhancement, type: submission

#9967 Readlineuniversal
  devel/readline/Portfile
Labels: by: member, maintainer: open, type: bugfix

#9971 httpie: update to 2.4.0
  net/httpie/Portfile
Labels: maintainer: open, type: update

#9973 google-cloud-sdk: update to 327.0.0
  devel/google-cloud-sdk/Portfile
Labels: maintainer, maintainer: open, type: update

#9969 vmd: new port
  textproc/vmd/Portfile
Labels: by: member, type: submission

#9937 zathura: add variant with synctex support
  office/zathura/Portfile
Labels: maintainer: open, type: enhancement

#9974 kustomize: update to 3.9.4
  devel/kustomize/Portfile
Labels: maintainer, maintainer: open, type: update

#9957 libmed: added patch for test10 compilation failure
  science/libmed/Portfile
  science/libmed/files/patch-test10.diff
Labels: maintainer: open, type: bugfix

#9978 MenuMeters: update maintainers
  aqua/MenuMeters/Portfile
Labels: maintainer: none, type: update

#9977 vcs_blackbox: update maintainers
  security/vcs_blackbox/Portfile
Labels: maintainer: open, type: update

#9972 opencv4: generate pkg-config file
  graphics/opencv4/Portfile
Labels: by: member, maintainer: open, type: enhancement

#9981 lagrange: update to 1.1.2
  net/lagrange/Portfile
Labels: maintainer, maintainer: open, type: enhancement, type: update

#9983 kustomize: update to 3.10.0
  devel/kustomize/Portfile
Labels: maintainer, maintainer: open, type: update

#9982 swi-prolog-devel: Updated to version 8.3.19
  lang/swi-prolog-devel/Portfile
Labels: maintainer, maintainer: open, type: update

#9947 py*-google-auth: upgrade to 1.25.0
  python/py-google-auth/Portfile
Labels: maintainer: open

#9976 libreoffice: switch to accepted patch
  office/libreoffice/Portfile
  office/libreoffice/files/patch-configure.diff
Labels: maintainer, maintainer: open, type: enhancement

#9990 libreoffice: move pkg-config calls to pre-configure
  office/libreoffice/Portfile
Labels: type: bugfix

#9986 rclone: update to 1.54.0
  net/rclone/Portfile
Labels: by: member, maintainer: open, type: update

#9992 gauche-dbd-mysql: delete neglected port
  databases/gauche-dbd-mysql/Portfile
Labels: maintainer: none

#9996 libreoffice: remove calls to pkg-config
  office/libreoffice/Portfile
Labels: maintainer, maintainer: open

#9999 sd: new port
  textproc/sd/Portfile
Labels: by: member, type: submission

#10000 auto-multiple-choice-devel: update to version 1.5.0_rc1-24-gb8156497
  x11/auto-multiple-choice/Portfile
Labels: maintainer, maintainer: open, type: enhancement, type: update

#9994 MyODBC: delete port
  databases/MyODBC/Portfile
  databases/MyODBC/files/mysql.data.template
  databases/MyODBC/files/mysql.driver.template
  databases/MyODBC/files/odbc.ini
Labels: maintainer: none

#10005 ortep3: new port
  science/ortep3/Portfile
Labels: type: submission

#10004 py27-scipy: add patch to fix build on Xcode 12
  python/py-scipy/Portfile
  python/py-scipy/files/patch-xcode12-fixes.27.diff
Labels: by: member, maintainer, maintainer: open, type: bugfix

#10006 ghc: Update to version 8.10.4
  lang/ghc/Portfile
Labels: maintainer, maintainer: open, type: enhancement, type: update

#9988 kompose: update to 1.22.0
  devel/kompose/Portfile
Labels: by: member, maintainer: open, type: update

#10008 ttyrec: Fix -Wimplicit-function-declaration
  sysutils/ttyrec/Portfile
  sysutils/ttyrec/files/implicit.patch
Labels: by: member, maintainer, maintainer: open, type: bugfix

#9993 dbow: delete neglected port
  devel/dbow/Portfile
  devel/dbow/files/patch-Makefile
  devel/dbow/files/patch-doc-Makefile
Labels: maintainer: none

#9816 inkscape: add openmaintainer and fix livecheck
  graphics/inkscape/Portfile
Labels: by: member, maintainer: requires approval, maintainer: timeout, type: bugfix, type: enhancement

#10010 py-sphinx-bootstrap-theme: Add py39
  python/py-sphinx-bootstrap-theme/Portfile
Labels: by: member, maintainer: none

#9490 openssh: restore launchd support in ssh-agent
  net/openssh/Portfile
  net/openssh/files/agent.patch
Labels: maintainer: none, type: bugfix

#10014 micronaut: update to 2.3.2
  java/micronaut/Portfile
Labels: maintainer, maintainer: open, type: update

#10013 openjdk: update to GraalVM 21.0.0.2
  java/openjdk/Portfile
Labels: maintainer, maintainer: open, type: update

#10015 skaffold: update to 1.20.0
  devel/skaffold/Portfile
Labels: maintainer, maintainer: open, type: update

#10009 ftnchek: new port
  devel/ftnchek/Portfile
Labels: type: submission

#10011 f77chk: new port
  devel/f77chk/Portfile
Labels: type: submission

#10012 f77_diagram: new port
  devel/f77_diagram/Portfile
Labels: type: enhancement, type: submission

#10016 gnome-vfs: new Portfile and patch to fix ticket #61889
  gnome/gnome-vfs/Portfile
  gnome/gnome-vfs/files/patch-test-async-directory.diff
Labels: maintainer: none

#9897 cairo: add fixes to allow building on older MacOS
  graphics/cairo-devel/Portfile
  graphics/cairo-devel/files/patch-cairo-quartz-surfaces.diff
  graphics/cairo/Portfile
  graphics/cairo/files/patch-cairo-quartz-surfaces.diff
Labels: by: member, maintainer: requires approval, type: bugfix

#10017 libreoffice: update to 7.1.1.1
  office/libreoffice/Portfile
Labels: maintainer, maintainer: open, type: update

#9754 stubby: update to 0.3.0
  net/stubby/Portfile
  net/stubby/files/patch-CMakeLists-fix-stubby-yml.diff
Labels: by: member, maintainer: open, type: update

#9998 name-that-hash: new port
  security/name-that-hash/Portfile
Labels: type: enhancement, type: submission

#10021 git-interactive-rebase-tool: Update to 2.0.0
  devel/git-interactive-rebase-tool/Portfile
Labels: maintainer, maintainer: open, type: update

#10019 stgit: Update to 1.0
  devel/stgit/Portfile
Labels: maintainer, maintainer: open, type: update

#9987 rancher-cli: update to 2.4.10
  devel/rancher-cli/Portfile
Labels: by: member, maintainer: open, type: update

#10002 usd: update to version 20.05
  graphics/usd/Portfile
  graphics/usd/files/patch-add-blender-mods.diff
  graphics/usd/files/patch-plugins-output-paths.diff
  graphics/usd/files/patch-tests-output-paths.diff
Labels: maintainer, type: update

#10028 socat: update to 1.7.4.1
  sysutils/socat/Portfile
Labels: by: member, maintainer: open, type: update

#10031 kustomize: update to 4.0.1
  devel/kustomize/Portfile
Labels: maintainer, maintainer: open, type: update

#10032 git-chglog: Update to 0.10.0
  sysutils/git-chglog/Portfile
Labels: maintainer, maintainer: open, type: update

#10020 qt5-qtwebkit: switch jpeg dependencies to libjpeg-turbo
  aqua/qt5/Portfile
Labels: maintainer: open, type: bugfix

#9980 fx: update to 20.0.2
  sysutils/fx/Portfile
Labels: by: member, maintainer: open, type: update

#10003 geos: update to 3.9.1
  science/geos/Portfile
Labels: maintainer: open, type: update

#10035 grafana: fix and relax build dependency
  net/grafana/Portfile
Labels: by: member, maintainer: open, type: enhancement

#10036 glab: update to 1.15.0
  devel/glab/Portfile
Labels: maintainer, maintainer: open, type: enhancement, type: update

#10038 py-rich: update to 9.11.0
  python/py-rich/Portfile
Labels: maintainer, maintainer: open, type: enhancement, type: update

#10037 name-that-hash: update to 1.1.3
  security/name-that-hash/Portfile
Labels: maintainer, maintainer: open, type: enhancement, type: update

#10039 glib2-devel: fix build on Lion
  devel/glib2-devel/Portfile
  devel/glib2-devel/files/patch-meson_build-atomic-test-older-clang-versions.diff
Labels: by: member, maintainer: open, type: bugfix

#10043 ncmpcpp: update URLs
  audio/ncmpcpp/Portfile
Labels: by: member, maintainer: open, type: update

#10041 kubeseal: update to 0.14.1
  sysutils/kubeseal/Portfile
Labels: by: member, maintainer: open, type: update

#10048 igraph: update to 0.9.0
  math/igraph/Portfile
Labels: maintainer, maintainer: open, type: bugfix, type: enhancement, type: update

#10045 just: update to 0.8.4
  sysutils/just/Portfile
Labels: by: member, maintainer: open, type: update

#10053 google-cloud-sdk: update to 328.0.0
  devel/google-cloud-sdk/Portfile
Labels: maintainer, maintainer: open, type: update

#10051 wireguard-go: update to 0.0.20210212
  net/wireguard-go/Portfile
Labels: maintainer, maintainer: open, type: update

#10050 Update databases/beekeeper-studio/Portfile to respect compiler
  databases/beekeeper-studio/Portfile
Labels: maintainer: open, type: bugfix, type: update

#10057 syncthing-macos: update to 1.13.1-1
  net/syncthing-macos/Portfile
Labels: maintainer: open, type: update
