Repository macports/macports-ports, pull requests merged in 2021-09, with the labels that each got.

#12042 google-cloud-sdk: update to 355.0.0
  devel/google-cloud-sdk/Portfile
Labels: type: update, maintainer, maintainer: open

#12043 ntpsec: update to 1.2.1
  sysutils/ntpsec/Portfile
  sysutils/ntpsec/files/patch-PreHighSierra.diff
Labels: type: update, maintainer, maintainer: open

#12052 swi-prolog-devel: Updated to version 8.3.29
  lang/swi-prolog-devel/Portfile
Labels: type: update, maintainer, maintainer: open

#12049 Gildas: update to 202109a
  science/gildas/Portfile
Labels: type: enhancement, type: update, maintainer

#11838 notcurses: 2.3.18 submission
  devel/notcurses/Portfile
Labels: type: submission

#12036 realpath: Update to 1.0.2
  sysutils/realpath/Portfile
  sysutils/realpath/files/version.patch
Labels: type: update, maintainer: requires approval, by: member

#12050 yubikey-manager: update to 4.0.5
  security/yubikey-manager/Portfile
Labels: type: enhancement, type: update, maintainer: open, by: member

#12044 brlaser: new port
  print/brlaser/Portfile
  print/brlaser/files/patch-absolute-filter-path.diff
  print/brlaser/files/patch-cups-1.1.diff
  print/brlaser/files/patch-no-open_memstream.diff
  print/brlaser/files/patch-no-stack-protector.diff
  print/brlaser/files/patch-tumble.diff
Labels: type: submission

#11945 OpenBLAS: use ARMV8 as default architecture for ARM
  math/OpenBLAS/Portfile
Labels: type: enhancement, maintainer, maintainer: open, by: member

#12059 docker: update to 20.10.8
  devel/docker/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#12060 rke: update to 1.3.0
  devel/rke/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#12061 kompose: update to 1.24.0
  devel/kompose/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#12058 rlwrap: update to v0.45.2 and add maintainer
  sysutils/rlwrap/Portfile
Labels: type: update, maintainer: none

#12065 flyway: update to 7.14.1
  java/flyway/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#12020 libprotozero: new port
  devel/protozero/Portfile
Labels: type: enhancement, type: submission

#12063 skaffold: update to 1.31.0
  devel/skaffold/Portfile
Labels: type: update, maintainer, maintainer: open

#12068 robodoc: update to 4.99.44
  devel/robodoc/Portfile
Labels: type: update, maintainer: none

#12062 arduino-cli: Fix livecheck regex
  devel/arduino-cli/Portfile
Labels: maintainer, maintainer: open

#12057 samba4: Update to version 4.14.7
  net/samba4/Portfile
  net/samba4/files/patch-fix-debug.diff
  net/samba4/files/patch-fix-st_atim.diff
Labels: type: update, maintainer: none

#12064 nauty: update to 2.7r2
  math/nauty/Portfile
Labels: type: update, maintainer, maintainer: open

#12025 allegro5: update to 5.2.7.0
  devel/allegro5/Portfile
Labels: type: update, maintainer: none

#11879 scala3: new port
  lang/scala3/Portfile
  lang/scala3/files/scala3
Labels: type: submission

#12011 libwebsockets: update to 4.2.2 and add maintainer
  devel/libwebsockets/Portfile
Labels: type: update, maintainer: open

#12070 openjdk: update openjdk8-openj9 to 8u302
  java/openjdk/Portfile
Labels: type: update, maintainer, maintainer: open

#12077 pqrs: update to v0.2.0
  devel/pqrs/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#12076 gopass: update to 1.12.8
  security/gopass/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#12074 sqlmap: update to 1.5.9
  security/sqlmap/Portfile
Labels: type: update, maintainer, maintainer: open

#11994 gmdb2: new port
  gnome/gmdb2/Portfile
Labels: type: submission

#12078 openjdk: update openjdk11-openj9 to 11.0.12
  java/openjdk/Portfile
Labels: type: update, maintainer, maintainer: open

#12079 clojure: update to 1.10.3.967
  lang/clojure/Portfile
Labels: type: update, maintainer, maintainer: open

#12086 openjdk: update openjdk16-openj9 to 16.0.2
  java/openjdk/Portfile
Labels: type: update, maintainer, maintainer: open

#12047 netcdf: update to 4.8.1
  science/netcdf/Portfile
Labels: type: update, maintainer: open

#12048 ecCodes: update to 2.23.0
  science/ecCodes/Portfile
Labels: type: update, maintainer: requires approval, maintainer: timeout

#11855 retdec: new port
  devel/retdec/Portfile
  devel/retdec/files/patch-python3.diff
  devel/retdec/files/patch-yara-syntax-error.diff
Labels: type: enhancement, type: submission

#12088 scala3.0: rename port
  lang/scala3.0/Portfile
  lang/scala3.0/files/scala3.0
  lang/scala3/Portfile
Labels: maintainer: none

#12092 minikube: update to 1.23.0
  sysutils/minikube/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#12066 py-docker: update to 5.0.2
  python/py-docker/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#12054 elasticsearch: Update to version 7.14.1
  databases/elasticsearch/Portfile
  databases/elasticsearch/files/patch-elasticsearch-env.diff
Labels: type: enhancement, type: update, maintainer: open

#12095 retroarch: update to 1.9.9
  emulators/retroarch/Portfile
Labels: type: update, maintainer, maintainer: open

#12094 melonds: update to 0.9.3
  emulators/melonds/Portfile
Labels: type: update, maintainer, maintainer: open

#12093 reddsaver: update to v0.4.0
  multimedia/reddsaver/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#12056 python310-devel: Rev bump libffi
  lang/python310-devel/Portfile
Labels: type: bugfix, maintainer: requires approval, maintainer: timeout

#12087 brook: New port
  net/brook/Portfile
Labels: type: submission

#12096 mcfly: Move scripts to share dir
  sysutils/mcfly/Portfile
Labels: maintainer: open

#12089 mysql8: update to 8.0.26
  databases/mysql8/Portfile
  databases/mysql8/files/patch-sql-local-boost.diff
Labels: type: bugfix, type: enhancement, type: update, type: security fix, maintainer: open

#12099 tree-sitter: add tree-sitter-cli subport
  devel/tree-sitter/Portfile
Labels: type: enhancement, maintainer: open

#12104 hamlib: add patch to use correct python*-config
  science/hamlib/Portfile
Labels: type: bugfix, maintainer: open, by: member

#12103 fheroes2: update to 0.9.7
  games/fheroes2/Portfile
  games/fheroes2/files/patch-readme-txt.diff
Labels: type: update, maintainer, maintainer: open

#12071 hashcat: update to 6.2.4
  security/hashcat/Portfile
Labels: type: update, maintainer: open

#12069 meson: Fix error building pango-devel with GCC
  devel/meson/Portfile
  devel/meson/files/patch-meson-gcc-appleframeworks.diff
  devel/meson/files/patch-meson55-gcc-appleframeworks.diff
Labels: type: bugfix, maintainer: open

#12105 git-credential-gopass: new port
  security/git-credential-gopass/Portfile
Labels: type: enhancement, type: submission

#12091 qcachegrind: update to 21.08.1
  devel/qcachegrind/Portfile
  devel/qcachegrind/files/0001-Fix-shell-invocations-for-MacPorts.patch
Labels: type: update, maintainer: requires approval

#12102 gnutar: add symlink gtar
  archivers/gnutar/Portfile
Labels: type: enhancement, maintainer: none

#12080 zsh-autosuggestions: update to 0.7.0
  sysutils/zsh-autosuggestions/Portfile
Labels: type: update, maintainer: open

#12090 meson: update to 0.59.1
  devel/meson/Portfile
Labels: type: update, maintainer: open

#12107 groovy: update to 3.0.9
  lang/groovy/Portfile
Labels: type: update, maintainer, maintainer: open

#12097 miniserve: update to 0.17.0
  net/miniserve/Portfile
  net/miniserve/files/patch-Cargo-toml-remove-git-package.diff
Labels: type: update, maintainer, maintainer: open

#12108 mysql8: broken symlink workaround
  databases/mysql8/Portfile
Labels: type: bugfix, maintainer: open

#10851 godot: update to version 3.3
  games/godot/Portfile
Labels: type: update, maintainer, maintainer: open

#12109 duckdb: enable httpfs extension by default
  databases/duckdb/Portfile
Labels: type: enhancement, maintainer: open

#11989 qemu: update to 6.1.0, add +target_arm to default_variants
  emulators/qemu/Portfile
  emulators/qemu/files/patch-configure.diff
Labels: type: enhancement, type: update, maintainer: open, by: member

#12111 yamllint: new port
  devel/yamllint/Portfile
Labels: type: submission

#12005 python3*: add dtrace variant
  lang/python310-devel/Portfile
  lang/python36/Portfile
  lang/python38/Portfile
  lang/python39/Portfile
Labels: type: enhancement, maintainer: requires approval, maintainer: timeout

#12110 cargo: update to 0.55.0
  devel/cargo/Portfile
Labels: type: update, maintainer: open

#12081 cmake: update to 3.21.2
  devel/cmake/Portfile
  devel/cmake/files/patch-Modules-noArchCheck.diff
  devel/cmake/files/patch-fix-system-prefix-path.diff
  devel/cmake/files/patch-qt5gui.diff
  devel/cmake/files/patch-restore-no-default-rpath-added-on-Tiger.diff
Labels: type: update, maintainer: requires approval

#12123 gdb: support +python39 variant
  devel/gdb/Portfile
Labels: type: enhancement, maintainer: none

#12083 gdbm: update to 1.21
  databases/gdbm/Portfile
  databases/gdbm/files/patch-fix-st_mtim.diff
Labels: type: update, maintainer: none

#12136 Claims maintainership on some ports
  devel/retdec/Portfile
  devel/sbt/Portfile
  lang/scala2.10/Portfile
  lang/scala2.11/Portfile
  lang/scala2.12/Portfile
  lang/scala2.13/Portfile
  lang/scala2.7/Portfile
  lang/scala2.8/Portfile
  lang/scala2.9/Portfile
  lang/scala3.0/Portfile
  mail/imapdedup/Portfile
  mail/offlineimap/Portfile
  python/py-rfc6555/Portfile
Labels: maintainer: none

#12148 notcurses: update to 2.4.0
  devel/notcurses/Portfile
Labels: type: update, maintainer, maintainer: open

#12022 libosmium: new port
  gis/libosmium/Portfile
Labels: type: enhancement, type: submission

#12156 devel/sbt: fix license
  devel/sbt/Portfile
Labels: maintainer, maintainer: open

#12155 scala3.0: fix livecheck regex
  lang/scala3.0/Portfile
Labels: maintainer, maintainer: open

#12112 py-musicbrainzngs: new port
  python/py-musicbrainzngs/Portfile
Labels: type: enhancement, type: submission

#12147 pango-devel: Fix Tiger build
  x11/pango-devel/Portfile
  x11/pango-devel/files/pango-tiger-no-coretext.diff
Labels: type: bugfix, maintainer: open

#12153 scala2.12 + 2.13: fixed license
  lang/scala2.12/Portfile
  lang/scala2.13/Portfile
Labels: type: enhancement, maintainer, maintainer: open

#12159 micronaut: update to 3.0.1
  java/micronaut/Portfile
Labels: type: update, maintainer, maintainer: open

#12158 google-cloud-sdk: update to 356.0.0
  devel/google-cloud-sdk/Portfile
Labels: type: update, maintainer, maintainer: open

#12140 py-country: enable python-3.9
  python/py-country/Portfile
Labels: type: enhancement, maintainer: none

#12114 py-confuse: new port
  python/py-confuse/Portfile
Labels: type: enhancement, type: submission

#12149 py-jsonpath-rw: new port
  python/py-jsonpath-rw/Portfile
Labels: type: enhancement, type: submission

#12152 haproxy: update to 2.4.4
  net/haproxy/Portfile
Labels: type: update, maintainer, maintainer: open

#12113 py-mediafile: new port
  python/py-mediafile/Portfile
Labels: type: enhancement, type: submission

#12115 py-munkres: new port
  python/py-munkres/Portfile
Labels: type: enhancement, type: submission

#12119 py-gpsoauth: new port
  python/py-gpsoauth/Portfile
Labels: type: enhancement, type: submission

#12117 py-validictory: new port
  python/py-validictory/Portfile
Labels: type: enhancement, type: submission

#12118 py-mechanicalsoup: new port
  python/py-mechanicalsoup/Portfile
Labels: type: enhancement, type: submission

#12160 py-pathvalidate: new port
  python/py-pathvalidate/Portfile
Labels: type: enhancement, type: submission

#12144 py-ibroadcast: new port
  python/py-ibroadcast/Portfile
Labels: type: enhancement, type: submission

#12162 py-pick: new port
  python/py-pick/Portfile
Labels: type: enhancement, type: submission

#12141 py-aubio: new port
  python/py-aubio/Portfile
Labels: type: enhancement, type: submission

#12143 py-termtables: new port
  python/py-termtables/Portfile
Labels: type: enhancement, type: submission

#12127 py-ifaddr: new port
  python/py-ifaddr/Portfile
Labels: type: enhancement, type: submission

#12139 py-grapheme: new port
  python/py-grapheme/Portfile
Labels: type: enhancement, type: submission

#12137 py-about-time: new port
  python/py-about-time/Portfile
Labels: type: enhancement, type: submission

#12125 py-last: new port
  python/py-last/Portfile
Labels: type: enhancement, type: submission

#12116 py-acoustid: new port
  python/py-acoustid/Portfile
Labels: type: enhancement, type: submission

#12124 py-discogs-client: new port
  python/py-discogs-client/Portfile
Labels: type: enhancement, type: submission

#12085 nvm: update to 0.38.0
  devel/nvm/Portfile
Labels: type: update, maintainer: open

#12154 glib2: fix build with latest Mason
  devel/glib2/Portfile
  devel/glib2/files/patch-meson_build-c-version.diff
Labels: maintainer: open, by: member

#12120 py-gmusicapi: new port
  python/py-gmusicapi/Portfile
Labels: type: enhancement, type: submission

#12169 rb-gettext: update to 3.4.1
  ruby/rb-gettext/Portfile
Labels: type: update, maintainer, maintainer: open

#12100 dupd: update to 1.7.1
  sysutils/dupd/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer: requires approval, maintainer: timeout

#12126 py-rarfile: new port
  python/py-rarfile/Portfile
Labels: type: enhancement, type: submission

#12128 py-soco: new port
  python/py-soco/Portfile
Labels: type: enhancement, type: submission

#12129 py-reflink: new port
  python/py-reflink/Portfile
Labels: type: enhancement, type: submission

#12138 py-alive-progress: new port
  python/py-alive-progress/Portfile
Labels: type: enhancement, type: submission

#12135 fpc: fix livecheck
  lang/fpc/Portfile
Labels: type: bugfix, maintainer: open

#12121 sitecopy: allow newer neon versions
  www/sitecopy/files/patch-configure
Labels: type: bugfix, maintainer: requires approval, by: member

#12122 ninja: fix cross-arch universal build
  devel/ninja/Portfile
  devel/ninja/files/patch-ninja-configure.py-remove-mmd.diff
Labels: type: bugfix, maintainer: open, by: member

#12131 py-mpd2: new port
  python/py-mpd2/Portfile
Labels: type: enhancement, type: submission

#12146 py-ttfquery: bump version 2.0.0b1
  python/py-ttfquery/Portfile
Labels: type: enhancement, maintainer: open

#12023 osmium-tool: new port
  gis/osmium-tool/Portfile
Labels: type: enhancement, type: submission

#12163 mvnd: new submission
  java/mvnd/Portfile
Labels: type: submission

#12130 mp3val: new port
  audio/mp3val/Portfile
  audio/mp3val/files/Makefile-cxxflags.patch
Labels: type: enhancement, type: submission

#12176 py-pyshark: Submission
  python/py-pyshark/Portfile
  python/py-pyshark/files/patch-config-ini.diff
Labels: type: enhancement, type: submission

#12167 httpie: update to 2.5.0
  net/httpie/Portfile
Labels: type: update, maintainer: open

#12182 gopls: update to 0.7.2
  devel/gopls/Portfile
Labels: type: update, maintainer: open, by: member

#12187 ghostscript: Apply patch for CVE-2021-3781
  print/ghostscript/Portfile
  print/ghostscript/files/patch-cve-2021-3781.diff
Labels: type: security fix, maintainer: none, by: member

#12170 syncthing: update to 1.18.2
  net/syncthing/Portfile
Labels: type: bugfix, type: update, maintainer: open

#12193 pv: Update to 1.6.19
  sysutils/pv/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#12191 Gocryptfs: Exclude pre-release versions from livecheck
  fuse/gocryptfs/Portfile
Labels: type: enhancement, maintainer, maintainer: open

#12188 retdec-devel: update to 20210910
  devel/retdec/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#12190 emacs{-app}-devel: update to 2021-09-10
  editors/emacs/Portfile
Labels: type: enhancement, type: update, maintainer: open

#11951 dovecot: update to 2.3.16
  mail/dovecot/Portfile
  mail/dovecot/files/dovecot-core-pushnotify.patch
  mail/dovecot/files/patch-src-master-master-settings.c.diff
Labels: type: update, type: security fix, maintainer: open, by: member

#11696 nautilus: require +x11 variant for gtk3
  gnome/nautilus/Portfile
Labels: type: enhancement, maintainer: open

#12200 lite-xl: update to 2.0.2
  editors/lite-xl/Portfile
  editors/lite-xl/files/patch-meson-build.diff
Labels: type: enhancement, type: update, maintainer, maintainer: open, by: member

#12199 py-bottlenose: new port
  python/py-bottlenose/Portfile
Labels: type: enhancement, type: submission

#12197 py-zbar: new port
  python/py-zbar/Portfile
Labels: type: enhancement, type: submission

#12171 meson: update to 0.57.2 on Tiger
  devel/meson/Portfile
  devel/meson/files/patch-meson-powermacintosh.diff
  devel/meson/files/patch-meson55-gcc-appleframeworks.diff
  devel/meson/files/patch-meson57-tiger-no-rpath-fix.diff
Labels: type: enhancement, type: update, maintainer: open

#12207 stern: update to 1.20.1
  sysutils/stern/Portfile
Labels: type: update, maintainer, maintainer: open

#12204 Bump Python version for autojump to Python 3.9
  sysutils/autojump/Portfile
Labels: type: enhancement, maintainer: none

#12212 scrcpy: update to 1.19
  multimedia/scrcpy/Portfile
Labels: type: update, maintainer, maintainer: open

#12134 docbook-xsl: fix livecheck
  textproc/docbook-xsl/Portfile
Labels: type: bugfix, maintainer: open

#12213 bottom: update to 0.6.4
  sysutils/bottom/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#12208 gzip: Correctly bypass 2038 check
  archivers/gzip/Portfile
Labels: type: bugfix, maintainer: none

#12175 pcap-mode.el: Submission
  net/pcap-mode.el/Portfile
Labels: type: enhancement, type: submission

#12215 drill: new port
  net/drill/Portfile
Labels: type: submission, by: member

#12196 binwalk: update to 2.3.3
  cross/binwalk/Portfile
Labels: type: update, maintainer: open

#12216 rust-analyzer: update to 20210913
  devel/rust-analyzer/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#12214 notcurses: update to 2.4.1
  devel/notcurses/Portfile
Labels: type: update, maintainer, maintainer: open

#12211 lib3mf: correct license
  print/lib3mf/Portfile
Labels: type: enhancement, maintainer, maintainer: open

#12217 new port: micronucleus
  cross/micronucleus/Portfile
Labels: type: submission

#12157 godot: simplify clang version checking
  games/godot/Portfile
Labels: type: enhancement, maintainer

#12186 mozjs60: Support for 10.4, 10.5, and PowerPC
  lang/mozjs60/Portfile
  lang/mozjs60/files/patch-config-powerpc.diff
  lang/mozjs60/files/patch-js-shell.diff
  lang/mozjs60/files/patch-libatomic.diff
  lang/mozjs60/files/patch-malloc_default_purgeable_zone.diff
  lang/mozjs60/files/patch-no-libc++.diff
  lang/mozjs60/files/patch-powerpc.diff
  lang/mozjs60/files/patch-pthread_setname_np.diff
Labels: type: bugfix, maintainer: open

#12220 blender: fix Xcode minimum version requirement for macOS 10.13
  graphics/blender/Portfile
Labels: type: bugfix, type: enhancement, maintainer

#12205 pew: Add python39 compatibility
  python/py-pew/Portfile
  python/py-pew/files/pew39
  python/py-pythonz/Portfile
  python/py-rangehttpserver/Portfile
  python/py-resumable-urlretrieve/Portfile
Labels: type: enhancement, maintainer: open

#12173 pango-devel: Fix man page building on Tiger
  x11/pango-devel/Portfile
Labels: type: bugfix, maintainer: open

#11690 gdb-apple: PowerPC support
  devel/gdb-apple/Portfile
  devel/gdb-apple/files/patch-gdb-availability.diff
  devel/gdb-apple/files/patch-include-libiberty.h.diff
  devel/gdb-apple/files/patch-macosx-nat-info.c.diff
  devel/gdb-apple/files/patch-macosx-nat-threads.c.diff
  devel/gdb-apple/files/patch-macosx-tdep.c.diff
Labels: type: enhancement, maintainer: open

#12206 mutationpp: Bump version
  science/mutationpp/Portfile
Labels: type: enhancement, maintainer, maintainer: open

#12230 google-cloud-sdk: update to 357.0.0
  devel/google-cloud-sdk/Portfile
Labels: type: update, maintainer, maintainer: open
