Repository macports/macports-ports, pull requests merged in 2021-06, with the labels that each got.

#11183 lilypond: fix 62801
  textproc/lilypond/Portfile
  textproc/lilypond/files/patch-add-flex-to-include-devel.diff
  textproc/lilypond/files/patch-add-flex-to-include.diff
  textproc/lilypond/files/patch-fix-missing-override.diff
Labels: by: member, maintainer: open, type: bugfix

#11194 logtalk: update to 3.47.0
  lang/logtalk/Portfile
Labels: maintainer, type: update

#11168 neovim: switch back to LuaJIT
  editors/neovim/Portfile
Labels: by: member, maintainer: open, type: bugfix, type: enhancement

#11166 Gpilab updates
  python/py-gpilab-core/Portfile
  python/py-gpilab-examples/Portfile
  python/py-gpilab-framework/Portfile
  python/py-gpilab-framework/files/gpilab-36
  python/py-gpilab-framework/files/gpilab-39
  python/py-json-tricks/Portfile
  python/py-qimage2ndarray/Portfile
Labels: by: member, maintainer, maintainer: open

#11207 fzf: Update to 0.27.2
  sysutils/fzf/Portfile
Labels: maintainer: open, type: update

#11206 py-awscli: Update to 1.19.84
  python/py-awscli/Portfile
Labels: maintainer, maintainer: open, type: update

#11202 hcloud: Update to 1.23.0
  devel/hcloud/Portfile
Labels: maintainer, maintainer: open, type: update

#11204 pmd: Update to 6.35.0
  java/pmd/Portfile
Labels: maintainer, maintainer: open, type: update

#11201 dnsperf: Update to 2.6.0
  net/dnsperf/Portfile
Labels: maintainer, maintainer: open, type: update

#11195 sfm: new port
  sysutils/sfm/Portfile
Labels: type: enhancement, type: submission

#11210 swi-prolog-devel: Updated to version 8.3.25
  lang/swi-prolog-devel/Portfile
Labels: maintainer, maintainer: open, type: update

#11205 py-Faker: Update to 8.4.0
  python/py-Faker/Portfile
Labels: maintainer, maintainer: open, type: update

#11200 dbeaver-community: Update to 21.1.0
  databases/dbeaver-community/Portfile
Labels: maintainer, maintainer: open, type: update

#11214 fswatch: update to 1.16.0
  sysutils/fswatch/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#11217 micronaut: update to 2.5.5
  java/micronaut/Portfile
Labels: maintainer, maintainer: open, type: update

#11215 google-cloud-sdk: update to 343.0.0
  devel/google-cloud-sdk/Portfile
Labels: maintainer, maintainer: open, type: update

#11216 josm: update to 17919
  gis/JOSM/Portfile
Labels: maintainer, maintainer: open, type: enhancement, type: update

#11030 GitUp: new port
  devel/GitUp/Portfile
  devel/GitUp/files/patch-disable-clt-install.diff
  devel/GitUp/files/patch-disable-sparkle.diff
  devel/GitUp/files/patch-exclude-arm-below-bigsur.diff
  devel/GitUp/files/patch-libgit2.diff
Labels: type: submission

#10996 llvm/clang/lldb-12: new port
  lang/llvm-12/Portfile
  lang/llvm-12/files/0001-MacPorts-only-clang-use-MP-omp-locations.patch
  lang/llvm-12/files/0002-MacPorts-Only-Don-t-embed-the-deployment-target-in-t.patch
  lang/llvm-12/files/0003-MacPorts-Only-Prepare-clang-format-for-replacement-w.patch
  lang/llvm-12/files/0004-MacPorts-Only-Fix-name-of-scan-view-executable-insid.patch
  lang/llvm-12/files/0005-clang-support-macports-libstdcxx.patch
  lang/llvm-12/files/0006-Define-EXC_MASK_CRASH-and-MACH_EXCEPTION_CODES-if-th.patch
  lang/llvm-12/files/0007-Threading-Only-call-pthread_setname_np-if-we-have-it.patch
  lang/llvm-12/files/0008-Threading-Only-call-setpriority-PRIO_DARWIN_THREAD-0.patch
  lang/llvm-12/files/0009-lib-Support-Unix-Path.inc-define-COPYFILE_CLONE-if-n.patch
  lang/llvm-12/files/0010-compiler-rt-cmake-config-ix.cmake-was-Leopard-No-ASA.patch
  lang/llvm-12/files/0011-Fix-missing-long-long-math-prototypes-when-using-the.patch
  lang/llvm-12/files/0012-compiler-rt-add-some-defs-missing-in-older-SDKs.patch
  lang/llvm-12/files/0013-clang-add-back-runtime-libraries-used-on-10.4-and-10.patch
  lang/llvm-12/files/0014-Fix-float.h-to-work-on-Snow-Leopard-and-earlier.patch
  lang/llvm-12/files/0015-Fixup-libstdc-header-search-paths-for-older-versions.patch
  lang/llvm-12/files/0016-10.10-and-less-compiler-rt-find-macosx-sdk.patch
  lang/llvm-12/files/0017-10.6-and-less-libcxx-work-around-no-reexported_symbo.patch
  lang/llvm-12/files/0018-10.6-and-less-clang-default-to-libc-on-all-darwin-sy.patch
  lang/llvm-12/files/0019-10.6-and-less-use-emulated-TLS-before-10.7.patch
  lang/llvm-12/files/0020-10.6-and-less-work-around-no-directory-watcher-befor.patch
  lang/llvm-12/files/0021-10.6-and-less-libcxx-disable-Availability-tests.patch
  lang/llvm-12/files/0022-10.5-and-less-default-to-fno-blocks.patch
  lang/llvm-12/files/0023-10.5-and-less-use-older-cfname-and-fix-uuid-on-leopa.patch
  lang/llvm-12/files/0024-10.5-and-less-compiler-rt-work-around-no-libdispatch.patch
  lang/llvm-12/files/llvm-bin
  lang/llvm-12/files/llvm-bin-compat
  lang/llvm-12/files/mp-clang-12
  lang/llvm-12/files/mp-llvm-12
Labels: by: member, type: submission

#11208 syncthing: update to 1.17.0
  net/syncthing/Portfile
Labels: maintainer: open, type: bugfix, type: enhancement, type: update

#11219 dart-sass: update to 1.34.1
  www/dart-sass/Portfile
Labels: maintainer, maintainer: open, type: update

#11211 libck: Update to 0.7.1
  devel/libck/Portfile
Labels: maintainer, maintainer: open, type: update

#11220 docker: update to 20.10.7
  devel/docker/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#11212 elinks-devel: update python version to 3.9
  www/elinks-devel/Portfile
Labels: maintainer: none, type: update

#11227 lang/sbcl: update to sbcl-2.1.5
  lang/sbcl/Portfile
  lang/sbcl/files/patch-compilation-with-old-sbcl.diff
  math/maxima/Portfile
Labels: by: member, maintainer: open, type: update

#11224 matterbridge: Update to 1.22.2
  net/matterbridge/Portfile
Labels: maintainer, maintainer: open, type: update

#11223 ansible-lint: Update to 5.0.11
  sysutils/ansible-lint/Portfile
Labels: maintainer, maintainer: open, type: update

#11199 abcMIDI: Update to 2021.05.25
  audio/abcMIDI/Portfile
Labels: maintainer, maintainer: open, type: update

#11228 py-boto3: update to 1.17.86
  python/py-boto3/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#11229 flyway: update to 7.9.2
  java/flyway/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#11221 latexdiff: update perl version to 5.30
  tex/latexdiff/Portfile
Labels: maintainer: none, type: update

#11226 Gildas: update to 202106b
  science/gildas/Portfile
Labels: maintainer, type: enhancement, type: update

#11189 gnss-sdr-[devel]: fix building crashes
  science/gnss-sdr/Portfile
  science/gnss-sdr/files/patch-fix-building.diff
  science/volk-gnss-sdr/Portfile
Labels: maintainer, maintainer: open, type: bugfix

#11197 molmol: fix build on Big Sur
  science/molmol/Portfile
  science/molmol/files/molmol-build.diff
Labels: maintainer, maintainer: open, type: bugfix

#11234 nuspell: remove dependency on boost
  textproc/nuspell/Portfile
Labels: by: member, maintainer: open, type: enhancement

#11237 py-Faker: Update to 8.5.1
  python/py-Faker/Portfile
Labels: maintainer, maintainer: open, type: update

#11238 podman: Update to 3.2.0
  sysutils/podman/Portfile
Labels: maintainer, maintainer: open, type: update

#11239 logcat-colorize: migrate to boost PG
  devel/logcat-colorize/Portfile
Labels: maintainer, maintainer: open, type: enhancement

#11233 drupal7: update to 7.81
  www/drupal7/Portfile
Labels: maintainer: none, type: bugfix, type: enhancement, type: update

#11235 libfive: migrate to boost PG
  graphics/libfive/Portfile
Labels: maintainer, maintainer: open, type: enhancement

#11198 py-igraph: add external_igraph variant
  python/py-igraph/Portfile
  python/py-igraph/files/patch-use-correct-cpp-stdlib.diff
Labels: maintainer, maintainer: open, type: enhancement

#11144 libreoffice: set Python version to 3.9
  office/libreoffice/Portfile
Labels: maintainer, maintainer: open, type: bugfix, type: enhancement, type: security fix

#11232 protobuf-c: fix build on macOS 10.11 and earlier
  devel/protobuf-c/Portfile
Labels: maintainer: none, type: bugfix

#11240 pngquant: update to 2.15.1
  graphics/pngquant/Portfile
Labels: maintainer: none, type: update

#11218 npm6, npm7, yarn: switch to nodejs16 as the default NodeJs dependency.
  devel/npm6/Portfile
  devel/npm7/Portfile
  devel/yarn/Portfile
Labels: by: member, maintainer: open, type: enhancement

#11243 golang: add support for git.sr.ht packages
  _resources/port1.0/group/golang-1.0.tcl
Labels: type: enhancement

#11193 retroarch: update to 1.9.4
  emulators/retroarch/Portfile
Labels: maintainer, maintainer: open, type: update

#11244 ansible-lint: Update to 5.0.12
  sysutils/ansible-lint/Portfile
Labels: maintainer, maintainer: open, type: update

#11246 py-boto3: update to 1.17.88
  python/py-boto3/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#11250 nextdns: update to 1.32.3
  net/nextdns/Portfile
Labels: maintainer, maintainer: open, type: update

#11251 abseil: Update to 20210324.2
  devel/abseil/Portfile
Labels: maintainer: none, type: update

#11248 go-task: Update to version 3.4.3
  devel/go-task/Portfile
Labels: maintainer: open, type: update

#11247 tanka: Update to version 0.16.0
  sysutils/tanka/Portfile
Labels: maintainer: open, type: update

#11196 kerberos5: update python version to 3.9
  net/kerberos5/Portfile
Labels: maintainer: open, type: update

#11230 mkvtoolnix: use the new boost pg
  multimedia/mkvtoolnix/Portfile
Labels: by: member, maintainer: open, type: enhancement

#11213 new port: nushell
  shells/nushell/Portfile
Labels: type: submission

#11261 dbvis: update to 12.0.6
  databases/dbvis/Portfile
Labels: maintainer, maintainer: open, type: update

#11263 isync: update to 1.4.2
  mail/isync/Portfile
Labels: maintainer, maintainer: open, type: security fix, type: update

#11267 wordpress: update to 5.5.5
  www/wordpress/Portfile
Labels: maintainer: none, type: bugfix, type: security fix, type: update

#11268 Update libfmt (6.2.0) -> (7.1.3)
  devel/libfmt/Portfile
Labels: maintainer: none, type: enhancement, type: update

#11269 exim: another attempt to fix 10.11 build
  mail/exim/Portfile
Labels: maintainer: none

#11266 ghc: Update to version 8.10.5
  lang/ghc/Portfile
  lang/ghc/files/keyid-588764fbe22d19c4.txt
  lang/ghc/files/keyid-97db64ad.txt
  lang/ghc/files/patch-aclocal.m4.diff
  lang/ghc/files/patch-gmp-ghc.mk.diff
Labels: maintainer, maintainer: open, type: enhancement, type: update

#11222 texlive-bin-extra: update perl version to 5.30
  tex/texlive-bin-extra/Portfile
Labels: maintainer: requires approval, maintainer: timeout, type: update

#11163 libjpeg-turbo: update to 2.1.0
  graphics/libjpeg-turbo/Portfile
  graphics/libjpeg-turbo/files/CMakeLists.txt.patch
Labels: by: member, maintainer: requires approval, maintainer: timeout, type: enhancement, type: update

#11270 py-Faker: Update to 8.6.0
  python/py-Faker/Portfile
Labels: maintainer, maintainer: open, type: update

#11271 sqlmap: Update to 1.5.6
  security/sqlmap/Portfile
Labels: maintainer, maintainer: open, type: update

#11255 macfuse: codesign binaries for arm64
  fuse/macfuse/Portfile
Labels: maintainer, maintainer: open, type: bugfix

#11120 mysql4: delete EOL port
  aqua/qt3-mac/Portfile
  databases/mysql4/Portfile
  databases/mysql4/files/my.cnf
  databases/mysql5/Portfile
  databases/mysqltcl/Portfile
  databases/mysqlxx/Portfile
  databases/soci/Portfile
  lang/php/Portfile
  mail/exim/Portfile
  multimedia/mythtv.28/Portfile
  net/mediatomb/Portfile
  python/py-mysql/Portfile
  ruby/rb-mysql/Portfile
  ruby/rb19-mysql/Portfile
  security/libpreludedb/Portfile
Labels: maintainer: requires approval, maintainer: timeout

#11096 Mysql8 is GA, update socket paths
  lang/php/Portfile
Labels: maintainer: requires approval, maintainer: timeout

#11273 adns: Update to 1.6.0
  net/adns/Portfile
  net/adns/files/patch-client__Makefile.in
  net/adns/files/patch-configure.diff
  net/adns/files/patch-dynamic__Makefile.in
  net/adns/files/patch-src__Makefile.in
  net/adns/files/patch-src__internal.h
Labels: maintainer: none, type: update

#11274 google-cloud-sdk: update to 344.0.0
  devel/google-cloud-sdk/Portfile
Labels: maintainer, maintainer: open, type: update

#11253 gmt6: update to 6.2.0
  science/gmt5/Portfile
Labels: maintainer: open, type: update

#11276 jruby: Update to 9.2.18.0
  lang/jruby/Portfile
Labels: maintainer, maintainer: open, type: update

#11279 py-onnx: dependencies cleanup
  python/py-onnx/Portfile
Labels: maintainer: none

#11256 dialog, libdialog: Update to 1.3.20210530
  devel/dialog/Portfile
Labels: maintainer: none, type: update

#11282 rxvt-unicode: use perl 5.30
  x11/rxvt-unicode/Portfile
Labels: maintainer, maintainer: open

#11278 yara: prepare for Python 3.10
  security/yara/Portfile
Labels: maintainer: none

#11281 zig: update to 0.8.0
  lang/zig/Portfile
Labels: maintainer: open, type: update

#11277 p5.26-io-socket-ssl: trivial change to retry build
  perl/p5-io-socket-ssl/Portfile
Labels: maintainer: none

#11287 skaffold: update to 1.26.0
  devel/skaffold/Portfile
Labels: maintainer, maintainer: open, type: update

#11249 gopass: Update to 1.12.6
  security/gopass/Portfile
Labels: maintainer: open, type: update

#11289 gnuplot: update to 5.4.2
  math/gnuplot/Portfile
Labels: by: member, maintainer: open, type: update

#10842 ctags: update license to indicate that the library part is public domain
  devel/ctags/Portfile
Labels: maintainer: none, type: enhancement

#11209 nnn: update to 4.1.1
  sysutils/nnn/Portfile
Labels: maintainer: open, type: enhancement, type: update

#11298 dbvis: update to 12.0.7
  databases/dbvis/Portfile
Labels: maintainer, maintainer: open, type: update

#11297 topgrade: update to 7.0.1
  sysutils/topgrade/Portfile
Labels: maintainer, maintainer: open, type: update

#11291 caddy: update to 2.4.1
  www/caddy/Portfile
  www/caddy/files/patch-nosql.diff
Labels: maintainer, maintainer: open, type: update

#11259 nco: update to 4.9.9
  science/nco/Portfile
Labels: maintainer: requires approval, maintainer: timeout, type: enhancement, type: update

#11258 ecCodes: update to 2.22.0
  science/ecCodes/Portfile
Labels: maintainer: requires approval, maintainer: timeout, type: enhancement, type: update

#11252 bfs: Update to 2.2.1
  sysutils/bfs/Portfile
Labels: maintainer: open, type: update

#11284 py-userpath: Update to version 1.6.0
  python/py-userpath/Portfile
Labels: maintainer: open, type: update

#11264 nheko, openimageio, openal-soft, poppler, xaos: compiler blacklist cleanup
  audio/openal-soft/Portfile
  graphics/openimageio/Portfile
  graphics/poppler/Portfile
  graphics/xaos/Portfile
  net/nheko/Portfile
Labels: maintainer: requires approval

#11295 cosign: New port
  security/cosign/Portfile
Labels: type: submission

#11285 pipx: Update to version 0.16.3
  python/pipx/Portfile
Labels: maintainer: open, type: update

#11294 mdbtools: Update GitHub location
  databases/mdbtools/Portfile
Labels: maintainer: none, type: bugfix, type: update

#11288 py-graph-tool: Update to version 2.37, portgroup boost, bugfixes
  python/py-graph-tool/Portfile
Labels: maintainer: none, type: bugfix, type: enhancement, type: update

#11306 tmux: update to 3.2a
  sysutils/tmux/Portfile
Labels: maintainer, maintainer: open, type: update

#11301 py-botocore: update to 1.20.91
  python/py-botocore/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#11310 py-boto3: update to 1.17.91
  python/py-boto3/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#11311 logisim-evolution: set fallback dep to openjdk16
  cad/logisim-evolution/Portfile
Labels: by: member, maintainer, maintainer: open, type: bugfix

#11180 fluidsynth: update to 2.1.9
  multimedia/fluidsynth/Portfile
  multimedia/fluidsynth/files/patch-external_project_cc.diff
Labels: maintainer: open, type: update

#10934 xca: update to 2.4.0
  security/xca/Portfile
  security/xca/files/rename-VERSION.patch
Labels: maintainer, maintainer: open, type: update

#11265 olm, tweeny, mtxclient, nheko: update maintainer's GitHub handle
  devel/olm/Portfile
  devel/tweeny/Portfile
  net/mtxclient/Portfile
  net/nheko/Portfile
Labels: maintainer: requires approval, maintainer: timeout

#11320 flyway: update to 7.10.0
  java/flyway/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#11317 ctop: Update to 0.7.6
  sysutils/ctop/Portfile
Labels: maintainer, maintainer: open, type: update

#11316 py-igraph: update to 0.9.5
  python/py-igraph/Portfile
  python/py-igraph/files/patch-use-correct-cpp-stdlib.diff
Labels: maintainer, maintainer: open, type: update

#11314 recode: update to 3.7.9
  textproc/recode/Portfile
Labels: maintainer: open, type: update

#11313 mpg123: update to 1.28.0
  audio/mpg123/Portfile
Labels: maintainer: none, type: update

#11321 py-boto3: update to 1.17.92
  python/py-boto3/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#11324 py-Faker: Update to 8.7.0
  python/py-Faker/Portfile
Labels: maintainer, maintainer: open, type: update

#11323 spring-boot-cli: update to 2.5.1
  java/spring-boot-cli/Portfile
Labels: maintainer, maintainer: open, type: update

#11322 skaffold: update to skaffold 1.26.1
  devel/skaffold/Portfile
Labels: maintainer, maintainer: open, type: update

#11325 libpst: update to 0.6.76
  devel/libpst/Portfile
Labels: maintainer: none, type: update

#11329 kitty: Update to 0.21.0
  aqua/kitty/Portfile
  aqua/kitty/files/patch-kitty-no-deprecated-declarations.diff
Labels: maintainer, maintainer: open, type: update

#11328 py-igraph: update to 0.9.6
  python/py-igraph/Portfile
Labels: maintainer, maintainer: open, type: update

#11327 libreoffice: update to 7.1.4.2
  office/libreoffice/Portfile
Labels: maintainer, maintainer: open, type: update

#11330 dvtm: port abandoned
  sysutils/dvtm/Portfile
Labels: maintainer: requires approval

#11307 fheroes2: new port
  games/fheroes2/Portfile
  games/fheroes2/files/patch-readme-txt.diff
Labels: type: submission

#11333 bpytop: prepare for Python 3.10
  sysutils/bpytop/Portfile
Labels: maintainer: open

#11319 py*-qscintilla-qt*: prepare for Python 3.10
  devel/qscintilla/Portfile
Labels: maintainer: open

#11331 grass7: prepare for Python 3.10
  gis/grass7/Portfile
Labels: maintainer: none

#11332 gsl: prepare for Python 3.10
  math/gsl/Portfile
Labels: maintainer: open

#11336 vtk: prepare for Python 3.10
  graphics/vtk/Portfile
Labels: maintainer: open

#11299 lensfun: prepare for Python 3.10
  graphics/lensfun/Portfile
Labels: maintainer: open

#11300 gpodder: prepare for Python 3.10
  gnome/gpodder/Portfile
Labels: maintainer: none

#11302 asymptote: prepare for Python 3.10
  graphics/asymptote/Portfile
Labels: maintainer: open

#11303 dbus-python: prepare for Python 3.10
  devel/dbus-python/Portfile
Labels: maintainer: open

#11304 openexr: prepare for Python 3.10
  graphics/openexr/Portfile
Labels: maintainer: open

#11241 Godot: Add Mavericks compatibility
  games/godot/Portfile
  games/godot/files/legacy-osx-defines.diff
Labels: maintainer: open, type: enhancement

#11292 matterhorn: update to 50200.13.0
  net/matterhorn/Portfile
Labels: maintainer, maintainer: open, type: update

#11337 paraview: prepare for Python 3.10
  science/paraview/Portfile
Labels: maintainer: open

#11338 libreoffice: prepare for Python 3.10
  office/libreoffice/Portfile
Labels: maintainer: open

#11340 py-ipython: prepare for Python 3.10
  python/py-ipython/Portfile
Labels: maintainer: open

#11341 py-ioflo: prepare for Python 3.10
  python/py-ioflo/Portfile
Labels: maintainer: none

#11346 fheroes2: fix build on older macOS versions
  games/fheroes2/Portfile
  games/fheroes2/files/patch-missing-headers.diff
Labels: maintainer, maintainer: open, type: bugfix

#11347 bwping: update to 2.3
  net/bwping/Portfile
Labels: maintainer, maintainer: open, type: update

#11344 pass: Update to 1.7.4 and remove variants
  security/pass/Portfile
  security/pass/files/patch-getopt-path.diff
Labels: maintainer: none, type: update

#11351 dnscrypt-proxy: update to 2.0.45
  net/dnscrypt-proxy/Portfile
Labels: maintainer: none, type: update

#11349 fheroes2: fix build issues on older macOS versions
  games/fheroes2/Portfile
  games/fheroes2/files/patch-mapregion-ctor.diff
Labels: maintainer, maintainer: open, type: bugfix

#11350 bwping: fix clock_gettime() issues on older systems
  net/bwping/Portfile
Labels: maintainer, maintainer: open, type: bugfix

#11357 procenv: new port
  sysutils/procenv/Portfile
Labels: by: member, type: enhancement, type: submission

#11360 bcprov: update to 1.69
  java/bcprov/Portfile
Labels: maintainer: none, type: bugfix, type: enhancement, type: update

#11354 spot: prepare for Python 3.10
  science/spot/Portfile
Labels: maintainer: none

#11355 flann: prepare for Python 3.10
  science/flann/Portfile
Labels: maintainer: none

#11348 innoextract: update to 1.9
  archivers/innoextract/Portfile
Labels: maintainer: open, type: update

#11339 py-pip: prepare for Python 3.10
  python/py-pip/Portfile
Labels: maintainer: open

#11335 nds2-client-swig: prepare for Python 3.10
  science/nds2-client-swig/Portfile
Labels: maintainer: open

#11356 volk-gnss-sdr: prepare for Python 3.10
  science/volk-gnss-sdr/Portfile
Labels: maintainer: open

#11352 SoapySDR: prepare for Python 3.10
  science/SoapySDR/Portfile
Labels: maintainer: open

#11342 ripgrep: update to 13.0.0
  textproc/ripgrep/Portfile
Labels: by: member, maintainer: open, type: update
