Repository macports/macports-ports, pull requests merged in 2021-11, with the labels that each got.

#12745 scala3.0: fix livecheck regex
  lang/scala3.0/Portfile
Labels: maintainer, maintainer: open

#12744 MenuMeters: update to 2.1.5
  aqua/MenuMeters/Portfile
Labels: type: update, maintainer, maintainer: open

#12739 checkssl: new port submission
  sysutils/checkssl/Portfile
Labels: type: submission

#12733 asciinema: update to 2.1.0, use python39
  sysutils/asciinema/Portfile
Labels: type: enhancement, type: update, maintainer: requires approval

#12740 libvpx-devel: respect configure.sdkroot & deployment target
  multimedia/libvpx-devel/Portfile
  multimedia/libvpx-devel/files/patch-configure.sh.diff
Labels: type: bugfix, maintainer: open

#12754 py-xlsxwriter: 3.0.2
  python/py-XlsxWriter/Portfile
Labels: maintainer, maintainer: open, by: member

#12748 mackup: update to 0.8.33, use python39
  sysutils/mackup/Portfile
Labels: type: enhancement, type: update, maintainer: open

#12764 prometheus: update to 2.31.0
  sysutils/prometheus/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#12766 fzy: Use makefile port group
  devel/fzy/Portfile
Labels: type: enhancement, maintainer: none

#12718 mscompress: new port
  archivers/mscompress/Portfile
Labels: type: enhancement, type: submission

#12765 beets-devel: update to 20211102
  audio/beets/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#12602 easytag-devel: new subport
  audio/easytag/Portfile
Labels: type: enhancement, maintainer: open

#12759 py-parsing: enable pep517 build
  python/py-parsing/Portfile
Labels: maintainer: open, by: member

#12769 py-reflink: fixed build before Sierra
  python/py-reflink/Portfile
  python/py-reflink/files/before-sierra.patch
Labels: type: bugfix, maintainer, maintainer: open

#12781 syncthing: update to 1.18.4
  net/syncthing/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer: open

#12777 google-cloud-sdk: update to 363.0.0
  devel/google-cloud-sdk/Portfile
Labels: type: update, maintainer, maintainer: open

#12779 redis: update to 6.2.6
  databases/redis/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#12767 py-rsa: Disable test.run for PY35,36
  python/py-rsa/Portfile
Labels: maintainer: open, by: member

#12784 lagrange: update to 1.8.0
  net/lagrange/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#12780 ruby22: fix build for Tiger/i386
  lang/ruby22/Portfile
  lang/ruby22/files/patch-ruby22-tigeri386.diff
Labels: type: bugfix, maintainer: open

#12775 ade: fix build on 10.4/10.5
  devel/ade/Portfile
Labels: type: bugfix, maintainer: open

#12757 apple-pki-bundle: Add macOS System Roots, utility scripts, and notes
  net/apple-pki-bundle/Portfile
  net/apple-pki-bundle/files/macOS System Roots 20211101.pem
  net/apple-pki-bundle/files/pems_add_to_macOS_System_Keychain.sh
  net/apple-pki-bundle/files/pems_not_in_pemfile.sh
  net/apple-pki-bundle/files/pems_that_wont_expire_soon.sh
Labels: type: enhancement, maintainer, maintainer: open

#12783 rspamd: Update to version 3.1
  mail/rspamd/Portfile
Labels: type: enhancement, type: update, maintainer: none

#12786 py-xhtml2pdf: add py39 and subcategory textproc
  python/py-xhtml2pdf/Portfile
Labels: maintainer: none

#12758 privoxy: Add updated CAs from apple-pki-bundle, use its utility scripts
  www/privoxy/Portfile
Labels: type: enhancement, maintainer, maintainer: open

#12774 godot: update to version 3.3.2
  games/godot/Portfile
Labels: type: update, maintainer

#12768 Gildas: update to 202111a
  science/gildas/Portfile
Labels: type: enhancement, type: update, maintainer

#12792 privoxy: Default configuration for HTTP/2 keep alive behavior
  www/privoxy/files/patch-config.diff
Labels: maintainer, maintainer: open

#12790 materialx: update to version 1.38.2
  graphics/materialx/Portfile
Labels: type: update, maintainer

#12793 macos-fortress: Default configuration for HTTP/2 keep alive behavior
  net/macos-fortress/files/privoxy-config.macports
  net/macos-fortress/files/privoxy-config.patch
Labels: maintainer, maintainer: open

#12794 gcc-devel: drop patch
  lang/gcc-devel/Portfile
  lang/gcc-devel/files/patch-min-fixes-for-macOS-12-Monterey.x86.diff
Labels: maintainer: none

#12799 tanka: Update to version 0.18.2
  sysutils/tanka/Portfile
Labels: type: update, maintainer, maintainer: open

#12797 go-jsonnet: New port
  devel/go-jsonnet/Portfile
Labels: type: submission

#12796 weechat-devel: remove obsolete port
  irc/weechat-devel/Portfile
Labels: maintainer: none

#12795 advancemenu: remove obsolete port
  games/advancemenu/Portfile
Labels: maintainer: none

#12798 Remove multiple obsolete -devel ports
  devel/liblxqt-devel/Portfile
  devel/libqtxdg-devel/Portfile
  devel/lxqt-build-tools-devel/Portfile
  devel/qtermwidget-devel/Portfile
  sysutils/lxqt-openssh-askpass-devel/Portfile
  sysutils/qterminal-devel/Portfile
Labels: maintainer: none

#12751 GitUp: update patch to remove sparkle
  devel/GitUp/Portfile
  devel/GitUp/files/patch-disable-sparkle.diff
Labels: type: enhancement, type: update, maintainer: open

#12803 ifeffit: patches to compile on Catalina
  science/ifeffit/Portfile
  science/ifeffit/files/implicit.patch
Labels: type: bugfix, maintainer, maintainer: open

#12736 jumpcut: Update to 0.75
  aqua/jumpcut/Portfile
Labels: type: update, maintainer: none, by: member

#12804 privoxy: Bugfix
  www/privoxy/Portfile
Labels: type: bugfix, maintainer, maintainer: open

#12747 aria2: add bash-completion
  net/aria2/Portfile
Labels: type: enhancement, maintainer: requires approval, maintainer: timeout

#12805 macos-fortress: Bugfix
  net/macos-fortress/Portfile
Labels: maintainer, maintainer: open

#12760 py-wheel: enable pep517 build
  python/py-wheel/Portfile
Labels: maintainer: open, by: member

#12810 mysql8: fix configure on macOS 12.0
  databases/mysql8/Portfile
  databases/mysql8/files/patch-package_name.cmake.diff
Labels: type: bugfix, maintainer: open

#12788 fzf: update to 0.28.0
  sysutils/fzf/Portfile
Labels: type: update, maintainer: open, by: member

#12752 nushell: update to 0.39.0
  shells/nushell/Portfile
Labels: type: update, maintainer: open, by: member

#12668 k6: update to 0.34.1
  net/k6/Portfile
Labels: type: update, maintainer: open, by: member

#12809 openiked: new port
  net/openiked/Portfile
Labels: type: enhancement, type: submission

#12812 raylib: update to 4.0.0
  multimedia/raylib/Portfile
Labels: type: update, maintainer: open, by: member

#12782 josm: update to 18303
  devel/gh-grep/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#12808 py-{anytree,bottlenose}: resolve conflict
  python/py-anytree/Portfile
  python/py-anytree/files/patch-setup.py.diff
  python/py-bottlenose/Portfile
  python/py-bottlenose/files/patch-setup.py.diff
Labels: type: bugfix, maintainer, maintainer: open

#12753 nim: update to 1.6.0
  lang/nim/Portfile
Labels: type: enhancement, type: update, maintainer: open

#12746 qt5-qtdeclarative: remove old pre-activate
  aqua/qt5/Portfile
Labels: maintainer: open

#12785 py-html2text: add py39 and py310 subports
  python/py-html2text/Portfile
  python/py-html2text/files/py310-html2text
  python/py-html2text/files/py39-html2text
Labels: maintainer: open

#12603 liblas: patch endian setting for arm64
  gis/liblas/Portfile
  gis/liblas/files/liblas-endian_hpp.diff
Labels: type: bugfix, maintainer: none

#12791 beets-devel: update to 20211103
  audio/beets/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#12762 py-build: update to 0.7.0, add py310
  python/py-build/Portfile
  python/py-build/files/build_env.py.patch
Labels: type: update, maintainer: open, by: member

#12770 py-zipp: enable pep517 build
  python/py-zipp/Portfile
Labels: maintainer: open, by: member

#12771 py-typing_extensions: enable pep517 build
  python/py-typing_extensions/Portfile
Labels: maintainer: open, by: member

#12772 py-importlib-metadata: enable pep517 build
  python/py-importlib-metadata/Portfile
Labels: maintainer: open, by: member

#12773 py-importlib-resources: enable pep517 build
  python/py-importlib-resources/Portfile
Labels: maintainer: open, by: member

#12816 OpenIPMI: 2.0.32
  sysutils/OpenIPMI/Portfile
Labels: maintainer, maintainer: open, by: member

#12817 fheroes2: update to 0.9.9
  games/fheroes2/Portfile
Labels: type: update, maintainer, maintainer: open

#12815 notmuch: Bump to version 0.34.1
  mail/notmuch/Portfile
Labels: maintainer, maintainer: open

#12820 privoxy: Security fix and bugfix
  www/privoxy/Portfile
Labels: type: bugfix, maintainer, type: security fix, maintainer: open

#12800 dvdrtools: fix compile problems under 11.x and 12.x
  sysutils/dvdrtools/Portfile
  sysutils/dvdrtools/files/patch-fix-missing-include.diff
Labels: type: bugfix, maintainer: none

#12823 pspp-devel: fix build on Tiger
  math/pspp-devel/Portfile
Labels: type: bugfix, maintainer: requires approval

#12827 py-huggingface_hub: Update to version 0.1.1
  python/py-huggingface_hub/Portfile
Labels: type: enhancement, type: update, maintainer: none

#12801 pkcs11-helper: update to 1.27 and patch to fix compile problems
  security/pkcs11-helper/Portfile
  security/pkcs11-helper/files/patch-nssfix.diff
Labels: type: bugfix, type: enhancement, type: update, maintainer: none

#12829 topgrade: update to 8.0.3
  sysutils/topgrade/Portfile
Labels: type: update, maintainer, maintainer: open

#12831 SilentKnight: update to 1.17
  sysutils/SilentKnight/Portfile
Labels: type: update, maintainer, maintainer: open

#12832 VisualVM: update to 2.1.1
  java/VisualVM/Portfile
Labels: type: update, maintainer, maintainer: open

#12830 dbvis: update to 12.1.4
  databases/dbvis/Portfile
Labels: type: update, maintainer, maintainer: open

#12761 turbovnc-viewer: update call to java_set_env
  x11/turbovnc-viewer/Portfile
Labels: type: bugfix, type: update, maintainer, maintainer: open

#12825 py-absl: Update to version 0.15.0
  python/py-absl/Portfile
Labels: type: enhancement, type: update, maintainer: open

#12826 py-datasets: Updsate to version 1.15.1
  python/py-datasets/Portfile
Labels: type: enhancement, maintainer: none

#12824 py-transformers: Update to version 4.12.3
  python/py-transformers/Portfile
Labels: type: enhancement, type: update, maintainer: none

#12834 hugo: update to 0.89.1
  www/hugo/Portfile
Labels: type: update, maintainer, maintainer: open

#12833 jdupes: update to 1.20.2
  sysutils/jdupes/Portfile
Labels: type: update, maintainer, maintainer: open

#12828 libcaca: remove need for compiler blacklist
  graphics/libcaca/Portfile
  graphics/libcaca/files/patch-fix-implicit-function.diff
  graphics/libcaca/files/patch-libcaca-common-image.diff
Labels: type: bugfix, maintainer: none

#12841 kubectx: Fixed/Updated dependency to kubectl-1.22
  sysutils/kubectx/Portfile
Labels: type: bugfix, maintainer: open

#12839 libcaca: fix Tiger build
  graphics/libcaca/Portfile
  graphics/libcaca/files/patch-libcaca-tiger.diff
Labels: type: bugfix, maintainer: none

#12840 clojure: update to 1.10.3.1020
  lang/clojure/Portfile
Labels: type: update, maintainer, maintainer: open

#12843 opensmtpd: Use OpenSSL portgroup
  mail/opensmtpd/Portfile
Labels: type: enhancement, maintainer

#12842 gingerblue: new port
  gnome/gingerblue/Portfile
Labels: type: enhancement, type: submission

#12438 moc: patches to build on BigSur / M1
  multimedia/moc/Portfile
Labels: maintainer: none

#12488 osm2pgsql: Specify lua as the default variant
  gis/osm2pgsql/Portfile
Labels: type: enhancement, maintainer: open

#12729 libedit: Update to 20210910-3.1
  devel/libedit/Portfile
  devel/libedit/files/getline.c
  devel/libedit/files/patch-history.diff
  devel/libedit/files/readline.c.patch
  devel/libedit/files/src__Makefile.in.patch
Labels: type: update, maintainer: open, by: member

#12822 Tcl/Tk: update to 8.6.12
  lang/tcl/Portfile
  lang/tcl/files/implicit.patch
  x11/tk/Portfile
  x11/tk/files/patch-unix-Makefile.in.diff
Labels: type: bugfix, type: update, maintainer: open

#12847 librsvg-devel: tweak librsvg_fallback
  graphics/librsvg-devel/Portfile
Labels: type: enhancement, maintainer: open

#12857 sfm: update to 0.4
  sysutils/sfm/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#12802 ld64: avoid +llvm90 for ld64_xcode
  devel/ld64/Portfile
Labels: type: bugfix, maintainer: requires approval, maintainer: timeout

#12860 serf1: fix openssl include path preference
  www/serf1/Portfile
  www/serf1/files/patch-SConstruct-openssl-library-ordering.diff
Labels: type: bugfix, maintainer: none

#12850 cargo-c: update to 0.9.5
  devel/cargo-c/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer: open

#12845 libusb-devel: fix pre-Catalina build issues
  devel/libusb/Portfile
Labels: type: bugfix, maintainer: open

#12854 retroarch: update to 1.9.13
  emulators/retroarch/Portfile
Labels: type: update, maintainer, maintainer: open

#12858 dosbox-x: update to version 0.83.19
  emulators/dosbox-x/Portfile
Labels: type: update, maintainer: none

#12821 MPlayer: Support arm64 architecture.
  multimedia/MPlayer/Portfile
  multimedia/MPlayer/files/patch-configure-arm64.diff
Labels: type: bugfix, maintainer: open

#12861 tor: update to 0.4.6.8
  security/tor/Portfile
  security/tor/files/patch-tortls_openssl3.diff
Labels: type: bugfix, type: enhancement, type: update, maintainer: none

#12855 dovecot: Update to version 2.3.17
  mail/dovecot/Portfile
Labels: type: enhancement, type: update, maintainer: open

#12853 openrct2: update to 0.3.5, update objects
  games/openrct2/Portfile
Labels: type: update, maintainer, maintainer: open

#12865 postfix: Whitespace and legibility improvements
  mail/postfix/Portfile
Labels: maintainer: open

#12867 openssl3: fix PowerPC assembly generation
  devel/openssl3/Portfile
  devel/openssl3/files/ppc-xlate.pl
Labels: type: bugfix, maintainer: open

#12873 Revert "py-parsing: upgrade to 3.0.5"
  python/py-parsing/Portfile
Labels: type: bugfix, maintainer: open

#12870 libewf: version bump from 20201210 to 20201230 and reverting back to openssl 1.1
  security/libewf/Portfile
Labels: type: bugfix, type: enhancement, maintainer: none

#12869 cadaver: add pkgconfig build dependency
  www/cadaver/Portfile
Labels: type: bugfix, maintainer, maintainer: open

#12848 openssl3: Fix i386 compile
  devel/openssl3/Portfile
  devel/openssl3/files/patch-fix-i386-atomics.diff
Labels: type: bugfix, maintainer: open

#12871 pkcs11-helper: reverted back to openssl 1.1 due to fix openssl 3 related problems
  security/pkcs11-helper/Portfile
Labels: type: bugfix, maintainer: none

#12872 privoxy: Fix -passout passphrase duplication code with newline bug
  www/privoxy/Portfile
  www/privoxy/files/openssl.cnf
Labels: type: bugfix, type: enhancement, maintainer, type: security fix, maintainer: open

#12876 openssl3: Only apply atomic patch when needed
  devel/openssl3/Portfile
Labels: type: bugfix, maintainer: open

#12814 cdo: update dependencies to use proj8
  science/cdo/Portfile
Labels: type: update, maintainer: open

#12877 openssl3: fix build on Tiger
  devel/openssl3/Portfile
Labels: type: bugfix, maintainer: open

#12844 retdec-devel: update to 20211107
  devel/retdec/Portfile
  devel/retdec/files/patch-openssl-3.0.diff
Labels: type: bugfix, type: enhancement, type: update, maintainer, maintainer: open

#12884 libcaca: fix patch level for Tiger patch
  graphics/libcaca/files/patch-libcaca-tiger.diff
Labels: type: bugfix, maintainer: none

#12882 tor: Fix activate issue when torrc already exists
  security/tor/Portfile
Labels: type: bugfix, maintainer: none

#12874 mpc: build and install documentation
  audio/mpc/Portfile
Labels: type: enhancement, maintainer: open

#12880 neomutt: update to 20211029
  mail/neomutt/Portfile
Labels: type: bugfix, type: enhancement, type: update, type: security fix, maintainer: open

#12750 fzf: add install helper, fix completion
  sysutils/fzf/Portfile
Labels: type: bugfix, maintainer: open

#12878 cadaver: fix macOS 10.15 build
  www/cadaver/Portfile
Labels: type: bugfix, maintainer, maintainer: open

#12890 tor: Fix destroot bug
  security/tor/Portfile
Labels: type: bugfix, maintainer: none

#12818 wolfssl: update to 5.0.0
  devel/wolfssl/Portfile
Labels: type: update, type: security fix, maintainer: requires approval, maintainer: timeout

#12883 openrct2: make distfiles contain versions in filenames
  games/openrct2/Portfile
Labels: type: bugfix, maintainer, maintainer: open

#12837 qt5*-qtbase: explicitly disable Vulkan support
  aqua/qt5/Portfile
  aqua/qt511/Portfile
  aqua/qt513/Portfile
Labels: type: bugfix, maintainer: open

#12892 crystal: update to 1.2.2
  lang/crystal/Portfile
  lang/crystal/files/patch-compiler.diff
  lang/crystal/files/patch-link.diff
Labels: type: update, maintainer, maintainer: open

#12888 KeePassXC: fix compilation issue of 2.6.6 on El Capitan
  security/KeePassXC/Portfile
  security/KeePassXC/files/patch-old-mac.diff
Labels: type: bugfix, maintainer: none

#12889 macos-fortress: Update to squid5
  net/macos-fortress/Portfile
  net/macos-fortress/files/squid-squid.conf.patch
  net/macos-fortress/files/squid.conf.macports
Labels: type: enhancement, type: update, maintainer, maintainer: open

#12852 tcl: use upstream approach in patch
  lang/tcl/files/implicit.patch
Labels: maintainer: open

#12894 libtasn1: use gnu99 instead of c99
  devel/libtasn1/Portfile
Labels: type: bugfix, maintainer: open

#12864 py-selenium: add Python 3.10 subport
  python/py-selenium/Portfile
Labels: type: enhancement, maintainer: open

#12896 hugo: update to 0.89.2
  www/hugo/Portfile
Labels: type: update, maintainer, maintainer: open

#12893 godot: work around compile error on macOS <= 10.10
  games/godot/Portfile
  games/godot/files/macosx-version-log_h-workaround.diff
Labels: type: bugfix, type: enhancement, maintainer

#12897 py-htmldocs: updates; add 310
  lang/py-htmldocs/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#12895 mysql56, mysql57, mysql8: add OpenSSL exception
  databases/mysql56/Portfile
  databases/mysql57/Portfile
  databases/mysql8/Portfile
Labels: maintainer: open

#12887 cdo: update to 2.0.0
  science/cdo/Portfile
Labels: type: enhancement, type: update, maintainer: open

#12836 darktable: update to 3.6.1
  graphics/darktable/Portfile
  graphics/darktable/files/patch-openmp-compiler-versions.diff
Labels: type: update, maintainer: open, by: member

#12904 lua-language-server: update nvim-lspconfig link
  lua/lua-language-server/Portfile
Labels: type: update, maintainer: open

#12905 igraph: update to 0.9.5
  math/igraph/Portfile
Labels: type: update, maintainer, maintainer: open

#11625 libjpeg-turbo: Support non-Altivec PowerPC
  graphics/libjpeg-turbo/Portfile
Labels: type: bugfix, maintainer: requires approval, maintainer: timeout

#12875 gingerblue: update port description and dependency on XML::Parser
  gnome/gingerblue/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#12910 libjpeg-turbo: update to 2.1.1
  graphics/libjpeg-turbo/Portfile
Labels: type: update, maintainer, by: member

#12902 privoxy: Add Privoxy tools, fix https
  www/privoxy/Portfile
  www/privoxy/files/openssl.cnf
  www/privoxy/files/patch-match-all.action.diff
Labels: type: enhancement, maintainer, type: security fix, maintainer: open

#12914 msieve: fix build on macOS 12 arm64
  math/msieve/Portfile
  math/msieve/files/patch-time.diff
Labels: maintainer: open

#12908 emacs-{,app-}devel: fix build on arm64
  editors/emacs/Portfile
Labels: type: bugfix, maintainer: open

#12913 py-docutils: add commit r8555 to address various usage issues
  python/py-docutils/Portfile
  python/py-docutils/files/patch-commit-8885.diff
Labels: type: bugfix, maintainer: open, by: member

#12909 mysql8: fix build on macOS 10.14
  databases/mysql8/Portfile
  databases/mysql8/files/patch-rpcgen.cmake.diff
Labels: type: bugfix, maintainer: open

#12907 crystal: add support for static linking
  lang/crystal/Portfile
  lang/crystal/files/patch-crypto.diff
  lang/crystal/files/patch-link.diff
  lang/crystal/files/patch-ssl.diff
  lang/crystal/files/patch-xml.diff
Labels: type: enhancement, maintainer, maintainer: open

#12891 ruby ports: enable parallel builds: part 1 (ruby26, ruby27, ruby30)
  lang/ruby26/Portfile
  lang/ruby27/Portfile
  lang/ruby30/Portfile
Labels: maintainer: requires approval, by: member

#12912 ruby ports: enable parallel builds: part 2 (ruby19 through ruby25)
  lang/ruby19/Portfile
  lang/ruby20/Portfile
  lang/ruby21/Portfile
  lang/ruby22/Portfile
  lang/ruby23/Portfile
  lang/ruby24/Portfile
  lang/ruby25/Portfile
Labels: type: bugfix, maintainer: open, by: member

#12885 libunistring: update Portfile to fix broken Tiger (10.4) build: trac …
  textproc/libunistring/Portfile
Labels: type: update, maintainer: none

#12900 seqan3: update to 3.1.0
  science/seqan3/Portfile
Labels: type: enhancement, type: update, maintainer: requires approval
