Repository macports/macports-ports, pull requests merged in 2021-10, with the labels that each got.

#12423 nsis: update to 3.08
  devel/nsis/Portfile
Labels: type: enhancement, type: update, maintainer: none

#12420 rb-nokogiri: update to 1.12.5
  ruby/rb-nokogiri/Portfile
Labels: type: update, maintainer, maintainer: open

#12429 py-{botocore,awscli,boto3}: update to 1.21.52, 1.20.52 and 1.18.52
  python/py-awscli/Portfile
  python/py-boto3/Portfile
  python/py-botocore/Portfile
Labels: type: update, maintainer, maintainer: open

#12389 py-curtsies: update to 0.3.7
  python/py-curtsies/Portfile
Labels: type: update, maintainer: open

#12428 keybase: update to 5.8.1
  security/keybase/Portfile
Labels: type: update, maintainer: none

#12427 sqlmap: update to 1.5.10
  security/sqlmap/Portfile
Labels: type: update, maintainer, maintainer: open

#12426 podman: update to 3.4.0
  sysutils/podman/Portfile
Labels: type: update, maintainer, maintainer: open

#12425 revive: update to 1.1.2
  devel/revive/Portfile
Labels: type: update, maintainer, maintainer: open

#12401 go-tools: update to 0.1.7
  devel/go-tools/Portfile
Labels: type: update, maintainer: open, by: member

#12402 glib2: fix universal build
  devel/glib2/Portfile
Labels: type: bugfix, maintainer: open, by: member

#12407 godot: fix regex handling for clang version detection
  games/godot/Portfile
Labels: type: bugfix, maintainer

#12441 py-Faker: update to 8.14.1
  python/py-Faker/Portfile
Labels: type: update, maintainer, maintainer: open

#12440 haproxy: update to 2.4.5
  net/haproxy/Portfile
Labels: type: update, maintainer, maintainer: open

#12439 ansible-lint: update to 5.2.0
  sysutils/ansible-lint/Portfile
Labels: type: update, maintainer, maintainer: open

#12448 micronaut: update to 3.0.3
  java/micronaut/Portfile
Labels: type: update, maintainer, maintainer: open

#12447 gitlab-runner: update to 14.3.2
  devel/gitlab-runner/Portfile
Labels: type: update, maintainer, maintainer: open

#12430 Gildas: update to 202110a
  science/gildas/Portfile
Labels: type: enhancement, type: update, maintainer

#12405 nnn: update to 4.3
  sysutils/nnn/Portfile
Labels: type: enhancement, type: update, maintainer: open

#12165 recutils: new submission
  databases/recutils/Portfile
Labels: type: submission

#12320 ogre: update to 13.0.1
  graphics/ogre/Portfile
  graphics/ogre/files/CMakeLists.txt-docs.patch
  graphics/ogre/files/CMakeLists.txt-objc.patch
  graphics/ogre/files/CMakeLists.txt-resources.patch
  graphics/ogre/files/patch-CMakeLists.txt.diff
  graphics/ogre/files/patch-CMake_CMakeLists.txt.diff
  graphics/ogre/files/patch-CMake_InstallResources.cmake
  graphics/ogre/files/patch-CMake_Packages_FindOGRE.cmake.diff
  graphics/ogre/files/patch-CMake_Packages_FindOIS.cmake.diff
  graphics/ogre/files/patch-CMake_Templates_SDK_CMakeLists.txt.in.diff
  graphics/ogre/files/patch-CMake_Utils_FindPkgMacros.cmake.diff
  graphics/ogre/files/patch-Docs_CMakeLists.txt.diff
  graphics/ogre/files/patch-OgreMain_CMakeLists.txt.diff
  graphics/ogre/files/patch-OgreMain_src_OSX_macUtils.cpp.diff
  graphics/ogre/files/patch-README_and_Tutorials_files.diff
  graphics/ogre/files/patch-Samples_Browser_CMakeLists.txt.diff
  graphics/ogre/files/patch-Samples_Browser_include_SampleBrowser_OSX.h.diff
  graphics/ogre/files/patch-Samples_CMakeLists.txt.diff
  graphics/ogre/files/patch-Samples_Media_CMakeLists.txt.diff
  graphics/ogre/files/patch-Tools_CMakeLists.txt.diff
  graphics/ogre/files/patch-Tools_XMLConverter_CMakeLists.txt.diff
  graphics/ogre/files/patch-rpaths.diff
Labels: type: bugfix, type: update, maintainer: none

#12457 xhyve: update to 20211002
  emulators/xhyve/Portfile
Labels: type: enhancement, type: update, maintainer

#12455 posix-macos-addons: update to 20211002
  devel/posix-macos-addons/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#12436 lablgtk2: update to version 2.18.11
  x11/lablgtk2/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer: open

#12458 s5cmd: update to v1.4.0
  net/s5cmd/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#12456 retdec-devel: update to 20211002
  devel/retdec/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#12454 autorestic: update to v1.2.0
  sysutils/autorestic/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#12453 fnm: update to v1.27.0
  devel/fnm/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#12451 totp-cli: update to v1.1.17
  security/totp-cli/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#12452 gitweb: update to v0.3.3
  devel/gitweb/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#12449 ntfs-3g: do not overwrite PortGroup dependencies
  fuse/ntfs-3g/Portfile
Labels: type: bugfix, maintainer: none

#12406 nco: update to 5.0.2
  science/nco/Portfile
Labels: type: update, maintainer: requires approval, maintainer: timeout

#12435 neovim: update to 0.5.1
  editors/neovim/Portfile
Labels: type: update, maintainer: open

#12434 postgis3: add port:pkgconfig to depends_build
  databases/postgis3/Portfile
Labels: type: enhancement, maintainer: open

#12463 gocryptfs: update to 2.2.0
  fuse/gocryptfs/Portfile
Labels: type: update, maintainer, maintainer: open

#12446 lowdown: update to 0.9.0
  textproc/lowdown/Portfile
Labels: type: update, maintainer: none

#12461 task: update to 2.6.0
  office/task/Portfile
Labels: type: enhancement, type: update, maintainer: none

#12465 py-argcomplete: update to 1.12.3
  python/py-argcomplete/Portfile
Labels: type: update, maintainer, maintainer: open

#12467 opencolorio: fix to compile with yaml-cpp 0.7.0
  graphics/opencolorio/Portfile
  graphics/opencolorio/files/patch-yaml-cpp-0.7.diff
Labels: type: bugfix, maintainer: open

#12469 py-typing: update to 3.10.0.0
  python/py-typing/Portfile
Labels: type: update, maintainer, maintainer: open

#12470 iperf3{,-devel}: update to {3.10.1, 20210928}
  net/iperf3/Portfile
Labels: type: update, maintainer, maintainer: open

#12393 mozjs52: deprecate
  lang/mozjs52/Portfile
Labels: maintainer: open

#12462 OpenBLAS: update to 0.3.18, update minimal architectures
  math/OpenBLAS/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open, by: member

#12472 lablgtk2: revbump after updating ocaml
  x11/lablgtk2/Portfile
Labels: type: bugfix, maintainer: open

#12474 Zabbix4/5: Update to 4.0.34/5.0.16
  net/zabbix4/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#12475 py-pydicom: 2.2.2
  python/py-pydicom/Portfile
Labels: maintainer, maintainer: open, by: member

#12396 git-lfs: update to 3.0.1
  devel/git-lfs/Portfile
Labels: type: update, maintainer: open, by: member

#12424 py-fabio: update to version 0.12.0
  python/py-fabio/Portfile
Labels: type: enhancement, type: update, maintainer: open

#12433 py-peakutils: update download info and python versions
  python/py-peakutils/Portfile
Labels: type: update, maintainer: open

#12478 swi-prolog-devel: Updated to version 8.5.0
  lang/swi-prolog-devel/Portfile
Labels: type: update, maintainer, maintainer: open

#12476 maven3: update to 3.8.3
  java/maven3/Portfile
Labels: type: update, maintainer: none

#12418 py-twisted: update to 21.7.0 (py36+), 21.2.0 (py35), fix fetch
  python/py-twisted/Portfile
Labels: type: update, maintainer: open, by: member

#12479 exploitdb: update to 2021-10-05
  security/exploitdb/Portfile
Labels: type: update, maintainer, maintainer: open

#12483 google-cloud-sdk: update to 360.0.0
  devel/google-cloud-sdk/Portfile
Labels: type: update, maintainer, maintainer: open

#12481 py-last: update to 4.3.0
  python/py-last/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#12482 fheroes2: update to 0.9.8
  games/fheroes2/Portfile
  games/fheroes2/files/patch-readme-txt.diff
Labels: type: update, maintainer, maintainer: open

#12477 jenv: new submission
  java/jenv/Portfile
Labels: type: submission

#12471 libatomic_ops: update to 7.6.12
  devel/libatomic_ops/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer: none

#12493 haproxy: update to 2.4.7
  net/haproxy/Portfile
Labels: type: update, maintainer, maintainer: open

#12721 py-igraph: update to 0.9.8
  python/py-igraph/Portfile
Labels: type: update, maintainer, maintainer: open

#12726 jdupes: update to 1.20.1
  sysutils/jdupes/Portfile
Labels: type: update, maintainer, maintainer: open

#12728 p11-kit: enable tests
  security/p11-kit/Portfile
Labels: type: enhancement, maintainer: open

#12727 git-lfs: update to 3.0.2
  devel/git-lfs/Portfile
Labels: type: update, maintainer: open, by: member

#12731 librsvg-devel: Use fallback for universal builds
  graphics/librsvg-devel/Portfile
Labels: type: bugfix, maintainer: open

#12174 boost: Try to fix cmake symlink creation.
  devel/boost/Portfile
Labels: type: bugfix, maintainer: open

#12734 ffmpeg-devel: some tweaks
  multimedia/ffmpeg-devel/Portfile
Labels: type: enhancement, maintainer: open

#12705 lua-language-server: Use legacysupport
  lua/lua-language-server/Portfile
Labels: maintainer, maintainer: open, by: member

#12723 lighttpd: update to 1.4.61
  www/lighttpd/Portfile
  www/lighttpd/files/errno_t.patch
Labels: type: update, maintainer: open

#12738 micronaut: update to 3.1.3
  java/micronaut/Portfile
Labels: type: update, maintainer, maintainer: open

#12737 skaffold: update to 1.34.0
  devel/skaffold/Portfile
Labels: type: update, maintainer, maintainer: open

#12711 qt5-qtbase: macOS 12 SDK compatibility fix
  aqua/qt5/Portfile
  aqua/qt5/files/patch-qiosurfacegraphicsbuffer.h.diff
Labels: type: bugfix, maintainer: open

#12675 bitwarden-cli: Build from sources
  security/bitwarden-cli/Portfile
Labels: type: enhancement, maintainer, maintainer: open

#12742 rpki-client: update to 7.4
  net/rpki-client/Portfile
Labels: type: enhancement, type: update, maintainer: none

#12741 bitwarden-cli: Update to 1.19.1
  security/bitwarden-cli/Portfile
Labels: type: update, maintainer, maintainer: open

#12394 ocaml-lwt: depend on ocaml-dune-configurator
  ocaml/ocaml-lwt/Portfile
Labels: type: bugfix, maintainer: open
