Repository macports/macports-ports, pull requests merged in 2021-03, with the labels that each got.

#10109 dialog: update to 1.3-20210117
  devel/dialog/Portfile
Labels: maintainer: none, type: bugfix, type: update

#10106 p5-compress-raw-lzma: update to 2.101.0
  perl/p5-compress-raw-lzma/Portfile
Labels: maintainer, maintainer: open, type: update

#10104 wireguard-tools: update to 1.0.20210223
  net/wireguard-tools/Portfile
Labels: maintainer, maintainer: open, type: update

#10119 qt5-qtwebkit: Add logic to allow compiling on ARM64 architectures
  aqua/qt5/Portfile
  aqua/qt5/files/patch-qtwebkit-FastMalloc.diff
  aqua/qt5/files/patch-qtwebkit-MachineStackMarker.cpp.diff
  aqua/qt5/files/patch-qtwebkit-Platform.h.diff
Labels: maintainer: open, type: bugfix

#10122 crystal: update to 0.36.1
  lang/crystal/Portfile
Labels: maintainer, maintainer: open, type: update

#10125 kustomize: update to 4.0.4
  devel/kustomize/Portfile
Labels: maintainer, maintainer: open, type: update

#10089 haskell_stack: Bugfix of stack_root
  _resources/port1.0/group/haskell_stack-1.0.tcl
Labels: type: bugfix

#10135 lang/sbcl: update to sbcl-2.1.2
  lang/sbcl/Portfile
  math/maxima/Portfile
Labels: by: member, maintainer: open

#10123 textproc/qpdf: trivial update to 10.2.0
  textproc/qpdf/Portfile
Labels: by: member, maintainer: none

#10136 micronaut: update to 2.3.4
  java/micronaut/Portfile
Labels: maintainer, maintainer: open, type: update

#10137 google-cloud-sdk: update to 330.0.0
  devel/google-cloud-sdk/Portfile
Labels: maintainer, maintainer: open, type: update

#10138 syncthing: update to 1.14.0
  net/syncthing/Portfile
Labels: maintainer: open, type: bugfix, type: enhancement, type: update

#10140 neovim: fix crash on Big Sur with Apple Silicon
  editors/neovim/Portfile
  editors/neovim/files/patch-CMakeLists.diff
Labels: maintainer: open, type: bugfix

#10142 py-h5py: Update to 3.2.0; upstream dropped py36.
  python/py-h5py/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#10056 buildbot: update to 2.10.1
  devel/buildbot-console-view/Portfile
  devel/buildbot-grid-view/Portfile
  devel/buildbot-pkg/Portfile
  devel/buildbot-waterfall-view/Portfile
  devel/buildbot-worker/Portfile
  devel/buildbot-www/Portfile
  devel/buildbot/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#10091 alex: Update
  devel/alex/Portfile
Labels: maintainer: none, type: enhancement, type: update

#10121 libslirp: new port
  net/libslirp/Portfile
Labels: type: enhancement, type: submission

#10149 clojure: update to 1.10.2.796
  lang/clojure/Portfile
Labels: maintainer, maintainer: open, type: update

#10143 kubectl: update to 1.20.4, 1.19.8, 1.18.16
  sysutils/kubectl/Portfile
Labels: maintainer: open, type: enhancement, type: update

#10128 swi-prolog-devel: Updated to version 8.3.20
  lang/swi-prolog-devel/Portfile
Labels: maintainer, maintainer: open, type: update

#10133 rspamd: Update to version 2.7
  mail/rspamd/Portfile
Labels: maintainer: none, type: enhancement, type: update

#10134 apache-solr8: Update to version 8.8.1
  java/apache-solr8/Portfile
Labels: maintainer, maintainer: open, type: enhancement, type: update

#10131 Hyperscan: Update to version 5.4.0
  textproc/hyperscan/Portfile
Labels: maintainer: none, type: enhancement, type: update

#10153 py-h5py: 3.2.1
  python/py-h5py/Portfile
Labels: by: member, maintainer, maintainer: open

#10154 minio[-mc]: Update to latest.
  www/minio-mc/Portfile
  www/minio/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#10058 gdal: add missing dependency on geos
  gis/gdal/Portfile
Labels: maintainer: open, type: bugfix

#10148 auto-multiple-choice-devel: update to version 1.5.0_rc2-2-gd3d7ea2
  x11/auto-multiple-choice/Portfile
Labels: maintainer, maintainer: open, type: enhancement, type: update

#10110 clamav-server: Bugfix
  sysutils/clamav-server/Portfile
  sysutils/clamav-server/files/patch-etc-clamd-conf-macports.diff
Labels: maintainer, maintainer: open, type: bugfix

#10111 macos-fortress: Update to Python38 dependencies
  net/macos-fortress/Portfile
  net/macos-fortress/files/pf.conf
Labels: maintainer, maintainer: open, type: enhancement, type: update

#10126 openimageio: update revision for dcmtk (revbump)
  graphics/openimageio/Portfile
Labels: maintainer: open, type: bugfix, type: update

#10124 libreoffice: update to 7.1.1.2
  office/libreoffice/Portfile
Labels: maintainer, maintainer: open, type: update

#10115 adblock2privoxy: Bugfix, Enhancement
  www/adblock2privoxy/Portfile
  www/adblock2privoxy/files/adblock2privoxy_blocklist.txt
Labels: maintainer, type: bugfix, type: enhancement

#8415 py-graph-tool: Update dependency to cgal5, remove old Python 35 and 36 versions
  python/py-graph-tool/Portfile
Labels: maintainer: none, type: enhancement, type: update

#10161 p5-extutils-cbuilder: revert epoch decrease
  perl/p5-extutils-cbuilder/Portfile
Labels: maintainer: none

#10165 tanka: new port
  sysutils/tanka/Portfile
Labels: type: submission

#10166 jsonnet-bundler: new port
  devel/jsonnet-bundler/Portfile
Labels: type: submission

#10164 blender: update to 2.90.0
  graphics/blender/Portfile
  graphics/blender/files/patch-macports-libs-creator.diff
  graphics/blender/files/patch-macports-libs-platform_apple.diff
  graphics/blender/files/patch-manpage-for-apple.diff
  graphics/blender/files/patch-unix-or-apple.diff
Labels: maintainer, type: update

#10087 SFML: Support Apple Silicon.
  multimedia/sfml/Portfile
  multimedia/sfml/files/patch-apple-silicon.diff
Labels: maintainer, maintainer: open, type: bugfix

#10163 rust: update to 1.50.0
  lang/rust/Portfile
  lang/rust/files/patch-src-librustc-llvm-lib.diff
Labels: by: member, maintainer, maintainer: open, type: update

#10116 ffmpeg: update to 4.3.2
  multimedia/ffmpeg/Portfile
Labels: by: member, maintainer: open, type: update

#10096 pandoc: Update
  textproc/pandoc/Portfile
Labels: maintainer: none, type: enhancement, type: update

#10145 autoconf: update to 2.71
  devel/autoconf/Portfile
  devel/autoconf/files/0001-tests-avoid-spurious-test-failure-with-libtool-2.4.3.patch
  devel/autoconf/files/use-macports-tools.patch
Labels: by: member, maintainer: requires approval, maintainer: timeout, type: update

#10108 libedit: Update to 20210216-3.1
  devel/libedit/Portfile
Labels: maintainer: open, type: update

#10168 cargo-bootstrap: update to 1.50.0
  devel/cargo/Portfile
Labels: by: member, maintainer: none, type: update

#10054 perl5.32: update to 5.32.1
  lang/perl5/Portfile
  lang/perl5/files/5.32/clean-up-paths.patch
  lang/perl5/files/5.32/enable-syscall-on-sierra.patch
  lang/perl5/files/5.32/fix-miniperl-linking-PR36438.patch
  lang/perl5/files/5.32/patch-Configure-remove-libs.diff
Labels: by: member, maintainer, maintainer: open, type: update

#10177 broot: update to 1.2.7, enable ARM64 support
  sysutils/broot/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#10169 py-igraph: update dependencies
  python/py-igraph/Portfile
  python/py-igraph/files/patch-cmake-args-fix.diff
Labels: maintainer, maintainer: open, type: bugfix, type: update

#10170 igraph: make compatible with old clang
  math/igraph/Portfile
Labels: maintainer, maintainer: open, type: bugfix

#10190 dbvis: update to 12.0.3
  databases/dbvis/Portfile
Labels: maintainer, maintainer: open, type: update

#10184 GPXSee: update to 8.8
  gis/GPXSee/Portfile
Labels: maintainer, maintainer: open, type: enhancement, type: update

#10183 lagrange: update to 1.2.2
  net/lagrange/Portfile
Labels: maintainer, maintainer: open, type: enhancement, type: update

#10192 directory-studio: update to 2.0.0.v20210213-M16
  databases/directory-studio/Portfile
Labels: maintainer, maintainer: open, type: update

#10189 igraph: require C++11
  math/igraph/Portfile
Labels: maintainer, maintainer: open, type: bugfix

#10195 micronaut: update to 2.4.0
  java/micronaut/Portfile
Labels: maintainer, maintainer: open, type: update

#10196 google-cloud-sdk: update to 331.0.0
  devel/google-cloud-sdk/Portfile
Labels: maintainer, maintainer: open, type: update

#10198 zabbix/zabbix2: Remove for good.
  net/zabbix/Portfile
  net/zabbix2/Portfile
Labels: by: member, maintainer: none

#10197 vips: update to version 8.10.5
  graphics/vips/Portfile
Labels: maintainer: requires approval, type: update

#10130 libp11: update to 0.4.11
  security/libp11/Portfile
Labels: maintainer: open, maintainer: timeout, type: bugfix, type: update

#10188 topgrade: update to 6.7.0
  sysutils/topgrade/Portfile
Labels: maintainer, maintainer: open, type: update

#10117 dart-sass: new port
  www/dart-sass/Portfile
Labels: type: enhancement, type: submission

#10204 weechat: update to 3.1
  irc/weechat/Portfile
Labels: maintainer, maintainer: open, type: update

#10205 mongoose: cleanup MacPorts < 2.6.0 handling
  www/mongoose/Portfile
Labels: maintainer: requires approval

#10200 py-clang/py-cytpeslib2: Update to latest.
  python/py-clang/Portfile
  python/py-ctypeslib2/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#10185 bsdsfv: cleanup MacPorts < 2.6.0 handling
  sysutils/bsdsfv/Portfile
Labels: maintainer: requires approval, maintainer: timeout

#10199 gdal: Update to 3.2.2
  gis/gdal/Portfile
Labels: maintainer: open, type: update

#10187 graphene: fix for arm64
  graphics/graphene/Portfile
Labels: maintainer: open, type: bugfix

#10172 blender: update to 2.90.1
  graphics/blender/Portfile
  graphics/blender/files/patch-macports-libs-platform_apple.diff
Labels: maintainer, type: update

#10159 fatsort: cleanup MacPorts < 2.6.0 handling
  sysutils/fatsort/Portfile
Labels: maintainer: requires approval, maintainer: timeout

#10158 vmdktool: cleanup MacPorts < 2.6.0 handling
  sysutils/vmdktool/Portfile
Labels: maintainer: requires approval, maintainer: timeout

#10141 opensmile: new port
  audio/opensmile/Portfile
Labels: type: enhancement, type: submission

#10097 lhs2tex: Update
  textproc/lhs2tex/Portfile
Labels: maintainer: open, type: enhancement, type: update

#10095 cpphs: Update
  devel/cpphs/Portfile
Labels: maintainer: none, type: enhancement, type: update

#10094 aeson-pretty: Update
  devel/aeson-pretty/Portfile
Labels: maintainer: none, type: enhancement, type: update

#10093 happy: Update
  devel/happy/Portfile
Labels: maintainer: none, type: enhancement, type: update

#10092 darcs: Update
  devel/darcs/Portfile
Labels: maintainer: open, type: enhancement, type: update

#10047 wolfSSL : update Portfile to latest version 4.7.0
  devel/wolfssl/Portfile
Labels: maintainer: requires approval, maintainer: timeout, type: security fix, type: update

#10160 hdf5-lz4-plugin: cleanup MacPorts < 2.6.0 handling
  science/hdf5-lz4-plugin/Portfile
Labels: maintainer: requires approval, maintainer: timeout

#10098 pandoc-citeproc: Update
  textproc/pandoc-citeproc/Portfile
Labels: maintainer: none, type: enhancement, type: update

#10147 pict2pdf: port abandoned
  graphics/pict2pdf/Portfile
Labels: maintainer: requires approval, maintainer: timeout

#10202 edbrowse: port abandoned
  www/edbrowse/Portfile
Labels: maintainer: requires approval

#10206 realpath: add maintainer's GitHub handle
  sysutils/realpath/Portfile
Labels: maintainer: requires approval

#10090 ihaskell: Update, use Python 38
  devel/ihaskell/Portfile
Labels: maintainer: none, type: enhancement, type: update

#10146 nodejs14: fix to allow arm64 compilation
  devel/nodejs14/Portfile
Labels: maintainer: open

#10209 bsdsfv: add maintainer's GitHub handle
  sysutils/bsdsfv/Portfile
Labels: maintainer: requires approval

#10176 lang/{rakudo,nqp,MoarVM}: Update to 2021.02(.1)
  lang/MoarVM/Portfile
  lang/nqp/Portfile
  lang/rakudo/Portfile
Labels: maintainer: open, type: update

#10174 esmf, wgrib2: cleanup MacPorts < 2.6.0 handling
  science/esmf/Portfile
  science/wgrib2/Portfile
Labels: maintainer: requires approval, maintainer: timeout

#10157 Add pngpaste @ version 0.2.3
  sysutils/pngpaste/Portfile
Labels: type: enhancement, type: submission

#10155 py-emcee3: submission
  python/py-emcee3/Portfile
Labels: type: enhancement, type: submission

#10208 gopls: update to 0.6.6
  devel/gopls/Portfile
Labels: maintainer: open, type: bugfix, type: enhancement, type: update

#10211 p5-locale-gettext: remove unused compiler_blacklist_versions portgroup
  perl/p5-locale-gettext/Portfile
Labels: maintainer: none

#10214 git-delta: add shell completions
  textproc/git-delta/Portfile
Labels: maintainer: open, type: enhancement

#10201 octave: bump to 6.2.0
  math/octave/Portfile
  math/octave/files/patch-octave6-qt4-fixes.diff
Labels: by: member, maintainer: open, type: enhancement

#10221 bat: add man and shell completions
  textproc/bat/Portfile
  textproc/bat/files/bat.bash
Labels: maintainer: open, type: enhancement

#10219 subversion-javahlbindings: remove old pre-activate
  devel/subversion-javahlbindings/Portfile
Labels: maintainer: none

#10223 py-elasticsearch: Update to version 7.11.0, add Python 39
  python/py-elasticsearch/Portfile
Labels: maintainer: none, type: enhancement, type: update

#10222 textproc/qpdf: trivial update to 10.3.1
  textproc/qpdf/Portfile
Labels: by: member, maintainer: none

#10224 fzf: update to 0.26.0
  sysutils/fzf/Portfile
Labels: maintainer, maintainer: open, type: update

#10226 py-antlr4-python3-runtime: Add Python 38 and 39
  python/py-antlr4-python3-runtime/Portfile
Labels: maintainer: none, type: enhancement

#10228 llvm-3.3, llvm-3.4, llvm-3.5, llvm-3.7: cleanup MacPorts < 2.6.0 handling
  lang/llvm-3.3/Portfile
  lang/llvm-3.4/Portfile
  lang/llvm-3.5/Portfile
  lang/llvm-3.7/Portfile
Labels: maintainer: requires approval

#10229 openrct2: update to 0.3.3
  games/openrct2/Portfile
Labels: maintainer: none, type: update

#10218 flameshot: new port
  sysutils/flameshot/Portfile
Labels: by: member, type: submission

#10212 vmdktool: fix implicit function declaration
  sysutils/vmdktool/Portfile
  sysutils/vmdktool/files/patch-expand_number.c.diff
Labels: maintainer: requires approval

#10207 flint: update to version 2.7.1
  math/flint/Portfile
Labels: maintainer: open, type: update

#10230 influxdb: update to 2.0.4
  sysutils/influxdb/Portfile
  sysutils/influxdb/files/config.toml.example
  sysutils/influxdb/files/org.macports.influxdb.plist
Labels: by: member, maintainer, maintainer: open, type: update

#10144 postgresql-jdbc: update to version 42.2.19
  java/postgresql-jdbc/Portfile
Labels: maintainer: none, type: update

#10240 git-chglog: Update to 0.11.2
  sysutils/git-chglog/Portfile
Labels: maintainer, maintainer: open, type: update

#10239 pngpaste: respect MacPorts settings
  sysutils/pngpaste/Portfile
  sysutils/pngpaste/files/patch-Makefile.diff
Labels: by: member, maintainer: open, type: enhancement

#10227 libfaiss: Update to version 1.7.0, add Python 39
  math/libfaiss/Portfile
Labels: maintainer: open, type: enhancement, type: update

#10244 mpich: add subport for Clang 11
  _resources/port1.0/group/mpi-1.0.tcl
  science/mpich/Portfile
  science/mpich/files/mpich-clang11
  science/mpich/files/mpich-clang11-fortran
Labels: by: member, maintainer: open, type: enhancement

#10215 rust-analyzer: update to 2021-03-08
  devel/rust-analyzer/Portfile
Labels: by: member, maintainer: open, type: update

#10248 macports-libcxx: new port
  lang/macports-libcxx/Portfile
  lang/macports-libcxx/files/patch-disable-availabilty.diff
Labels: by: member, type: submission

#10247 wireguard-tools: update to 1.0.20210315
  net/wireguard-tools/Portfile
Labels: maintainer, maintainer: open, type: update

#10245 py-trustme: update to 0.7.0
  python/py-service_identity/Portfile
  python/py-trustme/Portfile
Labels: by: member, maintainer: open, type: update

#10242 flameshot: transition to Qt5 portgroup
  sysutils/flameshot/Portfile
Labels: by: member, maintainer, maintainer: open

#10243 bettercap: new port
  net/bettercap/Portfile
Labels: by: member, type: submission

#10251 josm: update to 17560
  gis/JOSM/Portfile
Labels: maintainer, maintainer: open, type: enhancement, type: update

#10216 subtitleripper: add maintainer's GitHub handle, cleanup MacPorts < 2.6.0 handling
  multimedia/subtitleripper/Portfile
Labels: maintainer: requires approval

#10246 nnn: update to 3.6
  sysutils/nnn/Portfile
Labels: maintainer: open, type: enhancement, type: update

#10252 dnsviz: update to 0.9.3
  net/dnsviz/Portfile
Labels: maintainer, maintainer: open, type: update

#10264 google-cloud-sdk: update to 332.0.0
  devel/google-cloud-sdk/Portfile
Labels: maintainer, maintainer: open, type: update

#10263 kotlin: update to 1.4.31
  lang/kotlin/Portfile
Labels: maintainer, maintainer: open, type: update

#10269 clojure: update to 1.10.3.814
  lang/clojure/Portfile
Labels: maintainer, maintainer: open, type: update

#10259 py-omegaconf: Submission
  python/py-omegaconf/Portfile
Labels: type: enhancement, type: submission

#10270 py-avro: Update to 1.10.1, add Python 39
  python/py-avro/Portfile
Labels: maintainer: none, type: enhancement, type: update

#10266 py-execnet: Update to version 1.8.0, add Python 39
  python/py-execnet/Portfile
Labels: maintainer: none, type: enhancement, type: update

#10272 py-docopt: Add Python 39
  python/py-docopt/Portfile
Labels: maintainer: none, type: enhancement

#10260 py-hydra-core: Submission
  python/py-hydra-core/Portfile
Labels: type: enhancement, type: submission

#10268 py-pytest-forked: Update to version 1.3.0, add Python 39
  python/py-pytest-forked/Portfile
Labels: maintainer: none, type: enhancement, type: update

#10274 py-pydot: Update to version 1.4.2, add Python 39
  python/py-pydot/Portfile
Labels: maintainer: none, type: enhancement, type: update

#10275 dbvis: update to 12.0.4
  databases/dbvis/Portfile
Labels: maintainer, maintainer: open, type: update

#10258 py-sacrebleu: Submission
  python/py-sacrebleu/Portfile
Labels: type: submission

#10261 py-fairseq: Submission
  python/py-fairseq/Portfile
Labels: type: enhancement, type: submission

#10265 py-pytest-xdist: Update to version 2.2.1, add Python 39
  python/py-pytest-xdist/Portfile
Labels: maintainer: none, type: enhancement, type: update

#10267 py-apipkg: Add Python 39
  python/py-apipkg/Portfile
Labels: maintainer: none, type: enhancement

#10262 openjdk16, openjdk16-openj9: new subports
  java/openjdk/Portfile
Labels: maintainer, maintainer: open, type: enhancement

#10254 py-redis: Add Python 39
  python/py-redis/Portfile
Labels: maintainer: open, type: enhancement

#10273 py-hdfs: Update to version 2.6.0, add Python 39
  python/py-hdfs/Portfile
Labels: maintainer: open, type: enhancement, type: update

#10278 py-pypng: Disable livecheck on py??- subports
  python/py-pypng/Portfile
Labels: maintainer: open, type: enhancement

#10284 py-promise: Submission
  python/py-promise/Portfile
Labels: type: enhancement, type: submission

#10300 py-gin-config: Submission
  python/py-gin-config/Portfile
Labels: type: enhancement, type: submission

#10288 py-Faker: Submission
  python/py-Faker/Portfile
Labels: type: enhancement, type: submission

#10287 py-pytest-lazy-fixture: Submission
  python/py-pytest-lazy-fixture/Portfile
Labels: type: enhancement, type: submission

#10255 py-pytest-mypy: Submission
  python/py-pytest-mypy/Portfile
Labels: type: enhancement, type: submission

#10256 py-pytest-flake8: Submission
  python/py-pytest-flake8/Portfile
Labels: type: enhancement, type: submission

#10257 py-portalocker: Submission
  python/py-portalocker/Portfile
Labels: type: enhancement, type: submission

#10285 py-random2: Submission
  python/py-random2/Portfile
Labels: type: enhancement, type: submission

#10298 py-gym: Submission
  python/py-gym/Portfile
Labels: type: enhancement, type: submission

#10289 py-typeguard: Submission
  python/py-typeguard/Portfile
Labels: type: enhancement, type: submission

#10314 zabbix*: Update to 4.0.28/5.0.9
  net/zabbix4/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#10315 pam-google-authenticator: Update to 1.09
  security/pam-google-authenticator/Portfile
Labels: by: member, maintainer, maintainer: open, type: update
