Repository macports/macports-ports, pull requests merged in 2021-05, with the labels that each got.

#10862 stgit: Update to 1.1
  devel/stgit/Portfile
Labels: maintainer, maintainer: open, type: update

#10858 google-cloud-sdk: update to 338.0.0, add arm64 support
  devel/google-cloud-sdk/Portfile
Labels: maintainer, maintainer: open, type: update

#10863 nano: Update to 5.7
  editors/nano/Portfile
Labels: maintainer: open, type: update

#10859 stack: Update to version rc/v2.7.0.3
  lang/stack/Portfile
Labels: maintainer, maintainer: open, type: bugfix, type: enhancement, type: update

#10864 translate-shell: update to 0.9.6.12
  textproc/translate-shell/Portfile
Labels: maintainer: none, type: update

#10860 udunits2: Fix retroactive license
  science/udunits2/Portfile
Labels: maintainer: requires approval, type: bugfix

#10850 vf-1: bump default python version to 39
  net/vf-1/Portfile
Labels: maintainer, type: enhancement

#10849 py-python-dotenv: Update to 0.17.1
  python/py-python-dotenv/Portfile
Labels: maintainer: open, type: update

#10865 sqlmap: Update to 1.5.5
  security/sqlmap/Portfile
Labels: maintainer, maintainer: open, type: update

#10867 mingw-gcc: update to 11.1.0
  cross/i686-w64-mingw32-gcc/Portfile
  cross/x86_64-w64-mingw32-gcc/Portfile
Labels: maintainer: open, type: enhancement, type: update

#10866 libgpg-error: fix universal build on BigSur
  devel/libgpg-error/Portfile
Labels: by: member, maintainer: open

#10848 py-ukpostcodeparser: New port
  python/py-ukpostcodeparser/Portfile
Labels: type: submission

#10871 py-hcloud: New port
  python/py-hcloud/Portfile
Labels: type: submission

#10872 hcloud: New port
  devel/hcloud/Portfile
Labels: type: submission

#10847 py-Faker: Update to 8.1.2
  python/py-Faker/Portfile
Labels: maintainer: none, type: update

#10870 py-dns-lexicon: remove poetry dependency
  python/py-dns-lexicon/Portfile
  python/py-dns-lexicon/files/lexicon27
  python/py-dns-lexicon/files/lexicon36
  python/py-dns-lexicon/files/lexicon37
  python/py-dns-lexicon/files/lexicon38
  python/py-dns-lexicon/files/lexicon39
Labels: by: member, maintainer: open, type: bugfix

#10868 Update rust-src port: Standard library installation fixes.
  lang/rust/Portfile
Labels: maintainer: open, type: enhancement, type: update

#10876 tig: Update to 2.5.3
  devel/tig/Portfile
Labels: maintainer: open, type: update

#10878 webkit2-gtk: switch jpeg dependencies to libjpeg-turbo
  www/webkit2-gtk/Portfile
Labels: by: member, maintainer: requires approval, type: bugfix

#10879 mpich: ensure target compilers are added to depends_lib
  science/mpich/Portfile
Labels: maintainer: open, type: bugfix

#10832 py-ansible: Further performance tweak to patch
  python/py-ansible/Portfile
Labels: by: member, maintainer: open, type: enhancement

#10887 gdb: Update to 10.2
  devel/gdb/Portfile
Labels: maintainer: none, type: update

#10886 cloc: Update to 1.88
  textproc/cloc/Portfile
Labels: maintainer: none, type: update

#10884 yabai: update version to 3.3.8
  sysutils/yabai/Portfile
Labels: maintainer: open, type: update

#10883 ansible-lint: Update to 5.0.8
  sysutils/ansible-lint/Portfile
Labels: maintainer, maintainer: open, type: update

#10881 openjdk: add arm64 arch for openjdk*-zulu subports
  java/openjdk/Portfile
Labels: maintainer, maintainer: open, type: enhancement

#10891 py-pip: upgrade to version 21.1.1
  python/py-pip/Portfile
Labels: maintainer: open, type: bugfix

#10890 logtalk: update to 3.46.0
  lang/logtalk/Portfile
Labels: maintainer, type: update

#10892 plantuml: Update to 1.2021.5
  java/plantuml/Portfile
  java/plantuml/files/patch-add-missing-svg-folder.diff
Labels: maintainer, maintainer: open, type: update

#10852 openmpi: update to 4.1.1; add new variants heterogeneous and mpi1; enable use of published binaries for all compiler-specific subports
  science/openmpi/Portfile
Labels: maintainer, maintainer: open, type: enhancement, type: update

#10894 google-cloud-sdk: update to 339.0.0
  devel/google-cloud-sdk/Portfile
Labels: maintainer, maintainer: open, type: update

#10893 mutt: update to 2.0.7
  mail/mutt/Portfile
Labels: maintainer: requires approval, type: update

#10888 Gildas: update to 202105a
  science/gildas/Portfile
Labels: maintainer, type: enhancement, type: update

#10897 kotlin: update to 1.5.0
  lang/kotlin/Portfile
Labels: maintainer, maintainer: open, type: update

#10874 libreoffice: update to 7.1.3.2
  office/libreoffice/Portfile
Labels: maintainer, maintainer: open, type: update

#10875 retroarch: update to 1.9.2
  emulators/retroarch/Portfile
Labels: maintainer, maintainer: open, type: update

#10869 py-gevent: add zope-event and zope-interface as dependencies
  python/py-gevent/Portfile
Labels: by: member, maintainer: open

#10899 py-htmldocs: Update 39 and 38
  lang/py-htmldocs/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#10889 calendar-contacts-server: Add necessary APNS step in notes
  net/calendar-contacts-server/Portfile
Labels: maintainer, maintainer: open

#10846 py-configparser: update to 5.0.2
  python/py-configparser/Portfile
Labels: by: member, maintainer: open, type: update

#10900 openjdk: no universal_variant
  java/openjdk/Portfile
Labels: maintainer, maintainer: open, type: enhancement

#10908 micronaut: update to 2.5.1
  java/micronaut/Portfile
Labels: maintainer, maintainer: open, type: update

#10907 swig3: replace zulu-jdk8 dependency with openjdk8-zulu
  devel/swig3/Portfile
Labels: maintainer: open, type: enhancement

#10906 swig: replace zulu-jdk8 dependency with openjdk8-zulu
  devel/swig/Portfile
Labels: maintainer: open, type: enhancement

#10910 boost: force thread_local off on < 10.7
  devel/boost/Portfile
  devel/boost/files/patch-boost-libcpp-force-thread-local-off.diff
Labels: by: member, maintainer: open, type: bugfix

#10911 webkit2-gtk: fix build on newer systems
  www/webkit2-gtk/Portfile
  www/webkit2-gtk/files/patch-bool_narrowed.diff
Labels: by: member, maintainer: requires approval, type: bugfix

#10845 arping: remove duplicate binary
  net/arping/Portfile
Labels: by: member, maintainer: open, type: enhancement

#10903 py-webcolors: add py39 subport
  python/py-webcolors/Portfile
Labels: maintainer: open

#10902 py-logbook: add py39 subport
  python/py-logbook/Portfile
Labels: maintainer: open

#10904 py-pycryptodome: update to 3.10.1 and add py39 subport
  python/py-pycryptodome/Portfile
Labels: maintainer: open, type: update

#10912 kitty: Update to 0.20.3
  aqua/kitty/Portfile
  aqua/kitty/files/keyid-kitty.txt
  aqua/kitty/files/patch-kitty-no-deprecated-declarations.diff
Labels: maintainer, maintainer: open, type: update

#10914 glider: Update to 0.14.0
  net/glider/Portfile
Labels: maintainer, maintainer: open, type: update

#10905 ghidra: replace zulu-jdk11 dependency with openjdk11-zulu
  devel/ghidra/Portfile
Labels: maintainer: open, type: enhancement

#10909 pyinfra: new port
  sysutils/pyinfra/Portfile
Labels: by: member, type: submission

#10924 doctl: Update to 1.60.0
  www/doctl/Portfile
Labels: maintainer: open, type: update

#10921 s3cmd: add Python dateutil and magic dependencies
  net/s3cmd/Portfile
Labels: maintainer: none, type: bugfix

#10926 lagrange: update to 1.4.0
  net/lagrange/Portfile
Labels: maintainer, maintainer: open, type: enhancement, type: update

#10927 py-tokenizers: Update to version 0.10.2
  python/py-tokenizers/Portfile
Labels: maintainer: none, type: update

#10928 kitty: Add terminfo to prefix
  aqua/kitty/Portfile
Labels: maintainer, maintainer: open, type: enhancement

#10922 zulu-jdk: obsolete and replace by openjdk*-zulu
  java/zulu-jdk/Portfile
Labels: maintainer: none, type: enhancement

#10930 wezterm: update to 20210502-154244-3f7122cb
  aqua/wezterm/Portfile
Labels: maintainer: open, type: update

#10917 libreoffice: add upstream patch to support macOS 11.3 SDK
  office/libreoffice/Portfile
  office/libreoffice/files/patch-11.3-sdk.diff
Labels: maintainer, maintainer: open, type: bugfix

#10940 flyctl: New port
  devel/flyctl/Portfile
Labels: type: submission

#10944 flyctl: Add checksums for both architectures
  devel/flyctl/Portfile
Labels: maintainer, maintainer: open, type: bugfix

#10950 exim: update to 4.94.2
  mail/exim/Portfile
Labels: maintainer: none, type: bugfix, type: security fix, type: update

#10951 drupal7: update to 7.80
  www/drupal7/Portfile
Labels: maintainer: none, type: bugfix, type: enhancement, type: security fix, type: update

#10947 mesos: abandon maintainership
  devel/mesos/Portfile
Labels: maintainer, maintainer: open

#10936 chromedriver-78: remove obsolete port
  www/chromedriver/Portfile
Labels: maintainer: none

#10946 junit: Update to 4.13.2
  java/junit/Portfile
Labels: maintainer: none, type: update

#10953 cgal5: update to 5.2.1
  gis/cgal5/Portfile
Labels: maintainer: requires approval, type: enhancement, type: update

#10943 go-task: new port
  devel/go-task/Portfile
Labels: type: submission

#10923 dbeaver-community: Update to 21.0.4
  databases/dbeaver-community/Portfile
Labels: maintainer: open, type: update

#10964 opensc: Update to 0.21
  security/opensc/Portfile
Labels: maintainer: open, type: enhancement, type: security fix, type: update

#10958 sqlitebrowser: make qttools a build dependency
  databases/sqlitebrowser/Portfile
Labels: maintainer: open, type: enhancement

#10966 swi-prolog-devel: Updated to version 8.3.24
  lang/swi-prolog-devel/Portfile
Labels: maintainer, maintainer: open, type: update

#10965 dbeaver-community: drop maintainership
  databases/dbeaver-community/Portfile
Labels: maintainer, maintainer: open

#10941 hwloc: disable GUI variant by default
  devel/hwloc/Portfile
Labels: by: member, maintainer: open

#10961 dash: Update to 0.5.11.3
  shells/dash/Portfile
Labels: maintainer: open, type: update

#10967 ccache: update to 4.3
  devel/ccache/Portfile
Labels: maintainer: open, type: update

#10973 taskwarrior-tui: Update to 0.13.21 and add man
  office/taskwarrior-tui/Portfile
Labels: maintainer: open, type: enhancement, type: update

#10896 igraph: update to 0.9.3
  math/igraph/Portfile
Labels: maintainer, maintainer: open, type: update

#10975 borgbackup: Add fish completion
  sysutils/borgbackup/Portfile
Labels: maintainer: none, type: enhancement

#10976 py-Faker: Update to 8.1.3
  python/py-Faker/Portfile
Labels: maintainer, maintainer: open, type: update

#10970 topgrade: update to 6.9.0
  sysutils/topgrade/Portfile
Labels: maintainer, maintainer: open, type: update

#10931 graalvm: remove obsolete port
  java/graalvm/Portfile
Labels: maintainer: none, type: enhancement

#10983 bitwarden-cli: update to 1.16.0
  security/bitwarden-cli/Portfile
Labels: maintainer, maintainer: open, type: update

#10986 hugo: update to 0.83.1
  www/hugo/Portfile
Labels: maintainer, maintainer: open, type: update

#10933 libsndfile: update to 1.0.31
  audio/libsndfile/Portfile
  audio/libsndfile/files/patch-CMakeLists.txt.diff
  audio/libsndfile/files/patch-Wvla.diff
  audio/libsndfile/files/patch-sndfile-play.diff
Labels: maintainer: none, type: enhancement, type: update

#10937 stack: Update to release version 2.7.1
  lang/stack/Portfile
Labels: maintainer, maintainer: open, type: update

#10957 mpg123: update to 1.27.2
  audio/mpg123/Portfile
Labels: maintainer: none, type: update

#10952 vulture: update to 2.3
  devel/vulture/Portfile
Labels: by: member, maintainer: open, type: update

#10942 pngquant: update to 2.15.0
  graphics/pngquant/Portfile
Labels: maintainer: none, type: update

#10960 pmd: Update to 6.34.0
  java/pmd/Portfile
Labels: maintainer: none, type: update

#10945 grails: Update to 4.0.10
  devel/grails/Portfile
Labels: maintainer: none, type: update

#10968 gexiv2: use Python 3.9 by default
  gnome/gexiv2/Portfile
Labels: by: member, maintainer: open

#10969 inkscape: use Python 3.9 by default
  graphics/inkscape/Portfile
Labels: by: member, maintainer: open

#10971 fontforge: add +python39 variant, make default
  graphics/fontforge/Portfile
Labels: by: member, maintainer: none

#10979 openjdk*-zulu: fix typo in error message
  java/openjdk/Portfile
Labels: maintainer: open, type: bugfix

#10980 oha: New port
  net/oha/Portfile
Labels: type: submission

#10919 sse2neon: new port
  devel/sse2neon/Portfile
Labels: type: submission

#10920 SIMDe: new port
  devel/simde/Portfile
Labels: type: submission

#10988 skaffold: update to 1.24.0
  devel/skaffold/Portfile
Labels: maintainer, maintainer: open, type: update

#10990 py-xdg: Update to 0.27
  python/py-xdg/Portfile
Labels: maintainer: open, type: update

#10994 py-htmldocs: 3.8.10 and 3.9.5
  lang/py-htmldocs/Portfile
Labels: by: member, maintainer, maintainer: open

#10993 mpich: Include gcc11 cases as needed.
  _resources/port1.0/group/compilers-1.0.tcl
  science/mpich/Portfile
Labels: by: member, maintainer, maintainer: open

#10959 libwebsockets: Update to 4.2.0
  devel/libwebsockets/Portfile
Labels: maintainer: open, type: update

#10987 matterhorn: new port, version 50200.12.0
  net/matterhorn/Portfile
Labels: type: submission

#10991 adblock2privoxy: Update to version 2.0.2
  www/adblock2privoxy/Portfile
Labels: maintainer, type: update

#10997 dart-sass: update to 1.32.13
  www/dart-sass/Portfile
Labels: maintainer, maintainer: open, type: update

#10998 syncthing: update to 1.16.1
  net/syncthing/Portfile
Labels: maintainer: open, type: bugfix, type: enhancement, type: update

#11001 micronaut: update to 2.5.3
  java/micronaut/Portfile
Labels: maintainer, maintainer: open, type: update

#11000 singular: update to 4.2.0p2
  math/singular/Portfile
Labels: maintainer: none, type: update

#11002 py-django: update to 2.2.23
  python/py-django/Portfile
Labels: maintainer: open, type: security fix, type: update

#11004 py-Faker: Update to 8.1.4
  python/py-Faker/Portfile
Labels: maintainer, maintainer: open, type: update

#11003 clojure: update to 1.10.3.839
  lang/clojure/Portfile
Labels: maintainer, maintainer: open, type: update

#10989 qDMR: new port
  science/qdmr/Portfile
  science/qdmr/files/patch-ambiguous-abs-fix.diff
Labels: type: enhancement, type: submission

#10999 ntl: update to 11.4.4
  math/ntl/Portfile
Labels: maintainer: open, type: update

#11007 dns-server: fix typos in long_description, notes
  net/dns-server/Portfile
Labels: maintainer: open, type: bugfix

#10901 olm: update to 3.2.2 and add py-olm subport
  devel/olm/Portfile
Labels: maintainer: open, type: update

#10984 carthage: update to 0.38.0
  devel/carthage/Portfile
Labels: maintainer: open, type: update

#11009 jdupes: update to 1.20.0
  sysutils/jdupes/Portfile
Labels: maintainer, maintainer: open, type: update

#11010 plantuml: Update to 1.2021.6
  java/plantuml/Portfile
  java/plantuml/files/patch-add-missing-svg-folder.diff
Labels: maintainer, maintainer: open, type: update

#11008 syncthing-macos: update to 1.16.1-2
  net/syncthing-macos/Portfile
  net/syncthing-macos/files/patch-disable-autoupdatechecks.diff
  net/syncthing-macos/files/patch-no-bundled-syncthing.diff
Labels: maintainer: open, type: enhancement, type: update

#11011 haproxy: Update to 2.4.0
  net/haproxy/Portfile
Labels: maintainer: open, type: update

#11013 ismrmrd: 1.5.0
  science/ismrmrd/Portfile
  science/ismrmrd/files/utilities_ismrmrd_phandom.cpp.patch
Labels: by: member, maintainer, maintainer: open

#11015 ismrmrd: Add tests.
  science/ismrmrd/Portfile
Labels: by: member, maintainer, maintainer: open

#11012 Gradle: Update to 7.0.2
  devel/gradle/Portfile
Labels: maintainer: open, type: update

#11016 minio: Update to latest and license change
  www/minio-mc/Portfile
  www/minio/Portfile
Labels: by: member, maintainer, maintainer: open, type: update

#10882 git: credential_osxkeychain: create global gitconfig
  devel/git/Portfile
Labels: maintainer: open

#10885 SourceKitten: Update to 0.31.0
  devel/SourceKitten/Portfile
Labels: maintainer: none, type: update

#10880 AutoRaise: update to 2.1.0
  sysutils/AutoRaise/Portfile
Labels: maintainer, maintainer: open, type: update

#11017 SIMDe: fix build failures on 10.12/10.13
  devel/simde/Portfile
Labels: maintainer, maintainer: open, type: bugfix

#11020 arduino-cli: Update to 0.18.3
  devel/arduino-cli/Portfile
Labels: maintainer, maintainer: open, type: update

#11019 detekt-cli: Update to 1.17.0
  java/detekt-cli/Portfile
Labels: maintainer, maintainer: open, type: update

#11018 zstd: update to 1.5.0
  archivers/zstd/Portfile
Labels: maintainer: none, type: update

#11021 doctl: Update 1.61.0
  www/doctl/Portfile
Labels: maintainer: open, type: update

#11022 google-glog: Update to 0.5.0
  devel/google-glog/Portfile
  devel/google-glog/files/patch-fix-api-break.diff
Labels: maintainer: none, type: update

#10985 exim: attempt to fix build on 10.11 and earlier
  mail/exim/Portfile
Labels: maintainer: none

#11027 git: close file handle after writing
  devel/git/Portfile
Labels: maintainer: open

#10954 saml2aws: New port
  security/saml2aws/Portfile
Labels: type: submission

#11032 abseil: Update to 20210324.1
  devel/abseil/Portfile
Labels: maintainer: none, type: update

#11034 saml2aws: Fix gls dependency
  security/saml2aws/Portfile
Labels: maintainer, maintainer: open, type: bugfix

#11037 rxvt-unicode: update to 9.26
  x11/rxvt-unicode/Portfile
  x11/rxvt-unicode/files/CVE-2017-7483.patch
  x11/rxvt-unicode/files/patch-perl-5.28-compat.diff
Labels: maintainer, maintainer: open, type: update

#11038 yadm: Update to 3.1.0
  sysutils/yadm/Portfile
Labels: maintainer: open, type: update

#11023 lua-lpeg: update to 1.0.2
  devel/lua-lpeg/Portfile
  devel/lua-lpeg/files/patch-makefile.diff
Labels: by: member, maintainer: open, type: update

#11048 py-eyed3: update to version 0.9.6
  python/py-eyed3/Portfile
Labels: maintainer: none, type: update

#11042 py-absl: Update to version 0.12.0
  python/py-absl/Portfile
Labels: maintainer: open, type: update

#11045 py-tensorflow-datasets: Update to version 4.3.0
  python/py-tensorflow-datasets/Portfile
Labels: maintainer: none, type: update

#11046 dbeaver-community: Update to 21.0.5
  databases/dbeaver-community/Portfile
Labels: maintainer, maintainer: open, type: update

#11051 openjdk: add openjdk7-zulu subport
  java/openjdk/Portfile
Labels: maintainer, maintainer: open, type: enhancement
