Repository macports/macports-ports, pull requests merged in 2022-01, with the labels that each got.

#13513 py-kivy: delete py35 subport
  python/py-kivy/Portfile
Labels: maintainer: open, by: member

#13546 checkssl: update to 0.3
  sysutils/checkssl/Portfile
Labels: type: update, maintainer, maintainer: open

#13545 mysql8: avoid using OpenSSL 3 headers
  databases/mysql8/Portfile
  databases/mysql8/patch-cmake-ssl-include.diff
Labels: maintainer: open

#13533 meson: update Tiger to 0.58.2
  devel/meson/Portfile
  devel/meson/files/patch-meson57-tiger-no-rpath-fix.diff
Labels: type: update, maintainer: open

#13547 dfu-util: update to 0.11
  cross/dfu-util/Portfile
Labels: type: bugfix, type: update, maintainer: open

#13552 checkssl: update to 0.3.1
  sysutils/checkssl/Portfile
Labels: type: update, maintainer, maintainer: open

#13553 libnumbertext: update to 1.0.8
  devel/libnumbertext/Portfile
Labels: type: update, maintainer, maintainer: open

#13554 tanka: Update to version 0.19.0
  sysutils/tanka/Portfile
Labels: type: update, maintainer, maintainer: open

#13549 go-task: Update to version 3.9.2
  devel/go-task/Portfile
Labels: type: update, maintainer, maintainer: open

#13548 go-jsonnet: Update to v0.18.0
  devel/go-jsonnet/Portfile
Labels: type: update, maintainer, maintainer: open

#13511 nmap, wireshark22: add maintainer GitHub handle
  net/nmap/Portfile
  net/wireshark22/Portfile
Labels: maintainer: requires approval, maintainer: timeout

#13555 quassel: update to 0.14.0
  irc/quassel/Portfile
  irc/quassel/files/patch-no-dmg.diff
  irc/quassel/files/patch-src_common_types.h
Labels: type: update, maintainer: none

#13425 mod_tile: Handle conflict with boost port
  gis/mod_tile/Portfile
Labels: type: bugfix, maintainer, maintainer: open

#13557 cflow: update to 1.7
  devel/cflow/Portfile
Labels: type: bugfix, type: enhancement, type: update, type: security fix, maintainer: none

#13512 go-tools: update to 0.1.8
  devel/go-tools/Portfile
Labels: type: update, maintainer: open, by: member

#13556 jreleaser: cleanup
  devel/jreleaser/Portfile
Labels: maintainer: requires approval, by: member

#13558 py-execnet: update to 1.9.0
  python/py-execnet/Portfile
Labels: type: enhancement, type: update, maintainer: none

#13520 fpc: Fix arm64 port
  lang/fpc/Portfile
  lang/fpc/files/fpc.cfg.patch
Labels: type: bugfix, type: enhancement, maintainer, maintainer: open

#13315 quassel: add urlpreview variant
  irc/quassel/Portfile
Labels: type: bugfix, type: enhancement, maintainer: none

#12663 deark: new port (version 1.5.9)
  archivers/deark/Portfile
  archivers/deark/files/patch-Makefile.diff
Labels: type: submission

#13561 py-crcmod: Add py310-crcmod
  python/py-crcmod/Portfile
Labels: type: enhancement, maintainer: none

#13540 2048.cpp: update to 2021-10-14
  games/2048.cpp/Portfile
Labels: type: update, maintainer: open, by: member

#13566 chromedriver: update to 96.0.4664.45
  www/chromedriver/Portfile
Labels: type: enhancement, type: update, maintainer: none

#13565 dosbox-x: update to 0.83.21
  emulators/dosbox-x/Portfile
Labels: type: update, maintainer: none

#13559 Gildas: update to 202201a
  science/gildas/Portfile
  science/gildas/files/patch-admin-Makefile.python.diff
  science/gildas/files/patch-admin-gildas-env.sh.diff
Labels: type: enhancement, type: update, maintainer

#13567 micronaut: update to 3.2.4
  java/micronaut/Portfile
Labels: type: update, maintainer, maintainer: open

#13569 git: use updated gettext dependencies
  devel/git/Portfile
Labels: maintainer, maintainer: open, by: member

#13277 wolfssl: update maintainers list in Portfile to have JacobBarthelmeh
  devel/wolfssl/Portfile
Labels: type: enhancement, type: update, maintainer: requires approval, maintainer: timeout

#13571 zabbix4/5: 4.0.37/5.0.19; remote 42 and 44
  net/zabbix4/Portfile
Labels: maintainer, maintainer: open, by: member

#13572 zabbix42/44: Finish removing.
  net/zabbix4/Portfile
Labels: maintainer, maintainer: open, by: member

#13573 helix: update to 0.6.0
  editors/helix/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#13575 wolfssl: update to version 5.1.1
  devel/wolfssl/Portfile
Labels: type: update, maintainer, type: security fix, maintainer: open

#13587 clojure: update to 1.10.3.1058
  lang/clojure/Portfile
Labels: type: update, maintainer, maintainer: open

#13407 synkron: new port
  sysutils/synkron/Portfile
  sysutils/synkron/files/patch-add_missing_translations.diff
Labels: type: submission

#13586 nvm: update to 0.39.1
  devel/nvm/Portfile
Labels: type: update, maintainer: open, by: member

#13591 lagrange: update to 1.9.5
  net/lagrange/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#13578 fortune-mod: update to 3.12.0
  games/fortune-mod/Portfile
  games/fortune-mod/files/patch-cmake.diff
  games/fortune-mod/files/patch-fortune-mod-common.diff
Labels: type: update, maintainer, maintainer: open

#13592 py35-whoosh: remove obsolete subport
  python/py-whoosh/Portfile
Labels: maintainer: none

#13595 py-pynetdicom 2.0.1; 3.x only now
  python/py-pynetdicom/Portfile
Labels: maintainer, maintainer: open, by: member

#13598 py-pydicom: Add 3.10
  python/py-pydicom/Portfile
Labels: maintainer, maintainer: open, by: member

#13594 topgrade: update to 8.1.2
  sysutils/topgrade/Portfile
Labels: type: update, maintainer, maintainer: open

#13480 python27: fix support for virtualenv on macOS 12
  lang/python27/Portfile
  lang/python27/files/patch-getpath.diff
Labels: type: bugfix, maintainer: open

#13588 mailutils: update to 3.14
  mail/mailutils/Portfile
Labels: type: bugfix, type: enhancement, type: update, type: security fix, maintainer: none

#13596 dbvis: update to 12.1.5
  databases/dbvis/Portfile
Labels: type: update, maintainer, maintainer: open

#13602 ruby-build: update to version 20211227
  ruby/ruby-build/Portfile
Labels: type: update, maintainer: open

#13603 git: perl5.branches: add 5.34
  devel/git/Portfile
Labels: type: enhancement, maintainer: open, by: member

#13599 bwping: update to 2.4
  net/bwping/Portfile
Labels: type: update, maintainer, maintainer: open

#13601 http-prompt: Update twine dependency
  net/http-prompt/Portfile
Labels: type: update, maintainer: requires approval, by: member

#13604 bwping: fix build on 10.7
  net/bwping/Portfile
Labels: type: bugfix, maintainer, maintainer: open

#13606 gitqlient: new port
  devel/gitqlient/Portfile
Labels: type: enhancement, type: submission, by: member

#13607 zk: New port
  office/zk/Portfile
Labels: type: submission, by: member

#13584 bash: update to 5.1.16
  shells/bash/Portfile
Labels: type: bugfix, type: update, maintainer: requires approval

#13459 squish: add pkg-config file
  graphics/squish/Portfile
  graphics/squish/files/add-pkgconfig-file.diff
Labels: type: enhancement, maintainer: requires approval, maintainer: timeout

#13597 afscompress: update to 1.7.2
  sysutils/afscompress/Portfile
Labels: type: update, maintainer: open

#13579 qvge: new port
  graphics/qvge/Portfile
  graphics/qvge/files/patch-mac-icon.diff
Labels: type: enhancement, type: submission

#13612 josm: update to 18360
  gis/JOSM/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#13610 fontforge: update to 20201107
  graphics/fontforge/Portfile
  graphics/fontforge/files/patch-fontforge-startui-SRefCon-tiger.diff
  graphics/fontforge/files/patch-fontforge-startui-require-noerr.diff
Labels: type: update, maintainer: none

#13609 swi-prolog-devel: Updated to version 8.5.5
  lang/swi-prolog-devel/Portfile
Labels: type: update, maintainer, maintainer: open

#13615 py-igraph: update to 0.9.9
  python/py-igraph/Portfile
Labels: type: update, maintainer, maintainer: open

#13617 py-{boto3,rasa-nlu}: Remove Python 3.6
  python/py-boto3/Portfile
  python/py-rasa-nlu/Portfile
Labels: maintainer, maintainer: open, by: member

#13616 lazarus: update to upstream version 2.2.0
  devel/lazarus/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#13509 parallel: update to 20211222
  sysutils/parallel/Portfile
Labels: type: update, maintainer: requires approval, maintainer: timeout, by: member

#13582 netperf: Fix implicit func decls and wrong code
  net/netperf/Portfile
  net/netperf/files/implicit.patch
  net/netperf/files/mach.patch
Labels: maintainer: open, by: member

#13574 p5-mediawiki-api: new port
  perl/p5-mediawiki-api/Portfile
Labels: type: submission

#13516 discord-rpc: new port
  games/discord-rpc/Portfile
  games/discord-rpc/files/DiscordRPCConfig.cmake
  games/discord-rpc/files/FindDiscordRPC.cmake.in
  games/discord-rpc/files/add-package-locator-files.diff
  games/discord-rpc/files/create-both-lib-types.diff
  games/discord-rpc/files/discord-rpc.pc.in
Labels: type: submission

#13473 warzone2100: new port
  games/warzone2100/Portfile
Labels: type: submission

#13521 zig: update to 0.9.0
  lang/zig/Portfile
Labels: type: enhancement, type: update, maintainer: open

#13510 apache-geode: port abandoned
  databases/apache-geode/Portfile
Labels: maintainer: requires approval, maintainer: timeout

#13550 qgis: obsolete port
  gis/qgis/Portfile
  gis/qgis/files/patch-PyQtMacros.diff
  gis/qgis/files/patch-app_info_plist_in.diff
  gis/qgis/files/patch-python_core_conversions_sip.diff
Labels: maintainer: requires approval, maintainer: timeout, by: member

#13494 btrfs-progs: delete abandoned port
  sysutils/btrfs-progs/Portfile
  sysutils/btrfs-progs/files/patch-btrfs-image.c.diff
  sysutils/btrfs-progs/files/patch-btrfsck.c.diff
  sysutils/btrfs-progs/files/patch-disk-io.c.diff
  sysutils/btrfs-progs/files/patch-extent-tree.c.diff
  sysutils/btrfs-progs/files/patch-file-item.c.diff
  sysutils/btrfs-progs/files/patch-ioctl.h.diff
  sysutils/btrfs-progs/files/patch-kerncompat.h.diff
  sysutils/btrfs-progs/files/patch-list.h.diff
  sysutils/btrfs-progs/files/patch-mkfs.c.diff
  sysutils/btrfs-progs/files/patch-utils.c.diff
  sysutils/btrfs-progs/files/patch-volumes.c.diff
Labels: maintainer: requires approval, maintainer: timeout

#13627 git-town port
  devel/git-town/Portfile
Labels: type: submission

#13625 universal-ctags: update to 5.9.20220109.0
  devel/universal-ctags/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#13624 py-soco: update to 0.25.3
  python/py-soco/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#13623 py-jellyfish: update to 0.9.0
  python/py-jellyfish/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#13622 py-country: update to 22.1.10
  python/py-country/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#13626 retdec-devel: update to 20220104
  devel/retdec/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#13620 chromedriver: update to 97.0.4692.71
  www/chromedriver/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#13614 gn-devel: build tests only during test phase
  devel/gn-devel/Portfile
Labels: maintainer: none

#13621 beets-devel: update to 20220108
  audio/beets/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#13560 cdrtools: fix arm64 build by explicitly disabling stack scanning
  sysutils/cdrtools/Portfile
Labels: type: bugfix, maintainer: none

#13581 proj8: add test target
  gis/proj8/Portfile
Labels: type: enhancement, maintainer: open

#13605 py-django: update to 2.2.26
  python/py-django/Portfile
Labels: type: bugfix, type: update, type: security fix, maintainer: open

#13589 qbs: Update to 1.21.0
  devel/qbs/Portfile
Labels: type: update, maintainer: open

#13593 openjdk10: remove obsolete subport
  java/openjdk/Portfile
Labels: maintainer: open

#13637 google-cloud-sdk: update to 368.0.0
  devel/google-cloud-sdk/Portfile
Labels: type: update, maintainer, maintainer: open

#13428 redeclipse: new port
  games/redeclipse/Portfile
Labels: type: submission

#13641 warzone2100: add license_noconflict
  games/warzone2100/Portfile
Labels: type: bugfix, maintainer

#13646 lima: update to 0.8.1
  sysutils/lima/Portfile
Labels: type: update, maintainer: none

#13644 redeclipse, warzone2100: add supported_archs noarch to game data subports
  games/redeclipse/Portfile
  games/warzone2100/Portfile
Labels: type: enhancement, maintainer

#13580 graphene: fix build on 10.4/10.5
  graphics/graphene/Portfile
  graphics/graphene/files/patch-graphene-leopard.diff
  graphics/graphene/files/patch-src-bench-matrix.diff
Labels: type: bugfix, maintainer: open

#13647 brunsli: require C++11 compiler
  archivers/brunsli/Portfile
Labels: type: bugfix, maintainer: open

#13648 warzone2100: update to 4.2.4
  games/warzone2100/Portfile
Labels: type: update, maintainer

#13654 whitebox-tools: update to 2.0.0
  gis/whitebox-tools/Portfile
  gis/whitebox-tools/files/patch-Cargo.lock.diff
Labels: type: enhancement, type: update, maintainer: open

#13420 font-spleen: new port
  x11/font-spleen/Portfile
Labels: type: enhancement, type: submission

#13631 cdo: update to 2.0.3
  science/cdo/Portfile
Labels: type: update, maintainer: open

#13630 netcdf-fortran: update to 4.5.4
  science/netcdf-fortran/Portfile
Labels: type: update, maintainer: open

#13649 boost178: new port
  devel/boost178/Portfile
  devel/boost178/files/patch-apple-clang-no-libcxx.diff
  devel/boost178/files/patch-b2-build-older-OSes.diff
  devel/boost178/files/patch-boost-libcpp-force-thread-local-off.diff
  devel/boost178/files/patch-boost-python3.diff
  devel/boost178/files/patch-compiler.diff
  devel/boost178/files/patch-disable-numpy-extension.diff
  devel/boost178/files/patch-export_serialization_explicit_template_instantiations.diff
  devel/boost178/files/patch-libs-mpi-build-Jamfile.v2.diff
  devel/boost178/files/patch-revert-lib-name-tagged.diff
  devel/boost178/files/patch-tiger-availability.diff
  devel/boost178/files/patch-tools-build-src-tools-python-2.jam.diff
  devel/boost178/files/patch-tools-build-src-tools-python.jam.diff
Labels: type: enhancement, type: submission, by: member

#13657 Bump to version 0.34.3
  mail/notmuch/Portfile
Labels: maintainer, maintainer: open

#13655 proxmark3-iceman: errata, fix destroot option in variant
  science/proxmark3-iceman/Portfile
Labels: type: bugfix, maintainer, maintainer: open

#13600 armagetronad: new port
  games/armagetronad/Portfile
Labels: type: submission

#13653 redeclipse: fix licenses
  games/redeclipse/Portfile
Labels: type: bugfix, type: enhancement, maintainer

#13663 hugo: update to 0.92.0
  www/hugo/Portfile
Labels: type: update, maintainer, maintainer: open

#13664 warzone2100: fix incorrect license_noconflict
  games/warzone2100/Portfile
Labels: type: bugfix, maintainer

#13660 armagetronad: Use the right extract commands
  games/armagetronad/Portfile
Labels: maintainer: open, by: member

#13667 gopass: update to 1.13.1
  security/gopass/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#13672 unison: update to 2.51.5
  net/unison/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer: none

#13577 sysbench: new port
  benchmarks/sysbench/Portfile
Labels: type: submission

#13671 *-w64-mingw32-gcc: Add dependency zstd
  cross/i686-w64-mingw32-gcc/Portfile
  cross/x86_64-w64-mingw32-gcc/Portfile
Labels: type: bugfix, maintainer: open

#13678 micronaut: update to 3.2.6
  java/micronaut/Portfile
Labels: type: update, maintainer, maintainer: open

#13677 ki-shell: update to 0.4.1
  java/ki-shell/Portfile
Labels: type: update, maintainer, maintainer: open

#13679 skaffold: update to 1.35.2
  devel/skaffold/Portfile
Labels: type: update, maintainer, maintainer: open

#13670 poetry: relax dependency requirements
  python/poetry/Portfile
  python/poetry/files/patch-requirements.diff
Labels: type: bugfix, maintainer, maintainer: open

#13544 zthread: new port
  devel/zthread/Portfile
  devel/zthread/files/dynamic_lookup-11.patch
Labels: type: submission

#13642 hello: update to 2.11
  mail/hello/Portfile
Labels: type: update, maintainer: none

#13682 memtester: update to newer upstream version 4.5.1
  sysutils/memtester/Portfile
Labels: type: enhancement, type: update, maintainer: none

#13688 fontforge: Add +python310 variant, make default
  graphics/fontforge/Portfile
Labels: type: enhancement, maintainer: none, by: member

#13689 lagrange: update to 1.10.0
  net/lagrange/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#13685 libreoffice: update to 7.3.0.2
  office/libreoffice/Portfile
Labels: type: update, maintainer, maintainer: open

#13696 wireguard-go: update to 0.0.20220117
  net/wireguard-go/Portfile
Labels: type: update, maintainer, maintainer: open

#13692 submission: Add new port gzdice (version 0.1.2)
  python/gzdice/Portfile
Labels: type: submission

#13551 mrustc: new port
  lang/mrustc/Portfile
  lang/mrustc/files/patch-mrustc-macos-bootstrap.diff
  lang/mrustc/files/patch-mrustc-macports-compiler.diff
  lang/mrustc/files/patch-mrustc-macports-libdir.diff
  lang/mrustc/files/patch-mrustc-macports-version.diff
Labels: type: submission

#13698 crystal: update to 1.3.1
  lang/crystal/Portfile
  lang/crystal/files/patch-crypto.diff
  lang/crystal/files/patch-link.diff
  lang/crystal/files/patch-ssl.diff
  lang/crystal/files/patch-static.diff
Labels: type: update, maintainer, maintainer: open

#13695 aerc: update to 0.7.1
  mail/aerc/Portfile
Labels: type: enhancement, type: update, maintainer: none

#13628 emacs-{,-app}-devel: update to 2022-01-11
  editors/emacs/Portfile
Labels: type: enhancement, type: update, maintainer: open

#13529 p5-extutils-makemaker: fix Makefile generation on Tiger
  perl/p5-extutils-makemaker/Portfile
  perl/p5-extutils-makemaker/files/patch-extutils-makemaker-rpath.diff
Labels: type: bugfix, maintainer: none

#13700 ki-shell: update to 0.4.3
  java/ki-shell/Portfile
Labels: type: update, maintainer, maintainer: open

#13650 py-scipy: add mkl variant
  python/py-scipy/Portfile
Labels: type: enhancement, maintainer: open, by: member

#13674 py-requests: update to 2.27.1
  python/py-requests/Portfile
Labels: type: update, maintainer: open, by: member

#13673 py-importlib-metadata: Update to 4.10.0
  python/py-importlib-metadata/Portfile
Labels: type: enhancement, type: update, maintainer: open, by: member

#13662 geckodriver: Update to version 0.30.0
  www/geckodriver/Portfile
Labels: type: update, maintainer: open

#13706 sfeed: new port
  net/sfeed/Portfile
Labels: type: enhancement, type: submission

#13702 openjdk: add subport openjdk17-openj9
  java/openjdk/Portfile
Labels: type: enhancement, maintainer, maintainer: open

#13703 armagetronad: fix error "use of undeclared identifier 'finite'" on arm64
  games/armagetronad/Portfile
Labels: type: bugfix, maintainer, maintainer: open

#13707 micronaut: update to 3.2.7
  java/micronaut/Portfile
Labels: type: update, maintainer, maintainer: open

#13710 onefetch: Update to 2.11.0 and remove platforms
  devel/onefetch/Portfile
Labels: type: update, maintainer: open, by: member

#13711 google-cloud-sdk: update to 369.0.0
  devel/google-cloud-sdk/Portfile
Labels: type: update, maintainer, maintainer: open

#13708 py-terminaltables: update to 3.1.10
  python/py-terminaltables/Portfile
Labels: type: enhancement, type: update, maintainer: open, by: member

#13718 logtalk: update to 3.53.0
  lang/logtalk/Portfile
Labels: type: update, maintainer

#13719 crystal: update to 1.3.2
  lang/crystal/Portfile
Labels: type: update, maintainer, maintainer: open

#13721 talloc: clean up separate revision for macOS 11
  devel/talloc/Portfile
Labels: maintainer: none

#13720 abcde: switch to Perl 5.34
  audio/abcde/Portfile
Labels: maintainer, maintainer: open

#13722 lighttpd: update to lighttpd-1.4.64
  www/lighttpd/Portfile
  www/lighttpd/files/gcc-diag.patch
  www/lighttpd/files/implicit.patch
  www/lighttpd/files/patch-conf.diff
Labels: type: bugfix, type: enhancement, type: update, type: security fix, maintainer: open

#13724 phpmyadmin: add php81 variant
  www/phpmyadmin/Portfile
Labels: maintainer: open

#13725 ocrad: update to 0.28
  graphics/ocrad/Portfile
Labels: type: bugfix, type: enhancement, type: update, type: security fix, maintainer: none

#13715 imlib2: fix PPC build
  graphics/imlib2/Portfile
  graphics/imlib2/files/patch-imlib2-bigendian.diff
Labels: type: bugfix, maintainer: none

#13737 ki-shell: update to 0.4.4
  java/ki-shell/Portfile
Labels: type: update, maintainer, maintainer: open

#13736 py-argcomplete: update to 2.0.0
  python/py-argcomplete/Portfile
Labels: type: update, maintainer, maintainer: open

#13734 chromedriver: fixed livecheck
  www/chromedriver/Portfile
Labels: maintainer, maintainer: open

#13732 universal-ctags: update to 5.9.20220116.0
  devel/universal-ctags/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#13730 py-pytest-timeout: update to 2.1.0
  python/py-pytest-timeout/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open
