Repository macports/macports-ports, pull requests merged in 2022-08, with the labels that each got.

#15515 emacs{,-app}-devel: update to 20220728
  editors/emacs/Portfile
Labels: type: update, maintainer: open, by: member

#15528 btor2tools: update to 20220518
  math/btor2tools/Portfile
Labels: type: enhancement, type: update, maintainer: none

#15541 lilypond-devel: upgrade to 2.23.11
  textproc/lilypond/Portfile
  textproc/lilypond/files/patch-add-flex-to-include-devel.diff
Labels: type: enhancement, maintainer: open

#15554 redis: update to 7.0.4
  databases/redis/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#15546 wireshark3: update to 3.6.7
  net/wireshark3/Portfile
Labels: type: update, maintainer: requires approval, by: member

#15553 inih: submission
  devel/inih/Portfile
Labels: type: submission

#15557 llvm/clang/flang/mlir/lldb-devel: update and repair broken build
  lang/llvm-devel/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer: open, by: member

#15561 go: update to 1.18.5
  lang/go/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#15562 go: update to 1.17.13 (macOS 10.12 and older)
  lang/go/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#14631 clang-11-bootstrap: new port
  lang/clang-11-bootstrap/Portfile
  lang/clang-11-bootstrap/files/0002-Define-EXC_MASK_CRASH-and-MACH_EXCEPTION_CODES-if-th.patch
  lang/clang-11-bootstrap/files/0003-MacPorts-Only-Don-t-embed-the-deployment-target-in-t.patch
  lang/clang-11-bootstrap/files/0004-Fix-build-issues-pre-Lion-due-to-missing-a-strnlen-d.patch
  lang/clang-11-bootstrap/files/0005-Threading-Only-call-pthread_setname_np-on-SnowLeopar.patch
  lang/clang-11-bootstrap/files/0006-Only-call-setpriority-PRIO_DARWIN_THREAD-0-PRIO_DARW.patch
  lang/clang-11-bootstrap/files/0007-patch-llvm8-tools-dsymutil-symbolmap-use-older-cfname-and-fix-uuid-on-leopard.diff
  lang/clang-11-bootstrap/files/0008-patch-lib-support-unix-path-copyfileclone-on-older-systems.diff
  lang/clang-11-bootstrap/files/1002-MacPorts-Only-Fix-name-of-scan-view-executable-insid.patch
  lang/clang-11-bootstrap/files/1004-Default-to-fragile-ObjC-runtime-when-targeting-darwi.patch
  lang/clang-11-bootstrap/files/1005-Fixup-libstdc-header-search-paths-for-older-versions.patch
  lang/clang-11-bootstrap/files/1006-Fix-build-issues-pre-Lion-due-to-missing-a-strnlen-d.patch
  lang/clang-11-bootstrap/files/1007-Fix-float.h-to-work-on-Snow-Leopard-and-earlier.patch
  lang/clang-11-bootstrap/files/1008-compilerrt-fuzzer-missingdefs.diff
  lang/clang-11-bootstrap/files/1009-compilerrt-sanitizer-missingdefs.diff
  lang/clang-11-bootstrap/files/2002-Work-around-no-libdispatch-on-10.6.patch
  lang/clang-11-bootstrap/files/3001-Fix-missing-long-long-math-prototypes-when-using-the.patch
  lang/clang-11-bootstrap/files/3002-implement-atomic-using-mutex-lock_guard-for-64b-ops-.patch
  lang/clang-11-bootstrap/files/3003-patch-libcxx-chrono-restore-steadyclock-fallback.diff
  lang/clang-11-bootstrap/files/5000-patch-compilerrtdarwinutils-find-macosxsdkversion.diff
  lang/clang-11-bootstrap/files/5002-patch-toolchains-darwin-add-back-pre-10.6-link-libs.diff
  lang/clang-11-bootstrap/files/5004-patch-libcxx-reexport-symbols-lionorgreater-only.diff
  lang/clang-11-bootstrap/files/5005-MacPorts-only-patch-libcxx-includes-disable-availability-tests.diff
  lang/clang-11-bootstrap/files/9000-patch-clang-7.0-support-emulated-tls.diff
  lang/clang-11-bootstrap/files/9000-patch-llvm-7.0-support-emulated-tls.diff
  lang/clang-11-bootstrap/files/9001-macports-libstdcxx.diff
  lang/clang-11-bootstrap/files/9003-patch-clang-7.0-default-to-libcxx-on-all-systems.diff
  lang/clang-11-bootstrap/files/Fix-build-issues-pre-Lion-due-to-missing-a-strnlen.patch
  lang/clang-11-bootstrap/files/fix-build-clang-by-gcc10.diff
  lang/clang-11-bootstrap/files/leopard-no-asan.patch
  lang/clang-11-bootstrap/files/leopard-no-blocks.patch
  lang/clang-11-bootstrap/files/patch-clang-fix-include-next-sysroot-cpp-headers.diff
Labels: type: enhancement, type: submission

#15569 clang-11-bootstrap: fixed a typo by rebase
  lang/clang-11-bootstrap/Portfile
Labels: maintainer, maintainer: open

#15572 stdman: update to 2022.07.30
  lang/stdman/Portfile
  lang/stdman/files/patch-install.diff
Labels: type: update, maintainer, maintainer: open

#15571 odin: update to 0.2022.08
  lang/odin/Portfile
  lang/odin/files/patch-build.diff
  lang/odin/files/patch-makefile.diff
Labels: type: update, maintainer, maintainer: open

#15570 bitwarden-cli: update to 2022.6.2
  security/bitwarden-cli/Portfile
Labels: type: update, maintainer, maintainer: open

#15566 GPXSee: update to 11.2
  gis/GPXSee/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#15567 OpenJDK{8,13,15}:update to newer version
  java/openjdk13/Portfile
  java/openjdk15/Portfile
  java/openjdk8/Portfile
Labels: type: enhancement, maintainer, maintainer: open

#15573 clang-11-bootstrap: fix build on macOS 10.9
  lang/clang-11-bootstrap/Portfile
Labels: type: bugfix, maintainer, maintainer: open

#15574 k9s: update to 0.26.1
  sysutils/k9s/Portfile
Labels: type: update, maintainer, maintainer: open

#15575 kustomize: update to 4.5.7
  devel/kustomize/Portfile
Labels: type: update, maintainer, maintainer: open

#15576 google-cloud-sdk: update to 396.0.0
  devel/google-cloud-sdk/Portfile
Labels: type: update, maintainer, maintainer: open

#15581 qt4-mac: fix build on Rosetta
  aqua/qt4-mac/Portfile
Labels: type: bugfix, maintainer: open

#15396 vtm: update to 0.8.0
  sysutils/vtm/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#15457 meson: update to 0.63.0
  devel/meson/Portfile
Labels: type: enhancement, type: update, maintainer: open

#15582 clang-11-bootstrap: fix build on macOS 10.10
  lang/clang-11-bootstrap/Portfile
  lang/clang-11-bootstrap/files/fix-build-clang-by-gcc10-on-yosemite.diff
Labels: type: bugfix, maintainer, maintainer: open

#13995 libcxx: bootstrap with +emulated_tls on 10.6
  lang/libcxx/Portfile
Labels: type: enhancement, type: submission

#15585 libcxx: real skip dependencies archs check
  lang/libcxx/Portfile
Labels: maintainer: requires approval

#15584 py-clang/ctypeslib2: 310 versions & fixes
  python/py-clang/Portfile
  python/py-ctypeslib2/Portfile
Labels: maintainer, maintainer: open, by: member

#15496 pnpm: update to 7.8.0
  devel/pnpm/Portfile
Labels: type: update, maintainer: open

#15589 libfmt: update to 9.0.0
  devel/libfmt/Portfile
  devel/libfmt/files/fix-formatting-implicitly-convertible-types.patch
Labels: type: enhancement, type: update, maintainer: none

#15598 py-hypothesis: update to 6.54.1
  python/py-hypothesis/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#15597 bison: fix build on Rosetta
  devel/bison/Portfile
Labels: type: bugfix, maintainer: open

#15552 libgit2-glib: Update to 1.0.0
  gnome/libgit2-glib/Portfile
  gnome/libgit2-glib/files/patch-meson-find-mp-python3.diff
Labels: type: update, maintainer: open, by: member

#15580 libtheora: fix build on Rosetta
  multimedia/libtheora/Portfile
Labels: type: bugfix, maintainer: none

#15607 micronaut: update to 3.6.0
  java/micronaut/Portfile
Labels: type: update, maintainer, maintainer: open

#15590 openjdk11-temurin: update to 11.0.16
  java/openjdk11-temurin/Portfile
Labels: type: update, maintainer, maintainer: open

#15591 openjdk11-microsoft: update to 11.0.16
  java/openjdk11-microsoft/Portfile
Labels: type: update, maintainer, maintainer: open

#15592 openjdk17-microsoft: update to 17.0.4
  java/openjdk17-microsoft/Portfile
Labels: type: update, maintainer, maintainer: open

#15593 openjdk17-temurin: update to 17.0.4
  java/openjdk17-temurin/Portfile
Labels: type: update, maintainer, maintainer: open

#15608 universal-ctags: update to 5.9.20220731.0
  devel/universal-ctags/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#15609 retdec-devel: update to 20220624
  devel/retdec/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#15613 beets-devel: update to 20220810
  audio/beets/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#15616 py-awscli2: update to 2.7.21
  python/py-awscli2/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#15618 ismrmrd dcm2niix: 1.8.0 and 20220720
  science/dcm2niix/Portfile
  science/ismrmrd/Portfile
  science/ismrmrd/files/utilities_ismrmrd_phandom.cpp.patch
Labels: maintainer, maintainer: open, by: member

#15620 py-crashtest: update to 0.4.0
  python/py-crashtest/Portfile
Labels: type: enhancement, type: update, maintainer: open

#15619 py-shellingham: update to 1.5.0
  python/py-shellingham/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#15510 libslirp: update to 4.7.0, update maintainer handle
  net/libslirp/Portfile
Labels: type: enhancement, type: update, maintainer: requires approval, maintainer: timeout, by: member

#15625 py-zopfli: use pg compiler_wrapper
  python/py-zopfli/Portfile
Labels: type: bugfix, maintainer, maintainer: open

#15622 SilentKnight: update to 1.21
  sysutils/SilentKnight/Portfile
Labels: type: update, maintainer, maintainer: open

#15621 VisualVM: update to 2.1.4
  java/VisualVM/Portfile
Labels: type: update, maintainer, maintainer: open

#15535 py-pyqt5: `use_xcode yes`, `qt5.min_version 5.6`
  python/py-pyqt5/Portfile
Labels: maintainer: open

#15630 k9s: Generate shell completion files
  sysutils/k9s/Portfile
Labels: type: enhancement, maintainer: open

#15635 Gradle: Update to version 7.5.1
  devel/gradle/Portfile
Labels: type: update, maintainer: open

#15633 typescript-language-server: update to 1.0.0
  devel/typescript-language-server/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#15628 texlab: update to 4.2.1
  tex/texlab/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#15638 clojure: update to 1.11.1.1155
  lang/clojure/Portfile
Labels: type: update, maintainer, maintainer: open

#15547 nettle: update to 3.8.1
  devel/nettle/Portfile
Labels: type: enhancement, type: update, maintainer: open

#15568 nano: update to 6.4
  editors/nano/Portfile
Labels: type: enhancement, type: update, maintainer: open

#15604 rsync: fix build on Rosetta
  net/rsync/Portfile
Labels: type: bugfix, maintainer: open

#15389 exiv2: enable BMFF support
  graphics/exiv2/Portfile
Labels: maintainer: open, by: member

#15641 qtiplot: fix the build
  aqua/qtiplot/Portfile
  aqua/qtiplot/files/patch-boolean.diff
  aqua/qtiplot/files/patch-unsetflags.diff
Labels: type: bugfix, maintainer: open

#15631 Akumuli: update to 0.8.80, fix the build
  databases/Akumuli/Portfile
  databases/Akumuli/files/patch-cmakelists.diff
  databases/Akumuli/files/patch-httpserver.diff
  databases/Akumuli/files/patch-missing-headers.diff
  databases/Akumuli/files/patch-queryparser.diff
Labels: type: bugfix, type: enhancement, type: update, maintainer: none

#15645 gopass: update to 1.14.4
  security/gopass/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#15646 clang-11-bootstrap: fix build on macOS 10.5
  lang/clang-11-bootstrap/Portfile
  lang/clang-11-bootstrap/files/Fix-build-issues-pre-Lion-due-to-missing-a-strnlen.patch
  lang/clang-11-bootstrap/files/fix-build-with-old-xar.diff
  lang/clang-11-bootstrap/files/llvm-objdump-help-macho.diff
Labels: type: enhancement, maintainer, maintainer: open

#15647 libcxx: fix build on macOS 10.5
  lang/libcxx/Portfile
Labels: type: enhancement, maintainer: requires approval

#15644 llvm-5.0: fix the build on old systems with newer GCC, enable PPC
  lang/llvm-5.0/Portfile
  lang/llvm-5.0/files/patch-include-orc.diff
Labels: type: bugfix, maintainer: requires approval

#15632 pecco: update to 2022-03-18
  math/pecco/Portfile
Labels: type: enhancement, type: update, maintainer: none

#15643 unalz: Fix Bugs and Security Flaws
  archivers/unalz/Portfile
  archivers/unalz/files/1000-Makefile.diff
  archivers/unalz/files/1001-libz-linkage.diff
  archivers/unalz/files/1002-libbz2-linkage.diff
  archivers/unalz/files/1003-zlib-1.2.7-build.diff
  archivers/unalz/files/1004-pipe-mode-fixes.diff
  archivers/unalz/files/1005-filename-length-check.diff
  archivers/unalz/files/1006-fix-offset-overflow.diff
  archivers/unalz/files/1007-Remove-CXXFLAGS-from-linking.diff
Labels: type: bugfix, type: security fix, maintainer: none

#15544 gobject-introspection: fix build on Rosetta
  gnome/gobject-introspection/Portfile
Labels: type: bugfix, maintainer: open

#15651 openjdk8-zulu: update to 8.64.0.19
  java/openjdk8-zulu/Portfile
Labels: type: update, maintainer, maintainer: open

#15586 x265: fix Rosetta and ppc64 builds
  multimedia/x265/Portfile
  multimedia/x265/files/patch-ppc.diff
Labels: type: bugfix, maintainer: none

#15560 dnscrypt-proxy: update to 2.1.2
  net/dnscrypt-proxy/Portfile
Labels: type: update, maintainer: none

#15626 sheepit-client: New port
  graphics/sheepit-client/Portfile
  graphics/sheepit-client/files/sheepit-client.sh
Labels: type: submission, by: member

#15655 terraform-docs: Update to 0.16.0
  devel/terraform-docs/Portfile
Labels: type: update, maintainer: open

#15650 bash-completion: Update port completion
  sysutils/bash-completion/Portfile
  sysutils/bash-completion/files/port
Labels: type: update, maintainer: requires approval, by: member

#15649 flint: update to 2.9.0 and move to Cmake build system
  math/flint/Portfile
Labels: type: enhancement, type: update, maintainer: open

#15657 dnscontrol: New port (version 3.17.0)
  sysutils/dnscontrol/Portfile
Labels: type: submission

#15656 nanorc: New port (version 2020.10.10)
  editors/nanorc/Portfile
Labels: type: submission

#15662 just: update to 1.3.0
  sysutils/just/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer: open

#15654 gnuastro: update to 0.18
  science/gnuastro/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#15663 openjdk8-temurin: update to 8u345
  java/openjdk-distributions/Portfile
Labels: type: update, maintainer, maintainer: open

#15665 libcxx: cleanup dependency
  lang/libcxx/Portfile
Labels: maintainer

#15623 py-emoji: Submission
  python/py-emoji/Portfile
Labels: type: submission

#15669 uxn: update to 20220802
  emulators/uxn/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#15565 dosbox-x: update to 0.84.2
  emulators/dosbox-x/Portfile
  emulators/dosbox-x/files/patch-mactypes.diff
Labels: type: update, maintainer: none

#15661 py-XlsxWriter/pptx: add 3.10 versions.
  python/py-XlsxWriter/Portfile
  python/py-pptx/Portfile
Labels: maintainer, maintainer: open, by: member

#15660 clang-11-bootstrap, llvm-*: fix build on macOS 10.5
  lang/clang-11-bootstrap/files/0005-Threading-Only-call-pthread_setname_np-on-SnowLeopar.patch
  lang/llvm-10/files/0005-Threading-Only-call-pthread_setname_np-on-SnowLeopar.patch
  lang/llvm-11/files/0005-Threading-Only-call-pthread_setname_np-on-SnowLeopar.patch
  lang/llvm-5.0/files/0005-Threading-Only-call-pthread_setname_np-on-SnowLeopar.patch
  lang/llvm-6.0/files/0005-Threading-Only-call-pthread_setname_np-on-SnowLeopar.patch
  lang/llvm-7.0/files/0005-Threading-Only-call-pthread_setname_np-on-SnowLeopar.patch
  lang/llvm-8.0/files/0005-Threading-Only-call-pthread_setname_np-on-SnowLeopar.patch
  lang/llvm-9.0/files/0005-Threading-Only-call-pthread_setname_np-on-SnowLeopar.patch
Labels: type: bugfix, maintainer: requires approval

#15676 lean: update to v3.46.0
  math/lean/Portfile
Labels: type: update, maintainer, maintainer: open

#15674 dnscontrol: update to 3.18.0
  sysutils/dnscontrol/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#15672 flux: New port (version 0.31.5)
  sysutils/flux/Portfile
Labels: type: submission

#15670 fityk: update to 1.3.1
  math/fityk/Portfile
Labels: type: enhancement, type: update, maintainer: none

#15680 google-cloud-sdk: update to 397.0.0
  devel/google-cloud-sdk/Portfile
Labels: type: update, maintainer, maintainer: open

#15677 openjdk18-temurin: update arm64 to 18.0.2
  java/openjdk18-temurin/Portfile
Labels: type: update, maintainer, maintainer: open

#15514 py-ldap: update to 3.4.2
  python/py-ldap/Portfile
Labels: type: update, maintainer: none, by: member

#15681 varnish: update to 7.1.1
  www/varnish/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#15671 a60: ensure Rosetta builds for ppc and not x86
  lang/a60/Portfile
Labels: type: bugfix, maintainer: none

#15690 fheroes2: update to 0.9.18
  games/fheroes2/Portfile
Labels: type: update, maintainer, maintainer: open

#15692 dnscontrol: update to 3.18.1
  sysutils/dnscontrol/Portfile
Labels: type: bugfix, type: update, maintainer, maintainer: open

#15624 asio: update to 1.23.0
  devel/asio/Portfile
Labels: type: enhancement, type: update, maintainer: open

#15693 stack: Update to version 2.7.5
  lang/stack/Portfile
Labels: type: update, maintainer, maintainer: open

#15664 openjdk8: update to 8u345
  java/openjdk8/Portfile
Labels: type: update, maintainer: open

#15695 flux: update to 0.32.0
  sysutils/flux/Portfile
Labels: type: update, maintainer, maintainer: open

#15673 terragrunt: update to 0.38.7
  sysutils/terragrunt/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer: open

#15682 py-flask: update to 2.2.2
  python/py-flask/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#15685 clang-11-bootstrap: build by bootstrap before 10.12 only
  lang/clang-11-bootstrap/Portfile
Labels: type: enhancement, maintainer, maintainer: open

#15615 glfw: disable docs on PPC, fixes Rosetta build
  graphics/glfw/Portfile
Labels: type: bugfix, maintainer: open

#15698 bitwarden-cli: update to 2022.8.0
  security/bitwarden-cli/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#15696 unxip: submission
  archivers/unxip/Portfile
  archivers/unxip/files/patch-help_message.diff
Labels: type: submission, by: member

#15704 py-awscli2: update to 2.7.22
  python/py-awscli2/Portfile
Labels: type: bugfix, type: update, maintainer, maintainer: open

#15702 openjdk8-openj9: update to 8u345
  java/openjdk-distributions/Portfile
Labels: type: update, maintainer, maintainer: open

#15701 openjdk11-openj9: update to 11.0.16
  java/openjdk11-openj9/Portfile
Labels: type: update, maintainer, maintainer: open

#15700 openjdk17-openj9: update to 17.0.4
  java/openjdk17-openj9/Portfile
Labels: type: update, maintainer, maintainer: open

#15699 openjdk18-openj9: update to 18.0.2
  java/openjdk18-openj9/Portfile
Labels: type: update, maintainer, maintainer: open

#15707 httpie: update to 3.2.1
  net/httpie/Portfile
Labels: type: update, maintainer: none

#15688 pnpm: update to 7.9.1
  devel/pnpm/Portfile
Labels: type: enhancement, type: update, maintainer: open

#15691 leiningen: use codeberg for master_sites, update version to 2.9.10
  devel/leiningen/Portfile
Labels: type: enhancement, maintainer: open

#15712 broot: remove xorg-libxcb dependency
  sysutils/broot/Portfile
Labels: maintainer, maintainer: open, by: member

#15713 asciidoc: Update to 10.2.0
  textproc/asciidoc/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#15714 Bear: Update to 3.0.20
  devel/Bear/Portfile
  devel/Bear/files/patch-source-intercept-CMakeLists-txt.patch
  devel/Bear/files/patch-spdlog-header-only.diff
Labels: type: enhancement, type: update, maintainer, maintainer: open, by: member

#15715 grcp: Update to 0.9.1
  sysutils/qrcp/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#15666 llvm-{11,12,13,14,devel}: fix compatibility with legacy-support on 10.5
  lang/llvm-11/Portfile
  lang/llvm-11/files/0007-patch-llvm8-tools-dsymutil-symbolmap-use-older-cfname-and-fix-uuid-on-leopard.diff
  lang/llvm-12/Portfile
  lang/llvm-12/files/0023-10.5-and-less-use-older-cfname-and-fix-uuid-on-leopa.patch
  lang/llvm-13/Portfile
  lang/llvm-13/files/0023-10.5-and-less-use-older-cfname-and-fix-uuid-on-leopa.patch
  lang/llvm-14/Portfile
  lang/llvm-14/files/0023-10.5-and-less-use-older-cfname-and-fix-uuid-on-leopa.patch
  lang/llvm-devel/Portfile
  lang/llvm-devel/files/0023-10.5-and-less-use-older-cfname-and-fix-uuid-on-leopa.patch
Labels: type: bugfix, maintainer: requires approval, maintainer: timeout

#15711 xorg-xorgproto: update to 2022.2
  x11/xorg-xorgproto/Portfile
Labels: type: update, maintainer: open

#15687 *-mingw32-binutils: Update to 2.39
  _resources/port1.0/group/crossbinutils-1.0.tcl
  cross/i686-w64-mingw32-binutils/Portfile
  cross/i686-w64-mingw32-binutils/files/patch-dlltool-fix.diff
  cross/x86_64-w64-mingw32-binutils/Portfile
  cross/x86_64-w64-mingw32-binutils/files/patch-dlltool-fix.diff
Labels: type: enhancement, type: update, maintainer: open

#15719 miniflux: update to 2.0.38
  net/miniflux/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#15720 GPXSee: update to 11.3
  gis/GPXSee/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#15722 josm: update to 18531
  gis/JOSM/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#15694 termcolor: update to 2.1.0
  devel/termcolor/Portfile
Labels: type: update, maintainer: open, by: member

#15728 pypy-bootstrap: remove obsolete port
  lang/pypy-bootstrap/Portfile
Labels: maintainer: open

#15721 stagit: new port
  www/stagit/Portfile
Labels: type: enhancement, type: submission

#15727 poac: update to 0.4.1
  sysutils/poac/Portfile
Labels: type: enhancement, type: update, maintainer: open

#15729 minizip2: remove obsolete port
  archivers/minizip2/Portfile
Labels: maintainer: open

#15726 vtm: add mc variant
  sysutils/vtm/Portfile
Labels: type: enhancement, maintainer, maintainer: open

#15399 ssh-askpass-mac: submission
  aqua/ssh-askpass-mac/Portfile
  aqua/ssh-askpass-mac/files/org.macports.ssh-askpass-mac.plist
Labels: type: submission

#15737 krew: add installation instructions
  sysutils/krew/Portfile
Labels: type: enhancement, maintainer: open

#15743 armadillo: make openblas variant default on PPC, fixes build
  science/armadillo/Portfile
Labels: type: bugfix, maintainer: open

#15678 google-glog: fix build on old systems using gcc
  devel/gflags/Portfile
  devel/google-glog/Portfile
Labels: type: bugfix, maintainer: none

#15705 py-filelock: update to 3.8.0
  python/py-filelock/Portfile
Labels: type: enhancement, type: update, maintainer: open

#15703 postgresql14: update to 14.5
  databases/postgresql14-doc/Portfile
  databases/postgresql14-server/Portfile
  databases/postgresql14/Portfile
Labels: type: bugfix, type: update, maintainer: requires approval, maintainer: timeout

#15555 py-pytorch: Add Apple MPS GPU hardware acceleration, Apple Silicon support
  python/py-pytorch/Portfile
Labels: type: enhancement, maintainer: none

#15493 py-graph-tool: Add Python 310
  python/py-graph-tool/Portfile
Labels: type: update, maintainer, maintainer: open

#15501 qt5-qtwebengine: fallback to nodejs16 on macOS 10.13
  aqua/qt5/Portfile
Labels: maintainer: open

#15540 feh: update to 3.9
  graphics/feh/Portfile
  graphics/feh/files/implicit.patch
Labels: type: enhancement, type: update, maintainer: none

#15745 rofi: update to 1.7.4
  x11/rofi/Portfile
  x11/rofi/files/patch-filebrowser.diff
Labels: type: enhancement, type: update, maintainer, maintainer: open

#15746 dnscontrol: update to 3.19.0
  sysutils/dnscontrol/Portfile
Labels: type: update, maintainer, maintainer: open

#15748 bloaty: new port
  devel/bloaty/Portfile
Labels: type: enhancement, type: submission

#15751 gitlab-runner: update to 15.2.1
  devel/gitlab-runner/Portfile
Labels: type: update, maintainer: none, by: member

#15639 swig: remove dependency on swig3
  devel/swig/Portfile
Labels: type: bugfix, maintainer: open

#15708 gitweb: update to 0.3.5
  devel/gitweb/Portfile
Labels: type: update, maintainer: open

#15756 google-cloud-sdk: update to 398.0.0
  devel/google-cloud-sdk/Portfile
Labels: type: update, maintainer, maintainer: open

#15761 skaffold: update to 1.39.2
  devel/skaffold/Portfile
Labels: type: update, maintainer, maintainer: open

#15758 openjdk11-corretto: update to 11.0.16.9.1
  java/openjdk11-corretto/Portfile
Labels: type: update, maintainer, maintainer: open
