Repository macports/macports-ports, pull requests merged in 2022-03, with the labels that each got.

#14157 gobject-introspection{,-devel}: bump python dependency to 3.10
  gnome/gobject-introspection-devel/Portfile
  gnome/gobject-introspection/Portfile
Labels: type: enhancement, maintainer: open

#14156 gqrx-devel: remove obsolete subport
  science/gqrx/Portfile
Labels: maintainer: open

#14162 asciidoc: Update to 10.1.3
  textproc/asciidoc/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#14165 zabbix: 4.0.39, 5.0.21; prep for 6
  net/zabbix4/Portfile
Labels: maintainer, maintainer: open, by: member

#14168 zabbix: OpenSSL exception
  net/zabbix4/Portfile
Labels: maintainer, maintainer: open, by: member

#14169 google-cloud-sdk: update to 375.0.0
  devel/google-cloud-sdk/Portfile
Labels: type: update, maintainer, maintainer: open

#14161 Gildas: update to 202203a
  science/gildas/Portfile
Labels: type: enhancement, type: update, maintainer

#14170 micronaut: update to 3.3.4
  java/micronaut/Portfile
Labels: type: update, maintainer, maintainer: open

#14171 smartmontools: update to 7.3
  sysutils/smartmontools/Portfile
Labels: type: update, maintainer: open

#14164 gsmartcontrol: Update to 1.1.4
  sysutils/gsmartcontrol/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#14175 dosbox-x: update to 0.83.23
  emulators/dosbox-x/Portfile
Labels: type: update, maintainer: none

#14178 cool-retro-term: correct dependency
  aqua/cool-retro-term/Portfile
Labels: type: bugfix, maintainer, maintainer: open, by: member

#14166 libressl-devel update to 3.5.0
  security/libressl-devel/Portfile
Labels: type: enhancement, type: security fix, maintainer: requires approval

#14183 odin: update to 0.2022.03
  lang/odin/Portfile
  lang/odin/files/patch-makefile.diff
Labels: type: update, maintainer, maintainer: open

#14114 fossil: update to 2.18
  devel/fossil/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer: requires approval, maintainer: timeout

#14141 wget: update to 1.21.3
  net/wget/Portfile
  net/wget/files/SSL_INIT.patch
  net/wget/files/prefix.patch
Labels: type: update, maintainer: open

#14182 tectonic: update to version 0.8.2
  tex/tectonic/Portfile
Labels: type: update, maintainer: open

#14184 py-awscli2, py-awscrt: disable build on old macOS
  python/py-awscli2/Portfile
  python/py-awscrt/Portfile
Labels: type: bugfix, maintainer, maintainer: open

#14146 openjdk: add Amazon Corretto OpenJDK
  java/openjdk/Portfile
Labels: maintainer, maintainer: open

#14153 hugo: update to 0.93.0
  www/hugo/Portfile
Labels: type: update, maintainer: open, by: member

#14179 gjs: update to 1.64.5
  gnome/gjs/Portfile
  gnome/gjs/files/patch-gjs-gint64.diff
  gnome/gjs/files/patch-gjs-gsize.diff
  gnome/gjs/files/patch-gjs-test.diff
Labels: type: update, maintainer: open

#14143 gdcm: update to 3.0.10
  science/gdcm/Portfile
  science/gdcm/files/gdcm_charls.h.patch
  science/gdcm/files/patch-poppler.diff
  science/gdcm/files/patch-poppler_const.diff
Labels: type: bugfix, type: update, maintainer: open, by: member

#14154 Add php-pcov pecl port
  php/php-pcov/Portfile
Labels: type: enhancement, type: submission

#14190 py-pygraphviz: update to 1.9
  python/py-pygraphviz/Portfile
Labels: type: enhancement, maintainer: none

#14194 hugo: update to 0.93.2
  www/hugo/Portfile
Labels: type: update, maintainer: open, by: member

#14196 skaffold: update to 1.36.1
  devel/skaffold/Portfile
Labels: type: update, maintainer, maintainer: open

#14195 openjdk11-sap: more relevant URL for latest version
  java/openjdk/Portfile
Labels: type: enhancement, maintainer, maintainer: open

#14159 Wireshark3: add python3.10 variant
  net/wireshark3/Portfile
Labels: type: enhancement, maintainer: requires approval

#14081 ncarg: Escape cflags properly and mark as unsupported on arm64
  science/ncarg/Portfile
Labels: maintainer: open, by: member

#14198 jreleaser: update to version v1.0.0-M3
  devel/jreleaser/Portfile
Labels: type: enhancement, type: update, maintainer

#14197 procmail: update to maintained fork
  mail/procmail/Portfile
  mail/procmail/files/getline.patch
  mail/procmail/files/patch-CVE-2014-3618.diff
  mail/procmail/files/patch-CVE-2017-16844.diff
  mail/procmail/files/patch-security-fixes.diff
  mail/procmail/files/patch-src-foldinfo.c.diff
  mail/procmail/files/patch-src-manconf.c.diff
Labels: type: update, maintainer: none, by: member

#14173 glade: remove obsolete reinplace
  devel/glade/Portfile
Labels: type: bugfix, maintainer: open

#14200 Recoll: Update to v1.31.6
  textproc/recoll/Portfile
Labels: type: enhancement, type: update, maintainer: open

#14203 qsv: new port (version 0.34.1)
  textproc/qsv/Portfile
Labels: type: submission, by: member

#14180 nodejs: deprecate EOL versions
  devel/nodejs10/Portfile
  devel/nodejs13/Portfile
  devel/nodejs15/Portfile
  devel/nodejs8/Portfile
Labels: maintainer: open

#14089 vim, MacVim: add comment to keep patchlevels in sync
  editors/MacVim/Portfile
  editors/vim/Portfile
Labels: maintainer: requires approval, maintainer: timeout

#14207 retroarch: update to 1.10.1
  emulators/retroarch/Portfile
Labels: type: update, maintainer, maintainer: open

#14208 neomutt: Add support for lz4 and zstd compression
  mail/neomutt/Portfile
Labels: type: enhancement, maintainer: open, by: member

#14206 libreoffice: update to 7.3.1.3
  office/libreoffice/Portfile
Labels: type: update, maintainer, maintainer: open

#13927 libdeflate: fix install_name of dylib
  archivers/libdeflate/Portfile
  archivers/libdeflate/files/patch-shared_lib_ldflags-variable-fix.diff
Labels: type: bugfix, maintainer: open

#14213 swi-prolog-devel: Updated to version 8.5.8
  lang/swi-prolog-devel/Portfile
Labels: type: update, maintainer, maintainer: open

#13463 postgresql96-server: Remove shell from `postgres` user
  databases/postgresql96-server/Portfile
Labels: type: bugfix, maintainer: requires approval, maintainer: timeout

#14219 google-cloud-sdk: update to 376.0.0
  devel/google-cloud-sdk/Portfile
Labels: type: update, maintainer, maintainer: open

#14220 groovy: update to 4.0.1
  lang/groovy/Portfile
Labels: type: update, maintainer, maintainer: open

#14221 lagrange: update to 1.11.1
  net/lagrange/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#14223 miniflux: update to 2.0.36
  net/miniflux/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#13990 ghc: Update to version 9.2.1 and add native arm64 support
  lang/ghc/Portfile
  lang/ghc/files/keyid-588764fbe22d19c4.txt
  lang/ghc/files/keyid-ffeb7ce81e16a36b3e2ded6f2de04d4e97db64ad.txt
  lang/ghc/files/patch-ghc_mk.diff
  lang/ghc/files/patch-gmp-ghc.mk.diff
Labels: type: enhancement, type: update, maintainer, maintainer: open

#14226 josm: update to 18387
  gis/JOSM/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#14227 gradle: update to 7.4.1
  devel/gradle/Portfile
Labels: type: update, maintainer: open

#14228 hugo: update to 0.93.3
  www/hugo/Portfile
Labels: type: update, maintainer, maintainer: open

#14211 flyctl: Add shell completions
  devel/flyctl/Portfile
Labels: type: enhancement, maintainer: open

#14230 xar: Fix to-stdout functionality
  archivers/xar/Portfile
  archivers/xar/files/patch-stdout.diff
Labels: maintainer: open, by: member

#14210 typescript: new port
  lang/typescript/Portfile
Labels: type: submission

#14209 chromedriver: Update to version 99.0.4844.51
  www/chromedriver/Portfile
Labels: type: update, maintainer: open

#14148 gcc10-bootstrap: fix build on Big Sur
  lang/gcc10-bootstrap/Portfile
Labels: type: bugfix, type: enhancement, maintainer, maintainer: open

#14229 ecCodes: update to 2.25.0
  science/ecCodes/Portfile
Labels: type: update, maintainer, maintainer: open

#14222 py-hypothesis: update to 6.39.3
  python/py-hypothesis/Portfile
Labels: type: enhancement, type: update, maintainer: open, by: member

#14217 py-filterpy: fix dependencies, update Python versions
  python/py-filterpy/Portfile
Labels: type: enhancement, maintainer: open, by: member

#14189 foundationdb: update to 6.3.24
  databases/foundationdb/Portfile
Labels: type: enhancement, type: update, maintainer: open

#14242 melonds: update to 0.9.4
  emulators/melonds/Portfile
Labels: type: update, maintainer, maintainer: open

#14240 nodejs8: require OpenSSL 1.1
  devel/nodejs8/Portfile
Labels: type: bugfix, maintainer: open

#14241 libreoffice: update to 7.3.2.1
  office/libreoffice/Portfile
Labels: type: update, maintainer, maintainer: open

#14243 maven3: update to 3.8.5
  java/maven3/Portfile
Labels: type: update, maintainer: none

#14185 openjdk-source: new port
  java/openjdk-source/Portfile
  java/openjdk-source/files/patch-openjdk15u-build-fix.diff
  java/openjdk-source/files/patch-openjdk8u-xcode-configure1.diff
  java/openjdk-source/files/patch-openjdk8u-xcode-configure2.diff
Labels: type: enhancement, type: submission

#14244 goaccess: build with GeoIP support
  www/goaccess/Portfile
Labels: maintainer: open, by: member

#14239 hugo: update to 0.94.2
  www/hugo/Portfile
Labels: type: update, maintainer: open, by: member

#14245 weechat: update to 3.4.1, remove old python variants
  irc/weechat/Portfile
Labels: type: update, maintainer, maintainer: open

#14233 KeePassXC-devel: update to latest devel (>= 2.7.0-beta1)
  security/KeePassXC/Portfile
  security/KeePassXC/files/devel/patch-no-deployqt.diff
Labels: type: update, maintainer: none

#14246 dbvis: update to 13.0.1
  databases/dbvis/Portfile
Labels: type: update, maintainer, maintainer: open

#14247 SilentKnight: update to 1.18
  sysutils/SilentKnight/Portfile
Labels: type: update, maintainer, maintainer: open

#14225 libuv: update to 1.44.1
  devel/libuv/Portfile
  devel/libuv/files/patch-libuv-legacy.diff
  devel/libuv/files/patch-libuv-unix-core-close-nocancel.diff
  devel/libuv/files/patch-makefile-am-no-libutil-on-Tiger.diff
  devel/libuv/files/patch-no-libutil-on-Tiger.diff
Labels: type: enhancement, type: update, maintainer, maintainer: open, by: member

#14252 wolfssl: update to version 5.2.0
  devel/wolfssl/Portfile
Labels: type: update, maintainer, type: security fix, maintainer: open

#14224 flac: disable `-fstack-protector-strong` with GCC 4.*
  audio/flac/Portfile
Labels: type: bugfix, maintainer: none

#14128 openal-soft: Use legacysupport for new TargetConditionals.h macros
  audio/openal-soft/Portfile
Labels: type: bugfix, maintainer: open

#14255 t-rec: update to 0.7.3
  graphics/t-rec/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#14256 libuv: fix build on 10.5/10.6
  devel/libuv/files/patch-libuv-legacy.diff
Labels: type: bugfix, maintainer: open

#14262 usql: update to 0.9.7
  databases/usql/Portfile
  databases/usql/files/patch-no-upx.diff
Labels: type: update, maintainer, maintainer: open, by: member

#14257 arti: new port (version 0.1.0)
  security/arti/Portfile
Labels: type: submission, by: member

#14267 google-cloud-sdk: update to 377.0.0
  devel/google-cloud-sdk/Portfile
Labels: type: update, maintainer, maintainer: open

#14269 task: update to 2.6.2
  office/task/Portfile
Labels: type: update, maintainer: none

#14270 flac: fix configure flag for disabling stack protection
  audio/flac/Portfile
Labels: type: bugfix, maintainer: none

#14276 ghc: Add depends_skip_archcheck for platform arm, Fix prebuilt issues
  lang/ghc/Portfile
Labels: type: bugfix, maintainer, maintainer: open

#14275 bitwarden-cli: Update to version 1.22.0
  security/bitwarden-cli/Portfile
Labels: type: update, maintainer, maintainer: open

#14273 gopass: update to 1.14.0
  security/gopass/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#14282 go: pin to version 1.17.8 for macOS 10.12 and older
  lang/go/Portfile
Labels: maintainer, maintainer: open, by: member

#14279 update libressl to 3.4.3
  security/libressl/Portfile
Labels: type: bugfix, type: update, type: security fix, maintainer: requires approval

#14278 update libressl-devel to 3.5.1
  security/libressl-devel/Portfile
Labels: type: bugfix, type: update, type: security fix, maintainer: requires approval

#14294 android-platform-tools: update to 33.0.1
  java/android-platform-tools/Portfile
Labels: type: update, maintainer: open

#14292 lagrange: update to 1.11.2
  net/lagrange/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#14290 exact-image: build for BigSur/M1
  graphics/exact-image/Portfile
  graphics/exact-image/files/patch-codecs-jpeg2000.diff
Labels: maintainer: open

#14289 mozjs91: new port
  lang/mozjs91/Portfile
  lang/mozjs91/files/patch-skip-sdk-check.diff
Labels: type: submission

#14284 mozjs68: remove arm64 from `supported_archs`
  lang/mozjs68/Portfile
Labels: type: bugfix, maintainer: none

#14286 dot2tex: use Python 3.10
  python/dot2tex/Portfile
Labels: type: enhancement, maintainer: open, by: member

#14295 mozjs91: fix configuration when `sdkroot` is empty
  lang/mozjs91/Portfile
Labels: type: bugfix, maintainer: none

#14274 py-numpydoc: update to 1.2
  python/py-numpydoc/Portfile
Labels: type: update, maintainer: open, by: member

#14291 julius-caesar-3: fix build on 10.6/10.7
  games/julius-caesar-3/Portfile
  games/julius-caesar-3/files/patch-julius-deployment.diff
  games/julius-caesar-3/files/patch-julius-makeicns.diff
Labels: type: bugfix, maintainer: open

#14305 wireguard-go: update to 0.0.20220316
  net/wireguard-go/Portfile
Labels: type: update, maintainer, maintainer: open

#14306 lean: update to v3.42.0
  math/lean/Portfile
Labels: type: update, maintainer, maintainer: open

#14283 paho.mqtt.c: New port
  net/paho.mqtt.c/Portfile
Labels: type: enhancement, type: submission

#14311 skaffold: update to 1.37.0
  devel/skaffold/Portfile
Labels: type: update, maintainer, maintainer: open

#14303 fish: update to 3.4.0
  shells/fish/Portfile
  shells/fish/files/patch-tests-checks-tmux-complete-fish.diff
  shells/fish/files/patch-tests-checks-tmux-prompt-fish.diff
  shells/fish/files/patch-tests-interactive-fish.diff
Labels: type: enhancement, type: update, maintainer: none

#14308 stdman: new port
  lang/libstdcxx-docs/Portfile
  lang/stdman/Portfile
Labels: type: submission, maintainer, maintainer: open

#14312 py-multiprocess: update to 0.70.12.2 and added py310
  python/py-multiprocess/Portfile
Labels: type: enhancement, type: update, maintainer: none

#14319 chafa: update to 1.10.0
  graphics/chafa/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#14313 py-ipympl: add py38, py39, py310 subports and update to 0.7.0
  python/py-ipympl/Portfile
Labels: type: enhancement, maintainer: open

#14320 paho.mqtt.cpp: New port
  net/paho.mqtt.cpp/Portfile
Labels: type: enhancement, type: submission

#14212 openjdk: rename to openjdk-distributions
  java/openjdk-distributions/Portfile
Labels: maintainer, maintainer: open

#14318 prawcore: new port (v.2.3.0)
  python/py-prawcore/Portfile
Labels: type: submission

#14324 dotnet-cli: add arm64 architecture
  dotnet/dotnet-cli/Portfile
Labels: type: enhancement, maintainer, maintainer: open

#14326 py-kitchen: new port (v.1.2.6)
  python/py-kitchen/Portfile
Labels: type: submission

#14328 py-update_checker: add Python 3.10 variant
  python/py-update_checker/Portfile
Labels: maintainer: open

#14329 MoarVM: fix build on Snow Leopard
  lang/MoarVM/Portfile
Labels: type: bugfix, maintainer: open

#14266 exiftool: update to 12.4.0
  perl/exiftool/Portfile
Labels: type: enhancement, type: update, maintainer: open, by: member

#14327 fava: update to 1.21, use Python 3.10
  python/fava/Portfile
Labels: type: update, maintainer: open, by: member

#14325 openjdk-distributions: move openjdk8-zulu to its own Portfile
  java/openjdk-distributions/Portfile
  java/openjdk8-zulu/Portfile
Labels: maintainer, maintainer: open

#14315 ghc: Fix build on arm
  lang/ghc/Portfile
Labels: type: bugfix, maintainer, maintainer: open

#14330 hunspell-dict-uk_UA: update to 5.6.0, claim maintainership
  textproc/hunspell-dict-uk_UA/Portfile
Labels: type: update, maintainer: none, by: member

#14299 mozjs91: fall back to generic uptime logic pre-10.12
  lang/mozjs91/Portfile
  lang/mozjs91/files/patch-mozglue-clock_gettime.diff
Labels: type: bugfix, maintainer: none

#14254 luit: Update to 2.0.20220111
  x11/luit/Portfile
Labels: type: enhancement, type: update, maintainer: open

#13416 openmpi/mpich: enable support for clang12 and clang13
  _resources/port1.0/group/mpi-1.0.tcl
  science/mpi-doc/Portfile
  science/mpich/Portfile
  science/mpich/files/portselect/mpich-clang12
  science/mpich/files/portselect/mpich-clang12-fortran
  science/mpich/files/portselect/mpich-clang13
  science/mpich/files/portselect/mpich-clang13-fortran
  science/openmpi/Portfile
  science/openmpi/files/portselect/openmpi-clang12
  science/openmpi/files/portselect/openmpi-clang12-fortran
  science/openmpi/files/portselect/openmpi-clang13
  science/openmpi/files/portselect/openmpi-clang13-fortran
Labels: maintainer: requires approval, by: member, wip

#14334 py-kitchen: update to version 1.2.6_1
  python/py-kitchen/Portfile
Labels: type: update, maintainer: none

#14317 praw: new port (version 7.5.0)
  python/py-praw/Portfile
Labels: type: submission

#14293 mtr: use github PortGroup
  net/mtr/Portfile
Labels: type: bugfix, maintainer: none

#14335 newsboat: update to r2.27
  net/newsboat/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#14340 openjdk18-oracle: new submission
  java/openjdk18-oracle/Portfile
Labels: type: submission

#14341 openjdk-distributions: remove previously obsoleted openjdk15-openj9* ports
  java/openjdk-distributions/Portfile
Labels: maintainer, maintainer: open

#14338 openjdk18-zulu: new submission
  java/openjdk18-zulu/Portfile
Labels: type: submission

#14353 Colima: Update to v0.3.4
  sysutils/colima/Portfile
Labels: type: update, maintainer: open

#14322 cdo: update to 2.0.5
  science/cdo/Portfile
Labels: type: update, maintainer: open

#14297 npm[3-5]: deprecate
  devel/npm3/Portfile
  devel/npm4/Portfile
  devel/npm5/Portfile
Labels: maintainer: requires approval, maintainer: timeout

#14296 npm[6-8]: depend on nodejs14 on 10.8 and earlier
  devel/npm6/Portfile
  devel/npm7/Portfile
  devel/npm8/Portfile
Labels: type: bugfix, maintainer: open

#14351 openjdk18-sap: new submission
  java/openjdk18-sap/Portfile
Labels: type: submission

#14345 openjdk18-corretto: new submission
  java/openjdk18-corretto/Portfile
Labels: type: submission

#14356 cdo: require C++14
  science/cdo/Portfile
Labels: type: bugfix, maintainer: open

#14218 libdbi{,-drivers}: autoreconf to fix build on arm64
  databases/libdbi-drivers/Portfile
  databases/libdbi/Portfile
Labels: type: bugfix, maintainer: requires approval, maintainer: timeout

#14333 BLAKE3: new port (v1.3.1)
  security/blake3/Portfile
Labels: type: submission

#14357 mpich: update PowerPC patch
  science/mpich/Portfile
  science/mpich/files/patch-mpich-darwin-powerpc.diff
Labels: type: bugfix, type: update, maintainer: requires approval

#14358 cdo: require thread-local storage
  science/cdo/Portfile
Labels: type: bugfix, maintainer: open

#14347 openjdk-distributions: move openjdk17-oracle to its own Portfile
  java/openjdk-distributions/Portfile
  java/openjdk17-oracle/Portfile
Labels: maintainer, maintainer: open

#14337 tuir: new port (v.1.29.0)
  net/tuir/Portfile
Labels: type: submission

#14302 innoextract: fix build on 10.6
  archivers/innoextract/Portfile
Labels: type: bugfix, maintainer: open

#14360 MoarVM: fix build on 10.8 and earlier
  lang/MoarVM/Portfile
  lang/MoarVM/files/patch-Configure.diff
Labels: type: bugfix, maintainer: open

#14301 yarn: depend on nodejs14 on 10.8 and earlier
  devel/yarn/Portfile
Labels: type: enhancement, maintainer: open

#14362 KeePassXC: upgrade to 2.7.0
  security/KeePassXC/Portfile
  security/KeePassXC/files/devel/patch-no-deployqt.diff
  security/KeePassXC/files/devel/patch-no-findpackage-path.diff
  security/KeePassXC/files/patch-no-deployqt.diff
  security/KeePassXC/files/patch-no-findpackage-path.diff
  security/KeePassXC/files/patch-old-mac.diff
  security/KeePassXC/files/patch-quazip.diff
  security/KeePassXC/files/patch-touch-id.diff
Labels: maintainer: none

#14364 unshield: fix run-time issue on PowerPC
  archivers/unshield/Portfile
Labels: type: bugfix, maintainer: none

#14354 privoxy: Add user_pki_bundle variant
  www/privoxy/Portfile
Labels: type: enhancement, maintainer, maintainer: open

#14363 swi-prolog-devel: Updated to version 8.5.9
  lang/swi-prolog-devel/Portfile
Labels: type: update, maintainer, maintainer: open

#14336 libtommath: fix build error with MoarVM
  math/libtommath/Portfile
  math/libtommath/files/patch-pr-476.diff
Labels: type: enhancement, maintainer: none

#14367 fish: update to 3.4.1
  shells/fish/Portfile
Labels: type: enhancement, type: update, maintainer: none

#14371 gobject-introspection: update to 1.72.0
  gnome/gobject-introspection/Portfile
Labels: type: bugfix, type: update, maintainer: open
