Repository macports/macports-ports, pull requests merged in 2022-06, with the labels that each got.

#14984 rust, cargo: change maintainer
  devel/cargo/Portfile
  lang/rust/Portfile
Labels: maintainer, maintainer: open, by: member

#14959 py-telethon: Submission
  python/py-telethon/Portfile
Labels: type: submission

#14996 llvm-14: update to 14.0.4
  lang/llvm-14/Portfile
Labels: type: update, maintainer: none, by: member

#15002 cfonts: update minor 1.0.2 > 1.0.3
  textproc/cfonts/Portfile
Labels: type: enhancement, type: update, maintainer: open

#15007 libomp: 14.0.4 (no change, but tracking latest clang)
  lang/libomp/Portfile
Labels: maintainer, maintainer: open, by: member

#15003 rmlint: fix build on old systems, fix universal variant
  sysutils/rmlint/Portfile
  sysutils/rmlint/files/patch-darwin-old.diff
  sysutils/rmlint/files/patch-universal.diff
Labels: type: bugfix, maintainer: open

#15040 dosbox-x: update to 0.84.0
  emulators/dosbox-x/Portfile
Labels: type: update, maintainer: none

#15013 google-cloud-sdk: update to 388.0.0
  devel/google-cloud-sdk/Portfile
Labels: type: update, maintainer, maintainer: open

#15035 py-types-ujson: Submission
  python/py-types-ujson/Portfile
Labels: type: submission

#15034 py-types-simplejson: Submission
  python/py-types-simplejson/Portfile
Labels: type: submission

#15031 py-starlette: Update to version 0.20.1
  python/py-starlette/Portfile
Labels: type: update, maintainer: none

#15030 py-sparse: Submission
  python/py-sparse/Portfile
Labels: type: submission

#15029 py-setuptools-rust: Update to version 1.3.0
  python/py-setuptools-rust/Portfile
Labels: type: update, maintainer: none

#15027 py-pydub: Add Python 310
  python/py-pydub/Portfile
Labels: maintainer: none

#15009 xraylib: update to version 4.1.2, add python310 variant
  science/xraylib/Portfile
Labels: type: enhancement, type: update, maintainer: none

#15041 swi-prolog-devel: Updated to version 8.5.12
  lang/swi-prolog-devel/Portfile
Labels: type: update, maintainer, maintainer: open

#15016 py-autoflake: Submission
  python/py-autoflake/Portfile
Labels: type: submission

#15025 py-monotonic: Add Python 310
  python/py-monotonic/Portfile
Labels: maintainer: open

#15023 py-mdurl: Submission
  python/py-mdurl/Portfile
Labels: type: submission

#15006 Gildas: update to 202206a
  science/gildas/Portfile
Labels: type: enhancement, type: update, maintainer

#15015 py-analytics-python: Submission
  python/py-analytics-python/Portfile
  python/py-analytics-python/files/patch-setup_py.diff
Labels: type: submission

#15020 py-linkify-it-py: Submission
  python/py-linkify-it-py/Portfile
Labels: type: submission

#14987 clingo: update to 5.5.2, fix PPC build
  math/clingo/Portfile
  math/clingo/files/patch-locale.diff
Labels: type: bugfix, type: enhancement, type: update, maintainer: none

#15010 py-pymatgen: update to v2022.5.19, add py310
  python/py-pymatgen/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#15042 py-cli-helpers: update to 2.2.1
  python/py-cli-helpers/Portfile
Labels: type: bugfix, type: update, maintainer: open

#15008 gcc11/libgcc11: skip bootstrap comparison for 10.6 and earlier
  lang/gcc11/Portfile
Labels: maintainer: none, by: member

#14999 ninja: support installing `libninja.a`
  devel/ninja/Portfile
Labels: type: enhancement, maintainer: open

#14965 get_iplayer: update to 3.30
  net/get_iplayer/Portfile
Labels: type: enhancement, type: update, maintainer: open

#14784 lens: update to 5.5.3
  sysutils/lens/Portfile
  sysutils/lens/files/patch-package.json.diff
Labels: type: update, maintainer, maintainer: open, by: member

#15019 py-ffmpy: Submission
  python/py-ffmpy/Portfile
Labels: type: submission

#15051 lensfun: Fix python module installation; use python 3.10
  graphics/lensfun/Portfile
Labels: maintainer: open, by: member

#15021 py-markdown-it-py: Update to version 2.1.0
  python/py-markdown-it-py/Portfile
  python/py-markdown-it-py/files/patch-pyproject_toml.diff
Labels: type: update, maintainer: open

#15022 py-maturin: Submission
  python/py-maturin/Portfile
Labels: type: submission

#15028 py-python-multipart: Submission
  python/py-python-multipart/Portfile
Labels: type: submission

#15058 rb-rake: update to 13.0.6
  ruby/rb-rake/Portfile
Labels: type: enhancement, type: update, maintainer: none

#15057 rb-google: update to 0.6.0
  ruby/rb-google/Portfile
Labels: type: enhancement, type: update, maintainer: none

#15049 py-wxutils: update to v0.2.6, support py310
  python/py-wxutils/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#15048 py-pyshortcuts: update to v1.8.2, support py310
  python/py-pyshortcuts/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#15026 py-orjson: Submission
  python/py-orjson/Portfile
Labels: type: submission

#15054 nss: fix ppc64 build
  net/nss/Portfile
  net/nss/files/patch-ppc64.diff
Labels: type: bugfix, maintainer: none

#14911 jemalloc: update to 5.3.0, fix PPC build
  devel/jemalloc/Portfile
  devel/jemalloc/files/exception-specification.patch
  devel/jemalloc/files/patch-quantum.diff
Labels: type: bugfix, type: enhancement, type: update, maintainer: none

#14958 privoxy-pki-bundle: Set the version and revision to match curl-ca-bundle
  www/privoxy/Portfile
Labels: maintainer, maintainer: open

#14969 safeclib: fix build for ppc and ppc64
  devel/safeclib/Portfile
  devel/safeclib/files/patch-perf_private.diff
Labels: type: bugfix, maintainer: open

#14944 ocaml-zarith: do not apply patch on PPC, it breaks build
  ocaml/ocaml-zarith/Portfile
Labels: type: bugfix, maintainer: open

#14933 libuv: fix ppc64 build on Leopard
  devel/libuv/Portfile
  devel/libuv/files/patch-atomic-ops.diff
Labels: type: bugfix, maintainer: open

#14993 vmips: update to 1.5.1
  emulators/vmips/Portfile
Labels: type: enhancement, type: update, maintainer: open

#14990 ddrescue: update to 1.26
  sysutils/ddrescue/Portfile
Labels: type: enhancement, type: update, maintainer: requires approval, maintainer: timeout, by: member

#15012 py-fabio: update to v 0.13.0, add py310 subport
  python/py-fabio/Portfile
Labels: type: enhancement, type: update, maintainer: open

#15061 gallery-dl: update to 1.22.1
  net/gallery-dl/Portfile
Labels: type: enhancement, type: update, maintainer: none

#15038 py-silx: update to v 1.0.0, add py310 subport
  python/py-silx/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#15024 py-me-al: Submission
  python/py-me-al/Portfile
Labels: type: submission

#15014 py-gradio: Submission
  python/py-gradio/Portfile
Labels: type: submission

#15067 jenv: update to 0.5.5
  java/jenv/Portfile
Labels: type: update, maintainer, maintainer: open

#15066 micronaut: update to 3.5.1
  java/micronaut/Portfile
Labels: type: update, maintainer, maintainer: open

#15065 groovy: update to 4.0.3
  lang/groovy/Portfile
Labels: type: update, maintainer, maintainer: open

#15064 py-wxmplot: update to v0.9.50, add py310 support
  python/py-wxmplot/Portfile
Labels: type: update, maintainer, maintainer: open

#14729 Remove py-isce2 port due to lack of users
  python/py-isce2/Portfile
  python/py-isce2/files/gcc_SconfigISCE
Labels: maintainer, maintainer: open

#14991 nhc98: update to 1.22, fix a broken build
  lang/nhc98/Portfile
  lang/nhc98/files/patch-Makefile.nhc98.diff
  lang/nhc98/files/patch-modern-gcc.diff
  lang/nhc98/files/patch-ppc.diff
Labels: type: bugfix, type: enhancement, type: update, maintainer: none

#15059 igraph: update to 0.9.9
  math/igraph/Portfile
Labels: type: update, maintainer, maintainer: open

#15070 syncthing: update to 1.20.1
  net/syncthing/Portfile
Labels: type: update, maintainer: open, by: member

#14859 yabai: update to version 4.0.0
  sysutils/yabai/Portfile
  sysutils/yabai/files/patch-makefile.diff
Labels: type: enhancement, type: update, maintainer: open

#15055 py-netaddr: add py310 subport
  python/py-netaddr/Portfile
Labels: type: enhancement, maintainer: open

#15062 py-xdg: update to 0.28.0
  python/py-xdg/Portfile
Labels: type: update, maintainer: open, by: member

#15074 gtkwave: update to 3.3.111
  cad/gtkwave/Portfile
Labels: type: update, maintainer: none, by: member

#15078 magic-wormhole: bump revision number to ensure new build
  net/magic-wormhole/Portfile
Labels: type: bugfix, maintainer: open

#15063 3proxy: update to 0.9.4
  net/3proxy/Portfile
Labels: type: update, type: security fix, maintainer: requires approval, by: member

#15060 darcs: update to 2.16.5
  devel/darcs/Portfile
Labels: type: update, maintainer: open, by: member

#15071 putty: update to 0.77
  security/putty/Portfile
  security/putty/files/patch-configure.diff
Labels: type: update, maintainer: none

#15068 ddrescue: fix compilation error related to std::exit
  sysutils/ddrescue/Portfile
  sysutils/ddrescue/files/patch-loggers.cc-cstdlib.diff
Labels: maintainer: requires approval, by: member

#15072 yabai: update to 4.0.1
  sysutils/yabai/Portfile
Labels: type: update, maintainer: open, by: member

#15087 google-cloud-sdk: update to 389.0.0
  devel/google-cloud-sdk/Portfile
Labels: type: update, maintainer, maintainer: open

#13306 qemu: use MacPorts smbd, as opposed to macOS version
  emulators/qemu/Portfile
Labels: maintainer: open

#15050 xraylib: use newer Perl variants
  science/xraylib/Portfile
Labels: type: enhancement, maintainer: none

#15090 Blades: update to 3.1.1
  www/blades/Portfile
Labels: type: enhancement, type: update, maintainer: open

#15091 redis: update to 7.0.1
  databases/redis/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#15095 logtalk: update to 3.56.0
  lang/logtalk/Portfile
Labels: type: update, maintainer

#15099 sfeed: update to 1.5
  net/sfeed/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#15098 cfiles: update to 1.8
  sysutils/cfiles/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#15075 vigra: add python 3.10; remove python 3.5 and 3.6; change default python to 3.10, to match boost
  graphics/vigra/Portfile
Labels: maintainer: requires approval, by: member

#15092 redis: only link libatomic on i386
  databases/redis/Portfile
Labels: type: enhancement, maintainer, maintainer: open

#15079 tilemaker: init at 2.2.0
  gis/tilemaker/Portfile
Labels: type: enhancement, type: submission

#15094 luajit-openresty: Update to 2.1-20220411
  lang/luajit-openresty/Portfile
Labels: type: update, maintainer: open, by: member

#15105 cmake-bootstrap: Backport a fix for find_library
  devel/cmake-bootstrap/Portfile
  devel/cmake-bootstrap/files/patch-Source-cmFindLibraryCommand.cxx.diff
Labels: type: bugfix, maintainer: none

#15104 rawtherapee: fix broken port due to source code unable to find GtkMacIntegration lib files
  graphics/rawtherapee/Portfile
  graphics/rawtherapee/files/FindGtkMacIntegration.cmake
Labels: type: bugfix, maintainer, maintainer: open

#15089 nhc98: enable tests
  lang/nhc98/Portfile
  lang/nhc98/files/patch-tests.diff
Labels: type: enhancement, maintainer: none

#15106 josm: update to 18463
  gis/JOSM/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#15109 clojure: update to 1.11.1.1119
  lang/clojure/Portfile
Labels: type: update, maintainer, maintainer: open

#15108 gopass: update to 1.14.3
  security/gopass/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#15110 kotlin: update to 1.7.0
  lang/kotlin/Portfile
Labels: type: update, maintainer, maintainer: open

#15056 rb-kramdown: update to 2.4.0
  ruby/rb-kramdown/Portfile
Labels: type: enhancement, type: update, maintainer: open

#15085 py-fabio: update to v0.14.0
  python/py-fabio/Portfile
Labels: type: update, maintainer: open

#15086 cppman: Use Python 3.10
  lang/cppman/Portfile
Labels: maintainer: open, by: member

#15102 libbluray: update to 1.3.1
  multimedia/libbluray/Portfile
Labels: type: update, maintainer: open, by: member

#15101 htop: update to 3.2.1
  sysutils/htop/Portfile
Labels: type: update, maintainer: open, by: member

#15118 wasmer: update to 2.3.0
  lang/wasmer/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#15116 maven3: update to 3.8.6
  java/maven3/Portfile
Labels: type: update, maintainer: none

#15119 checkssl: update to 0.4.0
  sysutils/checkssl/Portfile
Labels: type: update, maintainer, maintainer: open

#15122 godot: remove clang variants, always use `${configure.compiler}` to find the correct compiler
  games/godot/Portfile
  games/godot/files/configure-macports-compiler.diff
Labels: type: bugfix, type: enhancement, maintainer

#15121 rust: find correct static runtime library
  _resources/port1.0/group/rust-1.0.tcl
  lang/rust/Portfile
Labels: type: bugfix, maintainer, maintainer: open, by: member

#15107 catch2: update to 2.13.9
  devel/catch2/Portfile
Labels: type: update, maintainer: open, by: member

#15123 openldap: conditionally declare build dependency on groff
  databases/openldap/Portfile
Labels: type: bugfix, maintainer: open

#15124 lldb-14: add codesign shell script, and mention in notes
  lang/llvm-14/Portfile
Labels: maintainer: none, by: member

#15126 uxn: update to 20220613
  emulators/uxn/Portfile
  emulators/uxn/files/patch-stdin-thread.diff
  emulators/uxn/files/patch-uxn-build.diff
Labels: type: enhancement, type: update, maintainer, maintainer: open

#15132 fheroes2: update to 0.9.16
  games/fheroes2/Portfile
Labels: type: update, maintainer, maintainer: open

#15137 librsvg: allow build on Mac OS X Snow Leopard
  graphics/librsvg/Portfile
  graphics/librsvg/files/patch-libtool.diff
  graphics/librsvg/files/patch-no_objc.diff
Labels: type: enhancement, maintainer: open, by: member

#15141 mle: new port
  editors/mle/Portfile
Labels: type: enhancement, type: submission

#15146 clojure: update to 1.11.1.1129
  lang/clojure/Portfile
Labels: type: update, maintainer, maintainer: open

#15138 google-cloud-sdk: update to 390.0.0
  devel/google-cloud-sdk/Portfile
Labels: type: update, maintainer, maintainer: open

#15149 redis: update to 7.0.2
  databases/redis/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#15152 py-colorama: update to 0.4.5
  python/py-colorama/Portfile
Labels: type: enhancement, type: update, maintainer: none

#15154 checkssl: update to 0.4.1
  sysutils/checkssl/Portfile
Labels: type: update, maintainer, maintainer: open

#15127 gettext: disable csharp globally
  devel/gettext/Portfile
Labels: type: bugfix, type: enhancement, maintainer: requires approval, maintainer: timeout, by: member

#15128 hub: migrate to golang portgroup
  devel/hub/Portfile
Labels: type: bugfix, type: enhancement, maintainer: requires approval, maintainer: timeout, by: member

#15158 android-platform-tools: Update to 33.0.2
  java/android-platform-tools/Portfile
Labels: type: update, maintainer: open

#15155 py-mdtraj: update to 1.9.7
  python/py-mdtraj/Portfile
Labels: type: update, maintainer, maintainer: open

#15130 cfonts: update to 1.0.4
  textproc/cfonts/Portfile
Labels: type: bugfix, type: update, maintainer: open

#15156 wireshark3: update to 3.6.6
  net/wireshark3/Portfile
Labels: type: update, maintainer: requires approval, by: member

#15142 libutf8proc: Fix build with GCC 4.2
  textproc/libutf8proc/Portfile
  textproc/libutf8proc/files/remove-Wsign-conversion.diff
Labels: type: bugfix, maintainer: none

#15088 devel/nsis: Support building Nsis on macOS versions older than 10.15
  devel/nsis/Portfile
  devel/nsis/files/patch-halibut_for_osx_pre10_15.diff
Labels: type: bugfix, maintainer: none

#15163 HexFiend: Update to 2.16.0
  editors/HexFiend/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#15165 kiln: update to 0.3.1
  www/kiln/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#15168 checkssl: update to 0.4.3
  sysutils/checkssl/Portfile
Labels: type: update, maintainer, maintainer: open

#15170 openjdk-distributions: move openjdk11-openj9 to its own Portfile
  java/openjdk-distributions/Portfile
  java/openjdk11-openj9/Portfile
Labels: maintainer, maintainer: open

#15161 clojure: update to 1.11.1.1139
  lang/clojure/Portfile
Labels: type: update, maintainer, maintainer: open

#15151 py-s3transfer: update to 0.6.0
  python/py-s3transfer/Portfile
Labels: type: enhancement, type: update, maintainer: open

#15162 py-barnaba: python39 and 310, updated tests
  python/py-barnaba/Portfile
Labels: maintainer, maintainer: open

#15167 cmake: update to 3.23.2
  devel/cmake/Portfile
  devel/cmake/files/patch-cmake-leopard-tiger.diff
  devel/cmake/files/patch-qt5gui.diff
Labels: type: enhancement, type: update, maintainer, by: member

#15172 swi-prolog: Updated to version 8.4.3
  lang/swi-prolog/Portfile
Labels: type: update, maintainer, maintainer: open

#15178 micronaut: update to 3.5.2
  java/micronaut/Portfile
Labels: type: update, maintainer, maintainer: open

#15169 libidn: update to 1.40
  mail/libidn/Portfile
Labels: type: enhancement, type: update, maintainer: none

#15144 octave: octave 7.*'s GraphicsMagick configure option changed
  math/octave/Portfile
Labels: type: bugfix, maintainer: open

#15133 netcdf: update to 4.9.0
  science/netcdf/Portfile
Labels: type: update, maintainer: open

#15157 sshuttle: fix destroot error
  net/sshuttle/Portfile
Labels: type: bugfix, maintainer: open, by: member

#15160 libLASi: various minor fixes I stumbled across
  print/libLASi/Portfile
Labels: type: enhancement, maintainer: open, by: member

#15171 bingrep: new port
  textproc/bingrep/Portfile
Labels: type: submission

#15174 texlab: new port
  tex/texlab/Portfile
Labels: type: submission

#15175 typescript-language-server: new port
  devel/typescript-language-server/Portfile
Labels: type: submission

#15120 sslscan: update to 2.0.13
  net/sslscan/Portfile
Labels: type: update, maintainer: open

#15180 clojure: update to 1.11.1.1149
  lang/clojure/Portfile
Labels: type: update, maintainer, maintainer: open

#15182 google-cloud-sdk: use MacPorts Python
  devel/google-cloud-sdk/Portfile
Labels: type: enhancement, maintainer, maintainer: open

#15185 py-awscli, py-botocore, py-boto3: Update to 1.25.14, 1.27.14 and 1.24.14
  python/py-awscli/Portfile
  python/py-boto3/Portfile
  python/py-botocore/Portfile
Labels: type: update, maintainer: open

#15195 gcc-devel: fix --with-darwin-extra-rpath
  lang/gcc-devel/Portfile
Labels: type: bugfix, maintainer: none

#15196 fswatch: update to 1.17.0
  sysutils/fswatch/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#15189 pngcheck: update to 3.0.3
  graphics/pngcheck/Portfile
Labels: type: bugfix, type: update, type: security fix, maintainer: none

#15159 openconnect: update to version 9.01
  net/openconnect/Portfile
Labels: type: update, maintainer: none

#15190 dos2unix: update to 7.4.3
  textproc/dos2unix/Portfile
Labels: type: enhancement, type: update, maintainer: none

#15193 py-awscli2: update to version 2.7.10
  python/py-awscli2/Portfile
Labels: type: update, maintainer: open

#15083 xraylarch: update to v0.9.62, add py310
  python/py-xraylarch/Portfile
Labels: type: update, maintainer, maintainer: open

#15198 py-funcparserlib: update to 1.0.0
  python/py-funcparserlib/Portfile
Labels: type: update, maintainer: open

#15199 antlr4-cpp-runtime: update to 4.9.3
  lang/antlr4-cpp-runtime/Portfile
Labels: type: update, maintainer, maintainer: open, by: member
