Repository macports/macports-ports, pull requests merged in 2022-07, with the labels that each got.

#15248 pdf2djvu: rebuild against libpoppler.122
  graphics/pdf2djvu/Portfile
Labels: maintainer: open

#15246 minikube: correct platform for arm64 fix
  sysutils/minikube/Portfile
Labels: maintainer, maintainer: open, by: member

#15223 alglib: update to 3.19.0
  math/alglib/Portfile
Labels: type: update, maintainer: open, by: member

#15231 7zip: fix legacysupport linking on macOS 10.12 and older
  archivers/7zip/Portfile
Labels: type: enhancement, maintainer: open

#15253 pnpm: new port
  devel/pnpm/Portfile
Labels: type: submission

#15247 lagrange: update to 1.13.7
  net/lagrange/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#15220 git-secret: update to 0.5.0
  devel/git-secret/Portfile
Labels: type: update, maintainer: open

#15249 lean: update to v3.44.1
  math/lean/Portfile
Labels: type: update, maintainer, maintainer: open

#15242 wolfssl: use --enable-all with configure
  devel/wolfssl/Portfile
Labels: type: enhancement, maintainer, maintainer: open

#15251 nauty: update to 2.7r4
  math/nauty/Portfile
Labels: type: bugfix, type: update, maintainer, maintainer: open

#15252 dosbox-x: update to 0.84.1
  emulators/dosbox-x/Portfile
Labels: type: update, maintainer: none

#15201 vtk: drop qt4 variant, set GitHub handle for comaintainer
  graphics/vtk/Portfile
Labels: maintainer: open

#15254 openjdk-distributions: move openjdk11-graalvm to its own Portfile
  java/openjdk-distributions/Portfile
  java/openjdk11-graalvm/Portfile
Labels: maintainer, maintainer: open

#15257 openjdk-distributions: move openjdk11-corretto to its own Portfile
  java/openjdk-distributions/Portfile
  java/openjdk11-corretto/Portfile
Labels: maintainer, maintainer: open

#15259 Update Pari to 2.13.4
  math/pari/Portfile
Labels: type: update, maintainer, maintainer: open

#15261 pnpm: update to 7.5.0
  devel/pnpm/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#15262 nbtscan: update to 1.7.2
  security/nbtscan/Portfile
  security/nbtscan/files/debian-patches-04_fix_compiler_warnings.diff
  security/nbtscan/files/debian-patches-05_fix_off_by_one.diff
Labels: type: update, maintainer: none

#15250 libvpx-devel: install vpxdec/vpxenc executables
  multimedia/libvpx-devel/Portfile
  multimedia/libvpx-devel/files/patch-configure.sh.diff
Labels: type: enhancement, maintainer: open, by: member

#15268 turbogit: update to 4.0.0
  devel/turbogit/Portfile
Labels: type: update, maintainer, maintainer: open

#15215 64tass: Add new port
  devel/64tass/Portfile
Labels: type: enhancement, type: submission

#15272 doxygen-devel: drop +qt4 variant
  textproc/doxygen-devel/Portfile
Labels: maintainer: none

#15275 s5cmd: update to 2.0.0
  net/s5cmd/Portfile
Labels: type: update, maintainer: open, by: member

#15274 Gildas: update to 202207b
  science/gildas/Portfile
Labels: type: enhancement, type: update, maintainer

#15271 texlab: update to 4.2.0
  tex/texlab/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#15269 spring-boot-cli: update to 2.7.1
  java/spring-boot-cli/Portfile
Labels: type: update, maintainer, maintainer: open

#15267 dumpasn1: update to 20210212
  textproc/dumpasn1/Portfile
  textproc/dumpasn1/files/bug348856.patch
  textproc/dumpasn1/files/bug840771.patch
Labels: type: update, maintainer: none

#15266 ccrypt: update to 1.11
  security/ccrypt/Portfile
Labels: type: update, maintainer: none

#15273 orca: install examples and docs, add notes
  audio/orca/Portfile
Labels: type: enhancement, maintainer, maintainer: open

#15277 7zip: fix additional linking issues
  archivers/7zip/Portfile
Labels: type: enhancement, maintainer: open

#15278 got: update to portable release 0.73
  devel/got/Portfile
Labels: type: update, maintainer: none

#15279 libntlm: update to 1.6
  net/libntlm/Portfile
Labels: type: bugfix, type: update, type: security fix, maintainer: none

#15280 volatility: update to 2.6.1 and add modeline
  security/volatility/Portfile
Labels: type: update, maintainer: none

#15282 iperf3-devel: update to 20220630
  net/iperf3/Portfile
Labels: type: update, maintainer, maintainer: open

#15283 mysql57: update to 5.7.38
  databases/mysql57/Portfile
Labels: type: update, maintainer: none

#15255 apache-arrow: Fix checksum
  devel/apache-arrow/Portfile
Labels: type: bugfix, maintainer: none

#15240 gobject_introspection-1.0.tcl: fix meson options
  _resources/port1.0/group/gobject_introspection-1.0.tcl
Labels: type: bugfix

#15256 creduce: add variants llvm90, llvm11; auto-select llvm11 for Big Sur and later; migrate default to llvm 9
  devel/creduce/Portfile
  devel/creduce/files/patch-llvm-11.diff
Labels: maintainer: requires approval, maintainer: timeout, by: member

#15292 qt6-qtimageformats: add ninja build dep
  aqua/qt6/Portfile
Labels: type: bugfix, maintainer: none, by: member

#15287 goaccess: Use OpenSSL 3
  www/goaccess/Portfile
Labels: type: enhancement, maintainer: open, by: member

#15145 crossbinutils-1.0.tcl: bugfix 65348
  _resources/port1.0/group/crossbinutils-1.0.tcl
Labels: type: bugfix

#15297 kiln: update to 0.3.2
  www/kiln/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#15204 glade: enable gjs
  devel/glade/Portfile
Labels: type: enhancement, maintainer: open

#15296 orca: bump revision to rebuild packages
  audio/orca/Portfile
Labels: maintainer, maintainer: open

#15290 pdfid: update to 0.2.8
  security/pdfid/Portfile
Labels: type: update, maintainer: none

#15203 vcsn: set obsolete
  devel/vcsn/Portfile
Labels: maintainer: open, by: member

#15219 ffmpeg-devel: enable av1 support with aom/rav1e
  multimedia/ffmpeg-devel/Portfile
Labels: type: enhancement, maintainer: open, by: member

#15298 ffmpeg-devel: update to 4.4.2
  multimedia/ffmpeg-devel/Portfile
Labels: type: update, maintainer: open, by: member

#15302 ushare: remove obsolete port
  net/ushare/Portfile
Labels: maintainer: none

#15301 libidn: update to 1.41
  mail/libidn/Portfile
Labels: type: enhancement, type: update, maintainer: none

#15307 OpenIPMI: 2.0.33
  sysutils/OpenIPMI/Portfile
Labels: maintainer, maintainer: open, by: member

#15306 swi-prolog-devel: Updated to version 8.5.14
  lang/swi-prolog-devel/Portfile
Labels: type: update, maintainer, maintainer: open

#15304 ghostscript: update to 9.56.1
  print/ghostscript/Portfile
Labels: type: update, maintainer: none

#15303 cfonts: update to 1.1.0
  textproc/cfonts/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#15276 maddy: new port
  mail/maddy/Portfile
  mail/maddy/files/patch-build.sh.diff
Labels: type: submission, by: member

#15288 cargo, rust: Use OpenSSL 3
  devel/cargo/Portfile
  lang/rust/Portfile
Labels: type: enhancement, maintainer: open, by: member

#15299 moreutils: move to perl 5.34
  sysutils/moreutils/Portfile
Labels: type: enhancement, maintainer: open, by: member

#15312 stdman: update to 2022.02.01
  lang/stdman/Portfile
  lang/stdman/files/patch-install.diff
Labels: type: update, maintainer, maintainer: open

#15311 libstdcxx-docs: update to 12.1.0
  lang/libstdcxx-docs/Portfile
Labels: type: update, maintainer, maintainer: open

#15310 py-undetected-chromedriver: Update to version 3.1.5.post
  python/py-undetected-chromedriver/Portfile
  python/py-undetected-chromedriver/files/patch-undetected_chromedriver-__init__-py.diff
  python/py-undetected-chromedriver/files/patch-undetected_chromedriver-patcher-py.diff
Labels: type: update, maintainer: none

#15309 chromedriver: Update to version 103.0.5060.53
  www/chromedriver/Portfile
Labels: type: update, maintainer: open

#15286 create-dmg: new port
  sysutils/create-dmg/Portfile
Labels: type: submission, by: member

#15314 mozjs68: Remove mrustc requirement on 10.6
  lang/mozjs68/Portfile
Labels: type: bugfix, maintainer: none

#15039 trafshow: fix build
  net/trafshow/Portfile
Labels: type: bugfix, maintainer: none

#15294 cgal5: update to 5.4.1
  gis/cgal5/Portfile
Labels: type: bugfix, type: update, maintainer: requires approval, maintainer: timeout

#15317 GetPoints: remove obsolete port
  aqua/GetPoints/Portfile
Labels: maintainer: none

#15313 libmd: update to 1.0.4
  devel/libmd/Portfile
Labels: type: enhancement, type: update, maintainer: open

#15318 ki-shell: update to 0.5.2
  java/ki-shell/Portfile
Labels: type: update, maintainer, maintainer: open

#15323 fswatch: update to 1.17.1
  sysutils/fswatch/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#15148 docker-machine-driver-qemu: new port
  devel/docker-machine-driver-qemu/Portfile
Labels: type: submission

#15324 kotlin: update to 1.7.10
  lang/kotlin/Portfile
Labels: type: update, maintainer: open

#14952 mono: update to a newer version that builds on M1
  devel/mono/Portfile
  devel/mono/files/patch-aot-compiler-devel.c.diff
Labels: maintainer: open, by: member

#15316 inetutils: update to 2.3
  net/inetutils/Portfile
  net/inetutils/files/patch-telnet-telnet.c.diff
Labels: type: enhancement, type: update, maintainer: open

#15328 josm: update to 18513
  gis/JOSM/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#14976 mkvtoolnix 41.0: fix header error, enabled build for PPC
  multimedia/mkvtoolnix/Portfile
  multimedia/mkvtoolnix/files/patch-mm_text_io.diff
Labels: type: bugfix, maintainer: open

#15321 epy: new port (version 2022.4.18)
  python/epy/Portfile
Labels: type: enhancement, type: submission

#15293 hilite: new port
  sysutils/hilite/Portfile
Labels: type: enhancement, type: submission

#14831 qt5: update to 5.15.5
  aqua/qt5/Portfile
  aqua/qt5/files/patch-cve-2021-38593.diff
Labels: type: bugfix, type: update, maintainer: open

#15076 util-linux: include getopt
  devel/git-flow/Portfile
  devel/quilt/Portfile
  devel/util-linux/Portfile
  net/gnetcat/Portfile
  security/pass/Portfile
  sysutils/getopt/Portfile
  sysutils/getopt/files/patch-Makefile.diff
  sysutils/getopt/files/patch-gnu-getopt.c.diff
  textproc/rarian/Portfile
  textproc/xmlto/Portfile
  www/netrik/Portfile
Labels: type: enhancement, maintainer: open

#15315 mozjs91: Fix build on Snow Leopard
  lang/mozjs91/Portfile
  lang/mozjs91/files/patch-mozglue-snow-leopard.diff
Labels: type: bugfix, maintainer: none

#15241 nextcloud-client: update to 3.5.2
  www/nextcloud-client/Portfile
  www/nextcloud-client/files/patch-fix-build-pre-macos-11.diff
Labels: type: bugfix, type: enhancement, type: update, maintainer, maintainer: open

#15332 gnupg2: Update to 2.2.36
  mail/gnupg2/Portfile
Labels: type: update, type: security fix, maintainer: open, by: member

#15334 pnpm: update to 7.5.1
  devel/pnpm/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#15329 sbt: update to 1.7.1
  devel/sbt/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#15330 scala3.1: update to 3.1.3
  lang/scala3.1/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#15331 aerc: update to 0.11.0
  mail/aerc/Portfile
Labels: type: enhancement, type: update, maintainer: none

#15335 crystal: update to 1.5.0
  lang/crystal/Portfile
Labels: type: update, maintainer, maintainer: open

#15333 universal-ctags: update to 5.9.20220710.0
  devel/universal-ctags/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#15337 onedpl: update to 2021.7.0
  devel/onedpl/Portfile
Labels: type: update, maintainer, maintainer: open

#14808 unicorn: new port (v2.0.0)
  devel/unicorn/Portfile
Labels: type: enhancement, type: submission

#15322 gjs-devel: update to 1.72.1
  gnome/gjs-devel/Portfile
  gnome/gjs-devel/files/patch-gjs-gint64.diff
  gnome/gjs-devel/files/patch-gjs-gsize.diff
  gnome/gjs-devel/files/patch-gjs-meson_options.diff
  gnome/gjs-devel/files/patch-gjs-test.diff
Labels: type: update, maintainer: open

#15131 pdfgrep-legacy: make obsolete
  textproc/pdfgrep-legacy/Portfile
  textproc/pdfgrep/Portfile
Labels: maintainer: requires approval

#14963 poac: new port (version 0.3.7)
  sysutils/poac/Portfile
Labels: type: enhancement, type: submission

#15338 singular: update to 4.3.1
  math/singular/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#15340 qobuz-dl: update to 0.9.9.7
  net/qobuz-dl/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#15341 google-cloud-sdk: update to 393.0.0
  devel/google-cloud-sdk/Portfile
Labels: type: update, maintainer, maintainer: open

#15339 retdec-devel: update to 20220615
  devel/retdec/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#15342 py-soco: update to 0.28.0
  python/py-soco/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#15344 fheroes2: update to 0.9.17
  games/fheroes2/Portfile
Labels: type: update, maintainer, maintainer: open

#15352 py-ifaddr: update to 0.2.0
  python/py-ifaddr/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#15350 py-discogs-client: update to 2.3.15
  python/py-discogs-client/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#15348 imapdedup: update to 20230706
  mail/imapdedup/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#15346 gringo: remove obsolete port
  math/gringo/Portfile
Labels: maintainer: none

#15345 xdxf_makedict: remove obsolete port
  textproc/xdxf_makedict/Portfile
Labels: maintainer: none

#15343 py-pycryptodome{,x}: update to 3.15.0
  python/py-pycryptodome/Portfile
  python/py-pycryptodomex/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#15355 wolfssl: update to version 5.4.0
  devel/wolfssl/Portfile
Labels: type: update, maintainer, type: security fix, maintainer: open

#15225 macos-trash: new port
  sysutils/macos-trash/Portfile
Labels: type: enhancement, type: submission

#15358 ogre: update to 13.4.1
  graphics/ogre/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#14824 asio: update to 1.22.1
  devel/asio/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer: open

#14674 ghc-ppc-bootstrap: new port; latest release of GHC for PowerPC
  lang/ghc-ppc-bootstrap/Portfile
Labels: type: submission

#15361 libidn2: update to 2.3.3
  mail/libidn2/Portfile
  mail/libidn2/files/patch-clang-before-34.diff
Labels: type: enhancement, type: update, maintainer: open

#15319 xapian-omega: requires pcre2
  devel/xapian-core/Portfile
Labels: maintainer: open

#15359 libuv: update to 1.44.2
  devel/libuv/Portfile
  devel/libuv/files/patch-atomic-ops.diff
  devel/libuv/files/patch-libuv-legacy.diff
  devel/libuv/files/patch-no-libutil-on-Tiger.diff
Labels: type: enhancement, type: update, maintainer, maintainer: open, by: member

#15369 micronaut: update to 3.5.3
  java/micronaut/Portfile
Labels: type: update, maintainer, maintainer: open

#15368 cloc: update to version 1.94
  textproc/cloc/Portfile
Labels: type: update, maintainer: none

#15370 rizin: switch to github releases instead of archive
  devel/rizin/Portfile
Labels: type: enhancement, maintainer: open

#15327 mono: update to 6.12.0.182
  devel/mono/Portfile
  devel/mono/files/dynamic_lookup-11.patch
Labels: type: update, maintainer: open, by: member

#15374 gallery-dl: update to 1.22.4
  net/gallery-dl/Portfile
Labels: type: enhancement, type: update, maintainer: none

#15373 py-awscli2: update to 2.7.16
  python/py-awscli2/Portfile
  python/py-awscli2/files/patch-requirements.diff
Labels: type: enhancement, type: update, maintainer, maintainer: open

#15371 redis: update to 7.0.3
  databases/redis/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#15356 nco: update to 5.1.0
  science/nco/Portfile
Labels: type: update, maintainer, maintainer: open

#15379 ogre: update to 13.4.2
  graphics/ogre/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#15377 py-inflate64: update to 0.1.4
  python/py-inflate64/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#15376 py-flask: update to 2.1.3
  python/py-flask/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#15375 apache-ant: remove source variant
  devel/apache-ant/Portfile
Labels: maintainer: none

#15378 py-pick: update to 1.3.0
  python/py-pick/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#15380 poac: update to 0.3.8
  sysutils/poac/Portfile
Labels: type: update, maintainer, maintainer: open

#15363 libdbi{,-drivers}: add maintainer’s GitHub handle
  databases/libdbi-drivers/Portfile
  databases/libdbi/Portfile
Labels: maintainer: requires approval

#15365 moodss, moomps, mysqltcl: remove old ports
  databases/mysqltcl/Portfile
  net/moodss/Portfile
  net/moodss/files/patch-Makefile
  net/moomps/Portfile
  net/moomps/files/patch-moomps.sh
Labels: maintainer: none

#15367 akonadi: remove check for variant mysql5
  devel/akonadi/Portfile
Labels: maintainer: open

#15366 postfix: remove obsolete variant mysql55
  mail/postfix/Portfile
Labels: maintainer: open

#15382 tig: update to 2.5.6
  devel/tig/Portfile
Labels: type: update, maintainer: open

#15386 detekt-cli: update to 1.21.0
  java/detekt-cli/Portfile
Labels: type: update, maintainer, maintainer: open

#15384 auto-multiple-choice-devel : update to version 1.5.1-75-ge55d8e1e
  x11/auto-multiple-choice/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#15393 cedar: update to v. 2022.03.18
  textproc/cedar/Portfile
Labels: type: enhancement, type: update, maintainer: none

#15390 k9s: update to 0.26.0
  sysutils/k9s/Portfile
Labels: type: update, maintainer, maintainer: open

#15394 diffutils: fix a build on Rosetta
  sysutils/diffutils/Portfile
Labels: type: bugfix, maintainer: none

#15372 pipenv: update to 2022.7.4
  python/pipenv/Portfile
Labels: type: enhancement, type: update, maintainer: open

#15388 vtk: update to 9.1.0
  graphics/vtk/Portfile
  graphics/vtk/files/patch-FT_CALLBACK_DEF.diff
  graphics/vtk/files/patch-IOMovie-module.cmake.diff
  graphics/vtk/files/patch-pugixml.diff
  graphics/vtk/files/patch-python38-tp_print.diff
  graphics/vtk/files/patch-qpainter.diff
Labels: type: enhancement, type: update, maintainer: open

#15381 qt58, qt59, qt511, qt513, qt5: fix spelling in comment
  aqua/qt5/Portfile
  aqua/qt511/Portfile
  aqua/qt513/Portfile
  aqua/qt58/Portfile
  aqua/qt59/Portfile
Labels: maintainer: open

#15403 tmux: Update to 3.3a
  sysutils/tmux/Portfile
Labels: type: update, maintainer: open, by: member

#15400 tio: submission
  comms/tio/Portfile
Labels: type: submission

#15416 openjdk8-zulu: update to 8.64.0.15
  java/openjdk8-zulu/Portfile
Labels: type: update, maintainer, maintainer: open

#15411 openjdk8-corretto: update to 8.342.07.1
  java/openjdk-distributions/Portfile
Labels: type: update, maintainer, maintainer: open

#15410 openjdk11-corretto: update to 11.0.16.8.1
  java/openjdk11-corretto/Portfile
Labels: type: update, maintainer, maintainer: open

#15415 openjdk11-zulu: update to 11.58.15
  java/openjdk11-zulu/Portfile
Labels: type: update, maintainer, maintainer: open

#15417 openjdk15-zulu: update to 15.42.15
  java/openjdk15-zulu/Portfile
Labels: type: update, maintainer, maintainer: open

#15408 openjdk17-corretto: update to 17.0.4.8.1
  java/openjdk17-corretto/Portfile
Labels: type: update, maintainer, maintainer: open

#15414 openjdk18-zulu: update to 18.32.11
  java/openjdk18-zulu/Portfile
Labels: type: update, maintainer, maintainer: open

#15409 openjdk18-corretto: update to 18.0.2.9.1
  java/openjdk18-corretto/Portfile
Labels: type: update, maintainer, maintainer: open

#15413 openjdk17-zulu: update to 17.36.13
  java/openjdk17-zulu/Portfile
Labels: type: update, maintainer, maintainer: open
