Repository macports/macports-ports, pull requests merged in 2022-10, with the labels that each got.

#16264 liblo: update to 0.31
  audio/liblo/Portfile
  audio/liblo/files/dynamic_lookup-11.patch
Labels: type: bugfix, type: enhancement, type: update, maintainer: none

#16263 wolfssl: update to version 5.5.1
  devel/wolfssl/Portfile
Labels: type: update, maintainer, type: security fix, maintainer: open

#16268 openjdk18-temurin: obsolete, replaced by openjdk19-temurin
  java/openjdk18-temurin/Portfile
Labels: maintainer, maintainer: open

#16266 gallery-dl: update to 1.23.2
  net/gallery-dl/Portfile
Labels: type: enhancement, type: update, maintainer: none

#16265 gnome-radio: update to version 48.0
  gnome/gnome-radio/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#16269 ReadyMedia: update to 1.3.2
  net/ReadyMedia/Portfile
  net/ReadyMedia/files/patch-kqueue.diff
Labels: type: update, maintainer, maintainer: open

#16267 openjdk17-oracle: update replacement to openjdk19-oracle
  java/openjdk17-oracle/Portfile
Labels: type: enhancement, type: update, maintainer: none

#16256 iso-codes: update to python 3.10
  devel/iso-codes/Portfile
Labels: type: update, maintainer: open

#16271 nixpacks: update to v0.9.2
  devel/nixpacks/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#16272 datree: update to v1.6.36
  devel/datree/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#16278 py-awscli2: update to 2.8.0
  python/py-awscli2/Portfile
  python/py-awscli2/files/patch-requirements.diff
Labels: type: enhancement, type: update, maintainer, maintainer: open

#16275 sbt: update to 1.7.2
  devel/sbt/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#16276 universal-ctags: update to 5.9.20221002.0
  devel/universal-ctags/Portfile
  devel/universal-ctags/files/docutils.patch
Labels: type: bugfix, type: enhancement, type: update, maintainer, maintainer: open

#16280 beets-devel: update to 20221003
  audio/beets/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#16281 chromedriver: update to 106.0.5249.61
  www/chromedriver/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#16260 mesa: update to 22.1.7
  x11/mesa/Portfile
  x11/mesa/files/old-unused/0001-applegl-Provide-requirements-of-_SET_DrawBuffers.patch
  x11/mesa/files/old-unused/disable_shader_cache.patch
  x11/mesa/files/old-unused/mesa17-0001-glxcmds-Fix-a-typo-in-the-__APPLE__-codepath.patch
  x11/mesa/files/old-unused/mesa17-0002-glext.h-Add-missing-include-of-stddef.h-for-ptrdiff_.patch
  x11/mesa/files/old-unused/mesa17-0003-applegl-Provide-requirements-of-_SET_DrawBuffers.patch
  x11/mesa/files/old-unused/mesa17-0004-mesa-Deal-with-size-differences-between-GLuint-and-G.patch
  x11/mesa/files/old-unused/no-missing-prototypes-error.patch
  x11/mesa/files/old-unused/patch-Hack-to-address-build-failure-when-using-newer-macOS.patch
  x11/mesa/files/old-unused/patch-include-GL-mesa_glinterop_h.diff
  x11/mesa/files/old-unused/static-strndup.patch
  x11/mesa/files/patch-driver_extensions.diff
  x11/mesa/files/patch-meson-spec-python.diff
  x11/mesa/files/patch-pre-10.8-scandir.diff
Labels: type: enhancement, type: update, maintainer: open, by: member

#16279 py-hypothesis: update to 6.56.0
  python/py-hypothesis/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#16288 Gildas: update to 202210b
  science/gildas/Portfile
Labels: type: enhancement, type: update, maintainer

#16285 py-unidecode: update to 1.3.6; add myself as maintainer
  python/py-unidecode/Portfile
Labels: type: enhancement, type: update, maintainer: open

#16283 sn-demangler: update to 0.0.7
  devel/sn-demangler/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#16291 nixpacks: updated to version 0.9.3
  devel/nixpacks/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#16290 datree: updated to version 1.6.37
  devel/datree/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#16292 sfeed: update to 1.6
  net/sfeed/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#16294 t-rec: update to 0.7.5
  graphics/t-rec/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#16262 vtm: update to 0.9.0
  sysutils/vtm/Portfile
Labels: type: enhancement, type: update, maintainer: none

#16297 checkssl: update to 0.4.4
  sysutils/checkssl/Portfile
Labels: type: update, maintainer, maintainer: open

#16254 openjdk8: fix build on macOS 10.7
  java/openjdk8/Portfile
  java/openjdk8/files/0001-8181503-Can-t-compile-hotspot-with-c-11.patch
  java/openjdk8/files/0002-Support-XCode-3-14.patch
  java/openjdk8/files/0003-Ignore-__NSAutoreleaseNoPool-errors.patch
  java/openjdk8/files/0004-8030812-Change-the-solaris-DTrace-implementation-to-.patch
  java/openjdk8/files/0005-os_perf_bsd-allow-to-compile-with-ZERO-CPU.patch
  java/openjdk8/files/0006-Disable-C-11-warnings.patch
  java/openjdk8/files/0007-Added-macosx-bin-zero-jvm.cfg.patch
  java/openjdk8/files/0008-ExtendedOptionsImpl.c-define-TCP_KEEPINTVL-and-TCP_K.patch
  java/openjdk8/files/0009-Revert-8211301-macos-support-full-window-content-opt.patch
  java/openjdk8/files/patch-openjdk8-xcode.diff
Labels: type: enhancement, maintainer: open

#16296 google-cloud-sdk: update to 405.0.0
  devel/google-cloud-sdk/Portfile
Labels: type: update, maintainer, maintainer: open

#16306 openssh: update to version 9.1p1
  net/openssh/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer: none

#16305 libressl: update to version 3.6.0
  security/libressl/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer: requires approval

#16304 lens: update to 6.1.2
  sysutils/lens/Portfile
Labels: type: update, maintainer: open

#16299 jello: New port (version 1.5.4)
  sysutils/jello/Portfile
Labels: type: submission

#16302 swi-prolog-devel: Updated to version 8.5.18
  lang/swi-prolog-devel/Portfile
Labels: type: update, maintainer, maintainer: open

#16308 gawk: fix build for 10.5: do not use -no_pie ldflag
  lang/gawk/Portfile
Labels: type: bugfix, maintainer: open

#16309 p5-tcl-ptk: update to 1.10
  perl/p5-tcl-ptk/Portfile
Labels: type: update, maintainer, maintainer: open

#16076 legacysupport: do not use_mp_libcxx if we’re not building against libc++
  _resources/port1.0/group/legacysupport-1.1.tcl
Labels: type: bugfix

#16312 mold: new port (v1.5.1)
  devel/mold/Portfile
Labels: type: enhancement, type: submission

#16318 fricas: update to 1.3.8
  math/fricas/Portfile
Labels: type: update, maintainer

#16313 libmaxminddb: update to 1.7.1
  devel/libmaxminddb/Portfile
Labels: type: enhancement, type: update, maintainer: none

#16307 openjdk8: fixed a typo
  java/openjdk8/Portfile
Labels: maintainer: open

#16303 pipenv: update to 2022.10.4
  python/pipenv/Portfile
Labels: type: enhancement, type: update, maintainer: open

#16298 pnpm: update to 7.13.2
  devel/pnpm/Portfile
Labels: type: enhancement, type: update, maintainer: open

#16301 bcprov: update to 1.72
  java/bcprov/Portfile
Labels: type: update, maintainer: none

#16300 pdftk-java: requires Java 8 or later
  textproc/pdftk-java/Portfile
Labels: type: bugfix, maintainer: none

#16295 nim: update to 1.6.8
  lang/nim/Portfile
  lang/nim/files/patch-install.sh-1.6.4-shellquoting.diff
Labels: type: update, maintainer: open

#16321 ncdc: update to 1.23.1
  net/ncdc/Portfile
Labels: type: update, maintainer: none

#16314 portmidi: update to 2.0.4
  audio/portmidi/Portfile
  audio/portmidi/files/patch-pm_common-CMakeLists.txt.diff
  audio/portmidi/files/patch-pm_mac-pmmacosxcm.c.diff
  audio/portmidi/files/patch-pm_test-CMakeLists.txt.diff
Labels: type: enhancement, type: update, maintainer: none

#16324 doxygen: redirect_bins to fix malloc errors with gcc
  textproc/doxygen-devel/Portfile
  textproc/doxygen/Portfile
Labels: type: bugfix, maintainer: none

#16326 cpp-argparse-dev: update to 1.6.8
  devel/cpp-argparse-dev/Portfile
Labels: type: update, maintainer

#16331 lens: update to 6.1.10
  sysutils/lens/Portfile
Labels: type: update, maintainer, maintainer: open

#16328 mvnd: update to 0.8.2
  java/mvnd/Portfile
Labels: type: update, maintainer, maintainer: open

#16327 fheroes2: update to 0.9.20
  games/fheroes2/Portfile
Labels: type: update, maintainer, maintainer: open

#16338 universal-ctags: update to 5.9.20221009.0
  devel/universal-ctags/Portfile
  devel/universal-ctags/files/docutils.patch
Labels: type: enhancement, type: update, maintainer, maintainer: open

#16337 giter8: update to 0.16.0
  devel/giter8/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#16336 py-hypothesis: update to 6.56.2
  python/py-hypothesis/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#16335 py-discogs-client: update to 2.5
  python/py-discogs-client/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#16315 vtm: update to 0.9.2
  sysutils/vtm/Portfile
Labels: type: enhancement, type: update, maintainer: none

#16341 dbeaver-community: update to version 22.2.2
  databases/dbeaver-community/Portfile
Labels: type: update, maintainer: open

#16344 nixpacks: update to version 0.10.2
  devel/nixpacks/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#16346 scala2.13: update to 2.13.10
  lang/scala/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#15263 lang/sbcl: update to sbcl-2.2.9
  lang/sbcl/Portfile
  lang/sbcl/files/patch-config-darwin-arm64.diff
  lang/sbcl/files/patch-config-darwin-x86_64.diff
  math/maxima/Portfile
Labels: type: update, maintainer: open, wip

#16351 lazarus: update to newer upstream version (2.2.4)
  devel/lazarus/Portfile
  devel/lazarus/files/noGUI-Printer.patch
Labels: type: update, maintainer, maintainer: open

#16350 tippecanoe: update to 2.9.0
  gis/tippecanoe/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#16349 igraph: update to 0.10.2
  math/igraph/Portfile
Labels: type: update, maintainer, maintainer: open

#16319 add p5-file-flock-tiny (File::Flock::Tiny) v0.14
  perl/p5-file-flock-tiny/Portfile
Labels: type: enhancement, type: submission

#16339 cmake +python27: Does not build, so remove option
  devel/cmake-devel/Portfile
  devel/cmake/Portfile
Labels: type: bugfix, maintainer: requires approval, maintainer: timeout

#16342 MoarVM, nqp, rakudo: use legacysupport.redirect_bins to fix malloc errors
  lang/MoarVM/Portfile
  lang/nqp/Portfile
  lang/rakudo/Portfile
Labels: type: bugfix, maintainer: open

#16353 nixpacks: update to v0.10.3
  devel/nixpacks/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#16369 groovy: update to 4.0.6
  lang/groovy/Portfile
Labels: type: update, maintainer, maintainer: open

#16323 py-nbconvert: update to 7.2.1
  python/py-nbconvert/Portfile
Labels: type: bugfix, type: update, maintainer: open

#16370 universal-ctags: update to 5.9.20221016.0
  devel/universal-ctags/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#16363 hlint: Update to version 3.5
  devel/hlint/Portfile
Labels: type: update, maintainer: none

#16365 gallery-dl: update to 1.23.3
  net/gallery-dl/Portfile
Labels: type: update, maintainer: none

#16366 vtm: update to 0.9.6
  sysutils/vtm/Portfile
Labels: type: update, maintainer: none

#16362 bitwarden-cli: update to 2022.10.0
  security/bitwarden-cli/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#16287 zlib: fix CVE-2022-37434
  archivers/zlib/Portfile
  archivers/zlib/files/patch-CVE-2022-37434.patch
Labels: type: security fix, maintainer: open

#16380 gnupg2: update to 2.2.40
  mail/gnupg2/Portfile
  mail/gnupg2/files/patch-fix-use-ldap.diff
Labels: type: update, type: security fix, maintainer: open

#16361 tcpflow: update to 1.6.1
  net/tcpflow/Portfile
  net/tcpflow/files/patch-configure.ac.diff
Labels: type: enhancement, type: update, maintainer: none

#16377 gcc10-bootstrap: displays output when extracing files only on debug
  lang/gcc10-bootstrap/Portfile
Labels: type: bugfix, maintainer, maintainer: open

#16357 go-task: update to 3.17.0
  devel/go-task/Portfile
Labels: type: update, maintainer: open, by: member

#16382 miniflux: update to 2.0.39
  net/miniflux/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#16374 py-igraph: update to 0.10.2
  python/py-igraph/Portfile
Labels: type: update, maintainer, maintainer: open

#16388 swi-prolog-devel: Updated to version 8.5.20
  lang/swi-prolog-devel/Portfile
Labels: type: update, maintainer, maintainer: open

#16101 libnet: rename libnet11 to libnet and update
  games/snoopy/Portfile
  games/snoopy/files/patch-brain.c.diff
  net/angst/Portfile
  net/angst/files/Makefile.patch
  net/arping/Portfile
  net/cdpd/Portfile
  net/cdpd/files/patch-Makefile.in
  net/dnsa/Portfile
  net/dsniff/Portfile
  net/dsniff/files/patch-Makefile.in.diff
  net/dsniff/files/patch-arp.c.diff
  net/dsniff/files/patch-arpspoof.c.diff
  net/dsniff/files/patch-buf.c.diff
  net/dsniff/files/patch-configure.diff
  net/dsniff/files/patch-dnsspoof.c.diff
  net/dsniff/files/patch-filesnarf.c.diff
  net/dsniff/files/patch-macof.c.diff
  net/dsniff/files/patch-pcaputil.c.diff
  net/dsniff/files/patch-pcaputil.h.diff
  net/dsniff/files/patch-record.c.diff
  net/dsniff/files/patch-ssh.c.diff
  net/dsniff/files/patch-sshcrypto.c.diff
  net/dsniff/files/patch-sshmitm.c-redef-of-csin.diff
  net/dsniff/files/patch-sshmitm.c.diff
  net/dsniff/files/patch-sshow.c.diff
  net/dsniff/files/patch-tcp_raw.c.diff
  net/dsniff/files/patch-tcp_raw.h.diff
  net/dsniff/files/patch-tcpkill.c.diff
  net/dsniff/files/patch-tcpnice.c.diff
  net/dsniff/files/patch-trigger.c.diff
  net/dsniff/files/patch-trigger.h.diff
  net/dsniff/files/patch-urlsnarf.c.diff
  net/dsniff/files/patch-webmitm.c-redef-of-csin.diff
  net/dsniff/files/patch-webmitm.c.diff
  net/dsniff/files/patch-webspy.c.diff
  net/ettercap/Portfile
  net/fragrouter/Portfile
  net/libipgeo/Portfile
  net/libnet/Portfile
  net/libnet/files/patch-Makefile
  net/libnet/files/patch-configure
  net/libnet/files/patch-configure.in.diff
  net/libnet/files/patch-include-libnet.h
  net/libnet/files/patch-include__libnet__libnet-headers.h
  net/libnet11/Portfile
  net/libnids/Portfile
  net/nemesis/Portfile
  net/netwib/Portfile
  net/packetforward/Portfile
  net/packetforward/files/patch-Makefile.diff
  net/packit/Portfile
  net/tcptraceroute/Portfile
  net/yersinia/Portfile
  sysutils/syslog-ng/Portfile
  sysutils/syslog-ng/files/patch-src-Makefile.in.diff
Labels: maintainer: requires approval, maintainer: timeout, by: member

#16371 R-app: restore support for older systems and PPC
  math/R-app/Portfile
Labels: type: bugfix, type: enhancement, maintainer: open

#16395 fricas: revbump for sbcl update
  math/fricas/Portfile
Labels: maintainer

#16386 google-cloud-sdk: update to 406.0.0
  devel/google-cloud-sdk/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#16400 micronaut: update to 3.7.2
  java/micronaut/Portfile
Labels: type: update, maintainer, maintainer: open

#16397 openjdk19-oracle: update to 19.0.1
  java/openjdk19-oracle/Portfile
Labels: type: update, maintainer, maintainer: open

#16396 jdk17: update to 17.0.5
  java/jdk17/Portfile
Labels: type: update, maintainer, maintainer: open

#16393 py-awscli2: update to 2.8.3
  python/py-awscli2/Portfile
  python/py-awscli2/files/patch-requirements.diff
Labels: type: enhancement, type: update, maintainer, maintainer: open

#16391 coreutils-uutils: update to 0.0.16
  sysutils/coreutils-uutils/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#16389 logtalk: update to 3.59.0
  lang/logtalk/Portfile
Labels: type: update, maintainer

#16356 mint: update to 0.17.2, add universal variant
  devel/mint/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer, maintainer: open

#16354 stack: Update to version 2.9.1
  lang/stack/Portfile
Labels: type: update, maintainer, maintainer: open

#16399 KeePassXC-devel: upgrade to latest commit of 2.7.x branch
  security/KeePassXC/Portfile
  security/KeePassXC/files/devel/patch-no-findpackage-path.diff
Labels: maintainer: none

#16368 OSXPal: remove obsolete port
  aqua/OSXPal/Portfile
Labels: maintainer: none

#16352 libraw: enable X3F support
  graphics/libraw/Portfile
Labels: maintainer: none

#16390 meson: update to 0.63.3
  devel/meson/Portfile
Labels: type: enhancement, type: update, maintainer: open

#16401 openjdk19-zulu: update to 19.30.11
  java/openjdk19-zulu/Portfile
Labels: type: update, maintainer, maintainer: open

#16402 openjdk17-zulu: update to 17.38.21
  java/openjdk17-zulu/Portfile
Labels: type: update, maintainer, maintainer: open

#16403 openjdk11-zulu: update to 11.60.19
  java/openjdk11-zulu/Portfile
Labels: type: update, maintainer, maintainer: open

#16404 openjdk8-zulu: update 8.66.0.15
  java/openjdk8-zulu/Portfile
Labels: type: update, maintainer, maintainer: open

#16406 yq: update to 4.28.2
  textproc/yq/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#16405 openjdk{8,16}-graalvm: remove previously obsoleted ports
  java/openjdk16-graalvm/Portfile
  java/openjdk8-graalvm/Portfile
Labels: maintainer: none

#16385 mplayer: update to 1.5
  multimedia/MPlayer/Portfile
  multimedia/MPlayer/files/configure.vorbis.patch
  multimedia/MPlayer/files/configure.x11.patch
  multimedia/MPlayer/files/llvm-gcc-workaround.patch
  multimedia/MPlayer/files/patch-configure-arm64.diff
  multimedia/MPlayer/files/patch-libvo-osx-objc-common-opengl-headers.diff
  multimedia/MPlayer/files/patch-mplayer-libx264-updated.diff
Labels: type: bugfix, type: enhancement, type: update, maintainer: open, by: member

#16425 mplayer-devel: update to 38405
  multimedia/MPlayer/Portfile
  multimedia/mplayer-devel/Portfile
  multimedia/mplayer-devel/files/configure.vorbis.patch
  multimedia/mplayer-devel/files/configure.x11.patch
Labels: type: update, maintainer: requires approval, by: member

#16423 openjdk13-zulu: update to 13.52.15
  java/openjdk13-zulu/Portfile
Labels: type: update, maintainer, maintainer: open

#16422 openjdk15-zulu: update to 15.44.13
  java/openjdk15-zulu/Portfile
Labels: type: update, maintainer, maintainer: open

#16414 openjdk11-corretto: update to 11.0.17.8.1
  java/openjdk11-corretto/Portfile
Labels: type: update, maintainer, maintainer: open

#16413 openjdk17-corretto: update to 17.0.5.8.1
  java/openjdk17-corretto/Portfile
Labels: type: update, maintainer, maintainer: open

#16412 openjdk19-corretto: update to 19.0.1.10.1
  java/openjdk19-corretto/Portfile
Labels: type: update, maintainer, maintainer: open

#16410 openjdk17-sap: update to 17.0.5
  java/openjdk17-sap/Portfile
Labels: type: update, maintainer, maintainer: open

#16411 openjdk11-sap: update to 11.0.17
  java/openjdk11-sap/Portfile
Labels: type: update, maintainer, maintainer: open

#16409 openjdk19-sap: update to 19.0.1
  java/openjdk19-sap/Portfile
Labels: type: update, maintainer, maintainer: open

#16420 ld64: default to ld64-97 for all PPC
  devel/ld64/Portfile
Labels: type: bugfix, maintainer: requires approval

#16418 libraw: fix universal variant
  graphics/libraw/Portfile
Labels: maintainer: none

#16426 icu-devel: update to 72.1
  devel/icu-devel/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#16416 openjdk8-corretto: update to 8.352.08.1
  java/openjdk8-corretto/Portfile
Labels: type: update, maintainer, maintainer: open

#16387 zlib: update to 1.2.13
  archivers/zlib/Portfile
  archivers/zlib/files/patch-CVE-2022-37434.patch
  archivers/zlib/files/patch-cc-logic.patch
  archivers/zlib/files/patch-crc-functions.patch
Labels: type: update, maintainer: open

#16340 py-httpx: added missed dependencies and select port
  python/httpx_select/Portfile
  python/httpx_select/files/base
  python/httpx_select/files/none
  python/py-httpx/Portfile
  python/py-httpx/files/py310-httpx
  python/py-httpx/files/py37-httpx
  python/py-httpx/files/py38-httpx
  python/py-httpx/files/py39-httpx
Labels: type: enhancement, type: submission, maintainer, maintainer: open

#16364 ihaskell: Update to version 20221009
  devel/ihaskell/Portfile
Labels: type: update, maintainer: none

#16431 icu-devel: fix build on 10.6
  devel/icu-devel/Portfile
  devel/icu-devel/files/patch-cinttypes-header.diff
Labels: type: bugfix, maintainer, maintainer: open

#16435 nixpacks: update to v0.10.5
  devel/nixpacks/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#16436 datree: update to v1.6.40
  devel/datree/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#16359 gflags: blacklist gcc-4.0, fixes build on 10.5.8
  devel/gflags/Portfile
Labels: type: bugfix, maintainer: none

#16378 cdo: update to 2.1.0
  science/cdo/Portfile
  science/cdo/files/patch-cdo-2.0.6-missing-include.diff
  science/cdo/files/patch-skip-Multiyearstat-yseas-test.diff
Labels: type: update, maintainer: open

#16330 terragrunt: update to 0.39.2
  sysutils/terragrunt/Portfile
Labels: type: update, maintainer: open

#16443 kiln: update to 0.4.0
  www/kiln/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#16441 vnstat: update to 2.10
  net/vnstat/Portfile
Labels: type: update, maintainer: none

#16440 aerc: update to 0.13.0
  mail/aerc/Portfile
Labels: type: enhancement, type: update, maintainer: none

#16439 skaffold: update to 2.0.0
  devel/skaffold/Portfile
Labels: type: update, maintainer, maintainer: open

#16433 cpp-argparse-dev: update to 1.7.0
  devel/cpp-argparse-dev/Portfile
Labels: type: update, maintainer

#16437 rmlint: blacklist old Apple clang of 10.6.8
  sysutils/rmlint/Portfile
Labels: type: bugfix, maintainer: open

#16430 mint: fix minimum Xcode version
  devel/mint/Portfile
Labels: type: bugfix, maintainer, maintainer: open

#16442 mold: update to 1.6.0
  devel/mold/Portfile
Labels: type: update, maintainer, maintainer: open

#16445 cmake-devel: fix a build error on 10.6: undefined _posix_spawn_file_actions_addinherit_np
  devel/cmake-devel/Portfile
  devel/cmake-devel/files/patch-uv_spawn.diff
Labels: type: bugfix, maintainer: requires approval

#16451 VisualVM: update to 2.1.5
  java/VisualVM/Portfile
Labels: type: update, maintainer, maintainer: open

#16450 dbvis: update to 14.0.1
  databases/dbvis/Portfile
Labels: type: update, maintainer, maintainer: open

#16448 git-town: update to version 7.8.0
  devel/git-town/Portfile
Labels: type: update, maintainer: open

#16455 dzip: use legacysupport PG
  archivers/dzip/Portfile
Labels: type: bugfix, maintainer: none

#16456 jdupes: update to 1.21.0
  sysutils/jdupes/Portfile
  sysutils/jdupes/files/makefile-fix-compiler-options.patch
Labels: type: update, maintainer, maintainer: open

#16428 go-tools: update to 0.2.0
  devel/go-tools/Portfile
Labels: type: update, maintainer: open, by: member

#16421 istioctl: update to 1.15.2
  sysutils/istioctl/Portfile
Labels: type: update, maintainer: open

#16345 crystal: update to 1.6.0
  lang/crystal/Portfile
Labels: type: enhancement, type: update, maintainer: open

#16348 llvm-5.0: correct patch-include-orc syntax
  lang/llvm-5.0/files/patch-include-orc.diff
Labels: type: bugfix, maintainer: requires approval, maintainer: timeout

#16320 mdds: update to 2.0.3
  devel/mdds/Portfile
Labels: type: enhancement, type: update, maintainer: open

#16458 gq: fix the broken port
  net/gq/Portfile
  net/gq/files/patch-ldap.h.diff
Labels: type: bugfix, maintainer: none

#16457 KeePassXC-devel: fix compilation on macOS <= 10.10
  security/KeePassXC/Portfile
  security/KeePassXC/files/devel/patch-touch-id.diff
Labels: type: bugfix, maintainer: none

#16449 doxygen: Update to version 1.9.5
  textproc/doxygen/Portfile
  textproc/doxygen/files/doxywizard.patch
Labels: type: enhancement, type: update, maintainer: none
