Repository macports/macports-ports, pull requests merged in 2022-12, with the labels that each got.

#16863 soplex: prevent linking against libquadmath
  math/soplex/Portfile
Labels: type: bugfix, maintainer, maintainer: open

#16861 beets-full: fix mirroring
  audio/beets/Portfile
Labels: type: bugfix, maintainer, maintainer: open

#16855 ntpsec: Fix build failure with clang 14.
  sysutils/ntpsec/Portfile
  sysutils/ntpsec/files/patch-allfixes.diff
Labels: type: bugfix, maintainer, maintainer: open

#16719 py-pandas: blacklist clang < 600
  python/py-pandas/Portfile
Labels: type: enhancement, maintainer: open

#16829 mail-server: Update to version 1.5
  mail/mail-server/Portfile
  mail/mail-server/files/prefix/etc/certificates/ca/openssl.cnf
  mail/mail-server/files/prefix/etc/dovecot/conf.d/10-ssl.conf
  mail/mail-server/files/prefix/etc/logrotate.d/mail
  mail/mail-server/files/prefix/etc/postfix/main.cf
Labels: maintainer, maintainer: open

#16806 mpfr: update to 4.1.1
  devel/mpfr/Portfile
Labels: type: update, maintainer: open

#16873 Gildas: update to 202212a
  science/gildas/Portfile
  science/gildas/files/patch-admin-Makefile.python.diff
  science/gildas/files/patch-admin-gildas-env.sh.diff
Labels: type: enhancement, type: update, maintainer

#16419 Submission of py-rawpy
  python/py-rawpy/Portfile
  python/py-rawpy/files/setup.py.diff
Labels: type: submission

#16871 snac: new Portfile for a minimalistic ActivityPub instance in C.
  net/snac/Portfile
  net/snac/files/Makefile.patch
Labels: type: enhancement, type: submission

#16749 i2pd: new port, C++ implementation of i2p
  security/i2pd/Portfile
  security/i2pd/files/0001-i2pd.conf-adjust-for-MacPorts.patch
Labels: type: submission

#16881 py-spacy: Update to version 3.4.3
  python/py-spaCy/Portfile
Labels: type: update, maintainer: none

#16877 dnscontrol: update to 3.23.0
  sysutils/dnscontrol/Portfile
Labels: type: update, maintainer, maintainer: open

#16879 vtm: update to 0.9.6k
  sysutils/vtm/Portfile
Labels: type: update, maintainer: none

#16852 gopass-summon-provider: update to 1.14.11
  devel/gopass-summon-provider/Portfile
Labels: type: enhancement, type: update, maintainer: open

#16841 fossil: update to 2.20
  devel/fossil/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer: requires approval, maintainer: timeout

#16882 git-lfs: update to 3.3.0
  devel/git-lfs/Portfile
Labels: type: update, maintainer: open, by: member

#16880 openiked: update to version 7.2.
  net/openiked/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer: open

#16681 libevent: Add upstream patch for libressl
  devel/libevent/Portfile
  devel/libevent/files/patch-libressl-compat.diff
Labels: type: bugfix, maintainer, maintainer: open

#16867 tiff: apply patch for CVE-2022-3970
  graphics/tiff/Portfile
  graphics/tiff/files/CVE-2022-3970.patch
Labels: type: security fix, maintainer: open, by: member

#16840 youtube-dl: add python311 variant
  net/youtube-dl/Portfile
Labels: type: enhancement, maintainer: requires approval, maintainer: timeout

#16884 datree: updated to version 1.8.8
  devel/datree/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#16883 sketchybar: update to version 2.11.2
  sysutils/sketchybar/Portfile
  sysutils/sketchybar/files/org.macports.sketchybar.plist
Labels: type: enhancement, type: update, maintainer, maintainer: open

#16859 terragrunt: upgrade to 0.42.2
  sysutils/terragrunt/Portfile
Labels: maintainer: open

#16886 skaffold: update to 2.0.3
  devel/skaffold/Portfile
Labels: type: update, maintainer, maintainer: open

#16641 py-more-itertools: update to 9.0.0; add py311
  python/py-more-itertools/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer: open

#16895 snac: update to version 2.13
  net/snac/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#16896 Scan manfix
  net/snac/Portfile
  net/snac/files/Makefile.patch
Labels: maintainer: open, by: member

#16885 mail-server: Fix sha1 case regex in certificate filename
  mail/mail-server/Portfile
Labels: type: bugfix, maintainer, maintainer: open

#16892 autorestic: update to 1.7.4
  sysutils/autorestic/Portfile
Labels: type: update, maintainer: open, by: member

#16900 mint: update to 0.17.4
  devel/mint/Portfile
Labels: type: bugfix, type: update, maintainer, maintainer: open

#16808 libptytty: set cxx_standard 11, fixes build on old systems
  devel/libptytty/Portfile
Labels: type: bugfix, maintainer: open

#16903 tcsh: update to 6.24.05
  shells/tcsh/Portfile
Labels: type: update, maintainer: none

#16905 py-subprocess-tee: Add patch for update deps
  python/py-subprocess-tee/Portfile
  python/py-subprocess-tee/files/patch-update-deps.diff
Labels: maintainer, maintainer: open, by: member

#16910 go: update to 1.19.4
  lang/go/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#16911 go-tools: update to 0.4.0
  devel/go-tools/Portfile
Labels: type: update, maintainer: open, by: member

#16907 swi-prolog-devel: Updated to version 9.1.1
  lang/swi-prolog-devel/Portfile
Labels: type: update, maintainer, maintainer: open

#16906 swi-prolog: Updated to version 9.0.2
  lang/swi-prolog/Portfile
Labels: type: update, maintainer, maintainer: open

#16904 vtm: update to 0.9.7b
  sysutils/vtm/Portfile
Labels: type: update, maintainer: none

#16908 glab: update to 1.24.1
  devel/glab/Portfile
Labels: type: enhancement, type: update, maintainer: open

#16343 freeglut: add xorg-libXi dependency
  x11/freeglut/Portfile
Labels: type: bugfix, maintainer: open, by: member

#16914 google-cloud-sdk: update to 411.0.0
  devel/google-cloud-sdk/Portfile
Labels: type: update, maintainer, maintainer: open

#16860 Obsession: new port: Qt-based Hotline client
  www/Obsession/Portfile
Labels: type: submission

#16921 tnylpo: update to 1.1.4
  emulators/tnylpo/Portfile
Labels: type: update, maintainer, maintainer: open

#16874 py-prompt_toolkit: update to 3.0.33
  python/py-prompt_toolkit/Portfile
Labels: type: enhancement, type: update, maintainer: open

#16837 boost*: add python311 variant
  devel/boost171/Portfile
  devel/boost176/Portfile
  devel/boost177/Portfile
  devel/boost178/Portfile
  devel/boost179/Portfile
  devel/boost180/Portfile
Labels: type: enhancement, maintainer: open

#16853 spacebar: new port
  sysutils/spacebar/Portfile
  sysutils/spacebar/files/org.macports.spacebar.plist
  sysutils/spacebar/files/patch-makefile.diff
  sysutils/spacebar/files/patch-src__event_loop.c.diff
Labels: type: enhancement, type: submission

#16902 libdeflate: update to 1.15
  archivers/libdeflate/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#16925 dbeaver-community: update to version 22.3.0
  databases/dbeaver-community/Portfile
Labels: type: update, maintainer: open

#16924 net/wireshark4: rev bump to 4.0.2
  net/wireshark4/Portfile
Labels: maintainer, by: member

#16917 nco: update to 5.1.3
  science/nco/Portfile
Labels: type: update, maintainer, maintainer: open

#16929 snac: update to version 2.14.
  net/snac/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer, maintainer: open

#16919 go-devel: update to 1.20rc1
  lang/go/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#16932 astrolog: new port (version 7.50)
  games/astrolog/Portfile
Labels: type: submission, by: member

#16926 dokku-client: new port
  sysutils/dokku-client/Portfile
Labels: type: enhancement, type: submission

#16928 Gildas: update to 202212b
  science/gildas/Portfile
Labels: type: bugfix, type: update, maintainer

#16918 ecCodes: update to 2.27.1
  science/ecCodes/Portfile
Labels: type: update, maintainer, maintainer: open

#16923 cppcheck: use newer gmake on Tiger, fix CXXFLAGS
  devel/cppcheck/Portfile
Labels: type: bugfix, maintainer: open, by: member

#16854 emacs{-app,}-devel: update to 20221128
  editors/emacs/Portfile
Labels: type: update, maintainer: open, by: member

#16940 phetch: update to 1.2.0
  net/phetch/Portfile
Labels: type: update, maintainer, maintainer: open

#16936 hiredis: update to 1.1.0
  databases/hiredis/Portfile
Labels: type: update, maintainer: none

#16930 libmpc: update to 1.3.0
  devel/libmpc/Portfile
Labels: type: update, maintainer: none

#16942 git: update to 2.38.2
  devel/git/Portfile
  devel/git/files/patch-git-older-gcc-deprecated.diff
Labels: type: update, maintainer, maintainer: open, by: member

#16912 netgen: update to 6.2.2204
  math/netgen/Portfile
  math/netgen/files/patch-CMakeLists.txt.diff
  math/netgen/files/patch-MacPorts-rpath.diff
  math/netgen/files/patch-cmake-version.diff
  math/netgen/files/patch-link-agains-ffmpeg.diff
  math/netgen/files/patch-link-ng.diff
  math/netgen/files/patch-no-console.diff
  math/netgen/files/patch-no-external.diff
  math/netgen/files/patch-no-pybind.diff
  math/netgen/files/patch-propagate_c_compiler.diff
Labels: type: enhancement, type: update, maintainer: open

#16943 ccache: bump revision for hiredis update
  devel/ccache/Portfile
Labels: maintainer: open

#16949 giter8: update to 0.16.1
  devel/giter8/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#16948 ecgen: update to 0.7.7
  math/ecgen/Portfile
  math/ecgen/files/old-macos.patch
Labels: type: enhancement, type: update, maintainer, maintainer: open

#16947 py-awscli2: update to 2.9.6
  python/py-awscli2/Portfile
  python/py-awscli2/files/patch-requirements.diff
Labels: type: enhancement, type: update, maintainer, maintainer: open

#16935 retdec: update to 5.0; retdec-devel: update to 20221208
  devel/retdec/Portfile
  devel/retdec/files/cmake-libtool-v4.0.diff
  devel/retdec/files/patch-hardcoded-make-devel.diff
  devel/retdec/files/patch-hardcoded-make-v40.diff
  devel/retdec/files/patch-python3.diff
  devel/retdec/files/patch-system-openssl.diff
  devel/retdec/files/patch-yara-syntax-error.diff
  devel/retdec/files/yara-inherits-linker-flags-v40.diff
  devel/retdec/files/yaramod-python.diff
Labels: type: enhancement, type: update, maintainer, maintainer: open

#16950 ecgen: fix build on old macOS
  math/ecgen/files/old-macos.patch
Labels: type: bugfix, maintainer, maintainer: open

#16938 irrlichtmt: update to 1.9.0mt8
  devel/irrlichtmt/Portfile
Labels: type: update, maintainer: open

#16956 nheko: Depend on mtxclient, cmark, olm at runtime
  net/nheko/Portfile
Labels: type: bugfix, maintainer: none, by: member

#16957 py-pymongoengine: Update to 0.24.2, add modern python, drop old python
  python/py-mongoengine/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#16955 libressl-devel: update to version 3.7.0.
  security/libressl-devel/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer, maintainer: open

#16909 homebank: update to 5.6
  x11/homebank/Portfile
Labels: type: update, maintainer: open

#16963 nixpacks: updated to version 0.16.0
  devel/nixpacks/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#16958 yaz: bump revision for hiredis update
  devel/nixpacks/Portfile
Labels: maintainer: none

#16961 x265: enable HDR10+ parsing
  multimedia/x265/Portfile
Labels: type: update, maintainer: none

#16962 minetest: update to 5.6.1
  games/minetest/Portfile
Labels: type: update, maintainer: none

#16969 scotch: fix tests
  science/scotch/Portfile
  science/scotch/files/cmake-shared-library.diff
Labels: type: bugfix, maintainer, maintainer: open

#16941 clojure-lsp: update to 2022.12.09-15.51.10
  devel/clojure-lsp/Portfile
Labels: type: update, maintainer, maintainer: open

#16973 crystal: update to 1.6.2
  lang/crystal/Portfile
Labels: type: update, maintainer, maintainer: open

#16974 clojure: update to 1.11.1.1208
  lang/clojure/Portfile
Labels: type: update, maintainer, maintainer: open

#16980 openssl3: Drop patch incorporated upstream
  devel/openssl3/Portfile
  devel/openssl3/files/patch-disable-avx512.diff
Labels: type: enhancement, maintainer, maintainer: open, by: member

#16977 xar: use path:lib/libssl.dylib:openssl for LibreSSL compatibility.
  archivers/xar/Portfile
Labels: type: enhancement, maintainer: open

#16981 asdf: update to 0.11.0
  sysutils/asdf/Portfile
Labels: type: update, maintainer, maintainer: open

#16985 snac: update to version 2.15.
  net/snac/Portfile
  net/snac/files/Makefile.patch
Labels: type: bugfix, type: enhancement, type: update, maintainer, maintainer: open

#16986 sketchybar: update to 2.12.0
  sysutils/sketchybar/Portfile
Labels: type: update, maintainer, maintainer: open

#16968 netgen: fix build on old macOS
  math/netgen/Portfile
  math/netgen/files/patch-sized-deallocation.diff
Labels: type: bugfix, maintainer: open

#16984 nixpacks: updated to version 0.16.2
  devel/nixpacks/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#16960 catch2: update version to 3.2.1
  devel/catch2/Portfile
Labels: type: update, maintainer: open

#16875 lerc: update to 4.0.0
  gis/lerc/Portfile
Labels: type: enhancement, type: update, maintainer: requires approval, maintainer: timeout

#16953 php-swoole, php-openswoole: bump revision for hiredis update
  php/php-openswoole/Portfile
  php/php-swoole/Portfile
Labels: maintainer: open

#16989 avrdude: update to 7.0
  cross/avrdude/Portfile
  cross/avrdude/files/dynamic_lookup-11.patch
  cross/avrdude/files/src-stk500v2.c.patch
Labels: type: update, maintainer: none

#16997 devel/pnpm: trivial version update
  devel/pnpm/Portfile
Labels: maintainer: open, by: member

#17004 GPXSee: update to 11.11
  gis/GPXSee/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#17003 add: update to 20221104
  math/add/Portfile
Labels: type: update, maintainer: none

#17001 tcsh: update to 6.24.06
  shells/tcsh/Portfile
Labels: type: update, maintainer: none

#17002 vttest: update to 20221111
  devel/vttest/Portfile
Labels: type: update, maintainer: none

#16996 bitwarden-cli: Update to 2022.11.0
  security/bitwarden-cli/Portfile
Labels: type: update, maintainer, maintainer: open

#16991 lerc: fix includes
  gis/lerc/Portfile
  gis/lerc/files/patch-include.diff
Labels: type: bugfix, maintainer: requires approval

#16995 LaTeXML: update to upstream version 0.8.7
  tex/LaTeXML/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer

#16964 gcc10-bootstrap: backport preliminary support of Ventura
  lang/gcc10-bootstrap/Portfile
  lang/gcc10-bootstrap/files/patch-darwin22.diff
Labels: type: bugfix, maintainer, maintainer: open

#17007 DeaDBeeF: update to 1.9.4
  multimedia/DeaDBeeF/Portfile
Labels: type: update, maintainer, maintainer: open

#16856 abella: new port in math
  math/abella/Portfile
  math/abella/files/patch-bytecode.diff
Labels: type: submission

#16992 bsdmake: Update checksums after Apple redirect to github
  devel/bsdmake/Portfile
Labels: type: bugfix, type: update, type: security fix, maintainer: open

#16998 python311: fix linker error on PPC
  lang/python311/Portfile
Labels: type: bugfix, maintainer: requires approval, by: member

#17021 gallery-dl: update to 1.24.2
  net/gallery-dl/Portfile
Labels: type: update, maintainer: none

#17019 roswell: update to v22.12.14.113
  devel/roswell/Portfile
Labels: type: update, maintainer, maintainer: open

#17018 swi-prolog-devel: Updated to version 9.1.2
  lang/swi-prolog-devel/Portfile
Labels: type: update, maintainer, maintainer: open

#17016 lean: update to v3.50.0
  math/lean/Portfile
Labels: type: update, maintainer, maintainer: open

#17015 poac: update to 0.5.1
  sysutils/poac/Portfile
Labels: type: update, maintainer, maintainer: open

#17014 swi-prolog: Updated to version 9.0.3
  lang/swi-prolog/Portfile
Labels: type: update, maintainer, maintainer: open

#17013 uxn: update to 20221211
  emulators/uxn/Portfile
  emulators/uxn/files/patch-uxn-build.diff
Labels: type: update, maintainer: none

#17000 vtm: update to 0.9.8d
  sysutils/vtm/Portfile
Labels: type: update, maintainer: none

#16972 nano: update to 7.1
  editors/nano/Portfile
Labels: type: update, maintainer: open

#17008 qoi: update to 20221213
  graphics/qoi/Portfile
  graphics/qoi/files/patch-makefile.diff
Labels: type: update, maintainer: none

#17027 skaffold: update to 2.0.4
  devel/skaffold/Portfile
Labels: type: update, maintainer, maintainer: open

#17026 micronaut: update to 3.7.5
  java/micronaut/Portfile
Labels: type: update, maintainer, maintainer: open

#16994 yabai: update to 5.0.2
  sysutils/yabai/Portfile
Labels: type: update, maintainer: open

#16982 istioctl: update to 1.16.1
  sysutils/istioctl/Portfile
Labels: type: update, maintainer: open

#16988 mackup: update to 0.8.36
  sysutils/mackup/Portfile
Labels: type: update, maintainer: open

#17033 python27-bootstrap: fix missing expat/libffi on Tiger
  lang/python27/Portfile
Labels: maintainer, maintainer: open, by: member

#17032 fheroes2: update to 1.0.0
  games/fheroes2/Portfile
Labels: type: update, maintainer, maintainer: open

#17011 dmarc-report-converter: new port
  mail/dmarc-report-converter/Portfile
Labels: type: submission

#17034 stgit: Update to 2.1.0, migration from Python to Rust
  devel/stgit/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#17023 fdupes: update to version 2.2.1
  sysutils/fdupes/Portfile
Labels: type: update, maintainer: requires approval, by: member

#17036 scrcpy: Update to version 1.25
  multimedia/scrcpy/Portfile
Labels: type: update, maintainer, maintainer: open

#17035 tcsh: update to 6.24.07
  shells/tcsh/Portfile
Labels: type: update, maintainer: none

#17031 py-igraph: re-add test dependencies for py311 subport
  python/py-igraph/Portfile
Labels: type: enhancement, maintainer, maintainer: open

#17017 gtk-internet-radio-locator: new port
  gnome/gtk-internet-radio-locator/Portfile
  gnome/gtk-internet-radio-locator/files/autogen.sh
Labels: type: enhancement, type: submission

#17037 snac: update to version 2.16.
  net/snac/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#17022 ghidra: update to 10.2.2
  devel/ghidra/Portfile
Labels: type: update, maintainer: open

#16844 zsh-history-substring-search: new port
  sysutils/zsh-history-substring-search/Portfile
Labels: type: enhancement, type: submission

#16310 openjdk7-bootstrap: fix path for libfreetype
  java/openjdk7-bootstrap/Portfile
Labels: type: bugfix, maintainer: open

#17043 sketchybar: update to 2.12.2
  sysutils/sketchybar/Portfile
Labels: type: update, maintainer, maintainer: open

#17045 lens: update to 6.3.0
  sysutils/lens/Portfile
Labels: type: update, maintainer, maintainer: open

#17046 flux: update to 0.38.2
  sysutils/flux/Portfile
Labels: type: update, maintainer, maintainer: open

#17039 libfmt4: submission of libfmt version 4.1.0
  devel/libfmt4/Portfile
Labels: type: submission

#17025 netgen: fix build on case sensetive FS
  math/netgen/Portfile
  math/netgen/files/patch-MacPorts-togl.diff
Labels: type: bugfix, maintainer: open

#17040 coolprop-if97: submission of IF97 port
  science/coolprop-if97/Portfile
Labels: type: submission

#17041 coolprop-refprop-headers: submission of new port
  science/coolprop-refprop-headers/Portfile
Labels: type: submission

#17038 rapidjson-devel: fix build failure
  devel/rapidjson-devel/Portfile
  devel/rapidjson-devel/files/patch-CMakeLists-arch.diff
Labels: maintainer: none

#16890 qt5-qtwebkit: Flag conflicting ports on case insensitive filesystems
  aqua/qt5/Portfile
Labels: type: bugfix, maintainer: open

#17047 mozjs102: new port
  lang/mozjs102/Portfile
  lang/mozjs102/files/patch-mozglue-clock_gettime.diff
  lang/mozjs102/files/patch-mozglue-snow-leopard.diff
  lang/mozjs102/files/patch-skip-sdk-check.diff
Labels: type: submission

#17049 epy: update to 2022.12.11
  python/epy/Portfile
Labels: type: update, maintainer, maintainer: open

#17051 mint: update to 0.17.5
  devel/mint/Portfile
Labels: type: bugfix, type: update, maintainer, maintainer: open

#17052 groovy: update to 4.0.7
  lang/groovy/Portfile
Labels: type: update, maintainer, maintainer: open

#17030 cdo: update to 2.1.1
  science/cdo/Portfile
  science/cdo/files/patch-skip-Multiyearstat-yseas-test.diff
  science/cdo/files/patch-skip-nc4-test.diff
Labels: type: update, maintainer: open

#17020 libproxy: add python310-311, drop python38 and below
  net/libproxy/Portfile
Labels: type: enhancement, maintainer: open

#16920 neovim: update to 0.8.1
  editors/neovim/Portfile
Labels: type: update, maintainer: open
