Repository macports/macports-ports, pull requests merged in 2022-09, with the labels that each got.

#15799 iTerm2: fix livecheck
  aqua/iTerm2/Portfile
Labels: type: bugfix, maintainer: open

#15595 nss: PPC fixes
  net/nss/Portfile
  net/nss/files/patch-ppc.diff
Labels: type: bugfix, type: enhancement, type: update, maintainer: none

#15960 flux: update to 0.33.0
  sysutils/flux/Portfile
Labels: type: update, maintainer, maintainer: open

#15517 libgfshare: update to 2.0.0
  security/libgfshare/Portfile
Labels: type: enhancement, type: update, maintainer: requires approval, maintainer: timeout

#15963 aerc: update to 0.12.0
  mail/aerc/Portfile
Labels: type: enhancement, type: update, maintainer: none

#15964 Gildas: update to 202209a
  science/gildas/Portfile
Labels: type: enhancement, type: update, maintainer

#15966 josm: update to 18543
  gis/JOSM/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#15968 wolfssl: update to version 5.5.0
  devel/wolfssl/Portfile
Labels: type: update, maintainer, type: security fix, maintainer: open

#15935 py-pycares: update to 4.2.2
  python/py-pycares/Portfile
Labels: type: update, maintainer: open, by: member

#15716 afscompress: enable LZVN/LZFSE support
  sysutils/afscompress/Portfile
Labels: type: bugfix, maintainer: open

#15456 py-transformers: Update to version 4.20.1, Add Python 310, Update dependencies
  python/py-transformers/Portfile
Labels: type: update, type: submission, maintainer: open

#15659 nhc98: fixing build on >10.6
  lang/nhc98/Portfile
Labels: type: bugfix, maintainer: none

#15606 muparser: update to 2.3.3-1
  math/muparser/Portfile
Labels: type: enhancement, type: update, maintainer: open

#15969 py-docx: Add Python 39 310
  python/py-docx/Portfile
Labels: maintainer: none

#15407 py-babel: update to 2.10.3
  python/py-babel/Portfile
Labels: type: update, maintainer: open

#15967 nixpacks: new Portfile (v0.4.0)
  devel/nixpacks/Portfile
Labels: type: enhancement, type: submission

#15973 swig3: remove old deactivate hack
  devel/swig3/Portfile
Labels: maintainer: open

#15972 swig-python3: remove obsolete subport
  devel/swig/Portfile
Labels: maintainer: open

#15725 mpd: Fix compilation on below macOS12
  audio/mpd/Portfile
  audio/mpd/files/wrappers/AudioToolBox/AudioToolbox.h
  audio/mpd/files/wrappers/CoreAudio/CoreAudio.h
Labels: type: bugfix, maintainer: none

#15733 libtapi: fix build on macOS 10.5
  devel/libtapi/Portfile
  devel/libtapi/files/optional-pthread_setname_np.diff
  devel/libtapi/files/patch-0004-tapi-add-PPC-support.diff
  devel/libtapi/files/patch-lexer.diff
Labels: type: bugfix, type: enhancement, maintainer: none

#15974 qemu: update to 7.1.0
  emulators/qemu/Portfile
Labels: type: update, maintainer: open

#15636 M2VDownsizer: new port
  multimedia/M2VDownsizer/Portfile
  multimedia/M2VDownsizer/files/1001-Replace-MPProcessors-Patch.diff
  multimedia/M2VDownsizer/files/1002-libmpeg2-Linkage-Patch.diff
  multimedia/M2VDownsizer/files/1003-Patch-config.h.diff
  multimedia/M2VDownsizer/files/1004-Fix-Includes-in-mjpeg_logging.diff
  multimedia/M2VDownsizer/files/M2VDownsizer.1
  multimedia/M2VDownsizer/files/Makefile
Labels: type: submission

#15891 apache-arrow: Remove unnecessary libunwind dependency
  devel/apache-arrow/Portfile
Labels: maintainer: none

#15977 py-stopwordsiso: Add Python 310
  python/py-stopwordsiso/Portfile
Labels: maintainer: none

#15975 nektarpp: update to 5.2.0
  science/nektarpp/Portfile
  science/nektarpp/files/opencascade.patch
Labels: type: enhancement, type: update, maintainer, maintainer: open

#15980 gingerblue: update to 6.2.0
  gnome/gingerblue/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer, type: security fix, maintainer: open

#15471 abseil: fix build for old systems
  devel/abseil/Portfile
  devel/abseil/files/patch-darwin-ppc.diff
Labels: type: bugfix, maintainer: open

#15950 clang-11-bootstrap: backport support of `using_if_exists`
  lang/clang-11-bootstrap/Portfile
  lang/clang-11-bootstrap/files/0001-Define-EXC_MASK_CRASH-and-MACH_EXCEPTION_CODES-if-th.patch
  lang/clang-11-bootstrap/files/0002-MacPorts-Only-Don-t-embed-the-deployment-target-in-t.patch
  lang/clang-11-bootstrap/files/0003-Fix-build-issues-pre-Lion-due-to-missing-a-strnlen-d.patch
  lang/clang-11-bootstrap/files/0004-Fix-build-issues-pre-Lion-due-to-missing-a-memmem-de.patch
  lang/clang-11-bootstrap/files/0005-Threading-Only-call-pthread_setname_np-on-SnowLeopar.patch
  lang/clang-11-bootstrap/files/0006-Only-call-setpriority-PRIO_DARWIN_THREAD-0-PRIO_DARW.patch
  lang/clang-11-bootstrap/files/0007-dsymutil-fix-build-on-Leopard.patch
  lang/clang-11-bootstrap/files/0008-lib-Support-Unix-Path.inc-define-COPYFILE_CLONE-if-n.patch
  lang/clang-11-bootstrap/files/0009-MacPorts-Only-Fix-name-of-scan-view-executable-insid.patch
  lang/clang-11-bootstrap/files/0010-default-to-libcxx-on-all-systems.patch
  lang/clang-11-bootstrap/files/0011-Default-to-fragile-ObjC-runtime-when-targeting-darwi.patch
  lang/clang-11-bootstrap/files/0012-Fixup-libstdc-header-search-paths-for-older-versions.patch
  lang/clang-11-bootstrap/files/0013-Fix-float.h-to-work-on-Snow-Leopard-and-earlier.patch
  lang/clang-11-bootstrap/files/0014-compiler-rt-add-some-defs-missing-in-older-SDKs.patch
  lang/clang-11-bootstrap/files/0015-10.5-and-less-compiler-rt-work-around-no-libdispatch.patch
  lang/clang-11-bootstrap/files/0016-Fix-missing-long-long-math-prototypes-when-using-the.patch
  lang/clang-11-bootstrap/files/0017-implement-atomic-using-mutex-lock_guard-for-64b-ops-.patch
  lang/clang-11-bootstrap/files/0018-libcxx-src-chrono.cpp-fix-build-by-older-SDKs.patch
  lang/clang-11-bootstrap/files/0019-compiler-rt-allow-build-before-10.7.patch
  lang/clang-11-bootstrap/files/0020-compiler-rt-added-CMAKE_OSX_DEPLOYMENT_TARGET-fallba.patch
  lang/clang-11-bootstrap/files/0021-add-back-runtime-libraries-used-on-10.4-and-10.5.patch
  lang/clang-11-bootstrap/files/0022-Don-t-look-into-sysroot-for-C-headers-if-they-are-fo.patch
  lang/clang-11-bootstrap/files/0023-disable-DirectoryWatcher-when-builds-by-GCC.patch
  lang/clang-11-bootstrap/files/0024-Use-for-long-options-in-help-text.patch
  lang/clang-11-bootstrap/files/0025-compatibility-with-xar-on-macOS-10.5.patch
  lang/clang-11-bootstrap/files/0026-clang-support-macports-libstdcxx.patch
  lang/clang-11-bootstrap/files/0027-compiler-rt-fix-building-by-GCC.patch
  lang/clang-11-bootstrap/files/0028-compiler-rt-allow-to-define-required-archs.patch
  lang/clang-11-bootstrap/files/0029-compiler-rt-atomic-which-can-be-compiled-by-GCC.patch
  lang/clang-11-bootstrap/files/0030-fix-building-on-10.10-by-GCC-10.patch
  lang/clang-11-bootstrap/files/0031-fix-build-of-shared-libc-.dylib-on-10.7.patch
  lang/clang-11-bootstrap/files/0032-disable-Apple-libc-Availability-tests.patch
  lang/clang-11-bootstrap/files/0033-Leopard-Default-to-fno-blocks.patch
  lang/clang-11-bootstrap/files/0034-Support-emulated-TLS-before-10.7.patch
  lang/clang-11-bootstrap/files/0035-clang-Implement-the-using_if_exists-attribute.patch
  lang/clang-11-bootstrap/files/0036-clang-Parse-Add-parsing-support-for-C-attributes-on-.patch
Labels: type: enhancement, maintainer, maintainer: open

#15979 igraph: update to 0.9.10
  math/igraph/Portfile
Labels: type: bugfix, type: update, maintainer, maintainer: open

#15976 libtapi: fixed build on old macOS
  devel/libtapi/Portfile
Labels: type: bugfix, maintainer, maintainer: open

#15986 py-awscli2: update to 2.7.29
  python/py-awscli2/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#15991 clang-11-bootstrap: fix build on 10.12 and 10.13
  lang/clang-11-bootstrap/Portfile
Labels: type: bugfix, maintainer, maintainer: open

#15988 arti: update to 1.0.0
  security/arti/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer: open

#15614 fluidsynth: update to 2.2.8, revbump known dependents
  audio/qsynth/Portfile
  emulators/scummvm/Portfile
  games/qtads/Portfile
  gnome/gstreamer1-gst-plugins-bad/Portfile
  multimedia/VLC2/Portfile
  multimedia/audacious-plugins/Portfile
  multimedia/fluidsynth/Portfile
  multimedia/lmms/Portfile
  print/denemo/Portfile
Labels: type: update, maintainer: requires approval

#15773 py-poppler-qt5: use_xcode when py-pyqt5 uses it
  python/py-poppler-qt5/Portfile
  python/py-poppler-qt5/files/patch-fix-qt-dirs.diff
Labels: type: bugfix, maintainer, maintainer: open

#16002 difftastic: Update to version 0.35.0
  devel/difftastic/Portfile
Labels: type: update, maintainer: open

#15992 libfilezilla: update to 0.32.0, fix build for old systems
  devel/libfilezilla/Portfile
  devel/libfilezilla/files/patch-util.diff
Labels: type: bugfix, type: enhancement, type: update, maintainer: open

#15989 gingerblue: add app bundle; add variant debug
  gnome/gingerblue/Portfile
Labels: maintainer: open, by: member

#15981 less: update to 608
  textproc/less/Portfile
  textproc/less/files/patch-configure.diff
Labels: type: enhancement, type: update, maintainer: open

#16016 hidapi: update to 0.12.0
  comms/hidapi/Portfile
Labels: type: enhancement, type: update, maintainer: open

#16003 dwdiff: update to 2.1.4
  textproc/dwdiff/Portfile
Labels: type: enhancement, type: update, maintainer: none

#16004 spidermonkey185: fix building on modern macOS
  lang/spidermonkey185/Portfile
Labels: type: bugfix, maintainer: none

#16019 elixir: update to version 1.14.0
  lang/elixir/Portfile
Labels: type: update, maintainer, maintainer: open

#16012 GPXSee: update to 11.4
  gis/GPXSee/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#16013 gource: update to 0.53
  devel/gource/Portfile
Labels: type: enhancement, type: update, maintainer: none

#16006 feh: update to 3.9.1
  graphics/feh/Portfile
Labels: type: enhancement, type: update, maintainer: none

#16005 libebur128: update to 1.2.6
  audio/libebur128/Portfile
Labels: type: enhancement, type: update, maintainer: open

#15970 mupdf: Update to version 1.20.3
  graphics/mupdf/Portfile
Labels: type: update, maintainer: open

#15983 py-xattr: update to 0.9.9
  python/py-xattr/Portfile
Labels: type: enhancement, type: update, maintainer: open

#15982 xorg-libXau: update to 1.0.10
  x11/xorg-libXau/Portfile
Labels: type: enhancement, type: update, maintainer: open

#15962 terragrunt: update to 0.38.9
  sysutils/terragrunt/Portfile
Labels: type: update, maintainer: open

#15954 py-hatch-fancy-pypi-readme: submission
  python/py-hatch-fancy-pypi-readme/Portfile
Labels: type: enhancement, type: submission

#16026 osm2pgsql: fix build before Mojave
  gis/osm2pgsql/Portfile
Labels: type: bugfix, maintainer: open

#16028 micronaut: update to 3.6.2
  java/micronaut/Portfile
Labels: type: update, maintainer, maintainer: open

#15994 libquirc: new port
  graphics/libquirc/Portfile
  graphics/libquirc/files/patch-quirc.diff
  graphics/libquirc/files/videoio.h
Labels: type: bugfix, type: enhancement, type: submission, maintainer: open

#16034 lean: update to v3.48.0
  math/lean/Portfile
Labels: type: update, maintainer, maintainer: open

#16030 py-jsonschema: update to 4.15.0
  python/py-jsonschema/Portfile
Labels: type: enhancement, type: update, maintainer: open

#16010 MacVim: added arm64 to supported_archs
  editors/MacVim/Portfile
Labels: type: enhancement, maintainer: requires approval

#16037 swi-prolog-devel: Updated to version 8.5.16
  lang/swi-prolog-devel/Portfile
Labels: type: update, maintainer, maintainer: open

#15993 opencv4-devel: Turn on QUIRC support
  graphics/opencv4-devel/Portfile
Labels: type: enhancement, type: update, maintainer: requires approval, wip

#16031 chromedriver: Update to version 105.0.5195.52, Use Python 310
  www/chromedriver/Portfile
Labels: type: update, maintainer: open

#16022 py-hdbscan: Update to version 0.8.28, add Python 39 310
  python/py-hdbscan/Portfile
Labels: type: enhancement, type: update, maintainer: none

#16043 dbvis: update to 13.0.5
  databases/dbvis/Portfile
Labels: type: update, maintainer, maintainer: open

#16041 scala3.2: new port (version 3.2.0)
  lang/scala-docs/Portfile
  lang/scala/Portfile
  lang/scala/files/scala2.10
  lang/scala/files/scala2.11
  lang/scala/files/scala2.12
  lang/scala/files/scala2.13
  lang/scala/files/scala2.7
  lang/scala/files/scala2.8
  lang/scala/files/scala2.9
  lang/scala/files/scala3.0
  lang/scala/files/scala3.1
  lang/scala/files/scala3.2
  lang/scala2.10/Portfile
  lang/scala2.10/files/scala2.10
  lang/scala2.11/Portfile
  lang/scala2.11/files/scala2.11
  lang/scala2.12/Portfile
  lang/scala2.12/files/scala2.12
  lang/scala2.13/Portfile
  lang/scala2.13/files/scala2.13
  lang/scala2.7/Portfile
  lang/scala2.7/files/scala2.7
  lang/scala2.8/Portfile
  lang/scala2.8/files/scala2.8
  lang/scala2.9/Portfile
  lang/scala2.9/files/scala2.9
  lang/scala3.0/Portfile
  lang/scala3.1/Portfile
  lang/scala3.2/Portfile
  sysutils/scala_select/Portfile
  sysutils/scala_select/files/base
  sysutils/scala_select/files/none
Labels: type: enhancement, type: submission, maintainer, maintainer: open

#15961 istioctl: update to 1.15.0
  sysutils/istioctl/Portfile
Labels: type: enhancement, type: update, maintainer: open

#15791 qt5pas: update to 2.2.0-0, fix build
  devel/qt5pas/Portfile
Labels: type: enhancement, type: update, maintainer: open

#15434 SourceKitten: Update to 0.32.0
  devel/SourceKitten/Portfile
Labels: type: enhancement, type: update, maintainer: none

#16052 n: update to 9.0.0
  devel/n/Portfile
Labels: type: enhancement, type: update, maintainer: none

#16055 cgrc: update to 0.5.0
  textproc/cgrc/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#15995 proxy-audio-device: Update to version 1.0.6
  audio/proxy-audio-device/Portfile
Labels: type: update, maintainer: open

#15990 mrustc: update to 20220904
  lang/mrustc/Portfile
  lang/mrustc/files/0001-Introduced-support-of-MACPORTS_LEGACY_SUPPORT_.patch
  lang/mrustc/files/0002-curl-sys-never-try-to-link-with-lib-darwin.patch
  lang/mrustc/files/0003-libgit2-sys-use-src-instead-.git-as-vendored-indicat.patch
  lang/mrustc/files/0004-libssh2-sys-use-src-instead-.git-as-vendored-indicat.patch
  lang/mrustc/files/0005-libgit2-sys-recovered-LIBGIT2_SYS_USE_PKG_CONFIG.patch
  lang/mrustc/files/0006-macOS-10.7-Switch-to-OpenSSL.patch
  lang/mrustc/files/0007-macOS-10.6-enforce-emulated-TLS-via-LLVM-Clang.patch
  lang/mrustc/files/0008-macOS-10.6-Fix-pthread_cond_destroy.patch
Labels: type: bugfix, type: enhancement, type: update, maintainer, maintainer: open

#16059 codeblocks-devel: tracks devel, @r12881
  devel/codeblocks-devel/Portfile
  devel/codeblocks/Portfile
Labels: type: submission, maintainer: none, by: member

#15997 atom: remove obsolete port
  editors/atom/Portfile
  editors/atom/files/patch-install-prefix.diff
Labels: maintainer: none

#16060 igraph: update to 0.10.1
  math/igraph/Portfile
Labels: type: update, maintainer, maintainer: open

#16048 n2n: update to 3.1.1, fixes build for Big Sur and up
  net/n2n/Portfile
  net/n2n/files/DESTDIR.patch
  net/n2n/files/configure.seed.patch
  net/n2n/files/no-space-after-L-or-I.patch
  net/n2n/files/patch-man-prefix.diff
Labels: type: enhancement, type: update, maintainer: none

#16040 yabai: update to version 4.0.4
  sysutils/yabai/Portfile
Labels: type: enhancement, type: update, maintainer: open

#16017 pnpm: update to 7.11.0
  devel/pnpm/Portfile
Labels: type: enhancement, type: update, maintainer: open

#16072 micronaut: update to 3.6.3
  java/micronaut/Portfile
Labels: type: update, maintainer, maintainer: open

#15985 gcc{12,-devel}: disable stdlib_flag on PPC by default
  lang/gcc-devel/Portfile
  lang/gcc12/Portfile
Labels: type: bugfix, maintainer: none

#16073 google-cloud-sdk: update available variants
  devel/google-cloud-sdk/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#16070 py-graphene: update to 3.1.1
  python/py-graphene/Portfile
Labels: type: enhancement, type: update, maintainer: none

#15998 alex: Update to version 3.2.7.1, native build with bootstrapped cabal
  devel/alex/Portfile
Labels: type: update, maintainer: none

#16001 hscolour: native build with bootstrapped cabal
  devel/hscolour/Portfile
Labels: maintainer: none

#16000 happy: native build with bootstrapped cabal
  devel/happy/Portfile
Labels: maintainer: none

#16067 stork: new port submission (version 1.5.0)
  textproc/stork/Portfile
Labels: type: submission

#16039 nixpacks: update to version 0.5.2
  devel/nixpacks/Portfile
Labels: type: enhancement, type: update, maintainer: open

#16083 qt(53|55|56|57|58|59|511|513)-qtimageformats: fix build
  aqua/qt511/Portfile
  aqua/qt511/files/patch-qtimageformats-qjp2handler.cpp.diff
  aqua/qt513/Portfile
  aqua/qt513/files/patch-qtimageformats-qjp2handler.cpp.diff
  aqua/qt53/Portfile
  aqua/qt53/files/patch-qtimageformats-qjp2handler.cpp.diff
  aqua/qt55/Portfile
  aqua/qt55/files/patch-qtimageformats-qjp2handler.cpp.diff
  aqua/qt56/Portfile
  aqua/qt56/files/patch-qtimageformats-qjp2handler.cpp.diff
  aqua/qt57/Portfile
  aqua/qt57/files/patch-qtimageformats-qjp2handler.cpp.diff
  aqua/qt58/Portfile
  aqua/qt58/files/patch-qtimageformats-qjp2handler.cpp.diff
  aqua/qt59/Portfile
  aqua/qt59/files/patch-qtimageformats-qjp2handler.cpp.diff
Labels: type: bugfix, maintainer: open

#16084 qt58-qtconnectivity: fix patch
  aqua/qt58/files/patch-qtconnectivity_qtbug_76847.diff
Labels: type: bugfix, maintainer: open

#16086 groovy: update to 4.0.5
  lang/groovy/Portfile
Labels: type: update, maintainer, maintainer: open

#16081 istioctl: fix build by patching init.sh
  sysutils/istioctl/Portfile
  sysutils/istioctl/files/patch-init-script.diff
Labels: type: bugfix, maintainer: open

#16089 cabal, cabal-prebuilt: Bugfix, add necessary dependencies
  lang/cabal/Portfile
Labels: type: bugfix, maintainer, maintainer: open

#16045 clisp: fix homepage
  lang/clisp/Portfile
Labels: maintainer: open

#16080 aeson-pretty: Use cabal-based native builds
  devel/aeson-pretty/Portfile
Labels: maintainer: none

#16078 adblock2privoxy: Use cabal-based native builds
  www/adblock2privoxy/Portfile
Labels: maintainer, maintainer: open

#16091 demangle: submission (version 20160204)
  devel/demangle/Portfile
Labels: type: enhancement, type: submission

#16087 HaXml: Update to version 1.25.9, use cabal-based native builds
  devel/HaXml/Portfile
Labels: maintainer: none

#16079 shellcheck: Use cabal-based native builds
  devel/shellcheck/Portfile
Labels: maintainer: open

#16092 fheroes2: update to 0.9.19
  games/fheroes2/Portfile
Labels: type: update, maintainer, maintainer: open

#16071 sslscan: update to 2.0.15
  net/sslscan/Portfile
Labels: type: update, maintainer: open, by: member

#16077 glfw: add v3.2.1 as fallback for 10.7-10.8
  graphics/glfw/Portfile
  graphics/glfw/files/patch-CMakeLists.txt.321.1.diff
  graphics/glfw/files/patch-CMakeLists.txt.321.2.diff
Labels: type: bugfix, maintainer: open, by: member

#16062 port_select ports: simplify via pg stub
  perl/fsdb_select/Portfile
  python/ansible_select/Portfile
  python/celery_select/Portfile
  python/django-htmlmin_select/Portfile
  python/hatchling_select/Portfile
  python/kerfi-vangasvipur_select/Portfile
  python/lexicon_select/Portfile
  python/obspy_select/Portfile
  python/pew_select/Portfile
  python/pip_select/Portfile
  python/py-sympy_select/Portfile
  python/pyflakes_select/Portfile
  python/tmuxp_select/Portfile
  sysutils/apl_select/Portfile
  sysutils/clang_select/Portfile
  sysutils/geant4_select/Portfile
  sysutils/llvm_select/Portfile
  sysutils/mpi_select/Portfile
  sysutils/octave_select/Portfile
  sysutils/php_select/Portfile
  sysutils/root_select/Portfile
  sysutils/ruby_select/Portfile
Labels: maintainer: requires approval, by: member

#16065 py-graphviz: update to 0.20.1, add py310 subport
  python/py-graphviz/Portfile
Labels: type: bugfix, type: enhancement, maintainer: open

#16054 java PG: fix detection of arm
  _resources/port1.0/group/java-1.0.tcl
Labels: type: bugfix

#16100 openttd: Update to 12.2
  games/openttd/Portfile
  games/openttd/files/patch-cmake-PackageBundle.diff
  games/openttd/files/patch-lto.diff
  games/openttd/files/patch-sysroot.diff
Labels: type: update, maintainer, maintainer: open, by: member

#16098 lhs2tex: Use cabal-based native builds
  textproc/lhs2tex/Portfile
Labels: maintainer: open

#16074 ghidra: use pg java; cleanup
  devel/ghidra/Portfile
Labels: maintainer: open, by: member

#16095 cpphs: Use cabal-based native builds
  devel/cpphs/Portfile
Labels: maintainer: none

#16094 py-undetected-chromedriver: Bugfix run dependency, clean up tests
  python/py-undetected-chromedriver/Portfile
Labels: type: bugfix, maintainer: none

#16057 emacs{,-app}-devel: update to 20220908
  editors/emacs/Portfile
Labels: type: update, maintainer: open, by: member

#16105 tippecanoe: update to 2.6.0
  gis/tippecanoe/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#16106 json2tsv: new port
  textproc/json2tsv/Portfile
Labels: type: enhancement, type: submission

#16046 ent: update to 20220220
  math/ent/Portfile
Labels: type: enhancement, type: update, maintainer: none

#16109 bitwarden-cli: update to 2022.9.0
  security/bitwarden-cli/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#16114 google-cloud-sdk: update to 402.0.0
  devel/google-cloud-sdk/Portfile
Labels: type: update, maintainer, maintainer: open

#16120 libtapi: fix livecheck
  devel/libtapi/Portfile
Labels: type: bugfix, maintainer, maintainer: open

#16119 demangle: fixed used commit
  devel/demangle/Portfile
Labels: type: bugfix, maintainer, maintainer: open

#16118 giter8: update to 0.15.0
  devel/giter8/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#16058 qt5: update to 5.15.6
  aqua/qt5/Portfile
  aqua/qt5/files/patch-cve-2021-38593.diff
Labels: type: update, maintainer: open

#16125 got: update to version 0.75.1
  devel/got/Portfile
Labels: type: enhancement, type: update, maintainer: none

#16097 qt511-qtconnectivity: fix for recent compilers
  aqua/qt511/Portfile
  aqua/qt511/files/patch-qtconnectivity_qtbug_76847.diff
Labels: type: bugfix, maintainer: open

#16128 py-igraph: update to 0.10.1
  python/py-igraph/Portfile
Labels: type: update, maintainer, maintainer: open

#16127 nixpacks: updated to version 0.5.5
  devel/nixpacks/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#16056 seqan3: update to 3.2.0
  science/seqan3/Portfile
Labels: type: enhancement, type: update, maintainer: open

#16047 ensmallen: update to 2.19.0
  math/ensmallen/Portfile
Labels: type: enhancement, type: update, maintainer: open

#16036 qoi: submission
  graphics/qoi/Portfile
  graphics/qoi/files/patch-makefile.diff
Labels: type: submission

#16131 rclone: add mount variant
  net/rclone/Portfile
Labels: type: enhancement, maintainer: open

#16121 istioctl: update livecheck
  sysutils/istioctl/Portfile
Labels: type: update, maintainer: open

#16068 jsmin: update to 20191031
  lang/jsmin/Portfile
Labels: type: enhancement, type: update, maintainer: open

#16130 xar: Don't overlink to libxml2's dependencies
  archivers/xar/Portfile
  archivers/xar/files/dont-overlink-to-libxml2.patch
Labels: maintainer: open, by: member

#16110 datree: new portfile in version 1.6.29
  devel/datree/Portfile
Labels: type: enhancement, type: submission

#16099 nodejs18: use MacPorts' newly upgraded ICU 71.1
  devel/nodejs18/Portfile
Labels: type: enhancement, maintainer: open, by: member

#16075 OpenCoarrays: update to 2.10.0, fix the build, add variants
  science/OpenCoarrays/Portfile
  science/OpenCoarrays/files/patch-isnan.diff
Labels: type: bugfix, type: enhancement, type: update, maintainer: none

#16108 cdo: update to 2.0.6
  science/cdo/Portfile
  science/cdo/files/patch-cdo-2.0.6-missing-include.diff
Labels: type: update, maintainer: open

#16137 ghc: Bugfix build with existing ghc installed
  lang/ghc/Portfile
Labels: type: bugfix, maintainer, maintainer: open

#15260 kismet: update to 2022-02-R1
  net/kismet/Portfile
  net/kismet/files/patch-configure.diff
  net/kismet/files/patch-kis_panel_frontend.h.diff
  net/kismet/files/patch-plugintracker.h.diff
Labels: type: update, maintainer: none

#16042 openjdk{11,17}-graalvm: add native-image subport
  java/openjdk11-graalvm/Portfile
  java/openjdk17-graalvm/Portfile
Labels: type: submission

#16044 ecm: fetch using macports_distfiles
  archivers/ecm/Portfile
Labels: type: enhancement, maintainer: none

#16138 scute: new port
  security/scute/Portfile
  security/scute/files/scute-1.7.0-add-no-chain-option.diff
  security/scute/files/scute-1.7.0-fix-global-definition.diff
Labels: type: submission

#16139 rawtherapee: set cmake build type; ensure optimization disabled, for debug build
  graphics/rawtherapee/Portfile
Labels: maintainer: open, by: member

#16143 libtapi: use clang-11-bootstrap on macOS 10.12
  devel/libtapi/Portfile
Labels: type: bugfix, maintainer, maintainer: open

#16123 emacs: update to 28.2
  editors/emacs/Portfile
  editors/emacs/files/patch-lib_verify.h.diff
  editors/emacs/files/patch-src_sysdep.c.diff
Labels: type: update, maintainer: open, by: member

#16140 openmotif: fix missing stdlib.h, sprintf() check
  x11/openmotif/Portfile
  x11/openmotif/files/include-stdlib.patch
Labels: type: bugfix, maintainer: none

#16126 nodejs16: Remove `use_xcode` line
  devel/nodejs16/Portfile
Labels: maintainer: open, by: member

#16009 libosinfo: update to 1.10.0
  sysutils/libosinfo/Portfile
Labels: type: enhancement, type: update, maintainer: open

#16142 demangle: fixed permission in share/docs
  devel/demangle/Portfile
Labels: type: bugfix, maintainer, maintainer: open

#16152 universal-ctags: update to 5.9.20220911.0
  devel/universal-ctags/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#16163 nixpacks: update to v0.5.7
  devel/nixpacks/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#16162 datree: update to v1.6.32
  devel/datree/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#16164 difftastic: Update to version 0.36.1
  devel/difftastic/Portfile
Labels: type: update, maintainer: open

#16159 pgbadger: update to 12.0
  databases/pgbadger/Portfile
Labels: type: enhancement, type: update, maintainer: none
