Repository macports/macports-ports, pull requests merged in 2022-02, with the labels that each got.

#13851 dex2jar: Update to 2.1
  java/dex2jar/Portfile
  java/dex2jar/files/patch-adjust-classpath.diff
Labels: type: update, maintainer: none, by: member

#13850 Bug fix for oof2 version 2.2.1
  science/oof2/Portfile
Labels: maintainer, maintainer: open

#13849 Bug fix for oofcanvas, now version 1.0.2
  graphics/oofcanvas/Portfile
Labels: maintainer, maintainer: open

#13830 cppcheck: update python dependency from 3.9 to 3.10
  devel/cppcheck/Portfile
Labels: type: enhancement, type: update, maintainer: open

#13835 py-requests-oauthlib: update to 1.3.1
  python/py-requests-oauthlib/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#13795 py-anyio: enable Python 3.10 variant
  python/py-anyio/Portfile
Labels: type: enhancement, maintainer: open

#13854 lima: update to 0.8.2
  sysutils/lima/Portfile
Labels: type: update, maintainer: none

#13816 py-geopandas: remove subports for EOL Python versions
  python/py-geopandas/Portfile
Labels: maintainer: open, by: member

#13856 chafa: update to 1.8.0
  graphics/chafa/Portfile
Labels: type: update, maintainer: open, by: member

#13858 samba4: Update to 4.15.5
  net/samba4/Portfile
Labels: type: update, type: security fix, maintainer: none, by: member

#13857 Gildas: update to 202202a
  science/gildas/Portfile
Labels: type: enhancement, type: update, maintainer

#13853 botan: update to 2.19.1
  security/botan/Portfile
  security/botan/files/patch-add-missing-header-cstdlib.diff
  security/botan/files/patch-fix-ldflags-order.diff
  security/botan/files/patch-fix-missing-sys-types.h.diff
Labels: maintainer: none

#13818 t-rex: new port
  gis/t-rex/Portfile
Labels: type: enhancement, type: submission

#13697 Update sqlitebrowser with new variant +sqlcipher, and new Portfile for sqlcipher
  databases/sqlcipher/Portfile
  databases/sqlitebrowser/Portfile
Labels: type: enhancement, type: submission, maintainer: open

#13863 google-cloud-sdk: update to 371.0.0
  devel/google-cloud-sdk/Portfile
Labels: type: update, maintainer, maintainer: open

#13865 elixir: add livecheck
  lang/elixir/Portfile
Labels: maintainer: requires approval

#13563 giter8: update to 0.13.1
  devel/giter8/Portfile
  devel/giter8/files/g8
  devel/giter8/files/giter8.launchconfig
Labels: type: enhancement, type: update, maintainer: none

#13867 kustomize: update to 4.5.1
  devel/kustomize/Portfile
Labels: type: update, maintainer, maintainer: open

#13868 libusb: fix build on 10.11 and earlier
  devel/libusb/Portfile
Labels: type: bugfix, maintainer: open

#13873 rcs: update to 5.10.1
  devel/rcs/Portfile
  devel/rcs/files/patch-noreturn.diff
  devel/rcs/files/secure_snprintf.patch
Labels: type: update, maintainer: none

#13831 asciinema: update python dependency from 3.9 to 3.10
  sysutils/asciinema/Portfile
Labels: type: enhancement, type: update, maintainer: requires approval, maintainer: timeout

#13823 OpenCoarrays: remove maintainer, update descrip.
  science/OpenCoarrays/Portfile
Labels: type: bugfix, maintainer: requires approval, maintainer: timeout

#13848 oui: new port
  net/oui/Portfile
Labels: type: enhancement, type: submission

#13852 rocksdb: Update to 6.27.3, switch to CMake
  databases/rocksdb/Portfile
  databases/rocksdb/files/patch-Makefile.diff
  databases/rocksdb/files/patch-build_tools_build_detect_platform.diff
Labels: type: bugfix, type: update, maintainer: open, by: member

#13872 nco: update to 5.0.6
  science/nco/Portfile
Labels: type: update, maintainer, maintainer: open

#13661 py-selenium: Update to version 4.1.0
  python/py-selenium/Portfile
Labels: type: update, maintainer: open

#13874 oof2: update to 2.2.2
  science/oof2/Portfile
Labels: type: bugfix, type: update, maintainer, maintainer: open

#13882 screen: update to 4.9.0
  sysutils/screen/Portfile
Labels: type: update, maintainer: open

#13884 py-jenkins-job-builder: remove outdated port using python 27
  python/py-jenkins-job-builder/Portfile
Labels: maintainer: none, by: member

#13885 unrar: update to 6.1.4
  archivers/unrar/Portfile
Labels: type: enhancement, type: update, maintainer: none

#13783 erlang: fix build error on 10.6
  lang/erlang/Portfile
  lang/erlang/files/patch-erts_emulator_sys_unix_ddll.c.diff
Labels: type: bugfix, maintainer: requires approval, maintainer: timeout

#13652 libbonoboui: replace dep to pangox-compat with pango
  gnome/libbonoboui/Portfile
Labels: type: bugfix, type: submission, maintainer: open

#13889 swi-prolog-devel: Updated to version 8.5.7
  lang/swi-prolog-devel/Portfile
Labels: type: update, maintainer, maintainer: open

#13887 py-Pillow: update to 9.0.1
  python/py-Pillow/Portfile
Labels: type: enhancement, type: update, maintainer: open

#13886 syncthing: update to 1.19.0
  net/syncthing/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer: open

#13879 py-cheroot: add python39 and python310
  python/py-cheroot/Portfile
Labels: type: enhancement, maintainer: none

#13881 py-markdown2: python310
  python/py-markdown2/Portfile
Labels: type: enhancement, maintainer: none

#13891 clojure: update to 1.10.3.1075
  lang/clojure/Portfile
Labels: type: update, maintainer, maintainer: open

#13878 py-google-auth-httplib2: upgrade to 0.1.0
  python/py-google-auth-httplib2/Portfile
Labels: type: enhancement, maintainer: open

#13876 py-bottle: add python310
  python/py-bottle/Portfile
Labels: type: enhancement, maintainer: none

#13880 py-flask-babel: add python39 and python310
  python/py-flask-babel/Portfile
Labels: type: enhancement, maintainer: none

#13877 py-magic: add python310
  python/py-magic/Portfile
Labels: type: enhancement, maintainer: open

#13819 godot: use external libs
  games/godot/Portfile
  games/godot/files/add-external_libs-support.diff
Labels: type: enhancement, maintainer

#13883 tigervnc: Update to 1.12.0
  x11/tigervnc/Portfile
  x11/tigervnc/files/patch-CMakeLists.txt.diff
  x11/tigervnc/files/patch-release-makemacapp.in.diff
  x11/tigervnc/files/patch-vncviewer-CMakeLists.txt.diff
Labels: type: update, maintainer: open, by: member

#13893 gdbm: update to 1.23
  databases/gdbm/Portfile
Labels: type: update, maintainer: none

#13894 screen: fix portfile
  sysutils/screen/Portfile
Labels: maintainer: open

#13895 py-numpy: update to 1.22.2
  python/py-numpy/Portfile
  python/py-numpy/files/patch-setuptools_setup.py.diff
Labels: type: update, maintainer: open, by: member

#13875 Faudio: remove obsolete port
  audio/FAudio/Portfile
  audio/FAudio/files/patch-faudio-remove-deployment-target.diff
Labels: maintainer: none

#13847 libsdl2_ttf: require C++11 and allow GCC
  devel/libsdl2_ttf/Portfile
Labels: type: bugfix, maintainer: open

#13771 pangomm: Fix broken pango includes
  x11/pangomm/Portfile
  x11/pangomm/files/patch-pango-include.diff
Labels: maintainer: open

#13903 fava: upgrade to 1.20.1
  python/fava/Portfile
Labels: type: enhancement, maintainer: open

#13897 gobject-introspection-devel: update to 1.70.0
  gnome/gobject-introspection-devel/Portfile
  gnome/gobject-introspection-devel/files/no-env-shebang.patch
  gnome/gobject-introspection-devel/files/patch-fix-scanner-in-build-execution.diff
  gnome/gobject-introspection-devel/files/patch-fix-tools-python.diff
  gnome/gobject-introspection-devel/files/patch-giscanner_girparser_py.diff
  gnome/gobject-introspection-devel/files/use-AC_PROG_CPP.patch
Labels: type: update, maintainer: open

#13905 py-httplib2: upgrade to 0.15.0
  python/py-httplib2/Portfile
Labels: type: bugfix, type: enhancement, maintainer: open

#13906 notmuch: Update to version 0.35
  mail/notmuch/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#13866 websocketpp: remove architecture restrictions
  net/websocketpp/Portfile
Labels: maintainer: open, by: member

#13904 openjdk*-openj9: update to OpenJ9 0.30.0
  java/openjdk/Portfile
Labels: type: update, maintainer, maintainer: open

#13910 libreoffice: update to 7.3.0.3
  office/libreoffice/Portfile
Labels: type: update, maintainer, maintainer: open

#13898 py*-beancount: upgrade to 2.3.4
  python/py-beancount/Portfile
Labels: type: enhancement, maintainer: open

#13912 lagrange: update to 1.10.4
  net/lagrange/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#13890 salt: remove EOL 3.5 and 3.6 python versions
  sysutils/salt/Portfile
Labels: maintainer: open, by: member

#13888 py-jupyterlab and deps: add py310 versions.
  python/py-json5/Portfile
  python/py-jupyter_server/Portfile
  python/py-jupyterlab/Portfile
  python/py-jupyterlab_server/Portfile
  python/py-nbclassic/Portfile
Labels: type: enhancement, maintainer: open

#13915 fheroes2: update to 0.9.12
  games/fheroes2/Portfile
Labels: type: update, maintainer, maintainer: open

#13899 MyPaint: require C++11
  graphics/MyPaint/Portfile
Labels: type: bugfix, maintainer: open

#13918 ed: update to 1.18
  editors/ed/Portfile
Labels: type: update, maintainer: none

#13923 vale: A syntax-aware linter for prose
  textproc/vale/Portfile
Labels: type: submission, by: member

#13913 neovim: update to version 0.6.1
  editors/neovim/Portfile
Labels: type: update, maintainer: open

#13925 doxygen: build using Python 3.10
  textproc/doxygen/Portfile
Labels: maintainer: none

#13920 py-tomlkit: update to 0.9.2
  python/py-tomlkit/Portfile
Labels: type: update, maintainer: open, by: member

#13919 input-source-switcher: New port
  sysutils/input-source-switcher/Portfile
Labels: type: submission, by: member

#13930 gradle: update to 7.4
  devel/gradle/Portfile
Labels: type: update, maintainer: open

#13931 google-cloud-sdk: update to 372.0.0
  devel/google-cloud-sdk/Portfile
Labels: type: update, maintainer, maintainer: open

#13928 notcurses: update to 3.0.5
  devel/notcurses/Portfile
Labels: type: bugfix, type: update, maintainer: open

#13934 qt513-qtbase, qt5-qtbase, qt6-qtbase: revbump due to double-conversion update
  aqua/qt5/Portfile
  aqua/qt513/Portfile
  aqua/qt6/Portfile
Labels: type: bugfix, maintainer: open

#13939 micronaut: update to 3.3.1
  java/micronaut/Portfile
Labels: type: update, maintainer, maintainer: open

#13932 gitlab-runner: switch to openmaintainer only
  devel/gitlab-runner/Portfile
Labels: maintainer, maintainer: open

#13943 cbor, cbor2: add python3.10 variant
  python/py-cbor/Portfile
  python/py-cbor2/Portfile
Labels: type: enhancement, maintainer: open

#13942 binutils: update to 2.38
  devel/binutils/Portfile
Labels: type: update, maintainer: none

#13937 protozero: Update to version 1.7.1
  devel/protozero/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#13926 sqlcipher: disable tcl to fix build on old macOS
  databases/sqlcipher/Portfile
Labels: type: enhancement, maintainer, maintainer: open

#13959 skaffold: update to 1.36.0
  devel/skaffold/Portfile
Labels: type: update, maintainer, maintainer: open

#13948 godot: update to 3.4.1
  games/godot/Portfile
Labels: type: update, maintainer

#13949 py-service_identity: add python3.10 variant
  python/py-service_identity/Portfile
Labels: type: enhancement, maintainer: open

#13962 fluent-bit: update to 1.8.12
  sysutils/fluent-bit/Portfile
  sysutils/fluent-bit/files/patch-monkey-flib_libco-memalign.diff
  sysutils/fluent-bit/files/patch-monkey-remove-malloc-h.diff
Labels: type: update, maintainer, maintainer: open, by: member

#13952 py-txaio: add python3.10 subport
  python/py-txaio/Portfile
Labels: type: enhancement, maintainer: none

#13950 py-pytrie: add python3.10 subport
  python/py-pytrie/Portfile
Labels: type: enhancement, maintainer: none

#13963 godot: update to 3.4.2
  games/godot/Portfile
  games/godot/files/patch-available2macro-os_osx.diff
Labels: type: update, maintainer

#13908 poppler: update to 22.02.0
  graphics/poppler/Portfile
  graphics/poppler/files/patch-check-boost.diff
  graphics/poppler/files/patch-cmake_modules_PopplerMacros.cmake.diff
  graphics/poppler/files/patch-glib_CMakeFiles.txt-fix-include-ordering.diff
  graphics/poppler/files/patch-trac-57167.diff
Labels: type: enhancement, type: update, maintainer: open, by: member

#13953 py-txtorcon: add python3.10 subport
  python/py-txtorcon/Portfile
Labels: type: enhancement, maintainer: open

#13954 py-u-msgpack-python: add python3.10 subport
  python/py-u-msgpack-python/Portfile
Labels: type: enhancement, maintainer: open

#13947 python-snappy: add python3.10 subport
  python/py-python-snappy/Portfile
Labels: type: enhancement, maintainer: open

#13945 py-pypng: add python3.10 subport
  python/py-pypng/Portfile
Labels: type: enhancement, maintainer: open

#13965 vtm: submission
  sysutils/vtm/Portfile
  sysutils/vtm/files/patch-so_nosigpipe.patch
Labels: type: submission

#13966 vttest: update to 20210210
  devel/vttest/Portfile
Labels: type: update, maintainer: none

#13969 hugo: update to 0.92.2
  www/hugo/Portfile
Labels: type: update, maintainer, maintainer: open

#13968 bitwarden-cli: Update to 1.21.0
  security/bitwarden-cli/Portfile
Labels: type: update, maintainer, maintainer: open

#13941 nano: update to 6.1
  editors/nano/Portfile
Labels: type: update, maintainer: open

#13972 py-spake2: add python3.10 variant
  python/py-spake2/Portfile
Labels: type: enhancement, maintainer: none

#13971 arangodb: Update to version 3.8.5.1
  databases/arangodb/Portfile
Labels: type: update, maintainer: none

#13973 py-pyqrcode: add python3.10 subport
  python/py-pyqrcode/Portfile
Labels: type: enhancement, maintainer: open

#13974 step-ca: new port
  security/step-ca/Portfile
Labels: type: submission, by: member

#13977 libarchive: update to 3.6.0
  archivers/libarchive/Portfile
Labels: type: update, maintainer: open, by: member

#13980 py-django-debug-toolbar: update to 2.2.1, py38, 39 subports
  python/py-django-debug-toolbar/Portfile
Labels: type: enhancement, type: update, type: security fix, maintainer: none

#13982 jreleaser: update to version v1.0.0-M2
  devel/jreleaser/Portfile
Labels: type: enhancement, type: update, maintainer

#13869 py*-google-auth: upgrade to 2.6.0
  python/py-google-auth/Portfile
Labels: type: enhancement, maintainer: open

#13993 py-gitpython: update to 3.1.26
  python/py-gitpython/Portfile
Labels: type: update, maintainer: none

#13988 global: update to 6.6.8 and python3.10
  devel/global/Portfile
Labels: type: update, maintainer: none

#13992 libreoffice: update to 7.3.1.1
  office/libreoffice/Portfile
Labels: type: update, maintainer, maintainer: open

#13999 bitwarden-cli: Update to version 1.21.1
  security/bitwarden-cli/Portfile
Labels: type: update, maintainer, maintainer: open

#13998 vtm: update to 0.6.0
  sysutils/vtm/Portfile
  sysutils/vtm/files/patch-so_nosigpipe.patch
Labels: type: update, maintainer, maintainer: open

#13997 openjdk11-*: update to 11.0.14.1
  java/openjdk/Portfile
Labels: type: update, maintainer, maintainer: open

#13981 ssh-askpass: New port
  security/ssh-askpass/Portfile
  security/ssh-askpass/files/patch-fix-prefix.diff
Labels: type: submission, by: member

#14005 lean: update to version 3.39.1
  math/lean/Portfile
Labels: type: update, maintainer, maintainer: open

#14009 py-httplib2: Add missing dependency py-parsing
  python/py-httplib2/Portfile
Labels: type: bugfix, maintainer: open

#14010 elixir: update to version 1.13.3
  lang/elixir/Portfile
Labels: type: update, maintainer: requires approval

#14015 google-cloud-sdk: update to 373.0.0
  devel/google-cloud-sdk/Portfile
Labels: type: update, maintainer, maintainer: open

#14013 micronaut: update to 3.3.3
  java/micronaut/Portfile
Labels: type: update, maintainer, maintainer: open

#14014 spring-boot-cli: update to 2.6.3
  java/spring-boot-cli/Portfile
Labels: type: update, maintainer, maintainer: open

#13987 ncdu, ncdu1: Create subport for 1.x version
  sysutils/ncdu/Portfile
Labels: maintainer, maintainer: open, by: member

#13996 reposurgeon: new port (version 4.31)
  devel/reposurgeon/Portfile
Labels: type: submission, by: member

#14021 openjdk11-zulu: update to 11.54.25
  java/openjdk/Portfile
Labels: type: update, maintainer, maintainer: open

#13805 teg: update to 0.12.0
  games/teg/Portfile
  games/teg/files/autogen.sh
  games/teg/files/patch-configure.in.diff
  games/teg/files/patch-tegdebug.diff
Labels: type: update, maintainer: none

#14020 drupal7: update to 7.87
  www/drupal7/Portfile
Labels: type: bugfix, type: update, type: security fix, maintainer: none

#14016 clojure: include tools.edn
  lang/clojure/Portfile
Labels: type: enhancement, maintainer: open

#13989 gengetopt: update to 2.23
  devel/gengetopt/Portfile
Labels: type: update, maintainer: open

#13955 vecLibFort: Update to 0.4.3
  devel/vecLibFort/Portfile
  devel/vecLibFort/files/patch-Makefile.diff
  devel/vecLibFort/files/patch-add-local-vecLib-760.100-header.diff
  devel/vecLibFort/files/patch-vecLibFort.diff
Labels: type: update, maintainer: requires approval, maintainer: timeout, by: member

#14000 lcms2: update to 2.13.1
  graphics/lcms2/Portfile
Labels: type: enhancement, type: update, maintainer: none

#13970 lanHEP: fix compiler selection and require C99
  science/lanHEP/Portfile
Labels: type: bugfix, maintainer: none

#13933 gdb: update to 11.2, provide patch to avoid lock-ups
  devel/gdb/Portfile
  devel/gdb/files/patch-darwin-nat.c.diff
Labels: type: bugfix, maintainer: none

#14023 teg: require C++17 and remove obsolete configure flag
  games/teg/Portfile
Labels: type: bugfix, maintainer: none

#13991 libarchive: Use muniversal portgroup
  archivers/libarchive/Portfile
Labels: type: bugfix, maintainer: open

#13909 miniserve: Update to 0.19.1
  net/miniserve/Portfile
  net/miniserve/files/patch-Cargo-toml-remove-git-package.diff
Labels: type: update, maintainer, maintainer: open, by: member

#14029 openssl11: Update to 1.1.1m
  devel/openssl11/Portfile
  devel/openssl11/files/patch-pre-Sierra.diff
Labels: type: bugfix, type: update, maintainer, type: security fix, by: member

#14028 dblatex: Update to 0.3.12, use Python 3.10
  textproc/dblatex/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#14026 py-humanize: add python 3.10 subport
  python/py-humanize/Portfile
Labels: type: enhancement, maintainer: open

#13967 notcurses: update to 3.0.6
  devel/notcurses/Portfile
Labels: type: bugfix, type: update, maintainer: open

#14034 rust: fix compiler_builtins version mis-match
  lang/rust/Portfile
  lang/rust/files/compiler_builtins.diff
Labels: type: bugfix, maintainer: open

#14018 emacs{,-app}-devel: update to 20220213
  editors/emacs/Portfile
Labels: type: update, maintainer: open, by: member

#14040 supertuxkart: fix build on 10.9 and earlier
  games/supertuxkart/Portfile
Labels: type: bugfix, maintainer: none

#14041 py-readability-lxml: Submission
  python/py-readability-lxml/Portfile
Labels: type: submission

#14030 dosbox-x: update to version 0.83.22, add sdl1 variant
  emulators/dosbox-x/Portfile
  emulators/dosbox-x/files/patch-build-macosx.diff
  emulators/dosbox-x/files/patch-futimens.diff
Labels: type: update, maintainer: none

#14048 bind9: fix include flag ordering
  net/bind9/Portfile
  net/bind9/files/flag_order.patch
Labels: type: bugfix, maintainer: requires approval, by: member

#14036 librsvg: update to 2.52.6 on 10.7+
  graphics/librsvg/Portfile
Labels: type: update, maintainer: open

#14050 py-tomlkit: update to 0.10.0
  python/py-tomlkit/Portfile
Labels: type: update, maintainer: open, by: member

#13985 imlib2: disable SVG support on 10.6 and earlier
  graphics/imlib2/Portfile
Labels: type: bugfix, maintainer: none

#14054 openssl11: fix build on Tiger
  devel/openssl11/Portfile
  devel/openssl11/files/patch-crypto-rand-tiger.diff
Labels: type: bugfix, maintainer: requires approval

#14024 gnome-voice: new port
  gnome/gnome-voice/Portfile
Labels: type: enhancement, type: submission

#14027 lanHEP: restore compilers support
  science/lanHEP/Portfile
Labels: maintainer: none

#13074 moltenvk: update to 1.1.7
  graphics/MoltenVK/Portfile
Labels: type: enhancement, type: update, maintainer: open

#14060 rdfind: Update to upstream version 1.5.0
  sysutils/rdfind/Portfile
Labels: type: update, maintainer: none

#14058 poetry: update to 1.1.13
  python/poetry/Portfile
  python/poetry/files/patch-requirements.diff
Labels: type: enhancement, type: update, maintainer, maintainer: open
