Repository macports/macports-ports, pull requests merged in 2023-04, with the labels that each got.

#18155 groovy: platforms is {darwin any}
  lang/groovy/Portfile
Labels: type: enhancement, maintainer: open, by: member

#18158 fortran-stdlib: update to 2023.03.08
  lang/fortran-stdlib/Portfile
Labels: type: update, maintainer, maintainer: open

#18157 ruby-devel: update to 2023.04.01
  lang/ruby-devel/Portfile
Labels: type: update, maintainer, maintainer: open

#18154 ruby-install: update to version 0.9.0
  ruby/ruby-install/Portfile
Labels: type: update, maintainer, maintainer: open

#18160 CLI11: update to 2.3.2
  devel/CLI11/Portfile
Labels: type: update, maintainer: open

#18162 solfege: Update homepage; add size to checksums
  audio/solfege/Portfile
Labels: type: update, maintainer: requires approval, by: member

#18163 R: unbreak build after curl update
  math/R/Portfile
  math/R/files/patch-curl.diff
Labels: type: bugfix, maintainer: open

#18168 liblsl: New port
  science/liblsl/Portfile
Labels: type: submission

#18176 datree: update to version 1.8.51
  devel/datree/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#18180 py-zstd: add subport py311-zstd
  python/py-zstd/Portfile
Labels: type: enhancement, maintainer: none

#18164 py-mupdf: new port (PyMuPDF)
  graphics/mupdf/Portfile
  python/py-mupdf/Portfile
  python/py-mupdf/files/setup.py.diff
Labels: type: enhancement, type: submission, maintainer: open

#18187 clojure: update to 1.11.1.1273
  lang/clojure/Portfile
Labels: type: update, maintainer, maintainer: open

#18181 google-cloud-sdk: update to 425.0.0
  devel/google-cloud-sdk/Portfile
Labels: type: update, maintainer, maintainer: open

#18182 openjdk20-corretto: new submission
  java/openjdk20-corretto/Portfile
Labels: type: submission

#18190 datree: update to version 1.8.63
  devel/datree/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#18183 py-urwid: add subport py311-urwid
  python/py-urwid/Portfile
Labels: type: enhancement, maintainer: none

#18184 py-pudb: add subports py39-pudb, py310-pudb, py311-pudb
  python/py-pudb/Portfile
Labels: type: enhancement, maintainer: none

#18159 grilo-plugins: use lua PG
  gnome/grilo-plugins/Portfile
Labels: type: enhancement, maintainer: open, by: member

#18193 snac: update to 2.26.
  net/snac/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#18179 qpdf: add legacysupport and use_mp_libcxx
  textproc/qpdf/Portfile
Labels: type: bugfix, maintainer: open

#18196 redis: update to 7.0.10
  databases/redis/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#18200 py-awscli2: update to 2.11.9
  python/py-awscli2/Portfile
  python/py-awscli2/files/patch-requirements.diff
Labels: type: enhancement, type: update, maintainer, maintainer: open

#18199 poetry: update to 1.4.2
  python/poetry/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#18197 pgbadger: update to 12.1
  databases/pgbadger/Portfile
Labels: type: enhancement, type: update, maintainer: none

#18202 Gildas: update to 202304a
  science/gildas/Portfile
Labels: type: enhancement, type: update, maintainer

#18140 vtk: add python310 and python311 variants
  graphics/vtk/Portfile
Labels: type: enhancement, maintainer: open

#18128 git-annex: update to 10.20230321
  devel/git-annex/Portfile
Labels: type: enhancement, type: update, maintainer: none

#18171 libvidstab: fix build for PPC
  multimedia/libvidstab/Portfile
  multimedia/libvidstab/files/0001-serialize.c-fix-for-Darwin-PPC.patch
Labels: type: bugfix, maintainer: none

#18216 linalg: update to 1.7.2
  math/linalg/Portfile
Labels: type: bugfix, type: update, maintainer, maintainer: open

#18210 hiop: update to 0.7.2
  math/hiop/Portfile
Labels: type: update, maintainer, maintainer: open

#18201 py-roman: update to 4.0
  python/py-roman/Portfile
Labels: type: enhancement, type: update, maintainer: open

#18215 [volk-]gnss-sdr: update release to 0.0.18 and devel to 20230407-306c566d
  science/gnss-sdr/Portfile
  science/volk-gnss-sdr/Portfile
Labels: type: bugfix, type: update, maintainer, maintainer: open

#18218 adept2: update to 2023.03.30
  math/adept2/Portfile
Labels: type: update, maintainer, maintainer: open

#18217 pika: update to 0.14.0
  devel/pika/Portfile
Labels: type: update, maintainer, maintainer: open

#18221 neovim: update to 0.9.0
  editors/neovim/Portfile
Labels: type: update, maintainer: open

#18223 neovim: add @judaew to list of maintainers
  editors/neovim/Portfile
Labels: maintainer: open

#18224 nixpacks: update to version 1.6.1
  devel/nixpacks/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#18222 eigenmath: update to upstream master
  math/eigenmath/Portfile
  math/eigenmath/files/patch-Makefile.diff
Labels: type: update, maintainer, maintainer: open

#18220 fxt: update to 2023.03.23
  math/fxt/Portfile
  math/fxt/files/patch-makefile.diff
Labels: type: update, maintainer, maintainer: open

#18225 lagrange: update to 1.15.8
  net/lagrange/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#18188 ecCodes: update to 2.30.0
  science/ecCodes/Portfile
Labels: type: update, maintainer, maintainer: open

#17860 R-igraphdata: various improvements
  R/R-igraphdata/Portfile
Labels: maintainer: none

#18231 libretroshare: update to upstream master
  net/libretroshare/Portfile
Labels: type: update, maintainer, maintainer: open

#18232 sslscan: update to 2.0.16
  net/sslscan/Portfile
Labels: type: update, maintainer: open, by: member

#18233 madness: update to upstream master
  science/madness/Portfile
Labels: type: update, maintainer, maintainer: open

#18207 cfourcc: update to 0.1.3.1
  multimedia/cfourcc/Portfile
Labels: type: update, maintainer: none

#18170 libavif: fix incorrect configure.arg, add tests variant
  multimedia/libavif/Portfile
Labels: type: bugfix, type: enhancement, maintainer: open

#18204 clang-*: default to +libstdcxx only when needed
  lang/llvm-10/Portfile
  lang/llvm-11/Portfile
  lang/llvm-12/Portfile
  lang/llvm-13/Portfile
  lang/llvm-14/Portfile
  lang/llvm-15/Portfile
  lang/llvm-16/Portfile
  lang/llvm-5.0/Portfile
  lang/llvm-6.0/Portfile
  lang/llvm-7.0/Portfile
  lang/llvm-8.0/Portfile
  lang/llvm-9.0/Portfile
  lang/llvm-devel/Portfile
Labels: maintainer: requires approval, by: member

#18192 clang-*: fix use of -stdlib=macports-libstdc++ on newer machines
  lang/clang-11-bootstrap/Portfile
  lang/llvm-10/Portfile
  lang/llvm-11/Portfile
  lang/llvm-12/Portfile
  lang/llvm-13/Portfile
  lang/llvm-14/Portfile
  lang/llvm-15/Portfile
  lang/llvm-16/Portfile
  lang/llvm-5.0/Portfile
  lang/llvm-6.0/Portfile
  lang/llvm-7.0/Portfile
  lang/llvm-8.0/Portfile
  lang/llvm-9.0/Portfile
  lang/llvm-devel/Portfile
Labels: type: bugfix, type: submission, maintainer: requires approval, by: member

#18205 libopenraw: update to 0.3.4 & use cargo_fetch PG
  graphics/libopenraw/Portfile
Labels: type: update, maintainer: open, by: member

#18212 snac: Fix manpage location, compiler, flags
  net/snac/Portfile
  net/snac/files/Makefile.patch
Labels: maintainer: open, by: member

#18226 proxmark3-iceman: update to v4.16191
  science/proxmark3-iceman/Portfile
Labels: type: update, maintainer, maintainer: open

#18238 mimalloc: update to 2.1.1
  devel/mimalloc/Portfile
Labels: type: update, maintainer, maintainer: open

#18242 liblsl: use boost181, fix build for older systems
  science/liblsl/Portfile
  science/liblsl/files/0001-loguru-fix-for-missing-pthread_is_threaded_np.patch
Labels: type: bugfix, maintainer: none

#18247 fheroes2: update to 1.0.3
  games/fheroes2/Portfile
Labels: type: update, maintainer, maintainer: open

#18246 shadowsocks-libev: new port
  net/shadowsocks-libev/Portfile
Labels: type: enhancement, type: submission

#18248 google-cloud-sdk: update to 426.0.0
  devel/google-cloud-sdk/Portfile
Labels: type: update, maintainer, maintainer: open

#18249 skaffold: update to 2.3.1
  devel/skaffold/Portfile
Labels: type: update, maintainer, maintainer: open

#18250 datree: update to version 1.8.64
  devel/datree/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#17715 mm-common: correct license
  gnome/mm-common/Portfile
Labels: maintainer: open

#18219 ffmpeg-upstream: update to 6.0
  multimedia/ffmpeg-upstream/Portfile
Labels: type: enhancement, type: update, maintainer: open

#18185 opencv4, opencv4-devel, opencv3, opencv3-devel: update Python bindings to 3.11
  graphics/opencv3-devel/Portfile
  graphics/opencv3/Portfile
  graphics/opencv4-devel/Portfile
  graphics/opencv4/Portfile
Labels: type: enhancement, type: update, maintainer: requires approval, maintainer: timeout

#18095 llvm-cx: new port (version 22.1.1)
  lang/llvm-cx/Portfile
Labels: type: submission

#18256 tcsh: update to 6.24.9
  shells/tcsh/Portfile
Labels: type: update, maintainer: none

#18254 Updated to MEME Suite 5.5.2
  science/memesuite/Portfile
Labels: type: update, maintainer, maintainer: open

#18258 llvm-cx: Seems "darwin any" isn't helpful here
  lang/llvm-cx/Portfile
Labels: type: bugfix, maintainer: none

#18266 snac: update to 2.27.
  net/snac/Portfile
  net/snac/files/Makefile.patch
Labels: type: bugfix, type: enhancement, type: update, maintainer, type: security fix, maintainer: open

#18257 openjdk18-temurin: remove obsolete port
  java/openjdk18-temurin/Portfile
Labels: maintainer: none

#18208 frescobaldi: update to 3.3.0
  editors/frescobaldi/Portfile
Labels: type: update, maintainer, maintainer: open

#18265 svt-av1: use legacysupport on 10.5 for _posix_memalign
  multimedia/svt-av1/Portfile
Labels: type: bugfix, maintainer: open

#18272 fpm: update to 0.18.1
  devel/fpm/Portfile
  devel/fpm/files/patch-filesystem_utilities.diff
  devel/fpm/files/patch-install.diff
Labels: type: update, maintainer, maintainer: open

#18280 micronaut: update to 3.8.9
  java/micronaut/Portfile
Labels: type: update, maintainer, maintainer: open

#18279 stern: update to 1.25.0
  sysutils/stern/Portfile
Labels: type: update, maintainer, maintainer: open

#18278 n: update to 9.2
  devel/n/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer, maintainer: open

#18277 gallery-dl: update to 1.25.2
  net/gallery-dl/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer, maintainer: open

#18270 rocksdb: add a patch for MAP_ANON, fix the build
  databases/rocksdb/Portfile
  databases/rocksdb/files/0002-MAP_ANON.patch
Labels: type: bugfix, maintainer: open

#18262 lang/ruby32: update to 3.2.2
  lang/ruby32/Portfile
Labels: type: update, type: security fix, maintainer: open

#18261 nnn: update to 4.8
  sysutils/nnn/Portfile
Labels: type: enhancement, type: update, maintainer: open

#18259 llvm-3.5: remove obsolete port
  lang/llvm-3.5/Portfile
Labels: maintainer: requires approval

#18234 sslscan: fix build for <10.7
  net/sslscan/Portfile
Labels: type: bugfix, maintainer: open

#17930 tmate: Use latest msgpack version
  sysutils/tmate/Portfile
Labels: type: bugfix, maintainer: open

#18260 saga: patch use of finite() non-standard function
  gis/saga/Portfile
  gis/saga/files/patch-me-cpp.diff
Labels: type: bugfix, maintainer: open

#18288 py-argcomplete: update to 3.0.5
  python/py-argcomplete/Portfile
Labels: type: update, maintainer, maintainer: open

#18287 fortune-mod: update to 3.18.0
  games/fortune-mod/Portfile
Labels: type: update, maintainer, maintainer: open

#18286 bsd-games: update to 3.3
  games/bsd-games/Portfile
  games/bsd-games/files/patch-gomoku.diff
Labels: type: update, maintainer, maintainer: open

#18290 datree: update to 1.8.65
  devel/datree/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#18289 crystal: update to 1.8.0
  lang/crystal/Portfile
Labels: type: update, maintainer, maintainer: open

#18293 oksh: update to 7.3
  shells/oksh/Portfile
Labels: type: update, maintainer: open

#18284 hstr: update to 3.0.0
  shells/hstr/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#18300 unxip: Update to 2.1
  archivers/unxip/Portfile
Labels: type: update, maintainer, maintainer: open

#18299 cpp-argparse-dev: update to 1.7.5
  devel/cpp-argparse-dev/Portfile
Labels: type: update, maintainer

#18276 py-scipy: update to 1.10.1
  python/py-scipy/Portfile
Labels: type: update, maintainer: open, by: member

#18283 wireshark4: update to 4.0.5
  net/wireshark4/Portfile
Labels: type: update, maintainer: requires approval, by: member

#18315 Serial-Studio: new port
  sysutils/Serial-Studio/Portfile
Labels: type: enhancement, type: submission

#18316 wasmer: update to 3.2.0
  lang/wasmer/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#18311 tetgen: new port
  science/tetgen/Portfile
  science/tetgen/files/cmake-fix.diff
Labels: type: enhancement, type: submission

#18281 gobject-introspection-devel: downgrade dependency to glib2-devel
  gnome/gobject-introspection-devel/Portfile
Labels: type: enhancement, maintainer: open

#18320 micronaut: update to 3.9.0
  java/micronaut/Portfile
Labels: type: update, maintainer, maintainer: open

#18337 hstr: update to 3.1.0
  shells/hstr/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#18321 google-cloud-sdk: update to 427.0.0
  devel/google-cloud-sdk/Portfile
Labels: type: update, maintainer, maintainer: open

#18305 privoxy: Update to version 3.0.34
  www/privoxy/Portfile
Labels: type: update, maintainer, maintainer: open

#18301 libocca: update patch to fix clang builds on <10.12
  devel/libocca/files/0003-Check-for-CLOCK_UPTIME_RAW-on-macOS-before-using-it.patch
Labels: type: bugfix, type: update, maintainer, maintainer: open

#18263 isl-devel: update to 0.26
  devel/isl-devel/Portfile
Labels: type: update, maintainer: none

#17050 gjs-devel: update to 1.74.1
  gnome/gjs-devel/Portfile
Labels: type: update, maintainer: open

#18340 toml-f: new port in fortran
  fortran/toml-f/Portfile
  fortran/toml-f/files/patch-no-tests.diff
Labels: type: submission

#18336 openjdk11-sap: update to 11.0.19
  java/openjdk11-sap/Portfile
Labels: type: update, maintainer, maintainer: open

#18335 openjdk20-sap: update to 20.0.1
  java/openjdk20-sap/Portfile
Labels: type: update, maintainer, maintainer: open

#18334 openjdk17-sap: update to 17.0.7
  java/openjdk17-sap/Portfile
Labels: type: update, maintainer, maintainer: open

#18333 openjdk20-corretto: update to 20.0.1.9.1
  java/openjdk20-corretto/Portfile
Labels: type: update, maintainer, maintainer: open

#18332 openjdk8-corretto: update to 8.372.07.1
  java/openjdk8-corretto/Portfile
Labels: type: update, maintainer, maintainer: open

#18331 openjdk11-corretto: update to 11.0.19.7.1
  java/openjdk11-corretto/Portfile
Labels: type: update, maintainer, maintainer: open

#18330 openjdk17-corretto: update to 17.0.7.7.1
  java/openjdk17-corretto/Portfile
Labels: type: update, maintainer, maintainer: open

#18324 openjdk11-zulu: update to 11.64.19
  java/openjdk11-zulu/Portfile
Labels: type: update, maintainer, maintainer: open

#18323 openjdk17-zulu: update to 17.42.19
  java/openjdk17-zulu/Portfile
Labels: type: update, maintainer, maintainer: open

#18322 openjdk20-zulu: update to 20.30.11
  java/openjdk20-zulu/Portfile
Labels: type: update, maintainer, maintainer: open

#18317 openjdk20-oracle: update to 20.0.1
  java/openjdk20-oracle/Portfile
Labels: type: update, maintainer, maintainer: open

#18319 jdk17: update to 17.0.7
  java/jdk17/Portfile
Labels: type: update, maintainer, maintainer: open

#18318 jdk20: update to 20.0.1
  java/jdk20/Portfile
Labels: type: update, maintainer, maintainer: open

#18304 proxmark3-iceman: enhance envs and fix library deps
  science/proxmark3-iceman/Portfile
Labels: maintainer, maintainer: open

#18306 hut: new port, CLI for SourceHut API
  devel/hut/Portfile
Labels: type: enhancement, type: submission

#18294 nim: update to 1.6.12
  lang/nim/Portfile
Labels: type: enhancement, type: update, maintainer: open

#18342 fortran-rpn-calc: new port
  fortran/fortran-rpn-calc/Portfile
Labels: type: submission

#18344 toml-f: build should depend on git for <10.9
  fortran/toml-f/Portfile
Labels: type: bugfix, maintainer, maintainer: open

#18347 fnc: update to 0.15
  devel/fnc/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer, maintainer: open

#18346 fortran-xml: new port
  fortran/fortran-xml/Portfile
  fortran/fortran-xml/files/patch-CMakeLists.diff
Labels: type: submission

#18351 R-Rcpp: fix for 10.4
  R/R-Rcpp/Portfile
  R/R-Rcpp/files/patch-tiger.diff
Labels: type: bugfix, maintainer, maintainer: open

#18285 onetbb: update to 2021.9.0
  devel/onetbb/Portfile
  devel/onetbb/files/patch-onetbb-older-platforms.diff
Labels: type: update, maintainer, maintainer: open

#18353 qrcp: Update to 0.10.1, fix license
  sysutils/qrcp/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#18354 Bear: Update to 3.1.1
  devel/Bear/Portfile
Labels: type: bugfix, type: update, maintainer, maintainer: open, by: member

#18355 borgmatic: Update to 1.7.12
  sysutils/borgmatic/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#18360 scala3.2: update to 3.2.2
  lang/scala/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#18206 coreutils-uutils: update to 0.0.18
  sysutils/coreutils-uutils/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#18362 vtm: update to 0.9.9c
  sysutils/vtm/Portfile
Labels: type: update, maintainer: none

#18364 mysql8: update to 8.0.33
  databases/mysql8/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#18366 openssl3: Fix CVE-2023-1255
  devel/openssl3/Portfile
  devel/openssl3/files/bc2f61ad70971869b242fc1cb445b98bad50074a.patch
Labels: maintainer, type: security fix, maintainer: open, by: member

#18365 gjs-devel: update to 1.76.0
  gnome/gjs-devel/Portfile
  gnome/gjs-devel/files/patch-gjs-skip-gtk-tests.diff
Labels: type: update, maintainer: open

#18359 varnish: update to 7.3.0
  www/varnish/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#16865 ipopt: update to 3.14.12
  math/ipopt/Portfile
Labels: type: bugfix, maintainer, maintainer: open

#18378 vtm: update to 0.9.9d
  sysutils/vtm/Portfile
Labels: type: update, maintainer: none

#18376 icu-devel: update to 73.1
  devel/icu-devel/Portfile
  devel/icu-devel/files/patch-balign-to-align.diff
  devel/icu-devel/files/patch-cinttypes-header.diff
Labels: type: enhancement, type: update, maintainer, maintainer: open

#18375 sbt: update to 1.8.2
  devel/sbt/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#18341 py-semver: update to 3.0.0
  python/py-semver/Portfile
Labels: type: update, maintainer: open, by: member

#18373 openjdk17-microsoft: update to 17.0.7
  java/openjdk17-microsoft/Portfile
Labels: type: update, maintainer, maintainer: open

#18372 openjdk20-temurin: update to 20.0.1
  java/openjdk20-temurin/Portfile
Labels: type: update, maintainer, maintainer: open

#18371 openjdk8-temurin: update to 8u372
  java/openjdk8-temurin/Portfile
Labels: type: update, maintainer, maintainer: open

#18370 openjdk11-temurin: update to 11.0.19
  java/openjdk11-temurin/Portfile
Labels: type: update, maintainer, maintainer: open

#18369 openjdk17-temurin: update to 17.0.7
  java/openjdk17-temurin/Portfile
Labels: type: update, maintainer, maintainer: open

#18368 spring-boot-cli: update to 3.0.6
  java/spring-boot-cli/Portfile
Labels: type: update, maintainer, maintainer: open

#18367 openjdk8-zulu: update to 8.70.0.23
  java/openjdk8-zulu/Portfile
Labels: type: update, maintainer, maintainer: open

#18374 py-imagehash: Submission
  python/py-imagehash/Portfile
Labels: type: submission
