Repository macports/macports-ports, pull requests merged in 2023-03, with the labels that each got.

#17823 clojure: update to 1.11.1.1237
  lang/clojure/Portfile
Labels: type: update, maintainer, maintainer: open

#17132 py-toposort: new port
  python/py-toposort/Portfile
Labels: type: submission

#17801 cppcheck: Switch to Python 3.11
  devel/cppcheck/Portfile
Labels: maintainer: open, by: member

#17797 cppman: Update to 0.5.4, add groff dep, switch to Python 3.11
  lang/cppman/Portfile
Labels: type: bugfix, maintainer: open, by: member

#17840 py-exifread: add py311 subport
  python/py-exifread/Portfile
Labels: maintainer: open

#17841 datree: updated to version 1.8.33
  devel/datree/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#17825 cairo,cairo-devel: use -std=gnu99 with gcc-4
  graphics/cairo-devel/Portfile
  graphics/cairo/Portfile
Labels: type: bugfix, maintainer: requires approval

#17842 Gildas: update to 202303a
  science/gildas/Portfile
Labels: type: enhancement, type: update, maintainer

#17837 opendoas: update to 6.8.2
  sysutils/opendoas/Portfile
Labels: type: update, maintainer: requires approval

#17843 swi-prolog-devel: Updated to version 9.1.7
  lang/swi-prolog-devel/Portfile
Labels: type: update, maintainer, maintainer: open

#17845 qBittorrent-qt5: put legacysupport lines in the right place
  net/qBittorrent-qt5/Portfile
Labels: type: bugfix, maintainer, maintainer: open, by: member

#17850 py-awscli2: update to 2.11.0
  python/py-awscli2/Portfile
  python/py-awscli2/files/patch-requirements.diff
Labels: type: enhancement, type: update, maintainer, maintainer: open

#17811 fossil: update to 2.21
  devel/fossil/Portfile
Labels: type: enhancement, type: update, maintainer: requires approval, maintainer: timeout

#17851 nixpacks: updated to version 1.4.1
  devel/nixpacks/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#17852 spring-boot-cli: update to 3.0.4
  java/spring-boot-cli/Portfile
Labels: type: update, maintainer, maintainer: open

#17846 ruby-devel: update to current upstream
  lang/ruby-devel/Portfile
Labels: type: update, maintainer, maintainer: open

#17855 libretroshare: update to current upstream
  net/libretroshare/Portfile
  net/libretroshare/files/0001-Fix-CMakeLists-for-MacPorts.patch
  net/libretroshare/files/0001-rsfile.h-fix-for-macOS-add-missing-headers.patch
  net/libretroshare/files/0002-rsdnsutils.patch
Labels: type: update, maintainer, maintainer: open

#17856 xcodes: updated to version 1.3.0
  devel/xcodes/Portfile
Labels: type: enhancement, type: update, maintainer: none

#17857 gocryptfs: Update to version 2.3.1
  fuse/gocryptfs/Portfile
Labels: type: update, maintainer, maintainer: open

#17861 libvpx: explicitly require c++11 and fix link
  multimedia/libvpx/Portfile
Labels: type: bugfix, maintainer: open, by: member

#17862 dnscontrol: update to 3.27.1
  sysutils/dnscontrol/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#17864 josm: update to 18678
  gis/JOSM/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#17869 GPXSee: update to 12.2
  gis/GPXSee/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#17865 nng: new port in devel
  devel/nng/Portfile
  devel/nng/files/patch-old-gcc.diff
  devel/nng/files/patch-posix_resolv_gai.diff
  devel/nng/files/patch-tests.diff
Labels: type: submission

#17859 git-cola: update to 4.1.0
  devel/git-cola/Portfile
  devel/git-cola/files/patch-pyqt-version.diff
Labels: type: update, maintainer: open, by: member

#17870 snac: update to 2.24.
  net/snac/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer, maintainer: open

#17872 azmq: new port in devel
  devel/azmq/Portfile
Labels: type: submission

#17844 fnm: update to 1.33.1
  devel/fnm/Portfile
Labels: type: update, maintainer: open, by: member

#17871 nixpacks: updated to version 1.4.2
  devel/nixpacks/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#17868 ruby-devel: technical update due to updated minitest with upstream
  lang/ruby-devel/Portfile
Labels: type: bugfix, maintainer, maintainer: open

#17440 vte: update to 0.70.2
  gnome/vte/Portfile
  gnome/vte/files/autogen.sh
  gnome/vte/files/patch-src-pty.cc.diff
  gnome/vte/files/patch-src-vteutils.cc.diff
  gnome/vte/files/patch-vte-gsize.diff
Labels: type: bugfix, type: enhancement, type: update, maintainer: open

#17879 hamlib: set cxx_standard 2011, required by configure
  science/hamlib/Portfile
Labels: type: bugfix, maintainer: open

#17820 kubectl_select: keep completions directory
  sysutils/kubectl/Portfile
Labels: type: bugfix, maintainer: open

#17888 rakudo and friends: update to 2023.02
  lang/MoarVM/Portfile
  lang/nqp/Portfile
  lang/rakudo/Portfile
Labels: type: update, maintainer: open

#17876 cppcheck: update to 2.10.2
  devel/cppcheck/Portfile
Labels: type: update, maintainer: open

#17156 py-milc: new port
  python/py-milc/Portfile
Labels: type: submission

#17827 neovim: update to 0.8.3
  editors/neovim/Portfile
Labels: type: update, maintainer: open

#17886 jemalloc: backport linking fix from upstream
  devel/jemalloc/Portfile
  devel/jemalloc/files/patch-Makefile.diff
Labels: type: bugfix, maintainer: none

#17506 py-virtualfish: added missed dependencies
  python/py-virtualfish/Portfile
Labels: type: enhancement, maintainer: none

#17895 clojure: update to 1.11.1.1252
  lang/clojure/Portfile
Labels: type: update, maintainer, maintainer: open

#17896 mpich/mpi-doc: 4.1.1
  science/mpi-doc/Portfile
  science/mpich/Portfile
Labels: maintainer: requires approval, by: member

#17898 go: update to 1.20.2
  lang/go/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#17897 syncthing: update to v1.23.2
  net/syncthing/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer: open

#17893 py-emcee3: update to 3.1.4
  python/py-emcee3/Portfile
Labels: type: enhancement, type: update, maintainer: open

#17899 skaffold: update to 2.2.0
  devel/skaffold/Portfile
Labels: type: update, maintainer, maintainer: open

#17894 FastAD: new port in math
  math/FastAD/Portfile
  math/FastAD/files/patch-gtest.diff
Labels: type: submission

#17890 BWidget: update to 1.9.16
  x11/BWidget/Portfile
Labels: type: bugfix, type: update, maintainer: none

#17858 macos-fortress: Update to version 2023.03.04
  net/macos-fortress/Portfile
  net/macos-fortress/files/proxy.pac
Labels: type: update, maintainer, maintainer: open

#17903 spice-gtk: Fix +quartz variant
  gnome/spice-gtk/Portfile
Labels: type: bugfix, maintainer: none, by: member

#17905 tilemaker: update to 2.3.0
  gis/tilemaker/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#17902 py-csvkit: update to 1.1.1, with support for python 3.11
  python/py-agate-dbf/Portfile
  python/py-agate-excel/Portfile
  python/py-agate-sql/Portfile
  python/py-agate/Portfile
  python/py-csvkit/Portfile
  python/py-csvkit/files/py311-csvkit
  python/py-dbfread/Portfile
  python/py-leather/Portfile
  python/py-pytimeparse/Portfile
Labels: type: enhancement, type: update, maintainer: open

#17884 py-trove-classifiers: update to 2023.2.20
  python/py-trove-classifiers/Portfile
Labels: type: enhancement, type: update, maintainer: none

#17906 lagrange: update to 1.15.3
  net/lagrange/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#17910 got: update to 0.85.
  devel/got/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer, maintainer: open

#17909 paho.mqtt.c: update to 1.3.12
  net/paho.mqtt.c/Portfile
Labels: type: enhancement, type: update, maintainer: none

#17908 google-cloud-sdk: update to 421.0.0
  devel/google-cloud-sdk/Portfile
Labels: type: update, maintainer, maintainer: open

#17911 terraform: new subport for 1.4
  sysutils/terraform/Portfile
Labels: maintainer, maintainer: open, by: member

#17818 py-nbconvert: Remove custom fetch code
  python/py-nbconvert/Portfile
Labels: maintainer: open, by: member

#17915 keybase: update to version 6.0.4
  security/keybase/Portfile
Labels: type: update, maintainer: none

#17874 texinfo: fix universal build with GCC
  textproc/texinfo/Portfile
Labels: type: bugfix, maintainer: none

#17912 ruby-build: Update to v20230309
  ruby/ruby-build/Portfile
Labels: type: update, maintainer, maintainer: open

#17921 nixpacks: updated to version 1.5.0
  devel/nixpacks/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#17853 zenmap: update to 7.93
  net/zenmap/Portfile
Labels: type: update, maintainer: requires approval, maintainer: timeout, by: member

#17919 emacs{-app,}-devel: update to 20230308
  editors/emacs/Portfile
Labels: type: update, maintainer: open, by: member

#17788 wxWidgets-3.2: Fix universal build
  graphics/wxWidgets-3.2/Portfile
Labels: type: bugfix, maintainer: open

#17900 git-devel: new subport for development version of git (version 2.40.0-rc2)
  devel/git/Portfile
Labels: maintainer, maintainer: open, by: member

#17926 lagrange: update to 1.15.4
  net/lagrange/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#17933 asciidoc: Fix documentation install directory
  textproc/asciidoc/Portfile
Labels: type: bugfix, maintainer, maintainer: open, by: member

#17934 borgbackup: Allow msgpack 1.0.5
  sysutils/borgbackup/Portfile
  sysutils/borgbackup/files/2842463f21499e3cb0258283ba4f0e349e46678e.patch
Labels: type: bugfix, maintainer: open, by: member

#17923 dnscrypt-proxy: update to 2.1.4
  net/dnscrypt-proxy/Portfile
Labels: type: update, maintainer: none

#17938 i2pd: update to 2.47.0
  security/i2pd/Portfile
Labels: type: update, maintainer: open, by: member

#17940 jreleaser: update to version 1.5.1
  devel/jreleaser/Portfile
Labels: type: enhancement, type: update, maintainer

#17883 py-prompt_toolkit: update to 3.0.38
  python/py-prompt_toolkit/Portfile
Labels: type: enhancement, type: update, maintainer: open

#17878 raja: new port in devel
  devel/raja/Portfile
  devel/raja/files/patch-throw-away-desul.diff
Labels: type: submission

#17655 cpmtools: update to 2.24
  sysutils/cpmtools/Portfile
Labels: type: update, maintainer: open

#17536 py-sisynala: delete deprecated port
  python/py-sisynala/Portfile
  python/py-sisynala/files/patch-setup.py.diff
Labels: maintainer: none

#17945 gnuplot: use lua PG
  math/gnuplot/Portfile
Labels: type: enhancement, maintainer: open, by: member

#17948 datree: updated to version 1.8.39
  devel/datree/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#17928 asciinema: update to 2.2.0
  sysutils/asciinema/Portfile
Labels: type: update, maintainer: requires approval, by: member

#17954 lua-luazip: use luarocks_org PG
  lua/lua-luazip/Portfile
Labels: type: enhancement, maintainer: open, by: member

#17956 GrandPerspective: update to 3.1.0
  aqua/GrandPerspective/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#17955 fheroes2: update to 1.0.2
  games/fheroes2/Portfile
Labels: type: update, maintainer, maintainer: open

#17951 fricas: patch for sbcl version 2.3.2
  math/fricas/Portfile
  math/fricas/files/sbcl-2.3.2.patch
Labels: type: bugfix, maintainer, maintainer: open

#14919 ocaml-dune: update to 3.7.0
  ocaml/ocaml-dune/Portfile
Labels: type: enhancement, type: update, maintainer: open

#17958 snac: update to 2.25.
  net/snac/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer, maintainer: open

#17959 tbls: update to 1.63.0
  databases/tbls/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#17960 plumed: update to v2.8.2
  science/plumed/Portfile
Labels: type: update, maintainer, maintainer: open

#17946 highlight: use lua PG and makefile PG features
  textproc/highlight/Portfile
Labels: type: enhancement, maintainer: open, by: member

#17963 parallel: update to 20230222
  sysutils/parallel/Portfile
Labels: type: enhancement, type: update, maintainer: open, by: member

#17939 libtorrent-rasterbar: add python311 variant
  net/libtorrent-rasterbar/Portfile
Labels: maintainer, maintainer: open, by: member

#17967 tree-sitter-cli: add runtime NodeJS depencency, don't fetch deps at build time
  devel/tree-sitter/Portfile
Labels: type: bugfix, type: enhancement, maintainer: open, by: member

#17972 groovy: update to 4.0.10
  lang/groovy/Portfile
Labels: type: update, maintainer, maintainer: open

#17971 stern: update to 1.24.0
  sysutils/stern/Portfile
Labels: type: update, maintainer, maintainer: open

#17973 goimapnotify: New port
  mail/goimapnotify/Portfile
Labels: type: submission, by: member

#17932 MacVim, vim: update & use lua PG
  editors/MacVim/Portfile
  editors/MacVim/files/patch-python.diff
  editors/MacVim/files/patch-python3.diff
  editors/MacVim/files/patch-remove-updater.diff
  editors/MacVim/files/patch-tcl.diff
  editors/vim/Portfile
  editors/vim/files/patch-python.diff
  editors/vim/files/patch-python3.diff
  editors/vim/files/patch-tcl.diff
Labels: type: enhancement, maintainer: requires approval, by: member

#17974 google-cloud-sdk: update to 422.0.0
  devel/google-cloud-sdk/Portfile
Labels: type: update, maintainer, maintainer: open

#17977 nco: update to 5.1.5
  science/nco/Portfile
Labels: type: update, maintainer, maintainer: open

#17978 datree: update to version 1.8.41
  devel/datree/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#17979 eccodes: update to 2.29.0
  science/ecCodes/Portfile
Labels: type: update, maintainer, maintainer: open

#17936 lua-argparse: use luarocks_org PG
  lua/lua-argparse/Portfile
Labels: type: enhancement, maintainer: open, by: member

#17935 lua-ansicolors: use luarocks_org PG
  lua/lua-ansicolors/Portfile
Labels: type: enhancement, maintainer: open, by: member

#17983 datree: update to version 1.8.42
  devel/datree/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#17982 solidity: new port in lang
  lang/solidity/Portfile
  lang/solidity/files/fmtlib.cmake
  lang/solidity/files/jsoncpp.cmake
  lang/solidity/files/patch-cmake_range-v3.cmake.diff
  lang/solidity/files/patch-libsolutil_JSON.cpp.diff
Labels: type: submission

#17943 edje: use lua PG (and other tweaks)
  graphics/edje/Portfile
Labels: type: enhancement, maintainer: open, by: member

#17937 swig*: do not build with versioned Lua binary
  devel/swig/Portfile
  devel/swig3/Portfile
Labels: type: enhancement, maintainer: open, by: member

#17941 lua-luafilesystem: use luarocks_org PG
  lua/lua-luafilesystem/Portfile
Labels: type: enhancement, maintainer: open, by: member

#17947 lua-checks: use luarocks_org PG
  lua/lua-checks/Portfile
Labels: type: enhancement, maintainer: open, by: member

#17981 openssl3: Fix build with Apple clang 7.0.0-10.0.0
  devel/openssl3/Portfile
  devel/openssl3/files/avx512.patch
Labels: maintainer: open, by: member

#17949 lua-metalua-parser: use luarocks_org PG
  lua/lua-metalua-parser/Portfile
Labels: type: enhancement, maintainer: open, by: member

#17950 lua-luacheck: update to 1.1.0 & use luarocks_org PG
  lua/lua-luacheck/Portfile
  lua/lua-luacheck/files/lua54-luacheck
Labels: type: enhancement, type: update, maintainer: open, by: member

#17952 lua-readline: update to 3.2 & use luarocks_org PG
  lua/lua-readline/Portfile
Labels: type: enhancement, type: update, maintainer: open, by: member

#17953 lua-lpeg: use luarocks_org PG
  lua/lua-lpeg/Portfile
Labels: type: enhancement, maintainer: open, by: member

#17991 prosody: update 0.11.2->0.12.3
  net/prosody/Portfile
  net/prosody/files/patch-config.diff
Labels: type: enhancement, type: update, maintainer: none, by: member

#17922 a2ps: update to 4.15
  print/a2ps/Portfile
Labels: type: update, maintainer: none

#17985 openssh: update to 9.3p1
  net/openssh/Portfile
  net/openssh/files/launchd.patch
Labels: type: bugfix, type: enhancement, type: update, maintainer, type: security fix, maintainer: open

#17995 clojure: update to 1.11.1.1257
  lang/clojure/Portfile
Labels: type: update, maintainer, maintainer: open

#17998 miniflux: update to 2.0.43
  net/miniflux/Portfile
Labels: type: enhancement, type: update, maintainer, type: security fix, maintainer: open

#17992 libressl-devel: update to 3.7.1.
  security/libressl-devel/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer, type: security fix, maintainer: open

#17965 cmake-devel: Update to 20230308-3.26.0-rc6-454bfa77
  devel/cmake-devel/Portfile
  devel/cmake-devel/files/patch-qt5gui.diff
Labels: type: update, maintainer: requires approval, maintainer: timeout, by: member

#17944 arpack: enable ISO_C_BINDING support
  math/arpack/Portfile
Labels: maintainer: none

#18003 gmake: update to 4.4.1
  devel/gmake/Portfile
Labels: type: update, maintainer: none, by: member

#18005 maven3: update to 3.9.1
  java/maven3/Portfile
Labels: type: update, maintainer, maintainer: open

#18007 gretl: update to 2023a
  math/gretl/Portfile
  math/gretl/files/gtk-x11-fix.diff
Labels: type: update, maintainer: none

#18013 rust PG: add ability to add flags to rust compiler
  _resources/port1.0/group/rust-1.0.tcl
Labels: type: enhancement, by: member

#18012 cargo: update version 0.68.0->0.69.0
  devel/cargo/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open, by: member

#17976 netcdf: update to 4.9.2
  science/netcdf/Portfile
  science/netcdf/files/patch-liblib-CMakeLists.txt.diff
Labels: type: update, maintainer: open

#17747 py-poppler-qt5: update to 21.3.0
  python/py-poppler-qt5/Portfile
  python/py-poppler-qt5/files/patch-fix-py36.diff
  python/py-poppler-qt5/files/patch-types.sip.diff
Labels: type: update, maintainer, maintainer: open

#17914 py-graph-tool: Update to version 2.46
  python/py-graph-tool/Portfile
Labels: type: update, maintainer, maintainer: open

#18014 openssl3: fix build on PPC
  devel/openssl3/Portfile
  devel/openssl3/files/patch-openssl3-ppc-asm.diff
Labels: maintainer: open

#17989 libquvi*: use lua PG and Lua version 5.2
  net/libquvi-scripts/Portfile
  net/libquvi/Portfile
Labels: type: enhancement, maintainer: open, by: member

#18018 wordpress: update to 5.5.11
  www/wordpress/Portfile
Labels: type: update, type: security fix, maintainer: none

#18017 drupal7: update to 7.95
  www/drupal7/Portfile
Labels: type: bugfix, type: enhancement, type: update, type: security fix, maintainer: none

#18021 lazarus: Update to 2.2.6
  devel/lazarus/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#17964 cmake: Update to 3.24.4
  devel/cmake/Portfile
Labels: type: update, maintainer: requires approval, maintainer: timeout, by: member

#18022 asdf: update to 0.11.3
  sysutils/asdf/Portfile
Labels: type: update, maintainer: open, by: member

#18001 bingrep: update to 0.11.0
  textproc/bingrep/Portfile
Labels: type: update, maintainer: open, by: member

#18023 py-language-server: remove obsolete port
  python/py-language-server/Portfile
Labels: maintainer: none

#18024 cantera-devel: remove obsolete subport
  science/cantera/Portfile
Labels: maintainer: open

#18025 qgis: remove obsolete port
  gis/qgis/Portfile
Labels: maintainer: none

#18026 google-glog-0.4: remove obsolete subport
  devel/google-glog/Portfile
Labels: maintainer: none

#18027 inkscape-gtk3-devel: remove obsolete port
  graphics/inkscape-gtk3-devel/Portfile
Labels: maintainer: none

#18035 rpki-client: update to 8.3.
  net/rpki-client/Portfile
  net/rpki-client/files/configure.ac.diff
  net/rpki-client/files/unistd.h.diff
Labels: type: enhancement, type: update, maintainer, maintainer: open

#18039 ismrmrd: 1.13.4
  science/ismrmrd/Portfile
Labels: maintainer, maintainer: open, by: member

#18038 mpv: patch youtube-dl hook to fix youtube playback
  multimedia/mpv/Portfile
  multimedia/mpv/files/patch-youtubedl-edl-track-error.diff
Labels: type: bugfix, maintainer: open

#18043 google-cloud-sdk: update to 423.0.0
  devel/google-cloud-sdk/Portfile
Labels: type: update, maintainer, maintainer: open

#18044 openjdk20-oracle: new submission
  java/openjdk20-oracle/Portfile
Labels: type: submission

#18045 jdk20: new submission
  java/jdk20/Portfile
Labels: type: submission

#18046 openjdk13: obsolete
  java/openjdk13-zulu/Portfile
Labels: maintainer, maintainer: open

#18047 openjdk15-zulu: obsolete
  java/openjdk15-zulu/Portfile
Labels: maintainer, maintainer: open

#18048 openjdk18-zulu: removal
  java/openjdk18-zulu/Portfile
Labels: maintainer: none
