Repository macports/macports-ports, pull requests merged in 2023-12, with the labels that each got.

#21616 lima: update to v0.19.0
  sysutils/lima/Portfile
Labels: type: update, maintainer: open

#21571 gcc{7,8,9}: fix build before 10.6 i386
  lang/gcc7/Portfile
  lang/gcc8/Portfile
  lang/gcc9/Portfile
Labels: type: bugfix, maintainer: none

#21531 qt5pas: fix build
  devel/qt5pas/Portfile
Labels: type: bugfix, maintainer: open

#17168 mcmcf90: new port in math
  math/mcmcf90/Portfile
  math/mcmcf90/files/patch-dynlib.diff
Labels: type: submission

#21109 bpack: update to 2.4.0
  math/bpack/Portfile
  math/bpack/files/patch-examples.diff
Labels: type: update, maintainer, maintainer: open

#21620 py-autoflake: update to 2.2.1
  python/py-autoflake/Portfile
Labels: type: update, maintainer: none

#21623 py-cliff: update to 4.4.0
  python/py-cliff/Portfile
Labels: type: update, maintainer: none

#21624 py-cjson: update to 1.2.2
  python/py-cjson/Portfile
Labels: type: update, maintainer: none

#21613 OpenBLAS: fix build on 10.6 x86_64
  math/OpenBLAS/Portfile
  math/OpenBLAS/files/patch-OpenBLAS-old-macos.diff
Labels: type: bugfix, maintainer, maintainer: open

#21615 quadpack: fix build with new fpm
  fortran/quadpack/Portfile
  fortran/quadpack/files/patch-fpm.diff
Labels: type: bugfix, maintainer, maintainer: open

#21626 maven3: update to 3.9.6
  java/maven3/Portfile
Labels: type: update, maintainer, maintainer: open

#21619 libKriging: unbreak build
  math/libKriging/Portfile
  math/libKriging/files/patch-CMakeLists.diff
Labels: type: bugfix, maintainer, maintainer: open

#21627 oof2: update to version 2.3.2
  science/oof2/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#21560 py-jsonschema-specifications: added new port, version 2023.11.1
  python/py-jsonschema-specifications/Portfile
Labels: type: submission

#21630 py-fastapi: update to 0.104.1
  python/py-fastapi/Portfile
Labels: type: update, maintainer: none

#21629 py-cmd2: update to 2.4.3
  python/py-cmd2/Portfile
Labels: type: update, maintainer: none

#21633 ginkgo: update to 1.7.0
  math/ginkgo/Portfile
Labels: type: update, maintainer, maintainer: open

#21634 py-antlr4-python3-runtime: update to 4.13.1
  python/py-antlr4-python3-runtime/Portfile
Labels: type: update, maintainer: none

#21636 spring-boot-cli: update to 3.2.0
  java/spring-boot-cli/Portfile
Labels: type: update, maintainer, maintainer: open

#21635 scrcpy: Update to version 2.3.1
  multimedia/scrcpy/Portfile
Labels: type: update, maintainer, maintainer: open

#21637 powellopt: update to 2023.12.03
  fortran/powellopt/Portfile
Labels: type: bugfix, type: update, maintainer, maintainer: open

#21632 basix: update to 0.7.0
  science/basix/Portfile
Labels: type: update, maintainer, maintainer: open

#21523 py-poppler-qt5: unbreak installation for python 3.7 and later
  python/py-poppler-qt5/Portfile
Labels: type: bugfix, maintainer: open

#21645 gsoap: update to 2.8.131, fix build on new macOS
  devel/gsoap/Portfile
Labels: type: update, maintainer: none

#21640 vtk: update to 9.3.0
  graphics/vtk/Portfile
Labels: type: update, maintainer, maintainer: open

#21647 ecl-devel: update to 20231122; ecl*: keep used compiler
  lang/ecl/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer, maintainer: open

#21648 hyfetch: Update to 1.4.11
  python/hyfetch/Portfile
Labels: type: update, maintainer: open

#21651 tldr-cpp-client: re-add worksrcdir to fix builds
  sysutils/tldr-cpp-client/Portfile
  sysutils/tldr-cpp-client/files/patch-Makefile.diff
Labels: maintainer, maintainer: open, by: member

#20733 tuist: new port
  devel/tuist/Portfile
Labels: type: submission

#21656 tesseract: update to 5.3.3
  textproc/tesseract/Portfile
  textproc/tesseract/files/patch-fix-mtree-violation-by-cmake-files.diff
Labels: type: enhancement, type: update, maintainer: open

#21657 groovy: update to 4.0.16
  lang/groovy/Portfile
Labels: type: update, maintainer, maintainer: open

#21655 fish: update to 3.6.3
  shells/fish/Portfile
Labels: type: bugfix, type: update, type: security fix, maintainer: none

#21659 helix: fix broken URL for 'gemini' grammar
  editors/helix/Portfile
  editors/helix/files/patch-languages.toml.diff
Labels: maintainer, maintainer: open, by: member

#21660 micronaut: update to 4.2.1
  java/micronaut/Portfile
Labels: type: update, maintainer, maintainer: open

#21662 symfony-cli: update to 5.7.4
  devel/symfony-cli/Portfile
Labels: type: update, maintainer, maintainer: open

#21664 Bear: Update to 3.1.3
  devel/Bear/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#21665 borgmatic: Update to 1.8.5
  sysutils/borgmatic/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#21666 goimapnotify: Update to 2.4-rc4
  mail/goimapnotify/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#21668 offlineimap: update to 8.0.0-20231201
  mail/offlineimap/Portfile
  mail/offlineimap/files/patch-keyring.diff
Labels: type: enhancement, type: update, maintainer, maintainer: open

#21669 clojure: update to 1.11.1.1429
  lang/clojure/Portfile
Labels: type: update, maintainer, maintainer: open

#21586 clang-11-bootstrap: prefer configure.build_arch over build_arch, use universal_possible
  lang/clang-11-bootstrap/Portfile
Labels: type: bugfix, maintainer, maintainer: open

#21644 libhx: update to 4.19
  devel/libhx/Portfile
  devel/libhx/files/0001-rand.c-fix-headers-for-macOS.patch
  devel/libhx/files/0002-build-resolve-compile-error-on-NetBSD.patch
  devel/libhx/files/patch-src-Makefile.in.diff
Labels: type: update, maintainer: none

#21675 fish: update to 3.6.4
  shells/fish/Portfile
Labels: type: bugfix, type: update, maintainer: none

#21671 google-cloud-sdk: update to 456.0.0
  devel/google-cloud-sdk/Portfile
Labels: type: update, maintainer, maintainer: open

#21676 lagrange: update to 1.17.5
  net/lagrange/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#21679 coreutils-uutils: update to 0.0.23
  sysutils/coreutils-uutils/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#21680 sbcl: use ecl instead ecl-devel
  lang/sbcl/Portfile
Labels: type: bugfix, maintainer, maintainer: open

#21685 symfony-cli: update to 5.7.5
  devel/symfony-cli/Portfile
Labels: type: update, maintainer, maintainer: open

#21686 cargo_fetch: Update reference to cargo2port
  _resources/port1.0/group/cargo_fetch-1.0.tcl
Labels: type: bugfix, type: update, by: member

#21690 php-pcov: added support for php83
  php/php-pcov/Portfile
Labels: type: enhancement, maintainer: open

#21687 meme: Update to 5.5.5
  science/memesuite/Portfile
Labels: type: update, maintainer, maintainer: open

#21689 php_igbinary: update to 3.2.15 and add php83 port
  php/php-igbinary/Portfile
Labels: type: enhancement, type: update, maintainer: open

#21693 cabal: Update to version 3.10.2.0
  lang/cabal/Portfile
Labels: type: update, maintainer, maintainer: open

#21672 proj9: update to version 9.3.1
  gis/proj9/Portfile
Labels: type: update, maintainer: open

#21694 pipx: update to 1.3.3
  python/pipx/Portfile
Labels: type: update, maintainer, maintainer: open

#21621 py-ipaddress: support newer pythons
  python/py-ipaddress/Portfile
Labels: type: enhancement, maintainer: open

#21697 paho.mqtt.cpp: update to 1.3.2
  net/paho.mqtt.cpp/Portfile
Labels: type: enhancement, type: update, maintainer: none

#19327 Add btop port
  sysutils/btop/Portfile
Labels: type: submission

#21699 abcl: always use FFI
  lang/abcl/Portfile
  lang/abcl/files/patch-macports-maven.diff
Labels: type: bugfix, type: enhancement, maintainer, maintainer: open

#21650 OpenBLAS: fix linking on older Mac versions
  math/OpenBLAS/Portfile
  math/OpenBLAS/files/patch-ar-options-old-macos.diff
  math/OpenBLAS/files/patch-weak-linking-old-macos.diff
Labels: type: bugfix, maintainer: open

#21605 wireshark4: update to 4.2.0
  net/wireshark4/Portfile
Labels: type: update, maintainer: requires approval, by: member

#21702 rapidjson-devel: update to 20231206
  devel/rapidjson-devel/Portfile
Labels: type: update, maintainer, maintainer: open

#21703 kokkos-devel: update to 2023.12.08
  devel/kokkos/Portfile
Labels: type: update, maintainer: open

#21704 ruby-devel: update to 2023.12.09
  lang/ruby-devel/Portfile
Labels: type: update, maintainer, maintainer: open

#21709 got: update to 0.95
  devel/got/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer, maintainer: open

#21706 tippecanoe: update to 2.37.1
  gis/tippecanoe/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#21696 bitwarden-cli: update to 2023.12.0
  security/bitwarden-cli/Portfile
Labels: type: update, maintainer: open

#21711 ecl-devel: update to 20231209
  lang/ecl/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer, maintainer: open

#21720 colima: Update to 0.6.7
  sysutils/colima/Portfile
Labels: type: update, maintainer, maintainer: open

#21717 prima: new port in fortran
  fortran/prima/Portfile
Labels: type: submission

#21710 cell-id: fix livecheck, general linting
  science/cell-id/Portfile
Labels: maintainer: requires approval

#21701 Update php apcu, redis, xhprof, zip and zstd extensions to build for php83
  php/php-APCu/Portfile
  php/php-redis/Portfile
  php/php-xhprof/Portfile
  php/php-zip/Portfile
  php/php-zstd/Portfile
Labels: type: enhancement, type: update, maintainer: requires approval

#21721 ast-grep: new port (version 0.14.2)
  devel/ast-grep/Portfile
Labels: type: submission, by: member

#21724 atomvm: update to 0.6.0a2
  erlang/atomvm/Portfile
Labels: type: update, maintainer, maintainer: open

#21726 advancecomp: update to 2.6
  archivers/advancecomp/Portfile
Labels: type: update, maintainer: none

#21730 R-igraph: update to 1.6.0
  R/R-igraph/Portfile
Labels: type: update, maintainer, maintainer: open

#21731 gallery-dl: update to 1.26.4
  net/gallery-dl/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer, maintainer: open

#21732 ruby-build: Update to 20231211
  ruby/ruby-build/Portfile
Labels: type: update, maintainer, maintainer: open

#21718 stanc3: update to 2023.12.08
  math/stanc3/Portfile
Labels: type: update, maintainer, maintainer: open

#21734 cpp-argparse-dev: update to v1.9.0
  devel/cpp-argparse-dev/Portfile
Labels: type: update, maintainer, maintainer: open

#21683 py-jsonschema: update to version 4.20.0
  python/py-jsonschema/Portfile
Labels: type: update, maintainer: open

#21736 mk-configure: update to 0.38.3
  devel/mk-configure/Portfile
Labels: type: update, maintainer, maintainer: open

#21741 libretroshare: update to 2023.11.26
  net/libretroshare/Portfile
  net/libretroshare/files/0001-Fix-CMakeLists-for-MacPorts.patch
Labels: type: update, maintainer, maintainer: open

#21743 edid-decode: update to version 20231207
  sysutils/edid-decode/Portfile
Labels: type: update, maintainer, maintainer: open

#21757 yabai: clarify post-install notes
  sysutils/yabai/Portfile
Labels: type: enhancement, maintainer: open

#21758 py311-htmldocs: 3.11.7
  lang/py-htmldocs/Portfile
Labels: maintainer, maintainer: open, by: member

#21756 logtalk: update to 3.73.0
  lang/logtalk/Portfile
Labels: type: update, maintainer

#21754 osxphotos: update to 0.66.0
  graphics/osxphotos/Portfile
Labels: type: update, maintainer, maintainer: open

#21755 py-python-json-logger: added new port
  python/py-python-json-logger/Portfile
Labels: type: submission

#21751 mochiweb: update to 3.2.1
  erlang/mochiweb/Portfile
Labels: type: update, maintainer: none

#21749 ocaml-xmlm: update to 1.4.0
  ocaml/ocaml-xmlm/Portfile
Labels: type: update, maintainer: none

#21698 py-gobject3: add py312 subport
  python/py-gobject3/Portfile
Labels: type: enhancement, maintainer: open

#21759 vapoursynth: update to 65
  multimedia/vapoursynth/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#21715 openjdk*: fix build with ccache
  java/openjdk11/Portfile
  java/openjdk13/Portfile
  java/openjdk15/Portfile
  java/openjdk17/Portfile
  java/openjdk18/Portfile
  java/openjdk19/Portfile
  java/openjdk20/Portfile
  java/openjdk21/Portfile
  java/openjdk8/Portfile
Labels: type: bugfix, maintainer: open

#21760 google-cloud-sdk: update to 457.0.0
  devel/google-cloud-sdk/Portfile
Labels: type: update, maintainer, maintainer: open

#21752 libvmaf: fix build on macOS <10.12
  multimedia/libvmaf/Portfile
Labels: type: bugfix, maintainer: open

#21762 abcl: avoid java PG
  _resources/port1.0/group/common_lisp-1.0.tcl
  lang/abcl/Portfile
Labels: type: bugfix, maintainer, maintainer: open

#21769 gFTL: update to 1.11.0
  devel/gFTL/Portfile
Labels: type: update, maintainer, maintainer: open

#21771 feq-parse: update to 2023.12.06
  fortran/feq-parse/Portfile
Labels: type: update, maintainer, maintainer: open

#21764 starpu: update to 1.4.2
  devel/starpu/Portfile
Labels: type: update, maintainer, maintainer: open

#21763 libcotp: update to 3.0.0
  security/libcotp/Portfile
  security/libcotp/files/patch-unbreak-build.diff
Labels: type: update, maintainer, maintainer: open

#21745 FAudio: update to 23.12
  audio/FAudio/Portfile
Labels: type: update, maintainer: none

#21723 py-bitarray: update to 2.8.5, add py312 subport
  audio/FAudio/Portfile
Labels: type: update, maintainer: open

#21761 ncview: Update to 2.1.9; remove deprecated config arguments
  science/ncview/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#21727 unbound: update to 1.19.0, unbreak build with gcc-4.2
  net/unbound/Portfile
  net/unbound/files/patch-macos_startup_fix.diff
Labels: type: bugfix, type: update, maintainer: open

#21773 ocaml-shell: new port
  ocaml/ocaml-shell/Portfile
Labels: type: submission

#21770 prima: update homepage
  fortran/prima/Portfile
Labels: type: enhancement, type: update, maintainer: open

#21740 superlu_dist: update to 8.2.1
  math/superlu_dist/Portfile
Labels: type: update, maintainer: open

#21739 py-tornado: upgrade to version 6.4, add py312
  python/py-tornado/Portfile
Labels: maintainer: open

#21784 collectd: Disable -Werror
  sysutils/collectd/Portfile
Labels: type: bugfix, maintainer, maintainer: open, by: member

#21782 py-terminado: upgrade to version 1.18.0, add py312
  python/py-terminado/Portfile
Labels: maintainer: open

#21748 strumpack: update to 7.2.0
  math/strumpack/Portfile
Labels: type: update, maintainer, maintainer: open

#21794 symfony-cli: update to 5.7.6
  devel/symfony-cli/Portfile
Labels: type: update, maintainer, maintainer: open

#21792 psblas3: update to 3.8.1-2
  math/psblas3/Portfile
Labels: type: bugfix, type: update, maintainer, maintainer: open

#21790 ecCodes: update to 2.33.0
  science/ecCodes/Portfile
Labels: type: update, maintainer, maintainer: open

#21791 NTPoly: update to 3.1.0
  math/NTPoly/Portfile
Labels: type: update, maintainer, maintainer: open

#21787 radian: update to 0.6.9
  math/radian/Portfile
Labels: type: update, maintainer, maintainer: open

#21798 libretroshare: fix installation broken with recent update
  net/libretroshare/Portfile
Labels: type: bugfix, maintainer, maintainer: open

#21804 micronaut: update to 4.2.2
  java/micronaut/Portfile
Labels: type: update, maintainer, maintainer: open

#21805 madness: update to 2023.12.03, move gperftools support into a variant
  science/madness/Portfile
Labels: type: update, maintainer, maintainer: open

#21799 hiop: update to 1.0.1
  math/hiop/Portfile
  math/hiop/files/patch-no-werror.diff
  math/hiop/files/patch-strumpack-includes.diff
Labels: type: update, maintainer, maintainer: open

#21746 fgsl: update to 1.5.0
  math/fgsl/Portfile
Labels: type: update, maintainer: open

#21795 swi-prolog-devel: Updated to version 9.1.21
  lang/swi-prolog-devel/Portfile
Labels: type: update, maintainer, maintainer: open

#21808 oci-cli: submission
  net/oci-cli/Portfile
Labels: type: submission

#21807 py-oci: update to 2.118.0
  python/py-oci/Portfile
Labels: type: update, maintainer: none

#21776 elmerfem: update to 2023.12.13
  science/elmerfem/Portfile
Labels: type: update, maintainer, maintainer: open

#21768 py-libxml2: add py312 subport
  python/py-libxml2/Portfile
Labels: type: enhancement, maintainer: open

#21750 ocaml-yojson: update to 2.1.2
  ocaml/ocaml-yojson/Portfile
Labels: type: update, maintainer: open

#21785 nektarpp: update to 5.4.0
  science/nektarpp/Portfile
  science/nektarpp/files/fusion-copy-constructor.patch
  science/nektarpp/files/opencascade.patch
Labels: type: enhancement, type: update, maintainer, maintainer: open

#21809 icu-devel: update to 74.2
  devel/icu-devel/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#21502 py-frozendict: New port, version 2.3.10
  python/py-frozendict/Portfile
Labels: type: submission

#21800 ocaml-dune: update to 3.12.1
  ocaml/ocaml-dune/Portfile
Labels: type: update, maintainer: open

#21811 lal*: abandon ports
  science/lal/Portfile
  science/lalapps/Portfile
  science/lalburst/Portfile
  science/lalframe/Portfile
  science/lalinference/Portfile
  science/lalinspiral/Portfile
  science/lalmetaio/Portfile
  science/lalpulsar/Portfile
  science/lalsimulation/Portfile
Labels: maintainer, by: member

#21797 net/rs-aggregate: submission (new Portfile)
  net/rs-aggregate/Portfile
Labels: type: submission

#21814 pika: update to 0.21.0
  devel/pika/Portfile
Labels: type: update, maintainer, maintainer: open

#21815 openjkd17-openj9: update to 17.0.9
  java/openjdk17-openj9/Portfile
Labels: type: update, maintainer, maintainer: open

#21816 openjdk11-openj9: update to 11.0.21
  java/openjdk11-openj9/Portfile
Labels: type: update, maintainer, maintainer: open

#21817 openjdk8-openj9: update to 8u392
  java/openjdk8-openj9/Portfile
Labels: type: update, maintainer, maintainer: open

#21813 photoqt-qt4: fix desktop file
  graphics/photoqt/Portfile
  graphics/photoqt/files/patch-desktop-file.diff
Labels: type: bugfix, maintainer, maintainer: open

#21681 mcmcf90: increase clang blacklist to 500 for Lion
  math/mcmcf90/Portfile
Labels: maintainer: open

#21780 py-nest_asyncio: upgrade to version 1.5.8, add py312
  python/py-nest_asyncio/Portfile
Labels: maintainer: open

#21573 fontmatrix: new port in sysutils
  sysutils/fontmatrix/Portfile
  sysutils/fontmatrix/files/0001-CMakeLists-do-not-force-i386.patch
Labels: type: submission

#21786 gnupg2: backport fix for Emacs EasyPG compatibility
  mail/gnupg2/Portfile
  mail/gnupg2/files/patch-fix-emacs-easypg.diff
Labels: type: bugfix, maintainer: open, by: member

#21507 mpv: update to 0.37.0, use meson build system
  multimedia/mpv/Portfile
  multimedia/mpv/files/config-maintainer
Labels: type: enhancement, type: update, type: submission, maintainer, maintainer: open, by: member

#21824 hpddm: update to 2.2.5
  math/hpddm/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#21823 asl: update to 20231117
  math/asl/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#21821 universal-ctags: update to 6.0.20231217.0
  devel/universal-ctags/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#21819 libatomic_ops: update to 7.8.2
  devel/libatomic_ops/Portfile
Labels: type: bugfix, type: update, maintainer: none

#21832 lima: upgrade to 0.19.1
  sysutils/lima/Portfile
Labels: maintainer, maintainer: open

#21834 openssh: update to 9.6p1
  net/openssh/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer, type: security fix, maintainer: open
