Repository macports/macports-ports, pull requests merged in 2023-05, with the labels that each got.

#18482 lbzip2: enable legacysupport.use_static
  archivers/lbzip2/Portfile
Labels: maintainer, maintainer: open, by: member

#18476 lbzip2: Remove homepage; use GitHub
  archivers/lbzip2/Portfile
Labels: maintainer: open, by: member

#18485 gallery-dl: update to 1.25.3
  net/gallery-dl/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer, type: security fix, maintainer: open

#18493 Gildas: update to 202305a
  science/gildas/Portfile
Labels: type: enhancement, type: update, maintainer

#18497 got: update to 0.88.
  devel/got/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer, maintainer: open

#18498 cdo: revision bump: changed upstream tarball
  science/cdo/Portfile
Labels: maintainer: open

#18495 imapdedup: used the desired python
  mail/imapdedup/Portfile
Labels: type: bugfix, maintainer, maintainer: open

#18481 lame: add simd variant
  audio/lame/Portfile
  audio/lame/files/lame-3.100-altivec-20171014.diff
  audio/lame/files/lame-3.100-altivec-20171217.diff
  audio/lame/files/lame-3.100-neon-20230418.diff
  audio/lame/files/lame-3.100-sse-20171014.diff
Labels: type: enhancement, maintainer: none

#18504 py-mupdf: update to 1.22.2
  python/py-mupdf/Portfile
Labels: type: update, maintainer: none

#17567 bazelisk: update to 1.16.0
  devel/bazelisk/Portfile
  devel/bazelisk/files/patch-build.sh.diff
  devel/bazelisk/files/patch-clean-and-stop-bazel-after-build.diff
Labels: type: update, maintainer: open, by: member

#18507 starpu: update to 1.4.0
  devel/starpu/Portfile
Labels: type: update, maintainer, maintainer: open

#18484 offlineimap: update to 8.0.0-20230330
  mail/offlineimap/Portfile
  mail/offlineimap/files/patch-keyring.diff
  mail/offlineimap/files/patch-utf8.diff
Labels: type: bugfix, type: enhancement, type: update, maintainer, maintainer: open

#18492 dosbox-x: update to 2023.05.01
  emulators/dosbox-x/Portfile
  emulators/dosbox-x/files/patch-build-macos.diff
  emulators/dosbox-x/files/patch-build-macosx.diff
Labels: type: update, maintainer: none

#18508 libretroshare: update to current upstream (2023.04.26)
  net/libretroshare/Portfile
Labels: type: update, maintainer, maintainer: open

#18494 KeepassXC-devel: fix build on macos 10.7-10.9
  security/KeePassXC/Portfile
  security/KeePassXC/files/devel/0001-use-setWindowFlags-instead-of-setWindowFlag-on-Qt-5..patch
  security/KeePassXC/files/devel/0002-Fix-build-failure-with-Qt5.6.patch
Labels: type: bugfix, maintainer: none

#18251 new port: input-leap (fork of aqua/barrier)
  aqua/input-leap/Portfile
  aqua/input-leap/files/macOS-add-support-for-right-side-modifier-keys.patch
  aqua/input-leap/files/remove-gtest.patch
  aqua/input-leap/files/set-cmake-revision.patch
Labels: type: submission

#18513 rpki-client: update to 8.4.
  net/rpki-client/Portfile
  net/rpki-client/files/configure.ac.diff
  net/rpki-client/files/unistd.h.diff
Labels: type: bugfix, type: enhancement, type: update, maintainer, maintainer: open

#18509 openjdk16-openj9: remove obsolete port
  java/openjdk16-openj9/Portfile
Labels: maintainer: none

#18514 google-cloud-sdk: update to 429.0.0
  devel/google-cloud-sdk/Portfile
Labels: type: update, maintainer, maintainer: open

#18502 libxkbcommon: fix executable linkages
  devel/libxkbcommon/Portfile
  devel/libxkbcommon/files/patch-libxkbcommon-mesonbuild-linkages.diff
Labels: maintainer: open, by: member

#18517 pika: update to 0.15.0
  devel/pika/Portfile
Labels: type: update, maintainer, maintainer: open

#18521 aqua/input-leap: remove unused and obsolete patch
  aqua/input-leap/Portfile
  aqua/input-leap/files/macOS-add-support-for-right-side-modifier-keys.patch
Labels: maintainer, maintainer: open

#18524 josm: update to 18721
  gis/JOSM/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#18510 yajl-fort: new port in fortran
  fortran/yajl-fort/Portfile
  fortran/yajl-fort/files/patch-fix-CMakeLists.diff
Labels: type: submission

#18520 madness: update to current upstream (2023.04.23)
  science/madness/Portfile
  science/madness/files/0002-Do-not-build-chem-it-is-broken.patch
Labels: type: update, maintainer, maintainer: open

#18519 GaussianLib: update to current upstream (2023.02.17)
  devel/GaussianLib/Portfile
Labels: type: update, maintainer, maintainer: open

#18527 shtools: update to 4.10.2
  science/shtools/Portfile
Labels: type: enhancement, type: update, maintainer

#18528 vtm: update to 0.9.9g
  sysutils/vtm/Portfile
Labels: type: update, maintainer: none

#18490 binwalk: upgrade dependency to python311
  cross/binwalk/Portfile
Labels: type: enhancement, maintainer: open

#18308 openjdk8: add arm64 support
  java/openjdk8-bootstrap/Portfile
  java/openjdk8/Portfile
  java/openjdk8/files/Support-arm64-and-fix-zero-assembler.diff
Labels: maintainer, maintainer: open

#18518 cutter: update to 1.2.8
  devel/cutter/Portfile
Labels: type: update, maintainer: open

#18530 gcc10-bootstrap: mark unsupported Xcode / CLT
  lang/gcc10-bootstrap/Portfile
Labels: type: bugfix, maintainer, maintainer: open

#18491 p5-pgtop: explicitly declare all dependencies
  perl/p5-pgtop/Portfile
Labels: type: bugfix, maintainer: none

#18534 osc: update to 1.1.2
  devel/osc/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#18535 giter8: update to 0.16.2
  devel/giter8/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#18536 gnuastro: update to 0.20
  science/gnuastro/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#18483 qbs: Update to 2.0.0
  devel/qbs/Portfile
  devel/qbs/files/patch-find-package.diff
Labels: type: enhancement, type: update, maintainer: open

#17500 ruby26: Fix build on macOS 12+, plus cleanups.
  lang/ruby26/Portfile
  lang/ruby26/files/patch-c99check.diff
  lang/ruby26/files/patch-configure_cxx11.diff
  lang/ruby26/files/patch-ext-openssl-extconf.rb.diff
  lang/ruby26/files/patch-generated.diff
  lang/ruby26/files/patch-osversions.diff
  lang/ruby26/files/patch-ruby_issue_17777.diff
  lang/ruby26/files/patch-sources.diff
  lang/ruby26/files/patch-test-fiddle-helper.rb.diff
  lang/ruby26/files/patch-tiger.diff
Labels: type: bugfix, maintainer: open

#18533 pika: fix build with clang on <= 10.15
  devel/pika/Portfile
Labels: type: bugfix, maintainer, maintainer: open

#18541 universal-ctags: update to 6.0.20230430.0
  devel/universal-ctags/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#18539 ruby-devel: update to current upstream (2023.05.06)
  lang/ruby-devel/Portfile
Labels: type: update, maintainer, maintainer: open

#18540 chromedriver: update to 113.0.5672.63
  www/chromedriver/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#18542 cpp-peglib: update to 1.8.3
  devel/cpp-peglib/Portfile
Labels: type: update, maintainer, maintainer: open

#18547 rapidjson-devel: update to current upstream (20230407)
  devel/rapidjson-devel/Portfile
Labels: type: update, maintainer, maintainer: open

#18546 libfixmath: update to current upstream (2023.03.20)
  math/libfixmath/Portfile
Labels: type: update, maintainer, maintainer: open

#18545 gss: update to 1.0.4
  security/gss/Portfile
  security/gss/files/patch-fix-m4.diff
Labels: type: bugfix, type: update, maintainer: none

#18549 fsplib: update to 0.14
  devel/fsplib/Portfile
  devel/fsplib/files/prefix.patch
Labels: type: update, maintainer: none

#18543 ocaml-ocamlbuild: update to 0.14.2
  ocaml/ocaml-ocamlbuild/Portfile
Labels: type: update, maintainer: open

#15397 py-tensorflow: Update to version 2.12.0, Add Python 310
  python/py-tensorflow/Portfile
Labels: maintainer: open, wip

#18552 snac: update to 2.30.
  net/snac/Portfile
  net/snac/files/Makefile.patch
Labels: type: bugfix, type: enhancement, type: update, maintainer, maintainer: open

#18554 py-llvmlite: fix build on macOS before 10.13
  python/py-llvmlite/Portfile
Labels: type: bugfix, maintainer: open

#18555 oce: fix build on amr64
  graphics/oce/Portfile
  graphics/oce/files/patch-use-isfinite-on-arm64.diff
Labels: type: bugfix, maintainer: open

#18523 openimageio: remove obsolete field3d dependency
  graphics/openimageio/Portfile
Labels: type: bugfix, maintainer: open

#18553 mssql-tools, msodbcsql*: Use platforms {darwin any}
  databases/msodbcsql/Portfile
  databases/msodbcsql17/Portfile
  databases/mssql-tools/Portfile
Labels: maintainer: open, by: member

#18556 symfony-cli: update to 5.5.5
  devel/symfony-cli/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#18557 sccache: update to 0.4.2
  devel/sccache/Portfile
Labels: type: enhancement, type: update, maintainer: none

#18501 mingw-w64: Update to 11.0.1
  cross/mingw-w64/Portfile
Labels: type: update, maintainer: open

#18503 *-w64-mingw32-gcc: Update to 13.1.0
  cross/i686-w64-mingw32-gcc/Portfile
  cross/i686-w64-mingw32-gcc/files/patch-notparallel-install-headers.diff
  cross/x86_64-w64-mingw32-gcc/Portfile
  cross/x86_64-w64-mingw32-gcc/files/patch-notparallel-install-headers.diff
Labels: type: update, maintainer: open

#17891 *-mingw32-binutils: Import upstream fix for ld
  cross/i686-w64-mingw32-binutils/Portfile
  cross/i686-w64-mingw32-binutils/files/0001-pr30079.diff
  cross/x86_64-w64-mingw32-binutils/Portfile
  cross/x86_64-w64-mingw32-binutils/files/0001-pr30079.diff
Labels: type: bugfix, maintainer: open

#18522 qt6*: update 6.2.4->6.4.3; major rewrite
  _resources/port1.0/group/qt6-1.0.tcl
  _resources/port1.0/group/qt6_info-1.0.tcl
  _resources/port1.0/group/qt6_variables-1.0.tcl
  _resources/port1.0/group/qt6_version_info-1.0.tcl
  aqua/qt6/Portfile
  aqua/qt6/files/patch-mkspecs.diff
  aqua/qt6/files/patch-qt5compat-find_libs.diff
  aqua/qt6/files/patch-qtbase-macos_10.14_sdk.diff
  aqua/qt6/files/patch-sdk-no-stderr.diff
  emulators/melonds/Portfile
  multimedia/welle.io/Portfile
  net/qBittorrent/Portfile
  textproc/cgrc/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer: open, by: member

#18566 nixpacks: update to version 1.7.0
  devel/nixpacks/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#18562 nali: new port
  net/nali/Portfile
Labels: type: enhancement, type: submission

#18567 openjdk17-graalvm: update x86_64 to 22.3.2
  java/openjdk17-graalvm/Portfile
Labels: type: update, maintainer, maintainer: open

#18568 openjdk11-graalvm: update x86_64 to 22.3.2
  java/openjdk11-graalvm/Portfile
Labels: type: update, maintainer, maintainer: open

#18570 webp: Fix CVE-2023-1999
  graphics/webp/Portfile
  graphics/webp/files/0001-EncodeAlphaInternal-clear-result-bw-on-error.patch
Labels: type: security fix, maintainer: open, by: member

#18578 lfortran: update to 0.19.0
  lang/lfortran/Portfile
  lang/lfortran/files/patch-ppc.diff
Labels: type: update, maintainer, maintainer: open

#18560 onetbb: fix build on macOS 10.6
  devel/onetbb/files/patch-onetbb-older-platforms.diff
Labels: type: bugfix, maintainer: open

#18563 libsoup: blacklist old Apple gcc, fix build on <10.7
  gnome/libsoup-devel/Portfile
  gnome/libsoup/Portfile
Labels: type: bugfix, maintainer: open

#18577 gallery-dl: update to 1.25.4
  net/gallery-dl/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer, maintainer: open

#18512 crlibm: do not use x86 asm on Rosetta
  devel/crlibm/Portfile
Labels: type: bugfix, maintainer: none

#18576 R: Revbump R-RcppParallel deps after oneTBB change to fix opportunistic linking
  R/R-BGVAR/Portfile
  R/R-BayesSenMC/Portfile
  R/R-LMMELSM/Portfile
  R/R-RcppMeCab/Portfile
  R/R-Rlgt/Portfile
  R/R-RoBTT/Portfile
  R/R-StanHeaders/Portfile
  R/R-baggr/Portfile
  R/R-bayesGAM/Portfile
  R/R-bayesbr/Portfile
  R/R-bayesdfa/Portfile
  R/R-bayesforecast/Portfile
  R/R-bistablehistory/Portfile
  R/R-blavaan/Portfile
  R/R-bmgarch/Portfile
  R/R-bmlm/Portfile
  R/R-bws/Portfile
  R/R-coconots/Portfile
  R/R-ctsem/Portfile
  R/R-diseq/Portfile
  R/R-fcirt/Portfile
  R/R-glmmPen/Portfile
  R/R-glmmrBase/Portfile
  R/R-hbamr/Portfile
  R/R-hsstan/Portfile
  R/R-lamW/Portfile
  R/R-matrixprofiler/Portfile
  R/R-measr/Portfile
  R/R-metaBMA/Portfile
  R/R-milr/Portfile
  R/R-parallelDist/Portfile
  R/R-pema/Portfile
  R/R-phacking/Portfile
  R/R-prophet/Portfile
  R/R-proxyC/Portfile
  R/R-publipha/Portfile
  R/R-quanteda.textmodels/Portfile
  R/R-quanteda/Portfile
  R/R-rPref/Portfile
  R/R-rater/Portfile
  R/R-re2r/Portfile
  R/R-rmBayes/Portfile
  R/R-rmsb/Portfile
  R/R-rstan/Portfile
  R/R-rstanarm/Portfile
  R/R-rstanemax/Portfile
  R/R-rstantools/Portfile
  R/R-stan4bart/Portfile
  R/R-stringfish/Portfile
  R/R-surveil/Portfile
  R/R-survstan/Portfile
  R/R-tmbstan/Portfile
  R/R-zoid/Portfile
Labels: type: bugfix, maintainer, maintainer: open

#18565 fortran-stdlib: update to current upstream (2023.05.08)
  lang/fortran-stdlib/Portfile
Labels: type: update, maintainer, maintainer: open

#18572 lporg: update to version 20.4.9
  sysutils/lporg/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#18582 stan: use path-style dep for rapidjson
  math/stan/Portfile
Labels: type: bugfix, maintainer, maintainer: open

#18583 vtm: update to 0.9.9h
  sysutils/vtm/Portfile
Labels: type: update, maintainer: none

#18573 payload-dumper-go: new port
  sysutils/payload-dumper-go/Portfile
Labels: type: enhancement, type: submission

#18588 cpio: update to 2.14
  archivers/cpio/Portfile
Labels: type: update, maintainer: open

#18584 nss: Fix installing with dash as /bin/sh
  net/nss/files/Makefile-MacPorts-Install.in
Labels: maintainer: none

#18592 icdiff: update to 2.0.6
  textproc/icdiff/Portfile
Labels: type: update, maintainer: open

#18590 mailutils: update to 3.16
  mail/mailutils/Portfile
Labels: type: update, maintainer: none

#18596 quickjs: new port in devel
  devel/quickjs/Portfile
  devel/quickjs/files/quickjs.pc
Labels: type: submission

#18589 sympow: fix build on macOS 10.8
  math/sympow/Portfile
Labels: type: bugfix, maintainer, maintainer: open

#18593 rabbitmq-server: update to 3.11.15
  net/rabbitmq-server/Portfile
Labels: type: enhancement, type: update, maintainer: none

#18600 beets-devel: update to 20230507
  audio/beets/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#18599 openjdk11-graalvm: fix incorrect version for aarch64
  java/openjdk11-graalvm/Portfile
Labels: type: bugfix, maintainer, maintainer: open

#18597 openjdk17-graalvm: fix incorrect version for aarch64
  java/openjdk17-graalvm/Portfile
Labels: type: bugfix, maintainer, maintainer: open

#18602 mod_security2: use lua PG
  www/mod_security2/Portfile
Labels: type: enhancement, maintainer: open, by: member

#18594 ffmpeg-upstream: skip building with Metal
  multimedia/ffmpeg-upstream/Portfile
Labels: type: bugfix, maintainer: open

#18564 openexr: 3.1.7 update; new openexr2 port; rev-bumps
  aqua/luminance-hdr/Portfile
  devel/libdevil/Portfile
  devel/libdevil/files/jasper.patch
  gis/gdal/Portfile
  gnome/gstreamer1-gst-plugins-bad/Portfile
  gnome/gstreamer1-gst-plugins-bad/files/patch-openexr3.diff
  graphics/ImageMagick/Portfile
  graphics/OpenSceneGraph-devel/Portfile
  graphics/OpenSceneGraph/Portfile
  graphics/OpenSceneGraph/files/patch-openexr3.diff
  graphics/Pangolin/Portfile
  graphics/alembic/Portfile
  graphics/blender/Portfile
  graphics/ctlang/Portfile
  graphics/ctlang/files/patch-CtlSimdInst.cpp.diff
  graphics/ctlang/files/patch-OpenEXR_CTL.pc.in.diff
  graphics/ctlang/files/patch-compat_files.diff
  graphics/darktable-devel/Portfile
  graphics/darktable/Portfile
  graphics/enblend/Portfile
  graphics/exact-image/Portfile
  graphics/exact-image/files/patch-openexr_cxx11.diff
  graphics/field3d/Portfile
  graphics/gegl-0.3/Portfile
  graphics/gegl-0.3/files/patch-cxx11.diff
  graphics/gegl-devel/Portfile
  graphics/gegl/Portfile
  graphics/gimp2-devel/Portfile
  graphics/gimp2/Portfile
  graphics/gimp3-devel/Portfile
  graphics/h3dapi/Portfile
  graphics/h3dutil/Portfile
  graphics/hugin-app/Portfile
  graphics/imath3/Portfile
  graphics/libjxl/Portfile
  graphics/opencv3-devel/Portfile
  graphics/opencv3/Portfile
  graphics/opencv4-devel/Portfile
  graphics/opencv4/Portfile
  graphics/openexr/Portfile
  graphics/openexr/files/patch-IlmImf-ImfSystemSpecific.h.diff
  graphics/openexr/files/patch-IlmImf-Makefile.diff
  graphics/openexr/files/patch-configure.diff
  graphics/openexr/files/patch-fltk.diff
  graphics/openexr/files/patch-ltmain.sh.diff
  graphics/openexr/files/patch-search_order.diff
  graphics/openexr2/Portfile
  graphics/openexr3/Portfile
  graphics/openimageio/Portfile
  graphics/openvdb/Portfile
  graphics/osl/Portfile
  graphics/pbrt3/Portfile
  graphics/povray/Portfile
  graphics/synfig/Portfile
  graphics/vigra/Portfile
  graphics/vips/Portfile
  science/gmic/Portfile
Labels: type: enhancement, type: submission, maintainer: requires approval, by: member

#18608 julia: Update to 1.9.0
  lang/julia/Portfile
Labels: type: enhancement, type: update, maintainer: open

#18613 skaffold: update to 2.4.1
  devel/skaffold/Portfile
Labels: type: update, maintainer, maintainer: open

#18607 qtkeychain: update to 0.13.2 for Qt5/6, 0.11.1 for Qt 4
  security/qtkeychain/Portfile
Labels: type: update, maintainer: none, by: member

#18617 advancecomp: update to 2.5
  archivers/advancecomp/Portfile
Labels: type: update, maintainer: none

#18622 dbvis: update to 23.2.1
  databases/dbvis/Portfile
Labels: type: update, maintainer, maintainer: open

#18623 VisualVM: update to 2.1.6
  java/VisualVM/Portfile
Labels: type: update, maintainer, maintainer: open

#18627 maven3: update to 3.9.2
  java/maven3/Portfile
Labels: type: update, maintainer, maintainer: open

#18612 openjdk11-graalvm: fix parse error on ppc
  java/openjdk11-graalvm/Portfile
Labels: type: bugfix, maintainer, maintainer: open

#18611 openjdk17-graalvm: fix parse error on ppc
  java/openjdk17-graalvm/Portfile
Labels: type: bugfix, maintainer, maintainer: open

#18628 erlang: update to 25.3
  lang/erlang/Portfile
Labels: type: enhancement, type: update, maintainer: requires approval

#18639 courier-unicode: update to 2.2.6
  devel/courier-unicode/Portfile
Labels: type: update, maintainer: none

#18638 cpp-utilities: update to 5.22.0
  devel/cpp-utilities/Portfile
Labels: type: update, maintainer: none

#18636 fxt: update to 2023.05.07
  math/fxt/Portfile
Labels: type: update, maintainer, maintainer: open

#18618 less: update to 633
  textproc/less/Portfile
Labels: type: update, maintainer: open

#18644 ruby-build: Update to 20230512
  ruby/ruby-build/Portfile
Labels: type: update, maintainer, maintainer: open

#18587 gdal: fix native variant flags
  gis/gdal/Portfile
Labels: type: bugfix, maintainer: open

#18230 hivex: new port
  devel/hivex/Portfile
Labels: type: submission

#18610 google-cloud-sdk: update to 430.0.0
  devel/google-cloud-sdk/Portfile
Labels: type: update, maintainer, maintainer: open

#17877 kokkos-devel: new port to track upstream, with support for 32-bit
  devel/kokkos/Portfile
Labels: type: submission, maintainer: open

#18075 repo: update to 2.32
  python/repo/Portfile
Labels: type: update, maintainer: none

#18647 rust-analyzer: update descriptions
  devel/rust-analyzer/Portfile
Labels: type: enhancement, type: update, maintainer: open

#18624 qbs: Update to 2.0.1
  devel/qbs/Portfile
  devel/qbs/files/patch-find-package.diff
Labels: type: enhancement, type: update, maintainer: open

#18236 gtkwave: update to 3.3.115
  cad/gtkwave/Portfile
Labels: type: update, maintainer: none

#18586 onetbb: fix build on clean 10.6 and 10.7
  devel/onetbb/files/patch-onetbb-older-platforms.diff
Labels: type: bugfix, maintainer: open

#18575 rocksdb: update to 8.1.1; use the right TBB
  databases/rocksdb/Portfile
  databases/rocksdb/files/0003-remove-redundant-move-11418.patch
Labels: type: bugfix, maintainer: open

#18640 eigen3-devel: update to current upstream
  math/eigen3/Portfile
Labels: type: update, maintainer, maintainer: open

#18646 adwaita-icon-theme: patch to disable parallel processing
  gnome/adwaita-icon-theme/Portfile
  gnome/adwaita-icon-theme/files/patch-adwaita-icon-theme-makefile.diff
Labels: type: bugfix, maintainer: open

#18643 OpenEXR, Imath: split Portfiles, removed unnecessary code, fix on old systems
  graphics/imath/Portfile
  graphics/openexr/Portfile
  graphics/openexr/files/patch-have_defines.diff
Labels: type: bugfix, type: enhancement, maintainer, maintainer: open, by: member

#18614 chntpw: new port
  sysutils/chntpw/Portfile
  sysutils/chntpw/files/chntpw.8
  sysutils/chntpw/files/patch-Makefile.diff
  sysutils/chntpw/files/patch-debian-04_get_abs_path.diff
  sysutils/chntpw/files/patch-debian-06_correct_test_open_syscall.diff
  sysutils/chntpw/files/patch-debian-07_detect_failure_to_write_key.diff
  sysutils/chntpw/files/patch-debian-08_no_deref_null.diff
  sysutils/chntpw/files/patch-debian-09_improve_robustness.diff
  sysutils/chntpw/files/patch-debian-10_remove_static.diff
  sysutils/chntpw/files/patch-debian-11_improve_documentation.diff
  sysutils/chntpw/files/patch-debian-12_readonly_filesystem.diff
  sysutils/chntpw/files/patch-debian-13_write_to_hive.diff
  sysutils/chntpw/files/patch-debian-14_improve_description.diff
  sysutils/chntpw/files/patch-debian-15_added_samunlock_binary.diff
  sysutils/chntpw/files/patch-warnings_64bit.diff
  sysutils/chntpw/files/reged.8
  sysutils/chntpw/files/sampasswd.8
  sysutils/chntpw/files/samunlock.8
  sysutils/chntpw/files/samusrgrp.8
Labels: type: submission

#18649 cgdm: update to 0.8.0
  devel/cgdb/Portfile
Labels: type: update, maintainer: none

#18650 howdoi: update to 2.0.20
  devel/howdoi/Portfile
Labels: type: update, maintainer: none

#18654 oniguruma6: fix spelling in long_description
  devel/oniguruma6/Portfile
Labels: maintainer: open

#18658 grep: fix for year2038 for 32-bit archs builds
  sysutils/grep/Portfile
Labels: type: bugfix, maintainer: open

#18661 libical: update to 3.0.16
  devel/libical/Portfile
  devel/libical/files/patch-gcc42.diff
Labels: type: update, maintainer: none

#18652 flann: update to 1.9.2
  science/flann/Portfile
Labels: type: update, maintainer: none

#18651 snac: update to 2.31
  net/snac/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer, maintainer: open

#18637 fpm: update to 0.8.2
  devel/fpm/Portfile
  devel/fpm/files/patch-install.diff
Labels: type: update, maintainer, maintainer: open

#18656 qt5-qtlocation: mapbox-gl-native: patch unique_any.hpp, for std::move
  aqua/qt5/Portfile
  aqua/qt5/files/patch-qtlocation-mbgl-unique_any.hpp.diff
Labels: maintainer: open, by: member

#18664 poac: update to 0.6.0
  sysutils/poac/Portfile
Labels: type: bugfix, type: update, maintainer: none

#18667 py-taskw: add python3.11 variant
  python/py-taskw/Portfile
Labels: type: enhancement, maintainer: none

#18666 py-segno: add python3.11 variant
  python/py-segno/Portfile
Labels: type: enhancement, maintainer: open

#18668 codemod: new port
  devel/codemod/Portfile
Labels: type: submission

#18626 ghidra: Update to 10.3
  devel/ghidra/Portfile
Labels: type: update, maintainer: open

#18634 ufo-ai: new port
  games/ufo-ai/Portfile
  games/ufo-ai/files/patch-bug-5336.diff
  games/ufo-ai/files/patch-bug-5345.diff
Labels: by: member

#18672 tk: Backport fix for ttk::ThemeChanged error
  x11/tk/Portfile
  x11/tk/files/fix-themechanged-error.patch
Labels: type: bugfix, maintainer: open

#18678 lang/sbcl: update to sbcl-2.3.4
  lang/sbcl/Portfile
  math/maxima/Portfile
Labels: type: update, maintainer: open, by: member

#18677 glib2-devel: remove legacysupport, fix Tiger
  devel/glib2-devel/Portfile
  devel/glib2-devel/files/patch-glib_gmem.c.diff
  devel/glib2-devel/files/patch-glib_gspawn.c.diff
Labels: maintainer: open

#18682 groonga: update to 13.0.1
  databases/groonga/Portfile
  databases/groonga/files/patch-cxx11.diff
Labels: type: bugfix, type: update, maintainer: open

#18684 fheroes2: update to 1.0.4
  games/fheroes2/Portfile
Labels: type: update, maintainer, maintainer: open

#18671 McBopomofo: provide versions for <10.8; fix build for >20
  aqua/McBopomofo/Portfile
Labels: type: bugfix, maintainer: none

#18689 zmap: submission new Portfile ZMap version 3.0.0 beta1
  net/zmap/Portfile
Labels: type: submission

#18690 fheroes2: use legacysupport.use_mp_libcxx on Mojave and older
  games/fheroes2/Portfile
Labels: maintainer: open

#18680 libuninameslist: update to 20221022
  devel/libuninameslist/Portfile
Labels: type: update, maintainer: none

#18692 optpp: update to 20220920
  math/optpp/Portfile
Labels: type: update, maintainer: none

#18694 bzip3: update to 1.3.0
  archivers/bzip3/Portfile
Labels: type: bugfix, type: enhancement, type: update, type: security fix, maintainer: open

#18681 supertuxkart: Fix build on 10.12 and earlier
  games/supertuxkart/Portfile
  games/supertuxkart/files/patch-supertuxkart-iosurfaceref.diff
  games/supertuxkart/files/patch-supertuxkart-no-metal.diff
Labels: maintainer: none

#18695 McBopomofo: depend on Macports python; portfile update
  aqua/McBopomofo/Portfile
Labels: type: bugfix, maintainer: none

#18663 pika: legacysupport.use_mp_libcxx for <10.16 to support filesystem
  devel/pika/Portfile
Labels: type: bugfix, maintainer, maintainer: open

#18700 snappy: update to 1.1.10
  archivers/snappy/Portfile
  archivers/snappy/files/patch-disable-sign-compare-warning.diff
Labels: type: update, maintainer: none, by: member

#18693 julia: Update to 1.9.0 (revised)
  lang/julia/Portfile
Labels: type: enhancement, type: update, maintainer: open

#18701 kokkos-devel: update to fix checksums
  devel/kokkos/Portfile
Labels: type: bugfix, maintainer: open
