Repository macports/macports-ports, pull requests merged in 2023-06, with the labels that each got.

#18907 netclient: new port v0.20.0
  net/netclient/Portfile
Labels: type: enhancement, type: submission

#18912 wireshark3: build with python311
  net/wireshark3/Portfile
Labels: maintainer: requires approval

#18864 symengine: update to 0.10.1
  math/symengine/Portfile
Labels: type: update, maintainer: open

#18872 openexr: ensure struct is packed on PPC systems
  graphics/openexr/Portfile
  graphics/openexr/files/patch-ensure_pack.diff
Labels: type: bugfix, maintainer, maintainer: open, by: member

#18914 notmuch: python3.10 -> python3.11 dependency
  mail/notmuch/Portfile
Labels: maintainer: open

#18844 lighttpd: Update to 1.4.71
  www/lighttpd/Portfile
Labels: type: bugfix, type: update, maintainer: open

#18916 cracklib: update to 2.9.11
  security/cracklib/Portfile
  security/cracklib/files/autogen.sh.patch
Labels: type: update, maintainer: none, by: member

#18875 lirc: allow build on newer systems (Python 3.11 & avoid conflict VERSION file and version header)
  sysutils/lirc/Portfile
Labels: type: bugfix, maintainer: open, by: member

#18605 zstdConfig.cmake: subport to install zstd CMake file
  archivers/zstd/Portfile
Labels: type: enhancement, maintainer: none, by: member

#18921 unrar: update to 6.2.8
  archivers/unrar/Portfile
Labels: type: update, maintainer: none

#18917 py-rich: update to 13.4.1
  python/py-rich/Portfile
Labels: type: update, maintainer: open, by: member

#18475 update vim to revision 1499
  editors/vim/Portfile
Labels: type: enhancement, type: update, maintainer: requires approval

#18918 mapserver: update to 8.0.1
  gis/mapserver/Portfile
  gis/mapserver/files/cmakelist.diff
  gis/mapserver/files/patch-configure.diff
  gis/mapserver/files/python.diff
Labels: type: update, maintainer: open

#18922 openconnect: update to version 9.12
  net/openconnect/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer: none

#18926 google-cloud-sdk: update to 433.0.0
  devel/google-cloud-sdk/Portfile
Labels: type: update, maintainer, maintainer: open

#18911 bzip3: update to 1.3.1
  archivers/bzip3/Portfile
Labels: type: update, maintainer: open, by: member

#17403 ginkgo: fix tests, add build dep on gtest
  math/ginkgo/Portfile
Labels: type: bugfix, type: enhancement, maintainer, maintainer: open

#18930 clojure: update to 1.11.1.1347
  lang/clojure/Portfile
Labels: type: update, maintainer, maintainer: open

#18933 postgis3: update to version 3.3.3
  databases/postgis3/Portfile
Labels: type: update, maintainer: open

#18936 scrcpy: Update to 2.0
  multimedia/scrcpy/Portfile
  multimedia/scrcpy/files/6b769675fa68e60c9765022e43c4d7b1e329353a.patch
Labels: type: update, maintainer: open, by: member

#18944 py-hypothesis: update to 6.75.9
  python/py-hypothesis/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#18938 scala: update to 3.3; add scala3.3 subport
  lang/scala/Portfile
  lang/scala/files/scala3.3
Labels: type: enhancement, type: update, maintainer, maintainer: open

#18940 singular: update to 4.3.2p2
  math/singular/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#18937 cl-bordeaux-threads: update to 0.9.1
  lisp/cl-bordeaux-threads/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#18941 cl-iterate: new port
  lisp/cl-iterate/Portfile
Labels: type: submission

#18942 py-alive-progress: update to 3.1.4
  python/py-alive-progress/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#18946 minio[-mc]: Update to 2022-10-2[24].
  www/minio-mc/Portfile
  www/minio/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#18948 openjdk17-openj9: update to 17.0.7
  java/openjdk17-openj9/Portfile
Labels: type: update, maintainer, maintainer: open

#18949 openjdk11-openj9: update to 11.0.19
  java/openjdk11-openj9/Portfile
Labels: type: update, maintainer, maintainer: open

#18935 openjdk8: fix configure on arm64
  java/openjdk8/Portfile
  java/openjdk8/files/Support-arm64-and-fix-zero-assembler.diff
Labels: type: bugfix, maintainer, maintainer: open

#18950 openjdk8-openj9: update to 8u372
  java/openjdk8-openj9/Portfile
Labels: type: update, maintainer, maintainer: open

#18951 openjdk19-openj9: new submission
  java/openjdk19-openj9/Portfile
Labels: type: submission

#18952 sbcl: fix build on i386
  lang/sbcl/Portfile
  lang/sbcl/files/patch-i386-missed-context.diff
Labels: type: bugfix, maintainer, maintainer: open

#18953 sbcl: fix build on i386
  lang/sbcl/Portfile
  lang/sbcl/files/patch-i386-old-preprocessor.diff
Labels: maintainer, maintainer: open

#18955 h4h5tools: fix build on newer systems
  science/h4h5tools/Portfile
  science/h4h5tools/files/patch-h4h5tools.diff
Labels: type: bugfix, maintainer: none, by: member

#18958 libimobiledevice: Add libimobiledevice-glue-devel
  devel/libimobiledevice-glue/Portfile
  devel/libirecovery/Portfile
Labels: maintainer: open

#18873 bitcoin: use legacysupport.use_mp_libcxx on Mojave and older
  finance/bitcoin/Portfile
Labels: maintainer: open

#18957 cl-gobject-introspection: new port
  lisp/cl-gobject-introspection/Portfile
Labels: type: submission

#18962 w3m: fix build with GCC 4.2
  www/w3m/Portfile
Labels: type: bugfix, maintainer, maintainer: open

#18963 vtm: update to 0.9.9m
  sysutils/vtm/Portfile
Labels: type: update, maintainer: none

#18913 cppman: update to 0.5.6
  lang/cppman/Portfile
Labels: type: update, maintainer: open, by: member

#18965 bitwarden-cli: Update to 2023.05.0
  security/bitwarden-cli/Portfile
Labels: type: update, maintainer, maintainer: open

#18964 detekt-cli: Update to version 1.23.0
  java/detekt-cli/Portfile
Labels: type: update, maintainer, maintainer: open

#18884 yabai: update to 5.0.6
  sysutils/yabai/Portfile
Labels: type: enhancement, type: update, maintainer: open

#18959 sbcl: fix build on 10.6 i386; update to 2.2.5
  lang/sbcl/Portfile
  lang/sbcl/files/patch-i386-contrib-sb-posix-posix-tests.lisp.diff
  lang/sbcl/files/patch-i386-mask-out-O_LARGEFILE-in-fcntl-1-test.diff
  lang/sbcl/files/patch-i386-missed-context.diff
  lang/sbcl/files/patch-i386-revert-OS_THREAD_STACK.diff
Labels: type: bugfix, maintainer, maintainer: open

#18968 snac: update to version 2.34
  net/snac/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#18967 lagrange: update to 1.16.3
  net/lagrange/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#18970 coreutils-uutils: update to 0.0.19
  sysutils/coreutils-uutils/Portfile
Labels: type: update, maintainer: open, by: member

#18972 vftool: new port
  sysutils/vftool/Portfile
Labels: type: submission, by: member

#18945 tinyows: update to version 1.2.0
  gis/tinyows/Portfile
  gis/tinyows/files/patch-Makefile_in.diff
  gis/tinyows/files/patch-ows_define_h.diff
Labels: type: update, maintainer: none

#18982 fpm: update to 0.9.0
  devel/fpm/Portfile
  devel/fpm/files/patch-install.diff
Labels: type: update, maintainer, maintainer: open

#18974 pika: update to 0.16.0
  devel/pika/Portfile
Labels: type: update, maintainer, maintainer: open

#18973 ghc: Update to version 9.6.2
  lang/ghc/Portfile
Labels: type: update, maintainer, maintainer: open

#18985 starpu: update to 1.4.1
  devel/starpu/Portfile
Labels: type: update, maintainer, maintainer: open

#18979 protobuf-c: Update required C++ version from 2011 to 2014
  devel/protobuf-c/Portfile
Labels: type: bugfix, type: update, maintainer: none

#18988 chromedriver: update to 114.0.5735.90
  www/chromedriver/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#18987 retdec-devel: update to 20230525
  devel/retdec/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#18670 clblast: set known_fail for darwin <11, since OpenCL 1.1 not supported
  math/clblast/Portfile
Labels: type: bugfix, maintainer: open

#18084 bash: blacklist old Xcode compilers that fail to build it
  shells/bash/Portfile
Labels: type: bugfix, maintainer: requires approval

#18865 qd: update to 2.3.23
  devel/qd/Portfile
Labels: type: update, maintainer: requires approval, maintainer: timeout

#18989 qt5-qtwebengine: remove unused dependencies jsoncpp and protobuf3-cpp
  aqua/qt5/Portfile
Labels: maintainer: open

#18915 lua-resty-*: install in LuaJIT module directory
  lua/lua-resty-core/Portfile
  lua/lua-resty-lrucache/Portfile
Labels: type: bugfix, maintainer: open, by: member

#18999 google-cloud-sdk: update to 434.0.0
  devel/google-cloud-sdk/Portfile
Labels: type: update, maintainer, maintainer: open

#18996 starship: update to 1.15.0
  sysutils/starship/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#18993 Gildas: update to 202306a
  science/gildas/Portfile
Labels: type: enhancement, type: update, maintainer

#18994 ffcall: fix build when cross-compiling
  devel/ffcall/Portfile
Labels: type: bugfix, maintainer: none, by: member

#19001 vinci: new port in math
  math/vinci/Portfile
Labels: type: submission

#19002 josm: update to 18746
  gis/JOSM/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#18903 pandoc: add notes about PDF support
  textproc/pandoc/Portfile
Labels: type: update, maintainer: open

#19000 qt5: update to 5.15.10
  aqua/qt5/Portfile
  aqua/qt5/files/CVE-2023-33285-qtbase-5.15.diff
  aqua/qt5/files/patch-sdk-no-stderr.diff
Labels: type: bugfix, type: update, maintainer: open

#18975 sbcl: pin 2.2.5 before 10.7
  lang/sbcl/Portfile
  lang/sbcl/files/0001-fix-building-when-root-directory-contain-non-ASCII-c.patch
  lang/sbcl/files/0002-add-MacPorts-XDG_DATA_DIRS.patch
  lang/sbcl/files/0003-Use-CLOCK_MONOTONIC-when-CLOCK_PROCESS_CPUTIME_ID-un.patch
  lang/sbcl/files/0004-Disable-pdf-manual.patch
  lang/sbcl/files/0005-Use-MacPorts-zstd.patch
  lang/sbcl/files/1001-Darwin-disable-custom-nanosleep-before-10.6.patch
  lang/sbcl/files/1002-Darwin-recovery-support-non-dispatch-semaphores.patch
  lang/sbcl/files/1003-x86-Darwin-mask-out-O_LARGEFILE-in-fcntl.1-test.patch
  lang/sbcl/files/1004-x86-Darwin-revert-OS_THREAD_STACK.patch
  lang/sbcl/files/1005-x86-Darwin-fix-build-by-old-preprocessor.patch
  lang/sbcl/files/1006-x86-Darwin-disable-failing-stat-mode-tests.patch
  lang/sbcl/files/1007-x86-Darwin-add-missed-OS_CONTEXT_PC.patch
  lang/sbcl/files/1008-x86-Darwin-fix-syntax-typos.patch
  lang/sbcl/files/1009-ppc-Darwin-Revert-Delete-support-for-and-darwin-ppc.patch
  lang/sbcl/files/1010-ppc-Darwin-Config.ppc-use-right-compiler-and-deploym.patch
  lang/sbcl/files/1011-ppc-Darwin-ppc-assem.S-fix-wrong-assembler-code-chun.patch
  lang/sbcl/files/1012-ppc-Darwin-Misc-fixes-for-PPC.patch
  lang/sbcl/files/1013-ppc-Darwin-make-config.sh-use-gcc-tls-for-ppc.patch
  lang/sbcl/files/1014-ppc-Darwin-ppc-assem-a-minor-fix-to-assembler-syntax.patch
  lang/sbcl/files/patch-config-darwin-arm64.diff
  lang/sbcl/files/patch-config-darwin-x86_64.diff
  lang/sbcl/files/patch-contrib-sb-posix-posix-tests.lisp.diff
  lang/sbcl/files/patch-make-doc.diff
  lang/sbcl/files/patch-use-right-gcc.diff
Labels: type: bugfix, type: enhancement, maintainer, maintainer: open

#19006 Revert "ci: Combine grep and cut into a single sed"
  .github/workflows/main.yml
Labels: type: bugfix, by: member

#19005 py-meshio: add py-rich dependency
  python/py-meshio/Portfile
Labels: type: bugfix, maintainer: open

#18984 clisp: pass FORCE_UNSAFE_CONFIGURE=1 to configure to fix powerpc build
  lang/clisp/Portfile
Labels: type: bugfix, maintainer: open

#19008 micronaut: update to 3.9.3
  java/micronaut/Portfile
Labels: type: update, maintainer, maintainer: open

#19012 drupal7: update to 7.98
  www/drupal7/Portfile
Labels: type: bugfix, type: update, type: security fix, maintainer: none

#19017 qt513-qtwebengine: fix build on macOS 10.15
  aqua/qt513/files/patch-qtwebengine_sdk.diff
Labels: type: bugfix, maintainer: open

#19016 ruby-build: Update to 20230608
  ruby/ruby-build/Portfile
Labels: type: update, maintainer, maintainer: open

#17778 wxWidgets-3.0: minor fix for PPC (relevant on 10.6, does not change anything for other configs)
  graphics/wxWidgets-3.0/Portfile
  graphics/wxWidgets-3.0/files/patch-ppc.diff
Labels: type: bugfix, maintainer: open

#19025 proj9: update to 9.2.1
  gis/proj9/Portfile
Labels: type: update, maintainer: open

#19020 cln: use muniversal PG version 1.1
  math/cln/Portfile
Labels: type: enhancement, maintainer: open, by: member

#19027 bart: Initial portfile
  science/bart/Portfile
  science/bart/files/Makefile.patch
Labels: type: submission, by: member

#19029 kotlin: update to 1.8.22
  lang/kotlin/Portfile
Labels: type: update, maintainer, maintainer: open

#19023 gdb-apple: fix build in Rosetta
  devel/gdb-apple/Portfile
Labels: type: bugfix, maintainer: open

#19034 bart: Tweaks to Portfile (no bump).
  science/bart/Portfile
Labels: maintainer, maintainer: open, by: member

#19035 got: update to version 0.89
  devel/got/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer, maintainer: open

#19038 flock: fix build with gcc-4.2
  sysutils/flock/Portfile
  sysutils/flock/files/patch-gcc-4.diff
Labels: type: bugfix, maintainer: open

#19040 blake3: update to 1.4.0
  security/blake3/Portfile
Labels: type: update, maintainer, maintainer: open

#18980 emacs{-app,}-devel: update to 20230605
  editors/emacs/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#19033 spirv-tools: use `legacysupport.use_mp_libcxx` on Mojave and older to support `<filesystem>`
  graphics/spirv-tools/Portfile
Labels: type: bugfix, maintainer: open

#19039 poppler qt5 ports: require Qt 5.8
  graphics/poppler-devel/Portfile
  graphics/poppler/Portfile
Labels: type: bugfix, maintainer: open

#18852 boehmgc: update to 8.2.4
  devel/boehmgc/Portfile
Labels: type: bugfix, type: update, maintainer: none

#18977 ruby-devel: update to upstream master (2023.06.05)
  lang/ruby-devel/Portfile
Labels: type: update, maintainer, maintainer: open

#19042 rawhide: new port (version 3.2)
  sysutils/rawhide/Portfile
Labels: type: enhancement, type: submission

#19043 sbcl: pin as 2.3.5 for i386 and powerpc
  lang/sbcl/Portfile
  lang/sbcl/files/0005-Use-MacPorts-zstd.patch
  lang/sbcl/files/1001-x86-Darwin-Revert-x86-darwin-files.patch
  lang/sbcl/files/1002-x86-Darwin-Revert-Perform-darwin-related-housekeepin.patch
  lang/sbcl/files/1003-x86-Darwin-Remove-mach-exception-handler.patch
  lang/sbcl/files/1004-Darwin-disable-custom-nanosleep-before-10.6.patch
  lang/sbcl/files/1005-Darwin-recovery-support-non-dispatch-semaphores.patch
  lang/sbcl/files/1006-x86-Darwin-mask-out-O_LARGEFILE-in-fcntl.1-test.patch
  lang/sbcl/files/1007-x86-Darwin-revert-OS_THREAD_STACK.patch
  lang/sbcl/files/1008-x86-Darwin-fix-build-by-old-preprocessor.patch
  lang/sbcl/files/1009-x86-Darwin-disable-failing-stat-mode-tests.patch
  lang/sbcl/files/1010-x86-Darwin-add-missed-OS_CONTEXT_PC.patch
  lang/sbcl/files/1011-x86-Darwin-fix-syntax-typos.patch
  lang/sbcl/files/1012-ppc-Darwin-Revert-Delete-support-for-and-darwin-ppc.patch
  lang/sbcl/files/1013-ppc-Darwin-Config.ppc-follow-up-changes.patch
  lang/sbcl/files/1013-ppc-Darwin-make-config.sh-use-gcc-tls-for-ppc.patch
  lang/sbcl/files/1014-ppc-Darwin-ppc-assem.S-fix-wrong-assembler-code-chun.patch
  lang/sbcl/files/1015-ppc-Darwin-Misc-fixes-for-PPC.patch
  lang/sbcl/files/1016-ppc-Darwin-ppc-assem-a-minor-fix-to-assembler-syntax.patch
  lang/sbcl/files/1017-Fix-building-by-lisp-without-endian-features.patch
  lang/sbcl/files/1018-Darwin-implement-os_tsd_get_direct-for-macOS-before-.patch
Labels: type: enhancement, maintainer, maintainer: open

#19048 tio: update to 2.6
  comms/tio/Portfile
Labels: type: update, maintainer: none, by: member

#18990 cadaver: update to 0.24
  www/cadaver/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer: open

#19041 julia: Update to 1.9.1
  lang/julia/Portfile
Labels: type: enhancement, type: update, maintainer: open

#19050 qt5*: use qt5 PG to set QMAKE_MAC_SDK
  aqua/phantomjs-qt/Portfile
  aqua/qt5/Portfile
  aqua/qt511/Portfile
  aqua/qt513/Portfile
  aqua/qt53/Portfile
  aqua/qt55/Portfile
  aqua/qt56/Portfile
  aqua/qt57/Portfile
  aqua/qt58/Portfile
  aqua/qt59/Portfile
Labels: type: enhancement, maintainer, maintainer: open, by: member

#19059 sbcl: fix buils on 11/arm, enable threads on PPC
  lang/sbcl/Portfile
  lang/sbcl/files/0004-Disable-pdf-manual.patch
  lang/sbcl/files/1004-Darwin-disable-custom-nanosleep-before-10.6.patch
  lang/sbcl/files/1004-Darwin-use-libc-nanosleep-before-10.6-and-on-PPC.patch
  lang/sbcl/files/1005-Darwin-recovery-support-non-dispatch-semaphores.patch
  lang/sbcl/files/1006-x86-Darwin-mask-out-O_LARGEFILE-in-fcntl.1-test.patch
  lang/sbcl/files/1007-x86-Darwin-revert-OS_THREAD_STACK.patch
  lang/sbcl/files/1008-x86-Darwin-fix-build-by-old-preprocessor.patch
  lang/sbcl/files/1009-x86-Darwin-disable-failing-stat-mode-tests.patch
  lang/sbcl/files/1010-x86-Darwin-add-missed-OS_CONTEXT_PC.patch
  lang/sbcl/files/1011-x86-Darwin-fix-syntax-typos.patch
  lang/sbcl/files/1012-ppc-Darwin-Revert-Delete-support-for-and-darwin-ppc.patch
  lang/sbcl/files/1013-ppc-Darwin-Config.ppc-follow-up-changes.patch
  lang/sbcl/files/1014-ppc-Darwin-ppc-assem.S-fix-wrong-assembler-code-chun.patch
  lang/sbcl/files/1015-ppc-Darwin-Misc-fixes-for-PPC.patch
  lang/sbcl/files/1016-ppc-Darwin-ppc-assem-a-minor-fix-to-assembler-syntax.patch
  lang/sbcl/files/1017-Fix-building-by-lisp-without-endian-features.patch
  lang/sbcl/files/1018-Darwin-implement-os_tsd_get_direct-for-macOS-before-.patch
  lang/sbcl/files/1019-ppc-Darwin-fix-threads-support.patch
Labels: type: bugfix, type: enhancement, maintainer, maintainer: open

#19058 fx: update to 24.1.0
  sysutils/fx/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#19056 ghc-filesystem: update to 1.5.14
  devel/ghc-filesystem/Portfile
Labels: type: update, maintainer: none

#19061 openssh: update compiler.blacklist-append to avoid segfault.
  net/openssh/Portfile
Labels: type: bugfix, type: update, maintainer, maintainer: open

#19063 sbcl: fix build on macOS 11 / arm
  lang/sbcl/Portfile
  lang/sbcl/files/0004-arm-Darwin-disable-futex-on-BigSur.patch
Labels: maintainer, maintainer: open

#19037 py-beancount: add python3.11 variant
  python/py-beancount/Portfile
  python/py-bottle/Portfile
  python/py-google-api-core/Portfile
  python/py-google-api/Portfile
  python/py-google-auth-httplib2/Portfile
  python/py-google-auth/Portfile
  python/py-googleapis-common-protos/Portfile
  python/py-magic/Portfile
  python/py-uritemplate/Portfile
Labels: type: enhancement, maintainer: open

#19060 glslang: require C++17
  graphics/glslang/Portfile
Labels: type: bugfix, type: enhancement, maintainer: open

#19067 hypre: update to 2.28.0
  math/hypre/Portfile
Labels: type: update, maintainer: none

#19055 zfp: update to upstream, fix tests on 32-bit
  science/zfp/Portfile
Labels: type: bugfix, type: update, maintainer, maintainer: open

#19007 py-pdal: add new port, version 3.2.3
  python/py-pdal/Portfile
Labels: type: submission

#18899 py-wxpython-4.0: add python 3.11
  python/py-wxpython-4.0/Portfile
  python/py-wxpython-4.0/files/buildtools_config_py.patch
Labels: type: enhancement, maintainer: none

#19075 loli: new port in lang
  lang/loli/Portfile
  lang/loli/files/loli-fix.diff
Labels: type: submission

#19074 rapidjson-devel: update to 20230517, fix tests
  devel/rapidjson-devel/Portfile
  devel/rapidjson-devel/files/patch-fix-cxx-standard.diff
Labels: type: update, maintainer, maintainer: open

#19077 loli: on 10.8 avoid xcode clang, it fails to build it
  lang/loli/Portfile
Labels: type: bugfix, maintainer, maintainer: open

#19083 radian: update to 0.6.6
  math/radian/Portfile
Labels: type: update, maintainer, maintainer: open

#19089 google-cloud-sdk: update to 435.0.0
  devel/google-cloud-sdk/Portfile
Labels: type: update, maintainer, maintainer: open

#19090 skaffold: update to 2.5.1
  devel/skaffold/Portfile
Labels: type: update, maintainer, maintainer: open

#19092 alex: Update to version 3.3.0.0
  devel/alex/Portfile
Labels: type: update, maintainer: none

#19082 paramonte: do not install test binary
  math/paramonte/Portfile
Labels: type: bugfix, maintainer, maintainer: open

#19081 beets-devel: update to 20230606; beets-alternatives: update to 0.11.0
  audio/beets/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#19099 toot: update to 0.36.0
  net/toot/Portfile
Labels: type: bugfix, type: enhancement, type: update, type: security fix, maintainer: open

#19101 fheroes2: update to 1.0.5, style nits
  games/fheroes2/Portfile
Labels: type: update, maintainer, maintainer: open

#19097 librtprocess: new port in graphics
  graphics/librtprocess/Portfile
  graphics/librtprocess/files/0001-ProcessorTargets-fix-native-flags.patch
Labels: type: submission

#19093 HaXml: Update to version 1.25.12
  devel/HaXml/Portfile
Labels: type: update, maintainer: none

#19096 ruby-build: Update to 20230614
  ruby/ruby-build/Portfile
Labels: type: update, maintainer, maintainer: open

#19098 Codeberg portgroup: Comment fix only
  _resources/port1.0/group/codeberg-1.0.tcl
Labels: type: bugfix

#19104 duckdb: fix build with gcc
  databases/duckdb/Portfile
Labels: type: bugfix, maintainer: open

#19105 libretroshare: update to current upstream (2023.06.13)
  net/libretroshare/Portfile
Labels: type: update, maintainer, maintainer: open

#19110 ruby-build: Update to 20230615
  ruby/ruby-build/Portfile
Labels: type: update, maintainer, maintainer: open

#19112 nedit: update to 5.7
  editors/nedit/Portfile
  editors/nedit/files/patch-Makefile-man.diff
  editors/nedit/files/patch-segfault.diff
Labels: type: update, maintainer: none, by: member

#17284 libopenmpt: new port in audio
  audio/libopenmpt/Portfile
Labels: type: submission

#19088 openjdk20-graalvm: new submission
  java/openjdk20-graalvm/Portfile
Labels: type: submission

#19087 openjdk17-graalvm: update to 17.0.7
  java/openjdk17-graalvm/Portfile
Labels: type: update, maintainer, maintainer: open

#19085 ecCodes: update to 2.30.2
  science/ecCodes/Portfile
Labels: type: update, maintainer, maintainer: open

#19078 gdal: fix opportunistic linking to pcre2
  gis/gdal/Portfile
Labels: type: bugfix, maintainer: open

#19073 kokkos-devel: update to 2023.06.11
  devel/kokkos/Portfile
Labels: type: update, maintainer: open

#19117 ismrmrd: 1.13.7
  science/ismrmrd/Portfile
Labels: maintainer, maintainer: open, by: member

#19100 py-pytorch: switch to system TBB
  python/py-pytorch/Portfile
Labels: type: bugfix, maintainer: none

#19119 py-pytorch: depedns on onetbb, not tbb
  python/py-pytorch/Portfile
Labels: type: bugfix, maintainer: none

#19064 ecl: disable any attempt to use on ppc and i386
  _resources/port1.0/group/common_lisp-1.0.tcl
  lang/ecl/Portfile
Labels: type: bugfix, maintainer, maintainer: open

#19107 icu-devel{,-docs}: update to 73.2
  devel/icu-devel/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#19120 fortran-stdlib: update to upstream (2023.06.16)
  lang/fortran-stdlib/Portfile
Labels: type: update, maintainer, maintainer: open

#19122 py-pytorch: blacklist unsupported clang
  python/py-pytorch/Portfile
Labels: type: bugfix, maintainer: none

#19129 kokkos-devel: update to 2023.06.15, use tarball_from archive, since Github keeps breaking checksums
  devel/kokkos/Portfile
Labels: type: update, maintainer: open

#18934 vim: Fix +python3 variant, follow-up to #18475
  editors/vim/Portfile
Labels: type: bugfix, maintainer: requires approval, by: member

#19114 amule: new port
  net/amule/Portfile
Labels: type: submission

#19084 toml-f: pick latest fixes from upstream
  fortran/toml-f/Portfile
Labels: maintainer, maintainer: open

#19031 audacious-*: removed unnecessary dependency on qt5
  multimedia/audacious-core/Portfile
  multimedia/audacious-plugins/Portfile
Labels: type: bugfix, maintainer: requires approval, maintainer: timeout, by: member

#19028 asymptote: update to 2.86, drop now unneeded patches
  graphics/asymptote/Portfile
  graphics/asymptote/files/patch-Makefile.diff
  graphics/asymptote/files/patch-time.diff
Labels: type: update, maintainer: open

#19009 transmission: install .torrent utils with +daemon
  net/transmission/Portfile
Labels: maintainer: open

#18931 py-hyrule: submission
  python/py-hyrule/Portfile
Labels: type: enhancement, type: submission
