Repository macports/macports-ports, pull requests merged in 2023-02, with the labels that each got.

#17487 homebank: update to 5.6.1
  x11/homebank/Portfile
Labels: type: update, maintainer: open

#17270 ruby-devel: update to current upstream
  lang/ruby-devel/Portfile
  lang/ruby-devel/files/ruby32
  lang/ruby-devel/files/ruby33
Labels: type: update, maintainer, maintainer: open

#17553 datree: update to version 1.8.21
  devel/datree/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#17542 toxcore: new port in net
  net/toxcore/Portfile
Labels: type: submission

#17386 ruby30: Fix build on 10.4, 10.5
  lang/ruby30/Portfile
  lang/ruby30/files/patch-generated.diff
  lang/ruby30/files/patch-random.c.diff
  lang/ruby30/files/patch-sources.diff
Labels: type: bugfix, maintainer: open

#17519 asciidoctor: Revert to last fully working version of Ruby (3.0)
  textproc/asciidoctor/Portfile
Labels: type: bugfix, maintainer: none

#17538 gpsd: update to 3.25, with earlier versions included
  net/gpsd/Portfile
Labels: type: update, maintainer, maintainer: open

#17556 py-cchardet: require cython at build phase (also fixes Python 3.11 incompatibility)
  python/py-cchardet/Portfile
Labels: type: bugfix, maintainer: open, by: member

#17451 OpenBLAS: move header files, reduce code with muniversal PG 1.1, add missing build dependency, and set NUM_THREADS
  math/OpenBLAS/Portfile
Labels: type: bugfix, type: enhancement, maintainer: open, by: member

#17526 fricas: revbump because of sbcl version change
  lang/sbcl/Portfile
  math/fricas/Portfile
Labels: maintainer, maintainer: open

#17513 gptfdisk: update to 1.0.9
  sysutils/gptfdisk/Portfile
  sysutils/gptfdisk/files/patch-Makefile.mac.diff
Labels: type: enhancement, type: update, maintainer: open

#17462 avr-libc: update to 2.1.0, add arm64 build support
  cross/avr-libc/Portfile
Labels: type: bugfix, type: update, maintainer: none

#17563 xeus-zmq: set cxx_standard 2014, fix build on <10.7
  devel/xeus-zmq/Portfile
Labels: type: bugfix, maintainer: open

#17540 ismrmrd: fixups
  science/ismrmrd/Portfile
  science/ismrmrd/files/patch-ismrmrd-no-werror.diff
Labels: type: bugfix, maintainer: open, by: member

#17562 pika: update to 0.12.0, drop now unneeded patch
  devel/pika/Portfile
  devel/pika/files/0001-compiler_fence-fix-for-Darwin-PPC.patch
Labels: type: enhancement, type: update, maintainer, maintainer: open

#17564 bsd-games: new port
  games/bsd-games/Portfile
  games/bsd-games/files/patch-gomoku.diff
Labels: type: submission

#17573 blink: new port
  emulators/blink/Portfile
Labels: type: submission, by: member

#17572 kotlin: update to 1.8.10
  lang/kotlin/Portfile
Labels: type: update, maintainer, maintainer: open

#17561 eigenmath: new port in math
  math/eigenmath/Portfile
Labels: type: submission

#17445 py-notebook: add py-jupyter_packaging dependency
  python/py-notebook/Portfile
Labels: maintainer: open

#17580 matrix-calculator: declare linking to libreadline
  math/matrix-calculator/Portfile
Labels: type: bugfix, maintainer, maintainer: open

#17579 hydra: fix build on <10.7
  security/hydra/Portfile
Labels: type: bugfix, maintainer: open

#17266 ofc: add fixes by upstream
  lang/ofc/Portfile
  lang/ofc/files/patch-upstream.diff
Labels: type: bugfix, maintainer, maintainer: open

#17585 josm: update to 18646
  gis/JOSM/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#17587 Freecell: fix build on 10.6
  aqua/Freecell/Portfile
  aqua/Freecell/files/patch-Freecell-undeclared-selectors.diff
Labels: type: bugfix, maintainer: none

#17592 eigenmath: respect MacPorts compiler & linker flags
  math/eigenmath/Portfile
  math/eigenmath/files/patch-Makefile.diff
Labels: type: bugfix, maintainer: open, by: member

#17589 gallery-dl: use python 3.11
  net/gallery-dl/Portfile
Labels: maintainer: none

#17557 mvnd: switch master_sites to official download URL
  java/mvnd/Portfile
Labels: maintainer, maintainer: open

#17597 upx: update to 4.0.2
  archivers/upx/Portfile
Labels: type: update, maintainer: open, by: member

#17598 wails: new port (version 2.3.1)
  devel/wails/Portfile
Labels: type: submission, by: member

#17577 terragrunt-0.43: update to 0.43.2; add @ajhall as maintainer
  sysutils/terragrunt/Portfile
Labels: type: bugfix, type: update, maintainer: open

#17575 dnscontrol: update to 3.26.0
  sysutils/dnscontrol/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#17535 py-rawpy: add py311 subport
  python/py-rawpy/Portfile
Labels: maintainer, maintainer: open

#17596 Freecell: fix build on Ventura
  aqua/Freecell/Portfile
  aqua/Freecell/files/patch-Freecell-no-deprecated-implementations.diff
  aqua/Freecell/files/patch-Freecell-undeclared-selectors.diff
Labels: type: bugfix, maintainer: none

#17594 miniflux: update to 2.0.42
  net/miniflux/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#17584 GPXSee: update to 11.12
  gis/GPXSee/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#17604 maven3: update to 3.9.0
  java/maven3/Portfile
Labels: type: update, maintainer, maintainer: open

#17582 eiscor: fix build on 10.7
  math/eiscor/Portfile
Labels: type: bugfix, maintainer, maintainer: open

#17605 dcmtk: Update for website reorg; Remove no-longer-needed patch.
  graphics/dcmtk/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#17606 ismrmrd: Bump; update for upstream changes.
  science/ismrmrd/Portfile
  science/ismrmrd/files/pugixml.patch
Labels: maintainer, maintainer: open, by: member

#17602 blaspp: new port in math
  math/blaspp/Portfile
Labels: type: submission

#17547 polkit: Clean up old references to configure.ac
  security/policykit/Portfile
  security/policykit/files/patch-configure.ac.diff
Labels: type: bugfix, maintainer: open, by: member

#17607 eigen3: Remove old cmake work-around; update -devel; add co-maintainer.
  math/eigen3/Portfile
  math/eigen3/files/patch-ppc.diff
Labels: maintainer, maintainer: open, by: member

#17608 eigen3: Rev-bump to capture patch, even if non-event.
  math/eigen3/Portfile
Labels: maintainer, maintainer: open, by: member

#17186 lua: add lua53 and lua54 subports
  lang/lua/Portfile
  lang/lua/files/patch-Makefile-53.diff
  lang/lua/files/patch-Makefile-54.diff
  lang/lua/files/patch-src-Makefile-53.diff
  lang/lua/files/patch-src-Makefile-54.diff
  lang/lua/files/patch-src-luaconf.h-53.diff
  lang/lua/files/patch-src-luaconf.h-54.diff
Labels: type: enhancement, maintainer: none, by: member

#17611 ddrescue: update to 1.27
  sysutils/ddrescue/Portfile
  sysutils/ddrescue/files/patch-loggers.cc-cstdlib.diff
Labels: type: enhancement, type: update, maintainer: requires approval

#17610 redis: update to 7.0.8
  databases/redis/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#17581 Sophus: long due update; add tests variant
  math/Sophus/Portfile
Labels: type: enhancement, maintainer: open

#17429 new submission: gng (replaces gdub)
  devel/gdub/Portfile
  java/gng/Portfile
Labels: type: submission, maintainer, maintainer: open

#17568 ldns: update to version 1.8.3.
  net/ldns/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer: none

#17565 psblas3: new port in math
  math/psblas3/Portfile
  math/psblas3/files/patch-install-dirs.diff
Labels: type: submission

#17617 google-cloud-sdk: update to 417.0.0
  devel/google-cloud-sdk/Portfile
Labels: type: update, maintainer, maintainer: open

#17618 s-nail: update to 14.9.24
  mail/s-nail/Portfile
  mail/s-nail/files/patch-apple-awk-compatibility.diff
Labels: type: update, maintainer: none

#17443 py-nbconvert: update to 7.2.9
  python/py-nbconvert/Portfile
  python/py-nbconvert/files/patch-hatch_build-disable-download.diff
Labels: type: bugfix, type: enhancement, type: update, maintainer: open

#16817 lua-luasec: fix the broken port, update to 1.2.0, use openssl PG
  devel/lua-luasec/Portfile
  devel/lua-luasec/files/patch-Makefile.diff
  devel/lua-luasec/files/patch-luasocket.diff
  devel/lua-luasec/files/patch-makefiles.diff
  devel/lua-luasec/files/patch-src-Makefile.diff
Labels: type: bugfix, type: enhancement, maintainer: none

#16889 lua-luasocket: update to 3.1.0, fix Rosetta and universal build
  devel/lua-luasocket/Portfile
  devel/lua-luasocket/files/patch-Makefiles.diff
  devel/lua-luasocket/files/patch-makefile.diff
  devel/lua-luasocket/files/patch-src-udp.c.diff
  devel/lua-luasocket/files/patch-src-usocket.c.diff
Labels: type: enhancement, type: update, maintainer: none

#17630 onetbb: update to 2021.8.0
  devel/onetbb/Portfile
Labels: type: update, maintainer, maintainer: open

#17629 onedpl: update to 2021.7.1
  devel/onedpl/Portfile
Labels: type: update, maintainer, maintainer: open

#17628 fortune-mod: update to 3.14.1
  games/fortune-mod/Portfile
Labels: type: update, maintainer, maintainer: open

#17627 libstdcxx-docs: update to 12.2.0
  lang/libstdcxx-docs/Portfile
Labels: type: update, maintainer, maintainer: open

#17622 kazmath: new port in devel
  devel/kazmath/Portfile
Labels: type: submission

#17624 openssh: update to version 9.2p1.
  net/openssh/Portfile
Labels: type: bugfix, type: enhancement, type: update, type: security fix, maintainer: none

#17625 libressl: update to version 3.6.2.
  security/libressl/Portfile
Labels: type: update, maintainer, type: security fix, maintainer: open

#17633 safeclib: fix livecheck
  devel/safeclib/Portfile
Labels: type: bugfix, maintainer, maintainer: open

#17586 iverilog: add missing dependency on bison
  science/iverilog/Portfile
Labels: type: bugfix, maintainer: open

#17631 vtm: update to 0.9.8t
  sysutils/vtm/Portfile
Labels: type: update, maintainer: none

#17619 tilt: update to 0.31.1
  devel/tilt/Portfile
Labels: type: update, maintainer: none

#17636 odin: update to 0.2023.02
  lang/odin/Portfile
Labels: type: update, maintainer, maintainer: open

#17639 fheroes2: update to 1.0.1
  games/fheroes2/Portfile
Labels: type: update, maintainer, maintainer: open

#17637 barman: update to 3.4.0
  databases/barman/Portfile
Labels: type: update, maintainer, maintainer: open

#17644 micronaut: update to 3.8.4
  java/micronaut/Portfile
Labels: type: update, maintainer, maintainer: open

#17640 R-fs: update to 1.6.1, fix build on darwin 11–14
  R/R-fs/Portfile
  R/R-fs/files/0001-fs-fix-libuv-for-10.7.patch
  R/R-fs/files/0002-core.c-patch-close_nocancel.patch
  R/R-fs/files/0003-libuv-link-to-legacysupport.patch
Labels: type: bugfix, type: update, maintainer, maintainer: open

#17645 add: update to 20230205
  math/add/Portfile
Labels: type: update, maintainer: none

#17646 vttest: update to 20230201
  devel/vttest/Portfile
Labels: type: update, maintainer: none

#17635 Gildas: update to 202302a
  science/gildas/Portfile
Labels: type: enhancement, type: update, maintainer

#17650 opencv3-devel: fix worksrcdir
  graphics/opencv3-devel/Portfile
Labels: type: bugfix, maintainer: requires approval, by: member

#17621 graphene: allow SSE2 with i386 builds
  graphics/graphene/Portfile
  graphics/graphene/files/patch-graphene-allow-sse2-on-32bit.diff
Labels: type: bugfix, type: enhancement, maintainer: open, by: member

#17651 hwloc: enable tests
  devel/hwloc/Portfile
Labels: type: enhancement, maintainer: open

#17653 caddy: update to 2.6.3
  www/caddy/Portfile
Labels: type: update, maintainer, maintainer: open

#17418 totp-cli: Update to version 1.2.5
  security/totp-cli/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer: open

#17656 Bear: Update to 3.0.21
  devel/Bear/Portfile
  devel/Bear/files/patch-source-intercept-CMakeLists-txt.patch
Labels: type: update, maintainer, maintainer: open, by: member

#17657 google-cloud-sdk: update to 417.0.1
  devel/google-cloud-sdk/Portfile
Labels: type: update, maintainer, maintainer: open

#17574 elixir: update to 1.14.3
  lang/elixir/Portfile
Labels: type: update, maintainer: open

#17659 dprint: upgrade to 0.34.4
  devel/dprint/Portfile
Labels: maintainer: open

#17393 hiop: new port in math
  math/hiop/Portfile
Labels: type: submission

#17302 dspl: new port in science
  science/dspl/Portfile
  science/dspl/files/0001-Fixes-for-Macports.patch
Labels: type: submission

#17666 groovy: update to 4.0.9
  lang/groovy/Portfile
Labels: type: update, maintainer, maintainer: open

#17665 nixpacks: update to version 1.3.1
  devel/nixpacks/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#17641 gwyddion: update to 2.62
  science/gwyddion/Portfile
  science/gwyddion/files/dynamic_lookup-11.patch
  science/gwyddion/files/patch-gtk-osx-application-gtk2.diff
  science/gwyddion/files/patch-macintegration_h.diff
Labels: type: update, maintainer

#17672 cyrus-sasl-xoauth2: new: A SASL XOAUTH2 plugin
  security/cyrus-sasl-xoauth2/Portfile
  security/cyrus-sasl-xoauth2/files/patch-autogen.sh-use-glibtoolize.diff
Labels: type: submission, by: member

#17614 py-zipfile-deflate64: add py311 subport
  python/py-zipfile-deflate64/Portfile
Labels: type: enhancement, maintainer: open

#17560 py-requests-unixsocket: Add py310 py311 subport
  python/py-requests-unixsocket/Portfile
Labels: maintainer: none

#17522 leiningen: update to 2.10.0
  devel/leiningen/Portfile
Labels: type: update, maintainer: open

#17649 homebank: update to 5.6.2
  x11/homebank/Portfile
Labels: type: update, maintainer: open

#17681 k9s: update to 0.27.3
  sysutils/k9s/Portfile
Labels: type: update, maintainer, maintainer: open

#17683 dtc: update to 1.7.0
  cross/dtc/Portfile
Labels: type: update, maintainer: open, by: member

#17689 swi-prolog-devel: Updated to version 9.1.5
  lang/swi-prolog-devel/Portfile
Labels: type: update, maintainer, maintainer: open

#17670 audiowmark: fix livecheck
  audio/audiowmark/Portfile
Labels: maintainer, maintainer: open

#17654 auto-multiple-choice: update to version 1.6.0
  x11/auto-multiple-choice/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer: none

#17690 avahi: fix daemon start failure
  net/avahi/Portfile
  net/avahi/files/patch-configure-var-run.diff
  net/avahi/files/patch-initscript-darwin-org.freedesktop.avahi-daemon.plist.in.diff
Labels: type: bugfix, maintainer: open

#17662 OpenBLAS: fix broken links to header files
  math/OpenBLAS/Portfile
Labels: type: bugfix, maintainer: open, by: member

#17590 mold: blacklist clang < 1300
  devel/mold/Portfile
Labels: maintainer: open

#17693 FAudio: update to 23.02
  audio/FAudio/Portfile
Labels: type: update, maintainer: none

#17667 madness: new port in science
  science/madness/Portfile
  science/madness/files/0001-CMakeLists-support-ppc.patch
  science/madness/files/0002-Do-not-build-chem-it-is-broken.patch
  science/madness/files/0003-Do-not-build-apps-they-depend-on-chem.patch
Labels: type: submission

#17678 OpenBLAS: fix regression on ppc/i386 Rosetta
  math/OpenBLAS/Portfile
Labels: type: bugfix, maintainer: open, by: member, wip

#17680 mariadb: fix build for Ventura and arm64
  databases/mariadb/Portfile
  databases/mariadb/files/patch-mariadb-Ventura-and-arm64.diff
Labels: type: bugfix, maintainer: open, by: member

#17671 postgresql14: version bump to 14.7
  databases/postgresql14-doc/Portfile
  databases/postgresql14-server/Portfile
  databases/postgresql14/Portfile
Labels: type: enhancement, maintainer: requires approval, by: member

#17698 taskopen: New port
  office/taskopen/Portfile
  office/taskopen/files/patch-fix-Makefile.diff
Labels: type: submission, by: member

#17702 mpich: pin to 4.0.3 for os.major <= 16
  science/mpi-doc/Portfile
  science/mpich/Portfile
Labels: maintainer: requires approval, by: member

#17669 libzita-resampler: fix livecheck
  audio/libzita-resampler/Portfile
Labels: maintainer, maintainer: open

#17707 Bear: Update to 3.1.0
  devel/Bear/Portfile
  devel/Bear/files/patch-spdlog-header-only.diff
Labels: type: update, maintainer, maintainer: open, by: member

#17708 tig: Update to 2.5.8
  devel/tig/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#17709 borgmatic: Update to 1.7.6, use python 3.11
  sysutils/borgmatic/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#17711 Remove maintainer
  lang/zig/Portfile
Labels: maintainer, maintainer: open

#17385 ruby27: Fix build on 10.4, 10.5
  lang/ruby27/Portfile
  lang/ruby27/files/patch-generated.diff
  lang/ruby27/files/patch-random.c.diff
  lang/ruby27/files/patch-sources.diff
Labels: type: bugfix, maintainer: open

#17595 ffmpeg-upstream: prevent autodetection of xlib
  multimedia/ffmpeg-upstream/Portfile
Labels: type: bugfix, maintainer: open, by: member

#17713 jenv: update to 0.5.6
  java/jenv/Portfile
Labels: type: update, maintainer, maintainer: open

#17714 google-cloud-sdk: update to 418.0.0
  devel/google-cloud-sdk/Portfile
Labels: type: update, maintainer, maintainer: open

#17703 apr: update to version 1.7.2
  devel/apr/Portfile
  devel/apr/files/apr-1.7.0-CVE-2021-35940.patch
  devel/apr/files/dynamic_lookup-11.patch
  devel/apr/files/patch-configure.diff
  devel/apr/files/patch-configure_ipv6.diff
Labels: type: update, type: security fix, maintainer: requires approval, by: member

#17705 apr-util: update to version 1.6.3
  devel/apr-util/Portfile
Labels: type: update, type: security fix, maintainer: requires approval, by: member

#17694 llvm-3.3, llvm-3.4: fix ppc build on Intel machines
  lang/llvm-3.3/Portfile
  lang/llvm-3.3/files/patch-macports-flags.diff
  lang/llvm-3.4/Portfile
  lang/llvm-3.4/files/patch-macports-flags.diff
Labels: type: bugfix, maintainer: requires approval, by: member

#17632 sundials6: update to 6.5.0
  math/sundials6/Portfile
Labels: type: update, maintainer: open

#17196 AlphaSparse: new port in math
  math/AlphaSparse/Portfile
  math/AlphaSparse/files/0001-Support-PPC-in-Makefile.patch
  math/AlphaSparse/files/0002-Makefile-cleanup.patch
  math/AlphaSparse/files/0003-Fix-for-missing-COMPAR_FN_T.patch
  math/AlphaSparse/files/0004-Use-stdlib.h-instead-of-malloc.h.patch
  math/AlphaSparse/files/0005-Remove-some-unneeded-spaces.patch
  math/AlphaSparse/files/0006-Makefile-for-x86-test-fix-lib-name-to-libalpha_spbla.patch
  math/AlphaSparse/files/0007-src-Makefile-there-is-no-tuning-dir.patch
  math/AlphaSparse/files/0008-Makefile-fix-dylib-target-for-macOS.patch
  math/AlphaSparse/files/0009-Fixes-for-Macports.patch
  math/AlphaSparse/files/0010-Makefile.tail-split-lib-target-to-fix-ar-error.patch
  math/AlphaSparse/files/0011-Hack-for-Rosetta.patch
Labels: type: submission

#17528 libdivsufsort: new port in devel
  devel/libdivsufsort/Portfile
Labels: type: submission

#17722 datree: updated to version 1.8.24
  devel/datree/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#17552 skhd: remove xcode requirement as xcode cli should be sufficient
  sysutils/skhd/Portfile
Labels: type: enhancement, maintainer: open

#17545 yabai: remove xcode requirement as xcode cli should be sufficient
  sysutils/yabai/Portfile
  sysutils/yabai/files/patch-workspace.m.diff
Labels: type: enhancement, maintainer: open

#17725 vtm: update to 0.9.8u
  sysutils/vtm/Portfile
Labels: type: update, maintainer: none

#17727 cotila: new port in math
  math/cotila/Portfile
Labels: type: submission

#17730 caddy: update to 2.6.4
  www/caddy/Portfile
Labels: type: update, maintainer, maintainer: open

#17685 ghidra: update to 10.2.3
  devel/ghidra/Portfile
Labels: type: update, maintainer: open

#17679 clojure: update to 1.11.1.1224
  lang/clojure/Portfile
Labels: type: update, maintainer, maintainer: open

#17677 z3: update to 4.12.1; add py311
  math/z3/Portfile
Labels: type: enhancement, type: update, maintainer: open

#17674 psi-otr: remove because of gone upstream
  net/psi-otr/Portfile
  net/psi-otr/files/patch-psi-otr.pro.diff
Labels: maintainer

#17569 dnscrypt-proxy: update to version 2.1.3
  net/dnscrypt-proxy/Portfile
Labels: type: update, maintainer: none

#17527 seqan3: fix ppc assembler for macOS
  science/seqan3/Portfile
  science/seqan3/files/patch-spin_delay.hpp-fix-for-Darwin-PPC.diff
Labels: type: bugfix, maintainer: open

#17516 osm2pgsql: update to 1.8.1
  gis/osm2pgsql/Portfile
Labels: type: enhancement, type: update, maintainer: open

#17729 apr: use the right compiler
  devel/apr/Portfile
Labels: type: bugfix, maintainer: requires approval, by: member

#17733 apachetop: update to 0.23.2
  sysutils/apachetop/Portfile
Labels: type: update, maintainer

#17648 luit: update to 2.0.20230201
  x11/luit/Portfile
Labels: type: update, maintainer: open

#17647 reflex: update to 2.5.4-20230206
  devel/reflex/Portfile
Labels: type: update, maintainer: open

#17748 onedpl: update to 2022.0.0
  devel/onedpl/Portfile
Labels: type: update, maintainer, maintainer: open

#17744 vtm: update to 0.9.8v
  sysutils/vtm/Portfile
Labels: type: update, maintainer: none

#17745 uxn: update to 20230217
  emulators/uxn/Portfile
Labels: type: update, maintainer: none

#17743 libdsk: submission
  devel/libdsk/Portfile
  devel/libdsk/files/dynamic_lookup-11.diff
Labels: type: submission

#17746 libzita-resampler: update to 1.10.1
  audio/libzita-resampler/Portfile
  audio/libzita-resampler/files/use-cmake.diff
Labels: type: update, maintainer, maintainer: open

#17676 lighttpd: Update to 1.4.69
  www/lighttpd/Portfile
Labels: type: bugfix, type: update, maintainer: open

#17732 gitui: Update to version 0.22.1
  devel/gitui/Portfile
Labels: type: update, maintainer: open

#17750 nethack: update to 3.6.7
  games/nethack/Portfile
  games/nethack/files/patch-sys__share__ioctl.diff
Labels: type: update, maintainer, maintainer: open

#17740 pika: fix build on < 10.15
  devel/pika/Portfile
Labels: type: bugfix, maintainer, maintainer: open
