Repository macports/macports-ports, pull requests merged in 2024-12, with the labels that each got.

#26835 llama.cpp: fix build on < 10.12
  sysutils/llama.cpp/Portfile
Labels: type: bugfix, maintainer: open

#26833 micropython: blacklist clang < 700
  devel/micropython/Portfile
Labels: maintainer: open

#26843 ruff: Update to 0.8.1
  devel/ruff/Portfile
Labels: type: update, maintainer, maintainer: open

#26836 zfp: update to 2024.11.26
  science/zfp/Portfile
Labels: type: update, maintainer, maintainer: open

#26847 pspg: update to 5.8.7, fix for old systems
  databases/pspg/Portfile
Labels: type: bugfix, type: update, maintainer: none

#26844 libsdl2-powerpc: minor fix, revbump
  devel/libsdl2-powerpc/Portfile
  devel/libsdl2-powerpc/files/0002-fix-x11.diff
Labels: type: bugfix, maintainer

#26839 elmerfem: update to 2024.11.29
  science/elmerfem/Portfile
Labels: type: update, maintainer, maintainer: open

#26832 caps-log: update to 1.2.1
  sysutils/caps-log/Portfile
Labels: type: update, maintainer, maintainer: open

#26804 jack: fallback to jack1 with libstdc++
  audio/jack/Portfile
Labels: type: bugfix, maintainer: none

#26803 mp3cue: revbump for libid3tag update
  audio/mp3cue/Portfile
Labels: type: bugfix, maintainer: none

#26799 cmus: revbump for libmad update
  audio/cmus/Portfile
Labels: type: bugfix, maintainer: open

#26798 qmmp: update to 1.6.9 for qt5; revbump for qt4 for libmad
  audio/qmmp/Portfile
Labels: type: bugfix, type: update, maintainer, maintainer: open

#26828 mp3cat: Update to 0.5
  audio/mp3cat/Portfile
  audio/mp3cat/files/implicit.patch
  audio/mp3cat/files/patch-Makefile.diff
Labels: type: update, maintainer: none

#26846 xeus-sqlite: fix dependencies in the portfile
  databases/xeus-sqlite/Portfile
Labels: type: bugfix, maintainer: open

#26850 initool: update to 1.0.0
  sysutils/initool/Portfile
Labels: type: update, maintainer, maintainer: open

#26809 sgrep2: Fix build on Apple Silicon
  textproc/sgrep2/Portfile
Labels: type: enhancement, maintainer: none

#26807 asymptote: update to 2.95, drop patches
  graphics/asymptote/Portfile
  graphics/asymptote/files/2696886e8fbd49af2ca113fdb29b46169366f58b.patch
  graphics/asymptote/files/cbbcfd2335a02654acd333f5ff89302586960720.patch
Labels: type: update, maintainer: open

#26806 gnupg2: update to 2.4.7, drop patch
  mail/gnupg2/Portfile
  mail/gnupg2/files/patch-app.c.diff
Labels: type: update, maintainer: open

#26853 bun: update to 1.1.38
  devel/bun/Portfile
Labels: type: update, maintainer, maintainer: open

#26814 libmp3splt: revbump for libmad update
  audio/libmp3splt/Portfile
Labels: type: bugfix, maintainer: open

#26762 hindent: Submission
  textproc/hindent/Portfile
Labels: type: submission

#26858 legacy-support-devel: Update to latest master.
  devel/legacy-support/Portfile
Labels: type: update, maintainer, maintainer: open

#26547 audacious*: update to 4.4.2, fix big-endian back
  audio/audacious-core/Portfile
  audio/audacious-core/files/patch-big-endian.diff
  audio/audacious-plugins/Portfile
  audio/audacious-plugins/files/patch-big-endian.diff
  audio/audacious/Portfile
Labels: type: bugfix, type: update, maintainer: requires approval

#26856 rebels-in-the-sky: Update to 1.0.25
  games/rebels-in-the-sky/Portfile
Labels: type: update, maintainer, maintainer: open

#26863 swi-prolog-devel: Updated to version 9.3.16
  lang/swi-prolog-devel/Portfile
Labels: type: update, maintainer, maintainer: open

#26862 oh-my-posh: update to version 24.11.4
  sysutils/oh-my-posh/Portfile
Labels: type: update, maintainer, maintainer: open

#26859 libheif: use fallback for 10.6
  multimedia/libheif/Portfile
Labels: maintainer: open

#26845 libsql: update to 0.5.0
  databases/libsql/Portfile
  databases/libsql/files/0001-sqliteInt.h-fix-pointer-size-for-ppc64.patch
Labels: type: update, maintainer: open

#25859 openmpi: add clang18, clang19, and gcc14 sub-ports
  science/openmpi/Portfile
  science/openmpi/files/portselect/openmpi-clang18
  science/openmpi/files/portselect/openmpi-clang18-fortran
  science/openmpi/files/portselect/openmpi-clang19
  science/openmpi/files/portselect/openmpi-clang19-fortran
  science/openmpi/files/portselect/openmpi-gcc14-fortran
Labels: type: enhancement, maintainer: requires approval, maintainer: timeout

#26871 cargo-c: update to 0.10.7
  devel/cargo-c/Portfile
Labels: type: update, maintainer: open, by: member

#26868 gallery-dl: update to 1.28
  net/gallery-dl/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer, maintainer: open

#26867 FAudio: update to 24.12, drop maintainership
  audio/FAudio/Portfile
Labels: type: update, maintainer, maintainer: open

#26873 algol68g: update to 3.5.10, drop maintainership
  lang/algol68g/Portfile
Labels: type: update, maintainer, maintainer: open

#26866 openssl3: Fix building on 10.4 Intel
  devel/openssl3/Portfile
Labels: type: bugfix, maintainer: open

#26879 ddev: update to 1.24.0
  devel/ddev/Portfile
Labels: type: update, maintainer, maintainer: open

#26880 lima: update to 1.0.2
  sysutils/lima/Portfile
Labels: type: bugfix, type: update, maintainer: open

#26875 ensmallen: update to 2.22.0, remove myself from maintainers
  math/ensmallen/Portfile
Labels: type: update, maintainer, maintainer: open

#26870 tk: do not switch to quartz on 32-bit where it fails
  x11/tk/Portfile
Labels: type: bugfix, maintainer: open

#26031 initial nodejs14->22 changes
  devel/nodejs14/Portfile
  devel/nodejs15/Portfile
  devel/nodejs16/Portfile
  devel/nodejs17/Portfile
  devel/nodejs18/Portfile
  devel/nodejs19/Portfile
  devel/nodejs20/Portfile
  devel/nodejs21/Portfile
  devel/nodejs21/files/patch-add-pthread-qos-guard-for-older-macs.patch
  devel/nodejs22/Portfile
  devel/nodejs22/files/patch-add-pthread-qos-guard-for-older-macs.patch
  devel/nodejs22/files/patch-common.gypi.diff
Labels: maintainer: open

#26857 gcc7-bootstrap: fix build on Intel Tiger
  lang/gcc7-bootstrap/Portfile
  lang/gcc7-bootstrap/files/patch-gcc7-tiger-intel.diff
Labels: type: bugfix, maintainer: none

#26877 tellico: avoid old Xcode gcc, it fails to build this
  kde/tellico/Portfile
Labels: type: bugfix, maintainer: none

#26890 qsv: properly set Python 3.12 as build dep
  textproc/qsv/Portfile
Labels: maintainer, maintainer: open, by: member

#26894 yggdrasil-go: update to 0.5.10
  net/yggdrasil-go/Portfile
Labels: type: update, maintainer: open

#26897 ddev: fix parsing on unsupported architectures
  devel/ddev/Portfile
Labels: maintainer, maintainer: open

#26892 uv: Update to 0.5.6
  devel/uv/Portfile
Labels: type: update, maintainer, maintainer: open

#26903 Gildas: update to 202412a
  science/gildas/Portfile
  science/gildas/files/patch-admin-Makefile.build.diff
  science/gildas/files/patch-admin-Makefile.python.diff
  science/gildas/files/patch-admin-python-config-ldflags.py.diff
Labels: type: enhancement, type: update, maintainer

#26901 py-awscli2: update to 2.22.12
  python/py-awscli2/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#26896 rsgain: use legacysupport.use_mp_libcxx on Mojave and older
  audio/rsgain/Portfile
Labels: maintainer: open

#26891 imager: update to v4.4-01 (dec24)
  science/imager/Portfile
Labels: type: update, maintainer

#26911 pv: 1.9.7
  sysutils/pv/Portfile
Labels: maintainer, maintainer: open, by: member

#26908 hurl: fix stealth update (6.0.0)
  www/hurl/Portfile
Labels: maintainer, maintainer: open, by: member

#26912 josm: update to 19265
  gis/JOSM/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#26889 koio: new port in devel
  devel/koio/Portfile
  devel/koio/files/patch-meson.build.diff
Labels: type: submission

#26854 pnpm: update to 9.14.4
  devel/pnpm/Portfile
Labels: type: update, maintainer: open

#26842 tippecanoe: update to 2.71.0, set needed C++17, fix 32-bit
  gis/tippecanoe/Portfile
  gis/tippecanoe/files/0001-mbtiles.cpp-isinf-to-std-isinf.patch
Labels: type: bugfix, type: update, maintainer: open

#26841 draco: fix build with gcc
  archivers/draco/Portfile
  archivers/draco/files/patch-gltf_utils.h.diff
Labels: type: bugfix, maintainer: open

#26915 mise: Update to 2024.12.0
  sysutils/mise/Portfile
Labels: type: update, maintainer, maintainer: open

#26917 pkcs11-provider: Update to 0.6
  security/pkcs11-provider/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#26918 Bear: Update to 3.1.5
  devel/Bear/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#26919 latexmk: Update to 4.85
  tex/latexmk/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#26656 gcc14: Add ppc FPU patch
  lang/gcc14/Portfile
  lang/gcc14/files/darwin-ppc-fpu.patch
Labels: type: bugfix, maintainer: none

#26922 sequoia-sq: Update to 0.40.0
  security/sequoia-sq/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#26906 py-wxpython-4.0: update to 4.2.2
  python/py-wxpython-4.0/Portfile
  python/py-wxpython-4.0/files/buildtools_config_py.patch
  python/py-wxpython-4.0/files/cython3.patch
Labels: type: update, maintainer: none

#26914 epoll-shim: bump legacysupport to 15 for clock_gettime
  devel/epoll-shim/Portfile
Labels: maintainer: none

#26855 libproxy: update to 0.5.9; add new option variants
  net/libproxy/Portfile
  net/libproxy/files/patch-bindings-perl-src-CMakeLists.txt.diff
  net/libproxy/files/patch-libproxy-cmake.diff
  net/libproxy/files/patch-libproxy-test-CMakeLists.txt.diff
  net/libproxy/files/patch-tools-man.diff
Labels: type: enhancement, type: update, maintainer: open

#26925 py-pdfminer: 20240706
  python/py-pdfminer/Portfile
Labels: maintainer, maintainer: open, by: member

#26927 py-progressbar: add support for Python 3.13
  python/py-progressbar/Portfile
Labels: maintainer: none, by: member

#26827 libressl: re-fix build on macOS < 10.14
  security/libressl/Portfile
Labels: maintainer: open

#26874 plfit: fix running tests, fix build with gcc
  math/plfit/Portfile
  math/plfit/files/patch-fix-linking-gcc.diff
Labels: type: bugfix, maintainer: open

#26813 libcddb: fix typo in two headers
  devel/libcddb/Portfile
  devel/libcddb/files/patch-fix-log-headers.diff
Labels: type: bugfix, maintainer: none

#26726 postgres95: Bugfix, Make PostgreSQL work with newer libxml2
  databases/postgresql95/Portfile
  databases/postgresql95/files/patch-xml_c.diff
Labels: maintainer: requires approval, maintainer: timeout

#26928 py-bitmath: add support for Python 3.13
  python/py-bitmath/Portfile
Labels: maintainer: none, by: member

#26930 py-mac-alias: add Python 3.13 support
  python/py-mac-alias/Portfile
Labels: maintainer: none, by: member

#26929 py-makelive: add Python 3.13 support
  python/py-makelive/Portfile
Labels: maintainer, maintainer: open, by: member

#26932 py-bitstring: update to 4.2.3, add subport for Python 3.13
  python/py-bitstring/Portfile
Labels: type: update, maintainer: none, by: member

#26931 py-applescript: add subport for Python 3.13
  python/py-applescript/Portfile
Labels: maintainer: none, by: member

#26936 mdds: remove obsolete port
  devel/mdds/Portfile
Labels: maintainer: none

#26940 ansifilter: update to 2.21
  textproc/ansifilter/Portfile
Labels: type: update, maintainer: open, by: member

#26939 py-osxmetadata: update to 1.4.0
  python/py-osxmetadata/Portfile
Labels: type: update, maintainer: open, by: member

#26938 nfdump: update to 1.7.5, fix build
  net/nfdump/Portfile
Labels: type: bugfix, type: update, maintainer: none

#26935 epoll-shim: blacklist clang < 800
  devel/epoll-shim/Portfile
Labels: maintainer: none

#26898 python39+: fix `ttyname_r` build error on Tiger gcc14
  lang/python310/Portfile
  lang/python311/Portfile
  lang/python312/Portfile
  lang/python313/Portfile
  lang/python314-devel/Portfile
  lang/python39/Portfile
Labels: type: bugfix, maintainer: requires approval

#26944 py-bpylist2: add Python 3.13 subport
  python/py-bpylist2/Portfile
Labels: maintainer: none, by: member

#26945 py-cgmetadata: update to 0.2.0, add Python 3.13 subport
  python/py-cgmetadata/Portfile
Labels: type: update, maintainer: none, by: member

#26946 py-blessed: add Python 3.13 subport
  python/py-blessed/Portfile
Labels: maintainer: none, by: member

#26947 py-uc-micro-py: add Python 3.13 subport
  python/py-uc-micro-py/Portfile
Labels: maintainer: none, by: member

#26958 py-arpeggio: add Python 3.13 subport
  python/py-arpeggio/Portfile
Labels: maintainer: none, by: member

#26948 py-mdit-py-plugins: update to 0.4.2, add Python 3.13 subport
  python/py-mdit-py-plugins/Portfile
Labels: type: update, maintainer: open, by: member

#26949 py-mdurl: add Python 3.13 subport
  python/py-mdurl/Portfile
Labels: maintainer: none, by: member

#26950 py-pathvalidate: update to 3.2.1, add Python 3.13 subport
  python/py-pathvalidate/Portfile
Labels: type: update, maintainer: none, by: member

#26933 py-feedparser: correct python 27; use pypi instead of github
  python/py-feedparser/Portfile
Labels: maintainer, maintainer: open, by: member

#26954 py-wurlitzer: add Python 3.13 subport
  python/py-wurlitzer/Portfile
Labels: maintainer: open, by: member

#26952 py-ptpython: update to 3.0.29, add Python 3.13 subport
  python/py-ptpython/Portfile
  python/py-ptpython/files/py313-ptpython
Labels: type: update, maintainer: none, by: member

#26934 rsgain: fix the build after legacysupport added
  audio/rsgain/Portfile
  audio/rsgain/files/0001-rsgain.cpp-use-C-cmath.patch
Labels: type: bugfix, maintainer: open

#26955 py-xdg-base-dirs: update to 6.0.2, add Python 3.13 subport
  python/py-xdg-base-dirs/Portfile
Labels: type: update, maintainer: open, by: member

#26956 py-pytimeparse2: add Python 3.13 subport
  python/py-pytimeparse2/Portfile
Labels: maintainer: none, by: member

#26957 py-shortuuid: add Python 3.13 subport
  python/py-shortuuid/Portfile
Labels: maintainer: none, by: member

#26970 hmmer: fix build on powerpc
  science/hmmer/Portfile
Labels: type: bugfix, maintainer: open

#26943 uv: Update to 0.5.7
  devel/uv/Portfile
Labels: type: update, maintainer, maintainer: open

#26965 libsdl2-powerpc: update to 2.30.10
  devel/libsdl2-powerpc/Portfile
Labels: type: update, maintainer

#26926 py-xlsxwriter/py-pptx: Add 3.13 versions
  python/py-XlsxWriter/Portfile
  python/py-pptx/Portfile
Labels: maintainer, maintainer: open, by: member

#26951 py-photoscript: update to 0.4.0, add Python 3.13 subport
  python/py-photoscript/Portfile
Labels: type: update, maintainer: open, by: member

#26959 py-textx: update to 4.1.0, add Python 3.13 subport
  python/py-textx/Portfile
Labels: type: update, maintainer: none, by: member

#26967 aptdec: fix build with Xcode gcc
  science/aptdec/Portfile
Labels: type: bugfix, maintainer: open

#26977 less: update to 668
  textproc/less/Portfile
Labels: type: enhancement, type: update, maintainer: open

#26975 coreutils-uutils: update to 0.0.28
  sysutils/coreutils-uutils/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#26953 py-linkify-it-py: add Python 3.13 subport
  python/py-linkify-it-py/Portfile
Labels: maintainer: none, by: member

#26983 py-markdown-it-py: add Python 3.13 subport
  python/py-markdown-it-py/Portfile
Labels: maintainer: none, by: member

#26976 py-pkginfo: update to 1.12.0
  python/py-pkginfo/Portfile
Labels: type: enhancement, type: update, maintainer: open

#26960 py-strpdatetime: update to 0.4.0, add Python 3.13 subport
  python/py-strpdatetime/Portfile
Labels: type: update, maintainer: open, by: member

#26981 py-utitools: new submission
  python/py-utitools/Portfile
Labels: type: submission, by: member

#26995 py-wxpython-4.0: Fix ScreenCaptureKit Error
  python/py-wxpython-4.0/Portfile
Labels: maintainer: none, by: member

#26993 mise: Update to 2024.12.3
  sysutils/mise/Portfile
Labels: type: update, maintainer, maintainer: open

#26969 rapidjson-devel: update to 20241202, drop maintainership
  devel/rapidjson-devel/Portfile
Labels: type: update, maintainer, maintainer: open

#26968 madness: update to 2024.12.06
  science/madness/Portfile
Labels: type: update, maintainer, maintainer: open

#26963 QMPlay2: update to 24.12.06 for new systems
  multimedia/QMPlay2/Portfile
Labels: type: update, maintainer, maintainer: open

#26904 qbs: Update to 2.5.0
  devel/qbs/Portfile
Labels: type: enhancement, type: update, maintainer: open

#26997 tevent: fix compiler choice
  devel/tevent/Portfile
Labels: type: bugfix, maintainer: none

#26998 gcc10: use correct triples on powerpc*
  lang/gcc10/Portfile
Labels: type: bugfix, maintainer: none

#26978 libvmime: fix for old systems
  mail/libvmime/Portfile
  mail/libvmime/files/patch-AI_NUMERICSERV.diff
Labels: type: bugfix, maintainer: none

#27005 oh-my-posh: update to version 24.12.0
  sysutils/oh-my-posh/Portfile
Labels: type: update, maintainer, maintainer: open

#27006 pv:1.9.15
  sysutils/pv/Portfile
Labels: maintainer, maintainer: open, by: member

#27008 py-htmldocs: latest for 3.10,11,12,13
  lang/py-htmldocs/Portfile
Labels: maintainer, maintainer: open, by: member

#27002 ocaml-utop: update to 2.15.0
  ocaml/ocaml-utop/Portfile
Labels: type: update, maintainer, maintainer: open

#27009 ocrmypdf: update to 16.7.0
  textproc/ocrmypdf/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer, type: security fix, maintainer: open

#27013 py-lesscpy: Update to 0.15.1
  python/py-lesscpy/Portfile
Labels: type: update, maintainer: none

#27014 flickcurl: fix stdlib usage
  devel/flickcurl/Portfile
  devel/flickcurl/files/001-use-stdlib-h.patch
Labels: type: bugfix, maintainer: none

#27012 lua: add legacy-support for Tiger
  lang/lua/Portfile
Labels: type: bugfix, maintainer: open

#27018 mise: Update to 2024.12.4
  sysutils/mise/Portfile
Labels: type: update, maintainer, maintainer: open

#27021 py-rich: add Python 3.13 subport
  python/py-rich/Portfile
Labels: maintainer: open, by: member

#27022 py-rich-theme-manager: add Python 3.13 subport, remove Python 3.8 (EOL) subport
  python/py-rich-theme-manager/Portfile
Labels: maintainer: none, by: member

#27011 google-benchmark: new package
  devel/google-benchmark/Portfile
Labels: type: enhancement, type: submission

#26910 lrzsz: update to support clang 16
  comms/lrzsz/Portfile
Labels: type: update, maintainer: none

#27025 dcm2niix: Fix openjpeg usage; add batch tool.
  science/dcm2niix/Portfile
Labels: maintainer, maintainer: open, by: member

#27026 inkscape: Fix dependency on libsoup 2.4
  graphics/inkscape/Portfile
Labels: type: bugfix, maintainer: open, by: member

#26937 libressl-devel: re-fix build on macOS < 10.14
  security/libressl-devel/Portfile
Labels: maintainer: open

#26979 Update py-jaraco packages
  python/py-jaraco.classes/Portfile
  python/py-jaraco.functools/Portfile
Labels: type: enhancement, type: update, maintainer: open

#26961 py-tenacity: update to 9.0.0, add Python 3.13 subport
  python/py-tenacity/Portfile
Labels: type: update, maintainer: open, by: member

#26973 postgresql17: update to 17.2
  databases/postgresql17-server/Portfile
  databases/postgresql17/Portfile
Labels: type: update, maintainer: open

#26972 opencascade: Fix build, initialization error
  science/opencascade/Portfile
  science/opencascade/files/patch-StdPrs_BRepFont.cxx.diff
Labels: type: bugfix, maintainer: open

#26907 castxml: update to 0.6.10
  lang/castxml/Portfile
Labels: type: update, maintainer: open

#27029 zmap: update to 4.3.1
  net/zmap/Portfile
Labels: type: bugfix, type: update, maintainer, maintainer: open

#27028 snac: update to 2.66
  net/snac/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer, maintainer: open

#26942 Updated to v2.0.2
  science/rtl-sdr/Portfile
  science/rtl-sdr/files/patch-fix-git-describe.diff
Labels: type: update, maintainer: open

#27032 dosbox-x: update to 2024.12.04
  emulators/dosbox-x/Portfile
Labels: type: update, maintainer: none

#27033 liboqs: update to 0.12.0
  devel/liboqs/Portfile
Labels: type: update, maintainer, maintainer: open

#27036 fizz: revbump for liboqs update
  devel/fizz/Portfile
Labels: maintainer, maintainer: open

#27015 scamper: Update to 20241112
  net/scamper/Portfile
Labels: type: update, maintainer: requires approval

#27001 xmms2: another go with fixing opportunistic linking
  audio/xmms2/Portfile
Labels: type: bugfix, maintainer: none

#27039 google-cloud-sdk: update to 503.0.0
  devel/google-cloud-sdk/Portfile
Labels: type: update, maintainer, maintainer: open, by: member
