Repository macports/macports-ports, pull requests merged in 2024-05, with the labels that each got.

#23774 uv: Update to 0.1.39
  devel/uv/Portfile
Labels: type: update, maintainer, maintainer: open

#23773 tlrc: Update to 1.9.2
  net/tlrc/Portfile
Labels: type: update, maintainer, maintainer: open

#23772 ipsw: Update to 3.1.480
  security/ipsw/Portfile
Labels: type: update, maintainer, maintainer: open

#23771 gitu: Update to 0.19.2
  devel/gitu/Portfile
Labels: type: update, maintainer, maintainer: open

#23767 mpdecimal: Use absolute path in install names
  math/mpdecimal/Portfile
  math/mpdecimal/files/no-rpath.patch
Labels: maintainer: open, by: member

#23764 libgig: update to 4.4.1
  audio/libgig/Portfile
Labels: type: update, maintainer: open

#23776 R-clock: fix for < 10.13 with clang
  R/R-clock/Portfile
  R/R-clock/files/Makevars
Labels: type: bugfix, maintainer, maintainer: open

#23777 jreleaser: update to version v1.12.0
  devel/jreleaser/Portfile
Labels: type: enhancement, type: update, maintainer

#23755 dagger: update to 0.11.2
  devel/jreleaser/Portfile
Labels: type: update, maintainer: open

#23780 google-cloud-sdk: update to 474.0.0
  devel/google-cloud-sdk/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#23782 pam-google-authenticator: Update to 1.10
  security/pam-google-authenticator/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#23779 ruby-build: Upgrade to 20240501
  ruby/ruby-build/Portfile
Labels: maintainer, maintainer: open

#23677 abaddon: update miniaudio, fix for older clang-using systems: need filesystem
  net/abaddon/Portfile
  net/abaddon/files/0005-miniaudio.h-fix-for-macOS.patch
Labels: type: bugfix, maintainer, maintainer: open

#23784 nvi: blacklist old Xcode gcc, which does not build this
  editors/nvi/Portfile
Labels: type: bugfix, maintainer: none

#23783 nvi2: new port in editors
  editors/nvi2/Portfile
  editors/nvi2/files/patch-SLIST_REMOVE_AFTER.diff
  editors/nvi2/files/patch-fix-include-path.diff
Labels: type: submission

#23786 py-rubicon-objc: update to 0.4.8
  python/py-rubicon-objc/Portfile
  python/py-rubicon-objc/files/patch-pyproject.diff
Labels: type: update, maintainer: none

#23788 ocaml-bos: fix livecheck
  ocaml/ocaml-bos/Portfile
Labels: type: enhancement, maintainer, maintainer: open

#23791 py-awscli2: update to 2.15.43
  python/py-awscli2/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#23792 mysql8: update to 8.0.37
  databases/mysql8/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#23794 google-cloud-sdk: add istioctl variant
  devel/google-cloud-sdk/Portfile
Labels: type: enhancement, maintainer, maintainer: open, by: member

#23795 jsoncons: update to 0.175.0
  devel/jsoncons/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#23797 httpie-go: new port (version 0.7.0)
  net/httpie-go/Portfile
Labels: type: submission

#23800 ntpsec: Fix livecheck
  sysutils/ntpsec/Portfile
Labels: type: bugfix, maintainer, maintainer: open

#23757 ruby33: update to v3.3.1; fix build on 10.4, 10.5
  lang/ruby33/Portfile
  lang/ruby33/files/patch-sources.diff
Labels: type: bugfix, type: update, maintainer: open

#23747 ruby32: update to v3.2.4; fix build on 10.4, 10.5
  lang/ruby32/Portfile
  lang/ruby32/files/patch-sources.diff
Labels: type: bugfix, type: update, maintainer: open

#23796 hdf5: Disable new float16 support for now.
  science/hdf5/Portfile
Labels: maintainer, maintainer: open, by: member

#23801 clojure: update to 1.11.3.1463
  lang/clojure/Portfile
Labels: type: update, maintainer, maintainer: open

#23813 asciidoctor: update to v2.0.22
  textproc/asciidoctor/Portfile
Labels: type: update, maintainer, maintainer: open

#23810 mz-cmaketools: update to 2024.04.29
  devel/mz-cmaketools/Portfile
Labels: type: update, maintainer, maintainer: open

#23809 ruby-devel: update to 2024.05.03
  lang/ruby-devel/Portfile
Labels: type: update, maintainer, maintainer: open

#23806 josm: update to 19067
  gis/JOSM/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#23803 Gildas: update to 202405b
  science/gildas/Portfile
Labels: type: enhancement, type: update, maintainer

#23804 starpu: update to 1.4.5
  devel/starpu/Portfile
Labels: type: update, maintainer, maintainer: open

#23621 pulseaudio: fix segfault on powerpc
  audio/pulseaudio/Portfile
  audio/pulseaudio/files/patch-avoid-segfault-on-powerpc.diff
Labels: type: bugfix, type: enhancement, maintainer: open

#23808 rb-net-ftp: remove rb33 subport, as it is now included in ruby33
  ruby/rb-net-ftp/Portfile
Labels: type: bugfix, maintainer: none

#23812 fava: update to 1.27.3
  python/fava/Portfile
Labels: type: update, maintainer: open, by: member

#23819 64tass: update to 1.59.3120
  devel/64tass/Portfile
Labels: type: update, maintainer, maintainer: open

#23763 libfdk-aac: update to 2.0.3
  audio/libfdk-aac/Portfile
Labels: type: update, maintainer: open

#23744 openvdb: fix build on PowerPC
  graphics/openvdb/Portfile
  graphics/openvdb/files/patch-libatomic.diff
Labels: type: bugfix, maintainer: open

#23742 glfw: build on < 10.6 and ppc against x11, unbreak the port
  graphics/glfw/Portfile
  graphics/glfw/files/patch-use-x11.diff
Labels: type: bugfix, maintainer: open

#23817 valkey: fix on 10.6, remove brewism
  databases/valkey/Portfile
  databases/valkey/files/patch-fix-older-macOS.diff
  databases/valkey/files/patch-remove-brewism.diff
Labels: type: bugfix, maintainer: open

#23820 micronaut: update to 4.4.2
  java/micronaut/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#23821 stern: update to 1.29.0
  sysutils/stern/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#23824 libsdl2-powerpc: update to 2.30.3
  devel/libsdl2-powerpc/Portfile
Labels: type: update, maintainer

#23827 tree-sitter-c-sharp: now needs -std=c99
  devel/tree-sitter-c-sharp/Portfile
Labels: type: bugfix, maintainer: open

#23825 R-QuickJSR: do not try libatomic linking with clang builds
  R/R-QuickJSR/Portfile
  R/R-QuickJSR/files/patch-no-libatomic.diff
Labels: type: bugfix, maintainer, maintainer: open

#23775 rnnoise: Use release tarball
  audio/rnnoise/Portfile
Labels: maintainer: open, by: member

#23830 symfony-cli: update to 5.8.17
  devel/symfony-cli/Portfile
Labels: type: update, maintainer, maintainer: open

#23805 borgmatic: Update to 1.8.11
  sysutils/borgmatic/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#23831 xmake: new port
  devel/xmake/Portfile
Labels: type: submission, by: member

#23832 tree-sitter-css: also needs C99 after update
  devel/tree-sitter-css/Portfile
Labels: type: bugfix, maintainer: open

#23793 eiffelstudio: Add another maintainer
  lang/eiffelstudio/Portfile
Labels: maintainer: open

#23829 ddrescue: update to 1.28
  sysutils/ddrescue/Portfile
Labels: type: enhancement, type: update, maintainer: requires approval, by: member

#23837 imposm: new port
  gis/imposm/Portfile
Labels: type: enhancement, type: submission

#23840 samba4: fix build on macOS <10.13
  net/samba4/Portfile
Labels: maintainer: none

#23843 pyftdi: update to 0.55.4
  python/py-pyftdi/Portfile
  python/py-pyftdi/files/patch-1_test_module_setup.diff
  python/py-pyftdi/files/patch-2_test_untestable_base.diff
Labels: type: update, maintainer: none

#23848 uxn: update to 20240506
  emulators/uxn/Portfile
Labels: type: update, maintainer: none

#23839 logtalk: update to 3.78.0
  lang/logtalk/Portfile
Labels: type: update, maintainer

#23798 unpaper: update to 7.0, change build system, adopt
  graphics/unpaper/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer: none

#23854 apr-util: Remove mysql5 variant
  devel/apr-util/Portfile
Labels: maintainer: requires approval, by: member

#23859 snac: update to 2.52
  net/snac/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer, maintainer: open

#23858 nicotine-plus: update to 3.3.3
  www/nicotine-plus/Portfile
Labels: type: update, maintainer, maintainer: open

#23860 google-cloud-sdk: update to 475.0.0
  devel/google-cloud-sdk/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#23861 kotlin: update to 1.9.24
  lang/kotlin/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#23862 uv: Update to 0.1.40
  devel/uv/Portfile
Labels: type: update, maintainer, maintainer: open

#23849 emacs-mac-app: Add renameapp variant
  aqua/emacs-mac-app/Portfile
Labels: type: enhancement, maintainer: open

#23853 rb-bigdecimal: update to 3.1.8
  ruby/rb-bigdecimal/Portfile
Labels: type: update, maintainer, maintainer: open

#23852 c3270: update to 4.3ga8
  comms/c3270/Portfile
Labels: type: update, maintainer, maintainer: open

#23828 imake: update to 1.0.10
  x11/imake/Portfile
Labels: type: update, maintainer: open

#23826 viewres: update to 1.0.7
  x11/viewres/Portfile
Labels: type: update, maintainer: open

#23799 py-pypng: Update to 0.20220715.0
  python/py-pypng/Portfile
Labels: type: update, maintainer: open

#23778 openjade: fix compiler choice
  textproc/openjade/Portfile
Labels: type: bugfix, maintainer: open

#23868 oh-my-posh: update to 19.27.0
  sysutils/oh-my-posh/Portfile
Labels: type: update, maintainer: open

#23802 mqttcli: new port (version 0.2.6)
  net/mqttcli/Portfile
Labels: type: submission

#23869 xdispatch2: update to 2.1.4, drop now redundant patches
  devel/xdispatch2/Portfile
  devel/xdispatch2/files/0002-Add-missing-stdexcept-header.patch
  devel/xdispatch2/files/0002-Fix-tests.patch
  devel/xdispatch2/files/0004-Tests-no-qt5.patch
Labels: type: update, maintainer, maintainer: open

#23863 2048.c: new port (1.0.0)
  games/2048.c/Portfile
Labels: type: submission

#23835 audacious-plugins: enable more plugins
  multimedia/audacious-plugins/Portfile
Labels: type: enhancement, maintainer: requires approval, maintainer: timeout, by: member

#23833 rnnoise: blacklist clang < 800
  audio/rnnoise/Portfile
Labels: maintainer: open

#23867 astyle: update to 3.4.14
  devel/astyle/Portfile
  devel/astyle/files/dont-force-stdlib.diff
Labels: type: update, maintainer: none

#23872 clac: new port
  math/clac/Portfile
Labels: type: submission, by: member

#23873 neocmakelsp: new port
  devel/neocmakelsp/Portfile
Labels: type: submission, by: member

#23881 ruff: Update to 0.4.4
  devel/ruff/Portfile
Labels: type: update, maintainer, maintainer: open

#23880 gitu: Update to 0.20.1
  devel/gitu/Portfile
Labels: type: update, maintainer, maintainer: open

#23877 nicotine-plus: update to 3.3.4
  www/nicotine-plus/Portfile
Labels: type: update, maintainer, maintainer: open

#23876 fast_double_parser: update to 0.8.0
  devel/fast_double_parser/Portfile
  devel/fast_double_parser/files/0001-CMakeLists-do-not-use-Linux-linker-flag-on-macOS.patch
Labels: type: update, maintainer, maintainer: open

#23865 py-pyqrcode: Add Python 3.12 subport
  python/py-pyqrcode/Portfile
Labels: type: enhancement, maintainer: open

#23889 py-slack-sdk: add python 3.12
  python/py-slack-sdk/Portfile
Labels: maintainer, maintainer: open

#23883 blis: update to 1.0
  math/blis/Portfile
Labels: type: update, maintainer, maintainer: open

#23864 gtk3: require active variant for glib2
  gnome/gtk3-devel/Portfile
  gnome/gtk3/Portfile
Labels: type: bugfix, maintainer: open, by: member

#23893 uv: Update to 0.1.42
  devel/uv/Portfile
Labels: type: update, maintainer, maintainer: open

#23892 g-ls: Update to 0.27.0
  sysutils/g-ls/Portfile
Labels: type: update, maintainer: open

#23847 got: update to 0.99
  devel/got/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer, maintainer: open

#23785 vis: update to 0.9
  editors/vis/Portfile
  editors/vis/files/patch-Makefile.diff
  editors/vis/files/patch-configure-luaver.diff
Labels: type: update, maintainer: open, by: member

#23898 jujutsu: update to 0.17.1
  devel/jujutsu/Portfile
Labels: type: update, maintainer: open

#23900 lang/ecl: update to 2024 05 10 release
  lang/ecl/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#23899 py-pygmt: Update to 0.12.0
  python/py-pygmt/Portfile
Labels: type: update, maintainer: none

#23856 gensync:update to 2.1.0
  net/gensync/Portfile
Labels: maintainer: open

#23846 qbs: Update to 2.3.1
  devel/qbs/Portfile
Labels: type: enhancement, type: update, maintainer: open

#23787 ctlang: update to 1.5.3, support tests
  graphics/ctlang/Portfile
Labels: type: enhancement, type: update, maintainer: open

#23676 QMPlay2: fix for 10.5
  multimedia/QMPlay2/files/0003-ScreenSaver-fix-IOKit-defines.patch
Labels: type: bugfix, maintainer, maintainer: open

#23645 mod_tile: Update to proj7, variants to use Postgresql15-16
  gis/mod_tile/Portfile
  gis/mod_tile/files/README_MacPorts.md
  gis/mod_tile/files/osm_setup_db.sh
  gis/mod_tile/files/renderd.conf.dist
Labels: type: bugfix, type: enhancement, type: update, maintainer, maintainer: open

#23705 apbs update port to upstream 3.4.1
  science/apbs/Portfile
  science/apbs/files/cmake-maloc.patch
  science/apbs/files/disable_python_cmake_check.patch
  science/apbs/files/open-U-obsolete.patch
  science/apbs/files/patch-CMakeLists.txt.diff
  science/apbs/files/patch-Eigen-include-path.diff
  science/apbs/files/patch-contrib-tabipb-CMakeLists.txt.diff
  science/apbs/files/patch-pbsolvercz.cpp.diff
  science/apbs/files/patch-testfiles.patch
  science/apbs/files/patch-tests-apbs_tester.py.diff
  science/apbs/files/python3.patch
  science/apbs/files/wrong-path-for-interpreter.patch
Labels: maintainer: none

#23902 oh-my-posh: update to version 19.28.0
  sysutils/oh-my-posh/Portfile
Labels: type: bugfix, type: update, maintainer, maintainer: open

#23903 astyle: update to 3.4.15
  devel/astyle/Portfile
Labels: type: update, maintainer: none

#23907 abseil-dependants: revbump after c++ std change
  devel/Bear/Portfile
  devel/apache-arrow/Portfile
  devel/grpc/Portfile
  devel/protobuf3-cpp-upstream/Portfile
  devel/re2/Portfile
  math/s2geometry/Portfile
  net/mtxclient/Portfile
Labels: type: bugfix, maintainer: open

#23897 pdfjam: update to pdfjam 3.11
  textproc/pdfjam/Portfile
Labels: type: update, maintainer: open, by: member

#23914 rust PG: sort crate names in alphabetical order
  _resources/port1.0/group/rust-1.0.tcl
Labels: type: enhancement, by: member

#23896 superfile: new port (v1.1.2)
  sysutils/superfile/Portfile
Labels: type: submission, by: member

#23916 textproc/jj: Add conflicts with jujutsu
  textproc/jj/Portfile
Labels: type: bugfix, maintainer: open

#23919 yq: update to 4.44.1
  textproc/yq/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#23913 olaf-devel: fix for older systems and powerpc
  audio/olaf-devel/Portfile
  audio/olaf-devel/files/patch-altivec.diff
Labels: type: bugfix, maintainer: open

#23910 codec2: avoid old Xcode gcc, it fails to build this
  audio/codec2/Portfile
Labels: type: bugfix, maintainer: open

#23927 py-bcrypt: fix for systems without Rust
  python/py-bcrypt/Portfile
Labels: type: bugfix, maintainer: open

#23906 rxvt-unicode: backport fix for OSC responses with 7-bit ST
  x11/rxvt-unicode/Portfile
  x11/rxvt-unicode/files/patch-fix-osc-response.diff
Labels: maintainer, maintainer: open

#23930 libressl: update to 3.9.2
  security/libressl/Portfile
Labels: type: bugfix, type: update, maintainer, type: security fix, maintainer: open

#23908 dagger: update to 0.11.4
  devel/dagger/Portfile
Labels: type: update, maintainer: open

#23886 d3dmetal: New Port
  devel/d3dmetal/Portfile
Labels: type: submission

#23855 zabbix3: Remove mysql5 variant
  net/zabbix3/Portfile
Labels: maintainer: open, by: member

#23935 d3dmetal: Don’t break everything
  devel/d3dmetal/Portfile
Labels: type: bugfix

#23940 oh-my-posh: update to version 19.29.0
  sysutils/oh-my-posh/Portfile
Labels: type: update, maintainer, maintainer: open

#23941 symfony-cli: update to 5.8.19
  devel/symfony-cli/Portfile
Labels: type: update, maintainer, maintainer: open

#23931 coreutils-uutils: update to 0.0.26
  sysutils/coreutils-uutils/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#23936 tig: Update to 2.5.10
  devel/tig/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#23871 hdf5: Fix leak of internal IDs
  science/hdf5/Portfile
  science/hdf5/files/fix-leak-of-internal-ids.patch
Labels: type: bugfix, maintainer: open, by: member

#23870 py-h5py: Use float16 datatype only if available
  python/py-h5py/Portfile
  python/py-h5py/files/float16.patch
Labels: type: bugfix, maintainer: open, by: member

#23635 kdepim4: Remove link-grammar dependency
  kde/kdepim4-runtime/Portfile
  kde/kdepim4/Portfile
Labels: maintainer: requires approval, maintainer: timeout, by: member

#23945 pgmodeler: update to 1.1.3
  databases/pgmodeler/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#23951 numchk: blacklist old Xcode gcc to fix build on old OS
  finance/numchk/Portfile
Labels: type: bugfix, maintainer: open

#23955 gk: update to v2.0.0
  devel/gk/Portfile
Labels: type: update, maintainer, maintainer: open

#23952 minicom: fix for old systems
  comms/minicom/Portfile
Labels: type: bugfix, maintainer: none

#23957 xscreensaver: fix build on macOS <10.13
  x11/xscreensaver/Portfile
  x11/xscreensaver/files/patch-ignore-qos.diff
Labels: maintainer: none

#23956 swi-prolog-devel: Updated to version 9.3.6
  lang/swi-prolog-devel/Portfile
Labels: type: update, maintainer, maintainer: open

#23954 softether5: update to 5.02.5184
  net/softether5/Portfile
Labels: type: update, maintainer, maintainer: open

#23904 bash-completion: update to 2.14.0
  sysutils/bash-completion/Portfile
Labels: type: update, maintainer: requires approval, maintainer: timeout, by: member

#23905 gimp2-devel: update to 2.10.38
  graphics/gimp2-devel/Portfile
  graphics/gimp2-devel/files/patch-mach-task-info.diff
  graphics/gimp2-devel/files/patch-quartz-32bit.diff
Labels: type: update, maintainer: open, by: member

#23959 google-cloud-sdk: update to 476.0.0
  devel/google-cloud-sdk/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#23960 skaffold: update to 2.12.0
  devel/skaffold/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#23961 oh-my-posh: update to version 19.29.1
  sysutils/oh-my-posh/Portfile
Labels: type: update, maintainer, maintainer: open

#23958 mysql8: update to 8.4.0
  databases/mysql8/Portfile
  databases/mysql8/files/patch-boost-clang16-cpp17-compat.diff
  databases/mysql8/files/patch-cmake-sasl-disable-platform-check.diff
  databases/mysql8/files/patch-cmake-ssl-include.diff
  databases/mysql8/files/patch-mysql8-ffsll-apple.diff
  databases/mysql8/files/patch-router-cmake-set_rpath.diff
  databases/mysql8/files/patch-scripts-cmakelists.diff
  databases/mysql8/files/patch-sql-local-boost.diff
  databases/mysql81/Portfile
  databases/mysql81/files/macports-default.cnf
  databases/mysql81/files/my.cnf
  databases/mysql81/files/mysql81
  databases/mysql81/files/org.macports.mysql-server.plist
  databases/mysql81/files/patch-boost-clang16-cpp17-compat.diff
  databases/mysql81/files/patch-cmake-install_layout.cmake.diff
  databases/mysql81/files/patch-cmake-install_macros-protobuf-path.cmake.diff
  databases/mysql81/files/patch-cmake-sasl-disable-platform-check.diff
  databases/mysql81/files/patch-cmake-ssl-include.diff
  databases/mysql81/files/patch-mysql8-ffsll-apple.diff
  databases/mysql81/files/patch-readline.cmake.diff
  databases/mysql81/files/patch-router-cmake-set_rpath.diff
  databases/mysql81/files/patch-scripts-cmakelists.diff
  databases/mysql81/files/patch-sql-local-boost.diff
  databases/mysql82/Portfile
  databases/mysql82/files/macports-default.cnf
  databases/mysql82/files/my.cnf
  databases/mysql82/files/mysql82
  databases/mysql82/files/org.macports.mysql-server.plist
  databases/mysql82/files/patch-boost-clang16-cpp17-compat.diff
  databases/mysql82/files/patch-cmake-install_layout.cmake.diff
  databases/mysql82/files/patch-cmake-install_macros-protobuf-path.cmake.diff
  databases/mysql82/files/patch-cmake-sasl-disable-platform-check.diff
  databases/mysql82/files/patch-mysql8-ffsll-apple.diff
  databases/mysql82/files/patch-readline.cmake.diff
  databases/mysql82/files/patch-scripts-cmakelists.diff
  databases/mysql82/files/patch-sql-local-boost.diff
Labels: type: update, maintainer, maintainer: open, by: member

#23962 logtalk: update to 3.79.0
  lang/logtalk/Portfile
Labels: type: update, maintainer

#23895 singular: update to 4-4-0 to fix building with new flint
  math/singular/Portfile
Labels: type: bugfix, type: update, maintainer: open

#23885 util-linux: unbreak for 32-bit platforms
  devel/util-linux/Portfile
Labels: type: bugfix, maintainer: open

#23971 ocaml-js_of_ocaml: update to 5.8.1
  ocaml/ocaml-js_of_ocaml/Portfile
Labels: type: update, maintainer, maintainer: open

#23972 tor-devel: update to 0.4.8.11
  security/tor-devel/Portfile
Labels: type: update, maintainer: none

#23973 libretroshare: update to 2024.05.13
  net/libretroshare/Portfile
Labels: type: update, maintainer, maintainer: open

#23975 R-rsparse: handle stealth update
  R/R-rsparse/Portfile
Labels: type: bugfix, maintainer, maintainer: open

#23974 fortran-stdlib: update to 2024.05.13
  lang/fortran-stdlib/Portfile
Labels: type: update, maintainer, maintainer: open

#23978 glances: unbreak for old systems
  sysutils/glances/Portfile
  sysutils/glances/files/patch-make-pydantic-optional.diff
Labels: type: bugfix, maintainer: none

#23982 turbo: update to 2024.05.15
  editors/turbo/Portfile
Labels: type: update, maintainer, maintainer: open

#23984 openmotif: unbreak after recent update
  x11/openmotif/Portfile
Labels: type: bugfix, maintainer: none
