Repository macports/macports-ports, pull requests merged in 2024-09, with the labels that each got.

#25555 libhx: update to 4.24
  devel/libhx/Portfile
  devel/libhx/files/0001-rand.c-fix-headers-for-macOS.patch
  devel/libhx/files/0002-build-resolve-compile-error-on-NetBSD.patch
Labels: type: update, maintainer: none

#25554 gnucobol: update to 3.2
  lang/gnucobol/Portfile
Labels: type: update, maintainer: none

#25553 chicken: update to 5.4.0
  lang/chicken/Portfile
  lang/chicken/files/patch-Makefile.macosx.diff
Labels: type: update, maintainer: none

#25551 cpp-utilities: update to 5.26.0
  devel/cpp-utilities/Portfile
Labels: type: update, maintainer: none

#25558 grpc: non-functional: use path-style deps for pkgconfig and libuv
  devel/grpc/Portfile
Labels: type: enhancement, maintainer: none

#25540 apbs: unbreak build with gcc
  science/apbs/Portfile
Labels: type: bugfix, maintainer: none

#25559 nlohmann-json-schema-validator: new port
  devel/nlohmann-json-schema-validator/Portfile
Labels: type: enhancement, type: submission

#25563 oh-my-posh: update to version 23.9.1
  sysutils/oh-my-posh/Portfile
Labels: type: update, maintainer, maintainer: open

#25569 ipsw: Update to 3.1.538
  security/ipsw/Portfile
Labels: type: update, maintainer, maintainer: open

#25568 uv: Update to 0.4.2
  devel/uv/Portfile
Labels: type: update, maintainer, maintainer: open

#25567 crossgcc: Correct compiler blacklist
  _resources/port1.0/group/crossgcc-1.0.tcl
Labels: type: bugfix

#25526 lazydocker: update to version 0.23.3
  devel/lazydocker/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer: open

#25524 TkPasMan: update to 2.2b
  x11/TkPasMan/Portfile
Labels: type: update, maintainer: requires approval

#25571 tio: update to 3.7
  comms/tio/Portfile
  comms/tio/files/patch-socket.diff
Labels: type: update, maintainer: open

#25572 tree-sitter-java: needs C99 now
  devel/tree-sitter-java/Portfile
Labels: type: bugfix, maintainer: open

#25575 gobject-introspection-devel: Fix giscanner with setuptools 74
  gnome/gobject-introspection-devel/Portfile
  gnome/gobject-introspection-devel/files/msvccompiler.patch
Labels: type: bugfix, maintainer: open

#25574 libsdl2-powerpc: update to 2.30.7
  devel/libsdl2-powerpc/Portfile
Labels: type: update, maintainer

#25573 FAudio: update to 24.09
  audio/FAudio/Portfile
Labels: type: update, maintainer, maintainer: open

#25562 qt64-qtbase: Fix building on 10.14 and 10.15 and a minor patch
  aqua/qt64/Portfile
  aqua/qt64/files/patch-qtbase-QTBUG-111443-qt64.diff
  aqua/qt64/files/patch-qtbase-macos_10.14_sdk.diff
  aqua/qt64/files/patch-qtbase-macports-clang-qt64.diff
Labels: type: bugfix, maintainer: open

#25531 asio: update to 1.31.0
  devel/asio/Portfile
Labels: type: update, maintainer: open, by: member

#25528 LyX: fix building Qt4 variant
  aqua/LyX/Portfile
  aqua/LyX/files/patch-GuiFontMetrics.cpp.diff
Labels: type: bugfix, maintainer: open

#25544 blosc2: update to 2.15.1
  archivers/blosc2/Portfile
Labels: type: update, maintainer: open

#25536 nnn: update to 5.0
  sysutils/nnn/Portfile
Labels: type: update, maintainer: open, by: member

#25537 ngspice: fix the port for < 10.8
  science/ngspice/Portfile
  science/ngspice/files/patch-fix-linking.diff
  science/ngspice/files/patch-ngspice-older-MACH-defines.diff
  science/ngspice/files/patch-use-cxx-to-link-cxx-code.diff
Labels: type: bugfix, maintainer: open

#25580 ipsw: Update to 3.1.539
  security/ipsw/Portfile
Labels: type: update, maintainer, maintainer: open

#25545 catch2: update to 3.7.0
  devel/catch2/Portfile
Labels: type: update, maintainer: open

#25543 CImg: update to 3.4.1
  devel/CImg/Portfile
Labels: type: update, maintainer: open

#25582 tree-sitter-json: needs C99
  devel/tree-sitter-json/Portfile
Labels: type: bugfix, maintainer: open

#25381 php-postgres: update postgresql versions
  lang/php/Portfile
Labels: type: enhancement, type: update, maintainer: requires approval, maintainer: timeout

#25550 f2c: update to 20240504
  lang/f2c/Portfile
  lang/f2c/files/implicit.patch
Labels: type: update, maintainer: open

#25583 sqlean: update the patch for legacy systems so that it works again
  databases/sqlean/files/patch-no-time-ext.diff
Labels: type: bugfix, type: update, maintainer: open

#25595 swi-prolog: Updated to version 9.2.7
  lang/swi-prolog/Portfile
Labels: type: update, maintainer, maintainer: open

#25598 ruby-build: Upgrade to 20240903
  ruby/ruby-build/Portfile
Labels: maintainer, maintainer: open

#25597 josm: update to 19207
  gis/JOSM/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#25594 py-rasterio: unbreak build with libstdc++
  python/py-rasterio/Portfile
  python/py-rasterio/files/patch-fix-setup.py.diff
Labels: type: bugfix, maintainer: open

#25534 binwalk: switch fork, update to 2.4.1
  cross/binwalk/Portfile
Labels: type: enhancement, maintainer: open, by: member

#25602 OCRmyPDF: update to 16.5.0
  textproc/ocrmypdf/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer, maintainer: open

#25589 boolector: update to 3.2.4
  math/boolector/Portfile
Labels: type: update, maintainer: none

#25600 rage: add port
  security/rage/Portfile
Labels: type: enhancement, type: submission

#25586 tor-devel: update to 0.4.8.12
  security/tor-devel/Portfile
Labels: type: update, maintainer: none

#25585 tapkee: update to 2024.07.17
  math/tapkee/Portfile
Labels: type: update, maintainer, maintainer: open

#25584 tatami: update to 3.1.0; tatami-devel: update to 2024.09.02
  devel/tatami/Portfile
Labels: type: update, maintainer, maintainer: open

#25542 swiftformat: new port
  devel/swiftformat/Portfile
Labels: type: submission

#25549 elixir: update to 1.17.2
  lang/elixir/Portfile
Labels: type: update, maintainer: open

#25548 dyncall: update to 1.4
  devel/dyncall/Portfile
  devel/dyncall/files/patch-callback_suite.diff
Labels: type: update, maintainer: requires approval, maintainer: timeout

#25605 ipsw: Update to 3.1.540
  security/ipsw/Portfile
Labels: type: update, maintainer, maintainer: open

#25603 uv: Update to 0.4.4
  devel/uv/Portfile
Labels: type: update, maintainer, maintainer: open

#25604 gitu: Update to 0.25.0
  devel/gitu/Portfile
Labels: type: update, maintainer, maintainer: open

#25607 syncthing: update to 1.27.11
  net/syncthing/Portfile
Labels: type: enhancement, type: update, maintainer: open

#25606 qrcp: update to 0.11.3
  sysutils/qrcp/Portfile
Labels: type: enhancement, type: update, maintainer: open

#25570 exempi: update to 2.6.5
  graphics/exempi/Portfile
Labels: type: update, maintainer: open

#25581 glances: restore Lion compatibility
  sysutils/glances/Portfile
Labels: maintainer: none

#25613 ruby-devel: update to 2024.09.04
  lang/ruby-devel/Portfile
Labels: type: update, maintainer, maintainer: open

#25614 mise: Upgrade to 2024.9.0
  sysutils/mise/Portfile
Labels: maintainer, maintainer: open

#25612 age-plugin-yubikey: add port
  security/age-plugin-yubikey/Portfile
Labels: type: enhancement, type: submission

#25616 eza: update to 0.19.2
  sysutils/eza/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#25615 Gildas: update to 202409a
  science/gildas/Portfile
  science/gildas/files/patch-admin-Makefile.python.diff
Labels: type: enhancement, type: update, maintainer

#25617 snac: update to 2.58
  net/snac/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer, maintainer: open

#25561 libpcap: needs compiler.thread_local_storage
  net/libpcap/Portfile
Labels: type: bugfix, maintainer: open

#25578 screen: update to 5.0.0
  sysutils/screen/Portfile
  sysutils/screen/files/patch-acconfig.h.diff
  sysutils/screen/files/patch-apple-screen.diff
  sysutils/screen/files/patch-apple-window.diff
  sysutils/screen/files/patch-tic.diff
  sysutils/screen/files/patch-xcode-12-implicit-function-fixes.diff
Labels: type: enhancement, type: update, maintainer, maintainer: open

#25619 google-cloud-sdk: update to 491.0.0
  devel/google-cloud-sdk/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#25588 lean: update to 3.51.1
  math/lean/Portfile
Labels: type: enhancement, type: update, maintainer: open

#25623 micronaut: update to 4.6.1
  java/micronaut/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#25624 clojure: update to 1.12.0.1479
  lang/clojure/Portfile
Labels: type: update, maintainer, maintainer: open

#25464 gnome-terminal: update to 3.38.3
  gnome/gnome-terminal/Portfile
  gnome/gnome-terminal/files/autogen.sh
  gnome/gnome-terminal/files/patch-configure.ac.diff
  gnome/gnome-terminal/files/patch-src-Makefile.am.diff
  gnome/gnome-terminal/files/patch-src-terminal-screen.c.diff
Labels: type: update, maintainer: open

#25495 cpputest: fix build
  devel/cpputest/Portfile
  devel/cpputest/files/0001-MockParameterTest.cpp-fix-ULL-constants.patch
Labels: type: bugfix, maintainer: none

#25620 openssl3: fix build with older versions of Perl
  devel/openssl3/Portfile
  devel/openssl3/files/patch-mkinstallvars.diff
Labels: maintainer: requires approval

#25629 fastfetch: update to 2.23.0 for legacy systems
  sysutils/fastfetch/Portfile
Labels: type: update, maintainer: open

#25632 uv: Update to 0.4.6
  devel/uv/Portfile
Labels: type: update, maintainer, maintainer: open

#25633 ruff: Update to 0.6.4
  devel/ruff/Portfile
Labels: type: update, maintainer, maintainer: open

#25631 jujutsu: update to 0.21.0
  devel/jujutsu/Portfile
Labels: type: update, maintainer: open

#25630 cpp-peglib: update to 1.9.0
  devel/cpp-peglib/Portfile
Labels: type: update, maintainer, maintainer: open

#25635 n: update to 10.0.0
  devel/n/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer, maintainer: open

#25637 tippecanoe: update to 2.62.0
  gis/tippecanoe/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#25634 screen: Fix invalid value 'c17' in '-std=c17'
  sysutils/screen/Portfile
Labels: type: bugfix, maintainer: open

#25638 syncthing: update to 1.27.12
  net/syncthing/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#25579 valkey: add redis_compat variant with redis symlinks
  databases/valkey/Portfile
Labels: type: enhancement, maintainer: open

#25641 vhs: update to 0.8.0
  graphics/vhs/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#25636 gallery-dl: update to 1.27.4, remove youtube-dl
  net/gallery-dl/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer, maintainer: open

#25592 Xaw3d: update to 1.6.6
  x11/Xaw3d/Portfile
  x11/Xaw3d/files/patch-src-vendor.diff
Labels: type: update, maintainer: open

#25591 gccxml-devel: update, fix on powerpc, set supported platforms
  lang/gccxml-devel/Portfile
  lang/gccxml-devel/files/patch-fix-host-darwin.diff
Labels: type: bugfix, type: update, maintainer: none

#25590 vampire: update to 4.9 release
  math/vampire/Portfile
  math/vampire/files/0001-Allocator.cpp-fix-for-macOS-where-aligned_alloc-may-.patch
Labels: type: update, maintainer: open

#25645 fastfetch: minor fix for legacy macOS (no revbump)
  sysutils/fastfetch/Portfile
  sysutils/fastfetch/files/0021-CMakeLists-do-not-use-Linux-ldflag-on-macOS.patch
  sysutils/fastfetch/files/0022-Tiger-specific-adjustments-to-CMakeLists.patch
Labels: type: bugfix, maintainer: open

#25647 pika: update to 0.28.0
  devel/pika/Portfile
  devel/pika/files/patch-fix-finding-boost.diff
Labels: type: update, maintainer, maintainer: open

#25649 py-awscli2: update to 2.17.46
  python/py-awscli2/Portfile
  python/py-awscli2/files/0001-py-awscli2-Support-empty-PAGER.patch
Labels: type: enhancement, type: update, maintainer, maintainer: open

#25655 libpipeline: update to 1.5.8
  devel/libpipeline/Portfile
Labels: type: update, maintainer, maintainer: open

#25653 ImageMagick7: Update to 7.1.1-38
  graphics/ImageMagick7/Portfile
Labels: type: update, maintainer, maintainer: open

#25657 bfs: update to 4.0.1
  sysutils/bfs/Portfile
Labels: type: update, maintainer, maintainer: open

#25659 gitui: update to 0.26.3
  devel/gitui/Portfile
Labels: type: enhancement, type: update, maintainer: open

#25656 man-db: update to 2.13.0
  textproc/man-db/Portfile
Labels: type: update, maintainer, maintainer: open

#25658 swi-prolog-devel: Updated to version 9.3.11
  lang/swi-prolog-devel/Portfile
Labels: type: update, maintainer, maintainer: open

#25667 chafa: update to 1.14.3
  graphics/chafa/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#25673 nco: update to 5.2.8
  science/nco/Portfile
Labels: type: update, maintainer, maintainer: open

#25674 ecCodes: update to 2.37.0
  science/ecCodes/Portfile
Labels: type: update, maintainer, maintainer: open

#25676 primesieve: update to 12.4
  math/primesieve/Portfile
Labels: type: update, maintainer: none

#25639 jpeginfo: add legacysupport portgroup for macOS 10.6 (strnlen)
  multimedia/jpeginfo/Portfile
Labels: maintainer: open

#25677 jd: new port (v1.9.1)
  textproc/jd/Portfile
Labels: type: submission, by: member

#25682 spral: update to 2024.05.08
  math/spral/Portfile
Labels: type: update, maintainer, maintainer: open

#25681 LBFGSpp: new port in math
  math/LBFGSpp/Portfile
Labels: type: submission

#25680 cppoptlib: new port in math
  math/cppoptlib/Portfile
Labels: type: submission

#25679 finite-diff: new port in math
  math/finite-diff/Portfile
  math/finite-diff/files/patch-CMakeLists.diff
Labels: type: submission

#25684 boehmgc: update to 8.2.8
  devel/boehmgc/Portfile
Labels: type: bugfix, type: update, maintainer: none

#25685 duckdb: update to 1.1.0
  databases/duckdb/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#25654 oscar: update to 1.5.3
  aqua/oscar/Portfile
  aqua/oscar/files/patch-nullptr.diff
  aqua/oscar/files/patch-oscar.pro.diff
Labels: type: update, maintainer: open, by: member

#25687 boehmgc: fix build after update
  devel/boehmgc/Portfile
Labels: type: bugfix, maintainer: none

#25689 nuclei: new port
  security/nuclei/Portfile
Labels: type: submission, by: member

#25646 Wine devel,wine staging update to 9.17
  cross/mingw-w64-wine-mono/Portfile
  emulators/wine-devel/Portfile
  emulators/wine-devel/files/1001-devel-msync.diff
  emulators/wine-devel/files/1001-staging-msync.diff
Labels: maintainer

#25692 mise: Upgrade to 2024.9.1
  sysutils/mise/Portfile
Labels: maintainer, maintainer: open

#25690 stunnel: prevent opportunistic linking to mimalloc, add a variant
  security/stunnel/Portfile
Labels: type: bugfix, maintainer: open

#25694 py-pynetdicom: 2.1.1
  python/py-pynetdicom/Portfile
Labels: maintainer, maintainer: open, by: member

#25695 pv: 1.8.14
  sysutils/pv/Portfile
Labels: maintainer, maintainer: open, by: member

#25696 oh-my-posh: update to version 23.12.0
  sysutils/oh-my-posh/Portfile
Labels: type: update, maintainer, maintainer: open

#25477 ipe: update to version 7.2.29
  graphics/ipe-tools/Portfile
  graphics/ipe-tools/files/patch-svgtoipe-svgtoipe.py.diff
  graphics/ipe-tools/files/pdftoipe-c++20.patch
  graphics/ipe-tools/files/pdftoipe-fix-building-with-poppler.patch
  graphics/ipe-tools/files/pdftoipe-fix-poppler-xmloutput.patch
  graphics/ipe/Portfile
  graphics/ipe/files/fix-missing-cstdlib.patch
  graphics/ipe/files/ipetoipe.in
Labels: type: bugfix, type: enhancement, type: update, maintainer: open

#25652 msdfgen: unbreak build with gcc
  graphics/msdfgen/Portfile
Labels: type: bugfix, maintainer: requires approval

#25643 sparskit: Update to 2-20210601
  science/sparskit/Portfile
  science/sparskit/files/patch-makefile.diff
Labels: type: update, maintainer: requires approval, maintainer: timeout, by: member

#25628 tmux: Remove supplied Vim syntax file
  sysutils/tmux/Portfile
  sysutils/tmux/files/tmux.vim
Labels: maintainer: open

#25651 redis: update to 7.4.0
  databases/redis/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#25648 cryptlib: fix build with gcc
  devel/cryptlib/Portfile
  devel/cryptlib/files/patch-static_assert.diff
Labels: type: bugfix, maintainer: open

#25700 google-cloud-sdk: update to 492.0.0
  devel/google-cloud-sdk/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#25701 got: update to 0.103
  devel/got/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer, maintainer: open

#25702 weechat: update to 4.4.2
  irc/weechat/Portfile
Labels: type: update, maintainer, maintainer: open

#25704 ipsw: Update to 3.1.542
  security/ipsw/Portfile
Labels: type: update, maintainer, maintainer: open

#25703 uv: Update to 0.4.9
  devel/uv/Portfile
Labels: type: update, maintainer, maintainer: open

#25706 stow: Update to 2.4.1
  sysutils/stow/Portfile
Labels: type: update, maintainer, maintainer: open

#25699 litecli: update to 1.12.2
  databases/litecli/Portfile
Labels: type: update, maintainer: none, by: member

#25697 glasskube: update to 0.20.1
  devel/glasskube/Portfile
Labels: type: update, maintainer: open, by: member

#25664 asymptote: update to 2.91
  graphics/asymptote/Portfile
Labels: type: update, maintainer: open

#25663 flint: update to 3.1.3-p1
  math/flint/Portfile
Labels: type: update, maintainer: open

#25650 postgresql-unaccent: remove port
  databases/postgresql-unaccent/Portfile
Labels: maintainer: none

#25618 verilator: update version 5.020->5.028
  science/verilator/Portfile
Labels: type: enhancement, type: update, maintainer: open

#25712 rocksdb: update to 9.6.1
  databases/rocksdb/Portfile
Labels: type: update, maintainer: open

#25698 py-pygments: update to 2.18.0
  python/py-pygments/Portfile
Labels: type: update, maintainer: open, by: member

#25662 py-bottleneck: update to 1.4.0
  python/py-bottleneck/Portfile
  python/py-bottleneck/files/patch-pyproject.toml.diff
Labels: type: update, maintainer: open, by: member

#25668 direnv: update to 2.34.0
  devel/direnv/Portfile
Labels: type: enhancement, type: update, maintainer: open

#25714 rsgain: add port
  audio/rsgain/Portfile
Labels: type: enhancement, type: submission

#25716 ipsw: Update to 3.1.543
  security/ipsw/Portfile
Labels: type: update, maintainer, maintainer: open

#25660 qtsingleapplication-qt4: new port in devel
  devel/qtsingleapplication-qt4/Portfile
  devel/qtsingleapplication-qt4/files/0001-qtsingleapplication-unbreak-build-with-Qt4.patch
Labels: type: submission

#25717 tree-sitter-go-mod: needs C99
  devel/tree-sitter-go-mod/Portfile
Labels: type: bugfix, maintainer: open

#25720 mise: Upgrade to 2024.9.2
  sysutils/mise/Portfile
Labels: maintainer, maintainer: open

#25719 libcoverart: fix build with gcc
  devel/libcoverart/Portfile
  devel/libcoverart/files/patch-cmakelists-4.diff
Labels: type: bugfix, maintainer: none

#25675 petsc: update to 3.21.5
  math/petsc/Portfile
Labels: type: update, maintainer: open

#25672 nanoflann: update to 1.6.1
  math/nanoflann/Portfile
Labels: type: update, maintainer: open

#25721 fluent-bit: update to 3.1.7
  sysutils/fluent-bit/Portfile
  sysutils/fluent-bit/files/0006-flb_utils.c-fix-for-macOS-12.patch
Labels: type: update, maintainer, maintainer: open, by: member

#25722 GPXSee: update to 13.24
  gis/GPXSee/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#25713 input-leap: update to git HEAD
  aqua/input-leap/Portfile
  aqua/input-leap/files/remove-gtest.patch
Labels: type: enhancement, type: update, maintainer, maintainer: open

#25688 libgdiplus: unbreak build on < 10.8
  devel/libgdiplus/Portfile
Labels: type: bugfix, maintainer: open

#25683 tcpkali: update to 1.1.1, fix build on < 10.7
  net/tcpkali/Portfile
  net/tcpkali/files/0001-tcpkali_iface.c-define-AI_NUMERICSERV-when-undefined.patch
Labels: type: bugfix, type: update, maintainer: open

#25678 OpenBLAS: update to 0.3.28
  math/OpenBLAS/Portfile
Labels: type: update, maintainer: open

#25669 dbeaver-community: Update to 24.2.0
  databases/dbeaver-community/Portfile
Labels: type: update, maintainer: open

#25723 mise: Upgrade to 2024.9.3
  sysutils/mise/Portfile
Labels: maintainer, maintainer: open
