Repository macports/macports-ports, pull requests merged in 2024-02, with the labels that each got.

#22475 py-spaghetti: update to 1.7.5.post1; pin 1.7.4 for py39
  python/py-spaghetti/Portfile
Labels: type: update, maintainer: none

#22485 ast: set needed C standard, fix build on < 10.7
  science/ast/Portfile
Labels: type: bugfix, maintainer: open

#22486 lima: Upgrade to v0.20.1
  sysutils/lima/Portfile
Labels: maintainer, maintainer: open

#22484 tiledb: update to 2.19.1, fix building tests variant
  databases/tiledb/Portfile
  databases/tiledb/files/patch-2.19.1.diff
  databases/tiledb/files/patch-libatomic-32-bit.diff
  databases/tiledb/files/patch-random.diff
  databases/tiledb/files/patch-unit_capi_error_tree.cc-temporary-fix.diff
Labels: type: bugfix, type: update, maintainer, maintainer: open

#22487 R-igraph: update to 2.0.1.1
  R/R-igraph/Portfile
Labels: type: update, maintainer, maintainer: open

#22472 openldap-devel: blacklist old Xcode gcc
  databases/openldap-devel/Portfile
Labels: type: bugfix, maintainer: open

#22491 swi-prolog-devel: Updated to version 9.3.0
  lang/swi-prolog-devel/Portfile
Labels: type: update, maintainer, maintainer: open

#22495 py-codecov: add py312
  python/py-codecov/Portfile
Labels: maintainer: none

#22470 py-pytest-env: new port, version 1.1.3
  python/py-pytest-env/Portfile
Labels: type: submission

#22450 mmg: update to 5.7.2
  science/mmg/Portfile
  science/mmg/files/0001-libmmg3d_private.h-include-inttypes.h-for-PRId.patch
Labels: type: bugfix, type: update, maintainer: open

#22449 opencascade: fix build on PowerPC
  science/opencascade/Portfile
  science/opencascade/files/patch-ViewerTest_CmdParser.cxx.diff
Labels: type: bugfix, maintainer: open

#22444 cgnslib: update to 4.4.0
  science/cgnslib/Portfile
Labels: type: update, maintainer: open

#22441 alglib: fix build on ppc currently broken due to size-of-bool assert
  math/alglib/Portfile
  math/alglib/files/patch-bool-size-ppc.diff
Labels: type: bugfix, maintainer: open

#22496 py-scikit-learn: update to 1.4.0; update and pin 1.3.2 to py38
  python/py-scikit-learn/Portfile
Labels: type: update, maintainer: open

#22497 py-codecov: drop obsolete py37
  python/py-codecov/Portfile
Labels: maintainer: none

#22498 py-pysal: update to 24.1
  python/py-pysal/Portfile
Labels: type: update, maintainer: none

#22501 py-setuptools: update to 69.0.3
  python/py-setuptools/Portfile
Labels: type: update, maintainer: open, by: member

#22503 tiledb: non-functional: fix portfile parsing
  databases/tiledb/Portfile
Labels: type: bugfix, maintainer, maintainer: open

#22505 eza: update to 0.18.0
  sysutils/eza/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#22500 py-psycopg: update to 3.1.17, add 312
  python/py-psycopg/Portfile
Labels: type: update, maintainer: open

#22507 openldap-devel: also blacklist old clang of Xcode 3.2.6
  databases/openldap-devel/Portfile
Labels: type: bugfix, maintainer: open

#22509 difftastic: Upgrade to 0.55.0
  devel/difftastic/Portfile
Labels: maintainer: open

#22516 py-threadpoolctl: add py312; drop py37; enable tests
  python/py-threadpoolctl/Portfile
  python/py-threadpoolctl/files/patch-test.diff
Labels: maintainer: open

#22510 hdf5: Only patch h5fc on +fortran.
  science/hdf5/Portfile
Labels: maintainer, maintainer: open, by: member

#22514 google-glog: fix compiler blacklist
  devel/google-glog/Portfile
Labels: type: bugfix, maintainer: none

#22478 socket_vmnet: new port (1.1.3)
  net/socket_vmnet/Portfile
Labels: type: submission

#22517 newsraft: new port
  net/newsraft/Portfile
Labels: type: enhancement, type: submission

#22515 py-quantecon: add Python 3.12 subport; enable test
  python/py-quantecon/Portfile
Labels: maintainer: none

#22512 libocca: fix older Intel builds
  devel/libocca/Portfile
  devel/libocca/files/0002-sys.cpp-add-missing-AvailabilityMacros.h.patch
  devel/libocca/files/0003-sys.cpp-use-clock_gettime-on-macOS-when-supported.patch
  devel/libocca/files/0004-sys.cpp-update-pthread_threadid-code-for-macOS.patch
Labels: type: bugfix, maintainer, maintainer: open

#22462 tmux: overwrite config dir
  sysutils/tmux/Portfile
Labels: type: enhancement, maintainer: open, by: member

#22521 colima: Upgrade to 0.6.8
  sysutils/colima/Portfile
Labels: maintainer, maintainer: open

#22523 socket_vmnet: use default CFLAGS/LDFLAGS
  net/socket_vmnet/Portfile
Labels: type: enhancement, maintainer, maintainer: open

#22519 igraph: update to 0.10.9
  math/igraph/Portfile
Labels: type: update, maintainer, maintainer: open

#22520 libsndfile: do not use gcc-4.2 on Intel
  audio/libsndfile/Portfile
Labels: type: bugfix, maintainer: none

#22513 py-pgspecial: update to 2.1.1, add 311, use psycopg3
  python/py-pgspecial/Portfile
Labels: type: update, maintainer: none

#22480 cryfs: set compiler.thread_local_storage
  net/cryfs/Portfile
Labels: type: bugfix, maintainer, maintainer: open

#22466 shards: update to 0.17.4
  devel/shards/Portfile
Labels: type: update, maintainer: open

#22465 catch2: update to 3.5.2
  devel/catch2/Portfile
Labels: type: update, maintainer: open, by: member

#22463 netdata: update to 1.44.1
  sysutils/netdata/Portfile
Labels: type: update, maintainer: open, by: member

#22526 mpich: remove -commons flag on XC 15
  science/mpich/Portfile
Labels: maintainer, by: member

#21043 hugin-app: Switch to wxWidgets version 3.2
  graphics/hugin-app/Portfile
Labels: type: enhancement, maintainer: open

#22527 socket_vmnet: patch to include correct Availability header
  net/socket_vmnet/Portfile
  net/socket_vmnet/files/fix-include-Availability-header.diff
Labels: type: bugfix, maintainer, maintainer: open

#22473 rsgislib: update to version 5.1.1
  gis/rsgislib/Portfile
Labels: type: update, maintainer: requires approval

#21251 poppler: fix library paths in generated typelib file
  graphics/poppler-devel/Portfile
  graphics/poppler-devel/files/patch-glib_CMakeFiles.txt-fix-lib-location.diff
Labels: type: bugfix, maintainer: open

#22528 legacy-support-devel: update to current master
  devel/legacy-support/Portfile
Labels: type: bugfix, type: update, maintainer: open

#22468 sqlite3: fix pointer size for ppc64
  databases/sqlite3/Portfile
  databases/sqlite3/files/patch-sqlite3-tools_fix-defines-ppc.diff
  databases/sqlite3/files/patch-sqlite3_fix-defines-ppc.diff
Labels: type: bugfix, maintainer: open

#22490 py-invoke: update to 2.2.0
  python/py-invoke/Portfile
Labels: type: update, maintainer: open, by: member

#22488 bitcoin: fix build on macOS < 10.13
  finance/bitcoin/Portfile
Labels: maintainer: open

#22525 adblock2privoxy: Update to version 2.2.0
  www/adblock2privoxy/Portfile
Labels: type: update, maintainer, maintainer: open

#22524 haskell-language-server: Submission
  devel/haskell-language-server/Portfile
  devel/haskell-language-server/files/Paths_NAME.hs
Labels: type: submission

#22460 fpc: fix os.version bug
  lang/fpc/Portfile
Labels: type: bugfix, maintainer, maintainer: open

#22533 socket_vmnet: Add minimum darwin version requirement
  net/socket_vmnet/Portfile
Labels: type: bugfix, maintainer, maintainer: open

#22535 lpython: new port in lang
  lang/lpython/Portfile
  lang/lpython/files/0001-stacktrace.cpp-include-syslimits.h-for-PATH_MAX.patch
  lang/lpython/files/0002-UserOverride.cmake-fix-native-optflag-for-PowerPC.patch
  lang/lpython/files/0003-Install-libs-into-a-sane-location.patch
  lang/lpython/files/0004-parser_stype.h-allow-building-for-ppc.patch
  lang/lpython/files/0005-patch-build0.sh.patch
  lang/lpython/files/0006-patch-version.patch
Labels: type: submission

#22537 libopenraw-legacy: non-functional: fix homepage
  graphics/libopenraw-legacy/Portfile
Labels: maintainer, maintainer: open

#22538 miniupnpc: update to 2.2.6
  net/miniupnpc/Portfile
Labels: type: update, maintainer: none

#22539 adept2: update to 2024.01.24
  math/adept2/Portfile
Labels: type: update, maintainer, maintainer: open

#22541 libretroshare: update to 2024.02.03
  net/libretroshare/Portfile
Labels: type: update, maintainer, maintainer: open

#22542 gloox: update to 1.0.28
  net/gloox/Portfile
Labels: type: update, maintainer: none

#22540 gtk-gnutella: update to 2024.02.02
  net/gtk-gnutella/Portfile
Labels: type: update, maintainer, maintainer: open

#22544 iwnet: update to 2024.01.27
  net/iwnet/Portfile
  net/iwnet/files/0001-Revert-iwn_poller_poll_in_thread-now-waits-poller-th.patch
Labels: type: update, maintainer, maintainer: open

#22532 picotls: new port
  net/picotls/Portfile
Labels: type: submission

#22508 cargo2port: Update to 0.2.1
  sysutils/cargo2port/Portfile
Labels: type: update, maintainer: open

#22548 py-awscli2: update to 2.15.17
  python/py-awscli2/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#22547 fortran-stdlib: update to 2024.01.17
  lang/fortran-stdlib/Portfile
Labels: type: update, maintainer, maintainer: open

#22502 netcdf @4.9.2: Add missing dependencies
  science/netcdf/Portfile
Labels: type: bugfix, type: enhancement, maintainer: open

#22499 py-ansible,py-ansible-core,py-resolvelib update to latest versions
  python/py-ansible-core/Portfile
  python/py-ansible-core/files/py312-ansible
  python/py-ansible/Portfile
  python/py-resolvelib/Portfile
Labels: type: enhancement, maintainer: open

#22546 py-pandas: fix compiler choice
  python/py-pandas/Portfile
Labels: type: bugfix, maintainer: open

#22549 coreutils-uutils: update to 0.0.24
  sysutils/coreutils-uutils/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#22550 py-resolvlib: Remove obsolete python 3.7 variant
  python/py-resolvelib/Portfile
Labels: type: security fix, maintainer: none

#22551 newsraft: fix prefix
  net/newsraft/Portfile
Labels: type: enhancement, maintainer, maintainer: open

#22552 sfm: fix prefix
  sysutils/sfm/Portfile
Labels: type: enhancement, maintainer, maintainer: open

#22553 p5-dbd-mysql: upgrade version, remove EOL variants, add mysql82
  perl/p5-dbd-mysql/Portfile
Labels: type: enhancement, type: security fix, maintainer: none

#22555 google-cloud-sdk: update to 462.0.1
  devel/google-cloud-sdk/Portfile
Labels: type: update, maintainer, maintainer: open

#22128 GtkWave : Update gtkwave to 3.3.117
  cad/gtkwave/Portfile
Labels: type: update, maintainer, maintainer: open

#22557 iv: non-functional: fix parsing port again
  devel/iv/Portfile
Labels: type: bugfix, maintainer, maintainer: open

#22562 ruby-devel: update to 2024.02.05
  lang/ruby-devel/Portfile
Labels: type: update, maintainer, maintainer: open

#22560 turbo: update to 2024.02.05, fixes Big-endian builds
  editors/turbo/Portfile
Labels: type: bugfix, type: update, maintainer, maintainer: open

#22522 fastmod: Upgrade to 0.4.4
  devel/fastmod/Portfile
Labels: maintainer: open

#22518 qt5-mysql-plugin, qt6-mysql-plugin new variants
  aqua/qt5/Portfile
  aqua/qt6/Portfile
Labels: type: bugfix, type: enhancement, maintainer: open

#22566 gitoxide: new port (version 0.33.0)
  devel/gitoxide/Portfile
Labels: type: submission, by: member

#22511 re2: update to 2024-02-01
  devel/re2/Portfile
Labels: type: update, maintainer, by: member

#22251 htop: unbreak build on < 10.9
  sysutils/htop/Portfile
  sysutils/htop/files/0001-darwin-Platform.c-use-mach-port.h.patch
  sysutils/htop/files/0002-darwin-PlatformHelpers-fix-CPU-detection-for-PowerPC.patch
Labels: type: bugfix, maintainer: open

#22392 OpenCoarrays: update to 2.10.2
  science/OpenCoarrays/Portfile
Labels: type: update, maintainer, maintainer: open

#22571 cgmnlm: update to 1.7
  net/cgmnlm/Portfile
Labels: type: update, maintainer, maintainer: open

#22570 pipx: update to 1.4.3
  python/pipx/Portfile
Labels: type: update, maintainer, maintainer: open

#22530 mackup: update to 0.8.40, set 312 default, use poetry
  sysutils/mackup/Portfile
Labels: type: update, maintainer: open

#22445 freeimage: fix Big-endian build
  graphics/freeimage/Portfile
  graphics/freeimage/files/patch-fix-ImfFastHuf.diff
  graphics/freeimage/files/patch-fix-PluginBMP.diff
  graphics/freeimage/files/patch-fix-PluginDDS.diff
Labels: type: bugfix, maintainer: none

#22576 py-mslex: new port
  python/py-mslex/Portfile
Labels: type: submission

#22575 pascal-p5: allow powerpc build (no change to the code)
  lang/pascal-p5/Portfile
Labels: type: enhancement, maintainer: open

#22577 wezterm: update to 20240203-110809-5046fc22
  aqua/wezterm/Portfile
Labels: type: update, maintainer: open

#22578 libgit2-devel: update to 1.7.2
  devel/libgit2-devel/Portfile
Labels: type: update, type: security fix, maintainer: open, by: member

#22580 go: update to 1.22.0
  lang/go/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#22583 GtkWave: Reverted GTKWave 3.3.117 to GTK2+quartz.
  cad/gtkwave/Portfile
Labels: maintainer, maintainer: open

#22586 google-cloud-sdk: update to 463.0.0
  devel/google-cloud-sdk/Portfile
Labels: type: update, maintainer, maintainer: open

#22588 openjdk17: update URLs
  java/openjdk17/Portfile
Labels: type: update, maintainer: open

#22587 openjdk21: update URLs
  java/openjdk21/Portfile
Labels: type: update, maintainer, maintainer: open

#22590 micronaut: update to 4.3.0
  java/micronaut/Portfile
Labels: type: update, maintainer, maintainer: open

#22582 pipx: change default variant to python312
  python/pipx/Portfile
Labels: type: enhancement, maintainer, maintainer: open

#22585 gk: update to v1.5.1
  devel/gk/Portfile
Labels: type: update, maintainer, maintainer: open

#22593 fheroes2: update to 1.0.12
  games/fheroes2/Portfile
Labels: type: update, maintainer, maintainer: open

#22591 sshpass: update to 1.10
  sysutils/sshpass/Portfile
Labels: type: update, maintainer: none

#22594 rustpython: new port (version 0.3.0)
  lang/rustpython/Portfile
Labels: type: submission, by: member

#22584 boehmgc: update to 8.2.6
  devel/boehmgc/Portfile
Labels: type: bugfix, type: update, maintainer: none

#22545 py-pdfminer: update to 20231228
  python/py-pdfminer/Portfile
Labels: type: update, maintainer: open

#22603 symfony-cli: update to 5.8.7
  devel/symfony-cli/Portfile
Labels: type: update, maintainer, maintainer: open

#22543 libmicrohttpd: update to 1.0.0
  www/libmicrohttpd/Portfile
  www/libmicrohttpd/files/patch-fix-gnutls-include.diff
Labels: type: update, maintainer: open

#22604 Remove gpanders as port maintainer
  devel/vint/Portfile
  lua/lua-ansicolors/Portfile
  lua/lua-argparse/Portfile
  lua/lua-checks/Portfile
  lua/lua-luacheck/Portfile
  lua/lua-luafilesystem/Portfile
  lua/lua-metalua-parser/Portfile
  lua/lua-readline/Portfile
  lua/stylua/Portfile
  mail/mutt_ics/Portfile
  net/nextdns/Portfile
  python/py-ansicolor/Portfile
  sysutils/neovim-remote/Portfile
  sysutils/netdata/Portfile
  sysutils/pushbroom/Portfile
  textproc/ijq/Portfile
Labels: maintainer, maintainer: open

#22606 skaffold: update to 2.10.1
  devel/skaffold/Portfile
Labels: type: update, maintainer, maintainer: open

#22607 iv: fix for i386 build
  devel/iv/Portfile
  devel/iv/files/patch-fpu.h-fix-i386-on-macOS.diff
Labels: type: bugfix, maintainer, maintainer: open

#22556 girara: Update to 0.4.2
  devel/girara/Portfile
Labels: type: update, maintainer: open, by: member

#22610 atomvm: update to 0.6.0b0
  erlang/atomvm/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#22601 fizz: fix build on i386 with libstdc++
  devel/fizz/Portfile
Labels: type: bugfix, maintainer, maintainer: open

#22616 alacritty: fix nerdfont variant
  aqua/alacritty/Portfile
  aqua/alacritty/files/crossfont-nerd-symbols.patch
Labels: maintainer: open

#22622 tippecanoe: update to 2.42.0
  gis/tippecanoe/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#22624 josm: update to 18969
  gis/JOSM/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#22619 ecCodes: update to 2.34.0
  science/ecCodes/Portfile
Labels: type: update, maintainer, maintainer: open

#22615 extractpdfmark: update to 1.1.1
  textproc/extractpdfmark/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#22596 qbs: Update to 2.2.2
  devel/qbs/Portfile
Labels: type: update, maintainer: open

#22614 py-pendulum: update to 3.0.0, use maturin
  python/py-pendulum/Portfile
Labels: type: update, maintainer: none

#22621 jsoncons: new port
  devel/jsoncons/Portfile
Labels: type: enhancement, type: submission

#22631 micronaut: update to 4.3.1
  java/micronaut/Portfile
Labels: type: update, maintainer, maintainer: open

#22629 openjdk8-openj9: update to 8u402
  java/openjdk8-openj9/Portfile
Labels: type: update, maintainer, maintainer: open

#22627 openjdk17-openj9: update to 17.0.10
  java/openjdk17-openj9/Portfile
Labels: type: update, maintainer, maintainer: open

#22626 openjdk21-openj9: update to 21.0.2
  java/openjdk21-openj9/Portfile
Labels: type: update, maintainer, maintainer: open

#22628 openjdk11-openj9: update to 11.0.22
  java/openjdk11-openj9/Portfile
Labels: type: update, maintainer, maintainer: open

#22597 scw: update to 2.26.0
  net/scw/Portfile
Labels: type: update, maintainer: open, by: member

#22608 libmicrohttpd: update receipt
  www/libmicrohttpd/Portfile
Labels: type: update, maintainer: open

#22638 dolt: update to 1.34.0
  devel/dolt/Portfile
Labels: type: update, maintainer: open

#22563 CLI11: update to 2.4.1, support testing
  devel/CLI11/Portfile
Labels: type: enhancement, type: update, maintainer: open

#22605 imath: update to 3.1.10
  graphics/imath/Portfile
Labels: type: update, maintainer: open, by: member

#22641 chez-scheme: update to 10.0.0
  lang/chez-scheme/Portfile
Labels: type: update, maintainer, maintainer: open

#22647 dcmtk: Update to 3.6.8
  graphics/dcmtk/Portfile
  graphics/dcmtk/files/install_path_fix.patch
  graphics/dcmtk/files/install_path_fix_part2.patch
Labels: type: update, maintainer, maintainer: open, by: member

#22599 forlab: new port in fortran
  fortran/forlab/Portfile
  fortran/forlab/files/0001-fpm.toml-add-install-target.patch
Labels: type: submission

#22600 simulated-annealing: new port in fortran
  fortran/simulated-annealing/Portfile
  fortran/simulated-annealing/files/patch-link-with-openblas.diff
Labels: type: submission

#22579 LimeChat: provide version for old system
  aqua/LimeChat/Portfile
  aqua/LimeChat/files/0001-Unbreak-the-build-10.5.patch
Labels: type: bugfix, maintainer: open

#22648 yyjson: new port (version 0.8.0)
  devel/yyjson/Portfile
Labels: type: submission, by: member

#22649 fastfetch: new port (version 2.8.2)
  sysutils/fastfetch/Portfile
Labels: type: submission, by: member

#22651 golangci-lint: update to 1.56.1
  devel/golangci-lint/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#22650 dokuwiki: update to 2024-02-06a
  www/dokuwiki/Portfile
Labels: type: update, maintainer: none

#22636 pgcli: update to 4.0.1, use psycopg3, add 311
  databases/pgcli/Portfile
Labels: type: update, maintainer: none

#22635 lapack: Fix builds with +accelerate +openblas
  math/lapack/Portfile
Labels: type: bugfix, maintainer, maintainer: open

#22625 netcdf-fortran: Rev bump only, to fix broken builds
  science/netcdf-fortran/Portfile
Labels: type: bugfix, maintainer, maintainer: open

#22620 g-ls: new port (0.26.0)
  sysutils/g-ls/Portfile
Labels: type: submission

#22652 jimtcl: new port (version 0.82)
  lang/jimtcl/Portfile
Labels: type: submission, by: member

#22653 snac: update to 2.47
  net/snac/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer, maintainer: open

#22654 roundcubemail: update to 1.6.6, add php83
  www/roundcubemail/Portfile
Labels: type: update, maintainer: none

#22657 igraph: update to 0.10.10
  math/igraph/Portfile
Labels: type: update, maintainer, maintainer: open

#22633 git-town: update to 12.0.0
  devel/git-town/Portfile
Labels: type: update, maintainer: open, by: member

#22658 duckdb: update to 0.10.0
  databases/duckdb/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#22660 got: update to 0.96
  devel/got/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer, maintainer: open
