Repository macports/macports-ports, pull requests merged in 2024-08, with the labels that each got.

#25145 py-silx: update to 2.1.0
  python/py-silx/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#25137 New Port: Ferium
  games/ferium/Portfile
Labels: type: submission

#25151 py-pulp: update to 2.9.0; migrate to PyPi
  python/py-pulp/Portfile
Labels: type: update, maintainer: none

#25088 OpenCSG: unbreak for older systems
  science/OpenCSG/Portfile
Labels: type: bugfix, maintainer: open

#25110 qbs: Update to 2.4.0
  devel/qbs/Portfile
Labels: type: enhancement, type: update, maintainer: open

#24912 gnome-calculator: Update to 46.1
  gnome/gnome-calculator/Portfile
Labels: type: enhancement, type: update, maintainer: open

#25158 yt-dlp: update to 2024.08.01
  net/youtube-dl/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer: requires approval

#25159 FAudio: update to 24.08
  audio/FAudio/Portfile
Labels: type: update, maintainer, maintainer: open

#25150 shellcheck: add manpage
  devel/shellcheck/Portfile
Labels: type: enhancement, maintainer: none

#25154 castxml: update to 0.6.8
  lang/castxml/Portfile
Labels: type: update, maintainer: open

#25161 fortran-stdlib-devel: update to 2024.07.09
  lang/fortran-stdlib/Portfile
Labels: type: update, maintainer, maintainer: open

#25163 scrcpy: Update to version 2.6
  multimedia/scrcpy/Portfile
Labels: type: update, maintainer, maintainer: open

#25162 libsoup, -devel: drop now unneeded special case for ppc
  gnome/libsoup-devel/Portfile
  gnome/libsoup/Portfile
Labels: type: bugfix, maintainer: open

#25166 ruff: Update to 0.5.6
  devel/ruff/Portfile
Labels: type: update, maintainer, maintainer: open

#25168 difftastic: Update to version 0.60.0
  devel/difftastic/Portfile
Labels: type: update, maintainer: open

#25165 GTK Internet Radio Locator 5.4.8 (macOS 14.5 / MacPorts 2.9.3)
  gnome/gtk-internet-radio-locator/Portfile
Labels: type: enhancement, maintainer, maintainer: open

#25156 mise: update to 2024.8.4
  sysutils/mise/Portfile
  sysutils/mise/files/patch-src_cli_self_update.diff
Labels: type: update, maintainer: open, by: member

#25171 libadwaita: update to 1.5.3
  gnome/libadwaita/Portfile
Labels: type: update, maintainer, maintainer: open

#25169 bitwarden-cli: Update to version 2024.7.2
  security/bitwarden-cli/Portfile
Labels: type: update, maintainer, maintainer: open

#25172 libsdl2-powerpc: update to 2.30.6
  devel/libsdl2-powerpc/Portfile
Labels: type: update, maintainer

#25167 ocrmypdf: update to 16.4.3
  textproc/ocrmypdf/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer, maintainer: open

#25134 hdfeos5: fix build when hdf5 is installed with +mpich
  science/hdfeos5/Portfile
Labels: type: bugfix, maintainer: requires approval

#25133 libdap: fix 32-bit build, add license
  science/libdap/Portfile
  science/libdap/files/patch-fix-32-bit.diff
Labels: type: bugfix, type: enhancement, maintainer: requires approval

#25015 libzdb-mysql55: add postgresql16 variant
  databases/libzdb-mysql55/Portfile
Labels: type: enhancement, maintainer: none

#24908 fvwm2: update to 2.7.0
  x11/fvwm2/Portfile
Labels: type: update, maintainer: none

#25174 pika: update to 0.26.1
  devel/pika/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#25177 josm: update to 19160
  gis/JOSM/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#25178 scrcpy: Update to version 2.6.1
  multimedia/scrcpy/Portfile
Labels: type: update, maintainer, maintainer: open

#25183 eza: update to 0.18.25
  sysutils/eza/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#25182 ipsw: Update to 3.1.532
  security/ipsw/Portfile
Labels: type: update, maintainer, maintainer: open

#25153 sfcgal: update to 1.5.2
  gis/sfcgal/Portfile
Labels: type: update, maintainer: requires approval, maintainer: timeout

#25185 fastfetch: fix the port for old systems and powerpc
  sysutils/fastfetch/Portfile
  sysutils/fastfetch/files/0001-gpu_apple.m-unbreak-for-10.11.patch
  sysutils/fastfetch/files/0002-memory_apple-fix-for-32-bit.patch
  sysutils/fastfetch/files/0003-opengl_apple.c-fix-for-10.7.patch
  sysutils/fastfetch/files/0004-sound_apple.c-fix-for-10.8.patch
  sysutils/fastfetch/files/0005-monitor_apple.m-no-HDR-before-10.11.patch
  sysutils/fastfetch/files/0006-gpu_apple.c-fix-for-old-systems.patch
  sysutils/fastfetch/files/0007-camera_apple.m-unbreak-for-10.7.patch
  sysutils/fastfetch/files/0008-brightness_apple.c-add-a-missing-include.patch
  sysutils/fastfetch/files/0009-Revert-refresh-rate-detection-commit-for-macOS.patch
  sysutils/fastfetch/files/0010-disk_bsd-minor-fix-for-a-type-fixes-calculation-of-d.patch
  sysutils/fastfetch/files/0011-CMakeLists-adjust-for-legacy-macOS.patch
  sysutils/fastfetch/files/0012-os_apple.m-etc.-fix-syntax-for-plists.patch
  sysutils/fastfetch/files/0013-osascript.m-fix-syntax.patch
  sysutils/fastfetch/files/0014-Revert-some-display-related-breakages.patch
  sysutils/fastfetch/files/0015-Fix-PowerPC-macros.patch
  sysutils/fastfetch/files/0016-Fix-autorelease-pools.patch
  sysutils/fastfetch/files/0017-disk_bsd-no-support-for-creation-time.patch
  sysutils/fastfetch/files/0018-Support-PowerPC-CPU-detection.patch
Labels: type: bugfix, type: enhancement, maintainer: open

#25187 osxphotos: update to 0.68.3
  graphics/osxphotos/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#25160 zmap: set required C11 standard
  net/zmap/Portfile
Labels: type: bugfix, maintainer: open

#25175 ruby-devel: update to 2024.08.03
  lang/ruby-devel/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer, maintainer: open

#25190 yq: update to 4.44.3
  textproc/yq/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#25184 pgbouncer: fix for < 10.7
  databases/pgbouncer/Portfile
Labels: type: bugfix, maintainer: open

#25193 oh-my-posh: update to version 23.4.1
  sysutils/oh-my-posh/Portfile
Labels: type: update, maintainer, maintainer: open

#25188 serpl: new port
  devel/serpl/Portfile
Labels: type: submission

#25086 ruby33: Cosmetic patchfile cleanup
  lang/ruby33/Portfile
  lang/ruby33/files/patch-sources.diff
  lang/ruby33/files/patch-vm_insnhelper.c.diff
Labels: maintainer, maintainer: open

#25170 torsocks: Update to 2.4.0
  net/torsocks/Portfile
  net/torsocks/files/gethostbyaddr_r.patch
  net/torsocks/files/implicit.patch
  net/torsocks/files/version.patch
Labels: type: update, maintainer: requires approval, by: member

#25164 luajit: update to 2.1.1720049189
  lang/luajit/Portfile
  lang/luajit/files/TARGET_OS.patch
Labels: type: update, maintainer: open

#25180 git-interactive-rebase-tool: Update to version 2.4.1
  devel/git-interactive-rebase-tool/Portfile
Labels: type: update, maintainer: open

#25196 fastfetch: rebase patches after update, support 10.4
  sysutils/fastfetch/Portfile
  sysutils/fastfetch/files/0001-gpu_apple.m-unbreak-for-10.11.patch
  sysutils/fastfetch/files/0002-memory_apple-fix-for-32-bit.patch
  sysutils/fastfetch/files/0003-opengl_apple.c-fix-for-10.7.patch
  sysutils/fastfetch/files/0004-sound_apple.c-fix-for-10.8.patch
  sysutils/fastfetch/files/0005-monitor_apple.m-no-HDR-before-10.11.patch
  sysutils/fastfetch/files/0006-gpu_apple.c-fix-for-old-systems.patch
  sysutils/fastfetch/files/0007-camera_apple.m-unbreak-for-10.7.patch
  sysutils/fastfetch/files/0008-brightness_apple.c-add-a-missing-include.patch
  sysutils/fastfetch/files/0009-CMakeLists-adjust-for-legacy-macOS.patch
  sysutils/fastfetch/files/0009-Revert-refresh-rate-detection-commit-for-macOS.patch
  sysutils/fastfetch/files/0010-disk_bsd-minor-fix-for-a-type-fixes-calculation-of-d.patch
  sysutils/fastfetch/files/0010-os_apple.m-etc.-fix-syntax-for-plists.patch
  sysutils/fastfetch/files/0011-osascript.m-fix-syntax.patch
  sysutils/fastfetch/files/0012-Fix-PowerPC-macros.patch
  sysutils/fastfetch/files/0013-Fix-autorelease-pools.patch
  sysutils/fastfetch/files/0014-disk_bsd-no-support-for-creation-time.patch
  sysutils/fastfetch/files/0015-Support-PowerPC-CPU-detection.patch
  sysutils/fastfetch/files/0016-Support-hostinfo-for-PowerPC-Macs.patch
  sysutils/fastfetch/files/0017-Revert-some-breakages.patch
  sysutils/fastfetch/files/0018-Fix-compatibility-with-10.4.patch
  sysutils/fastfetch/files/0019-Tiger-specific-adjustments-to-CMakeLists.patch
Labels: type: bugfix, type: enhancement, maintainer: open

#25194 gitu: Update to 0.24.0
  devel/gitu/Portfile
Labels: type: update, maintainer, maintainer: open

#25199 legacy-support: Update to v1.3.0.
  devel/legacy-support/Portfile
Labels: type: update, maintainer, maintainer: open

#25198 clojure: update to 1.11.4.1474
  lang/clojure/Portfile
Labels: type: update, maintainer, maintainer: open

#25195 gallery-dl: update to 1.27.2
  net/gallery-dl/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer, maintainer: open

#25176 neovim, -devel: update to 0.10.1 and 20240805
  editors/neovim/Portfile
  editors/neovim/files/embed-parsers-build.diff
Labels: type: update, maintainer: open

#25200 yggdrasil-go: update to 0.5.7
  net/yggdrasil-go/Portfile
Labels: type: update, maintainer: open

#25201 bluefish: use legacysupport to fix < 10.7
  editors/bluefish/Portfile
Labels: type: bugfix, maintainer: none

#25087 openEMS: update to 20240312, fix powerpc build
  science/openEMS/Portfile
  science/openEMS/files/0001-operator_ext_lumpedRLC.h-fix-includes.patch
  science/openEMS/files/0002-CMakeLists-define-version-once.patch
  science/openEMS/files/0003-CMakeLists-fix-powerpc.patch
Labels: type: bugfix, type: update, maintainer: open

#25202 edid-decode: update to version 20240731
  sysutils/edid-decode/Portfile
Labels: type: update, maintainer, maintainer: open

#25203 json2tsv: update to 1.2
  textproc/json2tsv/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#25181 catgirl: update to 2.2a
  net/catgirl/Portfile
  net/catgirl/files/patch-explicit-bzero.diff
Labels: type: update, maintainer: open

#25204 kotlin: update to 2.0.10
  lang/kotlin/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#25207 osxphotos: update to 0.68.4
  graphics/osxphotos/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#25209 google-cloud-sdk: update to 487.0.0
  devel/google-cloud-sdk/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#25205 catgirl: bump legacysupport to 13 for mkdirat and openat
  net/catgirl/Portfile
Labels: maintainer: open

#25211 vala{,-devel}: add missing lib dep for graphviz
  lang/vala-devel/Portfile
  lang/vala/Portfile
Labels: type: bugfix, maintainer: open, by: member

#25212 checkssl: update to 0.6.0
  sysutils/checkssl/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#25217 ipsw: Update to 3.1.533
  security/ipsw/Portfile
Labels: type: update, maintainer, maintainer: open

#25219 windowmaker: update to 0.96.0
  x11/windowmaker/Portfile
  x11/windowmaker/files/osdep_darwin.fix.diff
Labels: type: bugfix, type: update, maintainer: none

#25221 rb-unicode: update to 0.4.4.5
  ruby/rb-unicode/Portfile
Labels: type: update, maintainer: none

#25220 libdeflate: update to 1.21
  archivers/libdeflate/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#25215 hicolor-icon-theme: update to 0.18
  gnome/hicolor-icon-theme/Portfile
Labels: type: update, maintainer: none

#24640 rust: update to 1.80.1
  _resources/port1.0/group/rust_build-1.0.tcl
  devel/cargo/Portfile
  lang/rust/Portfile
Labels: type: update, maintainer: open, by: member

#25206 pv: Update to 1.8.12
  sysutils/pv/Portfile
Labels: type: update, maintainer: open

#25135 gmtsar: use legacysupport for getline
  science/gmtsar/Portfile
Labels: type: bugfix, maintainer: open

#25218 vtk: update to 9.3.1
  graphics/vtk/Portfile
Labels: type: update, maintainer: open

#25222 catgirl: fix build with gcc
  net/catgirl/Portfile
Labels: type: bugfix, maintainer: open

#25210 gdal: cleanup after 0659a06
  gis/gdal/Portfile
Labels: type: bugfix, maintainer: open

#25309 cegui: use C++11 to fix build on legacy systems
  devel/cegui/Portfile
Labels: type: bugfix, maintainer: open

#25307 pgpool-II: update to 4.5.2
  databases/pgpool-II/Portfile
Labels: type: enhancement, type: update, maintainer: none

#25298 xdelta: fix the build
  archivers/xdelta/Portfile
Labels: type: bugfix, maintainer: none

#25292 sakura: update to 3.8.8
  x11/sakura/Portfile
Labels: type: update, maintainer, maintainer: open

#25291 ocaml-parmap: update to 1.2.5
  ocaml/ocaml-parmap/Portfile
Labels: type: update, maintainer: none

#25263 catgirl-downloader: new port
  www/catgirl-downloader/Portfile
  www/catgirl-downloader/files/patch-use-right-python.diff
Labels: type: submission

#25261 darkstat: update to 3.0.721, fix build on older OS
  net/darkstat/Portfile
Labels: type: bugfix, type: update, maintainer: none

#25260 bcunit: fix build with Xcode gcc
  devel/bcunit/Portfile
  devel/bcunit/files/patch-drop-unsupported-flags.diff
Labels: type: bugfix, maintainer: open

#25314 mise: Upgrade to 2024.8.6
  sysutils/mise/Portfile
Labels: maintainer, maintainer: open

#25257 ocaml-camlp4: update to 4.14+1
  lang/ocaml-camlp4/Portfile
Labels: type: bugfix, type: update, maintainer: open

#25325 yggdrasil-go: update to 0.5.8
  net/yggdrasil-go/Portfile
Labels: type: update, maintainer: open

#25326 py-htmldocs: 3.12.5
  lang/py-htmldocs/Portfile
Labels: maintainer, maintainer: open, by: member

#25321 gallery-dl: update to 1.27.3
  net/gallery-dl/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer, maintainer: open

#25322 ipsw: Update to 3.1.535
  security/ipsw/Portfile
Labels: type: update, maintainer, maintainer: open

#25323 Bun: Update to 1.1.22
  devel/bun/Portfile
Labels: type: update, maintainer, maintainer: open

#25328 colima: Upgrade to 0.7.3
  sysutils/colima/Portfile
Labels: maintainer, maintainer: open

#25316 ruby32: Fix build with gcc14.
  lang/ruby32/Portfile
  lang/ruby32/files/patch-sources.diff
Labels: type: bugfix, maintainer, maintainer: open

#25327 ismrmrd: 1.14.1
  science/ismrmrd/Portfile
  science/ismrmrd/files/patch-ismrmrd-no-werror.diff
Labels: maintainer, maintainer: open, by: member

#25312 libqb: Use release tarball
  devel/libqb/Portfile
Labels: maintainer: open, by: member

#25329 catgirl-downloader: add missing deps
  www/catgirl-downloader/Portfile
Labels: type: bugfix, maintainer, maintainer: open

#25324 Packwiz: New Port
  games/packwiz/Portfile
Labels: type: submission

#25332 google-cloud-sdk: update to 488.0.0
  devel/google-cloud-sdk/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#25335 xmlwrapp: update to 0.9.1
  devel/xmlwrapp/Portfile
Labels: type: update, maintainer: none

#25333 spice-gtk: fix build for old systems
  gnome/spice-gtk/Portfile
Labels: type: bugfix, maintainer: none

#25254 py-meson: unbreak linking on < 10.7
  python/py-meson/Portfile
  python/py-meson/files/patch-unbreak-linking.diff
Labels: type: bugfix, maintainer: open

#25267 qbs: Update to 2.4.1
  devel/qbs/Portfile
Labels: type: enhancement, type: update, maintainer: open

#25278 libfmt11: new port
  devel/libfmt11/Portfile
Labels: type: submission

#25288 iperf3: fix for < 10.7
  net/iperf3/Portfile
Labels: type: bugfix, maintainer: open

#25286 findutils: update to 4.10.0
  sysutils/findutils/Portfile
Labels: type: enhancement, type: update, maintainer: open

#25290 readline: update to 8.2.13
  devel/readline/Portfile
Labels: type: enhancement, type: update, maintainer: open

#25339 eigenmath: update to 2024.06.20
  math/eigenmath/Portfile
Labels: type: update, maintainer, maintainer: open

#25340 basix: update to 0.8.0
  science/basix/Portfile
Labels: type: update, maintainer, maintainer: open

#25337 conauto: non-functional: use macports_distfiles
  math/conauto/Portfile
Labels: type: bugfix, maintainer, maintainer: open

#25336 oski: avoid archaic Xcode gcc
  devel/oski/Portfile
Labels: type: bugfix, maintainer: open

#25313 pgAdmin3: fix the port
  aqua/pgAdmin3/Portfile
Labels: type: bugfix, maintainer: none

#25338 any: update to 2024.05.01
  devel/any/Portfile
Labels: type: update, maintainer, maintainer: open

#25331 xmltooling: needs C++11
  security/xmltooling/Portfile
Labels: type: bugfix, maintainer: requires approval

#25342 fluent-bit: fix the port for earlier systems
  sysutils/fluent-bit/Portfile
  sysutils/fluent-bit/files/0001-macos-setup-do-not-use-clang-flag-with-gcc.patch
  sysutils/fluent-bit/files/0002-posix_file.c-add-a-missing-header.patch
  sysutils/fluent-bit/files/0003-libatomic-gcc.patch
  sysutils/fluent-bit/files/0004-snappy-compat.h-fix-Big-endian-on-Apple.patch
  sysutils/fluent-bit/files/0005-mk_scheduler-fix-for-missing-pthread_threadid_np.patch
  sysutils/fluent-bit/files/0006-flb_utils.c-fix-for-macOS-12.patch
  sysutils/fluent-bit/files/0007-Fix-for-meminfo-on-32-bit-darwin.patch
Labels: type: bugfix, maintainer: open

#25344 uv: Update to 0.2.36
  devel/uv/Portfile
Labels: type: update, maintainer, maintainer: open

#25315 wine-devel,wine-staging: update to 9.15
  emulators/wine-devel/Portfile
  emulators/wine-devel/files/1001-devel-msync.diff
  emulators/wine-devel/files/1001-staging-msync.diff
Labels: type: update, maintainer

#25343 edid-decode: update to version 20240811
  sysutils/edid-decode/Portfile
Labels: type: update, maintainer, maintainer: open

#25308 drupal7: use postgresql16 dependency
  www/drupal7/Portfile
Labels: type: enhancement, maintainer: none

#25300 jitsi-meet-electron: update to 2024.6.0
  net/jitsi-meet-electron/Portfile
Labels: type: update, maintainer: open

#25299 mysql8: rev bump to 8.4.2
  databases/mysql8/Portfile
Labels: type: enhancement, maintainer: open

#25296 libucl: update to 0.9.2, add conflict with ucl
  archivers/ucl/Portfile
  devel/libucl/Portfile
Labels: type: bugfix, maintainer: requires approval

#25294 petsc: update to 3.21.4
  math/petsc/Portfile
Labels: type: update, maintainer: open

#25277 gtk3: Add missing build dependency on mesa
  gnome/gtk3-devel/Portfile
  gnome/gtk3/Portfile
Labels: type: bugfix, maintainer: open, by: member

#25347 Bun: Update to 1.1.24
  devel/bun/Portfile
Labels: type: update, maintainer, maintainer: open

#25350 swi-prolog-devel: Updated to version 9.3.9
  lang/swi-prolog-devel/Portfile
Labels: type: update, maintainer, maintainer: open

#25351 py-rchitect: update to 0.4.7
  python/py-rchitect/Portfile
Labels: type: update, maintainer, maintainer: open

#25352 qrscan: fix build with Xcode gcc
  graphics/qrscan/Portfile
  graphics/qrscan/files/patch-Makefile.diff
Labels: type: bugfix, maintainer: open

#25353 fastfetch: update to 2.21.3 for legacy systems
  sysutils/fastfetch/Portfile
  sysutils/fastfetch/files/0001-Support-hostinfo-for-PowerPC-Macs.patch
  sysutils/fastfetch/files/0002-version.c-add-a-missing-macro-for-powerpc.patch
  sysutils/fastfetch/files/0003-Support-PowerPC-CPU-detection.patch
  sysutils/fastfetch/files/0004-gpu_apple.m-unbreak-for-10.11.patch
  sysutils/fastfetch/files/0005-memory_apple-fix-for-32-bit.patch
  sysutils/fastfetch/files/0005-monitor_apple.m-no-HDR-before-10.11.patch
  sysutils/fastfetch/files/0006-opengl_apple.c-fix-for-10.7.patch
  sysutils/fastfetch/files/0007-sound_apple.c-fix-for-10.8.patch
  sysutils/fastfetch/files/0008-gpu_apple.c-fix-for-old-systems.patch
  sysutils/fastfetch/files/0009-camera_apple.m-unbreak-for-10.7.patch
  sysutils/fastfetch/files/0010-brightness_apple.c-add-a-missing-include.patch
  sysutils/fastfetch/files/0011-os_apple.m-etc.-fix-syntax-for-plists.patch
  sysutils/fastfetch/files/0012-Fix-PowerPC-macros.patch
  sysutils/fastfetch/files/0012-osascript.m-fix-syntax.patch
  sysutils/fastfetch/files/0013-disk_bsd-no-support-for-creation-time.patch
  sysutils/fastfetch/files/0014-yyjson-PowerPC-macros.patch
  sysutils/fastfetch/files/0015-Support-PowerPC-CPU-detection.patch
  sysutils/fastfetch/files/0015-monitor_apple.m-no-HDR-before-10.11.patch
  sysutils/fastfetch/files/0016-Fix-autorelease-pools.patch
  sysutils/fastfetch/files/0017-CMakeLists-adjust-for-legacy-macOS.patch
  sysutils/fastfetch/files/0018-Fix-compatibility-with-10.4.patch
  sysutils/fastfetch/files/0019-Revert-some-breakages.patch
  sysutils/fastfetch/files/0020-Tiger-specific-adjustments-to-CMakeLists.patch
Labels: type: update, maintainer: open

#25354 shadowsocks-rust: update to v1.20.4
  net/shadowsocks-rust/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#25356 osxphotos: update to 0.68.5
  graphics/osxphotos/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#25359 got: update to 0.102
  devel/got/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer, maintainer: open

#25318 getmail6: New port.
  mail/getmail/Portfile
  mail/getmail6/Portfile
  mail/getmail6/files/0001-pop3-Support-use_xoauth2.patch
Labels: type: enhancement, type: submission, maintainer: none

#25272 docker-compose-plugin: update to version 2.29.1
  devel/docker-compose-plugin/Portfile
Labels: type: update, maintainer: open

#25265 libheif: build with kvazaar instead of x265
  multimedia/libheif/Portfile
Labels: type: enhancement, maintainer: open, by: member

#25363 uxn: update to 20240812
  emulators/uxn/Portfile
Labels: type: update, maintainer: none

#23620 qt6-qtbase: Fix build with CMake 3.28
  aqua/qt6/Portfile
  aqua/qt6/files/patch-qtbase-fix-cmake-3.28.diff
Labels: type: bugfix, maintainer: open

#25365 uv: Update to 0.2.37
  devel/uv/Portfile
Labels: type: update, maintainer, maintainer: open

#25364 ruff: Update to 0.6.1
  devel/ruff/Portfile
Labels: type: update, maintainer, maintainer: open

#25330 shtools: non-functional: path-style dep on OpenBLAS
  science/shtools/Portfile
Labels: maintainer: requires approval, maintainer: timeout

#25334 zmqpp: needs C++11
  devel/zmqpp/Portfile
Labels: type: bugfix, maintainer: open

#25369 tree-sitter-go: fix build on older systems after update
  devel/tree-sitter-go/Portfile
Labels: type: bugfix, maintainer: open

#25367 oh-my-posh: update to version 23.6.3
  sysutils/oh-my-posh/Portfile
Labels: type: update, maintainer, maintainer: open

#25370 pika: update to 0.27.0
  devel/pika/Portfile
Labels: type: update, maintainer, maintainer: open

#25371 libpqxx: update to 7.9.2
  databases/libpqxx/Portfile
Labels: type: enhancement, type: update, maintainer: none

#25366 astyle: update to 3.6
  devel/astyle/Portfile
Labels: type: update, maintainer: none

#24850 xdg-utils: Update to 1.2.1
  sysutils/xdg-utils/Portfile
  sysutils/xdg-utils/files/patch-xdg-realpath.diff
Labels: type: enhancement, type: update, maintainer: none

#25375 maven3: update to 3.9.9
  java/maven3/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#25186 openjdk8-powerpc: new port to support modern Java on PowerPC
  java/openjdk8-powerpc/Portfile
  java/openjdk8-powerpc/files/0001-Fix-timebomb-bug-in-GenerateCurrencyData.patch
  java/openjdk8-powerpc/files/0002-Ignore-__NSAutoreleaseNoPool-errors.patch
  java/openjdk8-powerpc/files/0003-os_perf_bsd-allow-to-compile-with-ZERO-CPU.patch
  java/openjdk8-powerpc/files/0004-Added-macosx-bin-zero-jvm.cfg.patch
  java/openjdk8-powerpc/files/0005-ExtendedOptionsImpl.c-define-TCP_KEEPINTVL-and-TCP_K.patch
  java/openjdk8-powerpc/files/0006-Revert-8211301-macos-support-full-window-content-opt.patch
  java/openjdk8-powerpc/files/0007-Provide-definition-of-__private_extern__-where-undef.patch
  java/openjdk8-powerpc/files/0008-8181503-Can-t-compile-hotspot-with-c-11.patch
  java/openjdk8-powerpc/files/0009-Disable-C-11-warnings.patch
  java/openjdk8-powerpc/files/1001-os_bsd_zero.cpp-implement-sync_val_compare_and_swap_.patch
  java/openjdk8-powerpc/files/1002-CoreLibraries.gmk-do-not-hardcode-arch.patch
  java/openjdk8-powerpc/files/1003-java_md_macosx-fix-broken-ObjC-code.patch
  java/openjdk8-powerpc/files/1004-os_bsd-add-ppc64-case.patch
  java/openjdk8-powerpc/files/1005-jniTypes_ppc-downgrade-error-to-warning.patch
  java/openjdk8-powerpc/files/1006-os_bsd.cpp-fix-vm_statistics.patch
  java/openjdk8-powerpc/files/1007-Awt2dLibraries-add-fnested-functions.patch
  java/openjdk8-powerpc/files/1008-java_md_macosx.c-define-preferredJVM.patch
  java/openjdk8-powerpc/files/1009-os_bsd.cpp-allow-headless-on-Apple.patch
  java/openjdk8-powerpc/files/1010-Makefile-fix-LP64-define.patch
  java/openjdk8-powerpc/files/1011-No-dtrace-for-now.patch
  java/openjdk8-powerpc/files/1012-toolchain.m4-hack-around-a-broken-Xcode-version-dete.patch
  java/openjdk8-powerpc/files/1013-os_bsd.cpp-fix-running-VM.patch
  java/openjdk8-powerpc/files/1014-portconfig-try-fix-broken-pipe.patch
  java/openjdk8-powerpc/files/1015-Some-hacks-to-fix-the-build-for-powerpc.patch
Labels: type: submission

#25380 gng: update to 1.0.5
  java/gng/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#25378 clifm: update to 1.20
  sysutils/clifm/Portfile
Labels: type: update, maintainer: open

#25384 mise: Upgrade to 2024.8.8
  sysutils/mise/Portfile
Labels: maintainer, maintainer: open

#25385 atomvm: update to 0.6.4
  erlang/atomvm/Portfile
Labels: type: update, maintainer, maintainer: open

#25383 mkconsole: backport fix from upstream for older systems
  aqua/mkconsole/Portfile
  aqua/mkconsole/files/2ed541237808b584962cb0ae7485ee3d31a1ca45.patch
Labels: type: bugfix, maintainer: none

#25379 nnn: fix for older systems
  sysutils/nnn/Portfile
  sysutils/nnn/files/0001-Drop-a-defunct-fallback.patch
Labels: type: bugfix, maintainer: open
