Repository macports/macports-ports, pull requests merged in 2024-01, with the labels that each got.

#22005 gvisor-tap-vsock: update to 0.7.1, add @catap as co-maintainer
  net/gvisor-tap-vsock/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#22007 toot: update to 0.40.2
  net/toot/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer: open

#22014 qgit: use Qt5 on new systems
  devel/qgit/Portfile
Labels: type: enhancement, maintainer, maintainer: open

#22008 initool: update to 0.14.1
  sysutils/initool/Portfile
Labels: type: update, maintainer, maintainer: open

#22015 TeXShop: restore version for old systems
  aqua/TeXShop/Portfile
  aqua/TeXShop/files/lilypond.engine
  aqua/TeXShop/files/patch-TSDocument.m.diff
Labels: type: bugfix, maintainer: open

#22021 fish: update to 3.7.0; adopt
  shells/fish/Portfile
Labels: type: bugfix, type: enhancement, type: update, type: security fix, maintainer: none

#22006 ntpsec: update to 1.2.3
  sysutils/ntpsec/Portfile
  sysutils/ntpsec/files/patch-allfixes.diff
Labels: type: update, maintainer, maintainer: open

#21991 libcxx-powerpc: add emutls support, install into libexec
  lang/libcxx-powerpc/Portfile
  lang/libcxx-powerpc/files/0014-libcxxabi-support-emutls.patch
  lang/libcxx-powerpc/files/0015-implement-atomic-using-mutex-lock_guard-for-64b-ops-.patch
Labels: type: enhancement, maintainer, maintainer: open

#22012 osxphotos: update to 0.67.2
  graphics/osxphotos/Portfile
Labels: type: update, maintainer, maintainer: open

#22013 mvnd: fix download location
  java/mvnd/Portfile
Labels: type: bugfix, maintainer, maintainer: open

#21998 QtPass: add a version for Qt4
  aqua/QtPass/Portfile
  aqua/QtPass/files/0001-qtpass.pro-remove-a-breaking-setting.patch
Labels: type: bugfix, maintainer: none

#21999 gscan2pdf: add missing dependency to p5-data-uuid
  graphics/gscan2pdf/Portfile
Labels: type: bugfix, maintainer: none

#22019 tor-devel: update to 0.4.8.10
  security/tor-devel/Portfile
Labels: type: update, maintainer: none

#22020 fontforge: provide version for 32-bit and old OS
  graphics/fontforge/Portfile
  graphics/fontforge/files/patch-fontforge-carbon-gettime-namecollision.diff
  graphics/fontforge/files/patch-fontforge-startui-SRefCon-tiger.diff
  graphics/fontforge/files/patch-fontforge-startui-require-noerr.diff
Labels: type: bugfix, maintainer: none

#21961 qt(59|511|513|5)-qtlocation: `conflicts_build rapidjson rapidjson-devel`
  aqua/qt5/Portfile
  aqua/qt511/Portfile
  aqua/qt513/Portfile
  aqua/qt59/Portfile
Labels: type: bugfix, maintainer: open

#21997 openexr2: update to 2.5.10, drop now unneeded patch
  graphics/openexr2/Portfile
  graphics/openexr2/files/patch-macOS-use-libdispatch-only-where-available.diff
Labels: type: update, maintainer: open

#22022 symfony-cli: update to 5.7.8
  devel/symfony-cli/Portfile
Labels: type: update, maintainer, maintainer: open

#22023 tinyxml2: update to 10.0.0
  textproc/tinyxml2/Portfile
Labels: type: update, maintainer, maintainer: open

#21986 qt6-qtdeclarative: Fix building with Xcode 11.3
  aqua/qt6/Portfile
  aqua/qt6/files/patch-qtdeclarative-xcode11.3.diff
Labels: type: bugfix, maintainer: open

#21628 qt6-qtbase: Fix finding qt6 with cmake find_package
  aqua/qt6/Portfile
Labels: type: bugfix, maintainer: open

#21988 qt6-qtpositioning: Fix building on MacOS 10.14 SDK
  aqua/qt6/Portfile
  aqua/qt6/files/patch-qtpositioning-macos_10.14_sdk.diff
Labels: type: bugfix, maintainer: open

#21972 qt(59|511)-qtscript: allow C++20 compilers to work
  aqua/qt511/Portfile
  aqua/qt59/Portfile
Labels: type: bugfix, maintainer: open

#22025 py-pygraphviz: update to version 1.11
  python/py-pygraphviz/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#22026 py-psycopg2: update to 2.9.9
  python/py-psycopg2/Portfile
Labels: type: enhancement, type: update, maintainer: open

#21982 qt(59|511|513)-qtlocation: add missing header include
  aqua/qt511/Portfile
  aqua/qt511/files/patch-qtlocation-mbgl-unique_any.hpp.diff
  aqua/qt513/Portfile
  aqua/qt513/files/patch-qtlocation-mbgl-unique_any.hpp.diff
  aqua/qt59/Portfile
  aqua/qt59/files/patch-qtlocation-mbgl-unique_any.hpp.diff
Labels: type: bugfix, maintainer: open

#21980 ddptools: new submission
  audio/ddptools/Portfile
Labels: type: submission

#22029 SuiteSparse: fix build on 10.6 and earlier
  math/SuiteSparse/Portfile
  math/SuiteSparse/files/patch-KLU-Include-klu_version.h.diff
Labels: maintainer: open

#22027 astyle: update to 3.4.10
  devel/astyle/Portfile
Labels: type: update, maintainer: none

#21987 qt6-qtmultimedia: Fix building on 10.14 SDK
  aqua/qt6/Portfile
  aqua/qt6/files/patch-qtmultimedia-macos_10.14_sdk.diff
Labels: type: bugfix, maintainer: open

#21989 qt6-qtspeech: Fix building with MacOS 10.14 SDK
  aqua/qt6/Portfile
  aqua/qt6/files/patch-qtspeech-macos_10.14_sdk.diff
Labels: type: bugfix, maintainer: open

#22017 Updated verilator from 5.018 to 5.020
  science/verilator/Portfile
Labels: type: update, maintainer: open

#22028 tinyproxy: fix startupitem
  net/tinyproxy/Portfile
Labels: type: bugfix, type: enhancement, maintainer: none

#22033 ddptools: fix supported_archs
  audio/ddptools/Portfile
Labels: maintainer, maintainer: open

#22030 barman: use python312
  databases/barman/Portfile
Labels: type: enhancement, maintainer, maintainer: open

#22032 arghandler: fix install location of CMake config files
  devel/arghandler/Portfile
  devel/arghandler/files/0002-CMakeLists-fix-installation-on-macOS.patch
Labels: type: bugfix, maintainer, maintainer: open

#22035 weechat: update to 4.1.2
  irc/weechat/Portfile
Labels: type: update, maintainer, maintainer: open

#22009 py-postgresql: update to 1.3.0
  python/py-postgresql/Portfile
Labels: type: enhancement, type: update, maintainer: none

#22039 ruby-devel: update to 2023.01.04 and branch 3.4
  lang/ruby-devel/Portfile
  lang/ruby-devel/files/ruby33
  lang/ruby-devel/files/ruby34
  lang/ruby33/Portfile
Labels: type: update, maintainer: open

#22043 clojure: update to 1.11.1.1435
  lang/clojure/Portfile
Labels: type: update, maintainer, maintainer: open

#22011 EqualX: new port in tex
  tex/EqualX/Portfile
  tex/EqualX/files/patch-DialogPreferences.cpp.diff
  tex/EqualX/files/patch-MainWindow.cpp.diff
  tex/EqualX/files/patch-defines.h.diff
  tex/EqualX/files/patch-equalx.pro.diff
Labels: type: submission

#20729 ldid-procursus: Restrict building on < OSX 10.13
  devel/ldid-procursus/Portfile
Labels: type: bugfix, maintainer: open

#22048 userspace-rcu: fix powerpc, use right cxx_stadard, enable tests
  devel/userspace-rcu/Portfile
  devel/userspace-rcu/files/0001-ppc.h-use-mftb-on-ppc.patch
  devel/userspace-rcu/files/0002-ppc.h-use-correct-cacheline-size-for-macOS.patch
Labels: type: bugfix, type: enhancement, maintainer: open

#22047 chrony: update to 4.5
  sysutils/chrony/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer: none

#22031 proxmark3-iceman: update to v4.17768
  science/proxmark3-iceman/Portfile
Labels: type: update, maintainer, maintainer: open

#22053 argtable3: fix build with old gcc, enable tests
  devel/argtable3/Portfile
  devel/argtable3/files/patch-gcc-4.diff
Labels: type: bugfix, type: enhancement, maintainer: open

#22054 blisp: fix build on older OS and with gcc
  sysutils/blisp/Portfile
  sysutils/blisp/files/0001-blisp_struct.h-use-_Static_assert-for-pre-C23-compat.patch
  sysutils/blisp/files/0002-parse_file.h-include-sys-types.h.patch
Labels: type: bugfix, maintainer: open

#22059 micronaut: update to 4.2.3
  java/micronaut/Portfile
Labels: type: update, maintainer, maintainer: open

#22024 fltk: update to 1.3.9
  aqua/fltk/Portfile
Labels: type: update, maintainer: open, by: member

#22058 hyfetch: Upgrade to Python 3.12
  python/hyfetch/Portfile
Labels: maintainer: open

#21875 py-scipy: update to 1.11.4; fix build on old systems
  python/py-scipy/Portfile
  python/py-scipy/files/patch-allow-MP-boost-1.10.diff
  python/py-scipy/files/patch-allow-MP-boost.diff
  python/py-scipy/files/patch-ckdtree-fix-isinf-1.10.diff
  python/py-scipy/files/patch-ckdtree-fix-isinf.diff
  python/py-scipy/files/patch-macosx-version-min.diff
  python/py-scipy/files/patch-special-fix-isnan-isinf.diff
Labels: type: bugfix, type: update, maintainer: open

#22060 eigen3-devel: update to 20240104
  math/eigen3/Portfile
Labels: type: update, maintainer, maintainer: open

#22061 net/wireshark4: revbump to 4.2.1
  net/wireshark4/Portfile
Labels: maintainer, by: member

#21707 clamav-server: Update to clamd version 1.2.1; Add proxy_settings variant
  sysutils/clamav-server/Portfile
  sysutils/clamav-server/files/patch-etc-clamd-conf-macports.diff
  sysutils/clamav-server/files/patch-etc-freshclam-conf-macports.diff
Labels: type: enhancement, type: update, maintainer, maintainer: open

#22055 EqualX: fix install on case-sensitive OS
  tex/EqualX/Portfile
  tex/EqualX/files/patch-defines.h.diff
Labels: type: bugfix, maintainer, maintainer: open

#22036 libssh: update to 0.10.6
  devel/libssh/Portfile
Labels: type: update, type: security fix, maintainer: open

#22064 icu: update to 73.2
  devel/icu/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#22068 trdsql: update to 0.20.0
  textproc/trdsql/Portfile
Labels: type: enhancement, type: update, maintainer: open

#22070 putty: update to 0.80
  security/putty/Portfile
  security/putty/files/sftpserver.c.patch
Labels: type: update, maintainer: none

#22040 catch2: update to 3.5.1
  devel/catch2/Portfile
Labels: type: update, maintainer: open

#22069 proftpd: update to 1.3.8b
  net/proftpd/Portfile
Labels: type: update, maintainer: none

#22071 net/wireshark4: revbump to 4.2.2
  net/wireshark4/Portfile
Labels: maintainer, by: member

#22067 *: use a path-style dependency on curl-ca-bundle
  mail/offlineimap/Portfile
  net/openntpd/Portfile
Labels: type: bugfix, maintainer: open

#22050 atomvm: set correct c_standard, fix build on older macOS
  erlang/atomvm/Portfile
Labels: type: bugfix, maintainer: open

#22074 jenkins: update to 2.426.2
  devel/jenkins/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#22075 metabase: update to 0.48.2
  databases/metabase/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#22077 tippecanoe: update to 2.40.0
  gis/tippecanoe/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#22045 yabai: update to version 6.0.4
  sysutils/yabai/Portfile
Labels: type: enhancement, type: update, maintainer: open

#22038 libjxl: unbreak build on systems which need __STDC_FORMAT_MACROS
  graphics/libjxl/Portfile
  graphics/libjxl/files/STDC_FORMAT_MACROS.patch
Labels: type: bugfix, maintainer: requires approval, maintainer: timeout

#22041 rocksdb: update to 8.9.1
  databases/rocksdb/Portfile
  databases/rocksdb/files/0001-rocksdb-fixes-for-macOS-PPC.patch
Labels: type: update, maintainer: open

#22044 pipenv: update to 2023.11.15
  python/pipenv/Portfile
Labels: type: enhancement, type: update, maintainer: open

#22083 py-mako: add py312 support
  python/py-mako/Portfile
Labels: type: enhancement, maintainer: open

#22084 gmt6: update to 6.5.0
  science/gmt5/Portfile
Labels: type: update, maintainer: open

#22091 alacritty: update to 0.13.1
  aqua/alacritty/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer: open

#22081 py-llfuse: update to 1.5.0
  python/py-llfuse/Portfile
Labels: type: enhancement, type: update, maintainer: none

#22088 emacs{,-app}-devel: update to 20240108
  editors/emacs/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#22080 py-pythran: update to 0.15.0
  python/py-pythran/Portfile
  python/py-pythran/files/patch-xsimd_scalar.hpp-fix-for-missing-__exp10-on-macOS.diff
Labels: type: enhancement, type: update, maintainer: open

#22092 tlrc: new port (1.8.0)
  net/tlrc/Portfile
Labels: type: submission

#22096 symfony-cli: update to 5.8.0
  devel/symfony-cli/Portfile
Labels: type: update, maintainer, maintainer: open

#22099 roundcubemail: update to 1.6.5
  www/roundcubemail/Portfile
Labels: type: update, type: security fix, maintainer: none

#22100 dnscrypt-proxy: update to 2.1.5
  net/dnscrypt-proxy/Portfile
Labels: type: update, maintainer: none

#22102 emacs{,-app}-devel: update tree-sitter dependencies
  editors/emacs/Portfile
Labels: type: enhancement, type: update, maintainer: open, by: member

#22101 google-cloud-sdk: update to 459.0.0
  devel/google-cloud-sdk/Portfile
Labels: type: update, maintainer, maintainer: open

#22097 gperftools: update to 2.15, fix tests target for CMake build, drop Rosetta patch
  devel/gperftools/Portfile
  devel/gperftools/files/patch-check_address_test.cc-missed-MAP_ANON-fix.diff
  devel/gperftools/files/patch-cmake-arm64-detect.diff
  devel/gperftools/files/patch-malloc_bench-random_shuffle.diff
  devel/gperftools/files/patch-rosetta.diff
Labels: type: bugfix, type: update, maintainer: none

#22103 maven3: mark platforms as "any"
  java/maven3/Portfile
Labels: type: enhancement, maintainer: open, by: member

#22109 lfortran: update to 0.30.0
  lang/lfortran/Portfile
  lang/lfortran/files/patch-use-sane-install-dirs.diff
Labels: type: update, maintainer, maintainer: open

#22112 symfony-cli: update to 5.8.1
  devel/symfony-cli/Portfile
Labels: type: update, maintainer, maintainer: open

#22113 crystal: update to 1.11.0
  lang/crystal/Portfile
Labels: type: update, maintainer, maintainer: open

#22076 kafkacat: rename to kcat and update to 1.7.1
  net/kafkacat/Portfile
  net/kcat/Portfile
Labels: type: enhancement, type: submission, maintainer: open

#21948 gnucash: use_mp_libcxx on older macos
  gnome/gnucash/Portfile
Labels: type: bugfix, maintainer: open

#22111 gpac: fix build on sonoma
  multimedia/gpac/Portfile
Labels: type: bugfix, maintainer, maintainer: open

#22119 borgbackup: Add missing py-cython dependency
  sysutils/borgbackup/Portfile
Labels: type: bugfix, maintainer: open, by: member

#22117 po4a: update to 0.69
  textproc/po4a/Portfile
Labels: type: bugfix, type: update, maintainer: none

#22120 fricas: update to version 3.10
  math/fricas/Portfile
Labels: type: update, maintainer, maintainer: open

#22122 include-what-you-use: update to 0.21
  devel/include-what-you-use/Portfile
Labels: type: update, maintainer, maintainer: open

#22121 onetbb: update to 2021.11.0
  devel/onetbb/Portfile
  devel/onetbb/files/patch-cmake-compilers.diff
Labels: type: update, maintainer, maintainer: open

#22079 py-netcdf4: Add py312 subport
  python/py-netcdf4/Portfile
Labels: type: enhancement, maintainer: open

#22078 py-xarray: Update to 2023.12.0
  python/py-xarray/Portfile
Labels: type: update, maintainer: open

#22126 bento4: update to 1.6.0-641
  multimedia/bento4/Portfile
Labels: type: update, maintainer, maintainer: open

#22125 cpprestsdk: update to 2.10.19
  www/cpprestsdk/Portfile
Labels: type: update, maintainer, maintainer: open

#22123 odin: update to 0.2024.01
  lang/odin/Portfile
  lang/odin/files/patch-build.diff
  lang/odin/files/patch-raylib.diff
Labels: type: update, maintainer, maintainer: open

#22124 chez-scheme: update to 9.6.4
  lang/chez-scheme/Portfile
  lang/chez-scheme/files/patch-compile.diff
Labels: type: update, maintainer, maintainer: open

#22118 golangci-lint: update to 1.55.2
  devel/golangci-lint/Portfile
Labels: type: enhancement, type: update, maintainer: open

#22089 py-socks: add python 3.12 support
  python/py-socks/Portfile
Labels: type: enhancement, maintainer: open

#22087 gobject-introspection: change to Python 3.12
  gnome/gobject-introspection/Portfile
Labels: type: enhancement, maintainer: open

#22086 boost176: add py312 support
  devel/boost176/Portfile
Labels: type: enhancement, maintainer: open

#22085 ninja: bump Python from 3.11 to 3.12
  devel/ninja/Portfile
Labels: type: enhancement, maintainer: open

#22094 py*-tiktoken: new port
  python/py-tiktoken/Portfile
  python/py-tiktoken/files/test_misc.diff
  python/py-tiktoken/files/test_simple_public.diff
Labels: type: enhancement, type: submission

#22090 gallery-dl: update to 1.26.6
  net/gallery-dl/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer, maintainer: open

#22131 onetbb: fix 32-bit builds (i386 / ppc)
  devel/onetbb/files/patch-onetbb-older-platforms.diff
Labels: type: bugfix, maintainer: open

#22132 Aseprite: Update to 1.3.2
  graphics/Aseprite/Portfile
  graphics/Aseprite/files/DEPS.patch
  graphics/Aseprite/files/USE_SHARED_LIBARCHIVE.patch
  graphics/Aseprite/files/USE_SHARED_LIBWEBP.patch
  graphics/Aseprite/files/git-sync-deps.patch
Labels: type: update, maintainer, maintainer: open, by: member

#22135 snac: update to 2.44
  net/snac/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer, maintainer: open

#22134 macos-fortress: Bugfix, typo
  net/macos-fortress/Portfile
  net/macos-fortress/files/privoxy-config.macports
  net/macos-fortress/files/privoxy-config.patch
Labels: type: bugfix, maintainer, maintainer: open

#22098 discount: update to 2.2.7d, add homepage
  textproc/discount/Portfile
Labels: type: update, maintainer: open

#22136 dispenso: new port in devel
  devel/dispenso/Portfile
  devel/dispenso/files/0001-platform.h-add-cpuRelax-for-PowerPC-and-ARM.patch
  devel/dispenso/files/0002-no-werror.patch
Labels: type: submission

#22137 virt-manager: use python312
  gnome/virt-manager/Portfile
Labels: type: enhancement, maintainer: none

#22138 onetbb: fix building tbbbind
  devel/onetbb/Portfile
Labels: type: bugfix, maintainer, maintainer: open

#22115 saga: update to 9.3.0 and new py*-pysaga subports
  gis/saga/Portfile
Labels: type: update, maintainer, maintainer: open

#22107 pg_rman: new port (version 1.3.16)
  databases/pg_rman/Portfile
  databases/pg_rman/files/patch-Makefile-pg_config.diff
Labels: type: submission, by: member

#22049 py-spopt: update to 0.6.0
  python/py-spopt/Portfile
Labels: type: update, maintainer: none

#22143 wgshadertoy: update to 0.3.3
  graphics/wgshadertoy/Portfile
Labels: type: update, maintainer, maintainer: open

#22145 fpm: update to 0.10.0
  devel/fpm/Portfile
  devel/fpm/files/patch-install.diff
Labels: type: update, maintainer, maintainer: open

#22146 toml-f: update to 0.4.2
  fortran/toml-f/Portfile
Labels: type: update, maintainer, maintainer: open

#22127 py-tox: update to 4.11.4, drop py37, add py312 subports
  python/py-tox/Portfile
  python/py-tox/files/tox312
Labels: type: update, maintainer: open, by: member

#21783 py-zmq: upgrade to version 25.1.2, add py312
  python/py-zmq/Portfile
Labels: maintainer: open

#22148 cppcheck: update to 2.13.1
  devel/cppcheck/Portfile
Labels: type: update, maintainer: open

#22147 watchman: revbump after folly update, use libfmt10
  sysutils/watchman/Portfile
Labels: type: bugfix, maintainer: open

#22149 dbcsr: update to 2.6.0, fix the port
  math/dbcsr/Portfile
Labels: type: bugfix, type: update, maintainer, maintainer: open

#22150 py-pygmt: Add Python 3.12 subport
  python/py-pygmt/Portfile
Labels: type: enhancement, maintainer: none

#22151 adblock2privoxy: Fix documentation
  www/adblock2privoxy/Portfile
Labels: maintainer, maintainer: open

#22156 fortran-stdlib: update to 2024.01.09
  lang/fortran-stdlib/Portfile
Labels: type: update, maintainer, maintainer: open

#22154 pipx: update to 1.4.2
  python/pipx/Portfile
Labels: type: update, maintainer, maintainer: open

#22155 libretroshare: update to 2023.12.27
  net/libretroshare/Portfile
Labels: type: update, maintainer, maintainer: open

#22153 feh: update to 3.10.2
  graphics/feh/Portfile
Labels: type: update, maintainer: none

#22158 rb-curses: new port in Ruby
  ruby/rb-curses/Portfile
Labels: type: submission

#22163 adblock2privoxy: Update PKI example
  www/adblock2privoxy/Portfile
  www/adblock2privoxy/files/openssl.cnf
Labels: type: update, maintainer, maintainer: open

#22162 privoxy: Update PKI documentation, example
  www/privoxy/Portfile
  www/privoxy/files/openssl.cnf
Labels: type: update, maintainer, maintainer: open

#22160 arduino-cli: update to 0.35.0
  devel/arduino-cli/Portfile
Labels: type: update, maintainer: open

#22167 stern: update to 1.28.0
  sysutils/stern/Portfile
Labels: type: update, maintainer, maintainer: open

#22166 skaffold: update to 2.10.0
  devel/skaffold/Portfile
Labels: type: update, maintainer, maintainer: open

#22139 SuiteSparse: update to 7.5.1
  math/SuiteSparse/Portfile
Labels: type: update, maintainer: open

#22141 MoltenVK-latest: Update to 1.2.7
  graphics/MoltenVK/Portfile
Labels: type: update, maintainer: open

#22168 py-beancount: revert pep517 change
  python/py-beancount/Portfile
Labels: type: bugfix, maintainer, maintainer: open

#22179 openssl3: Fix CVE-2023-6237
  devel/openssl3/Portfile
  devel/openssl3/files/0b0f7abfb37350794a4b8960fafc292cd5d1b84d.patch
  devel/openssl3/files/a830f551557d3d66a84bbb18a5b889c640c36294.patch
Labels: maintainer, type: security fix, maintainer: open, by: member

#22170 boost171 boost178 boost181: add py312 support
  devel/boost171/Portfile
  devel/boost178/Portfile
  devel/boost181/Portfile
Labels: type: enhancement, maintainer: open

#22178 rb-rake: update to 13.1.0
  ruby/rb-rake/Portfile
Labels: type: update, maintainer: none

#21994 x2goclient: restore Qt4 version, unbreak the build for macOS < 10.7
  aqua/x2goclient/Portfile
  aqua/x2goclient/files/patch-unbreak-gcc.diff
Labels: type: bugfix, maintainer: open

#22186 samba4: Update to 4.19.4, use Python 3.12
  net/samba4/Portfile
Labels: type: update, maintainer: none, by: member

#22165 osxphotos: update to 0.67.3
  graphics/osxphotos/Portfile
Labels: type: update, maintainer, maintainer: open

#22189 tilemaker: update to 3.0.0
  gis/tilemaker/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#22157 turbo: new port in editors
  editors/turbo/Portfile
Labels: type: submission
