Repository macports/macports-ports, pull requests merged in 2024-06, with the labels that each got.

#24240 ruff: Update 0.4.7
  devel/ruff/Portfile
Labels: type: update, maintainer, maintainer: open

#24242 mactop: write log file in $prefix/var/log
  sysutils/mactop/Portfile
Labels: type: bugfix, maintainer: open, by: member

#24243 dagger: update to 0.11.6
  devel/dagger/Portfile
Labels: type: update, maintainer: open

#24246 cminpack: update to 1.3.9
  math/cminpack/Portfile
Labels: type: update, maintainer, maintainer: open

#24249 git: update to 2.45.2
  devel/git/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#24252 cava: avoid opengl on old macOS
  audio/cava/Portfile
Labels: type: bugfix, maintainer: open

#24224 mc: remove build workaround for macOS 10.13 (High Sierra)
  sysutils/mc/Portfile
Labels: type: enhancement, maintainer: none

#24251 lfortran: update to 0.36.0
  lang/lfortran/Portfile
Labels: type: update, maintainer, maintainer: open

#24228 asciidoctor: update to 2.0.33
  textproc/asciidoctor/Portfile
Labels: type: update, maintainer: open, by: member

#24255 g-ls: Update to 0.28.2
  sysutils/g-ls/Portfile
Labels: type: update, maintainer, maintainer: open

#24253 ipsw: Update to 3.1.485
  security/ipsw/Portfile
Labels: type: update, maintainer, maintainer: open

#24231 wxMaxima: fix for old systems and powerpc
  math/wxMaxima/Portfile
  math/wxMaxima/files/patch-no-bundle.diff
Labels: type: bugfix, maintainer: requires approval

#24154 vdt: unbreak build on powerpc
  math/vdt/Portfile
Labels: type: bugfix, maintainer: open

#24256 ncmpcpp: switch to boost181 to fix gcc build, revbump
  audio/ncmpcpp/Portfile
Labels: type: bugfix, maintainer: none

#24189 yt-dlp: update to 2024.05.27
  net/youtube-dl/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer: requires approval

#24191 npm portgroup: use latest LTS release for default
  _resources/port1.0/group/npm-1.0.tcl
  devel/bash-language-server/Portfile
  devel/eask-cli/Portfile
  devel/pnpm/Portfile
  devel/pyright/Portfile
  devel/typescript-language-server/Portfile
  security/bitwarden-cli/Portfile
Labels: type: enhancement, maintainer: open

#24225 codeblocks-devel: fix for systems building with gcc using `libstdc++`
  devel/codeblocks-devel/Portfile
Labels: type: bugfix, maintainer: none

#24177 ocaml-dune: update to 3.15.3
  ocaml/ocaml-dune/Portfile
Labels: type: enhancement, type: update, type: submission, maintainer: open

#24261 openjdk17-openj9: update to 17.0.11
  java/openjdk17-openj9/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#24260 openjdk21-openj9: update to 21.0.3
  java/openjdk21-openj9/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#24262 openjdk11-openj9: update to 11.0.23
  java/openjdk11-openj9/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#24264 openjdk8-openj9: update to 8u412
  java/openjdk8-openj9/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#24265 google-cloud-sdk: update to 478.0.0
  devel/google-cloud-sdk/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#24258 rgb-tui: new port
  graphics/rgb-tui/Portfile
  graphics/rgb-tui/files/patch-CMakeLists.diff
Labels: type: submission

#24257 yggdrasil-go: update to 0.5.6
  net/yggdrasil-go/Portfile
Labels: type: update, maintainer: open

#24269 oh-my-posh: update to version 21.1.0
  sysutils/oh-my-posh/Portfile
Labels: type: update, maintainer, maintainer: open

#24267 gtk-fortran: new port
  fortran/gtk-fortran/Portfile
Labels: type: submission

#24064 vips: updated to 8.15.2, added libarchive to support vips dzsave and fixed macos-14 compilation
  graphics/vips/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer: open

#24208 rsgislib: revbump for gsl update and use boost181 to fix gcc build
  gis/rsgislib/Portfile
Labels: type: bugfix, maintainer: open

#24216 terraform-docs: update to 0.17.0
  devel/terraform-docs/Portfile
Labels: type: update, maintainer: open, by: member

#24219 e2fsprogs: update to 1.47.1
  sysutils/e2fsprogs/Portfile
  sysutils/e2fsprogs/files/patch_xlocale_h.diff
Labels: type: update, maintainer: open, by: member

#24207 sqlcipher: update to 4.6.0
  databases/sqlcipher/Portfile
Labels: type: update, maintainer: open

#24150 Submission: Bun
  devel/bun/Portfile
Labels: type: submission

#24124 newsraft: update to 0.24
  net/newsraft/Portfile
  net/newsraft/files/patch-makefile.diff
Labels: type: bugfix, type: update, maintainer: open

#24082 mariadb: fix build on powerpc and Sonoma
  databases/mariadb/Portfile
  databases/mariadb/files/patch-powerpc.diff
Labels: type: bugfix, maintainer: open

#24088 kate: fix compiler choice
  kde/kate/Portfile
Labels: type: bugfix, maintainer: none

#24234 LimeChat: sign app bundle on 13.0 and later
  aqua/LimeChat/Portfile
Labels: type: enhancement, maintainer: open, by: member

#24272 pipx: update to 1.6.0
  python/pipx/Portfile
Labels: type: update, maintainer, maintainer: open

#24247 ccache: update to 4.10
  devel/ccache/Portfile
Labels: type: update, maintainer: open

#24273 nghttp2: Remove C++20 requirement and don't autoreconf anymore
  www/nghttp2/Portfile
Labels: maintainer: open, by: member

#24280 ruby-devel: update to 2024.06.03
  lang/ruby-devel/Portfile
Labels: type: update, maintainer, maintainer: open

#24278 just-fast: use legacysupport for filesystem with libc++
  sysutils/just-fast/Portfile
Labels: type: bugfix, maintainer, maintainer: open

#24227 wxGTK-3.0: fix for a missing header bug
  graphics/wxWidgets-3.0/Portfile
  graphics/wxWidgets-3.0/files/patch-no-osx-evtloopsrc.h.diff
Labels: type: bugfix, maintainer: open

#24276 FAudio: update to 24.06
  audio/FAudio/Portfile
Labels: type: update, maintainer, maintainer: open

#24277 alacenc: update to 0.4.1, drop now unneeded patches
  audio/alacenc/Portfile
  audio/alacenc/files/0001-Make-endianness-check-actually-work.patch
  audio/alacenc/files/0002-atoms.cpp-fix-a-type.patch
Labels: type: update, maintainer, maintainer: open

#23918 pika: update to 0.25.0
  devel/pika/Portfile
Labels: type: update, maintainer, maintainer: open

#24012 sdcc: use -stdlib= only for clang
  lang/sdcc/Portfile
Labels: type: bugfix, maintainer: open

#24283 inipp: new port in devel
  devel/inipp/Portfile
Labels: type: submission

#24282 libclastfm: new port
  audio/libclastfm/Portfile
  audio/libclastfm/files/patch-fix-linking.diff
Labels: type: submission

#24288 talloc: required thread_local_storage
  devel/talloc/Portfile
Labels: type: bugfix, maintainer: none

#24239 tiledb: cleanup and migrate from legacy dependency management mode
  databases/tiledb/Portfile
  databases/tiledb/files/lz4_fix.diff
  databases/tiledb/files/patch-do-not-force-VCPKG.diff
Labels: type: enhancement, maintainer: open

#24294 ipsw: Update to 3.1.488
  security/ipsw/Portfile
Labels: type: update, maintainer, maintainer: open

#24293 dispenso: update to 1.3.0, drop patches
  devel/dispenso/Portfile
  devel/dispenso/files/0001-platform.h-add-cpuRelax-for-PowerPC-and-ARM.patch
  devel/dispenso/files/0002-no-werror.patch
Labels: type: update, maintainer: none

#24290 tdb: requires thread_local_storage
  databases/tdb/Portfile
Labels: type: bugfix, maintainer: none

#24295 bluemoon: update to 2.13
  games/bluemoon/Portfile
Labels: type: update, maintainer: none

#24296 oh-my-posh: update to version 21.2.0
  sysutils/oh-my-posh/Portfile
Labels: type: update, maintainer, maintainer: open

#24297 uv: Update to 0.2.6
  devel/uv/Portfile
Labels: type: update, maintainer, maintainer: open

#24298 cyclonedds: fix build on earlier macOS
  devel/cyclonedds/Portfile
  devel/cyclonedds/files/0001-threads.c-fix-for-pthread_threadid_np-on-macOS.patch
  devel/cyclonedds/files/0002-threads.c-provide-def-of-MAXTHREADNAMESIZE-when-unde.patch
  devel/cyclonedds/files/0003-ddsi_udp.c-use-ip_mreqn-where-it-is-actually-availab.patch
  devel/cyclonedds/files/0004-crypto_transform.c-fix-memcpy.patch
  devel/cyclonedds/files/0005-Fix-unresolved-symbol-on-big-endian-architectures.patch
Labels: type: bugfix, maintainer: open

#24300 ffms2: set required C++11 standard, fix build deps
  multimedia/ffms2/Portfile
Labels: type: bugfix, maintainer: open

#24304 logtalk: update to 3.80.0
  lang/logtalk/Portfile
Labels: type: update, maintainer

#24241 emacs: Prevent Macports tree-sitter grammar libs from shadowing
  editors/emacs/Portfile
  editors/emacs/files/site-start-app.el
  editors/emacs/files/site-start.el
Labels: type: bugfix, maintainer: open, by: member

#24308 symfony-cli: update to 5.9.1
  devel/symfony-cli/Portfile
Labels: type: update, maintainer, maintainer: open

#24306 Gildas: update to 202406a
  science/gildas/Portfile
  science/gildas/files/patch-admin-Makefile.build.diff
Labels: type: enhancement, type: update, maintainer

#24302 zvbi: disable rpath
  multimedia/zvbi/Portfile
Labels: type: bugfix, maintainer: none

#24315 ipsw: Update to 3.1.490
  security/ipsw/Portfile
Labels: type: update, maintainer, maintainer: open

#24311 gallery-dl: update to 1.27.0
  net/gallery-dl/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer, maintainer: open

#24316 oh-my-posh: update to version 21.2.1
  sysutils/oh-my-posh/Portfile
Labels: type: update, maintainer, maintainer: open

#24321 proxmark3-iceman: update to 4.18589
  science/proxmark3-iceman/Portfile
Labels: type: update, maintainer, maintainer: open

#24325 oh-my-posh: update to version 21.2.2
  sysutils/oh-my-posh/Portfile
Labels: type: update, maintainer, maintainer: open

#24327 saml2aws: update to 2.36.16
  security/saml2aws/Portfile
Labels: type: update, maintainer: open, by: member

#24303 ffmpeg-devel: enable sdl2 on powerpc
  multimedia/ffmpeg-devel/Portfile
Labels: type: enhancement, maintainer: open

#24335 py-scikit-build-core: update to 0.9.5
  python/py-scikit-build-core/Portfile
Labels: type: update, maintainer: none

#24009 glib2-devel Adapted patch to include gio-launch-desktop bin in x11 (generic)
  devel/glib2-devel/Portfile
  devel/glib2-devel/files/patch-meson_build-meson_options-appinfo.diff
Labels: maintainer: open

#24343 eza: update to 0.18.17
  sysutils/eza/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#24345 ruff: Update to 0.4.8
  devel/ruff/Portfile
Labels: type: update, maintainer, maintainer: open

#24344 uv: Update to 0.2.8
  devel/uv/Portfile
Labels: type: update, maintainer, maintainer: open

#24354 fireworkx: do not use -march=native
  x11/fireworkx/Portfile
Labels: type: bugfix, maintainer: none

#24352 blaspp: update to 2024.05.31
  math/blaspp/Portfile
Labels: type: update, maintainer, maintainer: open

#24337 rgb-tui: non-functional: add port notes re true color support
  graphics/rgb-tui/Portfile
Labels: type: enhancement, maintainer, maintainer: open

#24289 notmuch: needs C++11
  mail/notmuch/Portfile
Labels: type: bugfix, maintainer: open

#24287 arborx: update to 1.6
  math/arborx/Portfile
Labels: type: update, maintainer: open

#24284 superlu_dist: update to 9.0.0
  math/superlu_dist/Portfile
Labels: type: update, maintainer: open

#24334 libass: update to 0.17.2; libass-devel: update to 2024.06.02
  multimedia/libass/Portfile
Labels: type: update, maintainer: none

#24268 pympress: new port
  graphics/pympress/Portfile
Labels: type: submission

#24040 octave-fits: fix build with gcc
  octave/octave-fits/Portfile
  octave/octave-fits/files/patch-fits-3-octave-9-compat.diff
Labels: type: bugfix, maintainer: open

#24363 zfp: update to 2024.05.18
  science/zfp/Portfile
Labels: type: update, maintainer, maintainer: open

#24360 ace: update to version 8.0.0
  devel/ace/Portfile
  devel/ace/files/patch-ace-config.h.diff
  devel/ace/files/patch-include-makeinclude-platform_macros.GNU.diff
Labels: type: update, maintainer, maintainer: open

#24362 Fix geneweb incompatibility with camlp5 8.03.0
  genealogy/geneweb/Portfile
  genealogy/geneweb/files/patch-Makefile-PR1806.diff
  ocaml/ocaml-not-ocamlfind/Portfile
  ocaml/ocaml-not-ocamlfind/files/patch-Makefile.diff
  ocaml/ocaml-ocamlgraph/Portfile
  ocaml/ocaml-ppx_blob/Portfile
Labels: type: bugfix, type: submission, maintainer, maintainer: open

#24366 ipsw: Update to 3.1.491
  security/ipsw/Portfile
Labels: type: update, maintainer, maintainer: open

#24367 uv: Update to 0.2.9
  devel/uv/Portfile
Labels: type: update, maintainer, maintainer: open

#24339 libvirt: update to 10.4.0
  sysutils/libvirt/Portfile
Labels: type: update, maintainer: open, by: member

#24369 oh-my-posh: update to version 21.3.0
  sysutils/oh-my-posh/Portfile
Labels: type: update, maintainer, maintainer: open

#24323 pqrs: update to 0.3.1
  devel/pqrs/Portfile
Labels: type: update, maintainer: open, by: member

#24320 autorestic: update to 1.8.2
  sysutils/autorestic/Portfile
Labels: type: update, maintainer: open, by: member

#24346 sakura: new port, a terminal emulator
  x11/sakura/Portfile
Labels: type: submission

#24371 caps-log: new port
  sysutils/caps-log/Portfile
Labels: type: submission

#24342 py-awscli2: update to 2.16.2
  python/py-awscli2/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#24373 caps-log: use legacysupport for older systems with libc++
  sysutils/caps-log/Portfile
Labels: type: bugfix, maintainer, maintainer: open

#24368 camlp5-buildscripts: new port 0.03
  ocaml/ocaml-camlp5-buildscripts/Portfile
Labels: type: submission

#24375 cfm: update to 0.6.6
  sysutils/cfm/Portfile
  sysutils/cfm/files/patch-Makefile.diff
Labels: type: update, maintainer: requires approval

#24120 neovim: Build and install tree-sitter parsers
  editors/neovim/Portfile
  editors/neovim/files/embed-parsers-build.diff
Labels: type: bugfix, maintainer: open

#24313 openssl3: update to 3.3.1 and 3.1.6
  devel/openssl3/Portfile
  devel/openssl3/files/7e4d731b1c07201ad9374c1cd9ac5263bdf35bce.patch
  devel/openssl3/files/e9d7083e241670332e0443da0f0d4ffb52829f08.patch
Labels: type: update, maintainer: open, by: member

#24382 xvega: fix port after the recent update
  graphics/xvega/Portfile
  graphics/xvega/files/0001-CMakeLists-fix-optflags-for-PowerPC-case.patch
Labels: type: bugfix, maintainer: open

#24392 xcode-build-server: update to 1.1.0
  devel/xcode-build-server/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#24391 josm: update to 19096
  gis/JOSM/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#24389 bpack: update to 3.1.0
  math/bpack/Portfile
Labels: type: update, maintainer, maintainer: open

#24388 fortran-stdlib: update to 2024.06.06
  lang/fortran-stdlib/Portfile
Labels: type: update, maintainer, maintainer: open

#24387 tippecanoe: update to 2.55.0
  gis/tippecanoe/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#24376 ocaml-merlin: update to 4.14-414
  ocaml/ocaml-merlin/Portfile
Labels: type: update, maintainer, maintainer: open

#24379 rawproc: use legacysupport for filesystem
  graphics/rawproc/Portfile
Labels: type: bugfix, maintainer, maintainer: open

#24380 mpv-legacy: fix coreaudio, switch to ffmpeg6
  multimedia/mpv-legacy/Portfile
Labels: type: bugfix, type: enhancement, maintainer, maintainer: open

#24381 libsdl2-powerpc: add variants, minor fix to deps, revbump
  devel/libsdl2-powerpc/Portfile
Labels: type: enhancement, maintainer

#24385 GPXSee: update to 13.21
  gis/GPXSee/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#24305 Update: Bun 1.1.12
  devel/bun/Portfile
Labels: type: update, maintainer, maintainer: open

#24356 switchaudio-osx: unbreak for < 10.8
  audio/switchaudio-osx/Portfile
  audio/switchaudio-osx/files/0001-audio_switch.h-fix-for-pre-10.8.patch
  audio/switchaudio-osx/files/patch-kAudioObjectPropertyElementMain.diff
Labels: type: bugfix, maintainer: open

#24353 mlterm: use gtk3 by default, add variants for gtk2 and sdl2
  x11/mlterm/Portfile
Labels: type: enhancement, maintainer: none

#24349 libabw: set required C++11 standard
  devel/libabw/Portfile
Labels: type: bugfix, maintainer: open

#24338 libjwt: update to 1.17.1
  devel/libjwt/Portfile
Labels: type: update, maintainer: open, by: member

#24319 7zip: update to 24.06
  archivers/7zip/Portfile
Labels: type: update, maintainer: open, by: member

#24285 audacious-*: Fix gtk2 and gtk3 dependencies
  multimedia/audacious-core/Portfile
  multimedia/audacious-plugins/Portfile
Labels: maintainer: requires approval, maintainer: timeout, by: member

#24286 cl-cffi-gtk: Standardize dependencies
  lisp/cl-cffi-gtk/Portfile
Labels: maintainer: open, by: member

#24307 CI: Remove macos-11
  .github/workflows/main.yml
Labels: by: member

#24331 kompose: update to 1.34.0
  devel/kompose/Portfile
Labels: type: update, maintainer: open, by: member

#24328 bzip3: update to 1.4.0
  archivers/bzip3/Portfile
Labels: type: update, maintainer: open, by: member

#24322 pkixssh: allow builds with gcc, move keychain in a variant
  net/pkixssh/Portfile
Labels: type: bugfix, maintainer: open

#24395 game-porting-toolkit: fix path, move into devel
  devel/game-porting-toolkit/Portfile
  devel/game-porting-toolkit/files/0001-game_porting_toolkit_1.0_beta1.diff
  devel/game-porting-toolkit/files/0002-game_porting_toolkit_1.0_beta2.diff
  devel/game-porting-toolkit/files/0003-game_porting_toolkit_1.0_beta3.diff
  devel/game-porting-toolkit/files/0004-game_porting_toolkit_1.0_beta4.diff
  devel/game-porting-toolkit/files/0005-game_porting_toolkit_1.1.diff
  devel/game-porting-toolkit/files/1001-configure-remove-cross_compiling-check.diff
  devel/game-porting-toolkit/files/1002-server-remove-cxhack-21217.diff
  devel/game-porting-toolkit/files/1003-default-win10-19043.diff
  devel/game-porting-toolkit/files/1004-mscoree-update-wine-mono-to-7.4.1.diff
  devel/game-porting-toolkit/files/1005-ntdll-d3dmetal-env.diff
  devel/game-porting-toolkit/files/gameportingtoolkit
  devel/game-porting-toolkit/files/gameportingtoolkit-no-esync
  devel/game-porting-toolkit/files/gameportingtoolkit-no-hud
Labels: by: member

#24384 qtiplot: revbump upon gsl update
  aqua/qtiplot/Portfile
Labels: type: bugfix, maintainer: open

#24396 ipsw: Update to 3.1.492
  security/ipsw/Portfile
Labels: type: update, maintainer, maintainer: open

#24403 gdal: unbreak after update to 3.9.0
  gis/gdal/Portfile
Labels: type: bugfix, maintainer: open

#24405 snac: update to 2.54
  net/snac/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer, maintainer: open

#24415 snac: update to 2.55
  net/snac/Portfile
Labels: type: bugfix, type: update, maintainer, maintainer: open

#24417 elmerfem: update to 2024.06.07
  science/elmerfem/Portfile
Labels: type: update, maintainer, maintainer: open

#24409 gcab: fix build with old Xcode gcc
  gnome/gcab/Portfile
  gnome/gcab/files/allow-xcode-gcc.patch
Labels: type: bugfix, maintainer: none

#24410 py-bugsnag: update to 4.7.1
  python/py-bugsnag/Portfile
Labels: type: update, maintainer: none

#24422 oh-my-posh: update to version 21.4.0
  sysutils/oh-my-posh/Portfile
Labels: type: update, maintainer, maintainer: open

#24401 camlp5: synchronize dependencies with opam
  lang/camlp5/Portfile
Labels: type: enhancement, maintainer: open

#24420 pdal: increase revision after GDAL update to 3.9.0
  gis/pdal/Portfile
Labels: maintainer, maintainer: open

#24049 fluent-bit: update to 3.0.4
  sysutils/fluent-bit/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#24400 msp430-elf-binutils: update to version 2.34
  cross/msp430-elf-binutils/Portfile
Labels: type: enhancement, type: update, maintainer: none

#24424 mfem: update to 4.7
  science/mfem/Portfile
  science/mfem/files/patch-cstdint.diff
Labels: type: update, maintainer, maintainer: open

#24413 tracker3: new port in gnome
  gnome/tracker3/Portfile
  gnome/tracker3/files/patch-meson.build-32.diff
  gnome/tracker3/files/patch-meson.build.diff
Labels: type: submission

#24383 py-qt4py: Qt4 version to support powerpc systems
  python/py-qt4py/Portfile
Labels: type: bugfix, type: submission

#24377 py-msgpack: fix for 32-bit
  python/py-msgpack/Portfile
  python/py-msgpack/files/patch-32-bit.diff
Labels: type: bugfix, maintainer: open

#24419 wdsp: blacklist old Xcode gcc, fix for old systems
  science/wdsp/Portfile
Labels: type: bugfix, maintainer: open

#24397 libmsp430: new port
  devel/libmsp430/Portfile
  devel/libmsp430/files/bsl430dll_makefile.diff
  devel/libmsp430/files/makefile.diff
Labels: type: enhancement, type: submission

#24378 net-snmp: fix for older systems
  net/net-snmp/Portfile
  net/net-snmp/files/patch-legacy-compat.diff
Labels: type: bugfix, maintainer: open

#24426 uv: Update to 0.2.10
  devel/uv/Portfile
Labels: type: update, maintainer, maintainer: open

#24432 oh-my-posh: update to version 21.5.0
  sysutils/oh-my-posh/Portfile
Labels: type: update, maintainer, maintainer: open

#24429 ipsw: Update to 3.1.493
  security/ipsw/Portfile
Labels: type: update, maintainer, maintainer: open

#24436 py-cgmetadata: new submission
  python/py-cgmetadata/Portfile
Labels: type: submission, by: member
