Repository macports/macports-ports, pull requests merged in 2024-07, with the labels that each got.

#24732 mscp: fix build on systems where it fails
  net/mscp/Portfile
Labels: type: bugfix, maintainer: open

#24746 dino: update to 0.4.4
  net/dino/Portfile
  net/dino/files/patch-disable-openpgp.diff
  net/dino/files/patch-fix-install.diff
  net/dino/files/patch-fix-openpgp.diff
Labels: type: bugfix, type: update, maintainer, maintainer: open

#24748 eza: update to 0.18.21
  sysutils/eza/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#24747 jreleaser: update to version v1.13.1
  devel/jreleaser/Portfile
Labels: type: enhancement, type: update, maintainer

#24749 oh-my-posh: update to version 21.17.2
  sysutils/oh-my-posh/Portfile
Labels: type: update, maintainer, maintainer: open

#24752 elmerfem: update to 2024.07.01
  science/elmerfem/Portfile
Labels: type: update, maintainer, maintainer: open

#24756 gk update to v2.1.0
  devel/gk/Portfile
Labels: maintainer, maintainer: open

#24736 ginkgo: update to 1.8.0
  math/ginkgo/Portfile
Labels: type: update, maintainer, maintainer: open

#24711 TypeScript: Update to 5.5.2
  lang/typescript/Portfile
Labels: type: update, maintainer: open

#24729 gdal: fix arrow variant on 32-bit platforms (no revbump needed)
  gis/gdal/Portfile
Labels: type: bugfix, maintainer: open

#24724 icmake: fix build on older systems
  devel/icmake/Portfile
Labels: type: bugfix, maintainer: requires approval

#22699 x86_64-binutils: new package
  cross/x86_64-binutils/Portfile
Labels: type: enhancement, type: submission, maintainer, maintainer: open

#24758 coreutils-uutils: update to 0.0.27
  sysutils/coreutils-uutils/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#24759 tio: fix build on macOS <11
  comms/tio/Portfile
Labels: maintainer: open

#24760 HiGHS: update to 1.7.2
  math/HiGHS/Portfile
Labels: type: update, maintainer, maintainer: open

#24761 FAudio: update to 24.07
  audio/FAudio/Portfile
Labels: type: update, maintainer, maintainer: open

#24745 cppcheck: fix build on macOS <10.12
  devel/cppcheck/Portfile
Labels: maintainer: open

#23979 libgit2-devel: update to 1.8.1
  devel/libgit2-devel/Portfile
  devel/libgit2-devel/files/0001-process.c-fix-environ-for-macOS.patch
Labels: type: update, maintainer: open, by: member

#24754 openssh: update to 9.8p1, update patchfiles
  net/openssh/Portfile
  net/openssh/files/launchd.patch
  net/openssh/files/pam.patch
  net/openssh/files/patch-sshd-session.c-apple-sandbox-named-external.diff
Labels: type: update, maintainer: open, by: member

#24773 ruby-build: Upgrade to 20240702
  ruby/ruby-build/Portfile
Labels: maintainer, maintainer: open

#24780 uv: Update to 0.2.20
  devel/uv/Portfile
Labels: type: update, maintainer, maintainer: open

#24775 ocrmypdf: update to 16.4.1
  textproc/ocrmypdf/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer, maintainer: open

#24781 dcw-gmt: update to 2.2.0
  science/dcw-gmt/Portfile
Labels: type: update, maintainer, maintainer: open

#24783 google-cloud-sdk: update to 483.0.0
  devel/google-cloud-sdk/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#24779 mysql8: Add missing cmake PortGroup Flag OPENSSL_ROOT_DIR
  databases/mysql8/Portfile
Labels: type: bugfix, maintainer: open

#24784 chafa: fix build on i386 systems
  graphics/chafa/Portfile
  graphics/chafa/files/patch-extract-128-epi64.diff
Labels: maintainer: open

#24777 font-manager: update to 0.9.0
  sysutils/font-manager/Portfile
  sysutils/font-manager/files/patch-use-right-python.diff
Labels: type: update, maintainer, maintainer: open

#24788 simulavr: Update to 1.1.0
  emulators/simulavr/Portfile
  emulators/simulavr/files/doc.patch
  emulators/simulavr/files/include.patch
  emulators/simulavr/files/no-git.patch
  emulators/simulavr/files/no-python.patch
  emulators/simulavr/files/patch-at90can-elpm
  emulators/simulavr/files/patch-at90can-ivs
  emulators/simulavr/files/patch-msleep
  emulators/simulavr/files/patch-src_Makefile.in
  emulators/simulavr/files/patch-src_systemclock.cpp
Labels: type: update, maintainer: none, by: member

#24785 global: update to 6.6.13
  devel/global/Portfile
Labels: type: update, maintainer: none

#24776 wren-cli: Update to 0.4.0; fix conflict with libuv; fix universal variant and enable non-Intel archs; fix whitespace
  lang/wren-cli/Portfile
Labels: type: update, maintainer: open, by: member

#24792 ruby-devel: update to 2024.07.04
  lang/ruby-devel/Portfile
Labels: type: update, maintainer, maintainer: open

#24793 madness: update to 2024.06.27
  science/madness/Portfile
Labels: type: update, maintainer, maintainer: open

#24782 cdo: update to 2.4.2
  science/cdo/Portfile
Labels: type: update, maintainer, maintainer: open

#24795 gcc_dependencies: sync compiler choice to use gcc14
  _resources/port1.0/compilers/gcc_dependencies.tcl
Labels: type: bugfix

#24768 MoarVM: enable mimalloc support in a separate variant
  lang/MoarVM/Portfile
Labels: maintainer: open

#24797 Bun: Update to 1.1.18
  devel/bun/Portfile
Labels: type: update, maintainer, maintainer: open

#24801 oh-my-posh: update to version 21.18.2
  sysutils/oh-my-posh/Portfile
Labels: type: update, maintainer, maintainer: open

#24804 sqlean: update to 0.23.0, fix build on old systems
  databases/sqlean/Portfile
Labels: type: bugfix, type: update, maintainer: open

#24798 znc: fix build on macOS <10.14
  irc/znc/Portfile
Labels: maintainer: none

#24805 flashrom: fix build for < 10.7
  sysutils/flashrom/Portfile
Labels: type: bugfix, maintainer: open

#24098 py-pytorch: Update to version 2.3.0; Add Python 311 312
  python/py-pytorch/Portfile
  python/py-pytorch/files/Werror.patch
  python/py-pytorch/files/patch-macOS12-xcode14.diff
  python/py-pytorch/files/patch-macOS13-xcode14.diff
  python/py-pytorch/files/patch-pyproject_toml.diff
Labels: type: update, maintainer: none

#24810 oh-my-posh: update to version 21.20.2
  sysutils/oh-my-posh/Portfile
Labels: type: update, maintainer, maintainer: open

#24815 libsdl2-powerpc: update to 2.30.5
  devel/libsdl2-powerpc/Portfile
Labels: type: update, maintainer

#24814 lfortran: update to 0.37.0
  lang/lfortran/Portfile
Labels: type: update, maintainer, maintainer: open

#24786 py-urwid,py-pudb: add py312 subport
  python/py-pudb/Portfile
  python/py-urwid/Portfile
Labels: type: enhancement, maintainer: none

#24778 thrust: update to 2.4.0
  devel/thrust/Portfile
Labels: type: update, maintainer, maintainer: open

#24774 nut: update to 2.8.2
  sysutils/nut/Portfile
  sysutils/nut/files/dynamic_lookup-11.patch
Labels: type: update, maintainer: none, by: member

#24770 fricas: update to 1.3.11
  math/fricas/Portfile
Labels: type: update, maintainer, maintainer: open

#24765 py-gdal: update to 3.9.1
  python/py-gdal/Portfile
Labels: type: update, maintainer, maintainer: open

#24769 geos: update to 3.12.2
  science/geos/Portfile
Labels: type: update, maintainer: open

#23926 py-mistune: restore py27 subport to unbreak dependents
  python/py-mistune/Portfile
Labels: type: bugfix, maintainer: open

#24819 oh-my-posh: update to version 21.21.1
  sysutils/oh-my-posh/Portfile
Labels: type: update, maintainer, maintainer: open

#24829 gitu: Update to 0.22.1
  devel/gitu/Portfile
Labels: type: update, maintainer, maintainer: open

#24830 rtmidi: set correct C++ standard
  audio/rtmidi/Portfile
Labels: type: bugfix, maintainer: open

#24831 xeus-zmq: set cxx_standard 2017
  devel/xeus-zmq/Portfile
Labels: maintainer: open

#24821 rb-nokogiri: update to 1.16.6
  ruby/rb-nokogiri/Portfile
Labels: type: update, maintainer: open

#24817 feh: update to 3.10.3
  graphics/feh/Portfile
Labels: type: update, maintainer: none

#24832 timewarrior: unbreak for systems with libstdc++
  office/timewarrior/Portfile
  office/timewarrior/files/patch-fix-cxx.diff
Labels: type: bugfix, maintainer: open

#24826 qemu: enable +curses always
  emulators/qemu/Portfile
Labels: type: enhancement, maintainer: open, by: member

#24837 ipsw: Update to 3.1.512
  security/ipsw/Portfile
Labels: type: update, maintainer, maintainer: open

#24838 xeus: set cxx_standard 2017
  devel/xeus/Portfile
Labels: maintainer: open

#24790 fortran-stdlib: update to 0.7.0; -devel: update to 2024.07.01
  lang/fortran-stdlib/Portfile
Labels: type: update, maintainer, maintainer: open

#24822 fetchmail: update to 6.4.38
  mail/fetchmail/Portfile
Labels: type: update, maintainer: none

#24841 stanc3: update to 2.35.0
  math/stanc3/Portfile
Labels: type: update, maintainer, maintainer: open

#24839 gdal: enable MacPort's libc++ on macOS 10.12 and earlier
  gis/gdal/Portfile
Labels: type: bugfix, maintainer, maintainer: open

#24828 ristretto: Update to 0.13.2
  xfce/ristretto/Portfile
Labels: type: enhancement, type: update, maintainer: none

#24809 albafetch: fix build on macOS <10.9, refactor patch
  sysutils/albafetch/Portfile
  sysutils/albafetch/files/0001-fix-macos_infos.patch
Labels: maintainer: open

#24807 elmerfem: update to 2024.07.04, fix build with gcc14
  science/elmerfem/Portfile
  science/elmerfem/files/patch-umf4_f77wrapper.c.diff
Labels: type: bugfix, type: update, maintainer, maintainer: open

#24836 abella: update to 2.0.8.3; add ocaml ports needed to support it
  math/abella/Portfile
  math/abella/files/patch-bytecode.diff
  ocaml/ocaml-base64/Portfile
  ocaml/ocaml-crunch/Portfile
  ocaml/ocaml-ptime/Portfile
Labels: type: update, type: submission, maintainer, maintainer: open

#24843 kokkos-devel: update to 2024.07.05
  devel/kokkos/Portfile
Labels: type: update, maintainer: open

#24844 edid-decode: update to version 20240703
  sysutils/edid-decode/Portfile
Labels: type: update, maintainer, maintainer: open

#24800 MoarVM: fix build with gcc14
  lang/MoarVM/Portfile
Labels: type: bugfix, maintainer, maintainer: open

#24794 mathmod: new port in math
  math/mathmod/Portfile
  math/mathmod/files/patch-ParisoMathObject.cpp.diff
  math/mathmod/files/patch-ParisoMathObject.h.diff
  math/mathmod/files/patch-commun.cpp.diff
  math/mathmod/files/patch-drawingoptions.cpp.diff
  math/mathmod/files/patch-drawingoptions.ui.diff
  math/mathmod/files/patch-jiso.h.diff
  math/mathmod/files/patch-jpar.h.diff
  math/mathmod/files/patch-mathmodconfig.js.diff
  math/mathmod/files/patch-parametersoptions.cpp.diff
  math/mathmod/files/patch-parametersoptions.h.diff
Labels: type: submission

#24789 font-manager: Use meson.native.binaries
  sysutils/font-manager/Portfile
  sysutils/font-manager/files/patch-use-right-python.diff
Labels: maintainer: open, by: member

#24734 ocaml-yojson: update to 2.2.2
  ocaml/ocaml-yojson/Portfile
Labels: type: update, maintainer: open

#24772 gjs: fix for systems where latest mozjs fails
  gnome/gjs/Portfile
  gnome/gjs/files/patch-atomic_load.diff
  gnome/gjs/files/patch-gjs-gint64.diff
  gnome/gjs/files/patch-gjs-gsize.diff
  gnome/gjs/files/patch-gjs-meson_options-legacy.diff
  gnome/gjs/files/patch-gjs-test-legacy.diff
Labels: type: bugfix, maintainer: open

#24764 gnucash: add variant docs
  gnome/gnucash-docs/Portfile
  gnome/gnucash/Portfile
Labels: type: enhancement, maintainer: open

#24846 orage: Update to 4.18.0
  xfce/orage/Portfile
Labels: type: enhancement, type: update, maintainer: none

#24849 sqlean: update to 0.24.1
  databases/sqlean/Portfile
  databases/sqlean/files/patch-Makefile.diff
Labels: type: update, maintainer: open

#24848 snac: update to 2.56
  net/snac/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer, maintainer: open

#24847 xfce4-terminal: Update to 1.1.3
  xfce/xfce4-terminal/Portfile
  xfce/xfce4-terminal/files/remove-intltool-perl-hack.diff
Labels: type: enhancement, type: update, maintainer: none

#24852 squeeze: Remove port
  xfce/squeeze/Portfile
  xfce/squeeze/files/patch-internals.diff
Labels: maintainer: none

#24858 oh-my-posh: update to version 21.23.0
  sysutils/oh-my-posh/Portfile
Labels: type: update, maintainer, maintainer: open

#24859 ruby-build: Upgrade to 20240709.1
  ruby/ruby-build/Portfile
Labels: maintainer, maintainer: open

#24857 pdal: update to 2.7.2
  gis/pdal/Portfile
Labels: type: update, maintainer, maintainer: open

#24861 shtools: update to 4.13.1
  science/shtools/Portfile
Labels: type: enhancement, type: update, maintainer

#24856 telescope: update to 0.10.1
  net/telescope/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#24855 Gildas: update to 202407b
  science/gildas/Portfile
  science/gildas/files/patch-admin-Makefile.build.diff
Labels: type: enhancement, type: update, maintainer

#24860 josm: update to 19128
  gis/JOSM/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#24864 ipsw: Update to 3.1.514
  security/ipsw/Portfile
Labels: type: update, maintainer, maintainer: open

#24863 uv: Update to 0.2.23
  devel/uv/Portfile
Labels: type: update, maintainer, maintainer: open

#24867 skaffold: update to 2.13.0
  devel/skaffold/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#24862 dosbox-x: update to version 2024.07.01
  emulators/dosbox-x/Portfile
Labels: type: update, maintainer: none

#24820 OpenBLAS: update to 0.3.27; OpenBLAS-devel: update to 20240704
  math/OpenBLAS/Portfile
  math/OpenBLAS/files/patch-KERNEL.PPC970-KERNEL.PPCG4-unbreak-CMake-parsing.diff
  math/OpenBLAS/files/patch-OpenBLAS-old-macos.diff
  math/OpenBLAS/files/patch-ar-options-old-macos.diff
  math/OpenBLAS/files/patch-cpuid_power.c-add-CPU_SUBTYPE_POWERPC_7400-case.diff
  math/OpenBLAS/files/patch-enable-overstep-of-too-long-args-without-DYNAMIC_ARCH.diff
  math/OpenBLAS/files/patch-libnoarch.devel.diff
  math/OpenBLAS/files/patch-openblas.pc-fixed-version-and-url.diff
  math/OpenBLAS/files/patch-system_check.cmake-fix-arch-detection-for-Darwin-Pow.diff
  math/OpenBLAS/files/patch-xcode15-fix.diff
Labels: type: update, maintainer: open

#24870 paho.mqtt.cpp: update to 1.4.1
  net/paho.mqtt.cpp/Portfile
Labels: type: enhancement, type: update, maintainer: none

#24874 gcc12–14: fix triple for powerpc (no revbump)
  lang/gcc12/Portfile
  lang/gcc13/Portfile
  lang/gcc14/Portfile
Labels: type: bugfix, maintainer: none

#24873 zmap: update to 4.2.0
  net/zmap/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer, maintainer: open

#24875 swi-prolog-devel: Updated to version 9.3.8
  lang/swi-prolog-devel/Portfile
Labels: type: update, maintainer, maintainer: open

#24876 astyle: update to 3.5.2
  devel/astyle/Portfile
Labels: type: update, maintainer: none

#24853 py-igraph: update to 0.11.6
  python/py-igraph/Portfile
Labels: type: update, maintainer, maintainer: open

#24877 oh-my-posh: update to version 21.23.4
  sysutils/oh-my-posh/Portfile
Labels: type: update, maintainer, maintainer: open

#24881 ipsw: Update to 3.1.518
  security/ipsw/Portfile
Labels: type: update, maintainer, maintainer: open

#24880 uv: Update to 0.2.24
  devel/uv/Portfile
Labels: type: update, maintainer, maintainer: open

#24889 oh-my-posh: update to version 21.24.0
  sysutils/oh-my-posh/Portfile
Labels: type: update, maintainer, maintainer: open

#24887 got: update to 0.101
  devel/got/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer, maintainer: open

#24886 maestral: update to 1.9.4 for new systems
  sysutils/maestral/Portfile
Labels: type: update, maintainer, maintainer: open

#24885 pika: update to 0.26.0
  devel/pika/Portfile
Labels: type: update, maintainer, maintainer: open

#24882 xfce4-appfinder: Update to 4.18.1
  xfce/xfce4-appfinder/Portfile
Labels: type: enhancement, type: update, maintainer: none

#24890 screenfetch: new port in sysutils
  sysutils/screenfetch/Portfile
Labels: type: submission

#24878 ghc: update to 9.6.6
  lang/ghc/Portfile
Labels: type: update, maintainer: open, by: member

#24865 yt-dlp: update to 2024.07.09
  net/youtube-dl/Portfile
Labels: type: bugfix, type: enhancement, type: update, type: security fix, maintainer: requires approval

#24892 vttest: update to 20240708
  devel/vttest/Portfile
Labels: type: update, maintainer: none

#24893 py-awscli2: update to 2.17.13
  python/py-awscli2/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#24845 enchant2: update to 2.8.1
  textproc/enchant2/Portfile
Labels: type: update, maintainer: open, by: member

#24895 less: update to 661
  textproc/less/Portfile
Labels: type: enhancement, type: update, maintainer: open

#24897 miniflux: update to 2.1.4
  net/miniflux/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#24894 texmaker: Update to 5.1.4
  tex/texmaker/Portfile
Labels: type: update, maintainer: open, by: member

#24899 oh-my-posh: update to version 21.25.0
  sysutils/oh-my-posh/Portfile
Labels: type: update, maintainer, maintainer: open

#24898 crystal: set platforms to darwin >= 19
  lang/crystal/Portfile
Labels: maintainer: open

#24621 mail/mlmmj: Added a new port
  mail/mlmmj/Portfile
Labels: type: submission

#24902 ruby33: refactor failing patch
  lang/ruby33/Portfile
  lang/ruby33/files/patch-vm_insnhelper.c.diff
Labels: maintainer: open

#24910 oh-my-posh: update to version 21.26.0
  sysutils/oh-my-posh/Portfile
Labels: type: update, maintainer, maintainer: open

#24911 dagger: update to 0.12.0
  devel/dagger/Portfile
Labels: type: update, maintainer: open

#24900 pgtcl: update to 3.1.0
  databases/pgtcl/Portfile
Labels: type: enhancement, type: update, maintainer: none

#24909 Bun: Update to 1.1.20
  devel/bun/Portfile
Labels: type: update, maintainer, maintainer: open

#24884 wx*-3.0*: revbump for C++ ABI change
  graphics/wxWidgets-3.0/Portfile
Labels: type: bugfix, maintainer: open

#24737 mumps: update to 5.7.2
  math/mumps/Portfile
  math/mumps/files/patch-Makefile.inc.diff
  math/mumps/files/patch-shared.diff
Labels: type: update, maintainer: open

#24915 freac, MacPass, portfolio-performance +deps: Remove myself as maintainer
  aqua/smooth/Portfile
  audio/BoCA/Portfile
  audio/freac/Portfile
  audio/proxy-audio-device/Portfile
  devel/HNHUi/Portfile
  devel/KissXML/Portfile
  devel/TransformerKit/Portfile
  finance/portfolio-performance/Portfile
  security/KeePassKit/Portfile
  security/MacPass/Portfile
Labels: maintainer: open

#24914 tmux: update tmux-devel to latest commit (5039be6)
  sysutils/tmux/Portfile
Labels: type: update, maintainer, maintainer: open

#24917 oh-my-posh: update to version 21.26.2
  sysutils/oh-my-posh/Portfile
Labels: type: update, maintainer, maintainer: open

#24924 py-gmpy2: update to 2.2.0, add py312 subport
  python/py-gmpy2/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#24920 blake3: update to 1.5.2
  security/blake3/Portfile
Labels: type: update, maintainer, maintainer: open

#24928 logtalk: update to 3.81.0
  lang/logtalk/Portfile
Labels: type: update, maintainer

#24931 oh-my-posh: update to version 21.26.3
  sysutils/oh-my-posh/Portfile
Labels: type: update, maintainer, maintainer: open

#24921 libpqxx26: remove port
  databases/libpqxx26/Portfile
Labels: maintainer: none

#24934 libvterm: fix pedantic flag, fixes build with Xcode gcc
  devel/libvterm/Portfile
  devel/libvterm/files/patch-fix-pedantic.diff
Labels: type: bugfix, maintainer: open

#24936 ruff: Update to 0.5.2
  devel/ruff/Portfile
Labels: type: update, maintainer, maintainer: open

#24932 wolfssl: update to version 5.7.2
  devel/wolfssl/Portfile
Labels: type: update, maintainer, type: security fix, maintainer: open

#24935 fheroes2: update to 1.1.1
  games/fheroes2/Portfile
Labels: type: update, maintainer, maintainer: open

#24937 uv: Update to 0.2.25
  devel/uv/Portfile
Labels: type: update, maintainer, maintainer: open

#24938 ipsw: Update to 3.1.523
  security/ipsw/Portfile
Labels: type: update, maintainer, maintainer: open

#24939 openjdk22-zulu: update to 22.32.15
  java/openjdk22-zulu/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#24940 openjdk21-zulu: update to 21.36.17
  java/openjdk21-zulu/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#24941 openjdk17-zulu: update to 17.52.17
  java/openjdk17-zulu/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#24942 openjdk11-zulu: update to 11.74.15
  java/openjdk11-zulu/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#24943 openjdk8-zulu: update to 8.80.0.17
  java/openjdk8-zulu/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#24944 openjdk22: update to 22.0.2
  java/openjdk22/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#24945 google-cloud-sdk: update to 484.0.0
  devel/google-cloud-sdk/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#24947 openjdk21-corretto: update to 21.0.4.7.1
  java/openjdk21-corretto/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#24949 openjdk17-corretto: update to 17.0.12.7.1
  java/openjdk17-corretto/Portfile
Labels: type: update, maintainer, maintainer: open, by: member
