Repository macports/macports-ports, pull requests merged in 2025-10, with the labels that each got.

#29509 antlr: Fix mistake, remove noarch
  lang/antlr/Portfile
Labels: type: bugfix, maintainer, maintainer: open

#29517 libressl: update to 4.1.1
  security/libressl/Portfile
Labels: type: bugfix, type: update, maintainer, maintainer: open

#29510 fish: update to 4.1.1
  shells/fish/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer, maintainer: open

#29468 arpwatch: Attempt to fix build with macOS 26 SDK
  net/arpwatch/Portfile
  net/arpwatch/files/_getshort.patch
Labels: maintainer: open, by: member

#29512 lychee: Update to 0.20.1
  devel/lychee/Portfile
Labels: type: update, maintainer: open

#29521 openjdk21-jetbrains: update to 21.0.8-b1140.54
  java/openjdk21-jetbrains/Portfile
Labels: type: update, maintainer: open, by: member

#29525 openjdk25: build without -reproducible flag on macOS 12 and older
  java/openjdk25/Portfile
  java/openjdk25/files/non-reproducible.diff
Labels: maintainer, maintainer: open, by: member

#29523 openjdk25-microsoft: add earliest end-of-support date
  java/openjdk25-microsoft/Portfile
Labels: maintainer, maintainer: open, by: member

#29526 legacy-support: Update to v1.5.2.
  devel/legacy-support/Portfile
Labels: type: update, maintainer, maintainer: open

#29528 mise: Update to 2025.10.0
  sysutils/mise/Portfile
Labels: type: update, maintainer, maintainer: open

#29529 libfido2: update source
  security/libfido2/Portfile
Labels: type: update, maintainer, maintainer: open

#29531 symfony-cli: update to 5.15.0
  devel/symfony-cli/Portfile
Labels: type: update, maintainer, maintainer: open

#29522 ctris: update to v0.43
  games/ctris/Portfile
  games/ctris/files/patch-version.diff
Labels: type: enhancement, type: update, maintainer: none

#29519 qt6-qtcreator: update to v17.0.2
  devel/qt6-qtcreator/Portfile
Labels: type: update, maintainer, maintainer: open

#29493 funky: update to 3.5.5
  sysutils/funky/Portfile
Labels: type: enhancement, type: update, maintainer: open

#29533 lagrange: update to 1.19.3
  net/lagrange/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#29507 osm2pgsql: update to 2.2.0
  gis/osm2pgsql/Portfile
Labels: type: enhancement, type: update, maintainer: open

#29430 libsidplayfp: fix build with C11 compilers
  audio/libsidplayfp/Portfile
  audio/libsidplayfp/files/patch-fix-pre-cxx20.diff
Labels: maintainer: open

#29516 fossil: update to 2.27
  devel/fossil/Portfile
Labels: type: update, maintainer: open

#29416 macos-trash: Update to 2.0.0
  sysutils/macos-trash/Portfile
Labels: type: update, maintainer: open

#29543 jsoncons: update to 1.4.2
  devel/jsoncons/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#29545 cclient: fix for changed definiton of scandir
  mail/cclient/Portfile
  mail/cclient/files/scandir.patch
Labels: type: bugfix, maintainer: none

#29544 symfony-cli: update to 5.15.1
  devel/symfony-cli/Portfile
Labels: type: update, maintainer, maintainer: open

#29550 gallery-dl: update to 1.30.9
  net/gallery-dl/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer, maintainer: open

#29553 got: update to 0.120
  devel/got/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#29549 lbreakout2: update to 2.6.5
  games/lbreakout2/Portfile
Labels: type: enhancement, type: update, maintainer: none

#29558 bs: update to v2.13
  games/bs/Portfile
Labels: type: enhancement, type: update, maintainer: none

#29562 openssh: update to 10.1p1
  net/openssh/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer, type: security fix, maintainer: open

#29567 ecCodes: update to 2.44.0
  science/ecCodes/Portfile
Labels: type: update, maintainer, maintainer: open

#29566 mysql56: force pre-2017 C++ standard
  databases/mysql56/Portfile
Labels: maintainer: none

#29561 uncrustify: update to v0.81.0
  devel/uncrustify/Portfile
Labels: type: enhancement, type: update, maintainer: none

#29554 librssl-devel: update to 4.1.1
  security/libressl-devel/Portfile
Labels: type: bugfix, type: update, maintainer, maintainer: open

#29546 arduino-cli: update to 1.3.1
  devel/arduino-cli/Portfile
Labels: type: enhancement, type: update, maintainer: open

#29570 gemini-cli: new port
  llm/gemini-cli/Portfile
Labels: type: submission, by: member

#29572 google-cloud-sdk: update to 542.0.0
  devel/google-cloud-sdk/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#29573 k9s: update to 0.50.15
  sysutils/k9s/Portfile
Labels: type: update, maintainer, maintainer: open, by: member
