Repository macports/macports-ports, pull requests merged in 2025-02, with the labels that each got.

#27554 pooler: Update to 1.89
  science/pooler/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#27557 tippecanoe: update to 2.75.0
  gis/tippecanoe/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#27542 ngspice: update to version 44.2
  science/ngspice/Portfile
Labels: type: update, maintainer, maintainer: open

#27549 wine-*: Fix platforms & building on macOS High Sierra
  emulators/wine-devel/Portfile
  emulators/wine-stable/Portfile
Labels: type: bugfix, maintainer

#27559 mise: Update to 2025.1.17
  sysutils/mise/Portfile
Labels: type: update, maintainer, maintainer: open

#27548 Lazarus: update to 3.8 and fixes for qt4 and gtk2 variants.
  devel/lazarus/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer, maintainer: open

#27532 girara: update to version 0.4.5
  devel/girara/Portfile
Labels: type: update, maintainer: open

#27562 vile: Update to 9.8za
  editors/vile/Portfile
Labels: type: bugfix, type: update, maintainer: none

#27560 ocrmypdf: update to 16.8.0
  textproc/ocrmypdf/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer, maintainer: open

#27567 py-nbconvert: add missing dependency to py-jupyterlab_pygments
  python/py-nbconvert/Portfile
Labels: type: bugfix, maintainer: open

#27566 mise: Update to 2025.2.0
  sysutils/mise/Portfile
Labels: type: update, maintainer, maintainer: open

#27550 * Perl 5 has been updated to version 5.38.3.
  lang/perl5/Portfile
Labels: maintainer: none

#27564 bettercap: patch default caplets path
  net/bettercap/Portfile
Labels: type: enhancement, maintainer: open, by: member

#27561 bzip3: update to 1.5.1
  archivers/bzip3/Portfile
Labels: type: update, maintainer: open

#27438 1password: Update to provide completions on install
  security/1password-cli/Portfile
Labels: type: enhancement, type: update, maintainer: open

#27574 fswatch: update to 1.18.3
  sysutils/fswatch/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#27572 josm: update to 19307
  gis/JOSM/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#27571 snac: update to 2.71
  net/snac/Portfile
Labels: type: bugfix, type: update, maintainer, maintainer: open

#27568 Gildas: update to 202502b
  science/gildas/Portfile
  science/gildas/files/patch-admin-Makefile.build.diff
  science/gildas/files/patch-admin-Makefile.def.diff
  science/gildas/files/patch-admin-Makefile.python.diff
  science/gildas/files/patch-admin-define-system.sh.diff
  science/gildas/files/patch-admin-gildas-env.sh.diff
  science/gildas/files/patch-admin-python-config-ldflags.py.diff
Labels: type: enhancement, type: update, maintainer

#27563 py-pyobjc: update to 10.3.2
  python/py-pyobjc/Portfile
  python/py-pyobjc/files/patch-setup-no-werror.diff
Labels: type: update, maintainer: open

#27558 elixir: update to 1.18.2
  lang/elixir/Portfile
Labels: type: enhancement, type: update, maintainer: open

#27577 man: Fixes C99 implicit int errors in configure script
  sysutils/man/Portfile
  sysutils/man/files/patch-int-main.diff
Labels: type: bugfix, type: update, maintainer: none

#27575 ruby-build: Update to 20250205
  ruby/ruby-build/Portfile
Labels: type: update, maintainer, maintainer: open

#27425 Volk: Update to 3.1.2 and add Python 3.11 and 3.12 variants
  science/volk/Portfile
  science/volk/files/patch-cpu_features-add-support-for-ARM64.diff
Labels: type: enhancement, type: update, maintainer: requires approval, maintainer: timeout

#27578 ImageMagick7: Update to 7.1.1-43
  graphics/ImageMagick7/Portfile
Labels: type: update, maintainer, maintainer: open

#27580 google-cloud-sdk: update to 509.0.0
  devel/google-cloud-sdk/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#27581 openjdk24-zulu: update to 24.0.77
  java/openjdk24-zulu/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#27573 pymol: Update to 3.1.0 release
  science/pymol/Portfile
  science/pymol/files/setup.py.diff
Labels: type: update, maintainer, maintainer: open

#27579 lapack: Update to 3.12.1
  math/lapack/Portfile
  math/lapack/files/patch-version-nums.3.12.1-ONLY.diff
Labels: type: update, maintainer, maintainer: open

#27587 ghidra: update to 11.3
  devel/ghidra/Portfile
Labels: type: update, maintainer, maintainer: open

#27586 qgis3: fix python patch
  gis/qgis3/Portfile
Labels: maintainer, maintainer: open

#27584 gdal: always look for mpi variant
  gis/gdal/Portfile
Labels: maintainer, maintainer: open

#27582 uxn: update to 20250131
  emulators/uxn/Portfile
Labels: type: update, maintainer: none

#27590 swi-prolog-devel: Updated to version 9.3.20
  lang/swi-prolog-devel/Portfile
Labels: type: update, maintainer, maintainer: open

#27570 pnpm: update to 10.2.1, add nodejs ver fallback
  devel/pnpm/Portfile
Labels: type: enhancement, type: update, maintainer: open, by: member

#27597 gcovr: update to 8.3
  devel/gcovr/Portfile
  devel/gcovr/files/relax-hatchling-version.patch
Labels: type: update, maintainer: none

#27591 gdal-grass: update to 1.0.3, build with CMake
  gis/gdal-grass/Portfile
Labels: type: update, maintainer, maintainer: open

#27589 bitwarden-cli: update to version 2025.1.3
  security/bitwarden-cli/Portfile
Labels: type: enhancement, type: update, maintainer: open

#27583 openjpeg: update to 2.5.3
  graphics/openjpeg/Portfile
Labels: type: update, maintainer: open

#27263 proxy-audio-device: fix 1.0.7 Portfile
  audio/proxy-audio-device/Portfile
Labels: type: bugfix, maintainer: none

#27225 qbs: Fix building on 10.14
  devel/qbs/Portfile
Labels: type: bugfix, maintainer: open

#27592 bitcoin: update to 28.1
  finance/bitcoin/Portfile
Labels: type: update, maintainer: open

#27585 timg: update to 1.6.1
  graphics/timg/Portfile
  graphics/timg/files/0001-timg.cc-define-__STDC_FORMAT_MACROS-if-undefined.patch
Labels: type: update, maintainer: open

#27603 sqlite3: Avoid rpath; tweak install name
  databases/sqlite3/Portfile
  databases/sqlite3/files/no-rpath.patch
Labels: maintainer: open, by: member

#27606 dosbox-x: update to 2025.02.01
  emulators/dosbox-x/Portfile
Labels: type: update, maintainer: none

#27600 ocaml-uri and geneweb: bump revision as ocaml-angstrom was updated
  genealogy/geneweb/Portfile
  ocaml/ocaml-uri/Portfile
Labels: type: bugfix, maintainer, maintainer: open

#27599 xcode-build-server: update to v1.2.0
  devel/xcode-build-server/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#27608 podman: update to 5.3.2
  sysutils/podman/Portfile
Labels: type: enhancement, type: update, maintainer: open

#27610 libutf8proc: update to 2.10.0
  textproc/libutf8proc/Portfile
Labels: type: update, maintainer: open

#27607 gvisor-tap-vsock: update to 0.8.3
  net/gvisor-tap-vsock/Portfile
Labels: type: update, maintainer: open

#27609 vfkit: update to 0.6.0
  sysutils/vfkit/Portfile
Labels: type: update, maintainer: open

#27601 sshuttle: update to 1.2.0
  net/sshuttle/Portfile
Labels: type: enhancement, type: update, maintainer: open

#27602 yazi: Update to version 25.2.7
  sysutils/yazi/Portfile
Labels: type: update, maintainer: open

#27611 wasmtime: update to 29.0.1
  devel/wasmtime/Portfile
Labels: type: update, maintainer: open

#27619 legacy-support: update to v1.4.0.
  devel/legacy-support/Portfile
Labels: type: update, maintainer, maintainer: open

#27614 mise: Update to 2025.2.3
  sysutils/mise/Portfile
Labels: type: update, maintainer, maintainer: open

#27617 luv: update to 1.50.0-1
  devel/luv/Portfile
Labels: type: update, maintainer: open

#27622 gdal: fix typos
  gis/gdal/Portfile
Labels: maintainer, maintainer: open

#27626 wine-devel,wine-staging: Update to 10.1
  emulators/wine-devel/Portfile
Labels: type: update, maintainer

#27616 luajit: update to 2.1.1736781742
  lang/luajit/Portfile
Labels: type: update, maintainer: none

#27627 clojure: update to 1.12.0.1517
  lang/clojure/Portfile
Labels: type: update, maintainer, maintainer: open

#27628 snac: update to 2.72
  net/snac/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer, maintainer: open

#27630 symfony-cli: update to 5.10.7
  devel/symfony-cli/Portfile
Labels: type: update, maintainer, maintainer: open

#27631 micronaut: update to 4.7.5
  java/micronaut/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#27632 skaffold: update to 2.14.1
  devel/skaffold/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#27634 google-cloud-sdk: update to 510.0.0
  devel/google-cloud-sdk/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#27623 stimfit: update to version 0.16.6
  science/stimfit/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer

#27635 ruby-build: Update to 20250212
  ruby/ruby-build/Portfile
Labels: type: update, maintainer, maintainer: open

#27604 py-awscli2: add python 3.13
  python/py-awscli2/Portfile
Labels: type: enhancement, maintainer: open

#27637 jujutsu: update to 0.26.0
  devel/jujutsu/Portfile
Labels: type: update, maintainer: open

#27646 lima: Update to 1.0.6
  sysutils/lima/Portfile
Labels: type: update, maintainer, maintainer: open

#27645 pilrc: fix BMP loader
  palm/pilrc/Portfile
  palm/pilrc/files/64bit.diff
  palm/pilrc/files/fix-resource-list.diff
Labels: type: bugfix, maintainer, maintainer: open

#27647 hamlib: Update to v4.6.2
  science/hamlib/Portfile
Labels: type: update, maintainer: open

#27650 Legcord: update to 1.1.0
  net/Legcord/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer, maintainer: open

#27621 liboggz: update to 1.1.2
  audio/liboggz/Portfile
Labels: type: update, maintainer: requires approval, maintainer: timeout

#27661 uv: Update to 0.6.0
  devel/uv/Portfile
Labels: type: update, maintainer, maintainer: open

#27662 ipatool: Update to 2.1.6
  sysutils/ipatool/Portfile
Labels: type: update, maintainer, maintainer: open

#27660 ruby-build: Update to 20250215
  ruby/ruby-build/Portfile
Labels: type: update, maintainer, maintainer: open

#27656 tcsh: update to 6.24.15
  shells/tcsh/Portfile
Labels: type: update, maintainer: none

#27659 bfs: update to 4.0.5
  sysutils/bfs/Portfile
Labels: type: update, maintainer: open

#27658 unrar: update to 7.1.3
  archivers/unrar/Portfile
Labels: type: update, maintainer: none

#27657 vnstat: update to 2.13
  net/vnstat/Portfile
Labels: type: update, maintainer: none

#27653 logtalk: update to 3.89.0
  lang/logtalk/Portfile
Labels: type: update, maintainer

#27654 yabai: update to 7.1.10
  sysutils/yabai/Portfile
  sysutils/yabai/files/patch-makefile-macos11.diff
  sysutils/yabai/files/patch-makefile.diff
  sysutils/yabai/files/patch-workspace.m-macos11.diff
Labels: type: update, maintainer, maintainer: open

#27664 mise: Update to 2025.2.4
  sysutils/mise/Portfile
Labels: type: update, maintainer, maintainer: open

#27615 unibilium: update to 2.1.2
  devel/unibilium/Portfile
  devel/unibilium/files/patch-Makefile.diff
Labels: type: update, maintainer: none

#27668 tippecanoe: update to 2.75.1
  gis/tippecanoe/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#27667 jsoncons: update to 1.2.0
  devel/jsoncons/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#27672 openjdk21-openj9: update to 21.0.6
  java/openjdk21-openj9/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#27673 openjdk23-openj9: update to 23.0.2
  java/openjdk23-openj9/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#27676 openjdk8-openj9: update to 8u442
  java/openjdk8-openj9/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#27675 openjdk11-openj9: update to 11.0.26
  java/openjdk11-openj9/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#27666 GPXSee: update to 13.35
  gis/GPXSee/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#27636 sdcc: update to 4.5.0
  lang/sdcc/Portfile
Labels: type: bugfix, type: update, maintainer: open

#27651 stimfit: update to version 0.16.6_1
  science/stimfit/Portfile
Labels: type: enhancement, type: update, maintainer

#27679 ipsw: Update to 3.1.570
  security/ipsw/Portfile
Labels: type: update, maintainer, maintainer: open

#27678 g-ls: Update to 0.29.1
  sysutils/g-ls/Portfile
Labels: type: update, maintainer, maintainer: open

#27677 tlrc: Update to 1.10.0
  net/tlrc/Portfile
Labels: type: update, maintainer, maintainer: open

#27680 mise: Update to 2025.2.5
  sysutils/mise/Portfile
Labels: type: update, maintainer, maintainer: open

#27685 Update libframe to 8.48.4
  science/libframe/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#27686 mise: Update to 2025.2.6
  sysutils/mise/Portfile
Labels: type: update, maintainer, maintainer: open

#27688 gum: Update to 0.15.2
  devel/gum/Portfile
Labels: type: update, maintainer: open

#27687 py-awscli2: update to 2.24.5
  python/py-awscli2/Portfile
  python/py-awscli2/files/patch-requirements.diff
Labels: type: enhancement, type: update, maintainer, maintainer: open

#27693 kubectl-1.29-32: update to latest
  sysutils/kubectl/Portfile
Labels: maintainer, maintainer: open, by: member

#27694 symfony-cli: update to 5.11.0
  devel/symfony-cli/Portfile
Labels: type: update, maintainer, maintainer: open

#27692 fzf: update to 0.60.0
  sysutils/fzf/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#27696 hdf5: 1.14.6 py-h5py: Add 313
  python/py-h5py/Portfile
  science/hdf5/Portfile
Labels: maintainer, maintainer: open, by: member

#27702 logtalk: update to 3.89.1
  lang/logtalk/Portfile
Labels: type: update, maintainer

#27703 2048.c: Update to 1.0.3
  games/2048.c/Portfile
Labels: type: update, maintainer, maintainer: open

#27709 rsgislib: update to 5.1.8
  gis/rsgislib/Portfile
Labels: type: update, maintainer, maintainer: open

#27705 gitu: Update to 0.28.1
  devel/gitu/Portfile
Labels: type: update, maintainer, maintainer: open

#27704 ruff: Update to 0.9.6
  devel/ruff/Portfile
Labels: type: update, maintainer, maintainer: open

#27712 openssh: update to 9.9p2
  net/openssh/Portfile
Labels: type: bugfix, type: update, maintainer, type: security fix, maintainer: open

#27697 alacritty: update to 0.15.1
  aqua/alacritty/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer, maintainer: open

#27716 unicorn: update to 2.1.2
  devel/unicorn/Portfile
Labels: type: update, maintainer, maintainer: open

#27713 qemu: update to 9.2.1, use python 3.13
  emulators/qemu/Portfile
Labels: type: enhancement, type: update, maintainer: open, by: member

#27722 gitleaks: Update to 8.24.0
  security/gitleaks/Portfile
Labels: type: update, maintainer: open

#27719 apache-solr8: Update to version 8.11.4
  java/apache-solr8/Portfile
Labels: type: update, maintainer, maintainer: open

#27715 lcms2: update to 2.17
  graphics/lcms2/Portfile
Labels: type: update, maintainer: none

#27682 yash: update to version 2.58.1
  shells/yash/Portfile
Labels: type: update, maintainer: open

#27726 spring-boot-cli: update to 3.4.3
  java/spring-boot-cli/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#27723 gtk-doc: add and default to python 3.13 variant
  gnome/gtk-doc/Portfile
Labels: type: enhancement, maintainer: open, by: member

#27728 legacy-support-devel: Update to latest master - v20250220.
  devel/legacy-support/Portfile
Labels: type: update, maintainer, maintainer: open

#27730 g-ls: Update to 0.29.2
  sysutils/g-ls/Portfile
Labels: type: update, maintainer, maintainer: open

#27729 gitu: Update to 0.28.2
  devel/gitu/Portfile
Labels: type: update, maintainer, maintainer: open

#27725 py-graph-tool: Update to version 2.91
  python/py-graph-tool/Portfile
Labels: type: update, maintainer, maintainer: open

#27735 unrar: update to 7.1.4
  archivers/unrar/Portfile
Labels: type: update, maintainer: none

#27734 sv1-av1: use port:git on macOS <10.9
  multimedia/svt-av1/Portfile
Labels: maintainer: open

#27724 typst: Update to version 0.13.0
  textproc/typst/Portfile
Labels: type: update, maintainer: open

#27737 google-cloud-sdk: update to 511.0.0
  devel/google-cloud-sdk/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#27736 orc: update to 0.4.41
  devel/orc/Portfile
Labels: type: update, maintainer: none

#27733 ghidra: Update to 11.3.1
  devel/ghidra/Portfile
Labels: type: update, maintainer, maintainer: open

#27727 solidity: update to version 0.8.28
  lang/solidity/Portfile
  lang/solidity/files/fmtlib.cmake
  lang/solidity/files/jsoncpp.cmake
  lang/solidity/files/patch-CMakeLists.txt.diff
  lang/solidity/files/patch-cmake_range-v3.cmake.diff
  lang/solidity/files/patch-libsolutil_JSON.cpp.diff
  lang/solidity/files/patch-libyul_ObjectOptimizer.cpp.diff
  lang/solidity/files/test.sol
Labels: type: enhancement, type: update, maintainer, maintainer: open

#27689 pcre2: update to 10.45
  devel/pcre/Portfile
Labels: type: enhancement, type: update, maintainer: requires approval, maintainer: timeout

#27655 openssl3: fix build on macOS =<10.6 i386/PowerPC
  devel/openssl3/Portfile
  devel/openssl3/files/0001-revert-rcu.diff
  devel/openssl3/files/0002-use-atomic-relaxed.diff
  devel/openssl3/files/0003-dont-use-atomic-acq-rel.diff
Labels: maintainer: open

#27738 zlog: new port
  devel/zlog/Portfile
Labels: type: enhancement, type: submission

#27740 simplotask: update to 1.16.4
  sysutils/simplotask/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#27739 paho.mqtt.cpp: update to 1.5.1
  net/paho.mqtt.cpp/Portfile
Labels: type: enhancement, type: update, maintainer: none

#27742 presenterm: update to 0.10.1
  graphics/presenterm/Portfile
Labels: type: enhancement, type: update, maintainer: open

#27741 ruff: Update to 0.9.7
  devel/ruff/Portfile
Labels: type: update, maintainer, maintainer: open

#27714 Update py-gnureadline to 8.2.13; add py313 flavor
  python/py-gnureadline/Portfile
  python/py-gnureadline/files/patch-readline_not_editline.diff
  python/py-gnureadline/files/setup.py.patch
Labels: type: update, maintainer: open

#27745 rebels-in-the-sky: Update to 1.0.29
  games/rebels-in-the-sky/Portfile
Labels: type: update, maintainer, maintainer: open

#27750 chezmoi: Update to 2.60.0
  sysutils/chezmoi/Portfile
Labels: type: update, maintainer: open

#27707 py-h5py: update build dependencies
  python/py-h5py/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer: open, by: member

#27753 jaq: Update to 2.1.1
  textproc/jaq/Portfile
Labels: type: update, maintainer: open

#27752 offpunk: update to 2.5
  net/offpunk/Portfile
Labels: type: update, maintainer: none

#27751 tnylpo: update to 1.1.7
  emulators/tnylpo/Portfile
Labels: type: update, maintainer, maintainer: open

#27748 openh264: update to 2.6.0 (CVE-2025-27091)
  multimedia/openh264/Portfile
  multimedia/openh264/files/0001-meson.build-add-powerpc-arch.patch
  multimedia/openh264/files/meson-build-do-not-hardcode-libc-on-darwin.diff
  multimedia/openh264/files/no-Werror.patch
Labels: type: update, type: security fix, maintainer: none

#27743 zlog: fix build on macOS <10.9
  devel/zlog/Portfile
  devel/zlog/files/patch-stdint.diff
Labels: maintainer: open

#27761 tree-sitter: update to 0.25.2
  devel/tree-sitter/Portfile
Labels: type: update, maintainer: open
