Repository macports/macports-ports, pull requests merged in 2025-05, with the labels that each got.

#28302 uv: Update to 0.7.1
  devel/uv/Portfile
Labels: type: update, maintainer, maintainer: open

#28312 krep: fix build on macOS <10.12
  textproc/krep/Portfile
Labels: maintainer: open

#28311 algol68g: update to 3.5.14
  lang/algol68g/Portfile
Labels: type: update, maintainer: none

#28307 ruby-build: Update to 20250430
  ruby/ruby-build/Portfile
Labels: type: update, maintainer, maintainer: open

#28305 jpegoptim: fix build on macOS <10.7
  graphics/jpegoptim/Portfile
Labels: maintainer: open

#28299 imlib2: update to 1.12.5
  graphics/imlib2/Portfile
Labels: type: update, maintainer: none

#28313 oh-my-posh: update to version 25.20.0
  sysutils/oh-my-posh/Portfile
Labels: type: update, maintainer, maintainer: open

#28314 krep: blacklist clang < 700 for stdatomic.h
  textproc/krep/Portfile
Labels: maintainer: open

#28300 tig: Update to 2.5.12
  devel/tig/Portfile
Labels: type: bugfix, type: update, maintainer: open

#28304 liboggz: update to 1.1.3
  audio/liboggz/Portfile
Labels: type: update, maintainer: requires approval

#28316 yt-dlp: updated to 2025-04-30
  net/youtube-dl/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer: requires approval

#28317 MoltenVK: update to 1.3.0
  graphics/MoltenVK/Portfile
Labels: type: update, maintainer, maintainer: open

#28308 LBFGSpp: update to 0.4.0
  math/LBFGSpp/Portfile
Labels: type: update, maintainer: open

#28319 codemod: switch to use python3.13
  devel/codemod/Portfile
Labels: type: enhancement, maintainer: none

#28315 esmf: Fix builds for 10.8-10.10
  science/esmf/Portfile
Labels: type: bugfix, maintainer, maintainer: open

#28318 sunclock: add link to github repo
  x11/sunclock/Portfile
Labels: type: enhancement, maintainer: none

#28310 mfem: update to 4.8
  science/mfem/Portfile
Labels: type: update, maintainer: open

#28309 crossgcc: add build dep texinfo
  _resources/port1.0/group/crossgcc-1.0.tcl
Labels: type: bugfix

#28280 docbook-xsl: fix infinite recursion for e.g. samba
  textproc/docbook-xsl/Portfile
  textproc/docbook-xsl/files/patch-libxsl.diff
Labels: type: bugfix, maintainer: open

#28273 scalapack: fix duplicate rpaths warning/error
  math/scalapack/Portfile
Labels: type: bugfix, maintainer: none

#28269 mesa: fix build on Tiger
  x11/mesa/Portfile
  x11/mesa/files/patch-missing-mach-init-include.patch
Labels: type: bugfix, maintainer: open

#28327 mise: Update to 2025.5.0
  sysutils/mise/Portfile
Labels: type: update, maintainer, maintainer: open

#28325 eask-cli: update to 0.11.3
  devel/eask-cli/Portfile
Labels: type: update, maintainer, maintainer: open

#28328 gitlab-runner: update version to 17.11.0
  devel/gitlab-runner/Portfile
Labels: type: enhancement, type: update, maintainer: open

#28324 qgis3: add and default to python 3.13
  gis/qgis3/Portfile
Labels: maintainer: open, by: member

#28326 esmf: Fix builds for 10.6-10.8
  science/esmf/Portfile
  science/esmf/files/patch-task_vm_info_missing.diff
Labels: type: bugfix, maintainer, maintainer: open

#28332 gallery-dl: update to 1.29.6
  net/gallery-dl/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer, maintainer: open

#28338 libtorrent-rasterbar: add and default to python313
  net/libtorrent-rasterbar/Portfile
Labels: type: enhancement, maintainer, maintainer: open, by: member

#28341 OpenIPMI: 2.0.37
  sysutils/OpenIPMI/Portfile
Labels: maintainer, maintainer: open, by: member

#28336 crossgcc: always install texinfo
  _resources/port1.0/group/crossgcc-1.0.tcl
Labels: type: bugfix

#28333 wine-devel,wine-staging: Update to 10.7
  emulators/wine-devel/Portfile
Labels: type: update, maintainer

#28343 syncthing: update to 1.29.6
  net/syncthing/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#28342 ccache: update to 4.11.3
  devel/ccache/Portfile
Labels: type: update, maintainer: open

#28349 mise: Update to 2025.5.1
  sysutils/mise/Portfile
Labels: type: update, maintainer, maintainer: open

#28352 google-cloud-sdk: update to 521.0.0
  devel/google-cloud-sdk/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#28353 fheroes2: update to 1.1.8
  games/fheroes2/Portfile
Labels: type: update, maintainer, maintainer: open

#28351 pinact: Update to 3.1.0-0
  security/pinact/Portfile
Labels: type: update, maintainer, maintainer: open

#28347 gitu: Update to 0.31.0
  devel/gitu/Portfile
Labels: type: update, maintainer, maintainer: open

#28355 openjdk25-zulu: update to 25.0.33
  java/openjdk25-zulu/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#28356 skaffold: update to 2.16.0
  devel/skaffold/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#28357 libpng: update to 1.6.48
  graphics/libpng/Portfile
Labels: type: update, maintainer: requires approval

#28340 iverilog: fix implicit declaration error
  science/iverilog/Portfile
  science/iverilog/files/patch-fix-headers.diff
Labels: maintainer: open

#28354 ghostscript: update to 10.05.1
  print/ghostscript/Portfile
Labels: type: update, maintainer: none

#28350 esmf: Fix builds for 10.6
  science/esmf/Portfile
  science/esmf/files/patch.FieldEmpty_cppF90.diff
Labels: type: bugfix, maintainer, maintainer: open

#28348 tlrc: Update to 1.11.1
  net/tlrc/Portfile
Labels: type: update, maintainer, maintainer: open

#28334 get_iplayer: update to 3.36
  net/get_iplayer/Portfile
Labels: type: update, maintainer: open

#28296 FreeRDP: update to version 3.15.0
  net/FreeRDP/Portfile
  net/FreeRDP/files/findffmpeg-prefix.diff
  net/FreeRDP/files/patch-cmake-docbook.diff
  net/FreeRDP/files/patch-cmake_ignore_build_type.diff
Labels: type: bugfix, type: update, maintainer: none

#28244 git-crypt: update to 0.7.0, use local manpage xsl
  devel/git-crypt/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer: open

#28359 eask-cli: update to 0.11.4
  devel/eask-cli/Portfile
Labels: type: update, maintainer, maintainer: open

#28362 openjdk17-openj9: update to 17.0.15
  java/openjdk17-openj9/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#28363 openjdk11-openj9: update to 11.0.27
  java/openjdk11-openj9/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#28364 openjdk8-openj9: update to 8u452
  java/openjdk8-openj9/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#28367 ruby-build: Update to 20250507
  ruby/ruby-build/Portfile
Labels: type: update, maintainer, maintainer: open

#28366 mise: Update to 2025.5.2
  sysutils/mise/Portfile
Labels: type: update, maintainer, maintainer: open

#28368 zizmor: Update to 1.7.0
  security/zizmor/Portfile
Labels: type: update, maintainer, maintainer: open

#28373 snac: update to 2.76
  net/snac/Portfile
  net/snac/files/Makefile.patch
Labels: type: bugfix, type: enhancement, type: update, maintainer, maintainer: open

#28372 josm: update to 19396
  gis/JOSM/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#28370 yabai: update to 7.1.14
  sysutils/yabai/Portfile
Labels: type: update, maintainer, maintainer: open

#28374 mise: Update to 2025.5.3
  sysutils/mise/Portfile
Labels: type: update, maintainer, maintainer: open

#28377 tippecanoe: update to 2.78.0
  gis/tippecanoe/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#28344 go-tools: update to 0.33.0
  devel/go-tools/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#28379 qemu: update to 10.0.0
  emulators/qemu/Portfile
Labels: type: enhancement, type: update, type: security fix, maintainer: open

#28381 pdfjam: update to 4.2
  textproc/pdfjam/Portfile
Labels: type: update, maintainer: open, by: member

#28375 nlohmann-json: Update to 3.12.0
  devel/nlohmann-json/Portfile
Labels: type: update, maintainer: open

#28390 osxphotos: update to 0.70.0
  graphics/osxphotos/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#28392 miniflux: update to 2.2.8
  net/miniflux/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#28389 oxker: update to 0.10.3
  devel/oxker/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#28388 newsraft: update to 0.30
  net/newsraft/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#28387 GPXSee: update to 13.42
  gis/GPXSee/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#28384 tenv: update to 4.6.2
  sysutils/tenv/Portfile
Labels: type: update, maintainer, maintainer: open

#28383 telescope: update to 0.11
  net/telescope/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#28385 oksh: update to 7.7
  shells/oksh/Portfile
Labels: type: update, maintainer: open

#28401 chezmoi: Update to 2.62.4
  sysutils/chezmoi/Portfile
Labels: type: update, maintainer: open

#28405 et: update to 6.2.9
  net/et/Portfile
Labels: type: update, maintainer: open

#28407 oh-my-posh: update to version 25.23.0
  sysutils/oh-my-posh/Portfile
Labels: type: update, maintainer, maintainer: open

#28397 Bear: update to 3.1.6, update dependencies
  devel/Bear/Portfile
Labels: type: update, maintainer: open

#28410 snac: update to 2.77
  net/snac/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#28409 shadowsocks-rust: update to v1.23.4
  net/shadowsocks-rust/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#28411 imposm: update to 0.14.2
  gis/imposm/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#28406 imager: update to V4.5-01 (may25)
  science/imager/Portfile
  science/imager/files/greg.in
  science/imager/files/imager.in
  science/imager/files/sic.in
  science/imager/files/viewer.in
Labels: type: update, maintainer

#28380 openjdk21-jetbrains: update to 21.0.7-b982.16
  java/openjdk21-jetbrains/Portfile
Labels: type: update, maintainer: open, by: member

#28358 dagger: update to 0.18.6
  devel/dagger/Portfile
Labels: type: update, maintainer: open

#28412 virglrenderer: Avoid binary when libepoxy is +quartz
  graphics/virglrenderer/Portfile
Labels: type: bugfix, maintainer: open, by: member

#28253 openssh: update to 10.0p2
  net/openssh/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer, maintainer: open

#28417 opensmtpd: update to 7.7.0p0
  mail/opensmtpd/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer

#28416 pinact: Update to 3.1.1
  security/pinact/Portfile
Labels: type: update, maintainer, maintainer: open

#28415 gitleaks: Update to 8.26.0
  security/gitleaks/Portfile
Labels: type: update, maintainer: open

#28422 zmap: update to 4.3.4
  net/zmap/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer, maintainer: open

#28403 sshfs: update to 3.7.3
  fuse/sshfs/Portfile
  fuse/sshfs/files/patch-1a52814a4e4ccbc0774bb19bc655123398e407d5.diff
  fuse/sshfs/files/patch-5f767dec5b3fc07f665fdd4fbd9eb728a790f35f.diff
  fuse/sshfs/files/patch-70c8fd9031e7610bf182956a785f7fc8f104e0f7.diff
  fuse/sshfs/files/patch-a9eb71cb1cfd1ae2bb9bd58e2405fde9bb9f5e75.diff
  fuse/sshfs/files/patch-ccb6821019c19600110af6750e0d2395a9401617.diff
  fuse/sshfs/files/patch-configure.ac.diff
  fuse/sshfs/files/patch-ed0825440c48895b7e20cc1440bbafd8d9c88eb8.diff
  fuse/sshfs/files/sshfs.c.patch
Labels: type: enhancement, type: update, maintainer: open, by: member

#28400 protozero: update to 1.8.0
  devel/protozero/Portfile
Labels: type: update, maintainer: open

#28430 google-cloud-sdk: update to 522.0.0
  devel/google-cloud-sdk/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#28408 mosh: minor enhancements
  net/mosh/Portfile
Labels: type: enhancement, maintainer: open

#28399 astroid: update to 0.17
  mail/astroid/Portfile
Labels: type: update, maintainer: open

#28394 jc: update to 1.25.5
  sysutils/jc/Portfile
Labels: type: enhancement, type: update, maintainer: open

#28386 *-w64-mingw32-gcc: rev bump
  cross/i686-w64-mingw32-gcc/Portfile
  cross/x86_64-w64-mingw32-gcc/Portfile
Labels: type: bugfix, maintainer, maintainer: open

#28404 archivemount: fix building against new fuse3
  fuse/archivemount/Portfile
Labels: type: enhancement, maintainer: open, by: member

#28436 qt6-qtcreator: update to v16.0.2
  devel/qt6-qtcreator/Portfile
Labels: type: update, maintainer, maintainer: open

#28378 qemu: Fix compilation when macfuse is installed
  emulators/qemu/Portfile
Labels: type: bugfix, maintainer: open

#28438 mise: Update to 2025.5.4
  sysutils/mise/Portfile
Labels: type: update, maintainer, maintainer: open

#28453 libosmium: update to 2.22.0
  gis/libosmium/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer, maintainer: open

#28431 py-klein: update to 24.8.0
  python/py-klein/Portfile
Labels: type: update, maintainer: open

#28455 paho.mqtt.cpp: update to 1.5.3
  net/paho.mqtt.cpp/Portfile
Labels: type: enhancement, type: update, maintainer: none

#28424 zenmap: update to 7.97
  net/zenmap/Portfile
Labels: type: update, maintainer: requires approval, by: member

#28425 wireshark4: update to 4.4.6
  net/wireshark4/Portfile
Labels: type: update, maintainer: requires approval, by: member

#28421 genext2fs: update to 1.5.0
  sysutils/genext2fs/Portfile
Labels: type: update, maintainer: requires approval, maintainer: timeout

#26314 dbeaver-community: Update to 2024.2.3 and add `all_arches` variant.
  databases/dbeaver-community/Portfile
Labels: type: enhancement, type: update, maintainer: open

#27205 Critical: Update dotnetcli domain
  dotnet/aspnetcore-runtime-2.1/Portfile
  dotnet/aspnetcore-runtime-3.1/Portfile
  dotnet/aspnetcore-runtime-6/Portfile
  dotnet/aspnetcore-runtime-7/Portfile
  dotnet/aspnetcore-runtime-8/Portfile
  dotnet/aspnetcore-runtime-devel/Portfile
  dotnet/dotnet-cli/Portfile
  dotnet/dotnet-runtime-2.1/Portfile
  dotnet/dotnet-runtime-3.1/Portfile
  dotnet/dotnet-runtime-6/Portfile
  dotnet/dotnet-runtime-7/Portfile
  dotnet/dotnet-runtime-8/Portfile
  dotnet/dotnet-runtime-devel/Portfile
  dotnet/dotnet-sdk-2.1/Portfile
  dotnet/dotnet-sdk-3.1/Portfile
  dotnet/dotnet-sdk-6/Portfile
  dotnet/dotnet-sdk-7/Portfile
  dotnet/dotnet-sdk-8/Portfile
  dotnet/dotnet-sdk-devel/Portfile
Labels: type: update, maintainer: open

#27227 calendar-contacts-server: Fix build; Migrate to postgresql17; Deprecate APNS
  net/calendar-contacts-server/Portfile
  net/calendar-contacts-server/files/calendarserver.plist
  net/calendar-contacts-server/files/patch-build_python_venv.diff
Labels: type: bugfix, type: enhancement, maintainer, maintainer: open

#27510 QtPBFImagePlugin: Update to version 4.2
  graphics/QtPBFImagePlugin/Portfile
  graphics/QtPBFImagePlugin/files/patch-protobuf-dylib.diff
Labels: type: enhancement, type: update, maintainer: open

#27690 py-findpython: new port
  python/py-findpython/Portfile
Labels: type: enhancement, type: submission

#28458 kubectl: update 1.33, 1.32, 1.31, 1.30 subports
  sysutils/kubectl/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#28452 atuin: update to 18.6.1
  sysutils/atuin/Portfile
Labels: type: update, maintainer: open

#28467 ruby-build: Update to 20250516
  ruby/ruby-build/Portfile
Labels: type: update, maintainer, maintainer: open

#28463 dosbox-x: update to 2025.05.03
  emulators/dosbox-x/Portfile
Labels: type: update, maintainer: none

#28460 weechat: update to 4.6.3
  irc/weechat/Portfile
Labels: type: update, maintainer, maintainer: open

#28459 wireguard-go: update to 0.0.20250515
  net/wireguard-go/Portfile
  net/wireguard-go/files/patch-bump-deps-1.diff
  net/wireguard-go/files/patch-bump-deps-2.diff
Labels: type: update, maintainer, maintainer: open

#28456 simplotask: update to 1.17.0
  sysutils/simplotask/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#28465 presenterm: update to 0.13.0
  graphics/presenterm/Portfile
Labels: type: enhancement, type: update, maintainer: open

#28466 mise: Update to 2025.5.6
  sysutils/mise/Portfile
Labels: type: update, maintainer, maintainer: open

#28468 rebels-in-the-sky: Update to 1.0.30
  games/rebels-in-the-sky/Portfile
Labels: type: update, maintainer, maintainer: open

#28433 fpm: update to 0.11.0 and fix 71644
  _resources/port1.0/group/fortran-1.0.tcl
  devel/fpm/Portfile
  devel/fpm/files/patch-install.diff
Labels: type: bugfix, type: enhancement, type: update, maintainer: open

#28426 sshfs: request comaintainer
  fuse/sshfs/Portfile
Labels: maintainer: open, by: member

#28464 got: update to 0.112
  devel/got/Portfile
Labels: type: update, maintainer: open

#28470 audiowmark: update to 0.6.5
  audio/audiowmark/Portfile
Labels: type: update, maintainer, maintainer: open

#28398 macfuse: add fs_link variant
  fuse/macfuse/Portfile
Labels: type: enhancement, maintainer: open, by: member

#27778 mpack: fix configure and build failures
  mail/mpack/Portfile
  mail/mpack/files/cmulocal-bsd_sockets.m4.patch
  mail/mpack/files/configure.in.patch
Labels: type: bugfix, maintainer: none

#28298 catgirl-downloader: update to 0.2.8
  www/catgirl-downloader/Portfile
Labels: type: update, maintainer: open

#28469 mod_tile: update to 0.8.1
  gis/mod_tile/Portfile
  gis/mod_tile/files/README_MacPorts.md
  gis/mod_tile/files/osm_setup_db.sh
  gis/mod_tile/files/osmosis-db_replag.diff
Labels: type: bugfix, type: enhancement, type: update, maintainer, maintainer: open

#28434 mercurial: fix issues in port
  devel/mercurial/Portfile
  devel/mercurial/files/allow_rust.diff
  devel/mercurial/files/hg.diff
  devel/mercurial/files/makefile.diff
  devel/mercurial/files/rust_darwin.diff
  devel/mercurial/files/setup_py.diff
Labels: type: bugfix, maintainer, by: member

#28472 libxslt: Update to 1.1.43
  textproc/libxslt/Portfile
  textproc/libxslt/files/dynamic_lookup-11.patch
Labels: type: bugfix, type: update, type: security fix, maintainer: open

#28476 tabiew: new port
  textproc/tabiew/Portfile
Labels: type: enhancement, type: submission

#28482 mise: Update to 2025.5.8
  sysutils/mise/Portfile
Labels: type: update, maintainer, maintainer: open

#28483 pinact: Update to 3.1.2
  security/pinact/Portfile
Labels: type: update, maintainer, maintainer: open

#28473 openstreetmap-carto: update to 5.9.0
  gis/openstreetmap-carto/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#28477 timg: update to 1.6.2
  graphics/timg/Portfile
Labels: type: update, maintainer: open

#28471 openssh: remove remaining sandbox patch for 10.0p2
  net/openssh/Portfile
  net/openssh/files/com.openssh.sshd.sb
  net/openssh/files/patch-sandbox-darwin.c-apple-sandbox-named-external.diff
Labels: type: bugfix, maintainer: open

#28490 cppman: 0.5.9
  lang/cppman/Portfile
Labels: maintainer, maintainer: open, by: member

#28491 skim: update to 0.17.3
  sysutils/skim/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#28488 netdata: update to 2.5.1
  sysutils/netdata/Portfile
  sysutils/netdata/files/patch-pr-20145.diff
Labels: type: update, maintainer: open

#28492 zizmor: Upgrade to 1.8.0
  security/zizmor/Portfile
Labels: maintainer, maintainer: open

#28495 google-cloud-sdk: update to 523.0.0
  devel/google-cloud-sdk/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#28494 cdo: update to 2.5.2
  science/cdo/Portfile
Labels: type: update, maintainer, maintainer: open

#28496 n: update to 10.2
  devel/n/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#28498 cdargs: Add missing rev bump
  sysutils/cdargs/Portfile
Labels: type: bugfix, maintainer: open

#28499 duckdb: update to 1.3.0
  databases/duckdb/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#28505 mise: Update to 2025.5.9
  sysutils/mise/Portfile
Labels: type: update, maintainer, maintainer: open

#28502 wireguard-tools: update to 1.0.20250521
  net/wireguard-tools/Portfile
Labels: type: update, maintainer, maintainer: open

#28504 chromedriver: Update to version 136.0.7103.113
  www/chromedriver/Portfile
Labels: type: update, maintainer: none

#28507 eask-cli: update to 0.11.5
  devel/eask-cli/Portfile
Labels: type: update, maintainer, maintainer: open

#28506 lima: Update to 1.1.0
  sysutils/lima/Portfile
Labels: type: update, maintainer, maintainer: open
