Repository macports/macports-ports, pull requests merged in 2025-07, with the labels that each got.

#28792 libpng: update to 1.6.49
  graphics/libpng/Portfile
Labels: type: update, maintainer: requires approval

#28790 unrar: update to 7.1.8
  archivers/unrar/Portfile
Labels: type: update, maintainer: none

#28795 mise: Update to 2025.7.0
  sysutils/mise/Portfile
Labels: type: update, maintainer, maintainer: open

#28793 netdata: update to 2.5.4
  sysutils/netdata/Portfile
Labels: type: update, maintainer: open

#28773 got: update to 0.115
  devel/got/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer, maintainer: open

#28799 yt-dlp: update to 2025.06.30
  net/youtube-dl/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer: requires approval

#28800 google-cloud-sdk: update to 529.0.0
  devel/google-cloud-sdk/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#28801 eask-cli: update to 0.11.7
  devel/eask-cli/Portfile
Labels: type: update, maintainer, maintainer: open

#28791 bfs: update to 4.0.8
  sysutils/bfs/Portfile
Labels: type: update, maintainer: open

#28784 mockery: update to 3.5.0
  devel/mockery/Portfile
Labels: type: update, maintainer: open

#28796 dagger: update to 0.18.12
  devel/dagger/Portfile
Labels: type: update, maintainer: open

#28777 cabal: update to 3.14.2.0
  lang/cabal/Portfile
Labels: type: update, maintainer: open, by: member

#28776 stack: update to 3.7.1
  lang/stack/Portfile
Labels: type: update, maintainer: open, by: member

#28810 fricas: update to 1.3.12
  math/fricas/Portfile
Labels: type: update, maintainer, maintainer: open

#28806 direnv: Update to 2.37.0
  devel/direnv/Portfile
Labels: type: update, maintainer: open

#28813 auto-multiple-choice-devel: update to version 1.7.0-git 20250704122834
  x11/auto-multiple-choice/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer: none

#28805 openEMS: Rev bump for VTK-9.5.0 update
  science/openEMS/Portfile
Labels: type: bugfix, maintainer: open

#28816 carapace: fix homepage
  sysutils/carapace/Portfile
Labels: type: bugfix

#28817 mise: Update to 2025.7.1
  sysutils/mise/Portfile
Labels: type: update, maintainer, maintainer: open

#28820 oh-my-posh: update to version 26.14.3
  sysutils/oh-my-posh/Portfile
Labels: type: update, maintainer, maintainer: open

#28824 OCRmyPDF: update to 16.10.4
  textproc/ocrmypdf/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer, maintainer: open

#28828 snac: update to 2.80
  net/snac/Portfile
Labels: type: bugfix, type: update, maintainer, maintainer: open

#28825 chrony: add legacysupport portgroup for macOS 10.6 (strnlen)
  sysutils/chrony/Portfile
Labels: maintainer: open

#28808 nvm: Update to 0.40.3
  devel/nvm/Portfile
Labels: type: update, maintainer: open

#28802 py-service_identity: pin to last working version for py27
  python/py-service_identity/Portfile
Labels: maintainer: open

#28827 7zip: update to 25.0.0
  archivers/7zip/Portfile
Labels: type: enhancement, type: update, maintainer: open, by: member

#28836 pdal dependents: increase revision after PDAL update to 2.9.0
  gis/grass/Portfile
  gis/grass7/Portfile
  gis/qgis3/Portfile
Labels: maintainer, maintainer: open

#28826 libpng: update to 1.6.50
  graphics/libpng/Portfile
Labels: type: update, maintainer: requires approval

#28831 gdcm: update to 3.0.26
  science/gdcm/Portfile
  science/gdcm/files/CharLS-2.1.0.patch
  science/gdcm/files/patch-cstr.diff
  science/gdcm/files/patch-vtk.diff
Labels: type: update, maintainer: open

#28838 micronaut: update to 4.9.1
  java/micronaut/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#28840 mise: Update to 2025.7.3
  sysutils/mise/Portfile
Labels: type: update, maintainer, maintainer: open

#28843 uv: Update to 0.7.20
  devel/uv/Portfile
Labels: type: update, maintainer, maintainer: open

#28842 ipsw: Update to 3.1.621
  security/ipsw/Portfile
Labels: type: update, maintainer, maintainer: open

#28841 g-ls: Update to 0.31.0
  sysutils/g-ls/Portfile
Labels: type: update, maintainer, maintainer: open

#28846 nim: update to 2.2.4
  lang/nim/Portfile
Labels: type: update, maintainer, maintainer: open

#28851 Revert "x264: improve livecheck"
  multimedia/x264/Portfile
Labels: type: bugfix

#28850 fzy: update to 1.1
  devel/fzy/Portfile
Labels: type: update, maintainer: none

#28849 legacy-support-devel: Update to latest master - v20250711.
  devel/legacy-support/Portfile
Labels: type: update, maintainer, maintainer: open

#28856 py-llfuse: update to 1.5.1, add python 3.13 variant
  python/py-llfuse/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer: none

#28857 rspamd: Update to version 3.12.1
  mail/rspamd/Portfile
Labels: type: update, maintainer: none

#28853 coreutils-uutils: update to 0.1.0
  sysutils/coreutils-uutils/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#28867 openjdk11-zulu: update to 11.82.19
  java/openjdk11-zulu/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#28869 openjdk24-zulu: update to 24.32.13
  java/openjdk24-zulu/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#28870 google-cloud-sdk: update to 530.0.0
  devel/google-cloud-sdk/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#28871 maven3: update to 3.9.11
  java/maven3/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#28863 gallery-dl: update to 1.30.0
  net/gallery-dl/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer, maintainer: open

#28881 openjdk21-corretto: update to 21.0.8.9.1
  java/openjdk21-corretto/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#28883 openjdk17-corretto: update to 17.0.16.8.1
  java/openjdk17-corretto/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#28879 saga, py-pysaga: update to 9.9.0
  gis/saga/Portfile
  gis/saga/files/patch-exiv2.diff
Labels: type: update, maintainer, maintainer: open

#28880 Update argyll to 3 .4.0
  graphics/argyll/Portfile
Labels: type: update, maintainer: none

#28884 openjdk11-corretto: update to 11.0.28.6.1
  java/openjdk11-corretto/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#28887 openjdk24-graalvm: update to 24.0.2
  java/openjdk24-graalvm/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#28889 openjdk24: update to 24.0.2
  java/openjdk24/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#28890 openjdk21: update to 21.0.8
  java/openjdk21/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#28898 jdk21-graalvm: update to 21.0.8
  java/jdk21-graalvm/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#28896 git-annex: update to 10.20250630
  devel/git-annex/Portfile
Labels: type: enhancement, type: update, maintainer: none

#28900 josm: update to 19423
  gis/JOSM/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#28909 openjdk21-temurin: update to 21.0.8
  java/openjdk21-temurin/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#28910 jdk21: update to 21.0.8
  java/jdk21/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#28914 uv: Update to 0.8.0
  devel/uv/Portfile
Labels: type: update, maintainer, maintainer: open

#28864 tomcat-native: update to 1.3.1
  java/tomcat-native/Portfile
Labels: type: update, maintainer, maintainer: open

#28919 gitleaks: Update to 8.28.0
  security/gitleaks/Portfile
Labels: type: update, maintainer: open

#28915 kermit-devel: update to 10.0-beta12
  comms/kermit-devel/Portfile
Labels: type: enhancement, type: update, maintainer: none

#28912 openjdk21-jetbrains: update to 21.0.7b1038.58
  java/openjdk21-jetbrains/Portfile
Labels: type: update, maintainer: open, by: member

#28925 legacy-support-devel: Update to latest master - v20250720.
  devel/legacy-support/Portfile
Labels: type: update, maintainer, maintainer: open

#28930 openjdk17-microsoft: update to 17.0.16
  java/openjdk17-microsoft/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#28933 openjdk17-temurin: update to 17.0.16
  java/openjdk17-temurin/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#28940 a2ps: update to 4.15.7
  print/a2ps/Portfile
Labels: type: update, maintainer: none

#28945 google-cloud-sdk: update to 531.0.0
  devel/google-cloud-sdk/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#28950 ggc: install completions
  devel/ggc/Portfile
Labels: type: enhancement, maintainer: open, by: member

#28952 ncdc: update to 1.25
  net/ncdc/Portfile
Labels: type: enhancement, type: update, maintainer: none

#28949 hello: update to 2.12.2
  devel/mbedtls/Portfile
  devel/mbedtls3/Portfile
  mail/hello/Portfile
Labels: maintainer: open

#28955 liboqs: update to 0.14.0
  devel/liboqs/Portfile
Labels: type: update, maintainer: open

#28920 cgal6: Update to 6.0.1
  gis/cgal6/Portfile
Labels: type: update, maintainer: requires approval, maintainer: timeout

#28936 dagger: update to 0.18.14
  devel/dagger/Portfile
Labels: type: update, maintainer: open

#28934 glfw: Update to 3.4
  graphics/glfw/Portfile
Labels: type: update, maintainer: open

#28968 newsraft: update to 0.32
  net/newsraft/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#28965 redka: update to 0.6.0
  databases/redka/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#28927 vtk: Livecheck avoid release candidates
  graphics/vtk/Portfile
Labels: type: enhancement, maintainer, maintainer: open

#28917 direnv: Update to 2.37.1
  devel/direnv/Portfile
Labels: type: update, maintainer: open

#28947 ddrescueview: use ld-classic on macOS 14 and later
  sysutils/ddrescueview/Portfile
  sysutils/ddrescueview/files/patch-deployment_target.patch
Labels: type: bugfix, type: enhancement, maintainer: open, by: member

#28970 jenv: update website
  java/jenv/Portfile
Labels: type: bugfix, type: update, maintainer: open

#28973 openjdk24-temurin: update to 24.0.2
  java/openjdk24-temurin/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#28974 groovy: update to 4.0.28
  lang/groovy/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#28975 openjdk21-openj9: update to 21.0.8
  java/openjdk21-openj9/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#28976 openjdk17-openj9: update to 17.0.16
  java/openjdk17-openj9/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#28978 openjdk8-openj9: update to 8u462
  java/openjdk8-openj9/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#28977 openjdk11-openj9: update to 11.0.28
  java/openjdk11-openj9/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#28972 ruff: Update to 0.12.5
  devel/ruff/Portfile
Labels: type: update, maintainer, maintainer: open

#28984 openjdk21-jetbrains: update to 21.0.8b1038.68
  java/openjdk21-jetbrains/Portfile
Labels: type: update, maintainer: open, by: member

#28985 spring-boot-cli: update to 3.5.4
  java/spring-boot-cli/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#28986 py-whenever: update to 0.8.8
  python/py-whenever/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#28874 ghc: Fix `arm64` build
  lang/ghc/Portfile
Labels: maintainer, maintainer: open

#28990 yt-dlp: update to 2025.07.21
  net/youtube-dl/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer: requires approval

#28983 gemget: update to 1.9.0
  net/gemget/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#28971 fltk: Update to 1.4.4
  aqua/fltk/Portfile
  aqua/fltk/files/0001-Fl_cocoa.mm-fix-Apple-macro-for-PPC-case.patch
Labels: type: update, maintainer: open

#28962 Rev bump dependents for opencascade update
  science/gmsh/Portfile
  science/kicad/Portfile
  science/nektarpp/Portfile
Labels: maintainer: open

#28860 auctex: mark as obsolete
  editors/auctex/Portfile
Labels: maintainer, maintainer: open

#28980 cppcheck: update to 2.18.0
  devel/cppcheck/Portfile
Labels: type: update, maintainer: open

#28823 MMTabBarView: Submission
  devel/MMTabBarView/Portfile
Labels: type: submission

#28781 hamclock: New port
  x11/hamclock/Portfile
Labels: type: enhancement, type: submission

#29002 legacy-support-devel: Update to latest master - v20250728.
  devel/legacy-support/Portfile
Labels: type: update, maintainer, maintainer: open

#29003 netdata: update to 2.6.1
  sysutils/netdata/Portfile
Labels: type: update, maintainer: open

#28988 pipenv: update to 2025.0.4
  python/pipenv/Portfile
Labels: type: enhancement, type: update, maintainer: open

#29008 google-cloud-sdk: update to 532.0.0
  devel/google-cloud-sdk/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#29018 openjdk25-zulu: update to 25.0.45
  java/openjdk25-zulu/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#29021 dante: Update to 1.4.4
  net/dante/Portfile
Labels: type: update, maintainer: none

#28998 7zip: make a complete p7zip replacement
  archivers/7zip/Portfile
  archivers/7zip/files/patch-powerpc.patch
Labels: type: enhancement, maintainer: open, by: member
