Repository macports/macports-ports, pull requests merged in 2025-09, with the labels that each got.

#29234 GCC compilers: make gcc15 default runtime provider
  _resources/port1.0/group/compilers-1.0.tcl
  lang/gcc13/Portfile
  lang/gcc14/Portfile
  lang/gcc15/Portfile
  lang/libgcc/Portfile
Labels: maintainer: none, by: member

#29239 neovim, -devel: update to 0.11.4 and 20250901
  editors/neovim/Portfile
Labels: type: update, maintainer: open

#29241 asco: fix build on Sequoia
  science/asco/Portfile
Labels: type: bugfix, maintainer: open

#29250 osxphotos: update to 0.72.3
  graphics/osxphotos/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#29237 simg2img: Update to 1.1.5
  sysutils/simg2img/Portfile
  sysutils/simg2img/files/Makefile.patch
Labels: type: update, maintainer: none

#29251 astyle: update to 3.6.12
  devel/astyle/Portfile
Labels: type: update, maintainer: none

#29245 py-findpython: update to 0.7.0
  python/py-findpython/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#29242 Gildas: update to 202509a
  science/gildas/Portfile
Labels: type: enhancement, type: update, maintainer

#29238 ImageMagick7: Update to 7.1.2-3
  graphics/ImageMagick7/Portfile
Labels: type: update, maintainer, type: security fix, maintainer: open

#29229 libfido2: update to 1.16.0
  security/libfido2/Portfile
Labels: type: update, maintainer, maintainer: open

#29219 tenv: update to 4.7.21
  sysutils/tenv/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#29224 oxker: update to 0.11.1
  devel/oxker/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#29231 pngcheck: Update to 4.0.0
  graphics/pngcheck/Portfile
Labels: type: update, maintainer: none

#29181 opencv4: fix ffmpeg8 builds
  graphics/opencv4/Portfile
  graphics/opencv4/files/patch-ffmpeg8.diff
Labels: type: bugfix, maintainer: requires approval, maintainer: timeout

#29259 snac: update to 2.82
  net/snac/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer, maintainer: open

#29232 geographiclib: update to 2.5.2
  gis/geographiclib/Portfile
Labels: type: enhancement, type: update, maintainer: open

#29016 py-pyside6: updated variants and default variants, revbump
  python/py-pyside6/Portfile
Labels: type: update, maintainer, maintainer: open

#29260 google-cloud-sdk: update to 537.0.0
  devel/google-cloud-sdk/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#29252 cmake-devel: update to 4.1.1
  devel/cmake-devel/Portfile
Labels: type: update, maintainer: requires approval

#29253 lowdown: update to 2.0.2
  textproc/lowdown/Portfile
Labels: type: update, maintainer: open

#29249 freehdl: fix build on Sequoia
  science/freehdl/Portfile
  science/freehdl/files/patch-freehdl_kernel-db_hh.diff
Labels: type: bugfix, maintainer: none

#29218 Update argyll to 3.4.1
  graphics/argyll/Portfile
  graphics/argyll/files/patch-ppc.diff
Labels: type: bugfix, type: update, maintainer: none

#29127 htpdate: Update to 2.0.0
  net/htpdate/Portfile
Labels: maintainer: none

#28809 racket: Update to version 8.18; Use full Racket source with native apps
  lang/racket/Portfile
  lang/racket/files/paths-to-openssl.diff
Labels: maintainer: open

#29227 bstring: new port, version 1.0.1
  textproc/bstring/Portfile
Labels: type: submission

#29265 py-pyside6: update to version 6.9.2
  python/py-pyside6/Portfile
Labels: type: update, maintainer, maintainer: open

#29272 portmidi: update to 2.0.6
  audio/portmidi/Portfile
Labels: type: update, maintainer: none

#29278 syncthing-macos: update to v2.0.3+1
  net/syncthing-macos/Portfile
  net/syncthing-macos/files/patch-disable-autoupdatechecks.diff
  net/syncthing-macos/files/patch-no-bundled-syncthing.diff
Labels: type: enhancement, type: update, maintainer: open

#29279 MoltenVK: update to 1.4.0
  graphics/MoltenVK/Portfile
Labels: type: update, maintainer, maintainer: open

#29282 gallery-dl: update to 1.30.6
  net/gallery-dl/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer, maintainer: open

#29286 async-profiler: update to 4.1
  java/async-profiler/Portfile
Labels: type: enhancement, type: update, maintainer: none

#29285 mise: Update to 2025.9.5
  sysutils/mise/Portfile
Labels: type: update, maintainer, maintainer: open

#29280 wine-devel,wine-staging: Update to 10.14
  emulators/wine-devel/Portfile
  emulators/wine-devel/files/0002-wined3d-cwhack-18311.diff
  emulators/wine-devel/files/0003-wined3d-cwhack-18838.diff
  emulators/wine-devel/files/0004-winemac.drv-export-essential-apis.diff
  emulators/wine-devel/files/1001-staging-macos_hacks.diff
Labels: type: update, maintainer

#29283 py-virtualfish: update to 2.5.9, update Python subports
  python/py-virtualfish/Portfile
Labels: type: enhancement, type: update, maintainer: none

#29270 libomp: 21.1.0
  lang/libomp/Portfile
Labels: maintainer, maintainer: open, by: member

#29206 jarviz: install shell completions
  java/jarviz/Portfile
Labels: type: enhancement, maintainer: open, by: member

#29294 bstring: update to 1.0.2
  textproc/bstring/Portfile
Labels: type: update, maintainer, maintainer: open

#29295 cproto: update to 4.7y
  devel/cproto/Portfile
Labels: type: update, maintainer: none

#29292 ruby-build: Update to 20250908
  ruby/ruby-build/Portfile
Labels: type: update, maintainer, maintainer: open

#29298 swi-prolog-devel: Updated to version 9.3.30
  lang/swi-prolog-devel/Portfile
Labels: type: update, maintainer, maintainer: open

#29305 google-cloud-sdk: update to 538.0.0
  devel/google-cloud-sdk/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#29306 kotlin: update to 2.2.20
  lang/kotlin/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#29302 oh-my-posh: update to version 26.22.0
  sysutils/oh-my-posh/Portfile
Labels: type: update, maintainer, maintainer: open

#29318 kubie: Update to 0.26.0
  sysutils/kubie/Portfile
Labels: type: update, maintainer: open

#29323 amass: update to 5.0.1
  security/amass/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#29322 proxmark3-iceman: update to v4.20728
  science/proxmark3-iceman/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#29317 mutt: update to 2.2.14
  mail/mutt/Portfile
Labels: type: update, maintainer: requires approval

#29331 gitu: Update to 0.35.0
  devel/gitu/Portfile
Labels: type: update, maintainer, maintainer: open

#29325 fish: update to 4.0.6
  shells/fish/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer, maintainer: open

#29337 gallery-dl: update to 1.30.7
  net/gallery-dl/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer, maintainer: open

#29336 update to oath-toolkit: 2.6.13
  security/oath-toolkit/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#29343 coreutils-uutils: update to 0.2.2
  sysutils/coreutils-uutils/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#29341 eask-cli: update to 0.11.8
  devel/eask-cli/Portfile
Labels: type: update, maintainer, maintainer: open

#29345 macfuse: update to 5.0.6
  fuse/macfuse/Portfile
Labels: type: update, maintainer: open, by: member

#27898 clang-uml: new Portfile
  devel/clang-uml/Portfile
Labels: type: enhancement

#29348 openjdk25-zulu: update to 25.28.85
  java/openjdk25-zulu/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#29349 openjdk24-zulu: mark as end of life
  java/openjdk24-zulu/Portfile
Labels: maintainer, maintainer: open, by: member

#29350 openjdk25-graalvm: new submission
  java/openjdk25-graalvm/Portfile
Labels: type: submission, by: member

#29351 openjdk24-graalvm: mark as EOL
  java/openjdk24-graalvm/Portfile
Labels: maintainer, maintainer: open, by: member

#29357 zig: update minimum OS version
  lang/zig/Portfile
Labels: type: update, maintainer: none, by: member

#29360 weechat: update to 4.7.1
  irc/weechat/Portfile
  irc/weechat/files/no-extra-gcc-warnings.patch
Labels: type: update, maintainer, maintainer: open

#29362 ruby-build: Update to 20250916.1
  ruby/ruby-build/Portfile
Labels: type: update, maintainer, maintainer: open

#29363 neofetch: marking deprecated
  sysutils/neofetch/Portfile
Labels: type: enhancement, maintainer, maintainer: open

#29364 golines: update to 0.13.0
  devel/golines/Portfile
Labels: type: update, maintainer: open

#29344 lzma: update to 25.01
  archivers/lzma/Portfile
Labels: type: update, maintainer: open

#29367 openjdk25-corretto: update to 25.0.0.36.2
  java/openjdk25-corretto/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#29369 openjdk*-corretto: update support dates
  java/openjdk11-corretto/Portfile
  java/openjdk17-corretto/Portfile
  java/openjdk21-corretto/Portfile
  java/openjdk22-corretto/Portfile
  java/openjdk23-corretto/Portfile
  java/openjdk24-corretto/Portfile
  java/openjdk25-corretto/Portfile
  java/openjdk8-corretto/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#29377 openjdk*-microsoft: add end of support dates
  java/openjdk11-microsoft/Portfile
  java/openjdk17-microsoft/Portfile
  java/openjdk21-microsoft/Portfile
Labels: maintainer, maintainer: open, by: member

#29379 wxWidgets-3.0: support macOS 26
  graphics/wxWidgets-3.0/Portfile
  graphics/wxWidgets-3.0/files/patch-libpng.diff
Labels: type: bugfix, maintainer: none

#29383 wxWidgets-3.2: Fix build on macOS 26
  graphics/wxWidgets-3.2/Portfile
  graphics/wxWidgets-3.2/files/dd3f2509499e0e6aac4ebf8dab72b5d496c5bfbc.patch
Labels: type: bugfix, maintainer: none, by: member

#29384 openjdk*-graalvm: add support dates
  java/openjdk21-graalvm/Portfile
  java/openjdk22-graalvm/Portfile
  java/openjdk24-graalvm/Portfile
  java/openjdk25-graalvm/Portfile
Labels: maintainer, maintainer: open, by: member

#29381 hugo: update to 0.150.0
  www/hugo/Portfile
Labels: type: update, maintainer, maintainer: open

#29374 tevent: update to 0.17.1
  devel/tevent/Portfile
Labels: type: enhancement, type: update, maintainer: none

#29373 tdb: update to 1.4.14
  databases/tdb/Portfile
Labels: type: enhancement, type: update, maintainer: none

#29386 oh-my-posh: update to version 26.23.6
  sysutils/oh-my-posh/Portfile
Labels: type: update, maintainer, maintainer: open

#29392 gradle: add gradle8 subport
  devel/gradle/Portfile
Labels: type: enhancement, maintainer: open, by: member

#29389 algol68g: Update to 3.9.5
  lang/algol68g/Portfile
  lang/algol68g/files/0006-Fix-endianness-includes-and-macros.patch
Labels: type: update, maintainer: none

#29391 plantuml: update to 1.2025.7
  java/plantuml/Portfile
Labels: type: enhancement, type: update, maintainer: open

#29380 bossa: support macOS 26
  cross/bossa/files/patch-Makefile
Labels: type: bugfix, maintainer: open

#29046 gobject_introspection: Fix meson universal builds
  _resources/port1.0/group/gobject_introspection-1.0.tcl
Labels: type: bugfix

#29387 libfido2: update tarball extraction from releases
  security/libfido2/Portfile
Labels: maintainer, maintainer: open

#29396 qt5-qtbase: Fix build on macOS 26
  aqua/qt5/Portfile
  aqua/qt5/files/patch-qtbase-icu-cxx11.diff
  aqua/qt5/files/patch-qtbase-tahoe-no-agl-framework.diff
Labels: type: bugfix, maintainer: open, by: member

#29401 splash: Fix build for 10.7
  science/splash/Portfile
Labels: type: bugfix, maintainer: open

#29403 fheroes2: update to 1.1.11
  games/fheroes2/Portfile
Labels: type: update, maintainer, maintainer: open

#29404 nauty: update to 2.9.1
  math/nauty/Portfile
Labels: type: update, maintainer, maintainer: open

#29406 JDK cleanup
  java/jdk17/Portfile
  java/jdk21/Portfile
  java/jdk22/Portfile
  java/jdk23/Portfile
  java/jdk24/Portfile
  java/mvnd1/Portfile
  java/mvnd2/Portfile
  java/openjdk11-corretto/Portfile
  java/openjdk11-graalvm/Portfile
  java/openjdk11-openj9/Portfile
  java/openjdk11-sap/Portfile
  java/openjdk11-temurin/Portfile
  java/openjdk17-corretto/Portfile
  java/openjdk17-graalvm/Portfile
  java/openjdk17-openj9/Portfile
  java/openjdk17-sap/Portfile
  java/openjdk17-temurin/Portfile
  java/openjdk20-openj9/Portfile
  java/openjdk21-corretto/Portfile
  java/openjdk21-openj9/Portfile
  java/openjdk21-oracle/Portfile
  java/openjdk21-sap/Portfile
  java/openjdk21-temurin/Portfile
  java/openjdk22-corretto/Portfile
  java/openjdk22-openj9/Portfile
  java/openjdk22-oracle/Portfile
  java/openjdk22-sap/Portfile
  java/openjdk22-temurin/Portfile
  java/openjdk23-corretto/Portfile
  java/openjdk23-openj9/Portfile
  java/openjdk23-sap/Portfile
  java/openjdk23-temurin/Portfile
  java/openjdk24-corretto/Portfile
  java/openjdk24-openj9/Portfile
  java/openjdk24-sap/Portfile
  java/openjdk24-temurin/Portfile
  java/openjdk8-corretto/Portfile
Labels: maintainer, maintainer: open, by: member

#29407 spring-boot-cli: update to 3.5.6
  java/spring-boot-cli/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#29409 k9s: update to 0.50.12
  sysutils/k9s/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#29412 6tunnel: update to 0.14
  net/6tunnel/Portfile
Labels: type: enhancement, type: update, maintainer: open

#29366 lft: Fix build failure on macOS 26
  net/lft/Portfile
  net/lft/files/lft_types.h.patch
Labels: maintainer: requires approval, maintainer: timeout, by: member

#29411 py-zipfile-deflate64: Xcode ≥ 16.3 compatibility
  python/py-zipfile-deflate64/Portfile
  python/py-zipfile-deflate64/files/patch-zlib.diff
Labels: type: bugfix, maintainer: none

#29415 fish: update to 4.0.8
  shells/fish/Portfile
Labels: type: bugfix, type: update, maintainer, maintainer: open

#29418 Fix arch_classifier errors for i386
  java/jdk17/Portfile
  java/jdk21/Portfile
  java/jdk22/Portfile
  java/jdk23/Portfile
  java/jdk24/Portfile
  java/mvnd1/Portfile
  java/mvnd2/Portfile
  java/openjdk11-corretto/Portfile
  java/openjdk11-graalvm/Portfile
  java/openjdk11-microsoft/Portfile
  java/openjdk11-openj9/Portfile
  java/openjdk11-sap/Portfile
  java/openjdk11-temurin/Portfile
  java/openjdk11-zulu/Portfile
  java/openjdk17-corretto/Portfile
  java/openjdk17-graalvm/Portfile
  java/openjdk17-microsoft/Portfile
  java/openjdk17-openj9/Portfile
  java/openjdk17-sap/Portfile
  java/openjdk17-temurin/Portfile
  java/openjdk17-zulu/Portfile
  java/openjdk21-corretto/Portfile
  java/openjdk21-microsoft/Portfile
  java/openjdk21-openj9/Portfile
  java/openjdk21-oracle/Portfile
  java/openjdk21-sap/Portfile
  java/openjdk21-temurin/Portfile
  java/openjdk21-zulu/Portfile
  java/openjdk22-corretto/Portfile
  java/openjdk22-openj9/Portfile
  java/openjdk22-oracle/Portfile
  java/openjdk22-sap/Portfile
  java/openjdk22-temurin/Portfile
  java/openjdk22-zulu/Portfile
  java/openjdk23-corretto/Portfile
  java/openjdk23-openj9/Portfile
  java/openjdk23-sap/Portfile
  java/openjdk23-temurin/Portfile
  java/openjdk23-zulu/Portfile
  java/openjdk24-corretto/Portfile
  java/openjdk24-openj9/Portfile
  java/openjdk24-sap/Portfile
  java/openjdk24-temurin/Portfile
  java/openjdk24-zulu/Portfile
  java/openjdk25-zulu/Portfile
  java/openjdk8-corretto/Portfile
  java/openjdk8-zulu/Portfile
Labels: maintainer, maintainer: open, by: member

#29419 mvnd1: update to 1.0.3
  java/mvnd1/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#29425 zig: fix duplicate LC_RPATH
  lang/zig/Portfile
  lang/zig/files/patch-duplicate-LC_RPATH.diff
Labels: type: bugfix, maintainer: none, by: member

#29423 m4ri: update to 20250128
  math/m4ri/Portfile
Labels: type: enhancement, type: update, maintainer: none

#29371 aacgain: fix compile on Tahoe (MacOS 26)
  audio/aacgain/Portfile
Labels: type: bugfix, maintainer: none

#29420 adblock2privoxy: Update to version 2.3.1
  www/adblock2privoxy/Portfile
  www/adblock2privoxy/files/adblock2privoxy_blocklist.txt
Labels: type: update, maintainer, maintainer: open

#29427 xeus-zmq: fix build on macOS >=10.7 and =<10.12
  devel/xeus-zmq/Portfile
Labels: maintainer: open

#29428 rpki-client: update to 9.6
  net/rpki-client/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer, maintainer: open

#29429 xvega: fix build on macOS <10.13
  graphics/xvega/Portfile
Labels: maintainer: open

#29449 simplotask: update to 1.19.1
  sysutils/simplotask/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#29422 couchdb: update to 3.5.0
  databases/couchdb/Portfile
  databases/couchdb/files/patch-etc-launchd-org.apache.couchdb.plist.tpl.in.diff
  databases/couchdb/files/patch-support-dual-spidermonkey.diff
Labels: type: update, maintainer: requires approval, maintainer: timeout, by: member

#29456 miniflux: update to 2.2.13
  net/miniflux/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#29463 oh-my-posh: update to version 26.25.0
  sysutils/oh-my-posh/Portfile
Labels: type: update, maintainer, maintainer: open

#29464 google-cloud-sdk: fix livecheck
  devel/google-cloud-sdk/Portfile
Labels: maintainer: open

#29458 symfony-cli: update to 5.14.2
  devel/symfony-cli/Portfile
Labels: type: update, maintainer, maintainer: open

#29470 ramalama: Add missing py-yaml dependency
  llm/ramalama/Portfile
Labels: type: bugfix, maintainer, maintainer: open, by: member

#29467 rspamd: Update to version 3.13.0
  mail/rspamd/Portfile
Labels: type: update, maintainer: none

#29385 Add version 2.45 to crossbinutils
  _resources/port1.0/group/crossbinutils-1.0.tcl
Labels: type: enhancement

#29475 detox: update to 3.0.1
  sysutils/detox/Portfile
Labels: type: enhancement, type: update, maintainer: none

#29479 openjdk24-openj9: update EOL date
  java/openjdk24-openj9/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#29480 openjdk25-temurin: new port
  java/openjdk25-temurin/Portfile
Labels: type: submission, by: member

#29481 openjdk25-microsoft: new port
  java/openjdk25-microsoft/Portfile
Labels: type: submission, by: member

#29471 RHash: new port
  sysutils/RHash/Portfile
Labels: type: enhancement, type: submission

#29485 podman: update to 5.6.1
  sysutils/podman/Portfile
Labels: type: update, maintainer: open

#29484 py-matplotlib: removed references to missing variants
  python/py-matplotlib/Portfile
Labels: type: enhancement, maintainer: open

#29482 x86_64-binutils: Update to 2.45 and add targets haiku and solaris
  cross/x86_64-binutils/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#29488 k9s: update to 0.50.13
  sysutils/k9s/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#29431 BRiAl: update to 1.2.14
  math/BRiAl/Portfile
Labels: type: enhancement, type: update, maintainer: none

#29492 oxker: update to 0.12.0
  devel/oxker/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#29500 fish: update to 4.1.0
  shells/fish/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer, maintainer: open

#29496 oh-my-posh: update to version 26.26.1
  sysutils/oh-my-posh/Portfile
Labels: type: update, maintainer, maintainer: open

#29501 openjdk25: new port
  java/openjdk25/Portfile
Labels: type: submission, by: member

#29502 got: update to 0.119
  devel/got/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer, maintainer: open

#29495 hamlib: update to 4.6.5
  science/hamlib/Portfile
Labels: type: update, maintainer: open

#29499 nco: update to 5.3.5
  science/nco/Portfile
Labels: type: enhancement, type: update, maintainer: open

#29335 submission: FreeIPMI: version 1.6.15
  sysutils/freeipmi/Portfile
Labels: type: enhancement, type: submission

#29397 picotls: update, disable mbedtls, fix test
  net/picotls/Portfile
  net/picotls/files/patch-aligned_alloc.diff
Labels: type: bugfix, type: enhancement, type: update, type: security fix, maintainer: open
