Repository macports/macports-ports, pull requests merged in 2025-01, with the labels that each got.

#27222 pnpm: Update to 9.15.2
  devel/pnpm/Portfile
Labels: type: update, maintainer: open

#27217 viu: Update to 1.5.1
  graphics/viu/Portfile
Labels: type: update, maintainer: open

#27253 jsoncons: update to 1.0.0
  devel/jsoncons/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#27252 uacme: update to 1.7.6
  security/uacme/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#27249 audiowmark: update to 0.6.3
  audio/audiowmark/Portfile
  audio/audiowmark/files/patch-cinttypes.diff
  audio/audiowmark/files/patch-missing-errno.diff
Labels: type: update, maintainer, maintainer: open

#27256 mise: Update to 2025.1.0
  sysutils/mise/Portfile
Labels: type: update, maintainer, maintainer: open

#27257 xfig and fig2dev: update to 3.2.9a
  graphics/xfig/Portfile
  print/fig2dev/Portfile
Labels: type: update, maintainer: none

#27255 nco: update to 5.3.0
  science/nco/Portfile
Labels: type: update, maintainer: open

#27260 symfony-cli: update to 5.10.6
  devel/symfony-cli/Portfile
Labels: type: update, maintainer, maintainer: open

#27233 Update dotnet links to be global
  dotnet/aspnetcore-runtime-2.1/Portfile
  dotnet/aspnetcore-runtime-3.1/Portfile
  dotnet/aspnetcore-runtime-6/Portfile
  dotnet/aspnetcore-runtime-7/Portfile
  dotnet/aspnetcore-runtime-8/Portfile
  dotnet/aspnetcore-runtime-devel/Portfile
  dotnet/dotnet-cli/Portfile
  dotnet/dotnet-runtime-2.1/Portfile
  dotnet/dotnet-runtime-3.1/Portfile
  dotnet/dotnet-runtime-6/Portfile
  dotnet/dotnet-runtime-7/Portfile
  dotnet/dotnet-runtime-8/Portfile
  dotnet/dotnet-runtime-devel/Portfile
  dotnet/dotnet-sdk-2.1/Portfile
  dotnet/dotnet-sdk-3.1/Portfile
  dotnet/dotnet-sdk-6/Portfile
  dotnet/dotnet-sdk-7/Portfile
  dotnet/dotnet-sdk-8/Portfile
  dotnet/dotnet-sdk-devel/Portfile
Labels: type: update, maintainer: open

#27265 clojure: update to 1.12.0.1495
  lang/clojure/Portfile
Labels: type: update, maintainer, maintainer: open

#27264 pipx: change default variant to python313
  python/pipx/Portfile
Labels: type: enhancement, maintainer, maintainer: open

#27262 wolfssl: update to version 5.7.6
  devel/wolfssl/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#27261 shadowsocks-rust: update to v1.22.0
  net/shadowsocks-rust/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#27245 universal-ctags: update to 6.1.20241229.0
  devel/universal-ctags/Portfile
Labels: type: update, maintainer: open

#27272 fswatch: update to 1.18.0
  sysutils/fswatch/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#27274 docker: update to 27.4.1
  devel/docker/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#27276 rancher-cli: update to 2.10.1
  devel/rancher-cli/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#27278 operator-sdk: update to 1.38.0
  devel/operator-sdk/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#27279 rke: update to 1.7.1
  devel/rke/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#27280 antlr4-cpp-runtime: update to 4.13.2
  lang/antlr4-cpp-runtime/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#27281 flyway: update to 11.1.0
  java/flyway/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#27283 librsvg, librsvg-devel: use fallback version on Snow Leopard
  graphics/librsvg-devel/Portfile
  graphics/librsvg/Portfile
Labels: maintainer: open

#27286 appstream-glib: fix missing ossp-uuid dependency
  devel/appstream-glib/Portfile
Labels: type: bugfix, maintainer: open

#27248 multiple ports: fix vala dependency type
  devel/geoclue2/Portfile
  devel/libayatana-appindicator/Portfile
  devel/libdmapsharing/Portfile
  devel/zeitgeist/Portfile
  gnome/baobab/Portfile
  gnome/dconf/Portfile
  gnome/folks/Portfile
  gnome/gcab/Portfile
  gnome/gcr/Portfile
  gnome/gedit-plugins/Portfile
  gnome/gedit/Portfile
  gnome/gnome-autoar/Portfile
  gnome/gnome-calculator/Portfile
  gnome/gnome-chess/Portfile
  gnome/gnome-online-accounts/Portfile
  gnome/grilo/Portfile
  gnome/gspell/Portfile
  gnome/gtksourceview3/Portfile
  gnome/gucharmap/Portfile
  gnome/libchamplain/Portfile
  gnome/libdazzle-devel/Portfile
  gnome/libdazzle/Portfile
  gnome/libhandy-0.0/Portfile
  gnome/libpeas/Portfile
  gnome/libsecret/Portfile
  gnome/libsocialweb/Portfile
  gnome/seahorse/Portfile
  gnome/tracker/Portfile
  gnome/uhttpmock/Portfile
  graphics/birdfont/Portfile
  graphics/libmediaart/Portfile
  graphics/tiv/Portfile
  mail/gmime/Portfile
  mail/gmime3/Portfile
  net/gssdp/Portfile
  net/gupnp-av/Portfile
  net/gupnp-dlna/Portfile
  net/gupnp/Portfile
  net/libgweather/Portfile
  net/rygel/Portfile
  textproc/xmlbird/Portfile
  www/libhttpseverywhere/Portfile
  www/midori/Portfile
  x11/gtkspell3/Portfile
  xfce/libxfce4util/Portfile
Labels: type: bugfix, maintainer: open, by: member

#27295 docker-buildx-plugin: update to 0.19.3
  devel/docker-buildx-plugin/Portfile
Labels: type: update, maintainer: open, by: member

#27290 py-lazy_loader: update to 0.4, add py313 subport
  python/py-lazy_loader/Portfile
Labels: type: enhancement, type: update, maintainer: none

#27296 oh-my-posh: update to version 24.18.0
  sysutils/oh-my-posh/Portfile
Labels: type: update, maintainer, maintainer: open

#27293 multiple ports: fix libsoup dependency
  audio/easytag/Portfile
  audio/gmpc/Portfile
  comms/telepathy-gabble/Portfile
  comms/telepathy-salut/Portfile
  devel/cutter/Portfile
  devel/geany-plugins/Portfile
  devel/geoclue/Portfile
  devel/geoclue2/Portfile
  devel/gvfs/Portfile
  gnome/frogr/Portfile
  gnome/geocode-glib/Portfile
  gnome/gfbgraph/Portfile
  gnome/grilo/Portfile
  gnome/gstreamer010-gst-plugins-good/Portfile
  gnome/gthumb/Portfile
  gnome/libchamplain/Portfile
  gnome/libepc/Portfile
  gnome/libgdata/Portfile
  gnome/libsocialweb/Portfile
  gnome/polari/Portfile
  gnome/rest/Portfile
  gnome/tracker3/Portfile
  gnome/uhttpmock/Portfile
  graphics/osm-gps-map-gtk2/Portfile
  net/libgrss/Portfile
  net/libgweather/Portfile
  www/libhttpseverywhere/Portfile
  www/midori/Portfile
  www/webkit-gtk/Portfile
Labels: type: bugfix, maintainer: open, by: member

#27300 bitwarden-cli: Update to version 2024.12.0
  security/bitwarden-cli/Portfile
Labels: type: update, maintainer, maintainer: open

#27271 gcovr: new port
  devel/gcovr/Portfile
Labels: type: submission

#27292 mas: 1.9.0
  sysutils/mas/Portfile
  sysutils/mas/files/patch-fix-version.diff
Labels: type: enhancement, maintainer: open, by: member

#27270 plfit: update to 1.0.1
  math/plfit/Portfile
  math/plfit/files/patch-fix-linking-gcc.diff
Labels: maintainer, maintainer: open

#27299 opencv4: add py313 bindings
  graphics/opencv4/Portfile
Labels: type: enhancement, maintainer: requires approval

#27273 semver-utils: new port submission
  devel/semver-utils/Portfile
Labels: type: submission, by: member

#27307 cpp-argparse-dev: update to v1.9.6
  devel/cpp-argparse-dev/Portfile
Labels: type: update, maintainer, maintainer: open

#27308 igraph: use external plfit
  math/igraph/Portfile
Labels: maintainer, maintainer: open

#27305 got: update to 0.107
  devel/got/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer, maintainer: open

#27304 cdo: update to 2.5.0
  science/cdo/Portfile
Labels: type: update, maintainer, maintainer: open

#27303 libfive: use Python 3.13
  graphics/libfive/Portfile
Labels: maintainer: none

#27312 age: install manpages
  security/age/Portfile
Labels: type: enhancement, maintainer: open

#27306 ocrmypdf: rework python variants, default to 3.13; enable english by default
  textproc/ocrmypdf/Portfile
Labels: type: enhancement, maintainer: open, by: member

#27311 py-scipy: update to 1.15.0
  python/py-scipy/Portfile
  python/py-scipy/files/0001-Fix-cmath.patch
  python/py-scipy/files/0001-patch-extra-flags.patch
  python/py-scipy/files/0002-Use-legacysupport-manually-for-strnlen.patch
  python/py-scipy/files/0002-patch-extra-flags.patch
  python/py-scipy/files/patch-version-caps-pyproject.toml.diff
Labels: type: update, maintainer, maintainer: open, by: member

#27316 gallery-dl: update to 1.28.3 and bump python
  net/gallery-dl/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer, maintainer: open

#27314 Gildas: update to 202501a
  science/gildas/Portfile
  science/gildas/files/patch-admin-python-config-ldflags.py.diff
Labels: type: enhancement, type: update, maintainer

#27289 py-imageio: update to 2.36.1, add py313 subport
  python/py-imageio/Portfile
Labels: type: enhancement, type: update, maintainer: open

#27317 mise: Update to 2025.1.1
  sysutils/mise/Portfile
Labels: type: update, maintainer, maintainer: open

#27320 ruby3[23]: Fix build on 10.4 with gcc14.
  lang/ruby32/Portfile
  lang/ruby32/files/patch-sources.diff
  lang/ruby33/Portfile
  lang/ruby33/files/patch-sources.diff
Labels: type: bugfix, maintainer, maintainer: open

#27315 isync: Fix crash on 0-size messages on IMAP
  mail/isync/Portfile
  mail/isync/files/0001-accept-zero-sized-messages-from-IMAP.patch
Labels: type: bugfix, maintainer: open, by: member

#27321 swi-prolog-devel: Updated to version 9.3.18
  lang/swi-prolog-devel/Portfile
Labels: type: update, maintainer, maintainer: open

#27243 py-asitop: remove obsolete port
  python/py-asitop/Portfile
Labels: maintainer: none

#27327 fricas: revbump for new sbcl version 2.5.0
  math/fricas/Portfile
Labels: maintainer, maintainer: open

#27336 openssl3: Fix no_cache issue w/3rd party providers
  devel/openssl3/Portfile
  devel/openssl3/files/5549fcd4783cb6c2a7f07e74505a2eea4939e5b1.patch
Labels: type: bugfix, maintainer, maintainer: open, by: member

#27335 GPXSee: update to 13.34
  gis/GPXSee/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#27334 rpki-client: update to 9.4
  net/rpki-client/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer, maintainer: open

#27332 snac: update to 2.68
  net/snac/Portfile
  net/snac/files/Makefile.patch
Labels: type: bugfix, type: enhancement, type: update, maintainer, maintainer: open

#27331 dosbox-x: update to 2025.01.01
  emulators/dosbox-x/Portfile
Labels: type: update, maintainer: none

#27337 logtalk: update to 3.87.0
  lang/logtalk/Portfile
Labels: type: update, maintainer

#27342 mise: Update to 2025.1.2
  sysutils/mise/Portfile
Labels: type: update, maintainer, maintainer: open

#27343 google-cloud-sdk: update to 505.0.0
  devel/google-cloud-sdk/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#27322 astyle: update to 3.6.6
  devel/astyle/Portfile
  devel/astyle/files/dont-force-stdlib.diff
Labels: type: update, maintainer: none

#27302 wireshark4: update to 4.4.2
  net/wireshark4/Portfile
Labels: type: enhancement, type: update, maintainer: requires approval, maintainer: timeout, by: member

#27268 kealib: update to 1.6.1
  gis/kealib/Portfile
Labels: type: update, maintainer: requires approval, maintainer: timeout

#27287 py-pywavelets: update to 1.8.0, add py313 subport
  python/py-pywavelets/Portfile
  python/py-pywavelets/files/patch-pyproject.toml-1.5.0.diff
  python/py-pywavelets/files/patch-pyproject.toml.diff
  python/py-pywavelets/files/pyproject.toml-1.4.1.diff
Labels: type: enhancement, maintainer: open

#27344 icu,icu-devel: Tweak usage of muniversal
  devel/icu-devel/Portfile
  devel/icu/Portfile
Labels: type: enhancement, maintainer: none

#27309 wxWidgets-3.0: set c++ standards
  graphics/wxWidgets-3.0/Portfile
Labels: maintainer: open, by: member

#27347 glib2: Fix code generator with Python 3.13
  devel/glib2/Portfile
  devel/glib2/files/no-distutils.patch
Labels: type: bugfix, maintainer: open, by: member

#27349 mise: Update to 2025.1.3
  sysutils/mise/Portfile
Labels: type: update, maintainer, maintainer: open

#27340 stack: update to 3.3.1
  lang/stack/Portfile
Labels: type: update, maintainer: open, by: member

#27338 ghc: update to 9.12.1
  lang/ghc/Portfile
Labels: type: update, maintainer: open, by: member

#27235 legcord: new port
  net/Legcord/Portfile
Labels: type: enhancement, type: submission

#27318 tk dependents: default to +quartz when tk does
  graphics/tkimg/Portfile
  math/netgen/Portfile
  x11/Togl/Portfile
  x11/tix/Portfile
  x11/tkdnd/Portfile
  x11/tktable/Portfile
Labels: maintainer: open, by: member

#27354 moe: update to 1.15
  editors/moe/Portfile
Labels: type: update, maintainer: none

#27353 ed: update to 1.21
  editors/ed/Portfile
Labels: type: update, maintainer: none

#27356 mise: Update to 2025.1.4
  sysutils/mise/Portfile
Labels: type: update, maintainer, maintainer: open

#27284 tesseract-training: use_mp_libcxx on 10.13 and older
  textproc/tesseract/Portfile
Labels: type: bugfix, maintainer: open

#27291 py-scikit-image: update to 0.25.0, add py313 subport
  python/py-scikit-image/Portfile
  python/py-scikit-image/files/patch-pyproject.toml-0.24.0.diff
  python/py-scikit-image/files/patch-pyproject.toml.diff
Labels: type: enhancement, type: update, maintainer: open

#27358 py-awscli2: update to 2.22.33
  python/py-awscli2/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#27359 py-urwid: add subport py313
  python/py-urwid/Portfile
Labels: type: enhancement, maintainer: none

#27360 bun: update to 1.1.43
  devel/bun/Portfile
Labels: type: update, maintainer, maintainer: open

#27362 starship: update to 1.22.1
  sysutils/starship/Portfile
Labels: type: update, maintainer: open, by: member

#27366 legacy-support-devel: Update to latest master.
  devel/legacy-support/Portfile
Labels: type: update, maintainer, maintainer: open

#27367 mat2: update to 0.13.5, update default python
  multimedia/mat2/Portfile
  python/py-mutagen/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer, maintainer: open

#27368 mise: Update to 2025.1.6
  sysutils/mise/Portfile
Labels: type: update, maintainer, maintainer: open

#27363 py-urwid-readline: new port
  python/py-urwid-readline/Portfile
Labels: type: submission

#27210 ruby34: New version
  lang/ruby34/Portfile
  lang/ruby34/files/patch-generated.diff
  lang/ruby34/files/patch-sources.diff
  lang/ruby34/files/ruby34
Labels: type: submission

#27370 vttest: update to 20241208
  devel/vttest/Portfile
Labels: type: update, maintainer: none

#27374 nco: update to 5.3.1
  science/nco/Portfile
Labels: type: update, maintainer, maintainer: open

#27352 wireshark4: update to 4.4.3
  net/wireshark4/Portfile
Labels: type: update, maintainer: requires approval, maintainer: timeout, by: member

#27378 gallery-dl: update to 1.28.4
  net/gallery-dl/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer, maintainer: open

#27364 py-black: update to 24.10.0, add py313 subport
  python/py-black/Portfile
  python/py-black/files/black313
Labels: type: enhancement, type: update, maintainer: open

#27379 alacritty: update to 0.15
  aqua/alacritty/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer, maintainer: open

#27381 php-tideways_xhprof: remove obsolete port
  php/php-tideways_xhprof/Portfile
Labels: maintainer: open

#27384 libframe: update to 8.48.3
  science/libframe/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer: open

#27348 mesa: Add missing build dep
  x11/mesa/Portfile
Labels: type: bugfix, maintainer: open, by: member

#27382 python312-devel: remove obsolete port
  lang/python312-devel/Portfile
Labels: maintainer: none

#27365 py-jedi: update to 0.19.2
  python/py-jedi/Portfile
Labels: type: enhancement, type: update, maintainer: open

#27361 pnpm: update to 9.15.3
  devel/pnpm/Portfile
Labels: type: update, maintainer: open

#27385 keybase: update to version 6.4.0
  security/keybase/Portfile
Labels: type: update, maintainer: none

#27355 lighttpd: Update to 1.4.77
  www/lighttpd/Portfile
  www/lighttpd/files/patch-conf-darwin.diff
  www/lighttpd/files/patch-conf.diff
Labels: type: bugfix, type: update, maintainer: open

#27391 oh-my-posh: update to version 24.18.1
  sysutils/oh-my-posh/Portfile
Labels: type: update, maintainer, maintainer: open

#27390 eask-cli: update to 0.10.3
  devel/eask-cli/Portfile
Labels: type: update, maintainer, maintainer: open

#27392 mise: Update to 2025.1.7
  sysutils/mise/Portfile
Labels: type: update, maintainer, maintainer: open

#27389 ruby-build: Update to 20250114
  ruby/ruby-build/Portfile
Labels: type: update, maintainer, maintainer: open

#27393 libframe: fix bugs in cmake configuration
  science/libframe/Portfile
Labels: type: bugfix, maintainer: open

#27394 google-cloud-sdk: update to 506.0.0
  devel/google-cloud-sdk/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#27396 tippecanoe: update to 2.74.0
  gis/tippecanoe/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#27397 kustomize: update to 5.6.0
  devel/kustomize/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#27398 aerc: update to 0.19.0
  mail/aerc/Portfile
Labels: type: enhancement, type: update, maintainer: open

#27402 mani: Install manpage and completions
  devel/mani/Portfile
Labels: type: enhancement, maintainer: open

#27401 ruby-build: Update to 20250115
  ruby/ruby-build/Portfile
Labels: type: update, maintainer, maintainer: open

#27399 d3dmetal: Update to v2.0
  devel/d3dmetal/Portfile
Labels: type: update, maintainer

#27383 mariadb-10.{0,1,2}: mark obsolete
  databases/mariadb-10.0/Portfile
  databases/mariadb-10.0/files/macports-default.cnf
  databases/mariadb-10.0/files/mariadb-10.0
  databases/mariadb-10.0/files/my.cnf
  databases/mariadb-10.0/files/org.macports.mysql-server.plist
  databases/mariadb-10.0/files/patch-CMakeLists.txt.diff
  databases/mariadb-10.0/files/patch-cmake-install_layout.cmake.diff
  databases/mariadb-10.1/Portfile
  databases/mariadb-10.1/files/macports-default.cnf
  databases/mariadb-10.1/files/mariadb-10.1
  databases/mariadb-10.1/files/my.cnf
  databases/mariadb-10.1/files/org.macports.mysql-server.plist
  databases/mariadb-10.1/files/patch-CMakeLists.txt.diff
  databases/mariadb-10.1/files/patch-cmake-install_layout.cmake.diff
  databases/mariadb-10.1/files/patch-include_my_global.h.diff
  databases/mariadb-10.2/Portfile
  databases/mariadb-10.2/files/macports-default.cnf
  databases/mariadb-10.2/files/mariadb-10.2
  databases/mariadb-10.2/files/my.cnf
  databases/mariadb-10.2/files/org.macports.mysql-server.plist
  databases/mariadb-10.2/files/patch-CMakeLists.txt.diff
  databases/mariadb-10.2/files/patch-SSL_INCLUDES_first.diff
  databases/mariadb-10.2/files/patch-cmake-install_layout.cmake.diff
  databases/mariadb-10.2/files/patch-cmake_mysql_version.cmake.diff
  databases/mariadb-10.2/files/patch-include_my_global.h.diff
  databases/mariadb-10.2/files/patch-libmariadb_cmake_install.cmake.diff
  databases/mariadb-10.2/files/patch-libmariadb_libmariadb_CMakeLists.txt.diff
  databases/mariadb-10.2/files/patch-use-correct-readline.diff
Labels: maintainer: open, by: member

#27407 docker: update to 27.5.0
  devel/docker/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#27412 mise: Update to 2025.1.9
  sysutils/mise/Portfile
Labels: type: update, maintainer, maintainer: open

#27410 newsraft: update to 0.28
  net/newsraft/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#27411 josm: update to 19277
  gis/JOSM/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#27413 jsoncons: update to 1.1.0
  devel/jsoncons/Portfile
Labels: type: enhancement, type: update, maintainer, maintainer: open

#27404 cargo-c: update to 0.10.8
  devel/cargo-c/Portfile
Labels: type: update, maintainer: open, by: member

#27403 libpng: update to 1.6.45
  graphics/libpng/Portfile
Labels: type: update, maintainer: requires approval

#27415 meson: add llvm-config to cross files
  python/py-meson/Portfile
  python/py-meson/files/cross/arm64-darwin
  python/py-meson/files/cross/i386-darwin
  python/py-meson/files/cross/ppc-darwin
  python/py-meson/files/cross/ppc64-darwin
  python/py-meson/files/cross/x86_64-darwin
Labels: type: enhancement, maintainer: open, by: member

#27386 gdal: update to 3.10.1, add subport 'gdal-hdf4' replacing 'hdf4' variant
  gis/gdal/Portfile
Labels: type: update, maintainer, maintainer: open

#27400 utfcpp: new port
  textproc/utfcpp/Portfile
Labels: type: enhancement, type: submission

#27380 ncdc: update to 1.24.1, add GeoIP support
  net/ncdc/Portfile
Labels: type: enhancement, type: update, maintainer: none

#27388 minipro: Update to 0.7.2.
  devel/minipro/Portfile
Labels: type: update, maintainer: open

#27409 llama.cpp: update to b4508; fix builds for 10.15 and earlier
  llm/llama.cpp/Portfile
  llm/llama.cpp/files/patch-llama-mmap-errno.diff
Labels: maintainer: open, by: member

#27416 rebels-in-the-sky: Update to 1.0.28
  games/rebels-in-the-sky/Portfile
Labels: type: update, maintainer, maintainer: open

#27418 openjdk24-zulu: update to 24.0.67
  java/openjdk24-zulu/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#27420 glances: Update to version 4.3.0.8, Fix py-orjson related bug
  sysutils/glances/Portfile
Labels: type: update, maintainer, maintainer: open

#27435 openssl3: Fix CVE-2024-13176
  devel/openssl3/Portfile
  devel/openssl3/files/77c608f4c8857e63e98e66444e2e761c9627916f.patch
Labels: maintainer, type: security fix, maintainer: open, by: member

#27434 antlr4-cpp-runtime: enhancement add support for all architectures
  lang/antlr4-cpp-runtime/Portfile
Labels: type: enhancement, maintainer, maintainer: open, by: member

#27421 crossbinutils: Add compiler blacklist
  _resources/port1.0/group/crossbinutils-1.0.tcl
Labels: type: bugfix

#27439 legacy-support-devel: Update to latest master.
  devel/legacy-support/Portfile
Labels: type: update, maintainer, maintainer: open

#27436 legcord: update to 1.0.7
  net/Legcord/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer, type: security fix, maintainer: open

#27424 fldigi: Update to 4.2.06
  science/fldigi/Portfile
Labels: type: update, maintainer: open

#27423 qdmr: Update to 1.12.1
  science/qdmr/Portfile
Labels: type: update, maintainer: open

#27445 legcord: update to 1.0.8
  net/Legcord/Portfile
Labels: type: bugfix, type: enhancement, type: update, maintainer, maintainer: open

#27446 jdk23: update to 23.0.2
  java/jdk23/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#27447 jdk21: update to 21.0.6
  java/jdk21/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#27448 jdk21-graalvm: update to 21.0.6
  java/jdk21-graalvm/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#27451 openjdk23-corretto: update to 23.0.2
  java/openjdk23-corretto/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#27453 openjdk17-corretto: update to 17.0.14.7.1
  java/openjdk17-corretto/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#27452 openjdk21-corretto: update to 21.0.6.7.1
  java/openjdk21-corretto/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#27454 openjdk11-corretto: update to 11.0.26.4.1
  java/openjdk11-corretto/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#27455 openjdk8-corretto: update to 8.442.06.1
  java/openjdk8-corretto/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#27456 openjdk21-zulu: update 21.40.17
  java/openjdk21-zulu/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#27457 openjdk23-zulu: update to 23.32.11
  java/openjdk23-zulu/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#27458 openjdk17-zulu: update to 17.56.15
  java/openjdk17-zulu/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#27459 openjdk11-zulu: update to 11.78.15
  java/openjdk11-zulu/Portfile
Labels: type: update, maintainer, maintainer: open, by: member

#27460 openjdk8-zulu: update to 8.84.0.15
  java/openjdk8-zulu/Portfile
Labels: type: update, maintainer, maintainer: open, by: member
